### ISSUE TITLE
Less aggressive errors in longPolling transport abort

### ISSUE THREAD

**Issue by remcoros** [SignalR/SignalR#1008]
I'm using the 'error' event to respond to errors and show the user a notification.

```
$.connection.hub.error(this._connectionError);
```

this will show an 'alert' to the user that a connection error has occured.

When using longPolling, and the polling aborts (ie. the user clicks an external hyperlink on the page) this error event is triggered.

It's triggered in:
https://github.com/SignalR/SignalR/blob/master/src/Microsoft.AspNet.SignalR.Client.JS/jquery.signalR.transports.longPolling.js#L127

This creates a kind of weird effect, where the user clicks a link on the page, then signalr fires the error and I show the error alert to the user. This notification is visible for a brief moment, while the clicked page loads.

Currently I work around this, by delaying the show of the notification for 500ms. But this feels dirty.

Can the error detection be optimized to prevent this in some way?

edit:
I now do this:

```
        window.onbeforeunload = function () {
            if ($.connection.hub.pollXhr) {
                $.connection.hub.pollXhr.abort();
            }
        };
```

I found this work around here, describing the issue with $.ajax.error

http://stackoverflow.com/questions/11666421/jquery-ajax-request-abort-in-chrome
http://stackoverflow.com/questions/9397318/detecting-that-a-jquery-ajax-call-failed-because-the-page-is-reloading

edit:
Aborting the xhr was not good, as it stops the polling. 

I created a patch for longPolling transport, see PR.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
