### ISSUE TITLE
Automatically generate TypeScript interfaces

### ISSUE THREAD

**Issue by smithkl42** [SignalR/SignalR#1026]
Right now, SignalR is a bit complicated to use with TypeScript. Among other things, you have to manually generate the interfaces to use with TypeScript code, e.g.

``` typescript
interface SignalR {
    engagementHub: Alanta.Hubs.Engagement.EngagementHub;
}

module Alanta.Hubs.Engagement {
    export interface EngagementHub {
        server: EngagementServer;
        client: EngagementClient;
    }

    // Represents methods that the client can call on the server
    export interface EngagementServer {
        echo(message: string, callback?: (message: string) =>void ): JQueryPromise;

        getAvailableRooms(companyTag: string,
            authenticationGroupTag: string,
            connectionIdentifiers: ConnectionIdentifier[],
            displayOnlyAvailableRooms: bool,
            callback?: (connectionIdentifiers: ConnectionIdentifier[]) =>void ): JQueryPromise;

        getTemplate(templateName: string, callback: (template: string) =>void );
    }

    // Represents methods that the server can call on the client
    export interface EngagementClient {
        onEcho: (sessionId: string, msg: string, message: string) =>void;
    }
}
```

But of course, SignalR already knows everything about these interfaces, as it has to generate the underlying JavaScript for them. Given the general awesomeness of TypeScript, it would be very handy if there was some sort of a switch to get SignalR to generate these interfaces for you.

**Comment by cherrydev** [comment]
I can't seem to find anything on any of the new ASP.NET repositories.  Did this get lost in the shuffle?  Which project should it be part of?  SignalR-Server?  SignalR-Client-JS?

**Comment by RichiCoder1** [comment]
I ran into this recently for our company and went ahead and decided to take @muratg's idea a little farther: https://github.com/RichiCoder1/SignalR.TypeScript/. Supports just about everything I've throw at it, including generating definitions for generics, complex types, as well as generating the TypeScript interface for the "client" portion of a proxy. Will be adding a T4 template package so I can pull it into my own build without the current shenanigans I'm currently pulling. 
(Though my T4 template is pretty straightfoward:)
```t4
<#@ template debug="false" hostspecific="false" language="C#" #>
<#@ assembly name="System.Core" #>
<#@ import namespace="System.Text" #>
<#@ import namespace="System.Reflection" #>
<#@ output extension=".d.ts" #>
<#@ assembly name="$(TargetDir)$(TargetFileName)" #>
<#@ assembly name="$(TargetDir)SignalR.TypeScript.dll" #>
<#@ import namespace="[REDACTED].Hub" #>
<#
    var hubAssembly = typeof(AutoRefreshHub).Assembly;
    var definitionWriter = new DefinitionGenerator(hubAssembly);
#>
<#= definitionWriter.GetTypeDefinitionFile() #>
```

**Comment by IanYates** [comment]
:+1: - Thanks @RichiCoder1 .  I'll check that out.  I've got my own cobbled-together one using a mix of TypeLite (quite modified though) and some T4 template stuff.  It's definitely not in a shape to share and I'd rather see if I could adapt someone else's code to fit my situation and then share back properly anyway.

**Comment by RichiCoder1** [comment]
That was going to be my original approach, so I know your pain haha. Let me know if you need anything or have any ideas, and feel free to file issues or PRs :)

**Comment by cherrydev** [comment]
Since SignalR has been cut from the first release of aspnet5 (or whatever they're calling it this week) this is indefinitely on the back burner for me.
