### ISSUE TITLE
Hub proxy is not generated/registered in /Signalr/Hubs when a custom IAssemblyLocator is registered with the dependency locator

### ISSUE THREAD

**Issue by joshuahayes** [SignalR/SignalR#1032]
When registering a custom IAssemblyLocator after a call to mapHubs() two things occur;
1. Proxy for hub is not registered in /Signalr/Hubs
2. IAssemblyLocator that was registered is never actually called
   
   GlobalHost.DependencyResolver = new NinjectSignalRResolver(Kernel);
   RouteTable.Routes.MapHubs();
   GlobalHost.DependencyResolver.Register(typeof(IAssemblyLocator), () => Kernel.Get`<IAssemblyLocator>`());

_Note as per the wiki extensibility instructions, this code is run in the web activator post application start method. Additionally, `Kernel` refers to my Ninject IOC kernel_

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
