### ISSUE TITLE
Generate signalr/hubs proxy at build to provide Intellisense

### ISSUE THREAD

**Issue by tomsdev** [SignalR/SignalR#106]
Actually, the signalr/hubs proxy is generated at application start time, it would be great (and more productive) if we can do it a build time to have access to .js files so that Intellisense could discover it (by adding ///ReferencePath to our client .js files of course) and provide Intellisense in our client .js file where we call $.connection methods.

**Comment by sajeebchandan** [comment]
To get signalR Intellisence you can add a reference path on which script.js file you are writing scripts for signalR client hub code

`/// <reference path="jquery-3.3.1.js" />`
`/// <reference path="jquery.signalR-2.4.0.js" />`

![image](https://user-images.githubusercontent.com/34353160/49392029-76136c80-f757-11e8-84d0-2b410fa350a6.png)
