### ISSUE TITLE
For hub method return we don't encoding script tag in response for SSE and longPolling transport, but we encoding script tag in response for foreverFrame transport 

### ISSUE THREAD

**Issue by Xiaohongt** [SignalR/SignalR#1064]
Currently we don't encoding script tag in response for hub method return in SSE and longPolling transports, but we encoding script tag in response for hub method return in foreverFrame transport.

We need either encoding script tag in response for hub method return for all transports, or not encoding script tag  in response for hub method return  for all transports.

Note, this is only talking about the response for hub method return

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
