### ISSUE TITLE
/signalr/hubs not found

### ISSUE THREAD

**Issue by zagonth** [SignalR/SignalR#1072]
Hi there,
I've tried all the solutions here in the issues section but none of them worked for me.

Here is what I did:

A part of my web.config:

<pre>
<code>

  &lt;runtime&gt;
    &lt;assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"&gt;
      &lt;dependentAssembly&gt;
        &lt;assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" /&gt;
         &lt;bindingRedirect oldVersion="0.0.0.0-4.0.8.0" newVersion="4.0.8.0" /&gt;
      &lt;/dependentAssembly&gt;
    &lt;/assemblyBinding&gt;
   &lt;/runtime&gt;
   &lt;modules runAllManagedModulesForAllRequests="true"&gt;
       &lt;add name="ImageResizingModule" type="ImageResizer.InterceptModule"/&gt;
    &lt;/modules&gt;
     &lt;validation validateIntegratedModeConfiguration="false"/&gt;
   &lt;/system.webServer&gt;

</code>
</pre>

ChatHub.cs:

<pre>
<code>
[HubName("chatHub")]
public class ChatHub : Hub
{
    public void Send(string message, string userAgent)
    {
        Clients.All.newMessage(message, userAgent);
    }
}
</code>
</pre>

Global.asax: (I've also tried App_Code/App_Start/RegisterHubs.cs method but it never fires)

<pre>
<code>
 void Application_Start(object sender, EventArgs e)
{
    // Code that runs on application startup
    System.Web.Routing.RouteTable.Routes.MapHubs();
}
</code>
</pre>

chat.js

<pre>
<code>
///  &lt;reference path="../jquery-1.8.2.min.js" /&gt;
///  &lt;reference path="jquery.signalR-1.0.0-alpha2.js" /&gt;
$(function () {
    var chat = $.connection.chatHub;
    chat.client.newMessage = (function (data, userAgent) {
        $("#messages").append("&lt;div&gt;" + userAgent + ":      " + data + " &lt;/div&gt;");
    });
    $.connection.hub.start().done(function () {
        $("#sendWall").click(function () {
            var msg = $("#txtMsg").val();
            chat.server.send(msg, 'Can');
        });

        $("#echo").click(function () {
            var msg = $("#msg").val();
            chat.server.echo(msg);
        });
    });
});
</code>
</pre>

And  .aspx:

<pre>
<code>
&lt;script type="text/javascript" src="&lt;%= Page.ResolveClientUrl("~/Js/jquery/jquery-1.8.2.min.js") %&gt;"&gt;&lt;/script&gt;
&lt;script src="&lt;%= Page.ResolveClientUrl("~/Js/jquery/SignalR/jquery.signalR-1.0.0-alpha2.js") %&gt;" type="text/javascript"&gt;&lt;/script&gt;
&lt;script src='&lt;%= Page.ResolveClientUrl("~/signalr/hubs") %&gt;' type='text/javascript'&gt;&lt;/script&gt;
.
.
.
&lt;div id="wall"&gt;
  &lt;textarea id="txtMsg"&gt;&lt;/textarea&gt;
  &lt;input type="button" value="Send" id="sendWall" /&gt;
&lt;/div&gt;
&lt;div id="messages"&gt;
&lt;/div&gt;
</code>
</pre>

I can't figure out what I'm doing wrong or what I'm missing. It keeps saying "chat is undefined".
Just to try I made another simple application with the above setup and it runs perfectly, but on my main project it's not working. I'd be glad if you can help me.
Thanks in advance.

**Comment by sanghreaajit** [comment]
Hi,
Anyone able to make it work.
I m always getting signalr/hubs/login.aspx net::ERR_ABORTED
on localhost

**Comment by zagonth** [comment]
Hi there,
I think, _signalr/hubs/login.aspx_ url is wrong.

You must reference the dynamic proxy like this:
```html
<script src="~/signalr/hubs"></script>});
```

or 

in jquery like:

```javascript
var hubConn = $.hubConnection("http://localhost:<_Your LocalHost Project Port_>/signalr/hubs");
var hub = hubConn .createHubProxy('your hub name in server side');

hubConn .start().done(function () {
   //your logic
});
```

**Comment by sanghreaajit** [comment]
Hi,

Script is added like this only
<script src="~/signalr/hubs"></script>});

But when page loaded in browser console it show signalr/hubs/login.aspx
Seems some authentication issue not able to figure this out

I m using webisite project now converted to webapplication

**Comment by ragar005** [comment]
Add  the following line in Startup Class inside **Configuration Method**:
 `app.MapSignalR("/~/signalr", new HubConfiguration());`
