### ISSUE TITLE
on IE when connection.url is crossdomain and foreverFrame transport specified, connection still start but doesn't work

### ISSUE THREAD

**Issue by Xiaohongt** [SignalR/SignalR#1073]
on IE when connection.url is crossdomain and foreverFrame transport specified, connection still start but doesn't work, it will be better that throw error and not start the connection in this case.

Now in current 1.1 dev branch it will cause many script errors and connection start will fail.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
