### ISSUE TITLE
on client connection.messageId is null when client doesn't receive heart beat/ message from server, then reconnecting is false and reconnect scenarios become broken

### ISSUE THREAD

**Issue by Xiaohongt** [SignalR/SignalR#1078]
when client doesn't receive heart beat/ message from server, client connection.messageId is null, then reconnecting is false and reconnect scenarios become broken.

this is more issue for longPolling, since longPolling never receive heart beat / message from server, then reconnecting is false

e.g.
For longPolling, on client connection start
Don't send any message from server, so on client connection.messageId is null, and reconnecting is false.
Disconnect network, or kill the server process.

then you can see that client doesn't reconnect even though error event raise, since reconnecting is false so poll function still doesn't do reconnect.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
