### ISSUE TITLE
in JS client longPolling when connection.state is not reconnecting, error still could trigger infinite

### ISSUE THREAD

**Issue by Xiaohongt** [SignalR/SignalR#1079]
in longPolling client when connection.state is not reconnecting, error still could trigger infinite. (it only doesn't trigger the error when it is reconnecting).

To repro this, we can have reconnecting = false, and kill the server process, we can see that on client, the error trigger infinite.

Here is the code for error:

```
                    error: function (data, textStatus) {
                        if (textStatus === "abort") {
                            connection.log("Aborted xhr requst.");
                            return;
                        }

                        if (connection.state !== signalR.connectionState.reconnecting) {
                            connection.log("An error occurred using longPolling. Status = " + textStatus + ". " + data.responseText);
                            $(instance).triggerHandler(events.onError, [data.responseText]);
                        }

                        // If the request failed then we clear the timeout so that the
                        // reconnect event doesn't get fired
                        window.clearTimeout(reconnectTimeOut);

                        window.setTimeout(function () {
                            if (isDisconnecting(instance) === false) {
                                poll(instance, true);
                            }
                        }, connection.reconnectDelay);
                    }
```

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
