### ISSUE TITLE
Hub working in Azure (cloud services) but not in an Azure VM

### ISSUE THREAD

**Issue by samillar** [SignalR/SignalR#1123]
I am not sure if this is an Azure VM-specific question or just a more general question about why the /signalr/hubs HTTP request sometimes gets an 'incomplete' response.

We have an MVC4 app running with SignalR and have a single hub set up.  This all works great in our local IISExpress setup and also works when deployed to Azure via cloud services (single instance).  However, it all fails on an Azure VM.  I was hoping for some hints as to how to debug this.

In the scenarios when all is well the /signalr/hubs file has the following lines of code in the response:

signalR.serverHub.client = { };
signalR.serverHub.server = {
    // functions deleted for clatirty
    };

In the Azure VM failed scenario the /signalr/hubs response is identical to the successful scenarios _except_ that it is missing the lines above.

Is there a known issue with Azure VMs and if not then is there any way to debug why the hubs file is not getting correctly generated?

**Comment by fd98279** [comment]
Hello,

I'm facing similar issue, could you let me know which Azure SDK should be installed on the Azure Windows VM?

I'm calling SignalR hub method from Chrome. The connection is successful but the Server hub method invocation just hangs

[18:20:04 GMT-0500 (Eastern Standard Time)] SignalR: Auto detected cross domain url.
app.all.min.js:1172 [18:20:04 GMT-0500 (Eastern Standard Time)] SignalR: Client subscribed to hub 'analytics'.
app.all.min.js:1172 [18:20:04 GMT-0500 (Eastern Standard Time)] SignalR: Negotiating with 'https://XXXXX//signalr//negotiate?clientProtocol=1.5&access…BKsEzrFcuW1pD1-vuA&connectionData=%5B%7B%22name%22%3A%22analytics%22%7D%5D'.
app.all.min.js:1172 [18:20:04 GMT-0500 (Eastern Standard Time)] SignalR: webSockets transport starting.
app.all.min.js:1172 [18:20:04 GMT-0500 (Eastern Standard Time)] SignalR: Connecting to websocket endpoint 'wss://XXXXX/signalr/connect?transport=webSockets&clientProt…HSQYibQY0xi1&connectionData=%5B%7B%22name%22%3A%22analytics%22%7D%5D&tid=3'.
app.all.min.js:1172 [18:20:04 GMT-0500 (Eastern Standard Time)] SignalR: Websocket opened.
app.all.min.js:1172 [18:20:04 GMT-0500 (Eastern Standard Time)] SignalR: webSockets transport connected. Initiating start request.
app.all.min.js:1172 [18:20:05 GMT-0500 (Eastern Standard Time)] SignalR: The start request succeeded. Transitioning to the connected state.
app.all.min.js:1172 [18:20:05 GMT-0500 (Eastern Standard Time)] SignalR: Now monitoring keep alive with a warning timeout of 13333.333333333332, keep alive timeout of 20000 and disconnecting timeout of 30000
[18:20:05 GMT-0500 (Eastern Standard Time)] SignalR: Invoking analytics.getStatsSr  <--This call just hangs. I tried the same code in IIS Express and everything works fine. 

I'm not sure if the browser is even calling the Server side Hub Method. 
Don't see any network activity in the Network tab.

**Comment by fd98279** [comment]
This is not an issue with SignalR. 

I enabled SignalR tracing: https://docs.microsoft.com/en-us/aspnet/signalr/overview/testing-and-debugging/enabling-signalr-tracing

The hub class fails to invoke due to failed DLL dependency.
