### ISSUE TITLE
Calling connection.start() in JS client inside of the disconnect handler does not work.

### ISSUE THREAD

**Issue by mahmoudm** [SignalR/SignalR#1147]
Since the disconnected state is set after the on disconnected handler is fired, calling start() inside the handler will short circuit because it doesn't have the updated state yet.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
