### ISSUE TITLE
Can't get OnConnected() and OnDisconnected() to fire

### ISSUE THREAD

**Issue by smithkl42** [SignalR/SignalR#1170]
I've got a pretty simple demo app using RC1 in which I can't get the `Hub.OnConnected()` and `Hub.OnDisconnected()` overrides to fire. 

The full app is up on BitBucket:

https://bitbucket.org/smithkl42/signalr.webrtc

The specific Hub I'm having difficulty with is here:

https://bitbucket.org/smithkl42/signalr.webrtc/src/bc56ba42990cda3025155990b096d6ec8a3fbd53/SignalR.WebRTC/Hubs/RoomHub.cs?at=default

```
public override Task OnConnected()
{
    Debug.WriteLine("Connecting: " + Context.ConnectionId);
    return base.OnConnected();
}

public override Task OnDisconnected()
{
    try
    {
        Guid sessionId;
        if (connectionToSession.TryGetValue(Context.ConnectionId, out sessionId))
        {
            LeaveRoom(sessionId);
        }
    }
    catch (Exception ex)
    {
        Debug.WriteLine("Error processing OnDisconnected() event: " + ex);
    }
    return base.OnDisconnected();
}
```

The hub methods get called correctly, but neither the `OnConnected()` nor `OnDisconnected()` overrides fire.

Is there something obvious that I'm doing wrong? Or is this a SignalR bug?

**Comment by shwetayadkikar** [comment]
I am using SignalR 2.2.0 and have same issue as @vkelman

**Comment by mtwarowski** [comment]
I confirm the issue is still there.

**Comment by zalayeto** [comment]
I'm having the same issue, signalR 2.2.0. 
The client connects, methods get called, but OnConnected,OnDisconnected doesn't trigger.

**Comment by zalayeto** [comment]
In case it can be helpful for someone. In my case it was related to the fact that I'm using an IoC container, unity. For some reason, even my constructor with one parameter was always successfully called and the hub was created, the events weren't registered. 

Once, I registered a specific container for SignalR in Unity, the events are registered perfectly.

**Comment by hstorc** [comment]
@zalayeto can you explain which container you used for SignalR?
