### ISSUE TITLE
Return helpful error if client code targets wrong SignalR Hub proxy generation endpoint

### ISSUE THREAD

**Issue by rustd** [SignalR/SignalR#1181]
I had an incorrect script reference to:

```
<script src="/signalr/hub"></script>
```

Notice the missing 's' for "hub". This generated an HTTP 500 from the server. If I make the request directly in the browser, I get:

[InvalidOperationException: Protocol error: Unknown transport.]

Could we somehow provide a helpful error message here indicating the user has simply made a mistake in their script reference?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
