### ISSUE TITLE
maximum message size

### ISSUE THREAD

**Issue by ionelmoisuc** [SignalR/SignalR#1205]
Hello

What is the maximum message size that SignalR is meant to handle?

If client A sends a message split in chunks (a few messages) to a server and the server resends all those messages to client B, will client B receive messages in the same order as they were sent by client A ?

Thanks

**Comment by Torvin** [comment]
@mookid8000 I think what you are seeing is a [WebSocket size limit](https://github.com/SignalR/SignalR/issues/2723).

**Comment by fabiobenavides** [comment]
Any way to measure the message size? we tried that but it is not working:
https://stackoverflow.com/questions/51865925/monitoring-signalr-message-sizes

Thank you!

**Comment by anurse** [comment]
How have you configured your custom MessageBus? It's possible it's not properly registered and thus not being called.
