### ISSUE TITLE
JS client hubProxy.off( eventName) can't remove the event anymore after hubProxy.off( eventName, handler) called

### ISSUE THREAD

**Issue by Xiaohongt** [SignalR/SignalR#1259]
e.g. for below sample ( it doesn't matter what hub),   on client the handle on foo2 still is not removed:

``` javascript
myHub.on('foo2', handler);
myHub.on('foo2', handler);
myHub.on('foo2', handler);
myHub.off('foo2', handler);
myHub.off("foo2");   // the first time call here works 
myHub.on('foo2', handler);
myHub.on('foo2', handler);
myHub.on('foo2', handler);
myHub.off('foo2', handler);
myHub.off("foo2");   // not work anymore, if call it again again,still not wotk
```

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
