### ISSUE TITLE
Null reference exception when invoking client member on unexisting group

### ISSUE THREAD

**Issue by yvesgoeleven** [SignalR/SignalR#1264]
Hi,

whenever I invoke a method on an unexisting group in a hub, it throws a nullreference.

var group = Clients.Group("doesnotexist");
if(group != null) group.myMethod() ; <-- still throws a null reference exception

Is there a way to check if the group exists? Or could you treat it as if there were no subscribers to the group?

Thanks,
Yves

**Comment by detaybey** [comment]
Why can't we access the list of Groups ? I want to see if I already added a particular object in the group or not. The examples you provided only let us Groups.Add or Groups.Remove and do the persistence of the items in Groups via database. The Groups item list must be accessible to developers.
