### ISSUE TITLE
JS client webSockets transport doesn't raise error event when OnReceivedAsync throw in PersistentConnection

### ISSUE THREAD

**Issue by Xiaohongt** [SignalR/SignalR#1266]
e.g. in PersistentConnection

```
        protected override Task OnReceivedAsync(IRequest request, string connectionId, string data)
        {
            throw new Exception("error ");
       }
```

in this case JS client webSockets transport doesn't raise error event , it doesn't handle socket.onerror event, if we add it we can support raise error event in this case.

Note, SSE, foreverFrame and longPolling transports raise error event in this case.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
