### ISSUE TITLE
race issue can cause that Websocket connection never be removed in heartbeat on server after the client loses internet connection and become disconnected 

### ISSUE THREAD

**Issue by Xiaohongt** [SignalR/SignalR#1272]
We saw a race issue in OwinWebSocketHandler.ProcessRequestAsync that handler.End() got called before handler.ProcessWebSocketRequestAsync() completed.

Easyway to see the repro:
1. in app, set GlobalHost.Configuration.KeepAlive = 0;
2. request JS webSockets transport client on remote machine and start connection
3. disconnect network
4. debug the code on server

we can see that in OwinWebSocketHandler.ProcessRequestAsync that handler.End() get called before handler.ProcessWebSocketRequestAsync() complete, _raiseEvent become false, socket.OnClose doesn't get called, and Websocket connection IsAlive is still true.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
