### ISSUE TITLE
on remote JS client foreverFrame transport doesn't raise reconnect event after server reset when Configuration.KeepAlive = 0

### ISSUE THREAD

**Issue by Xiaohongt** [SignalR/SignalR#1275]
Repro :
1. in AspNet Sample  set GlobalHost.Configuration.KeepAlive = 0
2. map the AspNet Sample to IIS website, and build the web site
3. on remote machine JS client use foreverFrame transport to request the IIS website Raw/default.aspx
4. run iisreset on host machine

on remote client machine, you can that foreverFrame transport never raise reconnect event, the connection still connected, it can send message, but can't receive message

Note, on local JS client foreverFrame transport it doesn't repro, only repro on remote machine

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
