### ISSUE TITLE
Could not load file or assembly 'Microsoft.Owin.Host.SystemWeb

### ISSUE THREAD

**Issue by hahndorf** [SignalR/SignalR#1304]
After I integrated SignalR into my dev web projects and all worked well, I started (manually) deploying the changes to the staging server. I got the dreaded: 

> Could not load file or assembly 'Microsoft.Owin.Host.SystemWeb, Version=0.10.0.0, >Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located >assembly's manifest definition does not match the assembly reference. (Exception from >HRESULT: 0x80131040)

I did have all the assemblies there and also added the AssemblyBinding - bindingRedirect for Microsoft.Owin.Host.SystemWeb, but still got the error above.

I was able to reproduce this locally by using the web.config from the staging server. After swapping out various sections, I found the culprit. The old web.config from the staging server had the following root node:

```
<configuration xmlns="http://schemas.microsoft.com/.NetConfiguration/v2.0">
```

After removing the xmlns attribute everything worked fine.

So this issue can be closed right away, I just wanted it to be documented just in case someone else has the same problem.

**Comment by otmopo3** [comment]
Had the same error. Seem to solve it with adding application manifest with requiring elevated priveleges.
