### ISSUE TITLE
JS client PersistentConnection can't reconnect when route url ends with "/"

### ISSUE THREAD

**Issue by Xiaohongt** [SignalR/SignalR#1319]
for PersistentConnection, when route url ends with "/",
e.g. 

```
RouteTable.Routes.MapConnection<RawConnection>("raw-connection", "raw-connection/");
```

in JS client, 

``` javascript
var connection = $.connection("../raw-connection/");
```

Use webSockets, SSE or foreverFrame transport, stop and restart server process to make client reconnect.
On client the reconnect url doesn't include "/" for the route url, some like below:
http://localhost:40476/raw-connection?transport=webSockets.....

it returns error:
HTTP Error 404.0 - Not Found
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

when use longPolling transport, the poll url has the same issue, url some like:
http://localhost:40476/raw-connection?transport=longPolling&connectionId=9aee5c45-ac2a-44c8-ab56-785422170081....

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
