### ISSUE TITLE
signalR not diffrentiating sub domains

### ISSUE THREAD

**Issue by niravpatel** [SignalR/SignalR#1338]
Hi,
I am using signalR and using sub domains, each sub domain accessing the same code, when I am pushing some data by using any of my one sub domain then it automatically display the pushed data to all sub domain.

How can we restrict signalR and its hub according to sub domain wise?

**Comment by nibavsyed** [comment]
Hi,
I am using signalR and using sub domains, each sub domain accessing the same code, when I am pushing some chat data by using any of my one sub domain then it is not automatically display the pushed data to all sub domain.it is pushed chat data between same domain only.and also i could not see all the connected users in one sub domain to other subdomain,but it is showing all the connected users in same domain.connection id is creating new if i will traverse from one sub domain to another sub domain pages.

How can we retain a single  signalR connection and its hub according to sub domain wise?

**Comment by nibavsyed** [comment]
classified.syed.com can chat classified.syed.com , but i can't able to chat between syed.com and jobs.syed.com or classified.syed.com and jobs.syed.com, can any one please help me to solve this problem?

**Comment by nibavsyed** [comment]
I am using SignalR 2.2.0 version

**Comment by niravpatel** [comment]
you should use web methods with cross platform topology, for that CORS dll
are there, include it with NUget and then try

**Comment by nibavsyed** [comment]
yes i used CORS already

**Comment by nibavsyed** [comment]
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.Threading.Tasks;
using Microsoft.Owin;
using Owin;



using Microsoft.AspNet.SignalR;
using Microsoft.Owin.Cors;





[assembly: OwinStartup(typeof(Gofabby.Startup))]

namespace Gofabby
{
    public class Startup
    {

        public void Configuration(IAppBuilder app)
        {
           // app.MapSignalR();




            // Branch the pipeline here for requests that start with "/signalr"
            app.Map("/signalr", map =>
            {
                // Setup the CORS middleware to run before SignalR.
                // By default this will allow all origins. You can 
                // configure the set of origins and/or http verbs by
                // providing a cors options with a different policy.
                map.UseCors(CorsOptions.AllowAll);
                var hubConfiguration = new HubConfiguration
                {
                    // You can enable JSONP by uncommenting line below.
                    // JSONP requests are insecure but some older browsers (and some
                    // versions of IE) require JSONP to work cross domain
                    EnableJSONP = true
                };
                // Run the SignalR pipeline. We're not using MapSignalR
                // since this branch already runs under the "/signalr"
                // path.
                map.RunSignalR(hubConfiguration);
            });


        }

        

    }
}

**Comment by nibavsyed** [comment]
$(function () {



             var chatHub = $.connection.notificationsHub;
             $.connection.hub.url = "/signalr";
             //chatHub.url = "http://syed.com/signalr/hubs";
             //chatHub.url = $("#hdnCompanyUrl").val() + "/signalr";
             //$.connection.hub.url = $("#hdnCompanyUrl").val() + "/signalr";
             //$.connection.hub.url = 'syed.com';

             //$.connection.hub.qs = { 'version': '1.0' };

             // Create a function that the hub can call back to display messages.
             chatHub.client.updateUsersOnlineCount = function (count) {

                 $('#hduserCount').html(count);
                 // Add the message to the page. 
                 $('#userCount').text(count);
             };


            

             //var sid; syed
             //sid = document.getElementById("HiddenFieldSessionID");syed

             // Declare a proxy to reference the hub. 
             //var chatHub = $.connection.chatHub;


             //chatHub.client.displayNotification = function (msg, usr,pdate,chatid) {
             // $("#divMessage").html(usr + "::" + msg + "::" + pdate + "::" + chatid);

             //}; syed

             registerClientMethods(chatHub);
            
             // Start Hub
             //$.connection.hub.start({ waitForPageLoad: false }).done(function () {
             //$.connection.hub.start({ transport: 'auto' }).done(function () {


             //var chatsts = $('#hdChatSession').val();
             //if (chatsts != 1){
             //    $.connection.hub.start({ transport: 'auto' }).done(function () {
             //        setScreen(false);
             //        registerEvents(chatHub)

             //    });}


             $.connection.hub.start().done(function () {

                 registerEvents(chatHub)

             });


             if (document.getElementById("hdChatSession").value != 1) {
                 setScreen(false);
             }
             else {
                 setScreen(true);
                 //window.location.assign("login.aspx");


             }


         });

**Comment by nibavsyed** [comment]
autorefresh = $.connection.AutoRefresh; hai in this righthand  end AutoRefresh is hub class file name 
 right?

**Comment by nibavsyed** [comment]
var chatHub = $.connection.notificationsHub;
i am using autorefresh is chatHub,AutoRefresh is notificationsHub am i correct niravpatel?

**Comment by nibavsyed** [comment]
hai niravpatel ru there?
any idea?

**Comment by niravpatel** [comment]
I have created hub for chat users and as per the setting cub domain works
properly

**Comment by nibavsyed** [comment]
at last i found solutions , thanks , i made mistakes   
<script src='<%=ResolveClientUrl("~/media/js/jquery-1.11.2.min.js") %>' type="text/javascript"></script>    <script src='<%=ResolveClientUrl("~/Scripts/jquery.signalR-2.2.0.min.js") %>' type="text/javascript"></script>
    <script src='<%=ResolveClientUrl("~/signalr/hubs") %>' type="text/javascript"></script>

instead of 2.2.0 i used previously 2.1.0 , i changed above js script reference it is working fine

**Comment by nibavsyed** [comment]
Install-Package Microsoft.Owin.Cors ( now it will install signalR 2.2.0)

**Comment by nibavsyed** [comment]
$.connection.hub.url = "http://domain.com/signalr";
// Start Hub
             $.connection.hub.start({ waitForPageLoad: false }).done(function () {

                 registerEvents(chatHub)

             });
