### ISSUE TITLE
Platform coverage for running .NET clients functional automation

### ISSUE THREAD

**Issue by rustd** [SignalR/SignalR#1357]
Issue:
We are running the .NET client functional tests on v4.5 platforms only. We need to run them on the following configurations in an automated manner

We can triage these and add only that matter

Windows 8 (x86/x64) (.NET v4.5)
Windows 7 (x86/x64) (.NET v4.0)
Windows 7 (x86/x64) (.NET v4.5)
Windows Vista (x86/x64) (.NET v4.0)
Windows Vista (x86/x64) (.NET v4.5)

I am listing the following but we can leave them until some one opens a bug
Windows XP (.NET v4.0)
Windows ME (.NET v4.0)
Windows 2003 (.NET v4.0)

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
