### ISSUE TITLE
JS client longPolling fails to reconnect after ping succeeds if no messages were received

### ISSUE THREAD

**Issue by Xiaohongt** [SignalR/SignalR#1405]
e.g. for JS client longPolling connection:
1. after connected, client didn't send or receive any message from server except ping,
     the request like below in pending at this step:
     http://localhost/app/signalr/connect?transport=longPolling&connectionToken=.......
2. stop the server process just about 5 seconds and restart the server process
3. client received ping request before reconnect timeout, but reconnect still timeout, here some log:

[17:38:26 PST]: connected => reconnecting 4d634c34-47e0-42ce-bf77-5df40983202a
[17:38:33 PST]: pong received 
[17:38:33 PST] SignalR: Attempting to connect to 'http://localhost/app/signalr/connect?transport=longPolling&connectionToken=...... 
[17:38:56 PST] SignalR: Couldn't reconnect within the configured timeout (30000ms), disconnecting. 
 [17:38:56 PST] SignalR: Aborted xhr requst. 

repro on server:

``` csharp
    public class EchoHub : Hub
    {
        public Task EchoCallback(string message)
        {
            return Clients.Caller.echo(message);
        }

        public string EchoReturn(string message)
        {
            return message;
        }
    }
```

on JS client:

``` javascript
                var myHub = $.connection.echoHub ;
                $.connection.hub.logging = true;

                 echoHub.client.echo = function (value) {
                        console.log("[" + new Date().toTimeString() + "]: echo called: " +  value);
                 };
                var start = function () {
                    $.connection.hub.start({ transport: 'longPolling' })
                        .done(function () {
                             console.log("[" + new Date().toTimeString() + "]: connectioned");
                        });                    
                };
                start();

                $.connection.hub.stateChanged(function (change) {                   
                    var oldState = null,
                        newState = null;
                    for (var p in $.signalR.connectionState) {
                        if ($.signalR.connectionState[p] === change.oldState) {
                            oldState = p;
                        }
                        if ($.signalR.connectionState[p] === change.newState) {
                            newState = p;
                        }
                    }

                    console.log("[" + new Date().toTimeString() + "]:  " + oldState + " => " + newState + " " + $.connection.hub.id);
                });

```

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
