### ISSUE TITLE
iphone safari hangs when starting site if signalr previously active unless cookies deleted

### ISSUE THREAD

**Issue by redware** [SignalR/SignalR#1418]
SignalR may be attemting to reconnect to a previous session when a web page is navigated to but this behaviour will hang safari on an iphone (ipod touch ios6) if a previously active session has been closed. Deleting the cookies for the site fixes this.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
