### ISSUE TITLE
You are able to invoke client side events via a group even if the hub was connected to incorrectly

### ISSUE THREAD

**Issue by msarchet** [SignalR/SignalR#1425]
You can see the code required to reproduce this issue here

https://gist.github.com/4650092

To reproduce the bug paste the Hub.cs file into a new Hub. and paste the index.cshtml file into a cshtml view

Then launch in a browser and open a Javascript Console.
1. Click the Click Me button - nothing should appear in the javascript console.
2. Click the Join Group button - this will join you to the group base
3. Click the Click Me Button - you should see "new messge" logged in your javascript console.

For Debugging Purposes I was running in VS 2012 on Windows 8, running the rc2 build from nuget.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
