### ISSUE TITLE
Route matching for the Owin hub dispatcher handler is too agressive

### ISSUE THREAD

**Issue by DamianEdwards** [SignalR/SignalR#1445]
The HubDispatcherHandler matches any path that starts with the Hub url prefix (~/signalr by default). It should be explicitly matching as it allows arbitrary urls through to the HubDispatcher with the current code.

**Comment by DanielBryars** [comment]
Does the fact this issues is closed mean you have decided to keep the behavior "matches any path that starts with the Hub url prefix  (~/signalr by default)"? Or might you reopen this issue?

As per this question on StackOverflow I would like to take a dependency on this behavior : 

http://stackoverflow.com/questions/37729176/is-the-current-default-signalr-url-routing-behavior-by-design
