### ISSUE TITLE
Cursor parsing logic may expose details of topics in cursor map

### ISSUE THREAD

**Issue by DamianEdwards** [SignalR/SignalR#1447]
Cursor.GetCursors – Potential information disclosure in how cursors are handled when the key maximizer routine results in a miss.  A client can send specially-crafted payloads to probe the active number of topics currently recognized by the minifier.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Comment by SMayer135** [comment]
FYI Sonatype is still flagging this as a vulnerability due to the lack of info provided for it's closing. sonatype-2013-0042
