### ISSUE TITLE
Audit comparer types for all dictionaries

### ISSUE THREAD

**Issue by DamianEdwards** [SignalR/SignalR#1451]
We should ensure that all our comparers for the various dictionaries we use are correct. Currently we have a mix of Ordinal and OrdinalIgnoreCase, which might be fine, just needs verification.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
