### ISSUE TITLE
Hub.Dispose should call GC.SuppressFinalize(this) after call to Dispose

### ISSUE THREAD

**Issue by DamianEdwards** [SignalR/SignalR#1452]
What the title says.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
