### ISSUE TITLE
Fragmentation on the client side with the C# client.

### ISSUE THREAD

**Issue by jcondex** [SignalR/SignalR#1470]
I’m seeing the following on the Client side of my HighClientThreadPoolUse scenario.  This test basically creates 20 \* 100 connections and cycles though them!

In little time, the memory of the process goes up in excess of 1.5 GB and winDbg reports the following:

I have uploaded the dump files (x86) and perf counters here:
\indigofs\commonshare\jconde\SignalR\Bugs\MultipleClients_Fragmentation

```
0:263> !heapstat
Heap             Gen0         Gen1         Gen2          LOH
Heap0       147705848      1719008    515352896       200208

Free space:                                                 Percentage
Heap0        26358048        52032    442079744        33920SOH: 70% LOH: 16%

0:263> !eeheap -gc
Number of GC Heaps: 1
generation 0 starts at 0x000000d23df94ae0
generation 1 starts at 0x000000d23ddf1000
generation 2 starts at 0x000000d267271000
ephemeral segment allocation context: (0x000000d246c71ad8, 0x000000d246c71af0)
segment     begin allocated  size
000000d267270000  000000d267271000  000000d276dcfa38  0xfb5ea38(263580216)
000000d22aa00000  000000d22aa01000  000000d239a1cf08  0xf01bf08(251772680)
000000d23ddf0000  000000d23ddf1000  000000d246c71ad8  0x8e80ad8(149424856)
Large object heap starts at 0x000000d277271000
segment     begin allocated  size
000000d277270000  000000d277271000  000000d2772a1e10  0x30e10(200208)
Total Size:              Size: 0x27a2c228 (664977960) bytes.
------------------------------
GC Heap Size:            Size: 0x27a2c228 (664977960) bytes.

0:272> !gchandles -stat
Statistics:
              MT    Count    TotalSize Class Name
000007fe6ba332e0        1           24 System.Threading.Tasks.ThreadPoolTaskScheduler
000007fe6ba4b558        1           48 System.SharedStatics
000007fe6ba4b4c0        2           48 System.Object
000007fe6aaf0688        1           56 System.Diagnostics.TraceSource
000007fe6ba4c930        1           64 System.Security.PermissionSet
000007fe6aaeda28        1           80 System.Diagnostics.BooleanSwitch
000007fe6baa1a48        1           96 System.Threading.CdsSyncEtwBCLProvider
000007fe6ba44fc8        1           96 System.Diagnostics.Tracing.FrameworkEventSource
000007fe6ba378b8        1           96 System.Collections.Concurrent.CDSCollectionETWBCLProvider
000007fe6ba32988        1           96 System.Threading.Tasks.TplEtwProvider
000007fe6ba2f9e8        1          104 System.Runtime.Remoting.Contexts.Context
000007fe6ba4b3e8        1          160 System.ExecutionEngineException
000007fe6ba4b370        1          160 System.StackOverflowException
000007fe6ba4b2f8        1          160 System.OutOfMemoryException
000007fe6ba4b110        1          160 System.Exception
000007fe6aaf50e0        4          160 System.Net.TimerThread+TimerQueue
000007fe6ab469c8        1          200 System.Net.ServicePoint
000007fe6ba4b618        1          216 System.AppDomain
000007fe6ba45108        4          256 Microsoft.Win32.UnsafeNativeMethods+ManifestEtw+EtwEnableCallback
000007fe6ba4b460        2          320 System.Threading.ThreadAbortException
000007fe0d325d40        2          320 Microsoft.Test.Stress.StressTestHangException
000007fe6aaf52d0        6          336 System.Net.Logging+NclTraceSource
000007fe6aaf5430        7          560 System.Diagnostics.SourceSwitch
000007fe6aaf6e28        4          672 System.Net.Sockets.SocketException
000007fe6ab2f368        8         1344 System.Net.WebSockets.WebSocketException
000007fe6ba55c80       17         2856 System.OperationCanceledException
000007fe6baabb40       42         3024 System.Reflection.Emit.DynamicResolver
000007fe6ba9b928       20         3520 System.Threading.Tasks.TaskCanceledException
000007fe6ba5f5c0       29         4640 System.RuntimeType+RuntimeTypeCache
000007fe6ba4c568      554        53184 System.Threading.Thread
000007fe6ba2f1b8      582       108744 System.Object[]
000007fe6b3c9628     7454       834848 System.Threading.OverlappedData
000007fe6ba4f058     2167     89515275 System.Byte[]
Total 10920 objects

Handles:
    Strong Handles:       915
    Pinned Handles:       2174
    Async Pinned Handles: 7454
    Weak Long Handles:    76
    Weak Short Handles:   300
    Dependent Handles:    1

0:112> !dumpheap -type Free -stat
Statistics:
      MT    Count    TotalSize Class Name
72a665f0        1           20 System.Net.SafeLocalFree
003deeb0    24047   1198986606      Free
Total 24048 objects
Fragmented blocks larger than 0.5 MB:
    Addr     Size      Followed by
1ddefa3c    0.5MB         1de73cbc System.Byte[]
1e18fa14    0.5MB         1e214380 System.Byte[]
1e381eb8    0.5MB         1e4036cc System.Threading.OverlappedData
1eaa4e34    0.7MB         1eb5240c System.Threading.OverlappedData
1ec5a59c    0.6MB         1ece84f8 System.Byte[]
1ecf5000    0.7MB         1edabc04 System.Byte[]
1ef150d0    0.6MB         1efa5c0c System.Threading.OverlappedData
1f2ab728    0.6MB         1f34903c System.Byte[]
1f93a5cc    0.5MB         1f9beda4 System.Byte[]
1fb0876c    0.5MB         1fb92aec System.Net.WebSockets.WebSocketConnectionStream
1fc5d35c    0.8MB         1fd1d4fc System.Byte[]
```

Total committed bytes = 1,463,934,976
The ratio of total commited bytes and Free of !dumpheap -stat is:

1,463,934,976 / 1,198,986,606  = 1.22

**Comment by sandrik** [comment]
Hi Jorge and David,
We upgraded to 2.1.2 version few months ago and now are running stress tests before release.
Once in a while we do observe a memory leak.

The implementation we have is as follows:
1. ASP.NET website acting as communication server.
2. We have internal and external clients connected to it.
3. Internal clients are the data distributors (broadcasting manner)
4. The clients distributing the data are working within a LAN and interacting with the communication server via internal IP or even as localhost (in standalone deployments).
5. The message distribution frequency is done as chunks - every few minutes sending up to 1000 message for each connection while having up to 10 connections.

***Currently we do not have any throttling mechanism and my guess that it is a part of the problem but anyhow i wanted to get an advise from you regarding this memory leak.
Do you have any suggestions how to overcome this?
I have a dump file if necessary and here is a short print from the WinDbg (please look into 00007fff31341b40     4101       459312 System.Threading.OverlappedData).
Our windows service swell in to ~1.2GB while in normal behavior it should be around <= 500MB


0:000> !gchandles -stat
The version of SOS does not match the version of CLR you are debugging.  Please
load the matching version of SOS for the version of CLR you are debugging.
CLR Version: 4.0.30319.34003
SOS Version: 4.0.30319.18052
Statistics:
              MT    Count    TotalSize Class Name
00007fff319cc9f8        1           24 System.Threading.Tasks.ThreadPoolTaskScheduler
00007fff20a8bbf0        1           24 Bid+BindingCookie
00007fff31990330        1           48 System.SharedStatics
00007fff319914c0        1           64 System.Security.PermissionSet
00007fff313ab398        1           64 System.EventHandler`1[[Windows.Foundation.Diagnostics.TracingStatusChangedEventArgs, mscorlib]]
00007fff30a58410        1           64 Microsoft.Win32.NativeMethods+WndProc
00007fff30a58210        1           64 Microsoft.Win32.NativeMethods+ConHndlr
00007fff304d9da8        1           64 System.Runtime.Interop.UnsafeNativeMethods+EtwEnableCallback
00007fff30467af8        1           64 System.ServiceProcess.NativeMethods+ServiceControlCallbackEx
00007fff30467938        1           64 System.ServiceProcess.NativeMethods+ServiceMainCallback
00007fff20a8bb60        1           64 Bid+CtrlCB
00007fff31990220        3           72 System.Object
00007fff31a0d240        1           88 System.Runtime.Remoting.Identity
00007fff319a4db0        3           96 System.Threading.RegisteredWaitHandle
00007fff31a0d7a8        1          104 System.Runtime.Remoting.Contexts.Context
00007fff31a0be28        3          120 System.Threading._ThreadPoolWaitOrTimerCallback
00007fff20a951b0        2          128 SNINativeMethodWrapper+SqlAsyncCallbackDelegate
00007fff319a6728        3          144 System.Threading.AutoResetEvent
00007fff31a11aa8        1          160 System.Collections.Concurrent.CDSCollectionETWBCLProvider
00007fff319fd690        1          160 System.Threading.CdsSyncEtwBCLProvider
00007fff319cbe98        1          160 System.Threading.Tasks.TplEtwProvider
00007fff319b2ea0        1          160 System.Diagnostics.Tracing.FrameworkEventSource
00007fff31990148        1          160 System.ExecutionEngineException
00007fff319900d0        1          160 System.StackOverflowException
00007fff31990058        1          160 System.OutOfMemoryException
00007fff3198fe70        1          160 System.Exception
00007fff30a56020        4          160 System.Net.TimerThread+TimerQueue
00007ffed36f53c8        1          160 System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider
00007fff304d9ab0        3          168 System.Runtime.Diagnostics.DiagnosticTraceSource
00007fff30a9af58        1          200 System.Net.ServicePoint
00007fff319903f0        1          216 System.AppDomain
00007fff30a50978        4          224 System.Diagnostics.TraceSource
00007fff319b3230        5          320 Microsoft.Win32.UnsafeNativeMethods+ManifestEtw+EtwEnableCallback
00007fff319901c0        2          320 System.Threading.ThreadAbortException
00007fff30a56210        6          336 System.Net.Logging+NclTraceSource
00007fff30a46a60        5          400 System.Diagnostics.BooleanSwitch
00007fff20a97620        1          440 System.Data.SqlClient.TdsParserStateObject
00007fff30a56370       13         1040 System.Diagnostics.SourceSwitch
00007fff319bcc30      102         7344 System.Reflection.Emit.DynamicResolver
00007fff319911a8      285        27360 System.Threading.Thread
00007fff319ad9f8      249        39840 System.RuntimeType+RuntimeTypeCache
00007fff319902b8      278       360832 System.Object[]
00007fff31341b40     4101       459312 System.Threading.OverlappedData
Total 5096 objects

Handles:
    Strong Handles:       429
    Pinned Handles:       15
    Async Pinned Handles: 4101
    Ref Count Handles:    1
    Weak Long Handles:    365
    Weak Short Handles:   184
    Dependent Handles:    1

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
