### ISSUE TITLE
ConnectDisconnect scenario causes server to return a 503 Service unavailable error

### ISSUE THREAD

**Issue by jcondex** [SignalR/SignalR#1471]
The ConnectDisconnect scenario is causing the service to return a 503 error.

It seems that we’re hitting the appConcurrentRequestLimit which is defaulted to 5000, so somehow SignalR is not capable of processing the requests fast enough.

As soon as we hit 4,999 concurrent requests the connections start timing out and little after an exception is thrown:

System.Net.WebException: The remote server returned an error: (503) Server Unavailable.

An interesting thing about this scenario is that I use fairly large payloads (random of max 2MB), and for the rest it does pretty common things other than the fact that it Aborts, Disconnects, or Stops the connection while things are happening.

I have copied all the relevant stuff to \\indigofs\commonshare\jconde\SignalR\Bugs\ConnectDisconnect_503

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
