### ISSUE TITLE
Add the ability to send to multiple groups at once from a Hub

### ISSUE THREAD

**Issue by msarchet** [SignalR/SignalR#1475]
Currently I have found that sometimes I was to send the same information to multiple groups.

This can currently be achieved by either looping over the groups you want to send to with something like

`(new List<string>() { "Group1", "Group2"}).ForEach(g => Clients.Groups(g).alert("Danger'));`

However this seems a little clunky.

Would adding a method similar to

```
var groups = new List<string>() { "Group1", "Group2" };
Clients.Groups(groups).alert("Danger");
```

be something that could be a net benefit to the project?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
