### ISSUE TITLE
Microsoft.Aspnet.SIgnalR.Hubs.Hub class reference not found on code behind file C#

### ISSUE THREAD

**Issue by Watraplion** [SignalR/SignalR#1492]
Hi,
  I am new to SignalR library. I was created a new web project in VS2010.
  Then in Package Manager Console i executed the below command to set up the signalR package.

   PM> Install-Package Microsoft.Aspnet.SignalR -pre

  So it downloaded all the necessary files into the application.

---

Successfully installed 'Microsoft.AspNet.SignalR 1.0.0-rc2'.
Successfully added 'jQuery 1.6.4' to demo.
Successfully added 'Microsoft.AspNet.SignalR.JS 1.0.0-rc2' to demo.
Successfully added 'Newtonsoft.Json 4.5.11' to demo.
Successfully added 'Microsoft.AspNet.SignalR.Core 1.0.0-rc2' to demo.
Successfully added 'Owin 1.0' to demo.
Successfully added 'Microsoft.AspNet.SignalR.Owin 1.0.0-rc2' to demo.
Successfully added 'Microsoft.Web.Infrastructure 1.0.0.0' to demo.
Successfully added 'Microsoft.Owin.Host.SystemWeb 1.0.0-rc2' to demo.
Successfully added 'Microsoft.AspNet.SignalR.SystemWeb 1.0.0-rc2' to demo.
Successfully added 'Microsoft.AspNet.SignalR 1.0.0-rc2' to demo.

---

 Now i added a new class file called LetsHub.cs.

 In that file i wrote the following code,

 using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.AspNet.SignalR.Hubs;

namespace demo.Hubs
{
    [HubName("chatHub")]
    public class LetsChat : Hub
    {
        public void SendMsg(string Message)
        {
            Clients.All.addMessage(Message);
        }
    }
}

Here the problem is that, i am not
![SignalR](https://f.cloud.github.com/assets/3490328/130988/9dc95618-7044-11e2-9f54-ae4b13933472.JPG)
 able to inherite this "Hub" class. Hub class not available on this Microsoft.AspNet.SignalR.Hubs; namespace.

I am facing the same problem on VS 2012 also.

Please help me.

Thanks. !

**Comment by haephrati** [comment]
From VS open Tools -> Nuget Package Manager -> Package Manager Console
Then install the missing components using :
`Install-Package <package name>`
For example:
`Install-Package Microsoft.Owin.Security`
