### ISSUE TITLE
Restarting connection while in JS method received context blows up connection (LongPolling)

### ISSUE THREAD

**Issue by NTaylorMullen** [SignalR/SignalR#1529]
This is a hard one to describe so I'll do a code snippet:

``` JavaScript
var foo = $.connection.hub,
    start = function() {
        $.connection.hub.start({transport: "longPolling"}).done(function() {
            // Some method that calls bar, second time around this is what throws
            foo.server.callBar();
        });
    };

foo.client.bar = function() {
    $.connection.hub.stop();
    // Throws "SignalR: Connection must be started before data can be sent. Call .start() before .send()" via jquery.signalR.core.js send method
    start();
};

start();
```

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
