### ISSUE TITLE
Allow to Send Json Strings without duplicate Serialization

### ISSUE THREAD

**Issue by stevozilik** [SignalR/SignalR#1546]
Hi,

Currently even if I have a JSON formatted string that I want to send to clients, SignalR server will still run it through the full serialization process, allocating additional memory. That could be avoided.

Possible solution: 
Move the Stringify method from JsonSerializerExtensions to IJsonSerializer to be able to implement/override the method and return json string already contained in the 'value' parameter, rather than running it through another serialization. 

Motivation: in some scenarios, this can significantly lower memory consumption, since the message content would not duplicate for each sent message. i.e. currently when sending same message to 100 clients, the code would duplicate the content (json string) for reach client separately 100x. Referencing the same content, without serializing it again would greatly decrease the memory allocation per message.

**Comment by Svmali84** [comment]
Hi SignalR Team ,

preserialized json is only supported for PersistentConnect ? I tried passing ArraSegment<byte> but it did not work, SignalR still run serialization.
