### ISSUE TITLE
Turn off Chutzpah debug mode on local machine

### ISSUE THREAD

**Issue by NTaylorMullen** [SignalR/SignalR#1552]
Currently Chutzpah executes our JS unit tests always in debug mode primarily because this is the only output for Test Swarm to detect our JS tests.  However it makes finding failed tests on a local machine nearly impossible.  By disabling the debug mode on local the failed test(s) is/are the only one(s) outputted.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
