### ISSUE TITLE
For JS client longPolling transport, after script error throw from user-defined OnReceived handler, OnReceived event doesn’t raise anymore when new messages are sent to the connection which is a different behavior from other transports behavior 

### ISSUE THREAD

**Issue by Xiaohongt** [SignalR/SignalR#1557]
For JS longPolling transport,  after script error throw from user-defined OnReceived handler, (dismiss the debug popup for the error if script debugging is not disabled), OnReceived event doesn’t raise anymore when new messages are sent to the connection, but the connection is still connected, and it also can send messages. 

However for webSockets, serverSentEvents and foreverFrame transports,  after script error throw from user-defined OnReceived handlers, (dismiss the debug popup for the error if script debugging is not disabled),  OnReceived event still work and get raised when new messages are sent to the connection, and log the script error if it happens again.

In jquery.signalR.transports.longPolling.js, seems we can just call processMessages after poll? ( also need more update for data.Disconnect with this one)

``` javascript
instance.pollXhr = $.ajax({
    url: url,
    global: false,
    cache: false,
    type: "GET",
    dataType: connection.ajaxDataType,
    success: function (minData) {
        var delay = 0,
            data;

        fireConnect();

        if (minData) {
            data = transportLogic.maximizePersistentResponse(minData);
        }


        if (data &&
            $.type(data.LongPollDelay) === "number") {
            delay = data.LongPollDelay;
        }

        if (data && data.Disconnect) {
            return;
        }

        if (isDisconnecting(instance) === true) {
            return;
        }

        // We never want to pass a raiseReconnect flag after a successful poll.  This is handled via the error function
        if (delay > 0) {
            window.setTimeout(function () {
                poll(instance, false);
            }, delay);
        } else {
            poll(instance, false);
        }

        transportLogic.processMessages(instance, minData);

    },

    error: function (data, textStatus) {
        if (textStatus === "abort") {
            connection.log("Aborted xhr requst.");
            return;
        }

        if (connection.state !== signalR.connectionState.reconnecting) {
            connection.log("An error occurred using longPolling. Status = " + textStatus + ". " + data.responseText);
            $(instance).triggerHandler(events.onError, [data.responseText]);
        }

        // Transition into the reconnecting state
        transportLogic.ensureReconnectingState(instance);

        // If we've errored out we need to verify that the server is still there, so re-start initialization process
        // This will ping the server until it successfully gets a response.
        that.init(instance, function () {
            // Call poll with the raiseReconnect flag as true
            poll(instance, true);
        });
    }
});

```

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
