### ISSUE TITLE
CreateHubProxy won't return existing proxy if connected

### ISSUE THREAD

**Issue by jwynveen** [SignalR/SignalR#1559]
When using hubConnection.CreateHubProxy("user") with an existing connection that has already been started, it throws an error that you can't add a proxy after a connection has been started. That is fine, but the proxy already exists in the connection and I just want to access that proxy.

Looking at the source for CreateHubProxy, it looks like that check should get moved within the if instead of being at the start of the method.

```
    public IHubProxy CreateHubProxy(string hubName)
    {
      if (this.State != ConnectionState.Disconnected)
        throw new InvalidOperationException(string.Format((IFormatProvider) CultureInfo.CurrentCulture, Resources.Error_ProxiesCannotBeAddedConnectionStarted, new object[0]));
      HubProxy hubProxy;
      if (!this._hubs.TryGetValue(hubName, out hubProxy))
      {
        hubProxy = new HubProxy((IHubConnection) this, hubName);
        this._hubs[hubName] = hubProxy;
      }
      return (IHubProxy) hubProxy;
    }
```

Once you move that exception to only be throw inside the if, it will only be thrown if the proxy doesn't already exist.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
