### ISSUE TITLE
.Net client longPolling transport transitions into reconecting on poll.

### ISSUE THREAD

**Issue by Xiaohongt** [SignalR/SignalR#1576]
Polling should try and re-establish its connection with the server after timeout without going into the reconnecting state.  The JavaScript client has the correct behavior.

e.g. just run the repro, once the long polling transport times out it transitions into reconnecting to keep the connection alive.

This occurs with generic behavior, no network issues, and does not require any errors thrown on server side or client.

``` csharp
    //use the asp.net sample url
    var hubConnection = new HubConnection("http://localhost:40476/");  
    var chat = hubConnection.CreateHubProxy("chat");

    hubConnection.StateChanged += stateChange =>
    {
        Console.WriteLine("[" + DateTime.Now + "]: " + stateChange.OldState + " =>  " + stateChange.NewState);
    };

    hubConnection.Closed += () =>
    {
        Console.WriteLine("[" + DateTime.Now + "]: Connection Closed");
    };

    hubConnection.Reconnecting += () =>
    {
        Console.WriteLine("[" + DateTime.Now + "]: Connection Reconnecting");
    };

    hubConnection.Reconnected += () =>
    {
        Console.WriteLine("[" + DateTime.Now + "]: Connection re-established");
    };

    hubConnection.Error += Exception =>
    {
        Console.WriteLine("[" + DateTime.Now + "]: Error occurred ");
    };

    hubConnection.Start(new Microsoft.AspNet.SignalR.Client.Transports.LongPollingTransport()).Wait();

    Console.WriteLine("Url " + hubConnection.Url);
    Console.WriteLine("Transport name: " + hubConnection.Transport.Name);
    Console.WriteLine("ConnectionId: " + hubConnection.ConnectionId);

    chat.Invoke("join");

    string line = null;
    while ((line = Console.ReadLine()) != null)
    {

    }

```

Results like:

[2/22/2013 5:44:04 PM]: Disconnected =>  Connecting
[2/22/2013 5:44:07 PM]: Connecting =>  Connected
Url http://localhost:40476/signalr/
Transport name: longPolling
ConnectionId: a6628260-1edc-4b62-885f-33d8e9b69658
[2/22/2013 5:45:55 PM]: Connected =>  Reconnecting
[2/22/2013 5:45:55 PM]: Connection Reconnecting
[2/22/2013 5:46:00 PM]: Reconnecting =>  Connected
[2/22/2013 5:46:00 PM]: Connection re-established
[2/22/2013 5:47:45 PM]: Connected =>  Reconnecting
[2/22/2013 5:47:45 PM]: Connection Reconnecting
[2/22/2013 5:47:50 PM]: Reconnecting =>  Connected
[2/22/2013 5:47:50 PM]: Connection re-established
[2/22/2013 5:49:36 PM]: Connected =>  Reconnecting
[2/22/2013 5:49:36 PM]: Connection Reconnecting
[2/22/2013 5:49:41 PM]: Reconnecting =>  Connected
[2/22/2013 5:49:41 PM]: Connection re-established
.....

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
