### ISSUE TITLE
.Net client Connection(string url, IDictionary<string, string> queryString) doesn't encode parameter queryString

### ISSUE THREAD

**Issue by Xiaohongt** [SignalR/SignalR#1580]
e.g. for .Net client:

``` csharp
Dictionary<string, string> qs = new Dictionary<string, string>();
qs.Add("q=", "111");
//use the asp.net sample url
var conn = new Connection("http://localhost:40476/", qs);
```

It appends qs for negotiate url just like:
 /negotiate?q==111&_=1361617352953

queryString key for "q=" becomes "q", the value for "111" becomes "=111"

Note, e.g. JS client $.connection("http://localhost:40476/", {"q=": "111"} ) does encode the parameter for queryString

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
