### ISSUE TITLE
JS client $.connection(url, qs) with qs parameter value like "?q=aaa" causes connectionToken incorrect format

### ISSUE THREAD

**Issue by Xiaohongt** [SignalR/SignalR#1584]
e.g.  var connection = $.connection("../raw-connection", "?q=aaa");

then request url has "?q=aaa" instead of "&q=aaa",  which causes connectionToken incorrect format:

http://localhost:55735/raw-connection/connect?transport=foreverFrame&connectionToken=TYeiuEXUqN04ZP8ZhK9fXtLdEs64NzhwCfeKWqYXK9Ybo2ktCqZYOIuTrb8nj1ZLdsVQJxQbUWehfyLtBnLQfjQyRV8V35XaIrCcMqxjez4HEuH4vsBusCTYJcxKRMoq0?q=aaa&tid=2&frameId=1

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
