### ISSUE TITLE
Use window.setImmediate instead of window.setTimeout for scheduling JS to run after yielding the current execution stack

### ISSUE THREAD

**Issue by DamianEdwards** [SignalR/SignalR#1598]
window.setImmediate allows us to schedule JS to run but only after yielding the current work on the loop (updating UI, callbacks, etc.). IE10 and Mozilla supports it now, and we can easily shim in a window.setImmediate in browsers that don't have it but calling setTimeout(0)

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
