### ISSUE TITLE
[ServerSentEvents] .NET connection.Error raises System.Net.Sockets.SocketException A blocking operation was interrupted by a call to WSACancelBlockingCall

### ISSUE THREAD

**Issue by jcondex** [SignalR/SignalR#1609]
I'm seeing an SocketException being raised in connection.Error when a connection is stopped or disconnected using ServerSentEvents.

I have uploaded a repro here:
\indigofs\CommonShare\jconde\SignalR\Bugs\1609

To repro, deploy the hub (bin/www) and invoke the client like this:

SignalR.Stress.AbortStopOrDisconnect.exe /huburl:http://localhost/SignalR.Stress.AbortStopOrDisconnect /TransportNames:ServerSentEventsTransport /AbortStopDisconnect:stop /threads:1

We should swallow this when stop/disconnect/abort is invoked in a connection and keep it from firing the connection.Error event.

Here is the exception stack:

```
System.Net.Sockets.SocketException (0x80004005): A blocking operation was interrupted by a call to WSACancelBlockingCall
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
```

Log traces:

```
StressTestLogger Information: 5 : RunVariation : [15:59:00] Invoked stop on connectionId:606bf6c4-d630-402d-94f7-9789a77
36f15.
StressTestLogger Critical: 44 : [15:59:00] Error - ConnectionId:606bf6c4-d630-402d-94f7-9789a7736f15 ConnectionToken:oem
SZokgozAXONDT83qhMPWqj6CWkzN2ihWhtev6WuR_pN4kHnWSRxSV9fRgDoqZwQiB0m23I-i3lBAYAamMrFnvU31B3Ovu_Ufwq4sU481FUgrs4H5yMnHYSpD
72o1w0
StressTestLogger Critical: 44 : [15:59:00] System.Net.Sockets.SocketException (0x80004005): A blocking operation was int
errupted by a call to WSACancelBlockingCall
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
```

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
