### ISSUE TITLE
Single connection throughput error: Unable to read data from the transport connection

### ISSUE THREAD

**Issue by allymparker** [SignalR/SignalR#1612]
We are trying to use SignalR out of the web context as a publish/subscribe mechanism for real time ticking market data from within Excel.

When a user opens a sheet, a custom Excel RTD addin (the signal R client) subscribes to all market data streams in the cells on the server (the signalR hub; Currently a Windows Service).

After implementing SignalR we found that not all requests were getting from the client to the hub in our example sheet (around 2000 requests).

_System.Net.WebException: The underlying connection was closed: A connection that was expected to be kept alive was closed by the server. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host_

This example is an oversimplification of the issue but seems to consistently reproduce the error.  This error also seems to occur on broadcast back to the clients.

https://github.com/ConspiringWithTheDamned/SignalR_Throughput_Errors.git

It feels like I'm doing something fundamentally wrong - does anyone have any input on this issue?

Thanks.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
