### ISSUE TITLE
SignalR.Utils signalr.exe hub script generation doesn't support x86 dlls

### ISSUE THREAD

**Issue by tombull** [SignalR/SignalR#1627]
If you compile a site in x86 format and then run "signalr.exe ghp" against it to generate hub scripts, then you get:
System.BadImageFormatException: Could not load file or assembly 'X' or one of its dependencies. An attempt was made to load a program with an incorrect format. 

Note I'm working with the NuGet version of Microsoft.AspNet.SignalR.Utils.1.0.1. Why would anyone use x86? Er, edit and continue still only supports x86.

**Comment by planty** [comment]
I realise this is quite an old issue, but I've encountered the same problem with SignalR 2.2.1. Is there a solution to supporting x86 dlls?

**Comment by moozzyk** [comment]
I think you could use [corflags](https://msdn.microsoft.com/en-us/library/ms164699(v=vs.110).aspx) with /32BIT+ setting to force signalr.exe start as a 32-bit process on a 64-bit machine.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
