### ISSUE TITLE
Issues with large message sizes

### ISSUE THREAD

**Issue by DaveSussman** [SignalR/SignalR#163]
This is a query really, about processing large messages and what the recommendations might be regarding size limits and / or handling a large amount of data.

In my current app I have one call that can return one of two sets of data, depending upon a filter passed in. The data is a list of custom objects, populated from a database, and serialized via the Newtonsoft json serializer. In one case the data is 17k, which is fine; the other case gives a serialized string on 197k, which isn't fine, and fails with an unexpected error of:

  System.UriFormatException: Invalid URI: The URI string is too long

I'm using Win7 so the request limit should be big enough.

I'm curious to what my options are. Is there some config I can do, or is my only limit to chunk my data? In an ideal world I'd transport the data in chunks, but my use of SignalR was a drop in replacement for Laharsub, which didn't give me any issues.

Version: 0.3.6 (client - console app) & 0.3.5 (Server - MVC3 on Win7).

**Comment by BrannonKing** [comment]
Just got the "The Uri string is too long" in 2.1.2 with a message length of 86243 bytes.

**Comment by BrannonKing** [comment]
It appears that there are easy fixes for this. I'll put in a pull request for one. See here: http://stackoverflow.com/questions/6695208/uri-escapedatastring-invalid-uri-the-uri-string-is-too-long

**Comment by moozzyk** [comment]
@BrannonKing - this is fixed in 2.2.0 - #3040
