### ISSUE TITLE
SocketException in NetworkStream.BeginRead

### ISSUE THREAD

**Issue by jcondex** [SignalR/SignalR#1640]
One of our tests failed because the socket was unexpectedly closed.

Further analysis is needed to determine the cause of this issue.

Here is the client stack:

```
StressTestLogger Critical: 22 : [18:08:17] System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
```

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
