### ISSUE TITLE
.Net client webSockets transport doesn't raise Error event when OnReceived throw in PersistentConnection

### ISSUE THREAD

**Issue by Xiaohongt** [SignalR/SignalR#1658]
e.g. 
in .Net client:

``` csharp
//use the asp.net sample url
var connection = new Connection("http://localhost:40476/raw-connection/");
connection.Error += e =>
{
    Console.WriteLine("[" + DateTime.Now + "]: Error occurred " );
};
connection.Start(new Microsoft.AspNet.SignalR.Client.Transports.WebSocketTransport(new Microsoft.AspNet.SignalR.Client.Http.DefaultHttpClient())).Wait();
connection.Send("test");
```

in  the asp.net sample RawConnection:

``` csharp
protected override Task OnReceived(IRequest request, string connectionId, string data)
{
     //throw when data is just like "test"
     var message = JsonConvert.DeserializeObject<Message>(data);
     ......
 }
```

in this case .Net client webSockets transport doesn't raise error event, however SSE, longPolling transports raise error event in this case.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
