### ISSUE TITLE
.Net client OnError trace it will more useful trace the SignalRError instead of Exception

### ISSUE THREAD

**Issue by Xiaohongt** [SignalR/SignalR#1659]
Currently (copy below) in .Net client OnError we only trace the Exception error, it will be more useful trace the SignalRError and ResponseBody

``` csharp
 void IConnection.OnError(Exception error)
        {
            Trace.WriteLine("OnError({0})", error);

            if (Error != null)
            {
                Error(error);
            }
        }
```

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
