### ISSUE TITLE
Cross-Domain - HTTP403 on negotiate

### ISSUE THREAD

**Issue by Treyone** [SignalR/SignalR#1686]
Hi guys,

I'm using 1.01 from NuGet, with a pretty simple hub : on connection, the client calls a init method that subscribes the client to some groups depending on his profile.
The thing is, this runs on cross domain, as the client part might be on different and unpredictable domains.

After a lot of tuning, here's what I have :

Client side:

``` javascript
jQuery.support.cors = true;
$.connection.hub.url = 'http://myserver.compute.amazonaws.com/raidernotifier/signalr'
notifier = $.connection.dispatcher; //dispatcher = my hub
$.connection.hub.start({ jsonp: true }).done(function () {///jsonp for IE9
notifier.server.init(profile);
}
```

Server side (global.asax):

``` csharp
void Application_Start(object sender, EventArgs e)
        {
            RegisterRoutes();
        }

        private void RegisterRoutes()
        {
            RouteTable.Routes.MapHubs();
          //  GlobalHost.HubPipeline.EnableAutoRejoiningGroups();//maintenant mis par défaut, je garde pour mémoire pour l'instant

            RouteTable.Routes.Add(new ServiceRoute("broadcast", new WebServiceHostFactory(), typeof(broadcaster)));
        }
  protected void Application_BeginRequest(object sender, EventArgs e)
        {
 HttpContext.Current.Response.AddHeader("Access-Control-Allow-Origin", "*");
            if (HttpContext.Current.Request.HttpMethod == "OPTIONS")
            {
                HttpContext.Current.Response.AddHeader("Cache-Control", "no-cache");
                HttpContext.Current.Response.AddHeader("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE");
                HttpContext.Current.Response.AddHeader("Access-Control-Allow-Headers", "Content-Type,Origin,Accept,Authorization");
                HttpContext.Current.Response.AddHeader("Access-Control-Max-Age", "1728000");

                HttpContext.Current.Response.End();
            }
}

```

And here's where I get stuck : on load, where starting the client-side part, a call is fired to
http://myserver.compute.amazonaws.com/raidernotifier/signalr/negotiate?_=1363168277694

But this one is rejected (HTTP 403 error).

I guess I'm missing something, as I just didn't find other people with this issue. I've been investigating global.asax.cs, IIS configuration, firewall issues, client-side CORS configuration with no luck.

Does anybody have an idea ?

**Comment by PterPmnta** [comment]
@trailseeker can you solved, i have the same problem, but you try add `/signalr`, in the url server pah

**Comment by Ahsan70** [comment]
> Remove all of the code that adds the headers and add this setting to your server https://github.com/SignalR/SignalR/blob/master/ReleaseNotes.md#10

this url not working
