### ISSUE TITLE
Modify JS client to not utilize success, error, and complete methods on $.ajax

### ISSUE THREAD

**Issue by NTaylorMullen** [SignalR/SignalR#1695]
As of JQuery 1.8 the success, error, and complete methods are deprecated and will be removed in a future release.  They suggest using the promise methods (.done, .fail etc.).

For more details see the deprecation notice at http://api.jquery.com/jQuery.ajax/#jqXHR.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
