### ISSUE TITLE
in SqlServer send.sql consider updating @EndPayloadId for the number of deleting oldest block of messages

### ISSUE THREAD

**Issue by Xiaohongt** [SignalR/SignalR#1706]
Current in send.sql for for deleting oldest block of messages:

```
SET @OverMaxBy = @RowCount - @MaxTableSize;
SET @EndPayloadId = @StartPayloadId + @BlockSize  + @OverMaxBy;

-- Delete oldest block of messages
DELETE FROM [SignalR].[Messages_1]
WHERE [PayloadId] BETWEEN @StartPayloadId AND @EndPayloadId;
```

the number of messages will be deleted actually is @BlockSize  + @OverMaxBy + 1 (it includes the StartPayloadId message)

It will be better if update it to below minus 1 since below the number of messages will be deleted is @BlockSize  + @OverMaxBy:

```
SET @EndPayloadId = @StartPayloadId  + @BlockSize  + @OverMaxBy -1;
```

e.g.
if @StartPayloadId =1, @MaxTableSize =3, @BlockSize =2,
when @NewPayloadId =4, and @RowCount =4,
then @OverMaxBy = 1,  @EndPayloadId = @StartPayloadId + @BlockSize  + @OverMaxBy = 4
then it will delete all rows

Expected:
we should delete number @BlockSize  + @OverMaxBy rows

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
