### ISSUE TITLE
Take a .NET 4.5 dependency in SignalR core (server side)

### ISSUE THREAD

**Issue by DamianEdwards** [SignalR/SignalR#1723]
Remove support for .NE 4.0 in SignalR server side, allowing us to utilize async/await, etc.

**Comment by simquad** [comment]
I'm trying to install SignalR using v1.1.4 and is complaining about Microsoft.Owin.Security 2.1.0 not supporting .NET 4.0..... This seems crazy?

Am I missing something obvious?

**Comment by JobaDiniz** [comment]
Can I use `SignalR Client` framework 4.5 to connecto to `SignalR Sever` framework 4.0 (version 1.2.2) ?

**Comment by Guilh3rme3Soar3es** [comment]
SignalR 1.2.2 supports .NET Standard 2.0?
