### ISSUE TITLE
SignalR Hub Clients.Caller.method not being called

### ISSUE THREAD

**Issue by smit010** [SignalR/SignalR#1727]
We have a .NET Signal Client connecting to ASP.NET MVC Signal R Server. No server-side timeout properties were changed, and the .NET client is on a separate machine going through a proper domain.

On occassion, the server Hub calls the 'Clients.Caller.method', but it does not get executed on the client. Furthermore, once it starts happening, the Clients.Caller.method never gets called again (till the .NET client is restarted - as this creates a new connection and a HubProxy).

More information is provided in this Stackoverflow thread: http://stackoverflow.com/questions/15512980/signalr-net-client-disconnecting

Also note that this issue could be related to a previously reported one: https://github.com/SignalR/SignalR/issues/1472

I have added a new issue as this relates to the .NET client (as opposed to the javascript client).

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
