### ISSUE TITLE
window.print not working with SignalR

### ISSUE THREAD

**Issue by Andection** [SignalR/SignalR#1728]
When I connect to the page client script libraries SignlR.
When a page is connected javascript SignlR .. function widnow.print () does not open a window for printing .. but when I try to switch to another browser page shows me the page for printing.

It's reproducing in chrome version 25.0.1364.172 m

**Comment by gjdonkers** [comment]
I'm having the same issue but with Safari 8.0.6 (10600.6.3), working with Chorme is no problem. The version of SignalR is v2.2.0. Forcing {transport: 'longPolling'} doesn't work either. 

Anyone else has the same issue?

**Comment by nastakhov** [comment]
Same for Safari 9.1

**Comment by crajivgandhim** [comment]
Same issue with Safari 10.0.2(SignalR is v2.2.0), When this issue will be resolved?

**Comment by luisperezphd** [comment]
Have the same issue in several different versions of Safari.

**Comment by davidfowl** [comment]
It's a browser issue. I'm not aware of a workaround for this.
