### ISSUE TITLE
Create Testswarm Cross Domain tester

### ISSUE THREAD

**Issue by NTaylorMullen** [SignalR/SignalR#1753]
We should add a new testswarm configuration that runs all tests against a remote server.

For the client all we'd need to do:
1. In test.config.js bind window.document.testUrl to a query string parameter. 
2. In testUtilities.js force foreverFrame and serverSentEvents tests to only be run when not running cross domain.

I've done this locally and deployed my own server and the existing test framework already supports it (after doing 1 & 2 above), it would greatly improve our testing capabilities and would also help find bugs such as #1745.

Not to mention we could then also add cross domain specific tests.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
