### ISSUE TITLE
SignalR.Owin incorrectly parses cookeis

### ISSUE THREAD

**Issue by desunit** [SignalR/SignalR#1778]
I've found SignalR.Owin incorrectly interprets cookies:https://github.com/SignalR/SignalR/blob/master/src/Microsoft.AspNet.SignalR.Owin/ServerRequest.cs#L117

It uses the same code as URL parser which is not correct and causes many problems especially when SessionID contains plus (+) sign. 

According to [RFC 2109](http://www.ietf.org/rfc/rfc2109.txt)  value has to be:

```
(... a sequence of non-special, non-white space characters) from the HTTP/1.1 specification [RFC 2068] to describe their syntax.
```

The quick fix could be modifying that code so it suppresses "+" replacing:
https://github.com/SignalR/SignalR/blob/master/src/Microsoft.AspNet.SignalR.Owin/Infrastructure/UrlDecoder.cs#L45

Another issue with the current code that cookie value could be `"quoted"` then it wouldn't be correctly handled either.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
