### ISSUE TITLE
on IE10 with Browser Mode IE9, when stop cross-origin longPolling hub connection, it causes SCRIPT5007

### ISSUE THREAD

**Issue by Xiaohongt** [SignalR/SignalR#1780]
on IE10 with Browser Mode IE9, when stop cross-origin  longPolling hub connection, it causes SCRIPT5007: Object expected connect, line 1 character 1 for the longPolling connection response.

Repro:
1. on IE10, open developer tools, select "Browser Mode: IE9" 
2. request http://signalrtestweb.azurewebsites.net/hubs/myhub/myHub_proxy_url_91_x.html
3. click "Stop connection" button

you can see that  it causes SCRIPT5007: Object expected connect, line 1 character 1 for the longPolling connection response.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
