### ISSUE TITLE
Getting "The remote host closed the connection" Exception for some user's when navigate the website.

### ISSUE THREAD

**Issue by jesraelvergara** [SignalR/SignalR#1790]
Our App was written in MVC .net and we are getting "The remote host closed the connection" Exception for some user as they navigate the page but some other user works just fine. I've look at the Windows Log > Application and here is what got recorded.

Event code: 3005 
Event message: An unhandled exception has occurred. 
Event time: 4/1/2013 8:20:12 PM 
Event time (UTC): 4/2/2013 12:20:12 AM 
Event ID: EventIdHere
Event sequence: 126921 
Event occurrence: 230 
Event detail code: 0 

Application information: 
    Application domain: /LM/W3SVC/7/ROOT-1-130092926427857856 
    Trust level: Full 
    Application Virtual Path: / 
    Application Path: E:\www\OurPathHere\ 
    Machine name: OurMachineNameHere

Process information: 
    Process ID: 9196 
    Process name: w3wp.exe 
    Account name: NT AUTHORITY\NETWORK SERVICE 

Exception information: 
    Exception type: HttpException 
    Exception message: The remote host closed the connection. The error code is 0x80070057.
   at System.Web.Hosting.IIS7WorkerRequest.RaiseCommunicationError(Int32 result, Boolean throwOnDisconnect)
   at System.Web.Hosting.IIS7WorkerRequest.ExplicitFlush()
   at System.Web.HttpResponse.Flush(Boolean finalFlush)
   at System.Web.HttpResponseWrapper.Flush()
   at Microsoft.Owin.Host.SystemWeb.CallStreams.OutputStream.Flush()
   at Microsoft.AspNet.SignalR.Owin.ServerResponse.<Flush>b__0()
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.FromMethod(Action func)

Request information: 
    Request URL: http://OurHostNameHere/signalr/connect?transport=longPolling&connectionId=c13ea7b9-9ef2-4a00-954b-460c73e2038c&connectionData=[{"name":"notifier"}]&tid=6&_=1364862002669 
    Request path: /signalr/connect 
    User host address: OurHostAddressHere 
    User: OurUserHere 
    Is authenticated: True 
    Authentication Type: Negotiate 
    Thread account name: NT AUTHORITY\NETWORK SERVICE 

Thread information: 
    Thread ID: 22 
    Thread account name: NT AUTHORITY\NETWORK SERVICE 
    Is impersonating: False 
    Stack trace:    at System.Web.Hosting.IIS7WorkerRequest.RaiseCommunicationError(Int32 result, Boolean throwOnDisconnect)
   at System.Web.Hosting.IIS7WorkerRequest.ExplicitFlush()
   at System.Web.HttpResponse.Flush(Boolean finalFlush)
   at System.Web.HttpResponseWrapper.Flush()
   at Microsoft.Owin.Host.SystemWeb.CallStreams.OutputStream.Flush()
   at Microsoft.AspNet.SignalR.Owin.ServerResponse.<Flush>b__0()
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.FromMethod(Action func)

**Comment by xtrungmapx** [comment]
Hi @davidfowl ,

We are using Sentry to log out some errors from out application. This error exception is eating a lot of our "quota".

Anyway to handle/ignore this error ?

**Comment by SethuICOMM** [comment]
Hi,

In multitenant codebase , i got frequently this error and client complained. Not able to trace the error and don;t know which page produce and why?

issue belongs to IIS side or SQL server (DB) side?

Already i written application_start event with handling last error raised by system.

where should i include this error

Protected Sub Application_Start(ByVal sender As Object, ByVal e As EventArgs)
    TaskScheduler.UnobservedTaskException += New EventHandler(Function(s, arg)
                                                                  arg.SetObserved()
                                                                  (CType(arg.Exception, AggregateException)).Handle(Function(ex) True)
                                                              End Function)
End Sub
