### ISSUE TITLE
JS client raise no error event or raises an empty error when the webserver crashes

### ISSUE THREAD

**Issue by gustavo-armenta** [SignalR/SignalR#1845]
Minimal repro steps
1. Navigate to http://localhost:40476/Hubs/Test/clientsCaller.html
2. Open browsers with the other transports
3. Stop IIS Express

Expected Result
JS client raises OnError and provides an error message

Actual Result
serverSentEvents does not raise OnError
other transports raise OnError but there is no error message

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
