### ISSUE TITLE
GroupManager.Add(string connectionId, string groupName) should throw when pass empty string for groupName parameter

### ISSUE THREAD

**Issue by Xiaohongt** [SignalR/SignalR#1878]
GroupManager.Add(string connectionId, string groupName) should throw when pass empty string for groupName parameter

Functional impact:
when join groups, we already throw when groupName is null, we should also throw when groupName is empty string 

Repro:
Groups.Add(connectionId, "");

Expected results:
throw error for argument

Actual result:
no error, the empty groupName with group prefix is sent

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
