### ISSUE TITLE
Make Ajax sends POST JSON instead of url encoded form data

### ISSUE THREAD

**Issue by signalrcoreteam** [SignalR/SignalR#1886]
From both the JS and .NET clients, we should send up JSON instead of url encoded form data.

**Comment by MonkeyDo** [comment]
Any news on this?
Trying to use SignalR in a Cocoonjs canvas+ view, which erroneously sends the data as JSON.
Did anyone come up for  a workaround to use JSON?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
