### ISSUE TITLE
With scale-out, in receive message value for cursor should be similar as without scale-out

### ISSUE THREAD

**Issue by Xiaohongt** [SignalR/SignalR#1890]
With scale-out, in receive message value for cursor like "C":"0,20626|1,FFFFFFFFFFFFFFFF|2,FFFFFFFFFFFFFFFF|3,5419|4,3D7F0",

without scale-out, in receive message value for cursor like: "C":"B,4|F,1|G,0|H,0"

It will be better that with scale-out value for cursor is similar as without scale-out

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
