### ISSUE TITLE
NetworkError: 500 Internal Server Error

### ISSUE THREAD

**Issue by DavidSlavik** [SignalR/SignalR#1935]
Hello,

hhen I am running the web site on my local computer it works properly, but when I uploading to my domain, its starts to generates this error. Same problem I have on two my applications on difference servers. Same is only implementation solution, what is ASP.Net MVC 3, C#. Both of my applications are running on "Full trust" prottection on IIS server. Locally it works fine but problems are on remote servers.

Applications are running fine, but returns there errors :( Here is screenshot from mozilla firebug/network.

![SignalR](https://f.cloud.github.com/assets/2188078/415344/9da7e064-ac30-11e2-9cd4-f8684d2fc362.png)

Thanks!!!
-David

I have same issue like: https://github.com/SignalR/SignalR/issues/430 but 430 is closed...

**Comment by lextm** [comment]
Duplicate to #1315
