### ISSUE TITLE
ConnectDisconnect.SendingToHub variation hangs!

### ISSUE THREAD

**Issue by jcondex** [SignalR/SignalR#1959]
Look at the below repro.  The way it works is the abort_thread is created that sleeps for a random amount of time.  Once it finishes sleeping, it aborts the transport.

While the abort_thread is sleeping, a tight loop continuously invokes methods on the hub side.  I would expect some sort of exception to occur or something to tell me that the transport has been aborted, but instead the call to hubProxy.Invoke("ReceivePayload", payload).Wait(); blocks indefinitely.

After the abort_thread kicks in, the connection.State seems to be in the Connected state.

Here's the repro:

client:

``` csharp
        public void RunRepro()
        {
            while (true)
            {
                Repro();
            }
        }

        public void Repro()
        {
            HubConnection connection = new HubConnection(Properties.HubUrl);

            IHubProxy hubProxy = connection.CreateHubProxy(HubName);

            ServerSentEventsTransport transport = new ServerSentEventsTransport();

            connection.Start(transport).Wait();

            int threadId = Thread.CurrentThread.ManagedThreadId;

            object theLock = new object();

            Thread thd = new Thread(() =>
            {
                Thread.Sleep(new Random().Next(100) + 50);

                lock (theLock)
                {
                    transport.Abort(connection, TimeSpan.FromSeconds(10));
                }

                Log.Information("Aborted connection");
            });

            thd.Start();

            while (true)
            {
                try
                {
                    Payload payload = Payload.Random();
                    lock (theLock)
                    {
                        hubProxy.Invoke("ReceivePayload", payload).Wait();
                    }
                }
                catch (InvalidOperationException)  //in case there's a race condition - The Start method must be called before data can be sent.
                {
                    break;
                }

                Thread.Sleep(1);
            }
        }
```

Hub:

``` csharp
        public void ReceivePayload(Payload payload)
        {
            Assert.IsFalse(payload.IsNull);
        }
```

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
