### ISSUE TITLE
SignalR client JS doesn't reconnect if fails when starting first time

### ISSUE THREAD

**Issue by bborad** [SignalR/SignalR#1962]
Hi

My signalR client in my web page tries to connect to the server in a desktop application. 

Issue is when client (web page) tries to connect to the server first time and if the server is not online it fails and doesn't reconnect.  But if it connects in first time then after, if server drops off, it automatically tries to reconnect. 

Here's code example (client side)

var conn = $.hubConnection('url');
var chub = conn.createHubProxy('myhub');

chub.on('messageReceived', function(msg){
 $('#log').after('Message Received : ' + msg);
});

conn.stateChanged(function (state){
 if(state.newState == $.signalR.connectionState.reconnecting){
  $('#log').after('Reconnecting');
}
else if(state.newState == $.signalR.connectionState.connected){
  conn.start().done(function(){
       $('#log').after('connected');
       }).fail(function(){
        $('#log').after('Connection failed.');
       });
}
});

conn.start().done(function(){
       $('#log').after('connected');
       }).fail(function(){
        $('#log').after('Connection failed.');
       });
});

**Comment by jpierson** [comment]
Note that it appears that the `disconnect` and *not* `disconnected` method is actually on the hub at least in the lastest version of SignalR.
