### ISSUE TITLE
The user identity cannot change during an active SignalR connection

### ISSUE THREAD

**Issue by simoneb** [SignalR/SignalR#1998]
I'm stuck on this error message which I've started to get after upgrading to 1.1.0-beta1.

I've got several hubs that I'm using on the same page. I'm using the AuthorizeAttribute on a hub method requiring specific roles to be assigned to the user (Windows authentication with AD).

I specifically wanted that only one operation on a specific hub required different privileges from the user, but as I understand this is not possible using the same SignalR connection.

 After I started to get this error I tried to fix it by requiring the same roles on all hubs I'm using on the page, but this only makes it slightly better as I still keep getting the error. It almost looks like SignalR thinks that the user identity is changing, can it be that applying the AuthorizeAttribute on all hubs issues every time a new auth token and although the user identity is the same the token ends up being different?

Any guidance about how to fix this is appreciated.

**Comment by PHANTOMER** [comment]
I am still experiencing this issue. I have chat application. 2 tabs open in firefox (logged in as 2 different users). When I connect to my hub from the first tab, I am able to send messages. Then, as soon as I start connection from the second tab, the first tab goes crazy. When I try to send the message, I get a lot of 403 errors, which say that identity cannot change during active SignalR connection.

**Comment by Sam-Davis** [comment]
I found that this issue was solved by disabling anonymous authentication. Full answer here: 
http://stackoverflow.com/a/31564482/2945345

**Comment by niemyjski** [comment]
@Sam-Davis, but we don't have that enabled to begin with.

**Comment by Sam-Davis** [comment]
Sure. What type of auth are you using? The issue I was having was basically a race condition. Perhaps, you need to create a promise for the user being connected and only connect to signalR once this is complete.

**Comment by niemyjski** [comment]
OAuth/Token based authentication

**Comment by Zeni241** [comment]
I was getting the same error message when the user loggedIn and the user identity changed. The solution is to disconnect the hub connection before logging in and restart the signalR hub connection after successful logging.
The following example shows how to stop and start a connection when the user status has changed.
<script type="text/javascript">
    $(function () {
        var chat = $.connection.sampleHub;
        $.connection.hub.start().done(function () {
            $('#logoutbutton').click(function () {
                chat.connection.stop();
                $.ajax({
                    url: "Services/SampleWebService.svc/LogOut",
                    type: "POST"
                }).done(function () {
                    chat.connection.start();
                });
            });
        });
    });
</script>


The details can be found here.  http://www.asp.net/signalr/overview/security/introduction-to-security

**Comment by psib3r** [comment]
I had a similar error when using it in an MVC app, in my controller I had [Authorize] so I could get the user name from the HttpContext, this caused the issue, to resolve I simply added [Authorize] to my Hub class.

**Comment by RasicN** [comment]
@psib3r this took me way to long to find.  Thanks!  That was exactly my problem.  Just as a heads up if you are using Chrome as of right now you will not be able to Authenticate using windows authentication and websockets: https://stackoverflow.com/questions/26863242/signalr-mvc-5-websocket-no-valid-credentials.
But putting the [Authorize] tag on my Hub combined with anonymous authentication being enabled and Chrome created some weird things to happen.  Thanks!
