### ISSUE TITLE
Add tests for client certs in the .NET client

### ISSUE THREAD

**Issue by abnanda1** [SignalR/SignalR#2007]

**Comment by dealproc** [comment]
can this be extended to the mono runtime, and prove that client certificates will be presented to a server from the c# mono client?

Just spent 10+ hours on this, to come across this stackoverflow article saying that you basically have to negate the use of `hubConnection.AddClientCertificate(theCertificate)` and instead monkier it in via a custom IHttpClient:

```C#
class CertificateBearingHttpClient : IHttpClient
{
    DefaultHttpClient _client = new DefaultHttpClient();
    X509Certificate2 _certificate;

    Action<IRequest> AppendCertificate(Action<IRequest> prepareRequest)
    {
        return new Action<IRequest>(req =>
        {
            var fi = typeof(HttpWebRequestWrapper).GetField("_request", BindingFlags.NonPublic | BindingFlags.Instance);
            HttpWebRequest request = (HttpWebRequest)fi.GetValue(req);
            request.ClientCertificates.Add(_certificate);
            prepareRequest(req);
        });
    }

    public CertificateBearingHttpClient(X509Certificate2 cert)
    {
        _certificate = cert;
    }

    public void Initialize(IConnection connection)
    {
        _client.Initialize(connection);
    }

    public Task<IResponse> Get(string url, Action<IRequest> prepareRequest, bool isLongRunning)
    {
        return _client.Get(url, AppendCertificate(prepareRequest), isLongRunning);
    }

    public Task<IResponse> Post(string url, Action<IRequest> prepareRequest, IDictionary<string, string> postData, bool isLongRunning)
    {
        return _client.Post(url, AppendCertificate(prepareRequest), postData, isLongRunning);
    }
}
```
This patch is a bit infuriating, as it shouldn't be necessary.

</rant> over.. at least I'll be back functioning :)

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
