### ISSUE TITLE
WP8 LP client raises OnError event when "/poll" returns httpStatusCode=404

### ISSUE THREAD

**Issue by gustavo-armenta** [SignalR/SignalR#2031]
A console application can send a "/poll" request and wait for a response infinitely. A windows phone app is terminating the "/poll" request after one minute with a http status code 404 (Not Found). This 404 response is triggering an OnError event that will be handled by the user. It results on a different product behavior depending on the platform, maybe we want to consider hiding this particular error to the user.

Functional impact:
Low, after the one minute timeout, a new "/poll" request is created and communication continues successfully.

Expected result:
client does not raise the OnError event behaving as other platforms

Actual result:
client raises an OnError event with a HttpClientException

Repro Steps
1. Run WP8 sample
2. Wait 1.5 minutes without any activity on the WP8 app, you should see a HttpClientException

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
