### ISSUE TITLE
Returning custom/complex objects to the fail() callback

### ISSUE THREAD

**Issue by jamiewinder** [SignalR/SignalR#2050]
Currently, if an exception is thrown during a hub method, the promise on the Javascript is rejected, and the failCallback is called with a single string argument. This is either the Message property of the exception (if detailed errors are enabled) or a generic string that simply states that an exception occurred (if detailed errors are disabled). 

I think a good extensibility feature would be to provide a way to customise the object returned on an exception. I imagine this would involve implementing the following interface and somehow plugging it into the hub pipeline:

<pre>
interface IFailCallbackHandler
{
     object CreateFailObject(Exception ex);
}
</pre>

This would better suit the promise pattern on the client, as you could write: (Sorry for the long examples!)

<pre>
hub.server.login(un, pw).then(function(user)  {
     DisplayUser(user);
     alert("OK");
}, function(err) {
     if (err.Reason === "badusername") $("#username").addClass("invalid").focus();
     else if (err.Reason === "badpassword") $("#password").addClass("invalid").focus();
     else alert("Unknown error: " + err.Message);
});
</pre>

Rather than:

<pre>
hub.server.login(un, pw).then(function(result) {
    if (result.User)
    {
        DisplayUser(result.User);
        alert("OK");
    }
    else if (result.Error)
    {
        var reason = result.Error.Reason;
        if (reason === "badusername") $("#username").addClass("invalid").focus();
        else if (reason === "badpassword") $("#password").addClass("invalid").focus();
    }
}, function(err) {
    alert("Unknown error: " + err);
});
</pre>

(i.e. combining the result & error into a return object, and handling the success and failure logic branches in the same function). 

The done() and fail() callbacks are great patterns on the client-side and make code very readible, but they're difficult to fully utilise with SignalR providing complete control on the done() callback argument, but none to the fail() callback argument.

Thanks.

**Comment by Kooki** [comment]
Hi,

is it possible that this issue is still alive on signalr 2.2.0 ? Is there any workaround to receive a custom exception on a c# signalr client ?

Client Code :
`        public MyObject GetMyObject()
        {
            var result = hub.Invoke<MyObject>("GetMyObjectById", "id=1");
            result.ContinueWith(task =>
                                {
                                    if (result.IsFaulted)
                                    {
                                        result.Exception.Handle((x) =>
                                        {
                                            if (x is MyCustomException) 
                                            {
                                               //codse
                                            }
                                            return true; handled  
                                        });
                                        return null;
                                    }
                                    //yiehaa
                                });
            return null;
        }`

Server Code:
`        public async Task<MyObject> GetMyObjectById(string query)
        {
            if (query == "id=1")
            {
                throw new MyCustomException("damn",CustomExceptionType.SOMETHING);
            }
            return new MyObject();
        }`

On client side I got an `Name = "InvalidOperationException" FullName = "System.InvalidOperationException"` with my message 'damn', but without any other properties like 'CustomExceptionType' .

I already tried : 
`            appBuilder.MapSignalR(new HubConfiguration() { EnableJSONP = true , EnableDetailedErrors = true});
`

Any suggestions?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
