### ISSUE TITLE
Forever frame does not work in IE, when document.domain is set

### ISSUE THREAD

**Issue by matra774** [SignalR/SignalR#2054]
I have a web page, that explicitly sets the document.domain.  Whenusing foreverframe with IE, SignalR fails with AccessDenied error.

> LOG: [18:13:49 UTC+0200] SignalR: Negotiating with '/signalr/negotiate'. 
> LOG: [18:13:49 UTC+0200] SignalR: This browser doesn't support SSE. 
> LOG: [18:13:49 UTC+0200] SignalR: Binding to iframe's readystatechange event. 
> SCRIPT5: Access is denied.
> 
> connect?transport=foreverFrame&connectionToken=gE4M0Lp-ksxr_Bdc_4N3l6r8OjmVzGnSEt0D8Zpi2kqNJ2f2A1y9PveWtrwpylvsmbAoL5NsueW_wACpnDHm42c1_XhMOMcXFrFrzX5QKJYnWFjwNU5i24q16k2c3yjXLzQB68l60_UjHkSTSKV-ICQJd-5ElW7SZ1YcFVnr_R4NBH5Jow1w7SuYsC_30PCi0&connectionData=%5B%7B%22name%22%3A%22chathub%22%7D%5D&tid=4&frameId=1, line 3 character 5
> SCRIPT5007: Object expected 
> connect?transport=foreverFrame&connectionToken=gE4M0Lp-ksxr_Bdc_4N3l6r8OjmVzGnSEt0D8Zpi2kqNJ2f2A1y9PveWtrwpylvsmbAoL5NsueW_wACpnDHm42c1_XhMOMcXFrFrzX5QKJYnWFjwNU5i24q16k2c3yjXLzQB68l60_UjHkSTSKV-ICQJd-5ElW7SZ1YcFVnr_R4NBH5Jow1w7SuYsC_30PCi0&connectionData=%5B%7B%22name%22%3A%22chathub%22%7D%5D&tid=4&frameId=1, line 8 character 1
> SCRIPT5007: Object expected 
> connect?transport=foreverFrame&connectionToken=gE4M0Lp-ksxr_Bdc_4N3l6r8OjmVzGnSEt0D8Zpi2kqNJ2f2A1y9PveWtrwpylvsmbAoL5NsueW_wACpnDHm42c1_XhMOMcXFrFrzX5QKJYnWFjwNU5i24q16k2c3yjXLzQB68l60_UjHkSTSKV-ICQJd-5ElW7SZ1YcFVnr_R4NBH5Jow1w7SuYsC_30PCi0&connectionData=%5B%7B%22name%22%3A%22chathub%22%7D%5D&tid=4&frameId=1, line 9 character 1

After a while. it tries to reconnect with another transport, but by this time we have already lost improtant messages.

> LOG: [18:13:52 UTC+0200] SignalR: Failed to connect using forever frame source, it timed out after 3000ms. 
> LOG: [18:13:52 UTC+0200] SignalR: SignalR: Error occured when stopping foreverFrame transport. Message = Access is denied.
> 
> LOG: [18:13:52 UTC+0200] SignalR: Stopping forever frame 
> LOG: [18:13:52 UTC+0200] SignalR: SignalR: Initializing long polling connection with server. 
> LOG: [18:13:53 UTC+0200] SignalR: Attempting to connect to 'http://localhost:6634/signalr/connect?transport=longPolling&connectionToken=gE4M0Lp-ksxr_Bdc_4N3l6r8OjmVzGnSEt0D8Zpi2kqNJ2f2A1y9PveWtrwpylvsmbAoL5NsueW_wACpnDHm42c1_XhMOMcXFrFrzX5QKJYnWFjwNU5i24q16k2c3yjXLzQB68l60_UjHkSTSKV-ICQJd-5ElW7SZ1YcFVnr_R4NBH5Jow1w7SuYsC_30PCi0&connectionData=%5B%7B%22name%22%3A%22chathub%22%7D%5D&tid=2' using longPolling. 
> LOG: [18:13:53 UTC+0200] SignalR: Longpolling connected 

Reason for this is that the document that is loaded in hidden iFrame, does not explicitly set the document.domain to the same value as parent page.  Therfore, the frame fails in the first line of javascript:

``` javascript
 var $ = window.parent.jQuery,
```

To reproduce:
1. Try to use SignalR on page that sets document.domain (for example document.domain="localhost");
2. It will fail with above error

I've seen that similar issues have been already discussed in #873, and #643, but the fix does not seems to solve my problem.

**Comment by johncmatthews** [comment]
Is this still an existing issue in SignalR?  I am experiencing the exact behavior in the OP.  Thanks.

**Comment by moozzyk** [comment]
We are cutting ForeverFrame transport in the Core version of SignalR Server
