### ISSUE TITLE
iOS unable to connect. HubConnection.Start() not giving me an exception.

### ISSUE THREAD

**Issue by selzero** [SignalR/SignalR#2114]
Hi guys,

I just checked out and built the latest iOS branch. It compiles fine.

When I try to Start() the connection it falls out of the try() but doesnt give me an exception in the catch()

(This code works on windows and mac clients but not on iOS)

``` csharp
public void ConnectToServer()
{
    HubConnection connection = new HubConnection ("http://192.168.0.113:666/");
    var myHub = connection.CreateHubProxy ("MyHub");
    try {
            connection.Start ().ContinueWith (task =>{this.lblOutput.Text="ok";});

    } catch (Exception e) {}
}
```

**Comment by rajkanya** [comment]
hi @selzero can you please help me in this? I too am stuck with the same problem.
