### ISSUE TITLE
client-side exception then SignalR used together with MicrosoftAjax

### ISSUE THREAD

**Issue by dsosunov** [SignalR/SignalR#212]
Microsoft AJAX disposes resources when window is unloading.
This framework uses internal method _ensureDomNode and nodes in SignalR frame is not created (wrapped) by framework.

``` javascript
$type._ensureDomNode = function DomEvent$_ensureDomNode(element) {
    if (element && element.tagName && (element.tagName.toUpperCase() === "SCRIPT")) return;

    var doc = element ? (element.ownerDocument || element.document || element) : null;
    if (!element ||
        ((typeof(element.document) !== 'object') && (element != doc) && (typeof(element.nodeType) !== 'number'))) {
        throw Error.argument("element", Sys.Res.argumentDomNode);
    }
}
```

Therefore, element.tagName is not a string.

The quick fix is override this method and wrap in try/catch

Sample:

``` javascript
$(function () {
    var original = Sys.UI.DomEvent["_ensureDomNode"];
    Sys.UI.DomEvent["_ensureDomNode"] = function () {        
        try {
            original();
        } catch (e) {
        }
    };
});
```

But, may be community can propose the better solution.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
