### ISSUE TITLE
Several browsers show infinite loading status

### ISSUE THREAD

**Issue by xqiu** [SignalR/SignalR#215]
When I tried SignalR app with IE8, seems it always trying to show loading status in the status bar in IE8.  The temp site is http://319c8b3d7b394b46b1b7b7eb67d32778.cloudapp.net/. Contact me privately for code. Thanks.
### Similar issues:
- #103
- #383

**Comment by beefydog** [comment]
It is March 1st, 2015. So I take it iOS and Safari clients are still not compatible with SignalR?
