### ISSUE TITLE
Cross Domain - Access Control Headers Not Added Running Remotely

### ISSUE THREAD

**Issue by thnk2wn** [SignalR/SignalR#2156]
I have SignalR 1.1.2 communicating fine between a windows service (Owin self hosted) and an asp.net mvc app (JS client) when running locally. When the windows service is deployed remotely on the server (win 2008 r2) I receive the following error in Chrome:

> XMLHttpRequest cannot load http://ccweb-dev:8097/signalr/negotiate?_=1371325718534. Origin http://localhost:1912 is not allowed by Access-Control-Allow-Origin.
#### Running Remotely - Access-Control headers not added:

**Request**

> GET /signalr/negotiate?_=1371325718534 HTTP/1.1
> Host: ccweb-dev:8097
> Connection: keep-alive
> Accept: application/json, text/javascript, _/_; q=0.01
> Origin: http://localhost:1912
> User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.110 Safari/537.36
> Content-Type: application/x-www-form-urlencoded; charset=UTF-8
> Referer: http://localhost:1912/
> Accept-Encoding: gzip,deflate,sdch
> Accept-Language: en-US,en;q=0.8

**Response**

> HTTP/1.1 400 Bad Request
> Content-Type: text/html; charset=us-ascii
> Server: Microsoft-HTTPAPI/2.0
> Date: Sat, 15 Jun 2013 19:48:38 GMT
> Connection: close
> Content-Length: 334
#### Running locally Access-Control headers present:

**Request**

> GET /signalr/negotiate?_=1371325544785 HTTP/1.1
> Host: localhost:8097
> Connection: keep-alive
> Accept: application/json, text/javascript, _/_; q=0.01
> Origin: http://localhost:1912
> User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.110 Safari/537.36
> Content-Type: application/x-www-form-urlencoded; charset=UTF-8
> Referer: http://localhost:1912/
> Accept-Encoding: gzip,deflate,sdch
> Accept-Language: en-US,en;q=0.8

**Response**

> HTTP/1.1 200 OK
> Transfer-Encoding: chunked
> Content-Type: application/json; charset=UTF-8
> Server: Microsoft-HTTPAPI/2.0
> Access-Control-Allow-Origin: http://localhost:1912
> Access-Control-Allow-Credentials: true
> X-Content-Type-Options: nosniff
> Date: Sat, 15 Jun 2013 19:45:45 GMT
#### Win Svc Web App Startup Config

```
class WebAppStartup
{
    public void Configuration(IAppBuilder app)
    {
        var config = new HubConfiguration { EnableCrossDomain = true };
        app.MapHubs(config);
    }
}
```
#### Win Svc Start/Stop

```
protected override void OnStart(string[] args)
{
    EventLogger.EventLogSource = Settings.Default.EventLogSource;
    EventLogger.EventLogSourceCreation = EventLogSourceCreation.Installer;

    var url = ConfigurationManager.AppSettings["serverUrl"];
    _webApp = WebApplication.Start<WebAppStartup>(url);

    var msg = string.Format("Server running on {0}", url);
    ConsoleWriteLine(msg);
    EventLogger.TryWriteInformation(msg);

    if (ConsoleMode)
    {
        ConsoleWriteLine("Press Enter to stop program");
        Console.ReadLine();
        OnStop();
    }
}

protected override void OnStop()
{
    EventLogger.TryWriteInformation(string.Format("Service stopping at {0}",
        DateTime.Now.ToString("G")));

    if (null != _webApp)
        _webApp.Dispose();
}
```
#### JavaScript side:

```
<script src="~/Scripts/jquery.signalR-1.1.2.js"></script>
<!-- <script src="~/signalr/hubs"></script> -->

<script>
    $(function () {
        //jQuery.support.cors = true; //force cross-site scripting
        var connection = $.hubConnection('@signalrUrl');
        //connection.start({ transport: 'longPolling', xdomain: true });
        //connection.start({ jsonp: true, transport: 'longPolling' });
        connection.start();
        var batchUploadHub = connection.createHubProxy("batchUploadHub");

        // ... rest omitted for brevity
    });
</script>
```
#### Research

I've gone through a number of posts such as the below and others; seems like since 0.5.3 it's supposed to just work but isn't for me. Any ideas are appreciated as I've been going round and round with it for a while now.

http://stackoverflow.com/questions/9984534/signalr-cross-domain-connections-cors-access-control-allow-origin-issues
http://stackoverflow.com/questions/15177088/signalr-across-domains-errors-with-not-allowed-by-access-control-allow-origin
http://stackoverflow.com/questions/15467373/signalr-1-0-1-cross-domain-request-cors-with-chrome
https://github.com/SignalR/SignalR/issues/599

**Comment by joaquimsimao** [comment]
Estou com o mesmo erro ao publicar no serviço do azure, alguém conseguiu resolver?
