### ISSUE TITLE
Version SignalR 2.0.0-beta2 Could not load type... error!

### ISSUE THREAD

**Issue by ghost** [SignalR/SignalR#2242]
Server Error in '/' Application.

Could not load type 'Microsoft.AspNet.SignalR.Hosting.IWebSocketRequest' from assembly 'Microsoft.AspNet.SignalR.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.TypeLoadException: Could not load type 'Microsoft.AspNet.SignalR.Hosting.IWebSocketRequest' from assembly 'Microsoft.AspNet.SignalR.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[TypeLoadException: Could not load type 'Microsoft.AspNet.SignalR.Hosting.IWebSocketRequest' from assembly 'Microsoft.AspNet.SignalR.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.]
   Microsoft.Owin.Host.SystemWeb.<>c__DisplayClass1.<GetRethrowWithNoStackLossDelegate>b__0(Exception ex) +73
   Microsoft.Owin.Host.SystemWeb.Utils.RethrowWithOriginalStack(Exception ex) +37
   Microsoft.Owin.Host.SystemWeb.CallContextAsyncResult.End(IAsyncResult result) +153
   Microsoft.Owin.Host.SystemWeb.OwinHttpHandler.EndProcessRequest(IAsyncResult result) +34
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9628700
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.18045

**Comment by dharmmaurya563** [comment]
Not fix yet. Check and Help me

![image](https://user-images.githubusercontent.com/26319302/33898868-a8fe643c-df8f-11e7-93ad-8eee8096e2a5.png)

![image](https://user-images.githubusercontent.com/26319302/33898915-cda6151e-df8f-11e7-9759-931f9a23928c.png)
