### ISSUE TITLE
Add a wrapper (or code samples) for using WebRTC with SignalR

### ISSUE THREAD

**Issue by klinden** [SignalR/SignalR#2287]
It would be nice if there was a WebRTC wrapper for SignalR similar to what XSockets has (http://xsockets.net/api/webrtc-api). Or at least if there were some official code samples on how to get setup with this.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
