### ISSUE TITLE
The connection id is in the incorrect format.

### ISSUE THREAD

**Issue by andreamaruccia** [SignalR/SignalR#2292]
Hi there,

I've a balanced system with SignalR app deployed. I get many of this errors:

"The connection id is in the incorrect format."
- I do not have any special auth implemented (only anonymous)
- I've installed sql as backplane but it didn't remove the errors

In event viewer i get some more error details:

Request information: 
    Request URL: http://XXX.XXX.XXX/signalr/connect?transport=serverSentEvents&connectionToken=8qk64WPCj67YCco2I4A5EFg9rHdBvNeZ0J7eUHAORRSOHLZpId7qdZ6_Jfw8rVcv-k01-C5RlohVVX6nypOzatrFEGqvZqL-eBM8BXpJzTU6g9E0uPTmgW2CmbV0oW4MH1l95Id3Vawv2dxIzBHF5XBoVVWaFlUZyk-ZPGkoc4xMPcnJa2X9sH6XZdMXaxou0&connectionData=[{"name":"yomohub"}]&tid=9 
    Request path: /signalr/connect 
    User host address: 10.127.103.111 
    User:  
    Is authenticated: False 
    Authentication Type:  
    Thread account name: DOMAIN\USER 

Thread information: 
    Thread ID: 24 
    Thread account name: DOMAIN\USER
    Is impersonating: False 
    Stack trace:    at Microsoft.Owin.Host.SystemWeb.Infrastructure.ErrorState.<>c__DisplayClass1.<GetRethrowWithNoStackLossDelegate>b__0(Exception ex)
   at Microsoft.Owin.Host.SystemWeb.CallContextAsyncResult.End(IAsyncResult result)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

The strange thing is that when i paste that url in  a webbrowser it works only 1/3 times. I guess that connection id can be used only with the webserver that started it. I thought this would have been fixed installing the backplane.

What am i doing wrong?

Cheers,
Andrea

PS: i renamed server url with XXX and domain user for privacy

**Comment by arindamdat** [comment]
@davidfowl : is there a way by which I can tell signalR to not use MachineKey and to use a specified certificate to sign the connectionToken?
