### ISSUE TITLE
C++ Client To Do

### ISSUE THREAD

**Issue by JunTaoLuo** [SignalR/SignalR#2346]
- [ ] Find C++ mock framework for unit tests
- [ ] Chained callbacks
- [ ] Templated Callbacks (to handle states and accomodate function pointers...)
- [ ] LongPolling
- [ ] AutoTransport
- [ ] HubConnections
- [ ] Certs
- [ ] Abort hangs very frequently 

Code that differs from the C# Client
- ExceptionHelper
- StringHelper
- TaskAsyncHelper (should use pplpp instead for Delay())
- AsyncStreamReader::ReadAsyncIntoBuffer()

**Comment by moozzyk** [comment]
C++ client is actually there: https://github.com/aspnet/SignalR-Client-Cpp
