### ISSUE TITLE
.Net Client - Object deserialization requires Signalr.Core

### ISSUE THREAD

**Issue by ronag** [SignalR/SignalR#2350]
When using the .NET client and setting:

hubConnection.JsonSerializer.TypeNameHandling = TypeNameHandling.Objects;

The runtime starts looking for Signalr.Core when trying to deserialize server responses. Which shouldn't need to be required?

**Comment by shlatchz** [comment]
@ronag Can you please share your code, that returns TypeNameHandling.None for Signalr.Core objects? Thanks!
