### ISSUE TITLE
Latest firefox not firing clean disconnect on browser refresh

### ISSUE THREAD

**Issue by davidfowl** [SignalR/SignalR#2357]
The server is self hosted and the connection is cross domain using long polling (not jsonp).

**Comment by yesoreyeram** [comment]
@DamianEdwards In the https://github.com/SignalR/SignalR/commit/458589c299dfab2fd4441f27ff44f75f7eb6b7bf commit i can see a line

      var asyncAbort = !!connection.withCredentials && firefoxMajorVersion(window.navigator.userAgent) >= 11;

Where does the value "connection.withCredentials" is coming from? For me it is always undefined and so my asyncAbort is always false. This makes my long running abort call blocking everything in chrome and IE. Note: I am not using any cross domain calls.

Ref: http://stackoverflow.com/questions/33759013/async-signalr-abort-call?noredirect=1#comment55320300_33759013
