### ISSUE TITLE
Samsung / Android 4+ stock browser crashes when viewing sites with SignalR / SSE

### ISSUE THREAD

**Issue by GenaT** [SignalR/SignalR#2367]
Hello SignalR team!

Some time ago we faced the issue with the stock Android browser crashing (shutting suddenly without showing an alert) when viewing our portal.

I reported the issue to Android / Samsung having attached the device LogCat retrieved through Android SDK Monitor:

http://developer.samsung.com/forum/thread/stock-browser-crashes-on-galaxy-tab-2-and-galaxy-note-ii/202/239894?boardName=General&startId=zzzzz~
https://code.google.com/p/android/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars&groupby=&sort=&id=57518

![fatallog-1](https://f.cloud.github.com/assets/5121521/879070/373ea824-f921-11e2-8eab-6a845db15e5f.png)

We continued the investigation and it occurred that the problem is caused by SignalR, to be more exact by its Server Sent Events transport (selected by SignalR internally).

Hosting OS is Windows Server 2008 R2 Enterprise.
IIS version - 7.5.7600.16385.

First of all it seems strange that SSE transport is established for SignalR communication despite that the 2 tables suggest that SSE is not supported for Android:

http://www.asp.net/signalr/overview/getting-started/supported-platforms
http://caniuse.com/#feat=eventsource

If I explicitly / forcibly specify ‘longPolling’ transport when starting SignalR communication no issues occur with the stock Android browser when viewing our portal.

I also could reproduce the issue on some public SignalR samples (mentioned here - https://github.com/SignalR/SignalR/wiki/Projects-Using-SignalR):

https://compilify.net
http://elmahr.apphb.com
http://postworthy.com

To save time I have not checked other sample sites as they required registration.

The stock browser crashes on Compilify and ElmahR if you open them in the browser, press Stop button (before the page finishes loading) and then press Reload/ Refresh.
Postworthy crashes if you simply try to open it in the browser.
On Android Emulator (OS version  4.1.2) Compilify works OK while ElmahR and Postworthy just do not open (the home page remains blank while the browser is indefinitely trying to load content).

The bug is reproduced on the two devices:

1)Tablet Galaxy Tab 2
  Model: GT-P5100
  Android version: 4.0.4
  Firmware version: P5100XXLF2
  Assembly number: IMM76D.P5100XWBLF3
  Core version:
    3.0.8-798305-user
    dpi@DELL128#1
    SMP PREEMPT Thu Jun 28 09:27:47 KST 2012

2) Smartphone Galaxy Note II
   Model: GT-N7100
   Android version: 4.1.2
   Firmware version: N7100XXDLK7
   Assembly number: JZ054K.N7100XXDMC3
   Core version:
    3.0.31-1071214
    se.infra@SEP-117#1
    SMP PREEMPT Wed Mar 27 10:33:53 KST 2013

The bug is not reproduced on

Smartphone Galaxy S Plus
Model: GT-I9001
Android version: 2.3.6
Firmware version: I9001XXKPG
Assembly number: GINGERBREAD.XXKPS
Core version:
    2.6.35.7-perf
    root@DELL89 #1

Thanks!

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
