### ISSUE TITLE
JavaScript: Uncaught TypeError

### ISSUE THREAD

**Issue by kzfabi** [SignalR/SignalR#2374]
We are getting the following error:

**Uncaught TypeError: Property 'jQuery18309300050840247422_1374670377838' of object [object DOMWindow] is not a function**

At:
**http://_SOME_URL_/signalr/hub/poll?transport=longPolling&connectionToken=hb6Wl5SCptSjLmDl0GE6q-_tUBTseKOXyGHMD6azfrzUQpEJLiCsxoKMkkBUQsyLAvxWsmbxUYZsFlZHQUhLIx3TSRxbNr83EFrq3hW3pcW0BmuL5sBZcpZrEax**

User Agents getting this error:
- Mozilla/5.0 (Linux; U; Android 4.0.4; es-us; GT-I9100 Build/IMM76D) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
- Mozilla/5.0 (Linux; U; Android 4.1.2; es-us; GT-I9300 Build/JZO54K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
- Mozilla/5.0 (Linux; U; Android 4.2.2; es-us; GT-I9500 Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30

GT-I9100 = Samsung Galaxy S2
GT-I9300 = Samsung Galaxy S3
GT-I9500 = Samsung Galaxy S4

We are starting SignalR as follows:

``` javascript
$.connection.hub.start({ jsonp: true, transport: 'longPolling' }).done(function (myHubConnection) {
    // SignalR has connected
});
```

We found on StackOverflow that it could be related to **jsonp** beeing used in AJAX requests, and we are indicating SignalR to use **jsonp**:
http://stackoverflow.com/questions/6547657/uncaught-typeerror-property-is-not-a-function-after-page-has-loaded

Could this be a compatibility issue between the browser and SignalR?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
