### ISSUE TITLE
Closing Firefox/Opera tab does not trigger OnDisconnected event

### ISSUE THREAD

**Issue by gustavo-armenta** [SignalR/SignalR#2400]
REPRO STEPS
1. Add Microsoft.AspNet.SignalR.Samples\Hubs\HubConnectionAPI\HubConnectionAPI.cs on selfhost project in dev branch
2. Start selfhost project
3. Change sample to connect to the selfhost server by editing file Microsoft.AspNet.SignalR.Samples\Hubs\HubConnectionAPI\HubConnectionAPI.js
$.connection.hub.url = "http://localhost:8080/signalr";
4. On IE, navigate to http://localhost:40476/Hubs/HubConnectionAPI/Default.aspx
5. On Firefox, navigate to http://localhost:40476/Hubs/HubConnectionAPI/Default.aspx
6. Closing Firefox browser or closing Firefox tab does not trigger the OnDisconnected event (IE browser never sees the firefox client disconnected). Navigating to another page triggers OnDisconnected.

**Comment by IsaacSchemm** [comment]
Is this still necessary for more recent versions of Firefox?

I commented out the `if (isFirefox11OrGreater) { ... }` block in jquery.signalR-2.2.1.js, and disconnection seemed to work (closed cleanly) on Firefox 49.

**Comment by moozzyk** [comment]
It would be good to know what version of Firefox it was enabled in.
