### ISSUE TITLE
Add .NET servicing attribute to all assemblies

### ISSUE THREAD

**Issue by DamianEdwards** [SignalR/SignalR#2444]
For .NET 4.5 assemblies:

``` CSharp
[assembly: AssemblyMetadata("Serviceable", "True")]
```

For .NET 4.0 client:

``` CSharp
#if NET40
namespace System.Reflection
{
    [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true, Inherited = false)]
    internal sealed class AssemblyMetadataAttribute : Attribute
    {
        public AssemblyMetadataAttribute(string key, string value)
        {
            Key = key;
            Value = value;
        }

        public string Key { get; set; }
        public string Value { get; set; }
    }
}
#endif
```

**Comment by Vinoth-deva** [comment]
Hi any one have idea, Iam getting this error 

Could not load type 'Microsoft.Practices.EnterpriseLibrary.Common.Configuration.Manageability.ConfigurationElementManageabilityProviderAttribute' from assembly 'Microsoft.Practices.EnterpriseLibrary.Common, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

**Comment by davidfowl** [comment]
That error has nothing to do with SignalR.

**Comment by Vinoth-deva** [comment]
> That error has nothing to do with SignalR.

Okay.  Thanks for the reply.
