### ISSUE TITLE
OnDisconnect and OnReconnect events call bug

### ISSUE THREAD

**Issue by UsmanSabir** [SignalR/SignalR#2451]
Using:
SignalR 1.1.2
iis on windows server 2008
js client with transport: longpolling

1- OnDisconnect, OnReconnect events have call sequence bug in invocation. disconnect event is called first and after that reconnect event is invoked for same connection.

2- Some times disconnect event is called for connection but same client still can send messages to server.

We are using signalr in phonegap chat app on ios. After much attempts still I can't reproduce. it occurs occasionally. Mostly it occurs when iphone app moved to background and switched to sleep mode, connection get lost from server, then on reopening app this issue raised but not always :)

I dont know how you can test phonegap app, anyway link is here 
https://build.phonegap.com/apps/412575/builds

**Comment by syedabdulaala** [comment]
This is happening again.
First _OnDisconnect_ is invoked then _OnReconnect_ invokes. This only happens when user switch to different network or VPN. On the client-side, everything is perfect only _onReconnecting_ and _onReconnected_ callbacks are invoked.
