### ISSUE TITLE
Closing Firefox/Opera tab does not trigger OnDisconnected event

### ISSUE THREAD

**Issue by halter73** [SignalR/SignalR#2517]
REPRO STEPS
1. Add Microsoft.AspNet.SignalR.Samples\Hubs\HubConnectionAPI\HubConnectionAPI.cs on selfhost project in dev branch
2. Start selfhost project
3. Change sample to connect to the selfhost server by editing file Microsoft.AspNet.SignalR.Samples\Hubs\HubConnectionAPI\HubConnectionAPI.js
$.connection.hub.url = "http://localhost:8080/signalr";
4. On IE, navigate to http://localhost:40476/Hubs/HubConnectionAPI/Default.aspx
5. On Firefox, navigate to http://localhost:40476/Hubs/HubConnectionAPI/Default.aspx
6. Closing Firefox browser or closing Firefox tab does not trigger the OnDisconnected event (IE browser never sees the firefox client disconnected). Navigating to another page triggers OnDisconnected.

https://github.com/SignalR/SignalR/issues/2400

**Comment by priteshtechark** [comment]
I am still facing this issue in  signalr 2.2.2. One workaround I found is comment out window.setTimeout from jquery.signalR-2.2.2.js file. I am not sure if this has any other impact but it calls OnDisconnected  immediately when page reloads.

![image](https://user-images.githubusercontent.com/35554119/108806444-b32dd880-75c7-11eb-87a1-6c6f4b4b9cb7.png)
