### ISSUE TITLE
Console application running on Mono 3.2.1 and connected to remote HubConnection is failed

### ISSUE THREAD

**Issue by yeddahsu** [SignalR/SignalR#2550]
I tried to create one asp.net web application as SignalR server(OS: win 7) and deployed one C# console application as SignalR client(OS: ubuntu 12.10, mono version:Mono JIT compiler version 3.2.1 ).When I ran console application on ubuntu(Command: mono xxx.exe), I got the error message as below, could you give me some suggestions for the issue? Thanks.

```
There was an error opening the connection:System.NotImplementedException: This method must be implemented in derived classes
  at System.Net.WebRequest.set_ImpersonationLevel (TokenImpersonationLevel value) [0x00000] in <filename unknown>:0
  at (wrapper remoting-invoke-with-check) System.Net.WebRequest:set_ImpersonationLevel (System.Security.Principal.TokenImpersonationLevel)
  at System.Net.Http.WebRequestHandler.CreateWebRequest (System.Net.Http.HttpRequestMessage request) [0x00000] in <filename unknown>:0
  at System.Net.Http.HttpClientHandler+<SendAsync>c__asyncC.MoveNext () [0x00000] in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <filename unknown>:0
  at System.Net.Http.HttpClient+<SendAsyncWorker>c__async5.MoveNext () [0x00000] in <filename unknown>:0
```
### The source code is:

``` C#
            var connection = new HubConnection("http://172.19.66.104:8081/");
            IHubProxy myHub = connection.CreateHubProxy("ApiHub");

            connection.Credentials = CredentialCache.DefaultNetworkCredentials;

            try
            {

                myHub.On("broadcastMessage", message => 
                   Console.WriteLine("Receive action: {0} and sending http post request: schedule?commit={1}&&channelid=999", message, commitLst[message]));

               connection.Start().ContinueWith(task =>
                {
                    if (task.IsFaulted)
                    {
                        log.Info("There was an error opening the connection:{0}",
                                          task.Exception.GetBaseException());

                        Console.WriteLine("There was an error opening the connection:{0}",
                                          task.Exception.GetBaseException());
                    }
                    else
                    {
                        log.Info("Connected");
                        Console.WriteLine("Connected");
                    }

                }).Wait();

                Console.WriteLine("Connection status : " + connection.State.ToString());

            } catch (Exception e){
                Console.WriteLine(e.Message + e.StackTrace.ToString());

            }
```

**Comment by neographikal** [comment]
Mono 3.2.6 and Signalr 2.2 has the same problem.

**Comment by kanpinar** [comment]
Same here,
Linux version 4.1.13+ (dastaan@persia) (gcc version 5.3.1 20160101 (Ubuntu/Linaro 5.3.1-5ubuntu1) 
Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-10)**
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  armel,vfp+hard
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen

System.AggregateException: One or more errors occured ---> System.NotImplementedException: This method must be implemented in derived classes
  at System.Net.WebRequest.set_ImpersonationLevel (TokenImpersonationLevel value) [0x00000] in <filename unknown>:0
  at (wrapper remoting-invoke-with-check) System.Net.WebRequest:set_ImpersonationLevel (System.Security.Principal.TokenImpersonationLevel)
  at System.Net.Http.WebRequestHandler.CreateWebRequest (System.Net.Http.HttpRequestMessage request) [0x00000] in <filename unknown>:0
  at System.Net.Http.HttpClientHandler+<SendAsync>c__async0.MoveNext () [0x00000] in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[System.Net.Http.HttpResponseMessage].GetResult () [0x00000] in <filename unknown>:0
  at System.Net.Http.HttpClient+<SendAsyncWorker>c__async0.MoveNext () [0x00000] in <filename unknown>:0
  --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.Wait (Int32 millisecondsTimeout, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0
  at System.Threading.Tasks.Task.Wait () [0x00000] in <filename unknown>:0
  at signalr.SocketConnector.get_MessageProxy () [0x00000] in <filename unknown>:0
  at signalr.SocketConnector.Invoke (System.String method, System.Object[] args) [0x00000] in <filename unknown>:0
 --> (Inner exception 0) System.NotImplementedException: This method must be implemented in derived classes
  at System.Net.WebRequest.set_ImpersonationLevel (TokenImpersonationLevel value) [0x00000] in <filename unknown>:0
  at (wrapper remoting-invoke-with-check) System.Net.WebRequest:set_ImpersonationLevel (System.Security.Principal.TokenImpersonationLevel)
  at System.Net.Http.WebRequestHandler.CreateWebRequest (System.Net.Http.HttpRequestMessage request) [0x00000] in <filename unknown>:0
  at System.Net.Http.HttpClientHandler+<SendAsync>c__async0.MoveNext () [0x00000] in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[System.Net.Http.HttpResponseMessage].GetResult () [0x00000] in <filename unknown>:0
  at System.Net.Http.HttpClient+<SendAsyncWorker>c__async0.MoveNext () [0x00000] in <filename unknown>:0


root@raspberrypi:/home/pi/Desktop/myapp# mono -V
**Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-10)**
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  armel,vfp+hard
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen
root@raspberrypi:/home/pi/Desktop/myapp# cat /proc/version
**Linux version 4.1.13+ (dastaan@persia) (gcc version 5.3.1 20160101 (Ubuntu/Linaro 5.3.1-5ubuntu1) )** #2 Sun Jan 31 11:02:27 IST 2016
root@raspberrypi:/home/pi/Desktop/myapp#

**Comment by kanpinar** [comment]
When i added system.dll from windows ... Then Certificate error accurs.

**Comment by kanpinar** [comment]
Error is;

Unhandled Exception:
System.InvalidProgramException: Invalid IL code in System.Net.ServicePointManager:set_ServerCertificateValidationCallback (System.Net.Security.RemoteCertificateValidationCallback): method body is empty.

  at signalr.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidProgramException: Invalid IL code in System.Net.ServicePointManager:set_ServerCertificateValidationCallback (System.Net.Security.RemoteCertificateValidationCallback): method body is empty.

  at signalr.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0

**Comment by moozzyk** [comment]
Looks like there is a bug on Mono side tracking this: https://bugzilla.xamarin.com/show_bug.cgi?id=17582

**Comment by kanpinar** [comment]
After a few tryouts,
Chaged target platform from 4.5 to 4
Removed windows assemblies
at last it is working...

But 4.5 would be good...
If it would help my code like this
Client : Console App, i took from internet by googling
appconfig:<supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0" />

 public class Program
    {
        static void Main(string[] args)
        {
            var connector = new SocketConnector();
            connector.UpdateNotificationsCount(9);
            Console.ReadKey();
        }
}

 public class SocketConnector
    {
        //private static readonly Logger Logger = LogManager.GetCurrentClassLogger();

        public HubConnection _hubConnection;
        public IHubProxy _messageProxy;
        private IHubProxy MessageProxy
        {
            get
            {
                if (_messageProxy != null && _hubConnection.State == ConnectionState.Connected)
                {
                    return _messageProxy;
                }
                _hubConnection = new HubConnection("http://192.168.1.34");
                _hubConnection.JsonSerializer.Culture = CultureInfo.GetCultureInfo("tr-TR");

                _messageProxy = _hubConnection.CreateHubProxy("HubConnectionAPI");
                _messageProxy.JsonSerializer.Culture = CultureInfo.GetCultureInfo("tr-TR");

                _messageProxy.On<string>("displayMessage", (data) =>
                {
                    Console.WriteLine(data);
                });
                _hubConnection.Start().Wait();
                return _messageProxy;
            }
        }

        private void Invoke(string method, params object[] args)
        {
            try
            {
                //Logger.Trace("Invoking method {0}", method);
                MessageProxy.Invoke(method, args);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                //Logger.ErrorException(string.Format("Invoke {0} error.", method), ex);
            }
        }

        public void UpdateNotificationsCount(long memberKey)
        {
            Console.WriteLine("invoke");
            Invoke("UpdateNotificationsCount", memberKey, 10);
        }
    }


Server :

[assembly: OwinStartup(typeof(ServerApp.Startup))]

namespace ServerApp
{
    public partial class Startup
    {
        public void Configuration(IAppBuilder app)
        {
           
            ConfigureAuth(app);
             app.MapSignalR();
        }
    }
}

 public class HubConnectionAPI : Hub
    {
        public override Task OnConnected()
        {
            return base.OnConnected();
        }
        public override Task OnDisconnected(bool stopCalled)
        {
            return base.OnDisconnected(stopCalled);
        }

        public override Task OnReconnected()
        {
            return base.OnReconnected();
        }
    }


 public class WebApiApplication : System.Web.HttpApplication
    {
        static IScheduler Scheduler;
        protected void Application_Start()
        {
            AreaRegistration.RegisterAllAreas();
            GlobalConfiguration.Configure(WebApiConfig.Register);
            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            RouteConfig.RegisterRoutes(RouteTable.Routes);
            BundleConfig.RegisterBundles(BundleTable.Bundles);

            ISchedulerFactory schedFact = new StdSchedulerFactory();
            Scheduler = schedFact.GetScheduler();
            Scheduler.Start();
            var seconds = 1;

            IJobDetail job = JobBuilder.Create<MyJob>()
                .WithIdentity("MyJob", "group1")
                .UsingJobData("Param1", "Hello MyJob!")
                .Build();

            ITrigger trigger = TriggerBuilder.Create()
                .WithIdentity("MyJobTrigger", "group1")
                .StartNow()
                .WithSimpleSchedule(x => x.WithIntervalInSeconds(seconds).RepeatForever())
                .Build();

            Scheduler.ScheduleJob(job, trigger);
        }

    }

    public class MyJob : IJob
    {
        //static readonly ILog log = LogManager.GetLogger(typeof(WebApiApplication));

        public void Execute(IJobExecutionContext context)
        {
            Debug.WriteLine("----");
            //log.Info("My job executed");
            JobDataMap dataMap = context.JobDetail.JobDataMap;
            //log.Info(dataMap["Param1"]);
            //Debug.WriteLine(dataMap["Param1"]);
            var hubContext = GlobalHost.ConnectionManager.GetHubContext<HubConnectionAPI>();
            hubContext.Clients.All.displayMessage(DateTime.Now.ToString("dd.MM.yyy hh:mm:ss"));

        }
    }

working on 

qemu\qemu-system-arm.exe -kernel raspbian\kernel-qemu-4.1.13-jessie -m 256 -M versatilepb -cpu arm1176 -serial stdio -append "root=/dev/sda2 rootfstype=ext4 rw" -hda raspbian\2016-02-26-raspbian-jessie.img -redir tcp:50022::22

but there is a holly thing -m 256 can not be bigger :( i think versatilepb couses


hope it helps some one..
