### ISSUE TITLE
DefaultMessageBufferSize doesn't limit the number of messages

### ISSUE THREAD

**Issue by ChrisHimsworth** [SignalR/SignalR#2555]
I have been trying to use GlobalHost.Configuration.DefaultMessageBufferSize to limit the amount of messages stored in memory as I have an app that polls a database every 2 seconds and sends 5 separate messages, of which one of them can be up 87KB.

If you see http://www.asp.net/signalr/overview/performance-and-scaling/signalr-performance#tuning, SignalR configuration settings, DefaultMessageBufferSize.
It implies that this will limit the number of messages stored in memory.

But, looking through the source code for the use of DefaultMessageBufferSize, it seems to only set the initial capacity of the MessageStore, not the maximum capacity (i'm basing this on the code in constructor for Microsoft.AspNet.SignalR.Messaging.MessageStore).

**Comment by Brain2000** [comment]
Here are my thoughts after looking at the source.  Forgive me if I have anything wrong here:

It looks like DefaultMessageBufferSize sets the size per Topic created, which I believe is a one-to-one correlation for each unique Group name that you add a connection to.  Each Topic contains a MessageStore, which is basically a "Ring" buffer (I think Cisco Ethernet TX ring) where queued Messages are kept.

When a new MessageStore is created, it uses this formula:

minFragmentCount = 4
maxFragmentSize = 16384 for 32 bit, and 8192 for 64 bit (assume 64 bit here)
DefaultMessageBufferSize = 1000 (default)

fragmentCount = Max(minFragmentCount, DefaultMessageBufferSize / maxFragmentSize) = Max(4, 1000 / 8192) = 4
fragmentSize = Min((DefaultMessageBufferSize + fragmentCount - 1) / fragmentCount, maxFragmentSize) = Min((1000 + 4 - 1) / 4, 8192) = 250
fragments = new Fragment[fragmentCount + 1]

This will give you 4 fragments each containing an array of 250 Messages = 1000 Messages total per Topic.  The fragmentCount and fragmentSize variables never change, though fragments start to be swapped out once the TX ring has circled around and starts reusing the 4 fragment slots.

So if you have 100 groups, each with a buffer of 1000 messages, will give you a combined buffer potential of 100,000 messages, but you would have to send each Group 1000 messages to hit that number.  If each message is 50k (which is really on the high side), that would be almost 5GB worth of buffer storage.  It may also be worth noting that if a Group reaches 0 subscribers, it will deallocate itself after a period of time.

Each message sent to a Group only adds ONE item to that Group's MessageStore buffer, and each Connection in the Group then has an associated Broker that is scheduled to fetch and send the Message down the Connection.  For example, if you send a single Message to a Group with 10 Connections, it will not add 10 Messages to the buffer, but only one!

I am running a server that hosts around 20,000 groups, so therefore, I have turned my DefaultMessageBufferSize down to 100 to avoid out of memory errors once each group has filled the ring buffers.

It would be nice if there was an optional parameter to remove old messages after a timer expires.  Maybe I'll override the MessageStore class and add that [someyear when I have free time...]
