### ISSUE TITLE
WebSockets transport pings the wrong server URL.

### ISSUE THREAD

**Issue by NTaylorMullen** [SignalR/SignalR#2569]
This is a blatant bug.  We special case websockets when creating the URL and we shouldn't.

**Comment by arc95** [comment]
I've downloaded 2.2.2 and the issue is still there. The solution [above](https://github.com/SignalR/SignalR/issues/2569#issuecomment-29890698) seems to work, but it's only in the non-minified JS file. How do I add it to the minified one?
