### ISSUE TITLE
InvalidOperationException : "Connection started reconnecting before invocation result was received"

### ISSUE THREAD

**Issue by nazbrok** [SignalR/SignalR#2631]
Hi,

I am using SignalrR 1.1.3 with Silverlight 5 in LongPolling.

When I start a long running process on the server from the client, I always get this exception if a reconnection happen before the server finish it's jobs.

Is this a bug or something I should take care of in my application (and how) ?

Regards

**Comment by rajeevBlr** [comment]
@davidfowl please help with this issue. I am using Microsoft.AspNet.SignalR 2.4.1 and Microsoft.AspNet.SignalR.Client 2.4.1

I am invoking method on HubProxy within WebAPI controller API.

`  public async Task SaveNew([FromBody]InputParameter inputParameters)
        {
                   await hubProxy.Invoke("Method", arguments);
        }`

At times I get '**Connection started reconnecting before invocation result was received**' error message. 

at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SignalR.UpdateNotifier.<SendUpdatedScenario>d__7.MoveNext() in D:\XXX\Source\APP\src\WEBAPI\SignalR\ABC.cs:line 79
--- End of stack trace from previous location where exception was thrown ---

**Comment by halter73** [comment]
> 'Connection started reconnecting before invocation result was received'

This means that the underlying TCP connection died during the invocation of "Method". SignalR will automatically try to reconnect by reestablishing a TCP connection, but it will simply retry the invocation of "Method" because the client doesn't know whether or not the server received the invocation. Instead, the client just fails the invocation with an exception.
