### ISSUE TITLE
Add ability to provide a strongly typed object as a client hub proxy

### ISSUE THREAD

**Issue by DamianEdwards** [SignalR/SignalR#2639]
Now that we have the ability to define an interface that represents the client hub proxy when declaring the server hub type (see #2449) we should allow that same interface to be used to provide a typed client hub proxy, rather than using proxy.On("methodName").

More detail to come...

**Comment by delfuria** [comment]
Hi, any news about this implementation ?
When will it be available as V3 ?
Thanks
