### ISSUE TITLE
Scale-out providers should support a "send only" mode

### ISSUE THREAD

**Issue by DamianEdwards** [SignalR/SignalR#2688]
The scale-out providers for SQL, Redis & Service Bus should all support a mode where they only send messages to the back-plane but they don't receive any messages. This is useful in cases where you want to send messages to clients through the back-plane from something not running in the web application, e.g. a Windows service.

**Comment by mdentremont** [comment]
@DamianEdwards Just curious if this was ever implemented - and if not - do you have a link to a replacement ticket?
