### ISSUE TITLE
Calling Client Disconnect manually

### ISSUE THREAD

**Issue by raghav-axero** [SignalR/SignalR#269]
Hi,

We can get the clients of a hub via 

```
   var connectionManager = AspNetHost.DependencyResolver.Resolve<IConnectionManager>();
   dynamic clients = connectionManager.GetClients<MyHub>();
```

Can you let me know how can I disconnect this client manually via code (server side c#). I want to disconnect the client on click of some asp.net button via codebehind. Can you help me in doing it?

**Comment by DivyaaPatel** [comment]
If the Same User gets connected from more than one browser instance than that person is needed to disconnect forcibly from 1st instance to connect through 2nd instance. so even i think disconnecting forcibly should be allowed

**Comment by nohimys** [comment]
I have a requirement as such. 
I'm using a WPF Clients with a WPF Standalone Server and I've written my own logic to manage the connection, through OnConnected() & OnDisconnected(). I'm mapping the users according to their username & ONLY ONE USERNAME SHOULD BE CONNECTED AT A TIME. That's my requirement. Which means if two clients try to connect from the same same username, the 2nd client should be blocked & disconnected. I could do this easily if a forcefully disconnecting method from the server was available.

**Comment by hollow87** [comment]
Placing trust to behave properly in the client's hand is bad idea. I guess the server side portion could communicate with an external firewall to ensure the client disconnects when told to but that increases complexity and dependence on another technology when similar frameworks to SignalR suppport server side disconnection of clients.
