### ISSUE TITLE
SignalR “signalr/hubs” giving 404 error in a Custom DotNetNuke Module

### ISSUE THREAD

**Issue by isumh** [SignalR/SignalR#281]
I  have added SignalR.Hosting.AspNet.dll (reference) and SignalR.dll, and web.config:

<pre><code>&lt;configuration&gt;
   &lt;system.webServer&gt;
        &lt;validation validateIntegratedModeConfiguration="false" /&gt;
        &lt;modules runAllManagedModulesForAllRequests="true"&gt;
        &lt;/modules&gt;
    &lt;/system.webServer&gt;
&lt;/configuration&gt;
</code></pre>

custom DotNetNuke Module ascx file:

<pre><code>
&lt;%@ Control Language=&quot;C#&quot; AutoEventWireup=&quot;true&quot; CodeBehind=&quot;SignalTestView.ascx.cs&quot;
    Inherits=&quot;SignalRTest.SignalTestView&quot; %&gt;
&lt;script type=&quot;text/javascript&quot; src=&#39;&lt;%= ResolveClientUrl(&quot;~/signalr/hubs&quot;) %&gt;&#39;&gt;&lt;/script&gt;
&lt;script type=&quot;text/javascript&quot;&gt;
    $(function () {
        // Proxy created on the fly=
        var chat = $.connection.chat;

        // Declare a function on the chat hub so the server can invoke it
        chat.addMessage = function (message) {
            $(&#39;#messages&#39;).append(&#39;&lt;li&gt;&#39; + message + &#39;&lt;/li&gt;&#39;);
        };

        $(&quot;#broadcast&quot;).click(function () {
            // Call the chat method on the server
            chat.send($(&#39;#msg&#39;).val())
            .done(function () {
                //console.log(&#39;Success!&#39;);
            })
            .fail(function (e) {
                console.warn(e);
            });
        });

        // Start the connection
        $.connection.hub.start();
    });
     
&lt;/script&gt;
&lt;input type=&quot;text&quot; id=&quot;msg&quot; /&gt;
&lt;input type=&quot;button&quot; id=&quot;broadcast&quot; value=&quot;broadcast&quot; /&gt;
&lt;ul id=&quot;messages&quot;&gt;
&lt;/ul&gt;
&lt;p&gt;
    &lt;asp:Label ID=&quot;lblMsg&quot; runat=&quot;server&quot; Text=&quot;xxx&quot; /&gt;
&lt;/p&gt; 
</code></pre>

in .ascx.cs file:

```
   protected void Page_Init(object sender, EventArgs e)
    {


       // DotNetNuke.Framework.jQuery.RequestRegistration();
        if (!Page.ClientScript.IsClientScriptIncludeRegistered("signalR"))
            Page.ClientScript.RegisterClientScriptInclude("signalR", TemplateSourceDirectory + "/scripts/jquery.signalR.js");
```

**Comment by tvmodvn** [comment]
I help me setup SignalR for dnn 9.3.2 . Thanks you
