### ISSUE TITLE
Infinite wait for connection().Start().Wait() when connection.Closed event is triggered

### ISSUE THREAD

**Issue by eriksundberg** [SignalR/SignalR#2852]
Hi!

Background info:
OS: Windows 7
IIS: 6.1
VS: 2012
.net: 4.0
SignalR: 1.2
Barebone code-sample can be found at:
https://github.com/ekaerik/SignalRTestApp
(New to git, not sure everything is in order)

We have a issue regarding when the SignalR server goes down and the connection gets disconnected, we want to wait for the connection to start before we send new messages. 

To isolate the issue we created a new solution only containing a console and web project, nothing else but bare bone. We use regular IIS for our web to have full control over the app-pool.
1. Debug the Console application, after you see some dots in the output, stop the IIS app pool for the web project.
2. Wait for "Closed event triggered" in console output
3. Start app pool again
4. BUG?: Connection does not reconnect when we wait for Start() task to finish

If you change:
SignalRTestApp.Program.Main(...) line 20 from:
connection.Start().Wait();
to:
connection.Start();

It will work as we think would be expected: When app pool starts running connection will reconnect and the Console will send stuff again.

Did we miss something obvious?

**Comment by soyuznii** [comment]
i have  signalr Self host application in windows forms but i cannot enable cross domain i suspect this is the source of my problem, because my web client is connecting fine but my xamarin android client is not able to connect
please help
