### ISSUE TITLE
SQL backplane timing out on connect

### ISSUE THREAD

**Issue by jlew-cs** [SignalR/SignalR#2864]
This is a tricky one, since it is both intermittent and some environments seem immune entirely.  Here's what I can say definitively:
- We are using SignalR 2.0.2 with the SQL backplane enabled
- SQL Server is 2008 R2 SP2
- Longpolling transport is in use in all cases (we are XDR, so no choice on this)

In multiple environments, we experience the following behavior:
- Client issues a /negotiate request, which succeeds
- Client issues a /connect request, which sits waiting for a response
- Client timeout is triggered, aborts the /connect request, and issues an /abort request
- Once the server gets in this state, it stays that way for a while (maybe forever, until the IIS process is reset?) and repeats of the scenario continue to timeout on the /connect request.
- Increasing the timeout value on the server and/or client to something like 15 seconds doesn't help (client will wait for longer, still eventually aborts the request.)  The server is not under any kind of load, and there is no legitimate reason for it taking.  

I have tried breaking in the debugger when the /connect request is in process, but have not been able to catch a meaningful stack which would let me know what is being waited on.  I reproduced this once in a bare-bones project, but have not been able to do so reliably (it seems very sensitive to timing, and on some machines it doesn't seem to ever happen.)

Attaching the server traces I captured, which don't have any obvious (to me) clues. Open to suggestions on how to debug further/provide mode information.

**Comment by ankit1552** [comment]
Jeremy , We are also facing the similar issue , we are using web socket protocol to connect to signalR , it was working fine but when we enabled scale out using SQL , we are facing connection timeout error , can you please help me out on this.
