### ISSUE TITLE
JS Client Firefox Connection Stopped beforeunload

### ISSUE THREAD

**Issue by wsaeed** [SignalR/SignalR#2886]
In JS client firefox the connection is stopped even if you click stay on page raised from on beforeunload event.

SignalR version 1.2.0

**Comment by haozhang0216** [comment]
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them. 
I have couse this error. Wander if you can help me
