### ISSUE TITLE
SignalR 2.0 Death Spiral with 80 Clients

### ISSUE THREAD

**Issue by dstrickland67** [SignalR/SignalR#2899]
Problem
Our SignalR system has a tendency to go into a death spiral.  If the SignalR project hosted in IIS gets busy enough for a short interval, the RAM usage and CPU usage will explode into a point of no return.  And even if the CPU does level out, the RAM is never, ever freed which makes it easier to spiral on the next spike.

Environment
1 publicly exposed IIS hosted machine answering client requests over a hub
2 private OWIN self hosted NServiceBuses that process data and publish deltas

The NServiceBus machines publish over a Redis scaleout backplane.  No clients connect directly to them.  The IIS machine will answer requests like "Get my configuration", "Answer my heartbeat", "What should I display since I just started up?" in addition to taking subscriptions by adding connections to groups.

Repro
Once we have about 70-80 client machines connected the IIS server is stable @ 200 MB RAM, and < 1-2% cpu.  I can use a testing webpage with a simple javascript for loop which is guaranteed to start the death spiral.

```
    function heartbeat5kBtnClick() {
        for (var i = 0; i < 5000; i++) {
            heartbeatBtnClick();
        }
    }
```

The function it calls is defined as follows;

```
    async public Task Heartbeat(Guid requestId, DateTime timestamp)
    {
        //System.Diagnostics.Debug.WriteLine("Interlocked.Increment(ref HUBCOUNT) = " + Interlocked.Increment(ref HUBCOUNT));
        try
        {
            //Response<DateTime> result = await Task.Factory.StartNew<Response<DateTime>>((stateObj) =>
            //{
            //    return _FlatScreenHubService.Heartbeat(requestId, timestamp);
            //},
            //null,
            //TaskCreationOptions.PreferFairness); // <-- This just seems to make everything worse

            Response<DateTime> result = _FlatScreenHubService.Heartbeat(requestId, timestamp);
            if (null != result) Clients.Caller.heartbeatAsyncResult(JsonHelper.JsonSerializer<Response<DateTime>>(result));       // <-- should I be awaiting this?
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine("");
            System.Diagnostics.Debug.WriteLine(ex.Message);
            System.Diagnostics.Debug.WriteLine(ex.StackTrace);
        }
        finally
        {
            //System.Diagnostics.Debug.WriteLine("Interlocked.Decrement(ref HUBCOUNT) = " + Interlocked.Decrement(ref HUBCOUNT));
        }
    }
```

This _FlatScreenHubService is a singleton object and JsonHelper is just a helper object for serialization that is used for all server responses to the client.  All we're doing is returning a datetime we use to estimate the server's clock time compared to the client's clock.

```
    [Log4NetTrace(false)]
    public Response<DateTime> Heartbeat(Guid requestId, DateTime timestamp)
    {
        Response<DateTime> result = new Response<DateTime>();
        try
        {
            result.Result = DateTime.Now;
        }
        catch (Exception ex)
        {
            result.Code = 1;
            result.Exception = ex.Message;
        }
        finally
        {
            result.Id = requestId;
            result.Timestamp = DateTime.Now;
        }
        return result;
    }
```

The JsonHelper is defined as follows;

```
public class JsonHelper
{
    public static string JsonSerializer<T> (T t)
    {
        DataContractJsonSerializer ser = new DataContractJsonSerializer(typeof(T));
        using (MemoryStream ms = new MemoryStream())
        {
            ser.WriteObject(ms, t);
            string jsonString = Encoding.UTF8.GetString(ms.ToArray());
            ms.Close();
            return jsonString;
        }
    }  
    public static T JsonDeserialize<T> (string jsonString)
    {
        DataContractJsonSerializer ser = new DataContractJsonSerializer(typeof(T));
        using (MemoryStream ms = new MemoryStream(Encoding.UTF8.GetBytes(jsonString)))
        {
            T obj = (T)ser.ReadObject(ms);
            return obj;
        }
    }
}
```

More thoughts on Repro
During the business day it's not even necessary to abuse the heartbeat function.  Once enough clients have a hiccup, the chain of reconnection calls will be enough to start a death spiral and that's the point of no return.  Out of 6644 function calls, 6643 during a 1 hour period finished in less than 170 ms.  95% finish in less than 1 ms.  Based on what we've seen in publications, there is no way this kind of load should cause a death spiral like this.  So we are puzzled if we're just doing something structurally wrong.

**Comment by a6datta** [comment]
@dstrickland-mdl Are you still using signalr? If you could give us some directions. We are having exactly the same issue with the latest version on a very low number of connections (<20 connections, 20 messages/second).

**Comment by clayu** [comment]
I am having this same issue as well with version 2.2.1

**Comment by moozzyk** [comment]
@clayu - as per https://github.com/SignalR/SignalR/issues/2899#issuecomment-40264718 it was an issue with the app. If you believe you hit a SignalR bug please open a new issue and post a repro.

**Comment by timavaza** [comment]
We are getting this as well, using latest Signalr as of June 2019.
