### ISSUE TITLE
Multiple Hubs with same name not detected server side

### ISSUE THREAD

**Issue by IanMercer** [SignalR/SignalR#29]
If I have two classes deriving from Hub and they have the same [short] name I get a javascript error in the browser but no exception is thrown on the server.  Would be nice if an exception was thrown server side highlighting this problem.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
