### ISSUE TITLE
Using Forms Authentication auth cookie will never timeout

### ISSUE THREAD

**Issue by moity** [SignalR/SignalR#2907]
Using SignalR with Forms Authentication (ASP.NET MVC4, SignalR 2.0.2.0) is it possible to have Pings and Reconnects not reissue the Auth cookie (set it's timeout further into the future)?

Basically, I want the Auth cookie to timeout (which it was doing until having SignalR in the solution).

I can see the Auth Cookie in the Response Headers being reissued on Ping and Reconnects.

I've read the documentation and searched extensively but found nothing around this - can it be done via configuration or a HubPipelineModule?

Any help appreciated.

**Comment by RavilMahmutov** [comment]
> My implementation has evolved a little but this is basically it (remember to register the module in your config, or via code):
> 
> ```
> public class SignalRFormsAuthenticationCleanerModule : IHttpModule
> {
>    public void Init(HttpApplication application)
>    {
>       application.PreSendRequestHeaders += OnPreSendRequestHeaders;
>    }
> 
>    private bool ShouldCleanResponse(string path)
>    {
>       path = path.ToLower();
>       var urlsToClean = new string[] { "/signalr/", "<and any others you require>" };
> 
>       // Check for a Url match
>       foreach (var url in urlsToClean)
>       {
>          var result = path.IndexOf(url, StringComparison.OrdinalIgnoreCase) > -1;
>          if (result)
>             return true;
>       }
> 
>       return false;
>    }
> 
>    protected void OnPreSendRequestHeaders(object sender, EventArgs e)
>    {
>       var httpContext = ((HttpApplication)sender).Context;
> 
>       if (ShouldCleanResponse(httpContext.Request.Path))
>       {
>          // Remove Auth Cookie from response
>          httpContext.Response.Cookies.Remove(FormsAuthentication.FormsCookieName);
>          return;
>       }
>    }
> }
> ```

Hi, where should i add it? in Startup.cs?

**Comment by moity** [comment]
It's an HttpModule so you register it like any other, in your web.config or via code, startup.cs will work.
