### ISSUE TITLE
Disposal of hubs (and other dependencies?) via DependencyResolver

### ISSUE THREAD

**Issue by IanYates** [SignalR/SignalR#2908]
Hi,

I've made a StackOverflow question along with my thoughts for this - http://stackoverflow.com/questions/21967542/proper-hub-dependency-lifetime-management-for-signalr-and-castle-windsor .

Some IoC containers, such as Castle Windsor, will hold on to all resolved instances so that they can be properly pooled, disposed of, etc.  The mantra being along the lines of "if you resolve it then you release it".

The IDependencyResolver interface has no means by which resolved instances can be disposed / discarded.

My immediate concern is being able to dispose of instances of Hubs.  I see that the HubDispatcher has a DisposeHubs static method which just calls hub.Dispose().  From what I can see there's no way to replace (or meaningfully inherit from) the HubDispatcher as it's wired in to Owin by the HubDispatcherMiddleware class so I'm unable to make a little personal fix and instead have to change SignalR code.  I thought if the change I'm proposing is meaningful then I could contribute it back.

The `private static void DisposeHubs(IEnumerable<IHub> hubs)` method is only called from within a single method `private Task ExecuteHubEvent(IRequest request, string connectionId, Func<IHub, Task> action)`.  I propose adding a new virtual method to the DefaultDependencyResolver (and the IDependencyResolver interface) with a default implementation that just attempts to cast as IDisposable, and if that cast succeeds, calls `Dispose()`.
This would be a breaking change for those who implemented a custom IDependencyResolver and who did not inherit DefaultDependencyResolver.

Alternatively there could be a new interface, such as IDependencyDisposer, which could be retrieved from the IDependencyResolver in the same way as any other dependency.  It would have a method that accepts instances of IDisposable (or object?).  The default implemention would do the cast to IDisposable and a subsequent .Dispose() call.  However other implementations could pass the call back to the IoC container so that the container can properly dispose of the given object as well as any other dependencies that were injected into that object that should also be disposed/released.

ASP.Net MVC and WebAPI have their own ways of achieving this.  An excellent WebAPI example is at http://blog.ploeh.dk/2012/10/03/DependencyInjectioninASP.NETWebAPIwithCastleWindsor/ .  WebAPI provides a context where the resolver can effectively add callbacks (disposal of a provided IDisposable) to be notified when the request is finished.  That callback can then do whatever is required - typically performing a container-based Release() as per the example.

Anyway, I've not done a pull request before and I'm trying to be mindful of the advice given in the "Don't push your pull requests" article :)  I'm probably also not the first to point out the difficulty with releasing resolving objects so there may well be a workaround that my search-fu couldn't locate or you may already have something in the pipeline to help with this problem.

Thanks for reading.

**Comment by asgerhallas** [comment]
Has this changed? :)

**Comment by jnm2** [comment]
Yes, when is this getting implemented?

**Comment by asgerhallas** [comment]
@davidfowl I know you have already answered, that this will be addressed, in the next major. But to my knowledge the next major is out since your answer, and I can still not find the way to do it. Am I looking in the wrong place, or did this not make the cut? :)

**Comment by Liwoj** [comment]
Hello. Why is this closed ?
Current version of IDependencyResolver (https://github.com/SignalR/SignalR/blob/master/src/Microsoft.AspNet.SignalR.Core/DefaultDependencyResolver.cs) does have some support for releasing components but only using dispose and at the end of all lifecycle. What is correct solution here ? Implement my own dispose on hubs created by my resolver ? Feels too heavy. Can i use hub instance pooling?
Thx

**Comment by IanYates** [comment]
For others, see my comment in #3387 - register as transient in Windsor, and in your code wiring SignalR and Windsor together, if it sees a Hub-descendant class being requested, immediately release the newly resolved instance from the container.  SignalR won't mind that Dispose() was called on the hub.  The way I write the code in my hubs it only has singleton dependencies so the container release doesn't do any harm there either.  If that's not the case for you, refactor your hub code so it can be completely transient and perhaps inject a typed factory into it via its constructor and use that instead (just be sure to invoke the factory *outside* of the constructor so Windsor doesn't see the factory's output as a dependency of the hub and releases it early).  Whew - long sentence!!
