### ISSUE TITLE
Forever Frame transport with Internet Explorer when loading an attachment in an iframe causes frequent slow connections and disconnects

### ISSUE THREAD

**Issue by rubisco81** [SignalR/SignalR#2926]
I've created an html page containing a iframe an a link. When the user clicks the link, the iframe source is set to the URL of an MVC controller method that generates a Word document, which is written to the response along with header _Content-Disposition: attachment; filename="downloaded.docx"_. When the document has finished being generated, I call a method "documentGenerated" in the Hub, which on the client hides a progress modal displayed when the user clicked the link. As I am on IIS 7.5, SignalR is using the ForeverFrame in Internet Explorer.

In this scenario, at least half of the link clicks result in a SlowConnection. For the user means they receive a dialog to download the file, but the modal doesn't go away until SignalR reconnects after 10 seconds, making the page unusable during this time. If I force long polling via _$.connection.hub.start({ transport: "longPolling" })_ or by using FF or Chrome, the SlowConnection never occurs and it works as expected (modal disappears at the same time the download dialog appears).

I believe this issue is identical to https://github.com/SignalR/SignalR/issues/133, however I don't believe the line number mentioned in the quick dirty fix is accurate any longer.

To reproduce the issue, in the Microsoft.AspNet.SignalR.Samples project, under Hubs/HubConnectionAPI create a page called frame.aspx with this code:

```
<%@ Page Language="C#" %>

<script language="c#" runat="server">
    void butReport_Click(object sender, EventArgs e)
    {
        this.Response.ClearContent();
        this.Response.ClearHeaders();
        this.Response.BufferOutput = true;
        this.Response.ContentType = "application/notepad";
        this.Response.AddHeader("Content-Disposition", "attachment; filename=untitled.txt");
        this.Response.Write("test");
        this.Response.Flush();
    }
</script>
<html>
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:Button ID="butReport" Text="Download" runat="server" OnClick="butReport_Click" />
        </div>
    </form>
</body>
</html>
```

Next, in the Hubs/HubConnectionAPI/Default.aspx page, add the line `<iframe src="Frame.aspx"></iframe>` after `<ul id="messages"></ul>`. Browse to the page and click the download button and wait a few seconds to notice the frequent SlowConnection messages. You may need to click a few times before this occurs.

Thanks for any assistance you can provide!

**Comment by moozzyk** [comment]
We are cutting ForeverFrame transport in the Core version of SignalR Server
