### ISSUE TITLE
Memory leaks in IE/Chrome when use SignalR longPolling

### ISSUE THREAD

**Issue by Xiaohongt** [SignalR/SignalR#2953]
I have run sample message loops which does both send and receive messages for about 12 hours on IE and Chrome using longPolling transport, the results for process memory data Working Set –Private show that there are memory leaks.

BTW, the run for directly using XMLHttpRequest to send message /post and poll/get to signalr ( just like longPolling ) in infinite loops but without SignalR js run for over 10 hours on Chrome, doesn’t show memory leaks.

**Comment by mosullivan3** [comment]
Hello, just wondering when this fix is expected to be released ? The v2.2.0 milestone looks to be Past due by 4 months already. Thanks for fixing.
regards - Michael

**Comment by halter73** [comment]
2.2.0 should be released next week.
