### ISSUE TITLE
Little documentation on SqlServer Scaleout

### ISSUE THREAD

**Issue by thomaswr** [SignalR/SignalR#2967]
Documentation about SqlServer Scaleout is very scarce. 
There are some open questions like the following.
- What does the _TableCount_ setting do exactly? How to find the proper value for an application?
  The info we have is:

```
"The number of tables to store messages in. Using more tables reduces lock
contention and may increase throughput. This must be consistent between all
nodes in the web farm. Defaults to 1."
```
- What are the reasons for and against enabling _MaxQueueLength_ setting? 
  The info we have is:

```
"The maximum length of the outgoing send queue. Messages being sent to the
backplane (SQL Server in our case) are queued up to this length. After the
max length is reached, further sends will throw an InvalidOperationException.
Defaults to disabled."
```
- More information about the meaning and correlation of performance counters

**Comment by BraveIT** [comment]
Someone can give us a explain the QueuingBehavior  values mean.
