### ISSUE TITLE
New topic: SignalR Connection Density Testing with Crank

### ISSUE THREAD

**Issue by pfletcher** [SignalR/SignalR#2980]
This topic is written and has been reviewed, and is pending a change to the Crank tool (allow it to connect to a Hub so that a Persistent Connection is not required.)

**Comment by m1729** [comment]
Hi, just wondering if this issue could be closed? The changes are already in a repo, but the documentation is still required?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
