### ISSUE TITLE
Raise event when throwing away messages?

### ISSUE THREAD

**Issue by cwt237** [SignalR/SignalR#2991]
SignalR has an internal ring buffer per signal. 

I have an application that in certain cases cannot operate correctly if a single message is lost. 

I don't want to handle this at the client side (e.g. by matching sequence numbers), since this complicates the client side design. 

I understand why the ring buffer is in place, and I can test that it does indeed throw messages away (e.g. by decreasing the buffer size to 10). I can also live with the fact that messages may be thrown away from time to time (if this happens frequently, the buffer size can be increased), however, why is there no notification of this? (e.g. an event or a callback saying that a message was lost for signal x).

My colleague asked a similar question about this at http://stackoverflow.com/questions/22830823/can-a-signalr-message-loss-be-detected-server-side without any response from the SignalR team. 

I know you prefer not to use the issue list for questions, but we regard this as a bug or at least a required feature. 

Do you have any plans to support raising events (or similar) when losing messages?

**Comment by kellyelton** [comment]
What happens when the client misses the 'MessageLost' message?

If you send lots of messages frequently I'd recommend numbering your messages and then let the client determine if it's missing something and call back to get that itself via some mechanism(I'd use http request personally).
