### ISSUE TITLE
Crank: Update tool to use Hubs connection instead of just PersistentConnection

### ISSUE THREAD

**Issue by pfletcher** [SignalR/SignalR#3000]
We discussed in the review of my testing topics that Crank should be updated to use Hubs rather than just PersistentConnection.  Two documentation topics (#2980 and #2982 ) are dependent on this change.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
