### ISSUE TITLE
Client-side unhandled exception when "reconnecting" to rebooted SignalR Hub

### ISSUE THREAD

**Issue by ghost** [SignalR/SignalR#3003]
If I quickly restart the SignalR Hub host, the client trying to reconnect gets
"WebSocket connection to 'ws://.../signalr/reconnect?transport=webSockets&connectionToken=AQAAAN...' failed: Error during WebSocket handshake: Unexpected response code: 400" which goes unhandled by the SignalR AND therefore the disconnected event never fires.  This happens consistently for me with no other server-side errors.

![image](https://cloud.githubusercontent.com/assets/5518652/2744826/6f1bd42c-c72c-11e3-9fdc-913fb695b537.png)

**Comment by Tollin** [comment]
I have got the same issue. Is there any solution about this?
My problem is, if the page stay for a long time, this error occurs. how to resolved?
