### ISSUE TITLE
Make HubCallerContext easier to mock for unit testing a Hub

### ISSUE THREAD

**Issue by DamianEdwards** [SignalR/SignalR#3012]
We want to make hubs easier to unit test. Today, if a hub method uses the Context property, it's difficult to test because the HubCallerContext type is not easily mockable.

Let's add a parameterless constructor, and make all the properties virtual. This will then allow users to easily create a dummy HubCallerContext using a mocking library (or manually) and assign it to the Context property of their hub from within their unit tests.

**Comment by Jestar342** [comment]
Why didn't you just create an interface?
