### ISSUE TITLE
Problems with ASP.NET and multiple created AppDomains

### ISSUE THREAD

**Issue by tim-cools** [SignalR/SignalR#3018]
Hi,

We are losing messages when ASP.NET and SignalR. We receive the messages from NSB, and send them to our clients based on group. The problem is that we are losing messages after a while.

After long time research I found out that our ASP.NET application creates multiple AppDomains at a regular base for some reason. At one moment, when the new AppDomain is created, it seems like the new events are processed by both the AppDomain's, but the current SignalR connection is still handled by the a single  AppDomain. This causes our sending from server to client to fail silently. We noticed because we use the HttpContext.Cache, is it seem.

I'm still figuring out how this behavior is possible. But any help would be welcome.
Does someone have experience with this situation? 

We are using LongPolling btw.

Thanks in advance,

Tim Cools

Logging example (EntLib creates a file per AppDomain):
Events sent from server from AppDomain 49 do reach the client, but the one from 51 do not.

```
4/28/2014 3:14:24 Application Started! AppDomain:51
4/28/2014 3:21:15 CalibrationClient CacheState Add '2138F402', 'IsRunning: True, IsSuccess: False, Percentage: 1, Message: ', 'AppDomain: 51'
4/28/2014 3:21:23 CalibrationClient CacheState Update '2138F402', 'IsRunning: True, IsSuccess: False, Percentage: 4, Message: ', 'AppDomain: 51'
...
4/28/2014 3:25:03 CalibrationClient CacheState Update '2138F402', 'IsRunning: True, IsSuccess: False, Percentage: 78, Message: ', 'AppDomain: 51'
4/28/2014 3:25:11 CalibrationClient CacheState Update '2138F402', 'IsRunning: True, IsSuccess: False, Percentage: 81, Message: ', 'AppDomain: 51'
```

```
4/28/2014 3:14:04 Application Started! AppDomain:49
4/28/2014 3:21:01 CalibrationClient CacheState Add '2138F402', 'IsRunning: True, IsSuccess: False, Percentage: 0, Message: ', 'AppDomain: 49'
4/28/2014 3:21:08 CalibrationClient CacheState Update '2138F402', 'IsRunning: True, IsSuccess: False, Percentage: 1, Message: ', 'AppDomain: 49'
...
4/28/2014 3:24:52 CalibrationClient CacheState Update '2138F402', 'IsRunning: True, IsSuccess: False, Percentage: 74, Message: ', 'AppDomain: 49'
4/28/2014 3:25:07 CalibrationClient CacheState Update '2138F402', 'IsRunning: True, IsSuccess: False, Percentage: 79, Message: ', 'AppDomain: 49'    
```

```
4/28/2014 3:13:21 Application Started! AppDomain:47  
```

```
4/28/2014 3:14:14 Application Started! AppDomain:50
```

```
4/28/2014 3:13:54 Application Started! AppDomain:48
```

**Comment by Idhor** [comment]
We are experiencing the same issue, we see that suddenly new AppDomains are spawned with the old one that stays alive. I'm going crazy to figure this out
We aren't using any service the app is hosted on IIS 8.5
