### ISSUE TITLE
Unity3d Support

### ISSUE THREAD

**Issue by NVentimiglia** [SignalR/SignalR#3061]
Unity3d is a cross platform game engine that utilizes a subset of .net 3.5. I use it for development of games. I would like to use SignalR to facilitate communication. It uses Mono underneath.

Looking at the bits there are two reasons why the client will not compile for Unity3d.
- Dependency on newtonsoft json. All varients of newtonsoft json that I have tried do not work with Unity3d. I am instead using a variation of LITJson. Please update the client to alow the plugin of a ISerializer so we may use our own serialization.
- Dependency on the Task library. Unity currently does not support the task library. I could implement a copy if I needed... but I`m sure others will run into this problem.

**Comment by dzmitry-lahoda** [comment]
Anything changed since than?

**Comment by anurse** [comment]
The [`2.4.0-preview1-20180920-03`](https://www.nuget.org/packages/Microsoft.AspNet.SignalR.Client/2.4.0-preview1-20180920-03) version of the SignalR Client should support .NET Standard 2.0 and I believe Unity 2018 supports that version of the .NET Standard. If there are issues using SignalR 2.4.0 on Unity 2018 please file a bug and we can look in to it further.

We still don't have plans to allow the complete replacement of Newtonsoft.Json as a serialization library in ASP.NET SignalR. It's deeply integrated into the infrastructure.

**Comment by dzmitry-lahoda** [comment]
Seems we need Core versions as going to use binary formatter in future https://github.com/aspnet/SignalR/issues/3122 .
