### ISSUE TITLE
IHubProxy.On not being invoked after opening a socket

### ISSUE THREAD

**Issue by Ciamas** [SignalR/SignalR#3082]
Not sure if it is a bug or I'm doing something wrong but...Here is a short description:
1) Everything is working fine
2) Hub calls clients informing that there is a file that needs to be sent
3) Clients are opening sockets and then calling hub informing that sockets are ready on the addresses that are passed as params
4) File is being sent
5) As trace shows, everything should be still working fine because I see incoming new messages there, however, IHubProxy.On is not being invoked.

**Comment by moozzyk** [comment]
Probably a typo in the method name.
