### ISSUE TITLE
Document how to enable tracing of various SignalR components on server and clients

### ISSUE THREAD

**Issue by DamianEdwards** [SignalR/SignalR#3090]
How to enable client-side loggingWe need a concise document on how to enable tracing on the various components of SignalR on the server and the different clients. It should be placed in the [Troubleshooting & Debugging](http://www.asp.net/signalr/overview/signalr-20/troubleshooting-and-debugging/) section.

It should be titled "Enabling SignalR Tracing". It should cover tracing to various output types including text files and the console (where appropriate).

See https://github.com/SignalR/SignalR/blob/master/samples/Microsoft.AspNet.SignalR.Samples/Web.config#L27 for an example of how to enable server-side tracing for the various parts of SignalR.

See 'How to enable client-side logging' in http://www.asp.net/signalr/overview/signalr-20/hubs-api/hubs-api-guide-net-client for an example of how to enable tracing in the .NET client.

See http://www.asp.net/signalr/overview/signalr-20/hubs-api/hubs-api-guide-javascript-client#logging for an example of hoe to enable tracing in the JS client.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
