### ISSUE TITLE
SignalR in Android Webview (or Phonegap)

### ISSUE THREAD

**Issue by remcoros** [SignalR/SignalR#31]
Hey,

I'm trying to get SignalR working from a native android app, using the Phonegap framework.

Basically, Phonegap renders html5/js/css into a WebView (Android) or UIWebView (iOS), so I tought I would have this running pretty quickly.

So I started with a real basic page and a simple hub. Tested on a pc and also tested it using my phone's browser(s):
- Native Android (2.3) browser
- Dolphin browser
- Maxthon mobile

All worked !

So I compiled a native android app using phonegap and hoped it would just work (phonegap renders into an Android Webview which uses Webkit engine I think).

This did't work.

It doesn't go any further then 

$.connection.hub.start()

I don't see any javascript errors (altough I'm not sure, see below).

What's going on? What is the best way to go inspect this?

I'm having some trouble debugging this. 
- Using the Android emulator, JS errors are written to log and accessable trough 'adb logcat'. Problem is: The emulator only has access to the internet, not to the local lan. So i cannot run this on my local IIS / (express) server.
  So I need to put this on some public server to debug this (Don't have a access to one now)
- My device (HTC Sensation) (connected trough WLan, so has access to lan) doesn't write javascript errors to log. So 'adb logcat' is of no use here (known problem with HTC devices and javascript/log)

Because phonegap doesn't use some kind full blown browser (just the WebView), I cannot debug javascript. 

I tried 'weinre' (a JS console.log proxy) but it doesn't show me errors either.

My first guess whas it blocks cross-domain requests, but it seems phonegap isn't affected my cross-domain policies, because it runs from the filesystem (verified this, I have a working native phonegap 'ajax' app using external domains without issues).

Anyone here tried SignalR with phonegap (or from an Android Webview) already?

What could I do to test/debug/inspect this some more?

Thanks in advance,

Remco Ros

**Comment by super-coder** [comment]
so does SignalR work well with Cordova Android/iOS ? Connection is not lost when device is switched off?

**Comment by hainahoo** [comment]
Hi remcoros,
whether the SignalR is working even the phonegap app in suspended (inactive) status?

**Comment by mohsinali1317** [comment]
So if my server lies at www.xyz.com, then what will be the absolute url?

    var connString = "://www.xyz.com/connection";
