### ISSUE TITLE
Add documentation for Authentication with signalr js clientes

### ISSUE THREAD

**Issue by rmarinho** [SignalR/SignalR#3112]
I think in this page , http://www.asp.net/signalr/overview/signalr-20/security/hub-authorization ,it should have more info and specify the options for authenticating clients using the browser and signal javascript client.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
