### ISSUE TITLE
/start requests deadlock when the PreSendRequestHeaders event is set

### ISSUE THREAD

**Issue by halter73** [SignalR/SignalR#3116]
### Functional impact
- Clients are unable to establish SignalR connections when someone attaches to the `PreSendRequestHeaders` event.
### Minimal repro steps
- Install SignalR 2.1.0
- Attach to the `PreSendRequestHeaders` event.
- Create a PersistentConnection or Hub.
- Try to connect to the PersistentConnection or Hub with the JS or .NET client.
### Expected result
- The /start request should complete immediately after OnConnected completes, and the SignalR client should move into the connected state.
### Actual result
- 2.1.0 client: No transport can be initialized successfully, because all the transports time out waiting on the start request. After all the transports time out, the client moves to the disconnected state.
- Client after PR #3105 is applied: The SignalR client hangs in the connecting state indefinitely waiting on the /start request to complete.

This issue was originally reported on the [ASP.NET forums](http://forums.asp.net/t/1993105.aspx?SignalR+2+1+0+No+transport+could+be+initialized+successfully+).

**Comment by niemyjski** [comment]
I'm running into this issue in 2.2.0, It seems some times the first two tries it fails and then it connects.

https://github.com/exceptionless/Exceptionless/tree/master/Source/Api/Hubs

**Comment by niemyjski** [comment]
Only difference is I'm not attaching to any events
