### ISSUE TITLE
negotiate url doesn't work in subdomains

### ISSUE THREAD

**Issue by nibblesmx** [SignalR/SignalR#312]
I have a subdomain, http://labs.nibbles.mx which is actually pointing to http://nibbles.mx/labs behind the scenes using IIS rewrites and redirections defined in the web.config file.

the problem was, that signalR autogenerated the negotiate url like this http://labs.nibbles.mx/labs/signalr/signalr/negotiate

I have a workaround, which is using this line in JS, which seems to fix the issue.

$.connection.hub.url = '@Url.Content("~/signalr")';

It seems that the problem is with VirtualPathUtility.ToAbsolute("~/"). 

I tested both in my server, from this URL: http://labs.nibbles.mx/signalr

and you can see the difference between virtual path and url.content.

The code I'm using for comparison is tihs:

<p>
Virtual Path: @VirtualPathUtility.ToAbsolute("~/")
<br />
URL Content: @Url.Content("~/")
</p>

and I'm getting this:

Virtual Path: /labs/signalr/ 
URL Content: /signalr/

URL content is correct, virtual path is not.

Greetings,

Rodrigo

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
