### ISSUE TITLE
Xamarin Client Disconnection when app is idle/closed

### ISSUE THREAD

**Issue by matiasdecarli** [SignalR/SignalR#3134]
We are facing an issue with the communication between the server and an iPad app. While we tried setting the  `GlobalHost.Configuration` options without luck. 

``` csharp
GlobalHost.Configuration.LongPollDelay = TimeSpan.FromSeconds(1);            
GlobalHost.Configuration.DisconnectTimeout = TimeSpan.FromSeconds(9);
GlobalHost.Configuration.KeepAlive = TimeSpan.FromSeconds(3);
GlobalHost.Configuration.ConnectionTimeout = TimeSpan.FromSeconds(1);
GlobalHost.Configuration.TransportConnectTimeout = TimeSpan.FromSeconds(4);
```

It takes the server ~20/25 seconds to acknowledge that the iPad app has lost its connection. We are focused specially on the following scenarios: sudden lost of connectivity, force quitting the app, and the app being idle. 

Ideally we'd love the OnDisconnected event to be fired earlier (~ 5/10 seconds)

Debugging the protocol negotiation, using our Web App, We've seen that the iPad app isn't taking those into consideration (or at least not in practical terms), while the Web Client does. 

When we asked on the Jabber room, someone suggested that it might be related to the usage of Backplane. We did the test on the app, without the backplane, and the issue persisted.

**SignalR v.2.1.0**
**Dede.SignalR.Backplane.ServerHub v0.9.1**
**SignalR Xamarin v2.1.0** (from NuGet)

All this is hosted on Azure Websites, using Azure Service Bus and Azure Storage Table for scale out.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
