### ISSUE TITLE
Scaleout can miss messages if backplane message is missed and next message received moves to next fragment

### ISSUE THREAD

**Issue by DamianEdwards** [SignalR/SignalR#3151]
Consider the case where an configured for scaleout misses a  backplane message (id=100). The next message comes in (id=101) and is stored in `ScaleoutStore` but the add goes into a new fragment. Now somebody asks for all messages since 100, which doesn't exist in any fragment (it's in between two fragments).

e.g. [ 95, 96, 97, 98, 99 ] _Missed message 100_ [ 101, 102, 103, 104, 105 ]

In this case the store should return all messages after 100 (101 to 105) but instead treats the caller as up to date.

**Comment by davidfowl** [comment]
We never fixed this. It should be fixed in a patch.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
