### ISSUE TITLE
SignalR Hang on AuthorizeRequest state

### ISSUE THREAD

**Issue by ocdi** [SignalR/SignalR#3154]
I have an issue with SignalR on production environment that is getting stuck for some unknown reason. The end user perspective is it doesn't appear to be doing anything. This is the IIS Requests for that app pool, I have abbreviated the screenshot 
![image](https://cloud.githubusercontent.com/assets/2775804/3669512/fb20fe6c-1235-11e4-833f-af440fe76357.png)

This is the Module Name portion
![image](https://cloud.githubusercontent.com/assets/2775804/3669525/3cf9427c-1236-11e4-8a18-6ee4b40aeb10.png)

Using SignalR 2.0.3 with Owin 2.0.2. The only way to fix this (temporarily) is to recycle the app pool and then they go away. Any tips or pointers as to why that would happen that would be great!

I'm not doing anything with authorization specifically, aside from general MVC forms authentication.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
