### ISSUE TITLE
Clients sometimes received a duplicate message when re-deploy SignalR app using scale-out to Azure cloud service with 2 or 3 instances.

### ISSUE THREAD

**Issue by Xiaohongt** [SignalR/SignalR#3169]
Clients sometimes received a duplicate message when re-deploy SignalR app using scale-out to Azure cloud service with 2 or 3 instances.

Functional impact:
Clients receive a duplicate message which should not happen.

Repro steps:
1). We can use message loops in Asp.net samples, update the sample to use Sqlserver scale-out ( use Azure vm for Sql Server), or Azure SB scale-out
       In sample message loops: Hub method increase message(number) and send unique message to client, and return the unique message for client success callback, client send the unique message to server Hub method again ….
2). Deploy the sample to Azure cloud service with 2 or 3 instances
3).  On chrome, run serverSentEvents transport  client, request the cloud service url for message loops page Hubs/MessageLoops/default.aspx?transport=serverSentEvents
4).  Select “Send message to caller”, send each message in 50 milliiseconds, click “Start Message Loops”
5).  We can run 4 serverSentEvents transport  clients like step#3 and  step#4
6). Re-deploy the app to the cloud service

Expected result:
Since server always send unique message to clients, so client receiver should not receive duplicate message

Actual result:
Clients sometimes receive a a duplicate message, just one duplicate message on one connection.

Here is trace server1.zip for duplicate connections clients and server at:
https://onedrive.live.com/?cid=A52C30F0B44BA64E&id=A52C30F0B44BA64E%21105

Note, in server trace, we can see that each duplicate message is the first message sending to client on the each connection after re-deployment.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
