### ISSUE TITLE
Signalr Silverlight Firefox callback cyrillic string issue

### ISSUE THREAD

**Issue by starky27** [SignalR/SignalR#3177]
### Problem:

I have a simple Hub which returns cyrillic string:

```
  public class TestHub : Hub
  {
    public void Ping()
    {
      Clients.All.Pong("кириллица");
    }
  }
```

When I call the ping method from silverlight client hosted in Firefox I often gets wrong string.

![untitled](https://cloud.githubusercontent.com/assets/8308059/3746933/b605dc20-17c7-11e4-8f83-6141090c3bb6.png)

Seems like it appears only in Firefox, so I'm not sure is it Firefox or Signalr issue.
### Using:

Signalr 2.1.0
Silverlight (64-bit) 5.1.30214.0 

Browser:
Mozilla/5.0 (Windows NT 6.3; WOW64; rv:31.0) Gecko/20100101 Firefox/31.0
### Silverlight setup:

```
    public async Task Connect()
    {
      var uiDispatcher = Application.Current.RootVisual.Dispatcher;

      _hubConnection = new HubConnection("http://localhost:38135/");
      _testHubProxy = _hubConnection.CreateHubProxy("TestHub");
      _testHubProxy.On<string>("Pong", text => uiDispatcher.BeginInvoke(() => ui_textBox.Text = text));
      await _hubConnection.Start();
    }

    public async Task Ping()
    {
        await _testHubProxy.Invoke("Ping");
    }
```

**Comment by paaland** [comment]
Any progress? We are experiencing similar issues. "Space character" and norwegian characters (ÆØÅ) are sometimes missing or messed up when included in a signalr response. Only have this issue in Firefox. Works fine in IE, Chrome and Safari.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
