### ISSUE TITLE
bower-signalr: Please apply filename fix to 2.0.3

### ISSUE THREAD

**Issue by tedjp** [SignalR/SignalR#3180]
The jquery.signalR.js filename in bower.json in the bower-signalr repository has the wrong name for case-sensitive filesystems. It has been fixed in master (2.1.0) but not in 2.0. Would you consider applying the following commit to a 2.0 branch?

https://github.com/SignalR/bower-signalr/commit/12085cdba5109414d0934e3e30d537cf5e84cb9c

I'm not sure if you already have a version numbering scheme, but presumably it could be tagged as v2.0.3.1.

(I have to use version 2.0.3 due to a problem with LongPolling in 2.1.0 & 2.1.1.)

I've made the equivalent change in my own fork if that helps illustrate my request: https://github.com/tedjp/bower-signalr/commits/v2.0.3-fixed-filename

**Comment by moozzyk** [comment]
This has been fixed with https://github.com/SignalR/bower-signalr/commit/12085cdba5109414d0934e3e30d537cf5e84cb9c
