### ISSUE TITLE
Upgrading to 2.1.1 now causes a response can't be found

### ISSUE THREAD

**Issue by cblaze22** [SignalR/SignalR#3188]
I am using T4MVC to generate a strongly typed URL.  This worked in the previous version and isn't working now.  I am getting `Additional information: Response is not available in this context.` when trying to call urlHelper.Action.  The request.Response has the message `'(request.HttpContext).Response' threw an exception of type 'System.Web.HttpException'`.

```
            var request = Context.Request.GetHttpContext().Request.RequestContext;
            var urlHelper = new UrlHelper(request);
            var url = urlHelper.Action(MVC.Directors.EventSchedule.Index(EventId));
```

**Comment by Almeonamy** [comment]
I have same error. Was this problem solved? Or it still actual?

**Comment by godofwrath** [comment]
I get this problem too, I have to just remove targetFramework="4.5" from the httpruntime and not use websockets. This is either a bug or I just have no idea how to use signalR with websockets.

I would usually use

    If createSessionCookie Then Accounts.createSession(user.forumID, user.ipAddress, HttpContext.Current)

then in Accounts

    Public Shared Sub createSession(forumID As Integer, userIP As String, context As HttpContext)

but once I target 4.5 and websockets are enabled, this no longer works. Not sure why, but the response is blocked.

So I might just not understand how to allow the response or have the response be a websocket response instead or something? No idea.

Pretty sure this can be marked as closed, unless maybe somebody wants to offer some insight? 
After upgrading to a version of SignalR that uses websockets this occurs.

**Comment by ajbeaven** [comment]
I'm having the same problem with regard to websockets HttpContext not having a response. Is this documented anywhere? How do you access the response when using SignalR with websockets?

**Comment by godofwrath** [comment]
For me this was just purely happening in the case of accessing cookies after the initial connection was made, so I just had the server generate an ID, pass it to the client side javascript that would then create the cookie instead, and I just initiate everything that I would've otherwise via daisy chaining instead of response

**Comment by ajbeaven** [comment]
My use case is around i18n translation. I use a package that takes the response, finds special characters that indicates certain text should be translated, and spits back a modified response that uses the correct translation. 

My plan is to do this in a custom `HubPipelineModule`, modifying the response in `OnBeforeOutgoing` or something similar. I don't necessarily need the HttpResponseBase, but I do need a way to retrieve and modify whatever is being sent to the client. How does one do this with SignalR over websockets?

**Comment by godofwrath** [comment]
sounds to me like you have the same issue, and it also sounds like it could be resolved via some javascript,  and just hand the data back and forth from the client to the app using javascript, for instance:

var mainHub = $.connection.translationHub;
$.connection.hub.start()
        .done(function () {
mainHub.server.call("#Div").val
});

and in vb(or whatever language you're using)

public sub call(ByVal translationText As String)
do whatever you needed
end sub

You'll have to get inventive, but I hope this helps.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
