### ISSUE TITLE
Generics on Hubs

### ISSUE THREAD

**Issue by ferberts** [SignalR/SignalR#319]
Hello, I got problems using generics in my hub.

I wanted to use a Hub dependant on Generics and my Client won't succeed in connecting to the proxy. Is this a general limitation of SignalR? My class looks like the following:

```
namespace AspNetHub
{
    //[HubName("filterHub")]
    public class FilterHub<TNode> : Hub where TNode : Node<TNode>
    {
    }
}
```

This results in the HubName "AspNetHub.FilterHub`1". Now if I enter this as Proxyname it won't work. Also, if I uncomment the HubName Attribute it won't change the HubName either. Suggestions?

Thanks in advance.

**Comment by pvanroos** [comment]
Hi guys... Is the feature discussed above possible in v2.2.1?

**Comment by IanYates** [comment]
Yes, generics are possible in a sense.  Note the example by @akoeplinger though which shows a non-generic hub inheriting from a generic one.  
More recently (probably 18 months ago) there is now the ability to use strongly typed client interfaces (for server to client comms) and I've used generics with that successfully.

**Comment by pvanroos** [comment]
Hey @IanYates:  Thanks for the response.  My goal was to create a generic hub that relays updates, adds, deletes to subscribed clients.  (i.e. public class EntityHub<T> : Hub)  Then I can have clients set the subscription on this generic hub like IHubProxy.On<Contact> and viola ...   What do I get from this? I don't have to create a hub for each entity I want to have hub notifications for.
