### ISSUE TITLE
cookie isnt added to the request

### ISSUE THREAD

**Issue by li-raz** [SignalR/SignalR#3194]
I am working with Signalr .Net client version 2.1.0 as the server is using version 1.3
I need to add a cookie to the request of the connect, how ever it isnt added

var cookie = new Cookie("session-token", token);
                cookie.Domain = "localhost";

```
            _hubConnection = new HubConnection(_ip)
            {
                CookieContainer = new CookieContainer()

            };
            _hubConnection.CookieContainer.Add(cookie);
```

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
