### ISSUE TITLE
Seeing a lot of missing messages from Server to Client when publishing at a high rate

### ISSUE THREAD

**Issue by undecided2013** [SignalR/SignalR#3201]
I am testing the throughput of SignalR and I am sending 5K to 60K messages per second from the server but the client seems to be receiving about 1/3 of the messages. The ratio seems pretty constant. This is a self hosted server. The client is winforms. I am also noticing huge memory leak on the client. Memory keeps going up till eventually the client dies. Both Client and Server are running SignalR 2.0.2.

The client doesn't do much, just increments a perf counter. The server does the same and I correlate the two. 

``` C#
public partial class tickHubClientForm : Form
{
 HubConnection hubConnection;
        IHubProxy tickProxy;
        IDisposable handler;
PerformanceCounter TickReceived = new PerformanceCounter("Test Client", "Ticks Per Second", false);

        protected void UpdateTick(Tick tick)
        {
            TickReceived.Increment();
        }

 protected async Task performRequest()
         {

             hubConnection = new HubConnection("http://localhost:8374");
             hubConnection.ConnectionSlow += () => lblUpdate.Text = "Connection problems.";
             hubConnection.Error += ex => lblUpdate.Text = "SignalR error: {0}" + ex.Message;
             hubConnection.ConnectionSlow += () => lblUpdate.Text = "Connection slow";
             tickProxy = hubConnection.CreateHubProxy("TickHub");


            handler = tickProxy.On<Tick>("receiveTick", tick =>
             {
                 UpdateTick(tick);
             });

             await hubConnection.Start();
             tickProxy.Invoke("SubscribeToTicks");
}

private void btnStart_Click(object sender, EventArgs e)
        {
            performRequest();
        }

}
```

p.s. When I debug and look at the transport I see ServerSentEvents as the transport.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
