### ISSUE TITLE
Memory build-up

### ISSUE THREAD

**Issue by Katulus** [SignalR/SignalR#3205]
Hello,
I'm using SignalR server hosted in Windows service. I have hundreds of clients connected to this server. I noticed that when I start sending large messages from server to clients, memory grows (which is expected) but when all large messages are sent, memory does not drop.

I took memory dump and found out that SignalR keeps thousands (in my case about 40,000) messages in memory in MessageStore<Message>.Fragment instances. I already set GlobalHost.Configuration.DefaultMessageBufferSize to 32 (which is minimal value that SignalR uses) but because of lots of clients I still have huge amount of messages in memory. 
I looked into code and found out that messages in store fragments are never removed unless they are overriden by new message. So if I send large chunks of data to clients which fills fragments and then just send one message now and then, memory is never released because fragments are holding data and they can't be GCed. 

Is this observation correct or am I missing something? Is there any way how to release old messages from memory other than overriding them with new messages? Could SignalR release message from store once it's sent?

I'm having severe memory issues due to this fact. Even if I serialize big data transfers so that I send to only few clients at time, it eventually ends with OutOfMemoryException because old data are never removed.

Thanks for any advice.
Jiri

**Comment by danielmue** [comment]
What is the reason for storing messages, that have been sent to all clients already?

**Comment by davidfowl** [comment]
There's no way to know that all clients have actually received the messages. Signalr is based on pub sub. We have discussed volatile messaging in the past and it might be something we look at for v3 but no plans right now. You can set the message store size to reduce buffering (0 will not work)

**Comment by heyou93** [comment]
Any updates about this? Can i set the message store size to 0 or 1? (For minimum). We are having the same issue, our server load is running out of memory because of signalR self hosted service.

**Comment by moozzyk** [comment]
The minimum size you can set the buffer to is 32.

**Comment by Bykiev** [comment]
hey guys, how did you solve this issue? I'm also faced with this, but the message size is small enougth (I think) and I've already set `DefaultMessageBufferSize` to 32. RAM usage is constantly increasing and I don't know what I can do with it... Please, help!

**Comment by davidfowl** [comment]
> I've multiple hubs, is DefaultMessageBufferSize applied for all hubs or for each hub (if I have 5 hubs, total buffer will be equal to 160 message)?

It's per "signal", hub, group, connection id, user name etc.

> hey guys, how did you solve this issue? I'm also faced with this, but the message size is small enougth (I think) and I've already set DefaultMessageBufferSize to 32. RAM usage is constantly increasing and I don't know what I can do with it... Please, help!

This issue is 7 years old and one of the fundamental design "issues" with SignalR. The only lever you have here is that setting. I'd recommend taking a memory profile to see if there's anything you can do (like reducing your message size).

**Comment by Bykiev** [comment]
@davidfowl, thank you for reply, I've 5 hubs and `DefaultMessageBufferSize` is 5, so the max message count in store is 160, but the message count is bigger for some reason... I've attached the screenshot of dotMemory profiler. If I understand correctly, the re are 17.1K Message objects
![profiling](https://user-images.githubusercontent.com/13969777/143732755-ce5bc124-9481-4b47-bffe-e3762432f5e1.png)

**Comment by davidfowl** [comment]
32 * number of signals (groups, users, connection ids etc), so not 160. It's dependent of your application. Then there's the message size as well.

**Comment by Bykiev** [comment]
> 32 * number of signals (groups, users, connection ids etc), so not 160. It's dependent of your application. Then there's the message size as well.

Thanks, reducing mesage size fixed the issue. It seems in SignalR.Core you've changed internal logic and it's not using buffer ring anymore. Will be changed in SignalR?

**Comment by davidfowl** [comment]
> Will it be changed in SignalR?

No. This version of SignalR gets bug fixes only.
