### ISSUE TITLE
SignalR is not able to handle the request with respect to the sequence sent from server

### ISSUE THREAD

**Issue by hemachandran85** [SignalR/SignalR#3222]
In case of triggering multiple signalR events, Is it possible to handle the sequence of these events in client side.

for example:

1:02:01 pm  first event has been triggered           event A

1:02:02 pm  second event has been triggered      event B

1:02:03 pm  third event has been triggered          event C

1:02:04 pm  fourth event has been triggered        event D

Client Side:

I am receiving events in disorder manner (B, D, A, C).

Is it problem with SignalR or handling the outgoing request/response in asp.net?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
