### ISSUE TITLE
Is there a way to set timeout on 

### ISSUE THREAD

**Issue by eileithyia** [SignalR/SignalR#3226]
i mean set  timeout on hub.start(). i want to try to connect to  a different server if the the first connection takes too long to return any result. When i stop my IIS, it took like 3 mins to return "Error during negotiation request."  It doesn't looks like totalTransportConnectTimeout is doing anything.

  Something like this.

   $.connection.hub.start({ ConnectingTimeout: 5000 }).done(function () {
                log('hub started. connection Id=' + $.connection.hub.id);
                connect();
            }).fail(function (error) {
                log('Hub.Start(). ' + error);
                    ChatConnection.ServerSwitch();
            });

I know i can modify the jquery.signalR-2.1.0.js javascript  by adding "timeout:5000" in the code below. Other than hacking the signalr javascript, is there anyway other  way to do it on hub.start() in C# and js?

 transportLogic = signalR.transports._logic = {
        ajax: function (connection, options) {
            return $.ajax(
                $.extend(/_deep copy_/ true, {}, $.signalR.ajaxDefaults, {
                    type: "GET",
                    timeout:5000,
                    data: {},
                    xhrFields: { withCredentials: connection.withCredentials },
                    contentType: connection.contentType,
                    dataType: connection.ajaxDataType
                }, options));
        },

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
