### ISSUE TITLE
Using SignalR 2.1.1 with newest Microsoft.Owin library results in assembly conflict warnings

### ISSUE THREAD

**Issue by 101100** [SignalR/SignalR#3234]
This results in warnings or a requirement to use `assemblyBinding`s.
## Minimal repro steps
1. Include Microsoft.AspNet.SignalR.Core 2.1.1 in your project
2. Include Microsoft.Owin 2.1.0 in your project
## Expected result

No warnings are produced.
## Actual result

An assembly conflict warning is produced.
## Further details

This conflict also happens with the following libraries:
- Microsoft.Owin 2.1.0
- Microsoft.Owin.Security 2.1.0
- Newtonsoft.Json 6.0.4

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
