### ISSUE TITLE
SignalR for Xamarin.mac

### ISSUE THREAD

**Issue by karthickr87** [SignalR/SignalR#3237]
Dose signalR Lib supports Xamarin.mac. Could you please provide a sample, if it is supported.

**Comment by rob-derosa** [comment]
I'm curious about this too, specifically the ability to host from within a Xamarin.Mac app. Seems like it should work but NuGet fails to add package to Xamarin.Mac projects. Any info on future support would be awesome.

**Comment by tofutim** [comment]
Revisiting this since Nuget is failing to add.

**Comment by TinghuiWang** [comment]
Under Visual Studio for Mac - Trying to get Microsoft.AspNet.SignalR.SystemWeb 2.2.2
The process failed with following messages:

Package Microsoft.AspNet.SignalR.SystemWeb 2.2.2 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.AspNet.SignalR.SystemWeb 2.2.2 supports: net45 (.NETFramework,Version=v4.5)
Package Microsoft.Owin.Host.SystemWeb 2.1.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Owin.Host.SystemWeb 2.1.0 supports:
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)

**Comment by moozzyk** [comment]
SystemWeb is for the server. 2.x server cannot run on non-Windows. 2.2.2 contains a client that targets netstandard and this client can run on xamarinmac. See: https://github.com/SignalR/SignalR/issues/3851

**Comment by moozzyk** [comment]
2.2.2 contains a netstandard client which can be used in xamarin projects. 

https://github.com/SignalR/SignalR/issues/3851
