### ISSUE TITLE
IE11 shows infinite loading status, but IE9 and IE10 is fine 

### ISSUE THREAD

**Issue by Dora407** [SignalR/SignalR#3238]
i have loading issue in IE browser.I am using signalR version 1.1.4. it is working fine in chrome and firefox , but it shows continuous loading in IE all versions . After replace @JMacPSU code , loading stops in IE9 and IE10 .
but still shows loading in IE11.
i took code from this issue
https://github.com/SignalR/SignalR/issues/215
what to do, to stop loading in  IE11

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
