### ISSUE TITLE
Call signalr service hub method multiple times

### ISSUE THREAD

**Issue by Manoj1786** [SignalR/SignalR#3241]
I am using signalr 2.x with azure service bus.On client side I am using WPF 4.0.
I have a button.On clicking on the button I want to call a hub method multiple times.
Problem is it it returns the same result both the times.But When I call this method
separately It gives the right result.How to call the same hub method multiple times?

``` C#
public class SamTaskHub : Hub
{
         public void BeginGetTaskDetailsAsOrganizer(string sqlParams, bool isParametersCompressed)
        {
            string result = string.Empty;            
            try
            {
                result = SamSerializeGetResultFromProcedure(sqlParams, isParametersCompressed);
            }
            catch (Exception ex)
            {

            }
            Clients.Caller.EndGetTaskDetailsAsOrganizer(result);
        }

}
```

Client 

``` C#
private void button1_Click(object sender, RoutedEventArgs e)
        {                        
            Globals.UserInfo = new UserPreferences.SamUserInfo();
            Globals.UserInfo.UserId = 3;
            DatabaseFactory.Factory.BeginGetTaskDetailsAsOrganizer(null, OrganizerViewRequestType.OrganizerView, OrganizerViewOptions.All, "01 Jan 2000", "25 Aug 2014", EndGetTaskDetailsAsOrganizer1, null);
            DatabaseFactory.Factory.BeginGetTaskDetailsAsOrganizer(null, OrganizerViewRequestType.OrganizerView, OrganizerViewOptions.Cancelled, "01 Jan 2000", "25 Aug 2014", EndGetTaskDetailsAsOrganizer2, null);

        }
```

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
