### ISSUE TITLE
Can someone Please provide one complete example for Signalr 2.0 for VB.net users....PLEASE

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [SignalR/SignalR#3246]
You know what will be nice,

One complete example for vb.net users that works, step by step showing how to use signalr 2,0.

Sometimes we spend wasted hours (or days) trying to get our heads around stuff that you C# guys take for granted.

Google this: "Signalr 2.1 tutorial step by step vb.net ASP.net web application"

All you get back is a bunch of crud that leaves you more confused than when you started .

If VB.NET is still relevant to MS at all, then we would really appreciate some non - {} guidance.

Thanks.

**Comment by mustafaodeh123** [comment]
BenjaminGibbs

If you can help me to get started with SignalR I would really appreciate it! 
I did everything and it looks easy but I when I run it I am getting this error and I spent hours try to fix it and look over the internet but nothing seems to work. (I am using asp.net - vb.net)

"
[EntryPointNotFoundException: The following errors occurred while attempting to load the app.
 - No 'Configuration' method was found in class 'MyRuntimeWeb.Startup, MyRuntimeWeb, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
"

**Comment by pmg1963** [comment]
A VB startup class is

Imports Microsoft.Owin
Imports Owin
Imports Microsoft.Owin.Cors
<Assembly: OwinStartup(GetType(SignalRChat.Startup))> 
Namespace SignalRChat
    Public Class Startup
        Public Sub Configuration(app As IAppBuilder)
            ' Any connection or hub wire up and configuration should go here
            app.UseCors(CorsOptions.AllowAll)
            app.MapSignalR()
        End Sub
    End Class
End Namespace
All you need to do is create new class, name it startup.vb and paste the above code into it.

**Comment by AleliLegaspi** [comment]
@BenjaminGibbs 
Hello!  I have seen your comment here. Can you please help me in implementing signalR in vb.net? I have tried in C# but i cannot make it work when converting to vb.net. Hoping for your immediate reply. Thanks!
:)
