### ISSUE TITLE
SQL deadlock when using SQL scale out

### ISSUE THREAD

**Issue by davemarsland** [SignalR/SignalR#3247]
Environment: 3 windows 2008 servers using SQL 2012 as a backbone, signalr version 2.1.1

We get SQL deadlock errors when using the scaleout stream to keep our 3 signalr servers in sync. When this happens, we also see very high CPU usage (though this may be related to the .NET SQL data connection and not signalr) which persists until we kill the sql connection by clearing the app pool. In what scenario would we see the SQL server experience deadlocks like this? Signalr has a dedicated database, which no other process uses.

Stack trace:

SignalR.SqlMessageBus Error: 0 : Stream 0 : Error in SQL receive loop: System.Data.SqlClient.SqlException (0x80131904): Transaction (Process ID 162) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

Transaction (Process ID 275) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction. at Microsoft.AspNet.SignalR.Messaging.ScaleoutStream.Send(Func`2 send, Object state) at Microsoft.AspNet.SignalR.Infrastructure.Connection.Send(ConnectionMessage message) at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.Outgoing(IHubOutgoingInvokerContext context) at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.<>c__DisplayClass1b.<BuildOutgoing>b__19(IHubOutgoingInvokerContext context) at Microsoft.AspNet.SignalR.Hubs.HubPipeline.Send(IHubOutgoingInvokerContext context) at Microsoft.AspNet.SignalR.Hubs.ClientProxy.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)

**Comment by dclonch1** [comment]
I'm seeing sql deadlocks in version 2.2.0
