### ISSUE TITLE
MapSignalR hangs if custom dependency resolver is used with UseServiceBus

### ISSUE THREAD

**Issue by Unrefraction** [SignalR/SignalR#3250]
Hi everyone!

We use the next version of SignalR packages:
SignalR 2.1.1
SignalR.Utils 2.1.1
SignalR.ServiceBus 2.1.1

I cannot reproduce the issue locally, but other guys from my team had faced with the next issue:
in our project, we use custom dependency resolver for SignalR which is derived from DefaultDependencyResolver and has overriden GetService and GetServices methods where IUnityContainer is used internally.

If we tryr to call MapSignalR in the next order

```
        GlobalHost.DependencyResolver = new SignalRDependencyResolver(container);
        GlobalHost.DependencyResolver.UseServiceBus("connectionString", "prefixName");

        app.MapSignalR("/communication", new HubConfiguration
        {
            EnableDetailedErrors = true,
            EnableJavaScriptProxies = true
        });
```

it hangs and... that's all.

But if configure service bus first and then replace default dependency resolver with custom one - everything works fine.

Any suggestions why that happens?

Thank you!

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
