### ISSUE TITLE
NullReferenceException in SSE transport

### ISSUE THREAD

**Issue by peters** [SignalR/SignalR#3255]
Signalr: 2.1.1

Been getting a lot of these error reports from smartassembly lately. Why are they leaking through?

![image](https://cloud.githubusercontent.com/assets/869/4149327/6fa1caf0-3432-11e4-8a92-d8e266aa4c81.png)

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
