### ISSUE TITLE
Connection.Stop will not stop long polling if the first poll has not been made - .NET Client

### ISSUE THREAD

**Issue by halter73** [SignalR/SignalR#3256]
If the disconnectToken is canceled before we transition the LongPollingTransport into the `_running` state, we will fail to properly stop the transport.

This is likely similar to [the issue](https://github.com/SignalR/SignalR/issues/3255) that can cause a NullReferenceException in the ServerSentEventsTransport.

We can potentially work around this issue by giving `_running` three states so we can distinguish between the transport being stopped vs. simply not started.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
