### ISSUE TITLE
Can't connect from Windows Phone Silverlight 8.1 device

### ISSUE THREAD

**Issue by andreasbergqvist** [SignalR/SignalR#3267]
I have a Windows Phone Silverlight 8.1 app that got problem connecting to my hub when I made a release version.

Connecting work perfectly in Emulator (both 8.1 and 8.1 Update 1 and both in Debug and Release mode). When I connect my device (a Nokia Lumia 1020 with latest Developer Preview of Windows Phone 8.1) it works when I use Debug. But if I change to Release. I get the following exception when running HubConnection.Start:

Could not load file or assembly 'System.Net.Http.Phone, Version=2.0.5.0, Culture=neutral... or one of its dependencies. The system cannot find the file specified.

My code (I tested starting a new project with only this code, and got the same exception showing):
var connection = new HubConnection(url);
try
{
    connection.Start();
}
catch (Exception ex)
{
    MessageBox.Show(ex.Message);
}

**Comment by jbruening** [comment]
An update: I started experiencing this issue at random again, though it appeared to be stemming from other people deploying the application.  I've discovered that if the 8.0 sdk is used to deploy the application, the problem reappears. Using the 8.1 sdk to deploy the app, even from the same machine and onto the same phone with the same xap that has a currently non-working app, will fix the issue.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
