### ISSUE TITLE
Cookies not sent in cross domain request

### ISSUE THREAD

**Issue by AlexKovkin** [SignalR/SignalR#3273]
Hi, All

I encountered unexpected behavour. Client does not send cookies to server during cross domain request. SignalR client and server are of version 2.1.2.
Server has "map.UseCors(CorsOptions.AllowAll);" in code. Client adds  { withCredentials:true} to request.
In genral cross domain request works:
- Request contains Origin
- Response contains Access-Control-Allow-Credentials and Access-Control-Allow-Origin.

But Fidler do not shows pre-flight request.

Here is test solution http://ge.tt/api/1/files/5xcmRIx1/0/blob?download

Javascript client is built in WebApplication1 project. It has page http://localhost:12485/Home/index. This page creates cookie.
ConsoleSefhost - self hosted server with SignalR
WebApplication2 asp.net hosted SignalR server (run in IIS)

To reproduce cross domain request I connect to server by host name (computer name - BIG). So, base url for SignalR server looks like http://big:1200/signalr (instead of http://localhost:1200/signalr). JS Client is hosted on http://localhost:12485/Home/index. So we have different domains (localhost and BIG).
When both server and client are hosted on localhost browser sends cookie starting from negotiate request.

Can somebody say what is wrong?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
