### ISSUE TITLE
Unable to intercept Heartbeat through default TransportHeartbeat

### ISSUE THREAD

**Issue by jesuissur** [SignalR/SignalR#3276]
Hi

We are trying to intercept the connection's heartbeat to handle our clients' connection status on the server-side in a SignalR scaling scenario.  As of the 2.1.1 version of SignalR, it doesn't seems possible to do this easily.  We've tried the following scenario without much success.

We implemented our own custom (and quite dummy) ITransportHeartbeat and delegate every call to the default implementation.  We plugged our monitoring system in the MarkConnection method and it was fine.... for the first heartbeat or so.  Because it is the default TransportHeartbeat implementation which is in charge of executing the heartbeat's timer.  Hence, our custom implementation does not have any timer in it and no heartbeat is ever called after the first connection.

We would like to have a way to be notified of our clients' heartbeat in SignalR.  One easy (and maybe not the most elegant) way, would be to have the public methods of the default implementation (TransportHeartBeat) virtuals.

Does this feature is something SignalR could have?  Does anyone have a workaround for us?

Thanks
Phil

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
