### ISSUE TITLE
No AddClientCertifcate Method

### ISSUE THREAD

**Issue by bp76** [SignalR/SignalR#3277]
I am using version 1.2.2. I see no AddClientCertificate method on the Connection class in the client dll. I opened this up in reflector and it is indeed not there. Any suggestions?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
