### ISSUE TITLE
Redis Scaleout Dev Branch not properly using available Redis servers

### ISSUE THREAD

**Issue by saluce65** [SignalR/SignalR#3279]
I'm using copies of the current (as of this writing) dev branch Redis scaleout against three Redis servers (localhost:6379, localhost:6380, localhost:6381).  To verify the signals going across, I'm also running three clients subscribed to my application's channel, one per server.

When all three servers are running, all signals seem to be exclusively run through the first server in the connection string.  When that server is taken down, the entire app crashes rather than failing over to the other servers.

When starting up the application with the first server down, signals are alternately sent between the remaining two servers, and a loss of one of those servers has no effect on the application (the third server picks up the entire load).  And when the second server comes back up, signals are alternated between the two servers again.

However, as soon as the first server comes back online, all signals are sent exclusively to that server, and like the first case, if it crashes out again, the app crashes.

This might be an issue with the StackExchange.Redis ConnectionMultiplexer rather than the SignalR.Redis framework, but since I found it because of the SignalR framework I thought I'd pass that information to you and let you figure out whether you plan to work around it or bug StackExchange about it.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
