### ISSUE TITLE
OnConnected not called when running on multiple hosts with version 2.1.1-2.1.2

### ISSUE THREAD

**Issue by jkells** [SignalR/SignalR#3281]
We are using SignalR as a one way channel to push messages to web clients. 

We aren't using a backplane because we aren't publishing messages to groups of clients and clients only need to receive messages from the server they're currently connected to.

Essentially a task starts in OnConnected that sends messages periodically using the ConnectionId. The task is stopped in OnDisconnected.

Since version 2.1 there have been some weird changes to the OnConnected behaviour. I'm seeing OnConnected called on Server-A but the client ends up connected to Server-B. Calls to the client from Server-A aren't delivered ( as expected ) but OnConnected is never called on Server-B to get it started. 

The problem doesn't exist when running SignalR version 2.0.3

This simple example demonstrates the problem. When running on multiple hosts sometimes the browser correctly displays:

```
On connect called
Test called
```

Other times it only displays 

```
Test called
```

Looking in the debugger the times in fails are when OnConnected and Test end up being called on different hosts.

MyHub.cs:

```
public class MyHub : Hub
{
    public void Test()
    {
        Clients.Caller.Message(string.Format("Test called"));
    }


    public override Task OnConnected()
    {
        Clients.Caller.Message(string.Format("On connect called"));            
        return base.OnConnected();
    }
}
```

index.html

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
    <script src="Scripts/jquery-2.1.1.js"></script>
    <script src="/Scripts/jquery.signalR-2.1.2.js"></script>
    <script src="/signalr/hubs"></script>

    <script>
        $.signalR.myHub.client.message = function(message) {
            $("body").append("<p>" + message + "</<p>");
        };

        $.signalR.hub
            .start()
            .done(function() {
                $.signalR.myHub.server.test();
            });
    </script>
</head>
<body>    
</body>
</html>
```

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
