### ISSUE TITLE
Use WebSockets by default in the Windows Store client 

### ISSUE THREAD

**Issue by halter73** [SignalR/SignalR#3283]
If you want to use WebSockets in the Windows Store client, you have to manually specify it as the chosen transport as follows:

```
await connection.Start(new WebSocketTransport());
```

Or if you want to support falling back to long polling:

```
var httpClient = new DefaultHttpClient();

var autoTransport = new AutoTransport(httpClient, new IClientTransport[] {
    new WebSocketTransport(httpClient),
    new LongPollingTransport(httpClient)
});

await connection.Start(autoTransport);
```

Ideally calling `await connection.Start();` should be enough to try WebSockets when applicable.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
