### ISSUE TITLE
The AutoTransport should not be required to share an IHttpClient with passed-in transports

### ISSUE THREAD

**Issue by halter73** [SignalR/SignalR#3285]
The following code will result in a NullReferenceException:

```
var transport = new AutoTransport(new DefaultHttpClient(), new IClientTransport[]  {
    new ServerSentEventsTransport(),
    new LongPollingTransport()
});

await connection.Start(transport)
```

The NullReferenceException occurs because IHttpClient.Initialize is called on the client passed directly into the AutoTransport, but not the ones created by the default ctors of the ServerSentEventsTransport and the LongPollingTransport.

The NullReferenceException doesn't occur with the WebSocketTransport since it only uses the IHttpClient to make the /start request (where IHttpClient.Initialize is called) and not prior to the start request to establish a streaming a connection.

This can lead to an even harder-to-diagnose error where if you specify the WebSocketTransport first and the AutoTransport tries to fall back to another transport with an uninitiated IHttpClient, it will silently fail leaving the connection permanently in the "Connecting" state:

```
var transport = new AutoTransport(new DefaultHttpClient(), new IClientTransport[]  {
    // If the AutoTransport attempts to fall back from WebSockets, it will fail silently
    // remaining in the "Connecting" state permanently. If WebSockets succeeds to
    // connect, there will be no issue.
    new WebSocketTransport(),
    new ServerSentEventsTransport(),
    new LongPollingTransport()
});

await connection.Start(transport);
```

This happens because AutoTransport.ResolveTransport only handles async errors when it calls IClientTransport.Start.

The workaround is to use the same IHttpClient instance for the AutoTransport and the transports that are passed in, but I think it is too easy to shoot yourself in the foot.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
