### ISSUE TITLE
SignalR doesn't work behind a Reverse Proxy

### ISSUE THREAD

**Issue by Dunken** [SignalR/SignalR#3287]
I want to use a Reverse Proxy. Therefore I set $.connection.hub.url = "/NorthboundWebApiClient/signalr"; //NorthboundWebApiClient is name of RP

The calls to /connect fail because the RP doesn't get applied. The previous calls to /hubs and /negotiate succeed:

![image](https://cloud.githubusercontent.com/assets/1533991/4385621/b4785ec0-43c6-11e4-8130-a46527109f0b.png)

The result of /negotiate contains among others "Url":"/signalr". If I use a Reverse-Proxy rule (scan and replace) and set "Url":"/NorthboundWebApiClient/signalr" everything works fine.

**Comment by jpierson** [comment]
This sounds like a duplicate of https://github.com/SignalR/SignalR/issues/3649

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
