### ISSUE TITLE
SignalR JS client fails to connect sometimes

### ISSUE THREAD

**Issue by kohner86** [SignalR/SignalR#3288]
Recently upgraded from 2.0.0 to 2.1.2 and have been experiencing an intermittent issue in which the 'start' method on the JS client sometimes never finishes.  From looking at Firebug I can see an XHR request with 'start' in the path which hangs indefinitely.
   This seems to pop up intermittently (it hangs abount a third of the time) and I've been able to resolve it by reverting back to 2.0.0.
   Was this some sort of regression?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
