### ISSUE TITLE
SignalR 2.1.1 Data submit limit at client side

### ISSUE THREAD

**Issue by ArjunPathak** [SignalR/SignalR#3289]
We have updgraded to SignalR 2.1.1. Here we are facing data size submit error. It does not accept data of large size. Our older version was just 1.0.0. rc2 which was taking any amount of value in Hub method. 

In latest upgrade it only works when we submit very limited / small value to hub method.

Other info: Submit value is xml string. 

Let us know what configuration is to be done at client side to enable it to submit large value/strings.

Thanks in advance
Arjun Pathak

**Comment by m1729** [comment]
There are several issues that could connected to yours. Please take a look at
https://github.com/SignalR/SignalR/issues/1205
https://github.com/SignalR/SignalR/issues/2723
https://github.com/SignalR/SignalR/issues/2774
Is this issue duplicate to those?

**Comment by moozzyk** [comment]
This issue is filed for a deprecated version of SignalR (SignalR Asp.NET Core 1.0.0-rc2). We decided to build the version of SignalR for ASP.Net Core from scratch instead of porting existing 2.x code to ASP.Net Core.
