### ISSUE TITLE
Connection gets closed after period of inactivity (no reconnection)

### ISSUE THREAD

**Issue by pszmyd** [SignalR/SignalR#329]
I noticed, that for some reason, the connection gets closed after some period of inactivity. No reconnection is being performed - it just gets closed and JS starts shouting with errors "Uncaught SignalR: Connection must be started before data can be sent. Call .start() before .send()". I'm using a very simple setup, using the QuickStart example (https://github.com/SignalR/SignalR/wiki/QuickStart-Hubs) and latest SignalR branch.

This is how it looks on Chrome - after 1.2 minutes the request gets cancelled (timeout?): http://tinypic.com/r/2lka23s/5. Transport used is SSE. 

Will try to investigate on FF and IE9 and will keep you posted.

**Comment by abhishekbhalani** [comment]
@davidfowl I need your help on this.
I am facing same issue. 
jquery.signalR-2.2.1.min.js:9 Uncaught Error: 
SignalR: Connection must be started before data can be sent. Call .start() before .send()

when I click the send message button that time I am getting above error..
1) Should I changes timeout setting?
if yes , then Where it need to be changed  for websocket & longpooling..
