### ISSUE TITLE
Split off SignalR transport in a SignalR.Transport package

### ISSUE THREAD

**Issue by MircoBabin** [SignalR/SignalR#3294]
I'm currently using SignalR to provide a one-to-one pipeline from c# client to web browser tab. This scenario is not what SignalR is designed for.

It would be very great if just the transport between C# (without the messagebus system, without the hub system, without the IPersistentConnection system) and the webbrowser could be used as a NuGet package. So the long-polling, websockets, foreverframe or what ever transport between server and browser can be reused without the SignalR design choice for one-to-many or many-to-many.

**Comment by davidfowl** [comment]
Without the client protocol either?

**Comment by MircoBabin** [comment]
the c-Sharp to JavaScript protocol should be provided, with heartbeat,
reconnect, fallback and all other transport options. The messages sent
however are strings without any format. Maybe they should be bytes without
format. This option is now available using ArraySegment.

Op zondag 18 januari 2015 heeft David Fowler <notifications@github.com> het
volgende geschreven:

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
