### ISSUE TITLE
SignalR Connect request hangs on AuthorizeRequest state

### ISSUE THREAD

**Issue by pushist1y** [SignalR/SignalR#3295]
Just like in Issue #3154 
![IIS Screen](http://i.imgur.com/UFh84bd.png)

I've made an app illustrating this problem: http://portal.budget21.ru/ftp/test/SignalR_Test.zip

It reproduces on two computers
First: Win 7 + IIS 7.5
Second: Win Server 2008 R2 + IIS 7.5

using latest available SignalR and dependencies (SignalR 2.1.2, Microsoft.Owin 3.0.0 etc), used DLLs included in project.

**Comment by guylando** [comment]
@halter73 is what you described the explanation to what I have written in this issue: https://github.com/SignalR/SignalR/issues/4095 ?

**Comment by deepsuvarna** [comment]
I had this same issue on the server. But in my case the problem was related to a missing feature on the server. Basically the websocket protocol feature needs to be installed.
