### ISSUE TITLE
SignalR using ModernHttpClient hangs

### ISSUE THREAD

**Issue by kjeremy** [SignalR/SignalR#3298]
I'm trying to use [ModernHttpClient](https://github.com/paulcbetts/ModernHttpClient) for my Xamarin app by creating a new `DefaultHttpClient` that overrides 

```
protected virtual HttpMessageHandler CreateHandler()
{
    return new DefaultHttpHandler(_connection);
}
```

with 

```
protected virtual HttpMessageHandler CreateHandler()
{
    return new NativeMessageHandler();
}
```

but somewhere along the way it hangs.  Simply Replacing the message handler (which I thought was generic) fails.

**Comment by peterno** [comment]
You are not specifying on what platform you get the hang but for me iOS works without any problems. On Android it crashes but I have found a solution. Check issue #3439 where I have provided a solution.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
