### ISSUE TITLE
Cannot mock type safe Clients on Hub

### ISSUE THREAD

**Issue by kvisscher** [SignalR/SignalR#3299]
I'm unable to mock the `Clients` property on a generic `Hub<T>` because it is readonly. I think this is a bug because the dynamic `Hub` _does_ have a getter and setter.

**Comment by YakupIpek** [comment]
More simpler workaround would be introduce your own Generic Hub. Here is simply one
```c#
    public class HubBase<T> : Hub<T> where T : class
    {
        private IHubCallerConnectionContext<T> clients;
        public new IHubCallerConnectionContext<T> Clients
        {
            get
            {
                return clients ?? base.Clients;
            }
            set
            {
                clients = value;
            }
        }
    }
```

**Comment by jmfullerton** [comment]
Was this ever done?  I'm still having trouble mocking my hub based on Hub<T>.  In particular my hub uses Client.Others which is a read-only property.

**Comment by moozzyk** [comment]
You can mock IHubCallerConnectionContext interface and return whatever you see fit.
