### ISSUE TITLE
OAuth2/OIDC Token Authorization

### ISSUE THREAD

**Issue by billpratt** [SignalR/SignalR#3300]
Since WebSocket doesn't support the Authorization header, would you suggest setting the OAuth2/OIDC authentication token as a cookie to authenticate the user trying to connect to SignalR? With this route, you would could extend OAuthBearerAuthenticationProvider and override RequestToken to check for the cookie.  Thoughts?

``` csharp
app.UseOAuthBearerAuthentication(new OAuthBearerAuthenticationOptions
{
    Provider = new AppOAuthBearerAuthenticationProvider(),
});


public class AppOAuthBearerAuthenticationProvider : OAuthBearerAuthenticationProvider
{
    public override Task RequestToken(OAuthRequestTokenContext context)
    {
        var token = context.OwinContext.Request.Cookies["BearerToken"];
        if (!string.IsNullOrEmpty(token))
            context.Token = tokenCookie;

        return Task.FromResult<object>(null);
    }
}
```

**Comment by abergs** [comment]
This is of interest to me as well.
@billpratt Did you successfully implement the above suggestion?

**Comment by billpratt** [comment]
We tabled it for now.

**Comment by dealproc** [comment]
You can either:

* Pass it as a query string parameter
* Call a Web API endpoint to exchange the bearer token for an authorization cookie, and then the cookie should flow up to the SignalR controller through web sockets, IIRC.

**Comment by kevygreen** [comment]
You can use the following to take a query string parameter and add it to the headers list server side to make it work the same. Just call it from your Startup Class.

public void ConfigureAuth(IAppBuilder app) {
	//It needs for file downloads
	app.Use(async (context, next) =>
	{
		if (context.Request.QueryString.HasValue) {
			if (string.IsNullOrWhiteSpace(context.Request.Headers.Get("Authorization"))) {
				var queryString = HttpUtility.ParseQueryString(context.Request.QueryString.Value);
				string token = queryString.Get("access_token");
				if (!string.IsNullOrWhiteSpace(token)) {
					context.Request.Headers.Add("Authorization", new[] {$"Bearer {token}"});
				}
			}
		}
		await next.Invoke();
	});
	// Enable the application to use bearer tokens to authenticate users
	//app.UseOAuthBearerTokens(OAuthOptions);
}
