### ISSUE TITLE
SignalR Hub Clients.Client(<ConnectionId>).method not being called

### ISSUE THREAD

**Issue by Bompti** [SignalR/SignalR#3302]
I am using a .NET SignalR Client connecting to a Owin self host server.
When I try to call a client method like this: 

```
Dim myTestHub = GlobalHost.ConnectionManager.GetHubContext(Of TestHub)()
myTestHub.Clients.Client(<ConnectionId>).Test()
```

nothing happens, but it works if I do like this:

```
Dim myTestHub = GlobalHost.ConnectionManager.GetHubContext(Of TestHub)()
myTestHub.Clients.All().Test()
```

**Comment by nikahat** [comment]
hi could you please elaborate, how you solved your problem.
