### ISSUE TITLE
Can't build sample for WindowsPhone 8

### ISSUE THREAD

**Issue by sensboston** [SignalR/SignalR#3303]
I'm always getting warnings: 
Warning 111 The primary reference "System.Net.Http.Extensions" could not be resolved because it has an indirect dependency on the framework assembly "System.Threading.Tasks, Version=2.6.9.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. "WindowsPhone,Version=v8.0". To resolve this problem, either remove the reference "System.Net.Http.Extensions" or retarget your application to a framework version which contains "System.Threading.Tasks, Version=2.6.9.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".    Microsoft.AspNet.SignalR.Client.WP8.Samples

So, it can't use reference to "Microsoft.AspNet.SignalR.Client.Portable" and can't create the app.

Tried to update all NuGet packages but no luck at all :( I also tried an official release and working copy - same bug.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
