### ISSUE TITLE
SignalR Client methods not getting called by controller

### ISSUE THREAD

**Issue by rosenhu555** [SignalR/SignalR#3305]
Hi, I'm using SignalR on Windows 7, IIS 7.5. It works perfectly if I call the client methods from Hub, but the clients methods never get called from the MVC controller, without any errors.

```
In Controller:
var hubContext = GlobalHost.ConnectionManager.GetHubContext<ConfirmationHub>();
hubContext.Clients.Group(groupName).drawTable();

In Hub:
public void PushConfirmationUpdates(string groupName)
{
    // Clients.Group(groupName).drawTable() would have worked if not for comparison purpose
    var hubContext = GlobalHost.ConnectionManager.GetHubContext<ConfirmationHub>();
    hubContext.Clients.Group(groupName).drawTable();
}
public Task JoinGroup(string groupName)
{
    return Groups.Add(Context.ConnectionId, groupName);
}

In Javascript file:
$.connection.hub.url = "https://localhost:8700/signalr";
$.connection.hub.logging = true;
var confirmationProxy = $.connection.confirmationHub;   
confirmationProxy.client.drawTable = function () {
    // function implementation
};
$.connection.hub.start({ jsonp: true }).done(function () {
    var groupName = $("#groupName").val();
    confirmationProxy.server.joinGroup(groupName);
    $("#invokeButton").click(function () {
            confirmationProxy.server.pushConfirmationUpdates(groupName);
        }              
    });
});
```

I already updated SignalR to 2.1.2, and tried both IIS Express and full IIS, still the same behavior. Any ideas?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
