### ISSUE TITLE
TypeLoadException when use strongly typed Hub with an inherited interface

### ISSUE THREAD

**Issue by delfuria** [SignalR/SignalR#3311]
Hi,
On my project i have installed the latest versions of all packages and use a strongly type Hub declared in this way:

```
public class HubSync : Hub<ISendHubSync>
```

 on ISendSync.cs i have declared the class that inherit from a base class in this way:

```
public interface ISendHubSync : ISendHubSyncBase
{
    void AddMessage(string name, string message);
    void SendHelloObject(HelloModel hello);
}
public interface ISendHubSyncBase
{
    void Heartbeat();
}
```

If i compile and run all works fine until i try to invoke the AddMessage from that client.
When i do that i get a TypeLoadException.

If i move the definition of HeartBeat() from the base class to the inherited class all works fine in any case.

What has been wrong ??

**Comment by IanYates** [comment]
Just saw this in the release notes whilst checking for updated NuGet packages.  Yay - will give it a go :)
