### ISSUE TITLE
Signalr Documentation Links broken

### ISSUE THREAD

**Issue by ecogtip** [SignalR/SignalR#3312]
Hi,

Just wondering if its just me. But each time I click on one of SignalR documentation link it says "Page you are looking is not available"...

http://www.asp.net/signalr/overview/hubs-api/hubs-api-guide-server

more power

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
