### ISSUE TITLE
SignalR & IE Issue - poll is pendidng

### ISSUE THREAD

**Issue by ythouma** [SignalR/SignalR#3314]
I have a Problem With IE and SignalR, I'm using the it to perform a Syncing action between two databases, the Actions Completed successfully on Google Chrome / Firefox / Safari in all scenarios.

Using IE for the First time the sync performed successfully but only for one time, in the second time a pending request stack and the page stay freeze for ever.
I found a solution online which is changing the transport mode:
![3](https://cloud.githubusercontent.com/assets/9248735/4642696/171076e4-5448-11e4-9728-e4355b554b8f.PNG)

But page still freezing. check bellow Images
![1](https://cloud.githubusercontent.com/assets/9248735/4642530/2e344bb8-5446-11e4-9e18-feb193798d97.PNG)

![2](https://cloud.githubusercontent.com/assets/9248735/4642626/630357fc-5447-11e4-9205-eeebd727de37.PNG)

I'm Using:
SgnalR v2.1.0.0
.Net framework v4.5
jquery v1.8

is it an Issue or I'm Doing something wrong ?

**Comment by MosheL** [comment]
just add this and forgot all:

https://github.com/Yaffle/EventSource/
