### ISSUE TITLE
Error: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: %. 

### ISSUE THREAD

**Issue by Taras-od-ua** [SignalR/SignalR#3319]
Hi, all. We are using the SignalR(ASP.NET SignalR JavaScript Library v2.1.1) to send the messages to our users. In most cases it works fine.  But, sometimes we have the same pattern of error. 
It is production env. with LoadBalancer.

Error: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: %. Path '', line 0, position 0. at Newtonsoft.Json.JsonTextReader.ParseValue() at Newtonsoft.Json.JsonTextReader.ReadInternal() at Newtonsoft.Json.JsonTextReader.Read() at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) at Microsoft.AspNet.SignalR.Json.JsonSerializerExtensions.Parse[T](JsonSerializer serializer, String json) at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.AuthorizeRequest(IRequest request) at Microsoft.AspNet.SignalR.PersistentConnection.ProcessRequest(IDictionary`2 environment) at Microsoft.AspNet.SignalR.PersistentConnection.ProcessRequest(IDictionary`2 environment) at Microsoft.Owin.Mapping.MapMiddleware.d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage.d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously){prod}

Details below.

Client send to server request.

Requested URL: http://ourprodaction.com/signalr/negotiate?clientProtocol=1.4&connectionData=%255B%257B%2522name%2522%253A%2522notificationhub%2522%257D%255D&_=1413301809110
It can be different type(reconnect, abort, negotiate).

I look through our sources and sources of SignalR. Exception is at line 108 of https://github.com/SignalR/SignalR/blob/3f63af8bd51812c4b4280c946d9870775d6e2c1f/src/Microsoft.AspNet.SignalR.Core/Hubs/HubDispatcher.cs
I am sure, The cause of this error is parameter connectionData with value
%255B%257B%2522name%2522%253A%2522notificationhub%2522%257D%255D

this value is URL-encoded twice.
The value should be
%5B%7B%22name%22%3A%22notificationhub%22%7D%5D
which is encoded version of
[{"name":"notificationhub"}]
I didn't find any reasonable workaround. Also we don't have clear steps to reproduce it. But definitely the error is in SignalR layer (client-server interaction)

---
## JS in _Layout

```
/*SignalR Section*/
var hub = $.connection.NotificationHub;

if (hub) {

    hub.client.appendNewMessage = function (id, clientName, photo, message) {

        addMsg(clientName, getImgUrl(photo), message);
        sendConfirmation(id, confUrl);
    };

}
/* Start the hub connection*/
if ($.connection.hub && $.connection.hub.state === $.signalR.connectionState.disconnected) {
    $.connection.hub.start({ transport: 'longPolling' })
        .done(function() {
        })
        .fail(function(error) {
        });

    $.connection.hub.disconnected(function () {
        setTimeout(function () {

            $.connection.hub.start({ transport: 'longPolling' });
        }, 5000); /* Restart connection after 5 seconds.*/
    });
}
```

---
## server side code

```
[assembly: OwinStartup(typeof(Startup))]
namespace ThinkTimeWeb.Code.SignalR
{
    public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            var idProvider = new CustomUserIdProvider();
            GlobalHost.Configuration.ConnectionTimeout = TimeSpan.FromSeconds(30);

            GlobalHost.DependencyResolver.Register(typeof(IUserIdProvider), () => idProvider);
            app.MapSignalR();
        }
    }
    [HubName("NotificationHub")]
    public class NotificationHub : Hub
    {


        public static void BroadcastMessage(UserNotificationDto dto)
        {
            try
            {
                lock (_runLock)
                {
                    var context = GlobalHost.ConnectionManager.GetHubContext<NotificationHub>();

                    if (Connections.Exists(dto.UserRid))
                    {
                        switch (dto.Type)
                        {
                            case NotificationType.Text:

                                foreach (var con in Connections.GetConnections(dto.UserRid))
                                {
                                    context.Clients.Client(con).appendNewMessageTo(dto.Id, dto.FullName, dto.Photo, dto.Message);
                                }
                                break;
                            case NotificationType.Link:
                                foreach (var con in Connections.GetConnections(dto.UserRid))
                                {
                                    context.Clients.Client(con).appendMessageWithLinkTo(dto.Id, dto.FullName, dto.Photo, dto.Message);
                                }

                                break;

                            default:
                                throw new ArgumentOutOfRangeException();
                        }
                    }
                }
            }
            catch (Exception ex)
            {

                _log.ErrorException(ex.Message, ex);
            }
        }


        #region Overriding
        public override Task OnConnected()
        {
            var name = String.Empty;

                name = Context.User.Identity.Name;


                Connections.Add(name, Context.ConnectionId);

                return base.OnConnected();

        }

        public override Task OnDisconnected(bool stopCalled)
        {
            var name = String.Empty;

                name = Context.User.Identity.Name;
                Connections.Remove(name, Context.ConnectionId);
                return base.OnDisconnected(stopCalled);

        }

        public override Task OnReconnected()
        {
            var name = String.Empty;

                name = Context.User.Identity.Name;


                    Connections.Add(name, Context.ConnectionId);

                return base.OnReconnected();

        }

        #endregion


    }    
}
```

**Comment by hyperion1** [comment]
I have totally the same problem! In addition I found that this problem occures only for UserAgent: Mozilla/4.0+(compatible;+MSIE+8.0;+Windows+NT+5.1;+Trident/4.0) i.e Internet Explorer 8. Common things for all records that generate this error is: all of then have the above user agent; all of them use ServerSendEvent and return status is 200.

**Comment by kberawala** [comment]
any solutions on this issue ?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
