### ISSUE TITLE
Still get signalr connection has not been fully initialized. use .start().done() on 2.0

### ISSUE THREAD

**Issue by wyx2000** [SignalR/SignalR#3323]
![s12](https://cloud.githubusercontent.com/assets/1753969/4775133/ba00afcc-5bb4-11e4-8b97-0a729aff81e6.png)

Here is my initial code

```
$.getScript('http://' + agenthost + '/signalr/hubs', function () {
  var signalrurl = 'http://' + agenthost + '/signalr';
  $.connection.hub.url = signalrurl;
  $.connection.llift.client.notify = function (r) { agent.notify(r); };
  ...
  var huboptions = {};
  if (urlParams["method"])
    huboptions["transport"] = urlParams["method"];
  $.connection.hub.start(huboptions).done(function () {   
    $.connection.llift.server.join('00000000-0000-0000-0000-000000000000_monitorkey=' + token).done(
      function (rows) {
          ....
```

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
