### ISSUE TITLE
Minified javascript client is missing final semi-colon

### ISSUE THREAD

**Issue by webley** [SignalR/SignalR#3326]
The minifier used to generate jquery.signalR.min.js seems to be stripping the semi-colon at the end of the file.  This makes it impossible to concatenate files after it without generating script errors.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
