### ISSUE TITLE
Returning from Suspend Mode takes a long time before reconnect/new start happend. (need for better useability)

### ISSUE THREAD

**Issue by SharryTvTeam** [SignalR/SignalR#3330]
Hello,

when an Windows Universal App comes back from suspend mode, the SignalR Store Client take a long time to detect that he lost the connection and go to reconnect/new start (we use default timeouts).
It would be much better when signalR can check this faster (he can know how long the suspend was). Or we get a function to call CheckIfShouldReconnect() or something that we can call on app resume. Now our Customers must wait up to 10/20 seconds before they can continue with using the app.

**Comment by davidfowl** [comment]
@SharryTvTeam can't you handle this in your application?

**Comment by SharryTvTeam** [comment]
We have tried, but could not get this to work stable. We stop the current connection at suspending and start it again on resuming. That is not nice when you simply toggle applications to copy text, but it works for us. We hope that such things are implemented in the signalR framework in the next releases.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
