### ISSUE TITLE
 .Net client 2.1.2 connection issues with distributed SignalR hosted on Azure

### ISSUE THREAD

**Issue by uzibaron** [SignalR/SignalR#3333]
Hi,

When using the .Net client from nuget (Microsoft.aspnet.signalR.client) version 2.1.2 and connecting to a load balanced cloud service on azure, the OnConnected fires on server A, however the client sometimes (measured 50% of the times) connects to server B and keeps that connection open (monitoring with wireshark shows this behavior).

The main issue is that when the load balancer redirects the connection traffic to server B, OnConnected never fires on B and there is no way to persist that connection correctly in a custom backplane. (SQL at this case)

After investigating further and noticing that other signalR clients (android,iOS) do not have this issue, I've tried using the portable client (Microsoft.aspnet.signalR.client.portable) and that works 100% of the times from a .NET desktop client and WP8.

I guess there's some difference between 2.1.2 and portable 2.0.0 versions.

Thanks,
Uzi

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
