### ISSUE TITLE
SignalR + DirectX 12

### ISSUE THREAD

**Issue by grendizerufo** [SignalR/SignalR#3336]
hi
I hope to work for merging Signalr with DirectX 12 in next version of Signalr.

also I wish to build new solution build in native code C++ for online desktop pc to be used as self server to manage internet online data  ^_^ useful for online games client/server

the last thing I wish is to build new type of Signalr code, one for DirectX store app as manage code and other for DirectX desktop app as native code to make developer of DirectX to build online game and Engine games with SingalR Network.

this words for Mr.DamianEdwards 
thanks

**Comment by BrannonKing** [comment]
To clarify, you are looking for a native C++ SignalR client?

**Comment by moozzyk** [comment]
C++ client is developed here https://github.com/aspnet/SignalR-Client-Cpp
