### ISSUE TITLE
signalR save promise after disconnection

### ISSUE THREAD

**Issue by amitbarkai** [SignalR/SignalR#3338]
In the start method, the deferred being used is sometimes the one saved on the _connection object.
if you listen to the disconnect event of the hub, and try to initiate another connection, you get the previous deferred object, which is already resolved, and the hub doesn't try to connect again.
It seems that the deferred has not yet been deleted (it should be in the stop method that is initiated from the disconnect inner event).

**Comment by educielo** [comment]
Also facing this Problem. When disconnect fires all client sharing same connection fails to be called

**Comment by moozzyk** [comment]
Fixed in 6e55467a2d487cd4cf8de48a276f15207a3534a9
