### ISSUE TITLE
Signalr always falls to long polling in the production server

### ISSUE THREAD

**Issue by catchsrinivas** [SignalR/SignalR#3340]
When i host the application in the server it checks for the server side events and falls back to long polling always. The server hosting environment is Windows Server 2012 R1 and IIS 7.5

Is there anyway if we can solve this issue?

**Comment by tertork** [comment]
I just had the same problem on our test server running in Amazon AWS. It looks like it is a problem with the corporate proxy server. It is working if I use HTTPS, just not with HTTP.

**Comment by xleon** [comment]
Exactly same thing in Azure websites. In my case connecting from a Xamarin client (with Signalr PCL nugget) which does not support web sockets. It tries to connect with SSE and always falls back to LP.
Connecting the same client to my local web server (IIS express) SSE works fine

**Comment by xleon** [comment]
@tertork ohhhh yeahhh! using https in Azure made the trick!!
I spent about 4 hours before getting to this issue and your comment :)

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Comment by KantJoe** [comment]
i meet this problem at .net core 3.1 signalrcore

**Comment by satish2832** [comment]
Problem is there with nginx server with aws
