### ISSUE TITLE
http://signalr.net/ Website Down due to GitHub Pages DNS Changes

### ISSUE THREAD

**Issue by a-h** [SignalR/SignalR#3341]
https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/
https://github.com/blog/1917-github-pages-legacy-ip-deprecation

Requires admin action.

**Comment by nitinag** [comment]
Seems to be pointing to the correct ip now:
https://www.misk.com/tools/#dns/signalr.net

https://help.github.com/articles/tips-for-configuring-an-a-record-with-your-dns-provider/

This issue can be closed.
