### ISSUE TITLE
SignalR negotiate fails with "query string is too long"

### ISSUE THREAD

**Issue by n9** [SignalR/SignalR#3348]
In case a project has a lot of hubs, `negotiate` fails with "query string is too long". It is because names of all hubs are sent via GET request in query string:

`signalr/negotiate?clientProtocol=1.5&connectionData=<all the names in JSON here>`

Suggestion: What about to send connectionData in body of POST request?
Question: How to use SignalR in projects with many 'hub' classes? Is possible to tweak SignalR not to send all hub names?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Comment by hwalborn** [comment]
This is still an outstanding issue for me. I have many hubs in my solution and the negotiation fails because of the length of the query string. I have updated my web.config so that it can accept longer query strings on the backend, however that seems like a temporary solution. @aspnet-hello can we re-open this issue?

**Comment by anurse** [comment]
This would be a pretty significant, and protocol-breaking change, so it would be very difficult to do it outside of a major release (which isn't planned). We'd have to seriously consider the impact of doing this. Why do you feel like adjusting your server configuration is a temporary solution? It sounds like preceisely the right solution here.

**Comment by hwalborn** [comment]
@anurse thank you for getting back to me so quickly! We will continue with accepting longer max query string lengths for now.

**Comment by anurse** [comment]
Ok @hwalborn ! Thanks for the response. This is something we're [looking to improve in ASP.NET Core SignalR](https://github.com/aspnet/SignalR/issues/1802) because of precisely this problem.
