### ISSUE TITLE
No response to client when hub is not found on the server 

### ISSUE THREAD

**Issue by n9** [SignalR/SignalR#3349]
When I misspell name of a server hub, `System.InvalidOperationException` with "'{hubname}' Hub could not be resolved." message is thrown in `HubManagerExtensions.EnsureHub`. But it is silently ignored and client does not get any response.

**Exprected:** Client should receive this error message.

**Condition:** This situation occurs when the hub has [no client callbacks and therefore it does not fail in `negotiate`](https://github.com/SignalR/SignalR/issues/3348#issuecomment-64488855). (Since in `negotiate` the error is returned properly.)

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
