### ISSUE TITLE
Older Server (Protocol 1.2) does not connect to newer Client (Protocol 1.4)

### ISSUE THREAD

**Issue by kingtimm** [SignalR/SignalR#3360]
When connecting to a server that uses protocol 1.2, the client using protocol 1.4 will say: 

```
There was an error opening the connection:System.InvalidOperationException: You are using a version of the client that isn't compatible with the server. Client version 1.4, server version 1.2.
```

Normally, I would upgrade the server. However, it belongs to a major consumer electronics company. Access to their SignalR server is provided as part of their developer kit to integrate with the internet connected devices they sell (Thermostats, Light switches, etc). 

Downgrading the client version to 1.2.2 (which uses protocol version 1.2) works fine. However, this limits the number of platforms on which the SignalR client can be used. (I.E. Windows Phone 8.1).

It looks like there are provisions for a server to accommodate lesser protocol versions. The reverse accommodation could help as SignalR infrastructures start opening up to 3rd party integration.

**Comment by simeyla** [comment]
I suppose you could make an intermediary server that just proxies requests through to the 3rd party company. This would probably come with other benefits too such as better ability to log and track.

I've also seen this error when trying to access a /signalr url with http where there is an automatic redirect to https even though the client and server version are both 2.2
