### ISSUE TITLE
Issue using multiple AuthenticationSchemes

### ISSUE THREAD

**Issue by HagashenNaidu** [SignalR/SignalR#3361]
Hi,

We are trying to use multiple authentication schemes i.e. Negotiate, Basic and Anonymous. 

The use case being that the user can authenticate either as Negotiate or Basic and if they do not send any credentials then its anonymous and that is handled a certain way in the system.

Now what seems to happen is if we set just Negotiate and Basic then the Authorization header is sent on the first request.

As soon as we enable Anonymous then the Authorization header is not sent on the first request instead a second request seems to come through and that is the one that has the Authorization header on it.

Not sure if what we are trying to do is possible or if there is something else we need to do in order to achieve the use case?

Any assistance would be greatly appreciated.

**Comment by DamianEdwards** [comment]
Is this specifically a SignalR question/issue? Are you setting up the authentication in IIS? Can you try confirming your desired setup works with a resource that isn't SignalR, e.g. a static file that's protected by an ACL that doesn't include the IUSR account.

**Comment by HagashenNaidu** [comment]
Hi,

No authentication setup in IIS. I will try to the setup outside of SignalR.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
