### ISSUE TITLE
[Suggestion] Add some useful mechanisms for AOP/IOC through attributes

### ISSUE THREAD

**Issue by MaleDong** [SignalR/SignalR#3365]
Hello all:

SignalR has really offered us an easy way to implement IOC, however there seems to be an easier way for us to do using Attributes, with more features for IOC/AOP.

For example:
I'm now doing an IntegrationTest so that I have to write something like Log.Info……directly in each of them method by starting a stopWatch and end the stopWatch to calculate the real time for each method in the hub (how long it does take!)
However I think we can have a better way to cope with that: We can have some attribute like "AutoLogger", this attribute can be either used for a class, or for a single method to automatically calculate each method's real spending time by outputting the current method's name, start time, end time……. Of course, if a method doesn't need logger, another attribute called "NoLogger" should take functions.

The words above are just an easy to explain how easy and important AOP/IOC with attributes is! Just like MVC's AOP/IOC. Maybe we can invent something mechanism like that (including customized attributes……), my design is:

1) Open an interface called ICustomizedAttribute:
public interface ICustomizedAttribute
{
   void OnBeforeExecuteCurrentHub();  //Auto called when client's js starts to call the hub.
   void OnAfterExecuteCurrentHub();     //Auto called when the hub's method ended (before return).
}

2) Provide an abstract class from the interface, the suffix is "Attribute". All the customized attributes must be from the abstract class to implement their own logic codes.

3) Maybe we can also provide something like "OnErrorAttribute" (a delegate parameter attribute)....

**Comment by DamianEdwards** [comment]
As part of the work on v3 of SignalR we're taking advantage of the new IoC/DI support in ASP.NET 5. I'd ask you to take a look at the details of that and offer your suggestions regarding support for alternate patterns over at https://github.com/aspnet/DependencyInjection or https://github.com/aspnet/SignalR-Server as appropriate.

Thanks.

**Comment by MaleDong** [comment]
@DamianEdwards 

Many thanks! Can v3 of SignalR be used in VS2013?
