### ISSUE TITLE
SignlaR with Android et IOS

### ISSUE THREAD

**Issue by JanickRoss** [SignalR/SignalR#3367]
Is possible to use SignalR with Android et IOS mobile app or i must you other framework ? Buy xamarin is not a option ;(

Thnaks

**Comment by DamianEdwards** [comment]
We have an official Java client at https://github.com/SignalR/java-client which you can use with Android.

There is a community maintained iOS client at https://github.com/DyKnow/SignalR-ObjC

We are currently working on a C++ client (https://github.com/aspnet/SignalR-Client-Cpp) that will one day hopefully be usable natively from iOS apps (including Objective-C apps) but that's a ways off yet.
