### ISSUE TITLE
Mono SelfHost Performace / Latency

### ISSUE THREAD

**Issue by WJ-GitHub** [SignalR/SignalR#3372]
Tried SignalR SelfHost under Windows 7 (Core-i7) (localhost and ethernet-server) and Mono on Debian (Raspberry) and Ubuntu (virtualbox an ethernet-server).

Server Code Hub:

public int GetResult(double input)
{
return 1234;
}

Client Code:

DateTime start = DateTime.Now;
Task<int> t = chatHubProxy.Invoke<int>("GetResult", 0);
t.Wait();
label.Text = t.Result.ToString() + " " + (DateTime.Now - start).TotalMilliseconds;

Seen that the response times on windows machines are great (!!!) around 1ms also over ethernet.

Simple SelfHost on Mono shows performance issuses.
Raspberry: ~2700ms
Ubuntu (localhost): ~270ms

Looking around for solutions i found following post: http://stackoverflow.com/questions/26863525/latency-issues-with-self-hosting-a-simple-nancyfx-helloworld-application-running

With HAProxy and following configuration:

listen l1 0.0.0.0:8081
server srv1 127.0.0.1:8080

performance seems 4 times better (!?!?!?):
Raspberry: ~600ms
Ubuntu (localhost): ~70ms

Could anyone confirm ? What is the problem connecting the server direcly ? Why ist the latency over proxy-server better ? Problem of SignalR or Mono (because NancyFX seems having same problems) ? Any better proxy-servers than HAProxy ? What about WebSockets on Mono ? Will they give more performance ?

Greetings

**Comment by DamianEdwards** [comment]
This type of question is better asked on StackOverflow.com or our forums at http://forums.asp.net/1254.aspx
