### ISSUE TITLE
Value cannot be null. Parameter name: s on page load

### ISSUE THREAD

**Issue by bladefist** [SignalR/SignalR#3374]
Using SignalR 2.2

I am getting this error out of SignalR on the page load.  I find that odd because signalr is loaded via javascript, how would it crash the initial page load?  

Stack Trace:

System.ArgumentNullException: Value cannot be null. Parameter name: s
 at System.IO.StringReader..ctor(String s)
 at Microsoft.AspNet.SignalR.Json.JsonSerializerExtensions.Parse[T](JsonSerializer serializer, String json)
 at Microsoft.AspNet.SignalR.Hubs.HubRequestParser.Parse(String data, JsonSerializer serializer)
 at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.OnReceived(IRequest request, String connectionId, String data)
 at Microsoft.AspNet.SignalR.<>c__DisplayClass8.<>c__DisplayClassa.b__5()
 at Microsoft.AspNet.SignalR.TaskAsyncHelper.FromMethod(Func`1 func)

**Comment by paaland** [comment]
Any update? We get the same exception logged seemingly at random intervals. Some clients get them more often than others.

**Comment by bladefist** [comment]
@paaland  No, I'm still having this issue.  Makes me feel a little better I'm not the only one. Unfortunately it's really hard to duplicate.

**Comment by halter73** [comment]
@bladefist If your users are seeing a yellow screen of death with the above stack trace, that indicates that users are being directed to a URL that is handled by SignalR.

When you get these screenshots from users, is there a visible URL in the address bar? Does your exception logging tool provide this information?

P.S. It can sometimes be a security issue to show detailed exception messages to end users.

**Comment by bladefist** [comment]
@halter73  Here is an image, has the url too if you want to check the page: http://i.imgur.com/t5i48Z3.png

**Comment by DamianEdwards** [comment]
This is very strange. I was able to reproduce this against your site however from my end obviously there's no detail. It appears from the response headers that the request made it through your reverse proxy (nginx) and IIS was hit, but I have no idea how the SignalR endpoint logic is running instead of your MVC controller. Certainly not in a random way.

All I can think of is that perhaps you're running multiple servers and one of them is badly configured? Or you've accidently correlated the wrong failing request with the corresponding stack trace? FWIW here is the CF-RAY ID of the request I saw fail: 1ab7609b55e20c4d-SEA

If you could somehow provide an example of how your application is configured (copy of Startup.cs, web.config, Global.asax.cs, route configuation, etc.) then we might see something stand out, but this is certainly a head scratcher.

**Comment by bladefist** [comment]
@DamianEdwards  Thanks for the response.  There is only one IIS server, and that ngix you are seeing is Cloudflare.  

My Statup.cs is below, it's the default from the example.  There is nothing in my web.config pertaining to SignalR, it's a default implementation.  Globals and Route registration is all default MVC 4 project code.  I am using attribute routing on some of my controller actions, and that page you looked at is in an area.  

Maybe @paaland can add more helpful info.   Is there any way to handle the exception and just stop the errors from happening in the event s is null? I'm not up to speed on signalr interal code, but if you google that exception, there are plenty of hits, just not many answers.

Thanks!

Start Up:
[assembly: OwinStartup(typeof(TrackerBase.Startup))]
namespace TrackerBase
{
    public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            app.MapSignalR();
        }
    }
}

**Comment by paaland** [comment]
The site we are experiencing this issue on is using single sign-on (NTLM/Windows Authentication). My investigations so far point to an issue here. What we see (using Fiddler) is that some of the SignalR requests to the server results in status 400, and content-length 0. Which I guess is why Microsoft.AspNet.SignalR.Hubs.HubRequestParser.Parse() failes (the response body is empty). 

My best theory now is that my problem is related to this: http://blogs.msdn.com/b/asiatech/archive/2012/01/30/400-bad-request-when-posting-webservice-or-wcf-request-from-ie.aspx

Seems SignalR requests does not like being challenged by NTLM.

The application is a long-running silverlight app that uses SignalR to update on data change. So for long periods of time nothing might happen. The application works fine for a long time, but sometimes the parse error appear in the log. And that corresponds with IIS challenging the request with 400, content-length 0. I assumed that it was IE's responsibility to respond to the challenge and reissue the request?

If there has been a disconnect/reconnect, IIS appPool recycle or what ever I dont know. But sometimes the "state" is altered in such a way the SignalR stops working and reloading the application is the only way to fix it again.

**Comment by DamianEdwards** [comment]
@paaland can you sure your client code where you create the connection pls? Specifically, want to see how you are adding the Windows credential and *any* place you create a new HubConnection.

Note, the `Microsoft.AspNet.SignalR.Hubs.HubRequestParser` type is on the server only, so if its failing then it isn't due to an empty response due to challenge.

**Comment by juanfausd** [comment]
Hi guys! How is it going? I'm having the same error. I'm using SignalR version 2 and a Startup class in order to allow CORS when my sites init. Do you find a solution for this? Thanks in advance :)

**Comment by tnesser** [comment]
Hi, 

Got the same problem, but for us it seems to be a chrome problem. We have a Silverlight 5 client, and when we use IE there is no warnings in the event log. using Chrome creates a 3005 error with a ArgumentNullException. I think there probably is some kind of authentication issues. 

Client is SignalR 2.2.0

**Comment by styfle** [comment]
@DamianEdwards 
I'm having the same problem with 2.2.0. It looks like the client is attempting to use `NTLM`. Here are the headers and relevant parts of the code.

**Headers**

```http
Cache-Control: no-cache
Connection: Keep-Alive
Content-Length: 0
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Accept: text/plain, */*; q=0.01
Accept-Encoding: gzip, deflate
Accept-Language: en-US
Authorization: NTLM TlRMTVNTUAABAAAAB4IIogAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADw==
Cookie: user={"id":5216,"fullName":"Bill Johnson","email":"Bill.Johnson@example.com","memberSince":"2011-05-17T19:42:57Z","isLoggedIn":true}; _pk_id.1.46c3=f9d63bf676af25ea.1436459363.40.1440011478.1440011172.
Host: myapp.example.com
Referer: http://myapp.example.com/MyApp/Pages/Page.aspx?prj=4&n=506732
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
X-Requested-With: XMLHttpRequest
DNT: 1
```

**StackTrace**

```
System.ArgumentNullException: Value cannot be null.
at System.IO.StringReader..ctor(String s)
   at Microsoft.AspNet.SignalR.Json.JsonSerializerExtensions.Parse[T](JsonSerializer serializer, String json)
   at Microsoft.AspNet.SignalR.Hubs.HubRequestParser.Parse(String data, JsonSerializer serializer)
   at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.OnReceived(IRequest request, String connectionId, String data)
   at Microsoft.AspNet.SignalR.PersistentConnection.<>c__DisplayClassa.<>c__DisplayClassc.<ProcessRequestPostGroupRead>b__7()
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.FromMethod(Func`1 func)
```


**Client**

```js
var connectionId;
var connection = $.hubConnection('/MyApp/signalr', { useDefaultPath: false });
connection.logging = true;
connection.qs = { usrId: getUserId() };
myHub = connection.createHubProxy('myHub');

myHub.connection.disconnected(function () {
	// Try to reconnect after 5 seconds
	setTimeout(function () {
		connection.qs = { usrId: getUserId(), prevConId: connectionId };
		conPromise = connection.start();
	}, 5000);
});
			
connection.start().done(function () {
	console.log('SignalR connected with ConectionId: ' + connection.id);
	connectionId = connection.id;
})
```

**Server**

```cs
public class Startup
{
	public void Configuration(IAppBuilder app)
	{
		var hubConfiguration = new HubConfiguration();
		hubConfiguration.EnableDetailedErrors = true;
		hubConfiguration.EnableJavaScriptProxies = false;
		GlobalHost.HubPipeline.AddModule(new EmailErrorHandlingPipelineModule()); // Register error emails
		app.MapSignalR(hubConfiguration);
	}
}

public class MyHub : Hub {
        private readonly static ConcurrentDictionary<string, MyHubConnection> conIdToConnection = new ConcurrentDictionary<string, MyHubConnection>();
	public override Task OnConnected()
	{
		string conId = Context.ConnectionId;
		// Add connection
		int usrId = 0;
		int.TryParse(Context.QueryString["usrId"], out usrId);
		string prevConId = Context.QueryString["prevConId"];
		if (!string.IsNullOrWhiteSpace(prevConId))
		{
			KillConnection(prevConId);
		}
		conIdToConnection.TryAdd(conId, new MyHubConnection() {
			usrId = usrId,
			dateConnected = DateTime.Now,
			dateLastActive = DateTime.Now
		});

		Clients.Group(GROUP_USER_COUNT).userCountChanged(conIdToConnection.Count);
		return base.OnConnected();
	}
	
	public override Task OnReconnected()
	{
		string conId = Context.ConnectionId;
		// Add connection if it does not already exist
		int usrId = 0;
		int.TryParse(Context.QueryString["usrId"], out usrId);
		conIdToConnection.TryAdd(conId, new MyHubConnection()
		{
			usrId = usrId,
			dateConnected = DateTime.Now,
			dateLastActive = DateTime.Now
		});

		Clients.Group(GROUP_USER_COUNT).userCountChanged(conIdToConnection.Count);
		return base.OnReconnected();
	}

	public override Task OnDisconnected(bool stopCalled)
	{
		KillConnection(Context.ConnectionId);
		return base.OnDisconnected(stopCalled);
	}
}
```

**Comment by jhayotte** [comment]
Hi,

After implementation of SignalR in our solution I have got the same issue: 
```
Value cannot be null. Parameter name: s
```

After some hours of investigation it came out that it was due to a rewriting rule. I had a *rewriting rule*  updating in lowercase our url.

**Comment by l0nley** [comment]
Have the same issue.
```
Request URL:http://localhost:59985/signalr/send?transport=serverSentEvents&clientProtocol=1.5&connectionToken=QYQSKLN24KtDK4M3tvmNke4eZ7aNbkEIeAIcpUl0xNyQBogqJDZm2Amsbupv%2BIVAElaMQ%2FTmjOOw242Sg9tiBoKXGULEl%2FI24435i9RxVPslHXBETr%2B6xmwmmz0j6XtW&connectionData=%5B%7B%22name%22%3A%22documentshub%22%7D%5D
Request Method:POST
Status Code:500 Internal Server Error
Remote Address:[::1]:59985

Response Headers
Cache-Control:private
Content-Type:text/html; charset=utf-8
Date:Tue, 19 Jan 2016 09:24:45 GMT
Server:Microsoft-IIS/10.0
Transfer-Encoding:chunked
X-AspNet-Version:4.0.30319
X-Powered-By:ASP.NET
X-SourceFiles:=?UTF-8?B?YzpcdXNlcnNcdWxhZHppbWlyX2hhcmFidHNvdVxkb2N1bWVudHNcdmlzdWFsIHN0dWRpbyAyMDE1XFByb2plY3RzXENyYXRlLldlYlxDcmF0ZS5XZWJcc2lnbmFsclxzZW5k?=

Request Headers
Accept:text/plain, */*; q=0.01
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8
Cache-Control:no-cache
Connection:keep-alive
Content-Length:147
Content-Type:application/x-www-form-urlencoded; charset=UTF-8
Host:localhost:59985
Origin:http://localhost:59985
Pragma:no-cache
Referer:http://localhost:59985/
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
X-Requested-With:XMLHttpRequest

Query String Parameters
transport:serverSentEvents
clientProtocol:1.5
connectionToken:QYQSKLN24KtDK4M3tvmNke4eZ7aNbkEIeAIcpUl0xNyQBogqJDZm2Amsbupv+IVAElaMQ/TmjOOw242Sg9tiBoKXGULEl/I24435i9RxVPslHXBETr+6xmwmmz0j6XtW
connectionData:[{"name":"documentshub"}]
```
```
<package id="Microsoft.AspNet.SignalR" version="2.2.0" targetFramework="net452" />
  <package id="Microsoft.AspNet.SignalR.Core" version="2.2.0" targetFramework="net452" />
  <package id="Microsoft.AspNet.SignalR.JS" version="2.2.0" targetFramework="net452" />
  <package id="Microsoft.AspNet.SignalR.SystemWeb" version="2.2.0" targetFramework="net452" />
```
```
[ArgumentNullException: Value cannot be null.
Parameter name: s]
   System.IO.StringReader..ctor(String s) +11387784
   Microsoft.AspNet.SignalR.Json.JsonSerializerExtensions.Parse(JsonSerializer serializer, String json) +63
   Microsoft.AspNet.SignalR.Hubs.HubRequestParser.Parse(String data, JsonSerializer serializer) +37 
...
```
Error is persistent on my machine. It occurs in 100% of requests, but i cant understand why.

**Comment by moozzyk** [comment]
@l0nley - I don't see any data in your request. If the request headers you showed are the headers for the request that failed then content length is 147 but was there any data really sent?

**Comment by falsebo** [comment]
I find this code  in Jquery.signalr.2.2.1.js 
==>connection.ajaxDataType === "jsonp" ? "GET" : "POST" 
then add $.connection.hub.ajaxDataType="jsonp" and it works well 
in C# source code
this code in ForeverTransport.ProcessSendRequest and this only ReadForm .
INameValueCollection form = await Context.Request.ReadForm().PreserveCulture();
but it not support GET QueryString

**Comment by asherjvitek** [comment]
I was having this same issue and after many hours figured it out. The error was misleading as it was the result of another issue that was not directly showing itself. 

What my Code Does: The Hub runs a background thread that pushes messages back to the Client. The Client can then do subsequent actions after that background thread is done or errors.

Summary of Issue: I would make my first call to my Hub and everything would appear to work. Then on any subsequent call I would get this error. If I refreshed the page(causing a new connection to be created) I could then call the hub 1 time.

Resolution: I had a line of code that was erroring when trying to access my database trying to Authenticate before the background thread would run. The error would not cause the Hub code to stop and the background thread would proceed and push messages back to my Client. I fixed the error calling the Database and this resolved the issue.

The error was related to Authenticating to the database and I think this was causing "something"(very technical) to happen to my Hub that would cause it to generate this error on subsequent calls.

**Comment by moozzyk** [comment]
Maybe the iOS client has a bug but people reported this with C# and JS clients as well.

**Comment by matthew-gordon-westpac** [comment]
I got this error today.  

For me, after some investigation it occurred because in the Hub constructor, I created a new instance of a service, and during the construction of that service, an event was called, which caused a Clients.All.update() in the hub.  However, the hub hadn't finished being constructed by that point, so this error occurred.

The solution for me was to ensure that no "Clients.All.anything()" occurred before the hub's constructor had finished executing.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Comment by Rjtsahu** [comment]
I was able to reproduce same issue recently while i was developing a Signalr-Dashboard-Middleware library on top signalr. This issue happened when client calls send call and transport was ServerSentEvents. Further debugging into it, i found that issue was actually in my code, not in signalr.

The issue was that the IOwinRequest once read by a intecepting middleware  cannot be readed again untill the stream is seeked to ORIGIN , so when signalr-middleware tried to read data from request body it was getting null data so the exception.

So possibly who ever faced this issue is having either due to a bug in middleware or having a proxy server like thing. 

You can find code for above explanation here : https://github.com/Rjtsahu/Signalr-Dashboard/blob/master/Middleware/FilterMiddleware.cs

**Comment by alex-jitbit** [comment]
I keep getting this error with "serverSentEvents" transport occasionally.

This is a heavy used app with 100k users, and I get this error via our global exception-handler.

Why was this issue closed?

**Comment by halter73** [comment]
> So, in order to get back on top of the backlog, we’re going to close all issues that were opened prior to January 1st, 2018. This does not mean we’re not interested in fixing them, it just means they’ve gotten stale and we aren’t able to follow up on them. If one of these issues is affecting you, please feel free to open a new issue with the details and we will be happy to review it. There are a lot of issues in the tracker that are simply no longer relevant, or may have been addressed in a previous release.

https://devblogs.microsoft.com/aspnet/the-future-of-asp-net-signalr/#handlingthebacklogofissues

By all means, feel free to open a new issue. You'll notice in this issue, that there were a bunch of different possible causes, but they mostly boil down to SignalR receiving invalid requests to the `/signalr/send` endpoint without a POST body that contains an application/x-www-form-urlencoded `data` entry.

A network trace using something like fiddler or wireshark would likely help narrow down the issue.
