### ISSUE TITLE
URLs for Self Host Example are Wrong

### ISSUE THREAD

**Issue by agoln** [SignalR/SignalR#3375]
The URL that points to the self host example at the following web page is wrong:
https://github.com/SignalR/SignalR/wiki/Self-host

Currently, it references this page:
http://www.asp.net/signalr/overview/getting-started/tutorial-signalr-self-host

It should reference this page:
http://www.asp.net/signalr/overview/deployment/tutorial-signalr-self-host

**Comment by halter73** [comment]
Thanks!
