### ISSUE TITLE
Configuration of OWIN Self Hosted Application

### ISSUE THREAD

**Issue by btormey** [SignalR/SignalR#3377]
I have an OWIN Self Hosted application which I am trying to add `DisconnectTimeout` settings to, but it seems they are only loaded from the Global.asax. Since self-hosted console applications do not have a Global.asax file, I attempted adding the configuration settings to the Startup.cs file, but those settings never actually seem to get applied -- the default 30 seconds is still present. I also tried adding a Global.asax file to my application, but that file never actually seems to get called when running my application. Is there any other way to add these configuration settings to an OWIN self hosted app?

**Comment by moozzyk** [comment]
Setting in the `Startup` should work. If I set it like this
```
public class Startup
{
    public void Configuration(IAppBuilder app)
    {
        app.MapSignalR();
        GlobalHost.Configuration.DisconnectTimeout = new TimeSpan(0, 0, 20);
    }
}
```
I can see that the DisconnectTimeout in the `negotiate` response is 20 

```{
    "Url":"/signalr","ConnectionToken":"hYV7...5",
    "KeepAliveTimeout":13.3333332,
    "DisconnectTimeout":20.0,
    "TryWebSockets":true,
    "ProtocolVersion":"1.4",
    "TransportConnectTimeout":5.0,
    "LongPollDelay":0.0
}```

**Comment by Brain2000** [comment]
AHA!  Thank you @moozzyk.  Your configuration was the hint I needed to get this working.  The DisconnectTimeout must be set AFTER MapSignalR, or else the defaults will overwrite it if you set it beforehand.

**Comment by bigswede74** [comment]
@moozzyk I'm trying to do the same with the MaxIncomingWebSocketMessageSize but I cannot get the setting to take at all.


`        
            var config = new HubConfiguration
            {
                Resolver = new AutofacDependencyResolver(ContainerProvider.Container),
                EnableDetailedErrors = true,
                EnableJSONP = true,
                EnableJavaScriptProxies = true
            };

            app.MapSignalR("/signalr", config);

            GlobalHost.Configuration.MaxIncomingWebSocketMessageSize = 256000;

**Comment by moozzyk** [comment]
Have you seen this SO thread: https://stackoverflow.com/questions/21126624/signalr-autofac-owin-why-doesnt-globalhost-connectionmanager-gethubcontext? The answer was written by one and only @halter73 so I am sure it will help.I think you would have to resolve `IConfiguationManager` to get access to the [MaxIncomingWebSocketMessageSize](https://github.com/SignalR/SignalR/blob/3c07d7bebc15ec9cbf6ac9d7339b5d2d54f6fab3/src/Microsoft.AspNet.SignalR.Core/Configuration/IConfigurationManager.cs#L51) property. I also think you may need to do this before the transport is created.

**Comment by bigswede74** [comment]
@moozzyk That article helped out, we just had to set the GlobalHost.DependencyResolver as shown below. Thanks for the help.

`
            var config = new HubConfiguration
            {
                Resolver = new AutofacDependencyResolver(container),
                EnableDetailedErrors = true,
                EnableJSONP = true,
                EnableJavaScriptProxies = true
            };

            GlobalHost.DependencyResolver = config.Resolver;
            GlobalHost.Configuration.MaxIncomingWebSocketMessageSize = 1024 * 128`
