### ISSUE TITLE
Strong type hub - Interface inheritance

### ISSUE THREAD

**Issue by Duskheart** [SignalR/SignalR#3379]
Is interface inheritance  is supported?

In my case interface inheritance seem not working.
Example project: https://github.com/Duskheart/SignalRTypedHubException1

**Comment by halter73** [comment]
Thanks for the bug report. This should be fixed in 2.2.0 which we expect to release next week.

You can try out the fix now by using the Signalr nightlies available at https://www.myget.org/gallery/aspnetwebstacknightly.

https://github.com/SignalR/SignalR/issues/3311
