### ISSUE TITLE
SignalR error after a while in IIS.

### ISSUE THREAD

**Issue by javaheri** [SignalR/SignalR#3381]
we are using SignalR 2.0.We have 10 PC in our network,and each PC send notification to other PC in network with HubConnection.
But after a while IIS error "Service Unavailable : HTTP Error 503"
and after Stop/Start Application Pool everything is Ok.

        IHubProxy _hub;
         var connectionHub = new HubConnection("http://192.168.1.5");
         _hub = connectionHub.CreateHubProxy("HubName");
         connectionHub.Start().Wait();

        _hub.Invoke("SendNotification","Hello").Wait();

and below IIS error log:

StatusCode: 503, ReasonPhrase: 'Service Unavailable', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Cache-Control: private
  Date: Tue, 13 Jan 2015 06:59:27 GMT
  Server: Microsoft-IIS/7.5
  X-Powered-By: ASP.NET
  Content-Length: 5229
  Content-Type: text/html; charset=utf-8
}
   at Microsoft.AspNet.SignalR.Client.Http.DefaultHttpClient.<>c__DisplayClass2.<Get>b__1(HttpResponseMessage responseMessage)
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.TaskRunners`2.<>c__DisplayClass3a.<RunTask>b__39(Task`1 t)

**Comment by DamianEdwards** [comment]
I'm afraid we'll need quite a bit more detail to look into this. Can you provide some information regarding the topology/design of the application and how it uses SignalR? Also, what server/client OS versions you're using?

**Comment by javaheri** [comment]
Thanks Damian for Answering.

Application that we designed is so easy,
When a new Product inserted in SQL Server Database, each Client send notification to other clients.
(Approximately 2000 Product record in day).

Note:After Recycle Problem Solve.But after a while error occur.

I don't know it is necessary to Stop connectionHub after Invoke method?

************************************************************************************
Client Application:
Net 4.5
Windows Application
Visual Studio 2012

Code that we use in after Save Product in database:

    using Microsoft.AspNet.SignalR.Client;

    public static class ProductInvok
    {
        public static void ProductAddedSendNotification()
        {
     IHubProxy _hub;
     var connectionHub = new HubConnection("http://192.168.1.5");
     _hub = connectionHub.CreateHubProxy("productHub");
     connectionHub.Start().Wait();

    _hub.Invoke("AddedProducts","NewProductAdded").Wait();}}
************************************************************************************
Server Application:
Net 4.5
Asp.net Web Application
Web Form
SQL Server 2012
IIS 7.5

Code that we use in Web Form when new product added in database:

    <script type="text/javascript">
        $(function () {
            var products= $.connection.productHub;
            products.client.addedProducts= function (newProduct) {
                    console.log("Added");
                    alert(newProduct + " Added");
            }
            $.connection.hub.start().done(function () {
                console.log('Hub: Connected.');
            });
        });
    </script>

************************************************************************************
And the Hub:

using Microsoft.AspNet.SignalR;
using Microsoft.AspNet.SignalR.Hubs;
using System.Web;

namespace CompanyProducts.Hubs
{
[HubName("productHub")]
    public class ProductHub : Hub
    {
        public void AddedProducts(string newProduct)
        {
            Clients.All.addedProducts(newProduct);
        }
    }
}

************************************************************************************

**Comment by DamianEdwards** [comment]
@javaheri Yes you need to call stop on the connection after you've finished with it. In this case, you create a new connection on each invocation so they just keep building up until the server runs out of request slots.

**Comment by Tonay** [comment]
Hey, @DamianEdwards ; what do you mean that you said "Yes you need to call stop on the connection after you've finished with it". I have an .exe application and it should be keep signalr connection alive for application lifetime. Approximately 200 client use that hub connection and listens some method (with _hubPoroxy.On). If a close the connection clients not working correctly. 

But somehow i give an error sometimes (peak times) as '503 Server Unavailable'. I applied to performance tunning (from https://github.com/SignalR/SignalR/wiki/Performance) on IIS but nothing change. What else should i do? Any Idea?
