### ISSUE TITLE
"NetworkError: 400 Bad Request

### ISSUE THREAD

**Issue by EMIN3M1986** [SignalR/SignalR#3386]
I have problem. 
When I Want to connect to Server ( Windows 2012 Server ) this error appear on firebug.
 #2671 
"NetworkError: 400 Bad Request - http://sepehri.dotnetco.com/signalr/connect?transport=webSockets&clientProtocol=1.5&connectionToken=Kqd%2BPRtv8SMD8IhlEEBeZZm%2FX5DHTlIzIz1Kr4qho%2B5W%2FSN6bZXg4KSzeZhyvalwJJinrm5kVge9CUlVZkI%2B51jQB6luxwSOnztpirH8ERiwDYq1kIyDWz8XiiEsftHO&connectionData=%5B%7B%22name%22%3A%22mobilehub%22%7D%5D&tid=7"

Reponse & HTML:

Reload the page to get source for: http://sepehri.dotnetco.com/signalr/connect?transport=webSockets&clientProtocol=1.5&connectionToken=Kqd%2BPRtv8SMD8IhlEEBeZZm%2FX5DHTlIzIz1Kr4qho%2B5W%2FSN6bZXg4KSzeZhyvalwJJinrm5kVge9CUlVZkI%2B51jQB6luxwSOnztpirH8ERiwDYq1kIyDWz8XiiEsftHO&connectionData=%5B%7B%22name%22%3A%22mobilehub%22%7D%5D&tid=7

You can try it yourself 
http://sepehri.dotnetco.com/websocket.aspx

**Comment by DamianEdwards** [comment]
It appears to be a problem with your web server's HTTPS configuration. The /signalr/hubs resource loads fine over HTTP, but a security error occurs when attempting to load over HTTPS, probably due to you using a self-signed SSL certificate or similar.

![capture](https://cloud.githubusercontent.com/assets/249088/5810465/be879fa2-9ffb-11e4-85ad-8ca4904c9e47.PNG)

**Comment by EMIN3M1986** [comment]
Hi.
I recently added my own certificate to the website.
there isn't any problem with HTTPS but HTTP has the problem yet.

I added two version on this page.
One of them has HTTPS  hub address  and the other one has HTTP.

HTTPS: http://sepehri.dotnetco.com/websocket.aspx
HTTP: http://sepehri.dotnetco.com/websocket_HTTP.aspx

**Comment by halter73** [comment]
Both URLs seem to be working.

**Comment by EMIN3M1986** [comment]
Please check it again.
Check it with inspector.

**Comment by halter73** [comment]
I've been looking at the JS console, and I see SignalR successfully establishing WebSocket  connections to both the HTTP and HTTPS URLs on my end.

It could be the network that you are connecting from that is introducing the problem you're observing. Often times proxies will interfere with WebSocket requests. Using HTTPS usually works around this issue.

**Comment by EMIN3M1986** [comment]
You know how I can resolve this problem ?

**Comment by EMIN3M1986** [comment]
I solve my previous problem.
Now I have another problem. I can connect with my cellphone to server in SSE transport type, but I still have problem with Websocket transport type. In java Log there is no any problem. but connection dose not establish.
Please check my code.

WebsocketTransport ss = new WebsocketTransport(new Logger() {
                    @Override
                    public void log(String arg0, LogLevel arg1) {
                        Log.d("@NewLogger", arg0);
                        Log.d("@NewLogger", arg1.toString());
                    }
                });

connection.start().done(new Action<Void>() {
                    @Override
                    public void run(Void aVoid) throws Exception {
                        System.out.println("Done Connecting!");
                        Log.d("@@Connection", connection.getState().toString());
                        Log.d("@@Connection", connection.getConnectionId());
                    }
                });
