### ISSUE TITLE
Json converter

### ISSUE THREAD

**Issue by osmgunes** [SignalR/SignalR#3389]
Hi guys I am tryng to get web services with jason in windows phone but ı take this expextion

Additional information: Unexpected character encountered while parsing value: <. Path '', line 0, position 0

her is my code  

  WebResponse response = request.EndGetResponse(result);
                    Dispatcher.BeginInvoke(() =>
                    {
                        StreamReader reader = new StreamReader(response.GetResponseStream());
                        string text =reader.ReadToEnd();
                        string Total = "";

                        var parsedResponse =  JsonConvert.DeserializeObject<MyBlogList>(text);//this line where ı got exception

                        int i = 1;
                        Total = Total + "Klasörler \n -----------------------------\n";
                        foreach (var item in parsedResponse)
           
   

                    });

**Comment by DamianEdwards** [comment]
Not a SignalR question.
