### ISSUE TITLE
Connections vs Users

### ISSUE THREAD

**Issue by imperugo** [SignalR/SignalR#3390]
Hi, 
if I understood correctly, having 3 different browser tabs/windows means 3 different ConnectionId so basically 3 different connections also if I'm logged with the same user (makes sense).

I'd like to send a push from server to all the clients except mine, with mine I mean all connected users where the username different from mine and vice versa.

something like
```csharp
Clients.OthersUsersInGroup(GroupName,Username).myEvent(myArg)
```

What's the best way to do that?

**Comment by DamianEdwards** [comment]
What you want isn't really possible with today's API. So thanks for the suggestion :smile:

I've tagged this as v3 so we can consider it for inclusion in a future version. FYI we'll move this bug to the new repo shortly where you can then track its status.
