### ISSUE TITLE
Getting a NullReferenceException in SignalProxy Invoker when no clients connected

### ISSUE THREAD

**Issue by ejsmith** [SignalR/SignalR#3391]
https://github.com/SignalR/SignalR/blob/release/src/Microsoft.AspNet.SignalR.Core/Hubs/SignalProxy.cs#L50

The Invoker is null there when there are no clients connected and when I am calling:

Clients.Group("somegroup").someMethod();

**Comment by niemyjski** [comment]
+1

**Comment by niemyjski** [comment]
Any updates on this?

**Comment by halter73** [comment]
What version of SignalR are you using? Do you have a full stack trace for the NullReferenceException?

If the `Invoker` is null inside of `SignalProxy`, that would imply that there is no `IHubPipelineInvoker` registered with `GlobalHost.DependencyResolver`.

If you call `GlobalHost.DependencyResolver.Resolve<IHubPipelineInvoker>()` in your app, do you get null?

**Comment by niemyjski** [comment]
We are using the latest stable version of SignalR ( 2.2.0.0 )

![image](https://cloud.githubusercontent.com/assets/1020579/6008207/5f422c3e-aae5-11e4-88f0-0abc4bcd75c1.png)

IHubPipelineInvoker is set to {Microsoft.AspNet.SignalR.Hubs.HubPipeline}

Here is the stack trace:

     at Microsoft.AspNet.SignalR.Hubs.SignalProxy.Invoke(String method, Object[] args)
     at Microsoft.AspNet.SignalR.Hubs.SignalProxy.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
     at CallSite.Target(Closure , CallSite , Object , EntityChanged )
     at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
     at Exceptionless.Api.Hubs.MessageBusHub.OnEntityChanged(EntityChanged entityChanged) in c:\Code\Exceptionless\Source\Api\Hubs\MessageBusHub.cs:line 70

The source can be found here: https://github.com/exceptionless/Exceptionless/blob/master/Source/Api/Hubs/MessageBusHub.cs To reproduce, all you need to do is pull down the source and run the api.iss project.

**Comment by Xiaohongt** [comment]
@niemyjski , I tried your source to repro ( there are 29 projects),  I run api.iis project, but I got below error:
 ```
[WebException: The operation has timed out]
   System.Net.HttpWebRequest.GetResponse() +6518932
   Elasticsearch.Net.Connection.HttpConnection.DoSynchronousRequest(HttpWebRequest request, Byte[] data, IRequestConfiguration requestSpecificConfig) in C:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection.cs:261

[Exception: ping returned no status code]
   Elasticsearch.Net.Connection.Transport.Elasticsearch.Net.Connection.ITransportDelegator.Ping(ITransportRequestState requestState) in C:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\Transport.cs:95

[PingException: Pinging http://localhost:9200/ caused an exception]
   Elasticsearch.Net.Connection.Transport.Elasticsearch.Net.Connection.ITransportDelegator.Ping(ITransportRequestState requestState) in C:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\Transport.cs:108
. . .
```
I already enabled port 9200 on my machine and also set request timeout to 3 mins, do you know what else need to do to not get the exception?

**Comment by niemyjski** [comment]
I'm sorry, I don't have a smaller repro sample :(.. You need to run the StartBackendServers.bat to start mongo and redis. But we don't yet have that script setup to start elasticsearch (which runs on 9200). So you'd need to download elastic search and run that too ( http://www.elasticsearch.org/download/ ).

**Comment by niemyjski** [comment]
Were you able to reproduce this issue?

**Comment by niemyjski** [comment]
If you need me to help you setup any of the dependencies please let me know.

**Comment by niemyjski** [comment]
I just got another exception:

		System.NullReferenceException: Object reference not set to an instance of an object.
		at Microsoft.AspNet.SignalR.Hubs.SignalProxy.TryInvokeMember(System.Dynamic.InvokeMemberBinder binder, System.Object[] args, System.Object& result) at offset 0
		at ..CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object, Exceptionless.Core.Messaging.Models.PlanChanged) at offset -1
		at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](System.Runtime.CompilerServices.CallSite site, System.Dynamic.T0 arg0, System.Dynamic.T1 arg1) at offset 267
		at Exceptionless.Core.Messaging.RedisMessageBus.OnMessage(StackExchange.Redis.RedisChannel channel, StackExchange.Redis.RedisValue value) at offset 158 in c:\TeamCity\buildAgent\work\412f37944420f4f9\Source\Core\Messaging\RedisMessageBus.cs:line 31:col 22

**Comment by niemyjski** [comment]
Were you able to reproduce this?

**Comment by niemyjski** [comment]
It's been a few weeks, has anyone else ran into this behavior?

**Comment by Xiaohongt** [comment]
@niemyjski , I was not able to repro the exception stack trace yet ( I may be able to guess the repro), could you simplify the repro app?

**Comment by niemyjski** [comment]
We simplified the latest repro lately, all that is required is elasticsearch and mongo. I'd be more than happy to show you this issue via a skype session.

**Comment by Xiaohongt** [comment]
@niemyjski , do you still see the exception happen? I can't repro the exception on HubContext.Clients.Group("somegroup").someMethod().

**Comment by niemyjski** [comment]
Yes, I see it every day in development. It's pretty dang annoying. I'd be more than happy to enter a lync session and show you it / setup a repo.

**Comment by Xiaohongt** [comment]
@niemyjski , ok, could you show me the repro?

**Comment by niemyjski** [comment]
Yes I could show you via meeting or you just need to launch our project,
then submit any request with an api key to
/api/v2/events?access_token="LhhP1C9gijpSKCslHHCvwdSIz298twx271n1l6xw" and
then watch the error occur.

Thanks
-Blake Niemyjski

**Comment by Xiaohongt** [comment]
@niemyjski , could you let me know what steps to run your projects? (there are 26 projects ), what others I need to install and run? seems now we need to download elastic search from https://www.elastic.co/downloads/elasticsearch.

**Comment by niemyjski** [comment]
1. You just need to install java and then and make sure JAVA_HOME path is set to your java install directory (I can't believe they don't do this by default).
2. Start Elasticsearch, and MongoDB by running StartBackendServers.bat. This will automatically download the latest versions and run them from a temp directory.
3. Start the solution and update the redis connection string value in the web.config to localhost. This will require that redis is running, if no connection string is defined then in memory implementations will be used... (redis scaleout will not be used if the connection string is not set).
4. Start running by pressing f5 and set breakpoints in the try catches under the MessageBusHub / break on all exceptions.
5. Make any post request to `http://localhost:50000/api/v2/events?access_token=LhhP1C9gijpSKCslHHCvwdSIz298twx271n1l6xw with a body of any content. Notice you get null reference exceptions as well as other exceptions with the signalr implementation when using redis.

**Comment by niemyjski** [comment]
If you already have mongo and elastic search installed locally you can skip step 2.

**Comment by niemyjski** [comment]
I've updated the prevent comment.

**Comment by niemyjski** [comment]
@Xiaohongt we just removed our mongo dependency.. All you need to have now is elasticsearch running (by running the batch file) and press f5.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
