### ISSUE TITLE
SignalR Backplane Redundancy

### ISSUE THREAD

**Issue by illudens** [SignalR/SignalR#3395]
SignalR could be used very effectively in mission critical enterprise application if it could be configured to include a backplane failure recovery strategy.  In one common case, having the ability to provide a primary and secondary Service Bus namespace for messaging fail over would serve this purpose.  We see any single Service Bus namespace go down for minutes to hours at a time every month.  Having the capability to specify two or more namespaces would make SignalR far more robust when these outages occur.

**Comment by pseabury** [comment]
This would be very useful in critical applications that need more than the Single ServiceBus SLA that Microsoft provides.

**Comment by groenlid** [comment]
bumb. Is there any plans for this in the future?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
