### ISSUE TITLE
Post data is null when using Nancy and transports other than WebSockets

### ISSUE THREAD

**Issue by pws83** [SignalR/SignalR#3402]
Hi all,

I am new to SignalR and have setup a Nancy server which SignalR is mapped to using the handy MapSignalR() (no fancy parameters) extension.

Now, on Windows 8, everything runs fine and I am able to invoke server methods on my hub. But, on computers with Windows 7, I get an exception when the serializer is trying to deserialize the form's data. This occurs in the HubRequestParser.Parse method:
```
public HubRequest Parse(string data, JsonSerializer serializer)
{
	var deserializedData = serializer.Parse<HubInvocation>(data);
    ...
```
The reason for the exception is that `data` is null.

If I inspect the POST using Fiddler, I can see that the form's body indeed does contain data. The request url looks like this:
```
/signalr/send?clientProtocol=1.4&transport=serverSentEvents&connectionData=[%7B%22Name%22:%22MessageCenterHub%22%7D]&connectionToken=AQAAANCMnd8BFdERjHoAwE%2FCl%2BsBAAAAI%2BYvFvrNokesRGhS3FR43gAAAAACAAAAAAADZgAAwAAAABAAAAA4IXX9eH8dJQmsuwUNjGHyAAAAAASAAACgAAAAEAAAAF47AFMJSCLg%2ByK3FUK4tQgoAAAAvE9saG1yLQk2sNFDrXo1f8u2DYXtnYQyepU4AkJMgWaBA4QiSwvvNxQAAABjxJSN5w4h4SUWsLnKADhVgm%2BjBg%3D%3D
```
While the body looks like this:
```
data=%7b%22I%22%3a%220%22%2c%22H%22%3a%22MessageCenterHub%22%2c%22M%22%3a%22RequestNotifications%22%2c%22A%22%3a%5b1%5d%7d
```
As stated above, this all works on Windows 8 since WebSockets is being used as transport. But, if I switch to SSE or LongPolling, the exception happens.

I have tried mapping a descendant to `HubDispatcher` as a persistent connection to the pipeline and then overriding its `OnReceived` method and inspecting the supplied data and this confirms the `data`parameter is indeed already null at this point.

Does anyone know what can possibly be the cause of this?
Has the request stream already been read by the time it is passed to SignalR?

Thank you in advance!

**Comment by moozzyk** [comment]
Looks similar to #3374. @pws83 - can you provide a repro?

**Comment by pws83** [comment]
Thanks for answering @moozzyk , I will try to produce a repro.

**Comment by pws83** [comment]
So, right after my previous post I think I solved the mystery. When mapping SignalR, Nancy and whatever Owin extensions you have, *order* seems to be important. In my view this is completely insane, especially since we're dealing with extension methods that return themselves.

This:
```
IAppBuilder builder;
builder
    .UseNancy()
    .MapSignalR();
```
...is not equivalent to this:
```
IAppBuilder builder;
builder
    .MapSignalR()
    .UseNancy();
```
While the latter works as intended, the former produces the error mentioned in my first post.

Maybe this can be a lesson for everyone thinking about employing the builder pattern with method chaining: Never--ever--let the invocation order matter! It is the responsibility of the builder to build whatever it is designed to build, not its returning-this-methods.
