### ISSUE TITLE
Fragmentation on the client side with the C# client

### ISSUE THREAD

**Issue by ayarov** [SignalR/SignalR#3403]
This issue is related to #1470 which was closed 2 years but appears that it is on once again.
I have a dump file that can be supplied as soon as needed for the further investigation.
Thanks in advance.
## Details:

We upgraded to 2.1.2 version few months ago and now are running stress tests before release.
Once in a while we do observe a memory leak.

The implementation we have is as follows:
1. ASP.NET website acting as communication server.
2. We have internal and external clients connected to it.
3. Internal clients are the data distributors (broadcasting manner)
4. The clients distributing the data are working within a LAN and interacting with the communication server via internal IP or even as localhost (in standalone deployments).
5. The message distribution frequency is done as chunks - every few minutes sending up to 1000 message for each connection while having up to 10 connections.

***Currently we do not have any throttling mechanism and my guess that it is a part of the problem but anyhow i wanted to get an advise from you regarding this memory leak.
Do you have any suggestions how to overcome this?
I have a dump file if necessary and here is a short print from the WinDbg (please look into 00007fff31341b40 4101 459312 System.Threading.OverlappedData).
Our windows service swell in to ~1.2GB while in normal behavior it should be around <= 500MB

0:000> !gchandles -stat
The version of SOS does not match the version of CLR you are debugging. Please
load the matching version of SOS for the version of CLR you are debugging.
CLR Version: 4.0.30319.34003
SOS Version: 4.0.30319.18052
Statistics:
MT Count TotalSize Class Name
00007fff319cc9f8 1 24 System.Threading.Tasks.ThreadPoolTaskScheduler
00007fff20a8bbf0 1 24 Bid+BindingCookie
00007fff31990330 1 48 System.SharedStatics
00007fff319914c0 1 64 System.Security.PermissionSet
00007fff313ab398 1 64 System.EventHandler`1[[Windows.Foundation.Diagnostics.TracingStatusChangedEventArgs, mscorlib]]
00007fff30a58410 1 64 Microsoft.Win32.NativeMethods+WndProc
00007fff30a58210 1 64 Microsoft.Win32.NativeMethods+ConHndlr
00007fff304d9da8 1 64 System.Runtime.Interop.UnsafeNativeMethods+EtwEnableCallback
00007fff30467af8 1 64 System.ServiceProcess.NativeMethods+ServiceControlCallbackEx
00007fff30467938 1 64 System.ServiceProcess.NativeMethods+ServiceMainCallback
00007fff20a8bb60 1 64 Bid+CtrlCB
00007fff31990220 3 72 System.Object
00007fff31a0d240 1 88 System.Runtime.Remoting.Identity
00007fff319a4db0 3 96 System.Threading.RegisteredWaitHandle
00007fff31a0d7a8 1 104 System.Runtime.Remoting.Contexts.Context
00007fff31a0be28 3 120 System.Threading._ThreadPoolWaitOrTimerCallback
00007fff20a951b0 2 128 SNINativeMethodWrapper+SqlAsyncCallbackDelegate
00007fff319a6728 3 144 System.Threading.AutoResetEvent
00007fff31a11aa8 1 160 System.Collections.Concurrent.CDSCollectionETWBCLProvider
00007fff319fd690 1 160 System.Threading.CdsSyncEtwBCLProvider
00007fff319cbe98 1 160 System.Threading.Tasks.TplEtwProvider
00007fff319b2ea0 1 160 System.Diagnostics.Tracing.FrameworkEventSource
00007fff31990148 1 160 System.ExecutionEngineException
00007fff319900d0 1 160 System.StackOverflowException
00007fff31990058 1 160 System.OutOfMemoryException
00007fff3198fe70 1 160 System.Exception
00007fff30a56020 4 160 System.Net.TimerThread+TimerQueue
00007ffed36f53c8 1 160 System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider
00007fff304d9ab0 3 168 System.Runtime.Diagnostics.DiagnosticTraceSource
00007fff30a9af58 1 200 System.Net.ServicePoint
00007fff319903f0 1 216 System.AppDomain
00007fff30a50978 4 224 System.Diagnostics.TraceSource
00007fff319b3230 5 320 Microsoft.Win32.UnsafeNativeMethods+ManifestEtw+EtwEnableCallback
00007fff319901c0 2 320 System.Threading.ThreadAbortException
00007fff30a56210 6 336 System.Net.Logging+NclTraceSource
00007fff30a46a60 5 400 System.Diagnostics.BooleanSwitch
00007fff20a97620 1 440 System.Data.SqlClient.TdsParserStateObject
00007fff30a56370 13 1040 System.Diagnostics.SourceSwitch
00007fff319bcc30 102 7344 System.Reflection.Emit.DynamicResolver
00007fff319911a8 285 27360 System.Threading.Thread
00007fff319ad9f8 249 39840 System.RuntimeType+RuntimeTypeCache
00007fff319902b8 278 360832 System.Object[]
00007fff31341b40 4101 459312 System.Threading.OverlappedData
Total 5096 objects

Handles:
Strong Handles: 429
Pinned Handles: 15
Async Pinned Handles: 4101
Ref Count Handles: 1
Weak Long Handles: 365
Weak Short Handles: 184
Dependent Handles: 1

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
