### ISSUE TITLE
SignalR Azure Internet explorer does not trigger OnDisconnected

### ISSUE THREAD

**Issue by qreftan** [SignalR/SignalR#3406]
I'm displaying user count by storing the clientid when a client connects.

It's all good when the project is not published to Azure, but when its published, IE11 doesn't want to trigger the ondisconnect event. Every other browser works, (Chrome, Firefox and Safari).
So everytime the user navigates around on the site the counter will always go up by one, even if it's the same user, (It's not removing the old client ID from the list).

After about 30 seconds, the onReconnect fires, removing the incorrect added user.
Unchecking "Always refresh from server" in F12, Network tab, seems to solve the problem.

After more testing:
Navigating on the same page, (spamming home button), and closing Internet explorer will call the ondisconnect event, but NOT when navigating around on the site, (not the same page) OR if you leave the site for another, (type in a new URL and leave the current page).

Why does "Always refresh from server" solve the problem?

How can it be fixed without unchecking "Always refresh from server"?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
