### ISSUE TITLE
Which license applies to SignalR and surrounding packages ?

### ISSUE THREAD

**Issue by tomap** [SignalR/SignalR#3409]
Hi,

In your source code, you are using Apache v2 license
https://github.com/SignalR/SignalR/blob/master/LICENSE.md

However, in nuget
https://www.nuget.org/packages/Microsoft.AspNet.SignalR/2.2.0
the license is pointing to 
http://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm

Could you clarify why there is a difference ? and which license applies ?

Thank you,

Thomas P.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
