### ISSUE TITLE
Azure Event Hub Backplane

### ISSUE THREAD

**Issue by RaleS** [SignalR/SignalR#3412]
Are there plans to introduce Azure Event Hub Backplane?

**Comment by MaDeRkAn** [comment]
Yes Event hub is cheaper than topics.

**Comment by srijan55** [comment]
+1

**Comment by hieronymusde** [comment]
+1

**Comment by elucidsoft** [comment]
+1

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
