### ISSUE TITLE
Cross Domain & Authentication

### ISSUE THREAD

**Issue by zuperboy90** [SignalR/SignalR#3415]
I am using SignalR on a Asp.net Web Api project.

I am connecting to the hubs from separate Asp.net MVC projects (Cross Domain)

Everything works fine until now.

However, i need to implement Authentication on the SignalR Hubs, in order to do this, i simply need a token to be send as QueryString parameter: (the Authentication is made using a third party service)

![signalr1](https://cloud.githubusercontent.com/assets/273061/6349068/22a1b780-bc2f-11e4-8c60-457c9ee52b4d.png)

This works.

The problem is that i store sensitive information (token) on the client (browser). If a hacker inspects the source code of the page, it can easily see the token key.

Is there any way to encrypt / decrypt the query string parameter so it will be encrypted on the client side?

I can easily encrypt it on the client, but the problem is that it will be sent encrypted to the Web Api server as well.

**Comment by BrannonKing** [comment]
You might look into the Hawk authentication scheme. They change things up once a minute to make it more secure. You can make HawkNet work with SignalR without too much trouble, assuming you are running on port 80.

**Comment by zuperboy90** [comment]
This might be a good idea, but i think i cannot change the authentication scheme right now, as i will break the applications.

One solution i think of would be to initialize the SignalR connection (obtain connection id / signalR token) from the Server Side, and then, on client side, simply connect to SignalR using the token / connection Id i just received from the server side call.

This way, i don't have to expose any security tokens on the client side.

Is this possible?

**Comment by zuperboy90** [comment]
Ok, I found a solution which works, and I'll post it just in case somebody will face the same problem:

Here is how it works:
- I modified the SignalR javascript file to allow me to specify a custom url for "/signalr/start" url
- Doing this, i will make SignalR to request /start to the MVC Application instead of the Web Api application
- I've implemented a custom IHttpModule in the MVC application which will capture the /signalr/start request
- in the HttpModule, i redirect the request to Web Api project but i also append the query string parameters i need

![signalr2](https://cloud.githubusercontent.com/assets/273061/6369641/e6fc3652-bcf0-11e4-9eeb-45df95cafded.png)

The HttpModule:

	public class SignalRModule : IHttpModule
	{
		public void Dispose()
		{
			
		}

		public void Init(HttpApplication context)
		{
			context.BeginRequest += new EventHandler(this.Application_BeginRequest);
		}

		private void Application_BeginRequest(Object source, EventArgs e)
		{
			HttpApplication application = (HttpApplication)source;
			HttpContext context = application.Context;

			var url = context.Request.RawUrl;

			if(url.Contains("/signalr/start"))
			{
				string token = context.Request.QueryString["token"];
				string sessionToken = EncryptionDecriptionService.Decrypt(token, ConfigurationManager.AppSettings["SessionToken.SaltKey"]);

				url = url.Substring(url.IndexOf("/signalr"));
				url = string.Format("{0}&sessionToken={1}", url, sessionToken);

				string webApiUrl = string.Format("{0}/{1}", WebApi.ApiURL, url);

				using (HttpClient client = new HttpClient())
				{
					HttpResponseMessage response = client.GetAsync(webApiUrl).Result;
					if (response.IsSuccessStatusCode == true)
					{
						string result = response.Content.ReadAsStringAsync().Result;

						context.Response.Clear();
						context.Response.Write(result);
						context.Response.End();
					}
				}
			}
		}
	}

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
