### ISSUE TITLE
Host in WorkerRole without any endpoint?

### ISSUE THREAD

**Issue by Plasma** [SignalR/SignalR#3416]
Hello,

I have SignalR working fine in an Azure web/worker role system. I don't need SignalR opening a http endpoint on the worker roles (they are just job processors, thus send messages back to clients via the backplane and clients never talk to them directly).

Is there a way to "startup" SignalR but bind no endpoints?

I currently do: WebApp.Start<SignalRStartup>(new StartOptions{}) but that does bind an endpoint on a default address and port.

Thanks

**Comment by BrannonKing** [comment]
I don't have a good answer for you, but as a clue, I start mine like this:

```csharp
			var services = (ServiceProvider)ServicesFactory.Create();
			services.AddInstance<IFileUploadDownloadManager>(uploadManager);
			services.AddInstance<IUserManager>(userManager);

			var starter = services.GetService<IHostingStarter>();
			var options = new StartOptions(interfaceAddress);
			options.AppStartup = typeof(ServerStartup).AssemblyQualifiedName;
			_server = starter.Start(options);
```

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
