### ISSUE TITLE
Add ability to send a message to a role

### ISSUE THREAD

**Issue by SirwanAfifi** [SignalR/SignalR#3418]
In SignalR we have [this](https://github.com/SignalR/SignalR/issues/2401) ability (sending message for a user)
What if we want to send a message to a role or roles? for example something like this:

```
Clients.Role("Administrator").send(message);
```

It would be better to have this ability.
In my case I send message for Administrator users this way:

```
public override Task OnConnected()
        {
            var userRole = "";
            userRole = Context.User.Identity.IsAuthenticated ? _userManager.GetRolesAsync(int.Parse(Context.User.Identity.GetUserId())).Result.FirstOrDefault() : "Users";
            Groups.Add(Context.ConnectionId, userRole);
            return base.OnConnected();
        }
```

Then I'll send message to specific role this way:

```
Clients.OthersInGroup("Administrator").send(message); 
```

**Comment by DamianEdwards** [comment]
Thanks for the suggestion. You could certainly do this today yourself my adding connections to groups named after the roles the user is in and then sending to those groups. You have to be careful how you expose groups however, such that you don't inadvertently let users construct group names themselves that might allow them to have messages sent to groups that represent roles (if you don't want to allow that). If we supported this as a first class feature we can prevent by way of our signal prefixes (essentially namespaces for known signal types to avoid clashes).

I've tagged this as a v3 candidate and as such it'll get moved to the new repo when we start looking at v3 features.

**Comment by sharathdev** [comment]
SirwanAfifi - I am searching for the sample on how to "send a message to a role" and i am not able to find a solution to this. Did you get the answer to the above solution? Can you please share the sample code.

Thanks

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
