### ISSUE TITLE
Multiple X-Content-Type-Options response headers for SignalR requests

### ISSUE THREAD

**Issue by mattbrooks2010** [SignalR/SignalR#3420]
# Functional impact

An HTTP response header of `X-Content-Type-Options: nosniff` is added to the response for all SignalR requests, even if one is already present.
# Minimal repro steps
1. Create a new empty ASP.NET web application from the Visual Studio 2013 project templates.
2. `Install-Package Microsoft.AspNet.SignalR.Sample`
3. Follow `readme.txt` instructions to enable SignalR sample.
4. Add the following to `web.config`:

``` xml
<system.webServer>
    <httpProtocol>
        <customHeaders>
            <clear/>
            <add name="X-Content-Type-Options"
                 value="nosniff" />
        </customHeaders>
    </httpProtocol>
</system.webServer>
```
# Expected result

Only a single HTTP response header of `X-Content-Type-Options: nosniff` for HTTP requests to SignalR endpoints.
# Actual result

Two HTTP response headers of `X-Content-Type-Options: nosniff` for HTTP requests to SignalR endpoints.
# Further technical details

[This source code](https://github.com/SignalR/SignalR/blob/3a219c101587333d562f04f30903d50ad9773e1c/src/Microsoft.AspNet.SignalR.Core/PersistentConnection.cs#L155) appears to be the only line where the response header is set.

Issue has been observed on Windows 8.1 and Windows Server 2012 both running IIS 8.5.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
