### ISSUE TITLE
await Groups.Add() throws A task was cancelled error.

### ISSUE THREAD

**Issue by danielloczi** [SignalR/SignalR#3423]
Hi,

The following code snippet sometimes throws 'A task was cancelled' error (when calling Groups.Add()):
```C#
protected override async System.Threading.Tasks.Task OnConnected(IRequest request, string connectionId)
        {
            try
            {
                await Connection.Send(connectionId, getLastMessage(request));
            }
            catch (Exception ex)
            {
                System.Diagnostics.Trace.TraceError(String.Format("An error has occured when tried to send back the last message. ConnectionID:{0} Error message: {1}", connectionId, ex.Message));
            }
            try
            {
                await Groups.Add(connectionId, getTopicName(request).ToLower());
            }
            catch (Exception ex)
            {
                System.Diagnostics.Trace.TraceError(String.Format("An error has occured when tried to add user to group. ConnectionID:{0} Error message: {1}", connectionId, ex.Message));
            }
        }
```

I work with SignalR v2.2, Persistent Connection in Azure Web role with multiple server instances. I don't use backplane, I have my own (one direction communication) infrastructure: each webrole instance creates a new subscription for itself for each topic inside a service bus namespace and creates a new route for signalr for each topic. I post messages only directly to the topic. SignalR clients don't send messages back. When a user connects, I put him to a group, where the group name equals with the topic name. When a message received from a topic I forward it to the signalr group which name equals the topic name. So it's a must have to put the user to the correct group during the OnConnected event.
```C#
foreach (var topic in Global.ServiceBusHandler.Topics)
            {
                try
                {
                    Global.ServiceBusHandler.SubscriptionClients[topic].OnMessageAsync(async m =>
                    {
                        try
                        {
                            SignalingMessage lastSignalingMessage = MessageStore.GetLastMessage(topic);                         
                            if (lastSignalingMessage.EnqueuedToTopicTimeUtc > m.EnqueuedTimeUtc && lastSignalingMessage.EnqueuedToTopicTimeUtc < DateTime.Now.ToUniversalTime())
                            {   //skipping this message, the last stored message is newer.
                                Trace.TraceWarning("Skipping received message, the last stored message is newer. Topic:{0} Received message ID: {1} Received message enqueued time: {2}", topic, m.MessageId, m.EnqueuedTimeUtc);
                                return;
                            }
                            else
                            {
                                string lastMessageBody = m.GetBody<string>();
                                var signalRConext = GlobalHost.ConnectionManager.GetConnectionContext<StatusPersistentConnection>();
                                string groupName = topic.ToLower();                             //generate group name from topic                                
                                await signalRConext.Groups.Send(groupName, lastMessageBody);    //signal to Clients                                
                                await Global.MessageStore.StoreLastMessageAsync(new SignalingMessage(topic) { Message = lastMessageBody, EnqueuedToTopicTimeUtc = m.EnqueuedTimeUtc }); //store message as last message
                            }
                        }
                        catch (Exception ex)
                        {
                            Trace.TraceError("Cannot process incoming message, an error has occured. Topic:{0} Received message ID: {1} Error message: {2}", topic, m.MessageId, ex.Message);
                        }
                    });
                }
                catch (Exception ex)
                {
                    Trace.TraceError("Error has occured, unable to register OnMessage event handler for topic:{0} Error message: {1}", topic, ex.Message);
                }
            }
```

 Based on my resarch this issue is an old issue and it was fixed in the latest realase, but I still facing it in SignalR v2.2. Could you advise me a solution?

Thanks a lot,
 Daniel

**Comment by danielloczi** [comment]
I was able to narrow down the problem, and it was turned out, that the root of the problem is an invalid connection state. If there is no backplane, but you have multiple nodes behind a cloudapp hostname, it can happen, that a client connection (onConnect() or onReconnect() events) occures one node, but the messages travel across another node (I mean the server side OnReceived() occures on a different node). In the example below the client is connected to the node called "SignalingWebRole_IN_0". The Send button has a simple functionality: the OnClick event sends a message to SignalR server, which broadcasts the message back to all of the clients. As you can see on the picture the client message was received and broadcasted by "SignalingWebRole_IN_1", however this client is connected to node 0. In case of a normal connection , the message should be received on the same node where the OnConnected() event has occured: SignalingWebRole_IN_0.
![image](https://cloud.githubusercontent.com/assets/11349934/6845829/e248c128-d3b8-11e4-8e84-bc06b0f1ffa7.png)

**Comment by danielloczi** [comment]
Configuring the load balancer from the default settings (5-tuple) to 2-tuple mode solves the problem. To do that, the loadBalancerDistribution tag inside the Endpoint section of the WorkerRole should be modified to "sourceIP". This parameter is located in the ServiceDefinition.csdef file. Example:
```xml
<WorkerRole name="worker-role-name" vmsize="worker-role-size" enableNativeCodeExecution="[true|false]">
  <Endpoints>
    <InputEndpoint name="input-endpoint-name" protocol="[http|https|tcp|udp]" port="port-number" loadBalancerDistribution="sourceIP" />
  </Endpoints>
</WorkerRole>
```
Check http://azure.microsoft.com/blog/2014/10/30/azure-load-balancer-new-distribution-mode/ for details. 

Thanks the help for Attila Ersek and Balint Farkas.

**Comment by niemyjski** [comment]
@danielloczi, were you able to solve this without enabling sticky sessions?

**Comment by danielloczi** [comment]
Telling the truth I was happy with the load balancer workaround, so stopped to find other solution.
