### ISSUE TITLE
Chunked encoding invalid in HTTP/2 (SPDY)

### ISSUE THREAD

**Issue by luiscantero** [SignalR/SignalR#3425]
- A server that supports HTTP/2 (SPDY), such as IIS 8.5 on Windows 10 can handle SPDY clients such as IE11, newer Chrome and Firefox.
- SignalR seems to send a chunked response for the JavaScript proxy client (/signalr/hubs) regardless of this being invalid according to the SPDY protocol spec.
- IE11 gets a chunked response and the header "Transfer-Encoding: chunked" and is able to interpret the proxy correctly.
- Firefox >= 35.0 (over HTTPS) gets a chunked response, but a browser component removes the mentioned encoding header because it is invalid. This leads to an invalid JavaScript file that begins with the hex-coded content length.
- Chrome (over HTTPS) sees the mentioned encoding header and throws the error "err_spdy_protocol_error".

**Comment by selaromdotnet** [comment]
I also hit this issue, server is Windows 10 Server Technical Preview build 9841. we worked around it temporarily by simply downloading the file from another browser and serving it directly, but would be curious to know if we can fix this permanently by adjusting either SignalR or our server settings... thanks

**Comment by luiscantero** [comment]
I expect this to be fixed when VS2015/.NET 4.6 is released on July 20th. SignalR 3 will become part of ASP.NET 5 and .NET 4.6 adds support for HTTP/2.

**Comment by luiscantero** [comment]
Small correction ASP.NET 5 should be released around the end of 2015. VS2015 will include ASP.NET 4.6.

**Comment by luiscantero** [comment]
This issue seems to be fixed now. I did a quick test using Chrome 46 and Firefox 36 and it works. Edge also works.
