### ISSUE TITLE
Unexpected character encountered while parsing value: %. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by hyperion1** [SignalR/SignalR#3428]

**Comment by hyperion1** [comment]
I receive 5-10 exception : Unexpected character encountered while parsing value: %. Path '', line 0, position 0 for a day on my production server. When I examine the logs I found the follow: 
all of them are for IE8, and happens for: /signalr/send', '/signalr/negotiate', '/signalr/start' or '/signalr/connect'. In all of them transport=serverSentEvents and clientProtocol=1.5.
I cannot understand why are there send, start and connect events for Internet Explorer as i know it isn't support server sent events?

My code is as follow:
public class SignalRHub : Hub
    {
        public void SendToClientLastUpdateDate(string customerID, string lastUpdateDate)
        {
            IHubContext context = GlobalHost.ConnectionManager.GetHubContext<SignalRHub>();
            context.Clients.Group(customerID).notifyNomUpdated(lastUpdateDate);
        }

        public async Task SetGroupForCustomer(string customerID)
        {
            await Groups.Add(Context.ConnectionId, customerID);
            Clients.Caller.getLastUpdateFromSession();
        }
    }

<script type="text/javascript">
                $(function () {                    
                    //$.connection.hub.logging = true;                    
                    var proxy = $.connection.signalRHub;

                    proxy.client.notifyNomUpdated = function (lastUpdateDate) {                        
                        showLastUpdateDate(lastUpdateDate);
                    };

                    proxy.client.getLastUpdateFromSession = function () {                        
                        PageMethods.GetSessionValue("UserNomUpdated", checkLastUpdateDate);                        
                    };

                    $.connection.hub.start().done(function () {                        
                        PageMethods.GetSessionValue("CustomerID", checkCustomerID);
                    });
                    
                    function checkCustomerID(customerID) {                       
                        if (customerID != "") {
                            proxy.server.setGroupForCustomer(customerID);
                        }
                    }

                    function checkLastUpdateDate(lastUpdateDate) {
                        if (lastUpdateDate != "") {
                            showLastUpdateDate(lastUpdateDate);
                        }
                    }

                    function showLastUpdateDate(lastUpdateDate) {
                        $('#<%= LoadingImage.ClientID %>').addClass("displayNone") 
                        $('#<%= ReadyImage.ClientID %>').removeClass("displayNone");
                        var msg = 'Last update date: ' + lastUpdateDate;
                        $('#<%= UpdateLabel.ClientID %>').text(msg);
                    }
                });

**Comment by hyperion1** [comment]
I noticed that in most of the cases SignalR works fine with IE8 with long pooling transport. In my logs I also have multiple records where browser is IE8 and transport is server send event with, but then status is 403 and then the exception does not throws. But in some cases I have IE8 (Mozilla/4.0+(compatible;+MSIE+8.0;+Windows+NT+5.1;+Trident/4.0)) with transport=transport=serverSentEvents  and status = 200 and in this cases hub throws Exception: Unexpected character encountered while parsing value: %. Path '', line 0, position 0.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
