### ISSUE TITLE
Suggestion to improve SignalR: Send return values from a client-side method to server

### ISSUE THREAD

**Issue by mansoor-omrani** [SignalR/SignalR#3429]
Hi

I supposed this "Issues" section in SignalR github is not intended to receive suggestions. So, I posted my suggestion to http://forums.asp.net/signalr. But I was told to send it in github.

This is its link:
http://forums.asp.net/t/2039427.aspx?Suggestion+to+improve+SignalR+Send+return+values+from+a+client+side+method+to+hub

I hope you find it useful.

Kindest Regards
M.O.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
