### ISSUE TITLE
new error utility function needed on hubs

### ISSUE THREAD

**Issue by mansoor-omrani** [SignalR/SignalR#3430]
When the server calls a non-existing method on client-side, client has no way to be notified of such a request. That would be helpful if there was a $.connection.hub.error by which we could assign a callback and be notified of any potential error happened for the hub. Calling non-existing methods on client-side is one of the various error that can happen for a hub.

The difficult thing is, the SignalR javascript client library uses jQuery custom events and triggerHandler() to call client-side invocations requested by the server. So, I guess there is no easy way to implement a so called $.connection.hub.error() method, unless the mechanism of calling client-side methods changes completely.

If it was me, I went for writing a custom eventing system instead of using jQuery custom events. This might ensue compatibility issues, however, the good point is we can allow server to call client-side methods whose names exactly match what is defined on client, instead of case-insensitivity in event-names when using jQuery custom events.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
