### ISSUE TITLE
Hanging requests?

### ISSUE THREAD

**Issue by SebastianStehle** [SignalR/SignalR#3431]
Hi,

we have some server issues and try to eliminate all potential problems. I checked the Worker-Processes view in the IIS management tool and opened the view with opened the faulting worker process and saw a lof of signalR connect entries:

http://srv03.green-parrot.net/api2/Test.png

Is this normal and if not, what can I do? We use signalR only for a single page. The user starts a new search and we push the results with signalR to the user. Then we keep the connection open for another search.

Edit: We are running on signalR 2.2 and the Client IP is the loadbalancer

**Comment by SebastianStehle** [comment]
There is not so much activity here, right? :(

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
