### ISSUE TITLE
Unique sessions in many tabs. Have some troubles.

### ISSUE THREAD

**Issue by artjomjuferov** [SignalR/SignalR#3433]
I followed this example http://stackoverflow.com/questions/19522103/signalr-sending-a-message-to-a-specific-user-using-iuseridprovider-new-2-0 and made simple chat. If two chats are opened in single browser one of the chat's web socket closses and then cant reconect. Can you help me?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
