### ISSUE TITLE
Bug: Calling client-side methods by server, gets to the client sooner than the server-side methods called by the same client

### ISSUE THREAD

**Issue by mansoor-omrani** [SignalR/SignalR#3434]
Abstract
In half-duplex transports, a separate call is made by client for sending messages to server. Now assume on server-side we call a client-side method. Do you think which gets to the client sooner? The client-call we make on server-side or the response of our first send call?

We might all say the former. Apparently that's what we expect. But, practice shows something else. If the receive connection is faster than the send connection, the receive will overtake the send call the client has made. A good example is SSE transport.

Example to recreate the bug:
The following tiny program shows the issue.

``` C#
// server-side code
public class ChatHub: Hub
{
    public void Send(string message)
    {
        var nick = Clients.Caller.nick;
        Clients.Caller.messageDate = DateTime.Now.ToString();
        Clients.All.showMessage(nick, message);
    }
}
```

``` JavaScript
// client-side code
$(function(){
    var connection = $.hubConnection();
    var proxy = connection.createHubProxy("chathub");
    proxy.on("showmessage", function (nick, msg) {
        msg = proxy.state.messageDate + " " + nick + ": " + msg;
        $("#content").append("<p>" + msg + "</p>");
    });
    $("#send").click(function () {
        var msg = $("#message").val();
        proxy.invoke("send", msg);
        $("#message").val("");
    });
    connection.start().done(function () {
        $("#content").append("<p>connected</p>");
        proxy.state.nick = "mansoor"; //prompt("Enter your nickname to chat");
        proxy.state.messageDate = "";
        $("#send").attr("disabled", false);
    });
});
```

``` HTML
<!-- HTML -->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Test Client</title>
    <style type="text/css">
        body, td, th, input
        {
            font-family: Tahoma;
            font-size: 12px;
        }
        #content {
            border: 1px solid black;
            overflow-y: auto;
            width: 300px;
            height: 150px;
            padding: 5px;
        }
        #content p { margin-top: 5px; }
    </style>
</head>
<body>
    <div id="content"></div>
    <input type="text" id="message" size="40" />
    <input type="button" id="send" value=" Send " />

    <script src="Scripts/jquery-1.6.4.min.js"></script>
    <script src="Scripts/jquery.signalR-2.2.0.js"></script>
    <script type="text/javascript">
        $(function () {
            // client-side code
            // ...
        });
    </script>
</body>
</html>
```

Description
In the above sample chat, I used a "nick" and "messageDate" property to exchange state data between the client and server. "nick" is used by client to pass the nickname of the user to the server and "messageDate" is used by server and the server writes in it the time it received a message by a client.

As it is seen, the server just reads the nickname of the client from Clients.Caller.nick, then writes DateTime.Now into Clients.Caller.messageDate and finally calls the client-side showMessage() on all clients using Clients.All.

To my amazement, I noticed that at times, my client receives the response of Clients.All.showMessage() sooner than the response of calling ChatHub.Send().

The first time, you try to send a message by the client to the server, you will see, no date-time is shown for your message in your chat window. But in the rest messages, everything works fine.

The reason the first message is shown without any date-time in the chat window is a consequence of the anomaly. The value of the "messageDate" is assumed to be sent back to the client together with the response of the first "Send" call the client has made, but when calling the client-side "showMessage()" methods gets to the client sooner, no "messageDate" is sent to the client. So, the client doesn't see any "messageDate" property on its proxy.state object.

You can put two break points at the following $.extend() lines (line number 2670, 2815) in "jquery.signalr.2.2.0.js" to see the issue. Try refreshing the browser and send a message. You will see that the second $.extend() in connection.receive() is hit first at times instead of the first $.extend() in invoke() method.

``` JavaScript
...
invoke: function (methodName) {
   ...
   // Update the hub state
   $.extend(that.state, result.State);
   ...
}
hubConnection.fn.init = function (url, options) {
   ...
   connection.received(function (minData) {
      ...
      // Update the hub state
        $.extend(proxy.state, data.State);
        $(proxy).triggerHandler(makeEventName(eventName), [data.Args]);
       ...
    });
    ...
};
```

How to Fix:
In my opinion the reason of the bug lies in the following constructor in HubConnectionContext.cs:

``` C#
public HubConnectionContext(IHubPipelineInvoker pipelineInvoker, IConnection connection, string hubName, string connectionId, StateChangeTracker tracker): base(connection, pipelineInvoker, hubName)
{
    _connectionId = connectionId;

    Caller = new StatefulSignalProxy(connection, pipelineInvoker, connectionId, PrefixHelper.HubConnectionIdPrefix, hubName, tracker);
    CallerState = new CallerStateProxy(tracker);
    All = AllExcept();
    Others = AllExcept(connectionId);
}
```

The "All" property is filled with the returned result of AllExcept(), but no tracker is given to AllExcept(). So, when a client-side method is called on "All", the ClientProxy() instance does not access to state variables used in Clients.Caller.

**Comment by mansoor-omrani** [comment]
I posted the same issue in http://forums.asp.net/1254.aspx/1?ASP+NET+SignalR.

As I'm new to github, I couldn't make use of the editor in here correctly to highlight the code I used in this post. Here's the address of the post I sent in forums.asp.net

http://forums.asp.net/t/2041529.aspx?Bug+Calling+client+side+methods+by+server+gets+to+the+client+sooner+than+the+server+side+methods+called+by+the+same+client

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
