### ISSUE TITLE
SignalR target a specific user from server with custom IUserIdProvider

### ISSUE THREAD

**Issue by jbuiss0n** [SignalR/SignalR#3435]
I've an application using SignalR & WebAPI. I've a custom Authorization context based on a token, which I give on each SignalR requests using the QueryString.

I've implement and IUserIdProvider, in order to retrieve my User from the Token.

And finally, I want to call a client method from the server, for a specific User (with is ID), I'm using a HubContext from the GlobalHost.ConnectionManager.

My problem is that my User is never find from my HubContext, but it is from the Hub itself...

Here is my IUserIdProvider implementation

```
public class SignalRUserIdProvider : IUserIdProvider
{
    public string GetUserId(IRequest request)
    {
        var token = request.QueryString["token"];
        var scope = GetUnprotectedScope(token);

        if (scope == null)
            return null;

        return scope.Id_User.ToString();
    }
 }
```

Here is my Hub imlementation

```
[HubName("notifier")]
public class NotifierHub : Hub
{
    public void Notify(string message)
    {
        Clients.User("1").Notify(message); //When call from a client, this works very well, only the     User with the Id = 1 receive the notification
    }
}
```

And finally, I use this to call the client method from my server:

```
GlobalHost
    .ConnectionManager
    .GetHubContext<NotifierHub>()
    .Clients
    .User("1")
    .Notify(notification.Message);
    // This does nothing...
```

I'm out of solution at this point, I don't understand what happens, does anyone have already achieve this ?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
