### ISSUE TITLE
SignalrR, Xamarin iOS, HttpClient, Windows Auth all one big pile of problems

### ISSUE THREAD

**Issue by PawOrmstrupMadsen** [SignalR/SignalR#3439]
Hi
I am developing a "large" app with many users, and we hit a rather huge problem in iOS using xamarin and signalr.
the problem is that xamarin iOS is not handling changes in network going from wifi to 3g/4g.
the **connection just freezes and signalr will fail at all reconnect tries**,
to fix that problem one has to change out the default Httphandler that used in the httpclient with a "native" httphandler for iOS, i have changed to use modernhttpclient but here there are missing NTLM auth logic, so that i also had to implement.
next problem is that SignalR is using HttpClient per default i have had to change out the default client and handler for signalr to my newly made custom modernHttpClient and nativehttphandler.

if you want to test it you can make a simple webapi server or signalr hub (fails on both)
request some data from the server from a xamarin ios app using the "standard" way in .NET
change network from wifi to 3G and request some new data, it will fail!

well long story short, i have fixed the problems but it would be nice if there was a warning using signalr and iOS together, or atleast fix the default httpclient on the xamarin build of signalr.

ill post the codes changes i made for ModernHttpClient if someone else need the entire package they can build it them self, or if you have suggestions to improve my code :)

i have not found a good way to avoid having to hardcode the Uri in the Credential :( but it works for what i am doing. suggestions are welcome :)

``` C#
public class NativeMessageHandler : HttpClientHandler 
    {
......
 public override void DidReceiveChallenge(NSUrlSession session, NSUrlAuthenticationChallenge challenge, Action<NSUrlSessionAuthChallengeDisposition, NSUrlCredential> completionHandler)
            {
                if (challenge.ProtectionSpace.AuthenticationMethod == NSUrlProtectionSpace.AuthenticationMethodNTLM)
                {

                    if (challenge.PreviousFailureCount > 0)
                    {
                        // Reject NTLM if it failed once, and try the other types of auth
                        completionHandler(NSUrlSessionAuthChallengeDisposition.RejectProtectionSpace, null);
                        return;

                    }
                    var temp = HubInfo.HubServer.ToLower();
                    var temp2 = HubInfo.ApiServer.ToLower();
                    var cred = This.Credentials.GetCredential(new Uri(temp.ToString()), "NTLM") ??
                           This.Credentials.GetCredential(new Uri(temp2.ToString()), "NTLM");

                    completionHandler(NSUrlSessionAuthChallengeDisposition.UseCredential, new NSUrlCredential(cred.Domain + "\\" + cred.UserName, cred.Password, NSUrlCredentialPersistence.ForSession));
                    return;
                }
            }
.....
}
```

Here are the custom HttpHandler code:

``` C#
public class AwesomeHttpHandler : NativeMessageHandler
    {

        private readonly IConnection _connection;

        public AwesomeHttpHandler(IConnection connection)
        {
            if (connection != null)
            {
                _connection = connection;
            }
            else
            {
                throw new ArgumentNullException("connection");
            }

            Credentials = _connection.Credentials;

            if (this.SupportsPreAuthenticate())
            {
                PreAuthenticate = true;
            }

            if (_connection.CookieContainer != null)
            {
                CookieContainer = _connection.CookieContainer;
            }

        }

    }
```

and here are the "custom" httpclient

``` C#
   public class AwesomeHttpClient : IHttpClient
    {
        private HttpClient _longRunningClient;
        private HttpClient _shortRunningClient;

        private IConnection _connection;

        /// <summary>
        /// Initialize the Http Clients
        /// </summary>
        /// <param name="connection">Connection</param>
        [SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Justification = "Handler cannot be disposed before response is disposed")]
        public void Initialize(IConnection connection)
        {
            _connection = connection;

            _longRunningClient = new HttpClient(CreateHandler());

            // Disabling the Http Client timeout 
            _longRunningClient.Timeout = TimeSpan.FromMilliseconds(-1.0);

            _shortRunningClient = new HttpClient(CreateHandler());
            _shortRunningClient.Timeout = TimeSpan.FromMilliseconds(-1.0);
        }

        protected virtual HttpMessageHandler CreateHandler()
        {
            return new AwesomeHttpHandler(_connection);
        }

   ......
    }
```

Starting a connection now looks like this

``` C#
 await _connection.Start(new ServerSentEventsTransport(new AwesomeHttpClient()));
```

**Comment by peterno** [comment]
Thank you for your code examples, they led me into the solution I am using, to have ModernHttpClient and SignalR working together and getting the benefits you proposed related to the connection reconnecting when switching from wifi to 3g/4g.

My solution was just to subclass the DefaultHttpClient from SignalR and using that instance as input to the Start method.

```C#
public class ModernHttpClientSignalR : DefaultHttpClient
{
        protected override HttpMessageHandler CreateHandler()
        {
            return new NativeMessageHandler();
        }
}

await _connection.Start(new ModernHttpClientSignalR());
```
This works nicely on iOS.
On Android the ModernHttpClient does not like it when signalR is posting data without any ContentType and I had to fix line 83 in OkHttpNetworkHandler.cs.

From: 
```C#
var contentType = String.Join (" ", request.Content.Headers.GetValues ("Content-Type"));
```
To:
```C#
var contentType = string.Empty;
if (request.Content.Headers.ContentType != null)
{
    contentType = String.Join(" ", request.Content.Headers.GetValues("Content-Type"));
}
```
I will post the fix on the ModernHttpClient also.

**Comment by peterno** [comment]
The latest release of ModernHttpClient, 2.4.0, now has the above fix, see https://github.com/paulcbetts/ModernHttpClient/pull/141.

**Comment by blocke79** [comment]
Hi peterno,

I've tried to use ModenHTTPClient with SignalR by using your ModernHttpClientSignalR class.
However I'm getting 401 errors when it is connecting

    Exception: Microsoft.AspNet.SignalR.Client.HttpClientException: StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: ModernHttpClient.ProgressStreamContent, Headers:
    {
    Cache-Control: no-cache
    Date: Sun, 27 Dec 2015 14:16:00 GMT
    OkHttp-Received-Millis: 1451225762021
    OkHttp-Selected-Protocol: http/1.1
    OkHttp-Sent-Millis: 1451225761345
    Pragma: no-cache
    Server: Microsoft-IIS/8.0
    Set-Cookie: ARRAffinity=af50ac2a8e968040adc554bc078e3d6ca4b4306e07ace891b86b7496b3604f22;Path=/;Domain=changrs.azurewebsites.net
    WWW-Authenticate: Bearer
    X-Content-Type-Options: nosniff
    X-Powered-By: ASP.NET
    Content-Length: 0
    Expires: -1
    OkHttp-Received-Millis: 1451225762021
    OkHttp-Selected-Protocol: http/1.1
    OkHttp-Sent-Millis: 1451225761345
    Set-Cookie: ARRAffinity=af50ac2a8e968040adc554bc078e3d6ca4b4306e07ace891b86b7496b3604f22;Path=/;Domain=changrs.azurewebsites.net
    X-Content-Type-Options: nosniff
    X-Powered-By: ASP.NET
    }
      at Microsoft.AspNet.SignalR.Client.Http.DefaultHttpClient+<>c__DisplayClass2.<Get>b__1 (System.Net.Http.HttpResponseMessage responseMessage) [0x0001c] in <filename unknown>:0 
      at Microsoft.AspNet.SignalR.TaskAsyncHelper+<>c__DisplayClass19`2[T,TResult].<Then>b__17 (System.Threading.Tasks.Task`1 t) [0x0000c] in <filename unknown>:0 
      at Microsoft.AspNet.SignalR.TaskAsyncHelper+TaskRunners`2+<>c__DisplayClass42[T,TResult].<RunTask>b__41 (System.Threading.Tasks.Task`1 t) [0x00038] in <filename unknown>:0 
    --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:201 
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:170 
      at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:142 
      at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:124 
      at WotTha.SignalR.SignalRClient+<Connect>d__2f.MoveNext () [0x00035] in c:\Users\bradl_000\Documents\blocke79\WotTha\WotTha\SignalR\SignalRClient.cs:279

**Comment by Skywanker** [comment]
Update:

Xamarin now (beta channel as of now) have the option to natively use NSUrlSessionHandler instead of HttpClient

This is what i think i need to do to make SignalR use the new implementation with credentials (im using NTLM)


    public class HttpClientSignalR : DefaultHttpClient
    {
        private readonly ICredentials _credentials;

        public HttpClientSignalR(ICredentials credentials)
        {
            _credentials = credentials;
        }

        protected override HttpMessageHandler CreateHandler()
        {
            return new NSUrlSessionHandler()
            {
                Credentials = _credentials
            };
        }
    }


And to set up the connection i do this:
` 
await _connection.Start(new HttpClientSignalR(_connection.Credentials));
`

That way i get the best performance and the cleanest code.

now i dont have the problem of ModernHttpClient and Windows Auth.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
