### ISSUE TITLE
StringEnumConverter registered with GlobalHost's dependeny resolver ignored when using IHubContext to send events

### ISSUE THREAD

**Issue by cklam2** [SignalR/SignalR#3440]
In my SignalR project I registered the StringEnumConverter so that the server send the string representation of an enum instead of the numeric value:

```
JsonSerializer serializer = new JsonSerializer();
serializer.Converters.Add(new StringEnumConverter { AllowIntegerValues = true });
GlobalHost.DependencyResolver.Register(typeof(JsonSerializer), () => serializer);
```

This works fine when calling client methods directly from our Hub. 

However when calling those client methods [outside the Hub](http://www.asp.net/signalr/overview/guide-to-the-api/hubs-api-guide-server#callfromoutsidehub) then the converter seems to be ignored, ie enum values are not converted to string. 

```
IHubContext _context = GlobalHost.ConnectionManager.GetHubContext<MyHub>();
...
_context.Clients.Client(clientConnId).OnEvent(MyEnums.TestValue2); // Sends out "1" iso "TestValue2"
```

I know that I can mark all my enum values with a JsonConverterAttribute but I hoped that it would be sufficient to register it once and will work globally. Any solution available this?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
