### ISSUE TITLE
Silverlight SignalR 2.2.0 Client Long Polling Issue

### ISSUE THREAD

**Issue by MDL-ACarlson** [SignalR/SignalR#3442]
Hello!

During the last week or so I've started having some problems with some of our clients chain spamming /signalr/poll and we've pinned it down to clients that are using long polling for transport.  It seems as if the client receives some 404 errors due to a local site connectivity problem, and then the SignalR client goes into an infinite loop during the reconnect cycle.  We can't tell that the SignalR client is in a defective state because it seems to think it is okay.  It no longer reports any exceptions or receives server calls once it reconnects.  After that it seems to call /poll between 10-20 times a second, and we only know this because of NewRelic monitoring on our server.

Here is the end of the exception dump we get before the client goes into the infinite poll loop.

First this exception 6 to 18 times...
"HubError\r\nStatusCode: 404, ReasonPhrase: 'Not Found', Version: 0.0, Content: System.Net.Http.StreamContent, Headers:
{
  Content-Length: 0
}
   at Microsoft.AspNet.SignalR.Client.Http.DefaultHttpClient.<>c__DisplayClass6.<Post>b__5(HttpResponseMessage responseMessage)
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.<>c__DisplayClass19`2.<Then>b__17(Task`1 t)
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.TaskRunners`2.<>c__DisplayClass42.<RunTask>b__41(Task`1 t)
System.Collections.ListDictionaryInternal", 

Followed by this fellow who always appears last.
        "HubError
Couldn't reconnect within the configured timeout of 00:00:30, disconnecting.
System.Collections.ListDictionaryInternal"

As best as we can tell, after that exception we dispose of the old hub connection, and use a new HubConnection and HubProxy.  This new connection seems to be the one that succeeds, and then spams.  I wish I knew more, but we cannot reproduce this error on command.  Sometimes we go days without seeing it at any of our clients.

It feels like this bug is similar to #2125, but that was resolved several versions ago.

We're trying to figure out how to collect more logging data so we can get a better picture of the sequence of events given that the HubError handler isn't being called.

We would appreciate any guidance you could offer us in finding the root of this problem.

**Comment by moozzyk** [comment]
@MDL-ACarlson  can you turn on full logging on the client and attach the logs if this condition happens?

**Comment by MDL-ACarlson** [comment]
I am going to try.  I hope to have some more data from both the client and NewRelic today.  The server is returning 400 to the /signalr/poll call with the following error;

MODULE_SET_RESPONSE_ERROR_STATUS
Warning ModuleName="__DynamicModule_Microsoft.Owin.Host.SystemWeb.OwinHttpModule, Microsoft.Owin.Host.SystemWeb, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35_cf9d1b92-3d48-4355-a185-623341fcbaa3", Notification="AUTHORIZE_REQUEST", HttpStatus="400", HttpReason="Bad Request", HttpSubStatus="0", ErrorCode="The operation completed successfully. (0x0)", ConfigExceptionInfo=""

**Comment by MDL-ACarlson** [comment]
'
            _HubConnection = new HubConnection(_Uri)
            {
                TraceLevel = TraceLevels.All, 
                TraceWriter = Console.Out
            };

            _HubConnection.Headers.Add("X-SESSION-ID", FsStatus.SessionId.ToString());
            _HubConnection.Headers.Add("X-USER-ID", FsStatus.UserOid);

            _HubConnection.Closed += () => HubClose();
            _HubConnection.ConnectionSlow += () => HubConnectionSlow();
            _HubConnection.Error += (error) => HubError(error);
            _HubConnection.Received += (payload) => HubReceived(payload);
            _HubConnection.Reconnected += () => HubReconnected();
            _HubConnection.Reconnecting += () => HubReconnecting();
            _HubConnection.StateChanged += (change) => HubStateChanged(change);
            _HubConnection.TransportConnectTimeout = TimeSpan.FromSeconds(60);

            _HubProxy = _HubConnection.CreateHubProxy("flatScreenHub");
            //_HubProxy.On<string>("addNewMessageToPage", (data) => System.Diagnostics.Debug.WriteLine("From SL Client, forwarded by Server: " + data));
            _HubProxy.On<string>("FsRowItemChanged", (data) => ProcessFsRowItem(data));
            //_HubProxy.On<string>("onScreenConfig", (data) => ProcessScreenConfig(data));
            _HubProxy.On<string>("Reboot", (data) => ProcessReboot(data));
            _HubProxy.On<string>("RequestStatus", (data) => ProcessStatusRequest(data));
            //_HubProxy.On<string>("heartbeatAsyncResult", (data) => HeartbeatAsyncResult(data));
            //_HubProxy.On<string>("subscribeAsyncResult", (data) => SubscribeAsyncResult(data));
            _HubProxy.On<string>("BackfillAsyncResult", (data) => BackfillAsyncResult(data));

            try
            {
                _HubConnection.Start();
                //Send();
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine("SignalRClient.MessageToServer() failed...");
                System.Diagnostics.Debug.WriteLine(ex.Message);
                System.Diagnostics.Debug.WriteLine(ex.StackTrace);
                //ConfigureReconnectTimer();
            }
'

**Comment by moozzyk** [comment]
You should `await` starting the connection otherwise you want see exceptions most of the exceptions since except for simple argument validation it won't throw but will return a faulted task. Since you are not `awaiting` you are not observing this exception. Same with `Send()`.  Do you do anything special in the `HubStateChanged` callback?

**Comment by MDL-ACarlson** [comment]
Once I add await to the Start(), we do capture an exception.

System.NotSupportedException occurred
  Message=""
  StackTrace:
       at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
       at Microsoft.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
       at Microsoft.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at FlatScreen.Silverlight.NetCode.SignalRClient.<ConnectAsync>d__26.MoveNext()
  InnerException: System.NotSupportedException
       Message=Specified method is not supported.
       StackTrace:
            at System.Net.Browser.BrowserHttpWebRequest.InternalEndGetResponse(IAsyncResult asyncResult)
            at System.Net.Browser.BrowserHttpWebRequest.<>c__DisplayClassa.<EndGetResponse>b__9(Object sendState)
            at System.Net.Browser.AsyncHelper.<>c__DisplayClass4.<BeginOnUI>b__0(Object sendState)
       InnerException:

**Comment by MDL-ACarlson** [comment]
I have added the await call, and added a way to catch any exceptions from the Start() call to be submitted via a parallel REST service.  We haven't had any clients go into the death loop today, but we're keeping an eye on it.

**Comment by dstrickland-mdl** [comment]
Here are a data points to add to this.

At 2:57 in the system event log of the webserver, I see this:

A worker process with process id of '4036' serving application pool 'flatscreen-signalr.mydealerlot.com' has requested a recycle because the worker process reached its allowed processing time limit.

Immediately after that, the system entered a crash state.   We didn't notice it as almost all of the monitoring is new and we will getting our feet wet.

We restarted a few flatscreen clients, but no change 100%.

I then stopped the web, stopped the app pool, started the web, started the app pool.

Instantly every thing came back online.  

Thoughts?

![image](https://cloud.githubusercontent.com/assets/3538674/6993038/cd7b6c0c-dab4-11e4-88a8-7543297afffd.png)

**Comment by dstrickland-mdl** [comment]
I changed the recycle from every 20 minutes to 6am.  The app pool recycled, but the signalr service was in an error state until :
1.  iisreset /stop
2. delete c:/windows/microsoft.net/framework64/v4.0.30319/Temporary ASP.net Files
3. iisreset /start

I thought this might be related to not having a machinekey (another github issue), but that would also hold true for iisreset, not just boucing the web and app pool

![image](https://cloud.githubusercontent.com/assets/3538674/7004113/2a0bb3a2-dc34-11e4-8f12-f3989063ac9a.png)

**Comment by dstrickland-mdl** [comment]
Should be abandon the IIS hosting jus host the service and would that potentially make this 100% condition go away?

**Comment by moozzyk** [comment]
@dstrickland-mdl - I don't know. I would start from figuring out what is happening to the server that it crashes.

**Comment by dstrickland-mdl** [comment]
@moozzyk - I might have figured out the issue with the startup.  The app hosts a nservicebus which also has a logging.  The restart never closes the logging file long enough for the new app to use the same logging file.  The restart seems related to this.  The total shutdown seems to force then entire process down and therefore there is no conflict.  Does this seem to make sense?

**Comment by moozzyk** [comment]
Possibly. If the app pool starts recycling but never finishes then I suppose it is in a state which does not allow handling requests so requests are rejected.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
