### ISSUE TITLE
SignalR negotiation throws CryptographicException

### ISSUE THREAD

**Issue by vilchinsky** [SignalR/SignalR#3444]
I have following configured in Startup class.

var hubConfig = new HubConfiguration()
{
    EnableDetailedErrors = true,
    EnableJavaScriptProxies = true
};

app.Map("/realtime", subApp =>
{
    subApp.UseCors(CorsOptions.AllowAll);
    subApp.RunSignalR(hubConfig);
});

When during negotiation the request to ~/realtime/negotiate?clientProtocol=1.5&connectionData=%5B%5D&_=1427902988240 fails with 500 Internal Server error with the following info:

Exception Details: System.Security.Cryptography.CryptographicException: Error occurred during a cryptographic operation.

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:

[CryptographicException: Error occurred during a cryptographic operation.] System.Web.Security.Cryptography.HomogenizingCryptoServiceWrapper.HomogenizeErrors(Func2 func, Byte[] input) +246 Microsoft.Owin.Security.DataProtection.CallDataProtection.Protect(Byte[] userData) +15 Microsoft.AspNet.SignalR.Infrastructure.DataProtectionProviderProtectedData.Protect(String data, String purpose) +229 Microsoft.AspNet.SignalR.PersistentConnection.ProcessNegotiationRequest(HostContext context) +524 Microsoft.AspNet.SignalR.PersistentConnection.ProcessRequest(HostContext context) +123 Microsoft.AspNet.SignalR.Hubs.HubDispatcher.ProcessRequest(HostContext context) +502 Microsoft.AspNet.SignalR.PersistentConnection.ProcessRequest(IDictionary`2 environment) +328 Microsoft.Owin.Mapping.d__0.MoveNext() +594 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84 Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.d__5.MoveNext() +291 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84 Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.d__2.MoveNext() +293 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32 Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.EndFinalWork(IAsyncResult ar) +208 System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +443 System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +288

**Comment by ismcagdas** [comment]
Hi @dmarcautsan , how did you solve this issue ?
I have a similar problem and couldn't find a clear answer yet.

**Comment by dmarcautsan** [comment]
@ismcagdas If I'm not mistaken the issue was the same described here http://stackoverflow.com/questions/25857577/error-occurred-during-a-cryptographic-operation-when-decrypting-forms-cookie

**Comment by ismcagdas** [comment]
Thanks for your help.
In my case I'm hostin the application on azure and adding machinekey didn't work for me.
However this commment helped me https://github.com/SignalR/SignalR/issues/3670#issuecomment-204041898.

I know this is not secure but works for now.
Thanks again for your help.
