### ISSUE TITLE
IE 10 foreverFrame rendering bug in compatibility mode

### ISSUE THREAD

**Issue by roytoo** [SignalR/SignalR#3445]
IE 10 experiences severe layout issues using foreverFrame mode when
running in compatibility mode initiated by the header:
X-UA-Compatible: IE=EmulateIE9

It occurs because the frame.setAttribute("style", ...) call fails to
update the attributes as desired.

See attached image for representative example.

![signalr_foreverframe_nothidden](https://cloud.githubusercontent.com/assets/405462/6987265/10f6b2f2-da0b-11e4-8b72-e552443379e2.png)

[Yes, I'm aware that forcing compatibility mode via the header is an ugly hack.  But it being used on a large, "mature" web application as it is updated to use modern standards that do not require the hack.
:-) ]

**Comment by roytoo** [comment]
I completely forgot to mention that I have a candidate fix checked in under my fork.
It is located at:
https://github.com/roytoo/SignalR/commit/5deeb46bd72f3112d9cba50c2c6b538ace1f3921

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
