### ISSUE TITLE
Don't use redis backplane for client on the same server as the originating message

### ISSUE THREAD

**Issue by stephenweaver** [SignalR/SignalR#3447]
I'm writing a web api that lives in Azure and uses SignalR.

The current problem I'm having is when trying to scale it out to several azure servers scattered around the world. I set SignalR to use redis as it's backplane but the latency is not acceptable for clients connected to the same server.

Is there a configuration for SignalR to send the message to all clients on the server before sending it out on the backplane to other servers?

**This is how it works:**

![howitworks](https://cloud.githubusercontent.com/assets/5230027/7024800/4898059e-dd0d-11e4-8e04-d5fcabccc438.png)

**This is how I would like it to work:**

![howitshouldwork](https://cloud.githubusercontent.com/assets/5230027/7024803/510ca52c-dd0d-11e4-92a2-d9f89d07d515.png)

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
