### ISSUE TITLE
Not receiving the return object from server to Java Client 

### ISSUE THREAD

**Issue by Kujtimii** [SignalR/SignalR#3448]
I am trying to get a set of data from the server by calling a method that returns a return object with an array of the data, when the array contains 3 or 5 or some random number (it is not always the same ) of elements I receive the object and when I add more elements sometimes some of the elements get returned bot some not ,sometimes  the object does not return at all I think the problem is with the java client but I can not find the solution ? 
Link for more details.
http://stackoverflow.com/questions/29520892/i-have-problems-getting-return-object-from-server-to-java-client-with-signalr

I have tried the same thing with the StockTicker example and when i try to get more than 15 stocks it does not send me all the stocks for example. if i try to get 16 stocks i receive 8,if i try to get 17 i receive 9 and if i try to get 18 i do not receive the object at all.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
