### ISSUE TITLE
Post-call event for hubs

### ISSUE THREAD

**Issue by epicvrvs** [SignalR/SignalR#3451]
Hello,

Is there currently any way to trigger an event after a public SignalR Hub method has been executed? I was considering abusing a mechanism like that to fix up this poorly written web service that is leaking SQL connections all over the place, across ~200 hub methods in 20-30 different hubs. The event would then enable me to dispose all SQL connections that were created by the thread. There's a ThreadStatic EF context that keeps a reference to the SqlConnection once the request has been performed (which is another terrible hack to deal with other issues caused by the mismanagement of resources).

Rewriting the thing to manage the resources properly is far too time-consuming and risky. Manually triggering some kind of clean-up in each hub call would be clumsy and also unreliable because people would just keep on adding more methods that do not use the same mechanism then. I also thought of introducing timers that cause the references to the SqlConnections to expire after some inactivity.

There are events like that for ASP.NET controller actions, but I have been unable to find anything like that so far. To make things worse, this thing uses a rather old version of SignalR (v1.1.3) and people are terrified of upgrading it because of absurd .NET 3.5/4.0 restrictions in some components that rely on the same binaries.

Does SignalR currently offer some kind of pre-call/post-call event?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
