### ISSUE TITLE
SignalR + Xamarin, Start takes 2-4 seconds to complete

### ISSUE THREAD

**Issue by fps7806** [SignalR/SignalR#3452]
Hey, I am trying to speed up the initialization of my app and it seems that SignalR is a big part of the loading time on my case. I can see that it is using Server Send  transport. Is 2-4 seconds to complete a connection normal? I am also trying Application Insights to help me debug everything and the top 3 requests are SignalR related:

I ran a test to check why it takes so long and while the first connection takes around 2-4 seconds any subsequent Start call will take 400-800ms. So for now I make call to .Start when the app starts just to get that out of the way. Then after I'm ready for the actual connection it only take 400-800ms depending on the device.

![signalr_time](https://cloud.githubusercontent.com/assets/7218057/7103787/7d9a9e42-e086-11e4-9446-b25034376ca7.PNG)

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
