### ISSUE TITLE
SignalR (2.2.0.0) LongPolling with Windows Client, reporting erroneous ConnectionState

### ISSUE THREAD

**Issue by LastTribunal** [SignalR/SignalR#3453]
I have no issue connecting my Windows client to a IIS Signalr hub, using LongPolling.
When I shutdown the hub, the windows client ConnectionState shows Disconnected and then tries to reconnect, as it should. This is where things get strange: Although I have not turned the hub back on, the ConnectionState turns to Connected within a few seconds of Reconnecting

At this point, the client no longer handles ConnectionState change events .

**Comment by moozzyk** [comment]
Can you provide a repro for this?

**Comment by LastTribunal** [comment]
My hub is running on IIS.  I shutdown IIS..  To replicate, just start a .net client session and monitor the state:
 connection.StateChanged +=
        (change) => Debug.WriteLine("[StateChanged] {0} {1}", change.OldState, change.NewState);

**Comment by moozzyk** [comment]
Can you attach logs from the client?

**Comment by LastTribunal** [comment]
17:47:29.6202658 - null - ChangeState(Disconnected, Connecting)
17:47:34.1667204 - 825eb451-e56e-4177-b0ab-3a5902227556 - LP Connect: http://myhub/hub/signalr/signalr/connect?clientProtocol=1.4&transport=longPolling&connectionData=[{"Name":"MainHub"}]&connectionToken=lhwcdJTXWXzHSDwi4D2nMkvankzRwYI7eMlKO617w6B37cAtY3hYr5y166q%2BusreGj4o8A%2FoDF5W4zZ8B04zHhNE3iGf28hlvv4MznWPHVGq%2BxFxO1ZnNg70Hvbf4SxQ
17:47:34.3127350 - 825eb451-e56e-4177-b0ab-3a5902227556 - LP: OnMessage({"C":"d-F8F24DE7-B,0|C,0|D,1","S":1,"M":[]})
17:47:34.3317369 - 825eb451-e56e-4177-b0ab-3a5902227556 - LP Poll: http://myhub/hub/signalr/signalr/poll?clientProtocol=1.4&transport=longPolling&connectionData=[{"Name":"MainHub"}]&connectionToken=lhwcdJTXWXzHSDwi4D2nMkvankzRwYI7eMlKO617w6B37cAtY3hYr5y166q%2BusreGj4o8A%2FoDF5W4zZ8B04zHhNE3iGf28hlvv4MznWPHVGq%2BxFxO1ZnNg70Hvbf4SxQ&messageId=d-F8F24DE7-B%2C0%7CC%2C0%7CD%2C1
17:47:34.4477485 - 825eb451-e56e-4177-b0ab-3a5902227556 - ChangeState(Connecting, Connected)
17:47:49.4012437 - 825eb451-e56e-4177-b0ab-3a5902227556 - LP: OnMessage()
17:47:49.4012437 - 825eb451-e56e-4177-b0ab-3a5902227556 - LP Poll: http://myhub/hub/signalr/signalr/poll?clientProtocol=1.4&transport=longPolling&connectionData=[{"Name":"MainHub"}]&connectionToken=lhwcdJTXWXzHSDwi4D2nMkvankzRwYI7eMlKO617w6B37cAtY3hYr5y166q%2BusreGj4o8A%2FoDF5W4zZ8B04zHhNE3iGf28hlvv4MznWPHVGq%2BxFxO1ZnNg70Hvbf4SxQ&messageId=d-F8F24DE7-B%2C0%7CC%2C0%7CD%2C1
17:47:49.4312467 - 825eb451-e56e-4177-b0ab-3a5902227556 - ChangeState(Connected, Reconnecting)
17:47:49.4362472 - 825eb451-e56e-4177-b0ab-3a5902227556 - OnError(Microsoft.AspNet.SignalR.Client.HttpClientException: StatusCode: 503, ReasonPhrase: 'Service Unavailable', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Connection: close
  Date: Mon, 13 Apr 2015 17:41:11 GMT
  Server: Microsoft-HTTPAPI/2.0
  Content-Length: 326
  Content-Type: text/html; charset=us-ascii
}
   at Microsoft.AspNet.SignalR.Client.Http.DefaultHttpClient.<>c__DisplayClass6.<Post>b__5(HttpResponseMessage responseMessage)
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.<>c__DisplayClass19`2.<Then>b__17(Task`1 t)
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.TaskRunners`2.<>c__DisplayClass42.<RunTask>b__41(Task`1 t))
17:47:51.4474483 - 825eb451-e56e-4177-b0ab-3a5902227556 - LP Reconnect: http://myhub/hub/signalr/signalr/reconnect?clientProtocol=1.4&transport=longPolling&connectionData=[{"Name":"MainHub"}]&connectionToken=lhwcdJTXWXzHSDwi4D2nMkvankzRwYI7eMlKO617w6B37cAtY3hYr5y166q%2BusreGj4o8A%2FoDF5W4zZ8B04zHhNE3iGf28hlvv4MznWPHVGq%2BxFxO1ZnNg70Hvbf4SxQ&messageId=d-F8F24DE7-B%2C0%7CC%2C0%7CD%2C1
17:47:51.5404576 - 825eb451-e56e-4177-b0ab-3a5902227556 - OnError(Microsoft.AspNet.SignalR.Client.HttpClientException: StatusCode: 503, ReasonPhrase: 'Service Unavailable', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Connection: close
  Date: Mon, 13 Apr 2015 17:41:13 GMT
  Server: Microsoft-HTTPAPI/2.0
  Content-Length: 326
  Content-Type: text/html; charset=us-ascii
}
   at Microsoft.AspNet.SignalR.Client.Http.DefaultHttpClient.<>c__DisplayClass6.<Post>b__5(HttpResponseMessage responseMessage)
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.<>c__DisplayClass19`2.<Then>b__17(Task`1 t)
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.TaskRunners`2.<>c__DisplayClass42.<RunTask>b__41(Task`1 t))
17:47:53.5536589 - 825eb451-e56e-4177-b0ab-3a5902227556 - LP Reconnect: http://myhub/hub/signalr/signalr/reconnect?clientProtocol=1.4&transport=longPolling&connectionData=[{"Name":"MainHub"}]&connectionToken=lhwcdJTXWXzHSDwi4D2nMkvankzRwYI7eMlKO617w6B37cAtY3hYr5y166q%2BusreGj4o8A%2FoDF5W4zZ8B04zHhNE3iGf28hlvv4MznWPHVGq%2BxFxO1ZnNg70Hvbf4SxQ&messageId=d-F8F24DE7-B%2C0%7CC%2C0%7CD%2C1
17:47:58.5661601 - 825eb451-e56e-4177-b0ab-3a5902227556 - ChangeState(Reconnecting, Connected)

**Comment by LastTribunal** [comment]
As you can see, ChangeState(Reconnecting, Connected). 
But my IIS server was never restarted!!!
You should have no problem replicating...
BTW, I am explicitly using  Connection.Start(new LongPollingTransport()).ContinueWith(task =>..
I cannot get WebSickets working no matter what (but that's another issue you can help me resolve later perhaps)

Thanks

**Comment by moozzyk** [comment]
Are you sure the server does not auto-start?

**Comment by LastTribunal** [comment]
100%
you can verify for yourself.
There is a bug in the code.  Do I need to open a case with MS?

**Comment by LastTribunal** [comment]
Am I wasting my time on this blog?

**Comment by LastTribunal** [comment]
Thanks for wasting my time

**Comment by BrannonKing** [comment]
I think that the point is this: these legacy transports are so much slower and less reliable than WebSockets. Very few people feel like supporting old stuff (that was only there as a bridge) is worth their time. I feel like the time would be better spent getting the newer transport working. I know that's not an ideal answer; I'm just suggesting that your time may be better spent getting WebSockets working.

**Comment by LastTribunal** [comment]
I would rather have Sockets working, but I am not sure I would get different results
Any suggestions on getting this working, BrannonKing?

**Comment by LastTribunal** [comment]
https://github.com/SignalR/SignalR/issues/3482#issuecomment-104449442

**Comment by LastTribunal** [comment]
I think the original geniuses that built SignalR have moved on to other projects.  The new version was obviously built buy political appointees...

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
