### ISSUE TITLE
Clients do not receive SignalR messages unless the backend application pool is recycled

### ISSUE THREAD

**Issue by raedmalek** [SignalR/SignalR#3456]
Hello,
We currently have an application with a backend hosting a SignalRHub using Owin and a frontend which corresponds to a WPF client.

Business Logic Overview:
When a WPF client is opened, it connects to the Backend SignalRHub and it receives 4 SignalR messages with initial data content (scenario 1). The Backend’s main functionality is to do some calculations based on a group of data. If a part of this data is modified by one of the WPF clients, the Backend/SignalRHub sends a message to all WPF clients informing that calculations are going to be updated (scenario 2).

Explain the problem:
We sometimes have an issue with signalR: clients do not receive messages in scenario 2. This issue happens from time to time as we modify the backend Web.config or as we deploy a new application version.

A workaround we currently use:
When this issue occurs with the backend, we can see in the logs the following scenarios:
-   When a WPF client connects to the SignalRHub, the SignalRHub sends initialization messages to the newly connected WPF client (4 messages: 3 NotifyAgreeds and one NotifySentProfileUpdated). The client receives those messages. So scenario 1 still works correctly.
-   But in scenario 2, none of the WPF clients is getting the message NotifyRealTimeCalculationToBeUpdated from the SignalRHub Backend. Clients are getting no messages from backend anymore after the initialization messages.

This issue is solved if we recycle the backend application pool: when this problem occurs, if we keep all the WPF clients open, recycle the Backend application pool and then modify some of the data using a WPF client User Interface, the SignalRHub backend notifies all clients that a calculation update is ongoing and all clients get the message NotifyRealTimeCalculationToBeUpdated.

Tests and detailed Logs:

Log files can be found at this link https://onedrive.live.com/redir?resid=A6D84531B5817784!195&authkey=!AEjGsg5HxyqSpjQ&ithint=folder%2clog . Please be advised that all clocks are synchronized, so you can rely on the time logged in the files to reconstruct the flow of messages.

Here is a summary of the test I’ve done on : 15/04/2015 (full details in log files)

11:18:51 Start FirstWPFClient
11:18:55 FirstWPFClient receives the 4 initialization messages (3 NofiyAdreeds and one NotifySentProdfileUpdate ) as described in scenario 1

11:19:49 Start SecondWPFClient
11:19:53 SecondWPFClient receives the 4 initialization messages, as described in scenario 1

11:21:28 SecondWPFClient gets InterTSO data calling the service intertsomanagementservice.svc
11:21:34 SecondWPFClient modifies InterTSO data calling the service intertsomanagementservice.svc 

11:21:34 Backend logs the time it took it to save the new modified InterTSO and sends a SignalR message NotifyAgreeds of type TSO  to all clients

NONE of the clients gets this message

RECCYLE backend application pool, keeping WPF clients opened
11:22:26 SecondWPFClient modifies InterTSO data calling the service intertsomanagementservice.svc 
11:22:26 Backend logs the time it took it to save the new modified InterTSO and sends a SignalR message NotifyAgreeds of type TSO  to all clients

ALL clients get this message

11:22:26,851 FirstWPFClient receives the corresponding message
11:22:26,850 Second WPFClient receives the corresponding message

**Comment by moozzyk** [comment]
Please provide a simplified repro and describe the misbehavior in SignalR terms. I took a peek at some of the logs but they are not meaningful to me in any way since they are specific to your app. I did see WSAECONNREFUSED or authentication errors in the log but have no idea if this is related to the issues you are seeing. Also please provide the version of SIgnalR you are using and the transport the client is using to connect to the server.

**Comment by raedmalek** [comment]
related logs. Please refer to the following logs https://onedrive.live.com/redir?resid=A6D84531B5817784!205&authkey=!AAe-dDh5mHudFJI&ithint=folder%2csvclog :
-	BackendSignalRLog_BEFORE_AppPoolRecycle.svclog: SignalR logging on backend before App pool recycle
-	BackendSignalRLog_AFTER_AppPoolRecycle.svclog: SignalR logging on backend after App pool recycle
-	BackendApplicationLog_BEFORE_AppPoolRecycle.log: Application log for the Backend before the Application pool is recycled
-	BackendApplicationLog_AFTER_AppPoolRecycle.log: Application log for the Backend after the Application pool is recycled
-	FirstWPFClientApplicationLog.log: Application log for the first WPF Client that I started.
-	SecondWPFClientApplicationLog.log: Application log for the first WPF Client that I started.
Knowing that clocks are synched between the clients and the Backend, we are able to reconstruct the message exchange workflow looking at client and backend server logs. And an issue might be identified cross-viewing the backend Application and signalR logs. Please be advised that we have a multithreaded async processing application, so processing order in the log is not ordered to the milli-second accuracy level.

Here is extra info about the libraries we are using:
We host SignalR Hub using Owin | nuget packages:
- Microsoft.Owin 3.0.0
- Microsoft.Owin.Security 3.0.0
- Microsoft.Owin.Host.SystemWeb 3.0.0
- Owin 1.0
![backend_startup](https://cloud.githubusercontent.com/assets/9740641/7180655/1b3ec716-e444-11e4-891d-94799b2f1789.png)

SignalR nuget packages used:
-	Microsoft.AspNet.SignalR.Client 2.1.2
-	Microsoft.AspNet.SignalR.Core 2.1.2
-	Microsoft.AspNet.SignalR.JS 2.1.2
-	Microsoft.AspNet.SignalR.SqlServer 2.1.2 | cause in PROD we use two nodes. But the issue still happens when we work on one single node. The test logs I’ve sent are done in an environment having a single node in the backend.
-	Micorosoft.AspNet.SignalR.SystemWeb 2.1.2
-	Microsoft.AspNet.SignalR 2.1.2

Client:
I had also uploaded the code of the main WPF client class SignalRProxy.cs, which handles the client connection to SignalR Hub and the subscription its methods to this link https://onedrive.live.com/redir?resid=a6d84531b5817784%21204 .

The SignalR client is using the following transport protocols: WebSocketTransport and ServerSentEventsTransport.
![clienttransportprotcocol](https://cloud.githubusercontent.com/assets/9740641/7180683/45df56f2-e444-11e4-85d0-a50839024b2b.png)

Please be advised that in our application log, we log in detail all signalR connectionstate change, transport protocol and connectionID, for example
15/04/2015 11:22:22,364  Information   Technical      BELGRID\GIA761  15864  49     -1     00000000-0000-0000-0000-000000000000     Elia.STAT.Wpf.Common.Proxies.SignalRProxy - <InitializeHub>b__e - SignalR - Was (re)Connected: to http://test.belgrid.net/elia.stat.iishost/signalr/ via serverSentEvents (keepAlive?True) as 5db958fa-f2d5-4742-a21d-2b57e50eb4bc

Client subscribes to a list of the HubProxy methods
![clienthubproxymethods](https://cloud.githubusercontent.com/assets/9740641/7180691/6427bfbe-e444-11e4-8097-20a1e909e0ea.png)

Client logs each time is gets a message from the SignalR Hub
![clientloggingsignalrhubmessage](https://cloud.githubusercontent.com/assets/9740641/7180739/d370ed3c-e444-11e4-8d13-7ddeafdf8f76.png)

Server:
The server code for the SignalRHub can be found at this location: https://onedrive.live.com/?cid=a6d84531b5817784&id=a6d84531b5817784%21203&ithint=file,cs&authkey=!AFZgwkb_UQFAESc 
When a client first connect to the SignalR hub (at client startup), clients  gets initial data
![signalrhub1](https://cloud.githubusercontent.com/assets/9740641/7180774/229f75d6-e445-11e4-9570-9841b4651825.png)
![signalrhub2](https://cloud.githubusercontent.com/assets/9740641/7180777/29afb71e-e445-11e4-980f-2fafc1544022.png)
![signalrhub3](https://cloud.githubusercontent.com/assets/9740641/7180783/2e2b6784-e445-11e4-90d7-d01b221ed971.png)
![signalrhub4](https://cloud.githubusercontent.com/assets/9740641/7180787/33757766-e445-11e4-8b40-2421988ccbc5.png)

Tests and detailed Logs:
Now if we take a look at the logs of the tests I've described in my first post, we find the following:
FirstWPFClientApplicationLog.log (this is also visible in Backend log)
11:18:51 Start FirstWPFClient
11:18:55 FirstWPFClient receives the 4 initialization messages (3 NofiyAdreeds and one NotifySentProdfileUpdate ) as described in scenario 1

SecondWPFClientApplicationLog.log (this is also visible in Backend log)
11:19:49 Start SecondWPFClient
11:19:53 SecondWPFClient receives the 4 initialization messages, as described in scenario 1

SecondWPFClientApplicationLog.log (this is also visible in Backend log)
11:21:28 SecondWPFClient gets InterTSO data calling the service intertsomanagementservice.svc
11:21:34 SecondWPFClient modifies InterTSO data calling the service intertsomanagementservice.svc 

BackendApplicationLog_BEFORE_AppPoolRecycle.log
11:21:34 Backend logs the time it took it to save the new modified InterTSO and sends a SignalR message NotifyAgreeds of type TSO  to all clients

NONE of the clients gets this message

<<RECYLE backend application pool, keeping WPF clients opened>>

SecondWPFClientApplicationLog.log (this is also visible in Backend log)
11:22:26 SecondWPFClient modifies InterTSO data calling the service intertsomanagementservice.svc 
11:22:26 Backend logs the time it took it to save the new modified InterTSO and sends a SignalR message NotifyAgreeds of type TSO  to all clients

ALL clients get this message

FirstWPFClientApplicationLog.log (this is also visible in Backend log)
11:22:26,851 FirstWPFClient receives the corresponding message

SecondWPFClientApplicationLog.log (this is also visible in Backend log)
11:22:26,850 Second WPFClient receives the corresponding message

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
