### ISSUE TITLE
Message class instances leaking on SignalR 2.2.0 Self-Hosted in push to client

### ISSUE THREAD

**Issue by sevzas** [SignalR/SignalR#3458]
This issue might be related: https://github.com/SignalR/SignalR/issues/2413

I'm using SignalR 2.2.0 Self-Hosted with Owin on Windows 2008 R2 and .NET 4.5.  The client is written in Csharp on .Net 4.5.

In my test case I have the server pushing events (< 1 Kb each) to the client.  So there is one server, one client, and one Hub method for pushing data to the client.  This is running for an extended period of time (>30 minutes).

What I see in .Net Memory profiler is that the server is accumulating instances of Message, Message[] and MessageStore<Message>.Fragment.  It just keeps going up without bound.  It appears that the Message instances are linked like this:

Message <- 
Message[] <- 
MessageStore<Message>.Fragment <- 
MessageStore<Message>.Fragment[]
MessageStore<Message>

I've examined the SignalR source code closely and (ofcourse I could be wrong) but I don't see any mechanism for pruning Message instances from a MessageStore.  I do see something that garbage collects *Topics* in MessageBus.cs (a timer that calls GarbageCollectTopics() ) but I don't see how that can prune *Message* instances from a live MessageStore<Message>.

Could someone explain to me whether there is a mechanism for pruning Message objects from a long-lived MessageStore<Message> and how it works.

Thanks in advance.

**Comment by moozzyk** [comment]
#3205  ? The server has a ring buffer where the messages are stored.

**Comment by sevzas** [comment]
Thanks for that simple explanation.
