### ISSUE TITLE
Transport connection performance counters are wrong after falling back to long polling

### ISSUE THREAD

**Issue by deftflux** [SignalR/SignalR#3459]
### Functional impact

"Connections Current" performance counters specific to each transport cannot be trusted for diagnosing connection issues.
### Steps to reproduce

Here's some code:
#### Startup.cs

``` c#
using System;
using Microsoft.AspNet.SignalR;
using Microsoft.AspNet.SignalR.Transports;
using Owin;

namespace SignalRTransportCounterIssue
{
    public class Startup
    {
        static Startup()
        {
            var transportManager = GlobalHost.DependencyResolver.Resolve<ITransportManager>() as TransportManager;
            transportManager.Remove("foreverFrame");


            // To see the same thing happen for SSE falling back to long polling, comment out this line:
            transportManager.Remove("serverSentEvents");
        }

        public void Configuration(IAppBuilder app)
        {
            app.Map("/signalr", map =>
            {
                map.Use(async (ctx, continuation) =>
                {
                    await continuation();

                    // Make web sockets fail on the client so that the client falls back to long polling:
                    if (ctx.Request.Path.Value.StartsWith("/connect") && (ctx.Request.Query["transport"] == "webSockets"))
                        throw new Exception();
                });

                map.RunSignalR();
            });
        }
    }
}
```
#### test.html

``` html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
    <script src="Scripts/jquery-1.6.4.js" type="text/javascript"></script>
    <script src="Scripts/jquery.signalR-2.2.0.js" type="text/javascript"></script>
    <script type="text/javascript">
        var connection = $.hubConnection();

        connection.stateChanged(function(e) {
            if (e.newState === $.signalR.connectionState.disconnected) {
                $("#connectButton").text("Connect");
            } else {
                $("#connectButton").text("Disconnect");
            }
        });

        $(function() {
            $("#connectButton").click(function() {
                if ($(this).text() === "Connect") {
                    connection.start();
                } else {
                    connection.stop();
                }
            });
        });
    </script>
</head>
<body>

<div>
    <button id="connectButton" style="display: inline-block">Connect</button>
</div>
</body>
</html>
```
1. Make sure SignalR performance counters are installed.
2. Create an ASP .NET SignalR app using the code above and build it.
3. Create a new web site in IIS on a free port and point it to this app.
4. Edit the application pool settings for this web site and set the identity to NetworkService so that it has permission to access the performance counters.
5. Open a browser that supports web sockets or server sent events and navigate to test.html.
6. Click the "Connect" button.  This will spin up SignalR and cause the perf counter instance to be created.
7. Close the page and recycle the application pool so we can start with zeros.
8. Open perfmon and add the SignalR performance counters for the web site instance to the "Performance Monitor" tool.
9. Switch to "Report" graph style.
10. Once again, navigate to test.html and click "Connect".
11. Click "Disconnect".
### Expected result

Since no one is connected anymore, all transport connection counters should say 0.
### Actual result

One counter (WebSockets or ServerSentEvents) says 1, and LongPolling says 2,147,483,649.
### Further technical details

We are trying to diagnose why our SignalR application thinks there are more connections than there actually are.  The application is listening to OnConnected, OnReconnected, and OnDisconnected on the hub, and it keeps track of connection IDs that are connected and which transport they belong to.  When we compared our data to the SignalR performance counters, we noticed a rather obvious issue:

![signalr report highlighted](https://cloud.githubusercontent.com/assets/2748582/7171092/bd071a40-e399-11e4-879b-9d51a0abd9fc.png)

The "Connections Current LongPolling" counter is wrong; we don't have over 2 million long pollers.  In fact, "Connections Current" reports a total of 2,940 connections, so obviously the math doesn't add up.

What does add up is if you consider 2,147,483,665 to be a negative number, but with something gone terribly wrong in bitwise handling.  If you assume that it is a 32-bit number and zero out the sign bit, you get 17.  Make that a negative number (yes, I know that is not actually how you would do a bitwise negate operation, but bear with me), and you get -17.  Add in the counts from the other transports: -17 + 334 + 2,623 = 2,940.  This consistently checks out in all of my testing.  Further, a look at the graph for this counter makes it reasonable to think that it is actually a negative number:

![signalr longpolling graph](https://cloud.githubusercontent.com/assets/2748582/7171175/9b617f2e-e39a-11e4-8a65-7cf70706a04c.png)

We see here that when the process started, it immediately got many long pollers who reconnected, but then the number steadily goes down for some unknown reason until it goes negative.

I've actually been able to reproduce this issue in a new app.  It happens when a user first tries to connect using web sockets or server sent events but ends up falling back to long polling.  At that time, the counter for the original transport is not decremented; neither is the counter for long polling incremented.  Then, once the long poller disconnects, the long polling counter is decremented.  See steps to reproduce above.

**Comment by pablohiga** [comment]
The same is happening to me guys. Looking forward to updates about this. Thanks!

**Comment by Laver** [comment]
+1 vote for this. I had spotted the astronomically high number of LongPolling connections and was freaking out about issues in my application.

**Comment by ammills01** [comment]
Same issue here, but only on one box in a load balanced environment.

**Comment by anurse** [comment]
I've identified the issue. It occurs because we have separate counters for connections per transport, but when a connection hops transports we don't properly manage the connection counters there, so if a connection arrives on the WebSockets transport but later changes to Server-Sent Events (or Long Polling) and then disconnects, we end up with the WebSockets counter at +1 and the SSE/LP counter at -1 (which becomes Int32.MaxValue because the counters don't allow negative values.

The fix is just to transfer the count values when a connection hops transport by decrementing the old transport's counter and incrementing the new one. It's pretty straight forward and low-impact/low-risk. /cc @muratg @moozzyk 

PR coming shortly.
