### ISSUE TITLE
Add timeout to poll requests in longpolling transport

### ISSUE THREAD

**Issue by moozzyk** [SignalR/SignalR#3462]
We added a timout to poll requests in the JS client (ae2bd7e5675c5028) but we did not have time to add it in the .NET client. Without timeouts the .NET client can sort of hang waiting for a response that will never be sent as described in #3460

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
