### ISSUE TITLE
Reconnect not detected by the Server when transport is SSE

### ISSUE THREAD

**Issue by esskar** [SignalR/SignalR#3464]
I am running one SignalR server (current NuGet SignalR 2.2) and I connect with my Xamarin iOS client, also Nuget SignalR 2.2. 
When I switch, from wifi to 3g, i see OnDisconnect class in my hubs with stopCalled = false.
But i never see a Reconnect.
Now, i am still able to call functions on my hub, they get triggered on the server with the connection id i see during the first connect.
But when i try to call a function on the client using the connection id, nothing is received on the client.
so it looks like that the server forgets about the connection id.

I force transport SSE on the client. And connection is SSL secured.

**Comment by draganjovanovic1** [comment]
I had the same case yesterday (SignalR server 2.2 and SignalR client 2.2 on Xamarin Android app). Transport is SSE and connection is not SSL secured.

Client switched from 3G/HSDPA to WiFi and server fired OnDisconnect event without OnReconnect after that. Client continued to invoke server method with the same connection id but server could not reach the client any more. I tried to kill sever app for a minute or more and after turning hub on again client just continued invoking server with the same connection id as before w/o OnConnect or OnReconnect fired. I checked ITransportHeartbeat.GetConnections() and there were no connections there.

I tried to reproduce this today (switching between WiFi and cell network) but with no success.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
