### ISSUE TITLE
Blocking /abort request on pageunload seems unnecessary

### ISSUE THREAD

**Issue by Plasma** [SignalR/SignalR#3467]
Hello,

I received reports that our website was running slow from time to time.

I've tracked it down to SignalR JavaScript library hijacking the page unload methods when navigating to a new page URL, in order to send a synchronous /abort request via POST.

This sometimes takes multiple seconds for some reason (especially over the ocean between users and data centers) and seems unnecessary.

I've disabled this on my end by no-op'ing the abort methods so they don't do anything.

Is this something that can be removed from a future release?

Thank you

**Comment by ianschmitz** [comment]
We're in the same boat here. Would love to see this request performed asynchronously.

**Comment by Plasma** [comment]
As a temporary workaround I've overridden the abort methods by adding this script block right after the SignalR Hub script include:

````javascript
<script>
		/* SignalR Abort Remover */
		var noOpSignalRFunc = function () {
			if (console && console.log)
				console.log("Ignoring abort() request in SignalR transport");
		}

		$.signalR.transports.webSockets.abort = noOpSignalRFunc;
		$.signalR.transports.foreverFrame.abort = noOpSignalRFunc;
		$.signalR.transports.serverSentEvents.abort = noOpSignalRFunc;
		$.signalR.transports.longPolling.abort = noOpSignalRFunc;
</script>
````

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
