### ISSUE TITLE
using camelcase

### ISSUE THREAD

**Issue by jahtalab** [SignalR/SignalR#3468]
i tried to use camelCase with signalR, after i registered JsonSerializer with camleCase config, i got this error in the client:

You are using a version of the client that isn't compatible with the server. Client version 1.5, server version undefined.

I tracked down the problem to this part of client javascript code:

``` javascript
if (!res.ProtocolVersion || res.ProtocolVersion !== connection.clientProtocol) {
    protocolError = signalR._.error(signalR._.format(resources.protocolIncompatible, connection.clientProtocol, res.ProtocolVersion));
    $(connection).triggerHandler(events.onError, [protocolError]);
    deferred.reject(protocolError);

    return;
}

```

it expects the response to have 'ProtocolVersion' while the response contains 'protocolVersion'. the casing isn't right.

any idea when this will be fixed.

**Comment by swestner** [comment]
Did you ever resolve this? I am running into the same issue.

**Comment by jahtalab** [comment]
@swestner 
you can register this  [ContractResolver](https://gist.github.com/jahtalab/581f7281e90179c1aa38) in your JsonSerializerSettings

This class converts all objects to camelCase except those that come from SignalR assembly.

**Comment by alexjamesbrown** [comment]
Having same issue, 

When registering like this

            //camel case json for signalr
            var serializerSettings = new JsonSerializerSettings
            {
                ContractResolver = new CamelCasePropertyNamesContractResolver()
            };

            var serializer = JsonSerializer.Create(serializerSettings);
            GlobalHost.DependencyResolver.Register(typeof(JsonSerializer), () => serializer);

**Comment by lozzadude** [comment]
I had the same issue @alexjamesbrown. The solution here worked for me: https://stackoverflow.com/questions/30005575/signalr-use-camel-case

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
