### ISSUE TITLE
invoking specific client method - topic doesn't exists

### ISSUE THREAD

**Issue by jahtalab** [SignalR/SignalR#3470]
I'm trying to invoke a method in client by connectionId, here is the code the i use:

``` csharp
dynamic t = Clients.Client(Context.ConnectionId);
(t as ConnectionIdProxy).Invoke("someMethod", data);
```

this doesn't invoke the method in client and also gives no exceptions.

after using dotPeek to trace SignalR code i traced the issue to these lines of code in MessageBus class:

``` csharp
    public virtual Task Publish(Message message)
    {
      if (message == null)
        throw new ArgumentNullException("message");
      Topic topic;
      if (this.Topics.TryGetValue(message.Key, out topic))
      {
        long num = (long) topic.Store.Add(message);
        this.ScheduleTopic(topic);
      }
      this.Counters.MessageBusMessagesPublishedTotal.Increment();
      this.Counters.MessageBusMessagesPublishedPerSec.Increment();
      return TaskAsyncHelper.Empty;
    }

```

the problem is the message.key that SignalProxy produces (ie "hc-StockHub.75397aea-9dad-45df-8bad-84bbc5eca7f0") doesn't exists in Topics, so the line "this.Topics.TryGetValue(message.Key, out topic)" returns false and the method doesn't get called in the client.

inspecting the topics shows that it contains message key "c-75397aea-9dad-45df-8bad-84bbc5eca7f0", although it's not what has been produced by SignalProxy.

Is this a bug or I'm doing something wrong?

**Comment by BrannonKing** [comment]
You're not doing anything wrong. Somewhere along the line it was designed to do nothing in this particular scenario. I agree with your premise, though. I think we should add an `else` there that does something to inform the developer.

**Comment by jahtalab** [comment]
I didn't understand why it is doing nothing. 
I wanted to invoke a client method but it doesn't work. 
how should I fix this?
how to invoke a client method given its connectionId?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
