### ISSUE TITLE
Case sensitiveness issue on groups names when using redis backplane.

### ISSUE THREAD

**Issue by fbiagi** [SignalR/SignalR#3472]
Groups names should be case sensitive. This works well when using the default MessageBus.

But when I use the redis backplane, if I send a message to a group with out matching the case the group was created with, it will be stored on the topic, but not sent. If a another message is sent to the group, this time with matching case, both messages will be push to the client.

The exact basic scenario is this one:

``` C#
public class RtConnection : PersistentConnection
{
    protected override Task OnConnected(IRequest request, string connectionId)
    {
        var username = request.User != null ? request.User.Identity.Name : null;
        if (username != null)
        {
            return Groups.Add(connectionId, username); // username == "DOMAIN\user.name"
        }
        return base.OnConnected(request, connectionId);
    }
}
```

an then, the messages are sent from the server like this:

``` C#
var context = GlobalHost.ConnectionManager.GetConnectionContext<RtConnection>();

context.Groups.Send(group, "Message 1"); // group == "Domain\user.name"
// Not sent to client

// A while later...

context.Groups.Send(group, "Message 2"); // group == "DOMAIN\user.name"
// Client receives "Message 1" and "Message 2" immediately after this
```

Also, when connected with longPolling, the "Message 1" is received after a new polling request starts.

The SignalR version I'm using now is 2.2.0, but I also had the issue with some of the previous versions.

I've created a simple project (vs2012) to reproduce this: https://github.com/fbiagi/SignalRGroupIssue

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
