### ISSUE TITLE
Add an OnIncomingFinally method to HubPipelineModule

### ISSUE THREAD

**Issue by halter73** [SignalR/SignalR#3473]
Unlike OnAfterIncoming or OnIncomingError, OnIncomingFinally would be guaranteed to get called once if OnBeforeIncoming returns true regardless of the success or failure of the invocation.

If one were to simply override OnAfterIncoming and OnIncomingError, both might get called if OnAfterIncoming throws, so doing this isn't exactly the same as overriding an OnIncomingFinally method.

This probably isn't a super high priority, because you can still override BuildIncoming, but that isn't as nice/easy as overriding the On\* methods.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
