### ISSUE TITLE
Hugh memory usage in SignalR

### ISSUE THREAD

**Issue by LekOkay** [SignalR/SignalR#3474]
Hi there,

I have a problem when I using SignalR in my IM project. It run in Windows Azure. Everytime it become normal after I stop the website and restart it again.

I don't know what happen about that. I had dump file when it happened today. Could anybody tell me how to find out what happen about my cause?

Thanks very much.

![2015-04-25_165503](https://cloud.githubusercontent.com/assets/8298378/7332314/2ff2c4b2-eb6c-11e4-98e4-f8e967bca83c.png)

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
