### ISSUE TITLE
HubContext group call issue

### ISSUE THREAD

**Issue by jahtalab** [SignalR/SignalR#3475]
I'm using signalR to broadcast values to clients, I created a singleton class that gets HubContext like this:

``` c#
private readonly Lazy<IHubContext> _tickerHubContext = new Lazy<IHubContext>(() => GlobalHost.ConnectionManager.GetHubContext<TickerHub>());
```

also in my TickerHub class i have a subscribe method that clients call and i register them in a group.

the issue is that when i try to call a client method using a group it doesn't work.

I traced SignalR code, and it looks like the problem is in MessageBus class, Publish method:

``` c#
    public virtual Task Publish(Message message)
    {
      if (message == null)
        throw new ArgumentNullException("message");
      Topic topic;
      if (this.Topics.TryGetValue(message.Key, out topic))
      {
        long num = (long) topic.Store.Add(message);
        this.ScheduleTopic(topic);
      }
      this.Counters.MessageBusMessagesPublishedTotal.Increment();
      this.Counters.MessageBusMessagesPublishedPerSec.Increment();
      return TaskAsyncHelper.Empty;
    }
```

the topic that SignalProxy generates for group call, doesn't exist in this.Topics,

also since i'm working on this I'm interested in contributing to SignalR respository,
but I need some help to figure out what exactly is causing this issue.

**Comment by stricq** [comment]
I would like to second this.  I'm seeing the exact same issue when running under Windows Server 2012 R2.  On my local machine, Windows 7 Enterprise, it works fine.

**Comment by halter73** [comment]
If the topic doesn't exist, that generally means that there are no clients are currently subscribed to the group. Are you sure this isn't the problem?

**Comment by Reedwarbler** [comment]
I have the same issue. A test a demo website, and it works well on my local laptop with Windows 10. But when deployed on Amazon AWS (under Windows Server 2012 R2, http://ec2-54-200-104-97.us-west-2.compute.amazonaws.com/index.html) the group broadcast failed, but peer-to-peer and broadcast to all works fine.

**Comment by halter73** [comment]
@Reedwarbler Do you have multiple instances/load balancing setup on AWS?

**Comment by Reedwarbler** [comment]
@halter73  I didn't set the load balance, and there is only one instance.

**Comment by halter73** [comment]
@Reedwarbler I took a quick look at http://ec2-54-200-104-97.us-west-2.compute.amazonaws.com/index.html, but http://ec2-54-200-104-97.us-west-2.compute.amazonaws.com/Scripts/jquery.signalR-2.0.3.min.js is giving a 404.

**Comment by Reedwarbler** [comment]
@halter73  would you please check again? I was debugging the code, and covered with an old one.

**Comment by halter73** [comment]
@Reedwarbler I cloned your github repo. Are you sure that this is the project that you are deploying to AWS? It doesn't compile unless I change the "OnDisconnected" method in "ChatHub" to include the [stopCalled parameter](http://stackoverflow.com/a/27317578/719967). Once that change is made everything works locally. I know your issue is AWS only, but I wonder if your aren't running the code you think you are.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
