### ISSUE TITLE
Using longPolling slows down all AJAX calls

### ISSUE THREAD

**Issue by darrylluther** [SignalR/SignalR#3477]
I have found that when using the longPolling transport method my AJAX calls take a very long time. For example, with an active SignalR connection one of my AJAX calls took almost 2 minutes (1:53.58). Without an active SignalR connection it takes about 2 seconds. Normally I would fire up the developer tools to try to get some additional details, but this happens to be running in a 3rd party application that hosts an IE browser internally. I decided to fire up Fiddler to see if I could see anything going on and suddenly the AJAX call dropped back to a normal timeframe - 1.593 seconds (Fiddler results shown below). As soon as I shut down Fiddler the AJAX call goes back up to 2 minutes.

Request Count:   1
Bytes Sent:      1,282		(headers:1,282; body:0)
Bytes Received:  448		(headers:276; body:172)

ACTUAL PERFORMANCE
--------------
ClientConnected:	10:41:01.875
ClientBeginRequest:	10:41:01.906
GotRequestHeaders:	10:41:01.906
ClientDoneRequest:	10:41:01.906
Determine Gateway:	0ms
DNS Lookup: 		0ms
TCP/IP Connect:	0ms
HTTPS Handshake:	0ms
ServerConnected:	10:41:01.906
FiddlerBeginRequest:	10:41:01.906
ServerGotRequest:	10:41:01.906
ServerBeginResponse:	10:41:03.500
GotResponseHeaders:	10:41:03.500
ServerDoneResponse:	10:41:03.500
ClientBeginResponse:	10:41:03.500
ClientDoneResponse:	10:41:03.500

	Overall Elapsed:	0:00:01.593

RESPONSE BYTES (by Content-Type)
--------------
       ~headers~: 276
application/json: 172

**Comment by darrylluther** [comment]
Scratch this - it appears to be a localized issue and I can't replicate on other PCs nor VMs.

**Comment by moozzyk** [comment]
I was wondering if you are not running into some connection limit issue. Poll requests (by default) take up to 110 seconds. It seems that in your case a poll request is blocking the other request and when the server terminates the poll request the other request is executed so the requests are serialized.
