### ISSUE TITLE
System.InvalidOperationException: Data cannot be sent because the WebSocket connection is reconnecting

### ISSUE THREAD

**Issue by wprakash** [SignalR/SignalR#3479]
Hello,

I am using .NET client from A worker role to send realtime notifications to a WebRole which uses signalr backplane, but often the websocket is reconnecting and i am getting the following issue
System.InvalidOperationException: Data cannot be sent because the WebSocket connection is reconnecting.

Below is my signalr configuration in the webrole 
GlobalHost.Configuration.TransportConnectTimeout = TimeSpan.FromSeconds(5);
            GlobalHost.Configuration.KeepAlive = TimeSpan.FromSeconds(3);
            //To allow unlimited size
            GlobalHost.Configuration.MaxIncomingWebSocketMessageSize = null;
            GlobalHost.Configuration.ConnectionTimeout = TimeSpan.FromHours(1);

**Comment by moozzyk** [comment]
Messages cannot be send when the connection is reconnecting. You can subscribe to the `OnReconnecting/OnReconnected` events to be notified when reconnection happens.

**Comment by wprakash** [comment]
Yes i have subscribed to OnReconnecting/OnReconnected events, but ours is a high volume scenario and the messages keep coming through the azure service, what happens is that, the reconnection is happening almost every 3 seconds. And i am using Service Bus Backplane in my web role

**Comment by moozzyk** [comment]
I think you need to figure out why the connection is being dropped. Having a reconnect every 3 secs is not really expected.
