### ISSUE TITLE
Allow creating partitioned topics in ServiceBus scaleout by configuration

### ISSUE THREAD

**Issue by pseabury** [SignalR/SignalR#3481]
The ServiceBusScaleoutConfiguration should include a mechanism to optionally create partitioned Topics for the scaleout.  Empirical data collected over the past few months indicates that ServiceBus is not really a feasible scaleout mechanism due to the number of failed operations - even at low to moderate messaging volumes (order of 100's of ops per hour).

See - https://msdn.microsoft.com/en-us/library/azure/dn520246.aspx

**Comment by pseabury** [comment]
This will require upgrading SignalR to use Azure SDK v2.2 or later.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
