### ISSUE TITLE
a problem whit Cross Domain ,call connect.stop(),this is a problem

### ISSUE THREAD

**Issue by maobiwen** [SignalR/SignalR#3485]
js client version:2.0.1
signalr:2.2.0

when Cross Domain,call  $.connection.hub.stop(false, true); ,the server will not get notify as right,it will get notify after 30 seconds or later

if somebody open six page in 30 secondes ,the google chrome will not to work ,it will say"wait for socket ..." 

I dont know what can I do ,somebody can help me ? if you have deal with it ,please email to me,my email address is 9806230@qq.com 
thank you

BWT,I am a Chinese ,my english is .....sorry

**Comment by rooferz** [comment]
I've got the same problem only in Firefox 41.0.1. I'm using lastest source available but this problem still occurs.

When I refresh or leave the page, I receive this error in console:

>15:42:19.485 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:1664/signalr/abort?transport=webSockets&clientProtocol=1.5&connectionToken=vOnWSNSTu6QdDxj2MykAWV9IUs7YcurMCgTmdTYAzDmMiyRgsZoWdv4hdCuP51NzwJUXMRFRiS0LB4TVIeo2m3nn4qbaiEU5xDrCsEsjO5Gp%2FiyR1KY%2BAx2sfeXeOVPB&connectionData=%5B%7B%22name%22%3A%22callhub%22%7D%5D. (Reason: CORS request failed).1 <unknown>

But all connection process goes very well, I'me getting notified of my event, etc...

I'm on IIS 8 + NET 4.5 + WebSocket enabled.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
