### ISSUE TITLE
[Android] MalformedJsonException: SignalR Server returns HTML instead of JSON

### ISSUE THREAD

**Issue by antony-jekov** [SignalR/SignalR#3486]
Steps to reproduce:
1. Simple SignalR setup:

```
public class ChatHub : Hub
{
    public void Send(string msg)
    {
        Clients.Others.broadcastMessage(msg);
    }
}

public void Configuration(IAppBuilder app)
{
    var config = new HubConfiguration();
    config.EnableJSONP = true;
    app.MapSignalR(config);
}
```
1. Setup Android as shown in the java examples - https://github.com/SignalR/java-samples/blob/master/signalr-sample-chat/src/microsoft/aspnet/signalr/samples/chat/Program.java

Expected result: Successful connection.
Actual result: NegotiationResponse(String jsonContent, JsonParser parser) constructor receives an html page for jsonContent and exception is thrown.

Source code: https://drive.google.com/folderview?id=0BzROoa3Sf7D2flQ3bE9CWTRaWVQ3V1Z1aFZrZjQxN2ZnYzFMSURjUnRtVlRjanJhMDBGWXc&usp=sharing

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
