### ISSUE TITLE
Internet Explorer - ForeverFrame 'Access is Denied' Error

### ISSUE THREAD

**Issue by johncmatthews** [SignalR/SignalR#3487]
When SignalR attempts to negotiate using ForeverFrame with Internet Explorer, SignalR fails with an 'Access is Denied' error.

Console Ouput:
SignalR: Negotiating with '/signalr/negotiate'. 
SignalR: This browser doesn't support SSE. 
SignalR: Binding to iframe's readystatechange event. 
SCRIPT5: Access is denied.

This issue is only occurring in Internet Explorer.  I am using JavaScript library v1.1.2.  This is identical to the behavior that was reported in #2054.  Do you have any recommendations for a work-around?  Unfortunately, forcing users to disable their script debugging in Internet Explorer is not a valid work-around for us.

IIS version 8.0
Internet Explorer version 10

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
