### ISSUE TITLE
WebApp.Start will silently fail every other attempt in a Windows Service

### ISSUE THREAD

**Issue by mrwatts** [SignalR/SignalR#3488]
Hi,

I am developing a simple Windows Service, based on TopShelf and SignalR.

The problem is that the WebApp.Start method will silently fail every other attempt to start the service. So, at the first attempt the service will fail to start (the service manager will say the service did not start in a timely fashion), at the second attempt the service will run fine. If the service is stopped and then started, this will fail. The second attempt to start, will succeed. And so on and so on.

The line that fails is the 

``` c#
signalR = WebApp.Start("http://*:8080/");
```

line. It goes silently. There is no output, debugger exception (add a Thread.Sleep to give yourself some time to attach the debugger), nothing...

The code below is a stripped down version of my program and can be pasted into a standard C# console application program.cs template:

``` c#
/* 
This demonstation app requires the following nuget packages:

Microsoft.AspNet.SignalR.SelfHost
TopShelf

If this app generates an access denied exception, run the following from an elevated command prompt:

netsh http add urlacl url=http://*:8080/ user=DOMAIN\username

After building, install the windows service by passing the install parameter on the command line to the generated executable
*/
using Microsoft.AspNet.SignalR;
using Microsoft.AspNet.SignalR.Hubs;
using Microsoft.Owin;
using Microsoft.Owin.Hosting;
using Owin;
using System;
using System.Timers;
using Topshelf;

[assembly: OwinStartup(typeof(SignalRServiceTest.Startup))]
namespace SignalRServiceTest
{
    class Program
    {
        static void Main(string[] args)
        {
            IDisposable signalR = null;
            if (args.Length == 0 || args[0][0] == '-')
            {
                // we are not installing or doing any other TopShelf-ish operations

                // A TopShelf service can be started from the command line using the start command
                // which will cause the TopShelf application to start itself as a windows service. 
                // This makes that we will be started twice. 
                // Only the service instance must start the signalR app

                // PROBLEM:
                // the following line will silently fail every other attempt to start the windows service
                signalR = WebApp.Start("http://*:8080/");
            }

            using (signalR)
            {
                HostFactory.Run(configurator =>
                {
                    var service = new Service();

                    configurator.Service<Service>((s) =>
                    {
                        s.ConstructUsing(name => service);
                        s.WhenStarted(tc => tc.Start());
                        s.WhenStopped(tc =>
                            {
                                tc.Stop();
                                tc.Dispose();
                            });
                    });
                    configurator.RunAsLocalSystem();

                    configurator.SetDescription("SignalR Test Service");
                    configurator.SetDisplayName("SignalRTest");
                    configurator.SetServiceName("SignalRTestService");
                });
            }
        }
    }

    public class Service
    {
        private Timer _timer;

        public Service()
        {           
            _timer = new Timer(15) { AutoReset = true };
            _timer.Elapsed += (sender, args) => { };
        }
        public void Start()
        {
            _timer.Start();
        }

        public void Stop()
        {
            _timer.Stop();
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        protected virtual void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_timer != null)
                {
                    _timer.Dispose();
                    _timer = null;
                }
            }
        }
    }

    public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            app.MapSignalR();
        }
    }

    [HubName("SignalRTest")]
    public class MasterHub : Hub
    {
    }
}
```

I don't have a clue what's going on here and why it's failing. But considering the symptoms I am assuming a bug somewhere at the moment.

Note that you can run the application from VS or the command line as often as you want and it will succeed. It only fails when run as a service.

Martin

**Comment by mrwatts** [comment]
After some more debugging the conclusion is it has to do with a problem with performance counters.

The problem does not occur in the WebApp.Start method, but in MapSignalR. In the PerformanceCounterManager class, in the LoadCounter method, the following line causes the application to crash:

```c#
// Initialize the counter sample
counter.NextSample();
```

**Comment by mrwatts** [comment]
I found another issue posted here that seems to point to the same problem: #3414
I have implemented a similar solution as posted there, with a dummy performance counter, for the time being.

The positive side of this workaround is that the time required to start SignalR has been greatly reduced, from a few seconds to a few ms. :)

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
