### ISSUE TITLE
Slow disconnect

### ISSUE THREAD

**Issue by johnfcporto** [SignalR/SignalR#3490]
I have a class library and a web app that uses the dll .

My problem consists in this:
1. I login normally with some credencials.
2. I login with another user.
3. Get the list of users online.
4. When I disconnect some user, it takes almost 1 minute to go to onDisconnect method.

What is the problem somebody knows?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
