### ISSUE TITLE
SignalR Backplane Spuriously Disconnects

### ISSUE THREAD

**Issue by josh-ak** [SignalR/SignalR#3491]
Configuration: Azure service bus (same results with Azure Redis cache), Azure standard app service plan with 2 instances

Issue: OnDisconnect is called with frequency on hub even though the connection with the client is in a connected state. This only occurs when the backplane is used with multiple instances (if the backplane is enabled with a single instance, this problem does not occur). When this issue occurs and OnDisconnect is invoked, the connection still works: client-to-hub and hub-to-client calls continue to succeed (OnConnected is not subsequently invoked and the connection id is unchanged).

The following log entries demonstrate the issue. Log statements are present in OnConnected, OnReconnected and OnDisconnected. Not that the connectionIds between the 2 instances are unchanged. OnDisconnected is called multiple times, but the connection is still active (client-to-hub and hub-to-client methods succeed). (The connection ids were changed to 3 and 4 to make them more readable.)

OnDisconnected - user 1, connection id 3, Instance 5
OnDisconnected - user 1, connection id 3, Instance 6
OnDisconnected - user 2, connection id 4, Instance 5
OnDisconnected - user 1, connection id 3, Instance 5
OnDisconnected - user 2, connection id 4, Instance 6
OnConnected - user 1, connection id 3, Instance 5
OnConnected - user 1, connection id 3, Instance 6

The OnDisconnected method results from TransportHeartBeat in SignalR.Core timing out. In RaiseDisconnect, elapsed >= threshold is true. In this case threshold is set to GlobalHost.Configuration.DisconnectTimeout (30 seconds by default). Note that even though this timeout occurs, the connection is still functional. Again…all calls succeed during the period in which it is timing out and after it times out.

Transport log:
SignalR.Transports.LongPollingTransport Information: 0 : Timeout(ecb2c5ba-0a71-43e9-a3b8-744d48a7f6b1)
SignalR.Transports.LongPollingTransport Information: 0 : End(ecb2c5ba-0a71-43e9-a3b8-744d48a7f6b1)
SignalR.Transports.LongPollingTransport Verbose: 0 : Cancel(ecb2c5ba-0a71-43e9-a3b8-744d48a7f6b1)
SignalR.Transports.LongPollingTransport Verbose: 0 : DrainWrites(ecb2c5ba-0a71-43e9-a3b8-744d48a7f6b1)
SignalR.Transports.LongPollingTransport Information: 0 : CompleteRequest (ecb2c5ba-0a71-43e9-a3b8-744d48a7f6b1)
SignalR.Transports.TransportHeartBeat Verbose: 0 : ecb2c5ba-0a71-43e9-a3b8-744d48a7f6b1 is dead
SignalR.Transports.TransportHeartBeat Verbose: 0 : KeepAlive(f9284f8b-f8d7-4358-9298-25f28048da62)
SignalR.Transports.TransportHeartBeat Verbose: 0 : KeepAlive(c2c4f90a-8ecd-4d5e-ae98-8cd4859f7023)
SignalR.Transports.TransportHeartBeat Verbose: 0 : ecb2c5ba-0a71-43e9-a3b8-744d48a7f6b1 is dead
SignalR.Transports.LongPollingTransport Information: 0 : Timeout(c2c4f90a-8ecd-4d5e-ae98-8cd4859f7023)
SignalR.Transports.LongPollingTransport Information: 0 : End(c2c4f90a-8ecd-4d5e-ae98-8cd4859f7023)
SignalR.Transports.LongPollingTransport Verbose: 0 : Cancel(c2c4f90a-8ecd-4d5e-ae98-8cd4859f7023)
SignalR.Transports.LongPollingTransport Verbose: 0 : DrainWrites(c2c4f90a-8ecd-4d5e-ae98-8cd4859f7023)
SignalR.Transports.LongPollingTransport Information: 0 : CompleteRequest (c2c4f90a-8ecd-4d5e-ae98-8cd4859f7023)
SignalR.Transports.TransportHeartBeat Verbose: 0 : ecb2c5ba-0a71-43e9-a3b8-744d48a7f6b1 is dead
SignalR.Transports.TransportHeartBeat Verbose: 0 : KeepAlive(f9284f8b-f8d7-4358-9298-25f28048da62)
SignalR.Transports.TransportHeartBeat Verbose: 0 : c2c4f90a-8ecd-4d5e-ae98-8cd4859f7023 is dead
SignalR.Transports.TransportHeartBeat Verbose: 0 : ecb2c5ba-0a71-43e9-a3b8-744d48a7f6b1 is dead
SignalR.Transports.TransportHeartBeat Verbose: 0 : c2c4f90a-8ecd-4d5e-ae98-8cd4859f7023 is dead
SignalR.Transports.TransportHeartBeat Verbose: 0 : ecb2c5ba-0a71-43e9-a3b8-744d48a7f6b1 is dead
SignalR.Transports.TransportHeartBeat Verbose: 0 : KeepAlive(f9284f8b-f8d7-4358-9298-25f28048da62)
SignalR.Transports.TransportHeartBeat Verbose: 0 : c2c4f90a-8ecd-4d5e-ae98-8cd4859f7023 is dead
SignalR.Transports.TransportHeartBeat Verbose: 0 : ecb2c5ba-0a71-43e9-a3b8-744d48a7f6b1 is dead
SignalR.Transports.TransportHeartBeat Information: 0 : Removing connection ecb2c5ba-0a71-43e9-a3b8-744d48a7f6b1
SignalR.Transports.LongPollingTransport Information: 0 : Abort(ecb2c5ba-0a71-43e9-a3b8-744d48a7f6b1)
SignalR.Transports.TransportHeartBeat Verbose: 0 : c2c4f90a-8ecd-4d5e-ae98-8cd4859f7023 is dead
SignalR.Transports.TransportHeartBeat Verbose: 0 : KeepAlive(f9284f8b-f8d7-4358-9298-25f28048da62)
SignalR.Transports.TransportHeartBeat Verbose: 0 : c2c4f90a-8ecd-4d5e-ae98-8cd4859f7023 is dead
SignalR.Transports.LongPollingTransport Verbose: 0 : Cancel(f9284f8b-f8d7-4358-9298-25f28048da62)
SignalR.Transports.LongPollingTransport Verbose: 0 : DrainWrites(f9284f8b-f8d7-4358-9298-25f28048da62)
SignalR.Transports.LongPollingTransport Information: 0 : CompleteRequest (f9284f8b-f8d7-4358-9298-25f28048da62)

Bus log:
SignalR.ScaleoutMessageBus Information: 0 : OnReceived(0, 245, 1)
SignalR.ScaleoutMessageBus Information: 0 : Stream(0) - Changed state from Open to Closed
SignalR.ScaleoutMessageBus Information: 0 : Stream(1) - Changed state from Open to Closed
SignalR.ScaleoutMessageBus Information: 0 : Stream(2) - Changed state from Open to Closed
SignalR.ServiceBusMessageBus Error: 0 : OperationCanceledException was thrown in trying to receive the message from the service bus.
SignalR.ServiceBusMessageBus Error: 0 : OperationCanceledException was thrown in trying to receive the message from the service bus.
SignalR.ServiceBusMessageBus Error: 0 : OperationCanceledException was thrown in trying to receive the message from the service bus.

**Comment by mikhailshilkov** [comment]
@josh-ak Were you able to fix/workaround this issue? I'm having similar problems...

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
