### ISSUE TITLE
signalr self hosted authentication

### ISSUE THREAD

**Issue by parhamparsa** [SignalR/SignalR#3492]
I write a chat room with signalr, i have a console application as server and asp.net mvc as client of it. I need to have authentication to the program, when the user login from mvc client, the server cant recognize the user and Context.User is always null What can i do to fix that problem

my Startup class on server

class Startup
{
    public void Configuration(IAppBuilder app)
    {
        app.UseCors(CorsOptions.AllowAll);
        app.MapSignalR();
    }
 }
My Hub on server

public class MyHub : Hub
{
    public void Send(string name, string message)
    {
        Clients.All.addMessage(name, message);
    }

```
public override Task OnConnected()
{
     var user =Context.User.Identity.Name;
}
```

}
My Login in mvc client

```
public ActionResult Login()
{
    return View();
}

[HttpPost]
public ActionResult Login(User model)
{
    if (ModelState.IsValid)
    {
        using (ChatDBEntities db = new ChatDBEntities())
        {
            string userName = model.Username;
            string pass = model.Pass;

            bool isValid = db.Users.Any(a => a.Username.ToLower() == userName.ToLower() && a.Pass.ToLower() == pass.ToLower());

            if (isValid)
            {
                FormsAuthentication.SetAuthCookie(userName, false);
                return RedirectToAction("Chat", "Home");
            }
        }
    }
    return View(model);
}
```

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
