### ISSUE TITLE
SignalR client hangs on second self-hosted instance

### ISSUE THREAD

**Issue by breyed** [SignalR/SignalR#3493]
Given a self-hosted OWIN WebApp with SignalR server, and a SignalR client connected to it, after the server and client have been started and disposed, attempting to start them a second time causes the SignalR client to hang.

Repro:

```
using Microsoft.AspNet.SignalR.Client;
using Microsoft.Owin.Hosting;
using Owin;

class Program
{
    static void Main()
    {
        Test();
        Test();
    }

    static void Test()
    {
        using (var server = WebApp.Start("http://localhost:9000/"))
        using (var hubConnection = new HubConnection("http://localhost:9000/"))
            hubConnection.Start().Wait(); // Wait never returns on the second call to Test.
    }
}

public class Startup
{
    public void Configuration(IAppBuilder app)
    {
        app.Map("/signalr", appConfig => appConfig.RunSignalR());
    }
}
```

**Comment by nickhow83** [comment]
+1 causing an issue for us here too

**Comment by IcodeNet** [comment]
we have the exact same issue as well

**Comment by andyhoyle** [comment]
This issue prevents us from testing our SignalR implementation so +1 here too!

**Comment by mistakenot** [comment]
+1 here as well.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
