### ISSUE TITLE
SignalR together with WebClient

### ISSUE THREAD

**Issue by wmmihaa** [SignalR/SignalR#3496]
I have a windows service acting as a signalR client receiving messages from a hub. While some messages are to big, I put these in blob storage (on the hub/server) and pass a smaller message to the client (aka the windows service). The client then calls a separate endpoint on the server using WebClient:DownloadDataTaskAsync to receive the larger message.

In theory all is good, although in reality it seams that when I make the download call using WebClient, SignalR drops the connection. The error message I get is:

An internal WebSocket error occurred: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. 

Any ideas?

**Comment by shrik36** [comment]
Hi,
I would have see the codes for more details but I have a suggestion for you,

If you have long messages then you can create a record of messagecontent and messageId and pass only the messageid while interacting with SignalR. This will not only solve the problem of large message but also communication will be much faster.

**Comment by wmmihaa** [comment]
Thanks for the input,
That is actually exactly what i do. However after receiving the "notification message" from the hub, the client needs to retrieve the entire message by making a REST call to the server using WebClient:DownloadDataTaskAsync method.
It's when this call is made that SignalR drops the connection.

**Comment by shrik36** [comment]
There can be many reason for connection drop, like communication problem, database, wrong syntax, parameters, etc
I would suggest you to upload exact error/exception thrown by debugger,

However you can check:
If your service is locally hosted verify the service: parameters, calling method(GET, POST,..) and response.
Try testing your service without using 'WebClient:DownloadDataTaskAsync' method.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
