### ISSUE TITLE
Interpreting Signal Client trace messages

### ISSUE THREAD

**Issue by ericrrichards** [SignalR/SignalR#3498]
I apologize if this is covered somewhere, but I haven't come across it scouring the wiki documentation.

If I look at the trace output generated by my SignalR C# client application, I see a bunch of messages like this:

    18:06:43.5313737 - 0d1149ab-0940-4265-9529-eeeae2aaeabc - WS: OnMessage({})
    18:06:53.0449824 - 0d1149ab-0940-4265-9529-eeeae2aaeabc - WS: OnMessage({"C":"d-F2FEF6FD-A,0|B,2|C,1|D,0","M":[{"H":"IpcHub","M":"GetCurrentSessionDetails","A":[]},{"H":"IpcHub","M":"AvailableExpertsCount","A":[]}]})
    18:06:53.0549905 - 0d1149ab-0940-4265-9529-eeeae2aaeabc - WS: OnMessage({"C":"d-F2FEF6FD-A,0|B,3|C,1|D,0","M":[{"H":"IpcHub","M":"GetCurrentSessionDetails","A":[]}]})
    18:06:53.0549905 - 0d1149ab-0940-4265-9529-eeeae2aaeabc - WS: OnMessage({"C":"d-F2FEF6FD-A,0|B,4|C,1|D,0","M":[{"H":"IpcHub","M":"IsExpertAvailable","A":[3]}]})
    18:06:53.1350424 - 0d1149ab-0940-4265-9529-eeeae2aaeabc - WS: OnMessage({"C":"d-F2FEF6FD-A,0|B,5|C,1|D,0","M":[{"H":"IpcHub","M":"GetWaitingSessionIds","A":[]}]})
    18:06:53.2221019 - 0d1149ab-0940-4265-9529-eeeae2aaeabc - WS: OnMessage({"I":"1"})
    18:06:53.2221019 - 0d1149ab-0940-4265-9529-eeeae2aaeabc - WS: OnMessage({"I":"0"})
    18:06:53.2221019 - 0d1149ab-0940-4265-9529-eeeae2aaeabc - WS: OnMessage({"I":"2"})
    18:06:53.2231032 - 0d1149ab-0940-4265-9529-eeeae2aaeabc - WS: OnMessage({"I":"4"})
    18:06:53.2231032 - 0d1149ab-0940-4265-9529-eeeae2aaeabc - WS: OnMessage({"C":"d-F2FEF6FD-A,0|B,6|C,1|D,0","M":[{"H":"IpcHub","M":"IsExpertAvailable","A":[8]}]})
    18:06:53.2231032 - 0d1149ab-0940-4265-9529-eeeae2aaeabc - WS: OnMessage({"I":"3"})
    18:06:53.2251046 - 0d1149ab-0940-4265-9529-eeeae2aaeabc - WS: OnMessage({"C":"d-F2FEF6FD-A,0|B,7|C,1|D,0","M":[{"H":"IpcHub","M":"GetConnectedSessionIds","A":[]}]})
    18:06:53.2281066 - 0d1149ab-0940-4265-9529-eeeae2aaeabc - WS: OnMessage({"C":"d-F2FEF6FD-A,0|B,8|C,1|D,0","M":[{"H":"IpcHub","M":"GetConnectedSessionIds","A":[]}]})
    18:06:53.2311087 - 0d1149ab-0940-4265-9529-eeeae2aaeabc - WS: OnMessage({"C":"d-F2FEF6FD-A,0|B,9|C,1|D,0","M":[{"H":"IpcHub","M":"IsExpertAvailable","A":[11]}]})
    18:06:53.2311087 - 0d1149ab-0940-4265-9529-eeeae2aaeabc - WS: OnMessage({"I":"5"})
    18:06:53.2321094 - 0d1149ab-0940-4265-9529-eeeae2aaeabc - WS: OnMessage({"I":"6"})
    18:06:53.2321094 - 0d1149ab-0940-4265-9529-eeeae2aaeabc - WS: OnMessage({"I":"7"})
    18:06:53.2341108 - 0d1149ab-0940-4265-9529-eeeae2aaeabc - WS: OnMessage({"I":"8"})
    18:06:53.2361121 - 0d1149ab-0940-4265-9529-eeeae2aaeabc - WS: OnMessage({"C":"d-F2FEF6FD-A,0|B,A|C,1|D,0","M":[{"H":"IpcHub","M":"GetConnectedSessionIds","A":[]}]})
    18:06:53.2361121 - 0d1149ab-0940-4265-9529-eeeae2aaeabc - WS: OnMessage({"I":"9"})
    18:06:53.2391139 - 0d1149ab-0940-4265-9529-eeeae2aaeabc - WS: OnMessage({"C":"d-F2FEF6FD-A,0|B,B|C,1|D,0","M":[{"H":"IpcHub","M":"GetWaitingSessionIds","A":[]}]})
    18:06:53.2391139 - 0d1149ab-0940-4265-9529-eeeae2aaeabc - WS: OnMessage({"I":"10"})
    18:06:53.2521234 - 0d1149ab-0940-4265-9529-eeeae2aaeabc - WS: OnMessage({"C":"d-F2FEF6FD-A,0|B,C|C,1|D,0","M":[{"H":"IpcHub","M":"GetAvailability","A":[]}]})
    18:06:53.2601277 - 0d1149ab-0940-4265-9529-eeeae2aaeabc - WS: OnMessage({"I":"11"})
    18:06:53.5583361 - 0d1149ab-0940-4265-9529-eeeae2aaeabc - WS: OnMessage({})

What do the components of these messages mean?  I can understand most of it, it appears to be output like:

    [TIMESTAMP] - [CONNECTIONID] - [TRANSPORT]: OnMessage({...})

Within the OnMessage portion, it looks like "H" is the name of the Hub, "M" is the name of the client method, and "A" is the parameters to the client method.

What are the "C" & "I" values here?

**Comment by moozzyk** [comment]
[Here](http://blog.3d-logic.com/2015/03/29/signalr-on-the-wire-an-informal-description-of-the-signalr-protocol/) is a blog post I wrote that describes the protocol SignalR is using.

**Comment by ericrrichards** [comment]
Thanks!
