### ISSUE TITLE
Application stuck due to signalR when laptop wake up from hibernation.

### ISSUE THREAD

**Issue by vishalchaudhary874** [SignalR/SignalR#3501]
I have a requirement for running my web application on laptop. My application uses SignalR for two way communication. On server where we do not hibernate Web application works perfectly. On laptop I have to handle case like hibernate, sleep.
On window 7 laptop i have IIS 7.5. I have deployed my web application on this IIS. My web application works perfectly on laptop also. Now if i hibernate my laptop and than resume laptop. My application stops working. 

On IIS i can find signalR request pending from long time.

![image](https://cloud.githubusercontent.com/assets/11922806/8051610/425c04bc-0e9c-11e5-9ea5-42145f0dc293.png)

In browser console i got errors like

![image](https://cloud.githubusercontent.com/assets/11922806/8051620/6755fb74-0e9c-11e5-9daf-829232246749.png)

![image](https://cloud.githubusercontent.com/assets/11922806/8051622/6e4dc51a-0e9c-11e5-97eb-0b9c5844c319.png)

I have tried multiple settings on IIS that can resolve this issue. I have also upgarded signal r to latest 2.2 version. From javascipt i have added error handler as below

$.connection.hub.error(function () {
                   console.log("Received Exception");
           $.connection.hub.start();
                   $.connection.hub.stop();
        });

this handler executed multiple time on laptop resume from hibernate mode but issue remains.

If I remove signalr from my application than I do not get these issues. Application works perfectly .

Is there any way i can solve this issue.

Thanks for Understanding this issue.

**Comment by gabrieligbastos** [comment]
+1

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
