### ISSUE TITLE
Connection started but client events not called with websockets

### ISSUE THREAD

**Issue by sav931** [SignalR/SignalR#3502]
Hi,
I'm using windows server 2012 and activated websockets on it.
When signalr use websockets,  the connection is successfully started but no event in client side are called, only if I force signalr to connect with long polling....

Any suggestion ?

**Comment by evaldosantos** [comment]
Is there any update about this issue? Seems I have the same problem...

I'm consuming a service using signalr 2.2. All was working well using long polling. However since my service started to use websockets the hub events are inconsistent triggered. Sometimes work, sometimes not. I tried several approaches in order to get the code working as was using long polling but without success.

Sorry, english isn't my first language.

**Comment by glittle** [comment]
Similar problem... was working well until I enabled websockets. Now the frames from the server have no data in them. Does server logic have to change if websockets are in use?

**Comment by glittle** [comment]
Issue resolved... my client code, originally from signalR 0.5.2 days, was getting the connection id in the hub.done() function with `var id = this.id;`.  Changed to use `var id = $.connection.hub.id;`.  I use the ID later... and it was undefined.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Comment by amandhamija98** [comment]
Hi, I am facing this issue. I am using signalr2 with mvc5. After enabling hub logging, I can see that a client method is getting triggered, but the code never enters that method. This is the message on my console: Triggering client hub event 'receiveNewIceCandidate' on hub 'VideoCallHub'
but receiveNewIceCandidate method is never actually called

**Comment by Pedromiller** [comment]
Any solution for this issue? I'm having the same trouble with signalR 3.1.15
