### ISSUE TITLE
Raise an OnError and/or allow setting a ServiceBusRetries property when failing to push a message into Azure Service Bus

### ISSUE THREAD

**Issue by oferze** [SignalR/SignalR#3503]
There's an outstanding Azure issue where the Service Bus backplane randomly fails getting items pushed by SignalR. The problem is that these messages are pushed using a `Task` and the failures bubble up violently as a generic uncaught Task exception.

Please catch these `Task` errors internally, expose & raise an event that the host code can intercept.

Alternatively (or better - in addition) could you please implement a retry mechanism (I'm not referring to client disconnections, but to Azure Service Bus failures) and expose something like a `ServiceBusRetries` property in `GlobalHost.DependencyResolver.UseServiceBus(...)`.

**Comment by davidfowl** [comment]
Why aren't you observing the task?

**Comment by oferze** [comment]
Because it's too "late" and too generic. I'm also not sure we can detect what was the exact message at that time.

I was hoping to have at least a proper retry mechanism within SignalR (as these Azure failures appear very often).

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
