### ISSUE TITLE
Error during negotiation request.

### ISSUE THREAD

**Issue by niemyjski** [SignalR/SignalR#3506]
About 2 weeks ago our [JavaScript error client](https://github.com/exceptionless/Exceptionless.JavaScript) started logging this error (no stack trace available) via the [error handler callback](https://github.com/exceptionless/Exceptionless.UI/blob/master/src/components/signalr/signalr-service.js#L64-L68). We are using the latest client and server versions of SignalR.

![image](https://cloud.githubusercontent.com/assets/1020579/8263990/6d3e1e88-16a6-11e5-9684-7815703e71ca.png)

We currently have over 14k of these errors and all of them seem to be IE11. We haven't changed anything with this in the past few months...

![image](https://cloud.githubusercontent.com/assets/1020579/8264003/8c6bf1b8-16a6-11e5-890e-ea8db8fef8a7.png)

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
