### ISSUE TITLE
Websocket is not connected when Adding Backplane Code in SignalR

### ISSUE THREAD

**Issue by DevFB** [SignalR/SignalR#3509]
//string sqlConnectionString = ConfigurationManager.AppSettings["ConnectionString"].ToString();
//GlobalHost.DependencyResolver.UseSqlServer(sqlConnectionString);
app.MapSignalR();

Websocket is not connected when I uncomment above two lines means its using SignalR backplane.
Btw, I am able to use SQL backplane with Long Polling and SSE however I wanted to use Websocket with Backplance.

It works only when Backplane is down.

Following is the trace

[16:11:14 GMT+7] SignalR: webSockets transport starting.
jquery.signalR-2.2.0.min.js:8 [16:11:14 GMT+7] SignalR: Connecting to websocket endpoint 'ws://ec2-52-xx-15x-12x.ap-southeast-1.compute.amazonaws.com/signalr/connect?transport=webSockets&clientProtocol=1.5&connectionToken=duU6zqNyYVJ71TJhN773k3vA4SCduFfsH4Zj8MOUeqD6P%2BtvOURy8up%2Blmh3LdnFkav%2BZ%2BxLdPSXotrBNAzQfg5zmlRH1p9r9Ss5mTjMYdarDGRs&connectionData=%5B%7B%22name%22%3A%22hub%22%7D%5D&tid=7'.
jquery.signalR-2.2.0.min.js:8 [16:11:18 GMT+7] SignalR: Websocket opened.
jquery.signalR-2.2.0.min.js:8 [16:11:18 GMT+7] SignalR: Unclean disconnect from websocket: [no reason given].
jquery.signalR-2.2.0.min.js:8 [16:11:18 GMT+7] SignalR: Closing the Websocket.
jquery.signalR-2.2.0.min.js:8 [16:11:18 GMT+7] SignalR: webSockets transport failed to connect. Attempting to fall back.
jquery.signalR-2.2.0.min.js:8 [16:11:18 GMT+7] SignalR: serverSentEvents transport starting.

I have gone through numbers of suggestions, links, work around suggested by community, however none seems to work.

Actually the original problem was my SignalR connection was taking too much time to connect, then to troubleshoot(TS) that, I found social media is taking too long to establish and that was causing SignalR to connect for Long, then I remove those social media to TS further, then I found my client is trying to connect Websocket first but its not getting connected so its then switching to next available Protocol, then I started to look for why Websocket is not getting connected in my AWS Load Balancing environment.

So coming short, now I conclude my Web socket is getting connected only when I disable backplane as per the above code but that doesn't resolve my problem.

My server is properly configured with all required settings as I am able to connect with Websocket with My app(without backplane) as well as the Chat APP that is available for SignalR demo.

**Comment by lucasmarzetti** [comment]
Hi, I have the same issue. SignalR stops working when the backplane is enabled. I'm my case, the backplane is Redis but I'm having exactly the same behavior than you. Did you figure out this?

Thanks

**Comment by moozzyk** [comment]
Is it just the first websocket or any websocket? What can happen is that on the first request warming up things takes a while and the connection attempt times out. Then the client falls back to using a different transport and now that things warmed up they are able to connect. You could verify this by trying starting another (websocket) connection/client after the first connection has been successfully established.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
