### ISSUE TITLE
How to scaleout SignalR using Redis backplane without Redis script?

### ISSUE THREAD

**Issue by jiangshilin** [SignalR/SignalR#3510]
My webapp use Redis backplane to scaleout SignalR, but my IAAS provider's Redis service does not support script for now.

I have read the source and find out that Microsoft.AspNet.SignalR.Redis use StackExchange.Redis.IDatabaseAsync.ScriptEvaluateAsync to publish message.

I have tried following way to modify the source, but all won't work.
1. Switch script to step operations, Publish & Subscribe message with json serializion. It will serialize and deserialize correctly, but client still connect fail.
2. Switch script to step operations,  try to serialize message to original format, but does not know how to encode.

Please help me to find a corret way, thanks.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
