### ISSUE TITLE
SingalR performance counters with Azure SDK 2.6

### ISSUE THREAD

**Issue by ghost** [SignalR/SignalR#3511]
There is a good article explaining how to enable SignalR performance counters on Azure web roles:

[Using SignalR Performance Counters in an Azure Web Role](http://www.asp.net/signalr/overview/performance/using-signalr-performance-counters-in-an-azure-web-role)

However, in Azure SDK 2.6 diagnostics through code is entirely deprecated (SignalRDiagnosticHelper class) and everything must be configured in xml file diagnostics.wadcfgx.

Does it mean that it is enough simply to move definitions of performance counters to the xml configuration file? If so, how should we be with dynamic category names? Or can this still lead to troubles due to diagnostics monitor starting before the role starts?

P.S. It would be also nice to have the asp.net article updated with the latest SDK 2.6 changes.

**Comment by kirthiroyadu** [comment]
Any changes/updates to this? The article still uses the deprecated code.

**Comment by anurse** [comment]
I did some reviewing of the doc. It's quite out of date. I can assemble an outline for building a new one. The dynamic category names are a small problem, but you can register for all of instances of the SignalR counters by using `\SignalR(*)\[Counter Name]` as the path. For example `\SignalR(*)\Connections Current`.

/cc @muratg @moozzyk

**Comment by anurse** [comment]
I confirmed that if you move the Performance Counters to the xml file and use `\SignalR(*)\[SignalR Counter Name]` as the path, it does work.

**Comment by anurse** [comment]
Logged a bug to fix the doc: https://github.com/aspnet/Docs/issues/2636
