### ISSUE TITLE
GetHubContext should preserve Strongly-Typed Hubs

### ISSUE THREAD

**Issue by Genae** [SignalR/SignalR#3512]
GetHubContext() always gives me an untyped Hub:
<pre>
    public class LogHub : Hub&lt;ILogClient&gt;
    {
        public void SendMessage(string msg)
        {
            Clients.All.addNewMessage("this uses ILogClient :)");
        }
        public override Task OnConnected()
        {
            MyLogger.SendLastLogs();
            return base.OnConnected();
        }
    }

    public class MyLogger
    {
        public static void SendLastLogs()
        {
            var context = GlobalHost.ConnectionManager.GetHubContext&lt;LogHub&gt;();
            context.Clients.All.addNewMessage("this uses dynamic :(");
        }
    }

    public interface ILogClient
    {
        void addNewMessage(string msg);
    }
</pre>

**Comment by stto3703** [comment]
You can get the hub context by specifying also the client type:
```
var context = GlobalHost.ConnectionManager.GetHubContext<LogHub, ILogClient>();
```
Then you have strong typing.

**Comment by davidfowl** [comment]
@stto3703 yep :smile:
