### ISSUE TITLE
ping requests never timeout, fill browser domain connection queue  - websocket transport

### ISSUE THREAD

**Issue by mikemwalsh** [SignalR/SignalR#3514]
Signalr js client v 2.1.2
Signalr asp.net server v 2.2.0

After having known issues on our network cropped up recently (dropped packets at firewall), where the javascript client is located, we are running in to an interesting issue.  It would appear that at times the signalr ping can get in to a state where it never times out.

![stuckping](https://cloud.githubusercontent.com/assets/2761579/8598909/7c299140-262b-11e5-8cef-01d14062eef7.png)

as per the screenshot, this is after 12.25 hours of connectivity, the next ping, and all subsequent pings got to this state.  I am not 100% sure this is related to $.ajax timeouts, but it is pointing in that direction.  

This is a huge issue as it clogs the browser pre domain limit queue.  This is running in mobile safari, wrapped in cordova, on ios.  Once in this state the app is broken, all ajax calls fail as they get stuck at the end of the browser per domain queue.

My understanding is that safari/mobileSafari does not put a timeout on ajax connection, it defaults to never time out.  I have not yet found a way to set this timeout so the signalr library uses it.  I have tried setting $.ajaxSetting({timeout: 40000}), on the window object, for a 40 second timeout, but it does not seem to take.

The rest of out app's ajax calls locally set the timeout to 40000 on each call, not through ajaxSetup

What is the recommended approach - should this not be handled internally to signal r, based on the already configured transport timeouts, setting it to a sane timeout based on the connection timeouts or anather parameter?  Furthermore, should signalr not keep a reference to a ping and cancel previous pings before initiating a new one?

Let me know if I missed anything in my setup - perhaps this is something that I can configure better?

**Comment by mikemwalsh** [comment]
As a follow up, we have discovered we can set $.signalr.ajaxDefaults.timeout = 40000 and force a 40 second timeout.  I am not sure if this is suggested or supported.  What is the reason that timeouts are defaulted to null in ajaxDefaults and not the setting from #.ajax or a sane default?  Is it to allow the browser to specify the default timeout?  Again, if that is the case, I raise the issue of safari taking null as 'never time out'.  Im trying to dig through old issues/code to figure out why it was implemented this way but I don't get it yet.  

Any reply would be helpful.

**Comment by mikemwalsh** [comment]
We have tested with $.signalr.ajaxDefaults.timeout = 40000 for several days and the weekend, it appears to resolve the issue.

On the bug fixed clients, across 3 connected devices we only saw 5 pings that failed in a 12 hour period.  On the 3 clients that do not have the timeout set, some how 1/3 clients got enough failed pings to clog the browser queue (5+).  I still have no idea what could be causing the pings to get stuck and never time out, but it is happening.

The timeout resolves it but I still don't understand the root cause.

**Comment by mikemwalsh** [comment]
Does anyone else have any thoughts on this?  Seems to me like a serious issue for anyone using ios/safari.  I have a local workaround, so if no-one wants to discuss this we can close it - but I am interested in some input on how this should work.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
