### ISSUE TITLE
Number of threads goes crazzy on embedded windows 7

### ISSUE THREAD

**Issue by BernardWielfaert** [SignalR/SignalR#3515]
Hi,

We have a SignalR implementation with client -> hub communication between 2 c# applications on an embedded Windows system and after a while running on the sending client the amount of threads increases till Windows stops (>1000). Any idea where the problem would lay ?

Regards,
Bernard

**Comment by BernardWielfaert** [comment]
Strange the thread accumulation starts after the hub can't be reached anymore for a number of seconds(proved by failing ping)

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
