### ISSUE TITLE
Objective-c/swift client

### ISSUE THREAD

**Issue by rajeshaz09** [SignalR/SignalR#3518]
Right now i am evaluating SignalR for my product. 
When we can i expect Swift/Objective-C client for SignalR from ASP.NET team?

**Comment by rajeshaz09** [comment]
SignalR is very good technology.  Most of the enterprises now want mobility solutions (Apps). Their first priority is IOS. 
Since, there is no official client for ios/osx from ASP.NET team, this technology is useless.

**Comment by rajeshaz09** [comment]
Other community driven libraries are not stable (SigalR-Objc).

**Comment by davidfowl** [comment]
You can check this out https://github.com/adamhartford/SwiftR. We dont' have any plans to do a swift client in the near term.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
