### ISSUE TITLE
[Question] How to customize our own "scale out" components with SignalR？

### ISSUE THREAD

**Issue by ghost** [SignalR/SignalR#3519]
Helo all:

In Microsoft's website, we can scale out in SignalR with MSSQL, Redis and ServiceBus (Azure) [for more, plz see:http://www.asp.net/signalr/overview/performance/scaleout-in-signalr ]. So how to customize our own components with SignalR (e.g: I'd like to do this with Oracle, but plz don't give me Oracle example only, I need the thoughts——How to do with that, are there any abstract classes or interfaces that I must implement to make SignalR work with our own "scale out" things?)

If we don't have such components, would you mind adding them so as to let us "customize" easily? In my mind, There should be something abstract template or interfaces that we can directly inherit from or implement our own logic (saving/loading) codes to work with SignalR;)

PS: I'm not sure whether SignalR has such functions or not, so my title is something questionable. If you think the title isn't suitable but a suggestion, you can change it;)

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
