### ISSUE TITLE
.Net client not reconnecting and threads issue

### ISSUE THREAD

**Issue by BernardWielfaert** [SignalR/SignalR#3520]
We use SignalR in a .net client server implementation. After the server gets disconnected I do not get the reconnect event and so the client never connects again. I have a fairly basic implementation of client and server. Strange when the amount of threads used by the client seems to rise by 1/second until maximum. It runs on Windows 7 embedded (client) and Windows 7 ulitimate (server).

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
