### ISSUE TITLE
[Question] How do I correctly initialize SignalR in a unit testing environment?

### ISSUE THREAD

**Issue by nparrish** [SignalR/SignalR#3522]
I have an OWIN server to which I have added a SignalR Hub.  I test my web API using Xunit by creating TestServers:

``` cs
using (var testServer = TestServer.Create<Startup.Startup>())
{
...
}
```

To test the SignalR functionality, it seems I need a URL, so I create the test web server as follows:

``` cs
using (var testServer = WebApp.Start<Startup.Startup>("http://localhost:8675"))
{
...
}
```

Then I use the SignalR .NET Client to create a HubConnection, register for callbacks, etc.  This works fine if I run my tests one at a time.  When running all tests in the project, however, the HubConnection fails to start.

I can alleviate that problem by providing my own DependencyResolver to app.MapSignalR (why?):

``` cs
s_dependencyResolver = new SimpleInjectorSignalRDependencyResolver();
app.MapSignalR(new HubConfiguration { Resolver = s_dependencyResolver });
```

but now no events are received by the client.  Any suggestions?

**Comment by lavahot** [comment]
I would suggest looking at some of the tests in the [tests](https://github.com/SignalR/SignalR/tree/master/tests) directory. Specifically the tests in the Common namespace might help you. And If you haven't already, read [this tutorial](http://www.asp.net/signalr/overview/testing-and-debugging/unit-testing-signalr-applications) on unit testing with SignalR.

**Comment by pms1969** [comment]
+1 for this problem.  Admittedly, it's more of an integration set of tests, but the problem persists.  1 test on it's own works fine, 2 or more tests fail.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
