### ISSUE TITLE
Typescript Definition for 2.2

### ISSUE THREAD

**Issue by maverix** [SignalR/SignalR#3523]
Hi All,

I just got the latest version of the signalr type definition from the Definitely Typed project.
They are quite behind and only have a definition file for signalr 1.0.

Does anyone have a newer version (2.2 ideally)?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
