### ISSUE TITLE
Unable to get property 'json' of undefined or null reference

### ISSUE THREAD

**Issue by Meadock** [SignalR/SignalR#3524]
Hello. I've been working with SignalR for over a year now. Right now I'm implementing handlers for the different connection scenarios my application could face. The one I'm having difficulty with is a server restart after a full disconnect. Here's the scenario: The server shuts down, the reconnect timeout (30 seconds) passes, the client is disconnected, the server starts back up, the client connects, the client calls a hub function, and then I get the following error in signalR.transports.foreverFrame.receive: "Unable to get property 'json' of undefined or null reference" on the following line of code: "if (connection.json !== connection._originalJson) {". connection is undefined. Is this a bug or am I not doing something right?

line number is 2159
file is jquery.signalR-2.2.0.js 

These seem similar to my issue:
https://github.com/SignalR/SignalR/issues/1275
https://github.com/SignalR/SignalR/issues/3362

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
