### ISSUE TITLE
SignalR client for IoT device

### ISSUE THREAD

**Issue by grahamehorner** [SignalR/SignalR#3525]
Please consider building additional SignalR clients for Arduino style IoT devices.

**Comment by lavahot** [comment]
I agree. This would be nice.

**Comment by piolo94** [comment]
I've read that now SignalR has a little support for bare socket connection. It worths a try, maybe in these days I can work on little wrapper for arduino.

**Comment by moozzyk** [comment]
[Asp.NET Core SignalR](https://github.com/aspnet/SignalR) makes it possible to connect to the server using bare websockets. Here is a post showing this: https://blog.3d-logic.com/2017/01/15/signalr-core-part-23-asp-net-sockets/. Currently there are no plans to create SignalR 2.x clients for IoT.

**Comment by piolo94** [comment]
The moment I posted my answer I've seen this article. LOL
