### ISSUE TITLE
How to connect signalR hub to internet enabled system ?

### ISSUE THREAD

**Issue by amangautam15** [SignalR/SignalR#3526]
I created a server having signalR hub and a client. both are windows applications.
I want to connect my signalR hub to my organization server's IP address. But when i start the connection its throwing the exception 
signalr exception
![signalr exception](https://cloud.githubusercontent.com/assets/13640135/9058319/d36bcada-3abd-11e5-9be2-a5674630670e.jpg)

please help me urgently. How to connect the signalR hub on an internet enabled system ? 
Thanks!

**Comment by lavahot** [comment]
Could you post some code so we can get a little more information? Maybe around where the exception is thrown?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
