### ISSUE TITLE
Is it possible to implement signalr server using other languages?

### ISSUE THREAD

**Issue by javagg** [SignalR/SignalR#3528]
SignalR is wonderful solution for real-time communication in web application. I've seen a few clients components written in other languages like c++, java, objc. But it seems there is only one server implementation using c#. I wonder if there are some technical issues make other languages implementation impossible. if so, could signalr protocol be improved to make this easy to do?

**Comment by davidfowl** [comment]
Clients are easy to implement, server aren't as easy. There are a bunch more touch points on the server side including the scale out, the message bus implementation, transport implementation etc.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
