### ISSUE TITLE
SignalR doesn't plays well with .net Native on Windows 10

### ISSUE THREAD

**Issue by maddentist** [SignalR/SignalR#3529]
I have made a windows store app which makes use of signalR.
It works very well in Debug mode. However, it doesn't work when compiled in Release mode which makes use of the .net native compiler (App is developed in C#). It appears that a PlatformNotSupported Exception is raised. Same appears if .net native compilation is chosen for Debug and the app works ok in Release when .net native is not used. This happen in x86, ARM and x64 modes.

This is what VS shows while running
Exception thrown: 'System.PlatformNotSupportedException' in Microsoft.AspNet.SignalR.Client.dll

And while Compiling with .NET native with static .net analysis enabled (path and file have been replaced by ... to enhance readbility)
1>  Checking assembly ...\obj\x64\Release\ilc\in\Microsoft.AspNet.SignalR.Client.dll'. 
1>...\Microsoft.AspNet.SignalR.Client : Gatekeeper warning GK0004: GK0004 Method 'System.Void System.Threading.Thread.CurrentCulture.set(System.Globalization.CultureInfo)' is not yet implemented.
1>...\Microsoft.AspNet.SignalR.Client : Gatekeeper warning GK0004: GK0004 Method 'System.Void System.Threading.Thread.CurrentUICulture.set(System.Globalization.CultureInfo)' is not yet implemented.
1>...\Microsoft.AspNet.SignalR.Client : Gatekeeper warning GK0004: GK0004 Method 'System.IAsyncResult System.IO.Stream.BeginWrite(System.Byte[], System.Int32, System.Int32, System.AsyncCallback, System.Object)' is not yet implemented.
1>...\Microsoft.AspNet.SignalR.Client : Gatekeeper warning GK0004: GK0004 Method 'System.Void System.IO.Stream.EndWrite(System.IAsyncResult)' is not yet implemented.
1>  Checking assembly ...\obj\x64\Release\ilc\in\Microsoft.AspNet.SignalR.Client.Store.dll'. 

Hope this helps and hope to have this bug ironed out soon. Keep up the good work, SignalR rocks.

**Comment by ilkayilknur** [comment]
Any updates for this issue ? This is a blocking issue for UWP Apps. We cannot submit apps to the store because of this issue.

**Comment by moozzyk** [comment]
Fixed in 4a46099e9323d3be250bc1f013421ffd10a96397 9e5449bdff81b9f85a9605739651db5d14234c5f be8a4ed8238ec8f5f08fd5fb04a14e35d7ad4145 edeacf4cbadffda58e65452687b793b4a1fea9f5
