### ISSUE TITLE
SignalR /negotiate useless redirect on access denied.

### ISSUE THREAD

**Issue by MosheL** [SignalR/SignalR#3530]
When I am using  `AuthorizeRequest` and return `false`, I see in Fiddler that  SignalR responded with `302 Redirect` to form authentication URL.
This is useless, as  the request started by `AJAX` and the cliend can do nothing with this page (HTML).

I think that the  `/negotitate` need to respond with 403, and client need to check what to do (reconnect, redirect, show Login window or similar).

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
