### ISSUE TITLE
Multiple activators for type Microsoft.AspNet.SignalR.Infrastructure.IProtectedData are registered.

### ISSUE THREAD

**Issue by Ingvanegas** [SignalR/SignalR#3531]
after a certain time when trying to send a message that exception occurs

IHubContext hubContext = GlobalHost.ConnectionManager.GetHubContext<MyHub>();
hubContext.Clients.All.addMessage(name, Mensaje);

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
