### ISSUE TITLE
Inconsistent API (Sync/Async)

### ISSUE THREAD

**Issue by breyed** [SignalR/SignalR#3532]
$.hubConnection(...).createHubProxy(...).invoke(...).fail(...) can be called synchronously or asynchronously depending on when a failure is detected. This duality means that using `fail` in Angular requires an extra wrapper to force the callback to always be async.

See [Inconsistent API (Sync/Async)](https://github.com/SignalR/SignalR/issues/new) in the Angular JS documentation.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
