### ISSUE TITLE
Self hosting: socket leak (Mono) 

### ISSUE THREAD

**Issue by vuicich** [SignalR/SignalR#3533]
I use SignalR 2.2.0 self-hosting applicationon (JS-client, long-polling transport, CORS) on Mono (Mono 4.0.3, Ubuntu 14.04).

After js-client disconnecting (page reload/unload, or explicit $.connection.hub.stop()) I see that SignalR process does not free sockets to OS. I see lost socket file descriptors using lsof command from Shell:

$ lsof -p {process PID}
...
mono 33740 root 7u sock 0,7 0t0 108928 can't identify protocol
mono 33740 root 8u sock 0,7 0t0 109271 can't identify protocol
mono 33740 root 9u sock 0,7 0t0 109300 can't identify protocol
...
Number of lost descriptors increments after every client disconnection. If I see more then 1000 socket descriptors in my production server I see fatal System.IO.IOException: Too many open files. And after this clients couldn't connect to the server.
Problem doesn't reproduced for ServerSentEvents (SSE) transport.

I found reproduction case under Mono (version 3.10.0) from your documentation sample: http://www.asp.net/signalr/overview/deployment/tutorial-signalr-self-host. Complete example can be downloaded here: https://code.msdn.microsoft.com/SignalR-Self-Host-Sample-6da0f383.
Also it is important to set LongPolling transport explicitly:

...
$.connection.hub.start({
transport: ['longPolling', 'foreverFrame', 'serverSentEvents']
}).done(function () {
...

**Comment by paralin** [comment]
I might have the same issue in prod, can someone look at this?

**Comment by davidfowl** [comment]
We don't support mono in production.

**Comment by paralin** [comment]
@davidfowl Doesn't make too much sense as MS is moving towards open-source C# at the moment and a large amount of production is done in Linux these days

**Comment by davidfowl** [comment]
Doesn't change the fact that our supported cross platform story is core clr, not mono. On top of that, signalr 3.0 will run on core clr not the current 2.x

**Comment by paralin** [comment]
I see, thanks! Makes sense.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
