### ISSUE TITLE
Feature: Call hub method only after connection is established

### ISSUE THREAD

**Issue by mcctomsk** [SignalR/SignalR#3542]
My application is working under a fucked-up corporate network (proxies and stuff), so I have to use long polling and experience disconnects all the time. My major issue is that I can not force a connection to be established before a hub method is called.

Here is a mess I use as a workaround:
1.  Restart hub after disconnect

```
$.connection.hub.disconnected(function() {
    console.log('Disconnected');

    setTimeout(function() {
        $.connection.hub.start({ transport: ['webSockets', 'longPolling'] });
    }, 5000); // Restart connection after 5 seconds.

    $.connection.hub.start({ transport: ['webSockets', 'longPolling'] }).done(function() {
        modemsHub.server.watchClinic('@ViewBag.Clinic.Id');

        console.log('Started');
    }).fail(function() {
        console.log('Failed to Start');
    });
});
```
1.  Wrap hub methods calls into the following structure:

```
if ($.connection.hub && $.connection.hub.state === $.signalR.connectionState.connected) {
  modemsHub.server.myHubMethod();
} else {
  $.connection.hub.start({ transport: ['longPolling'] }).done(function() {
    modemsHub.server.myHubMethod();
  });
```

I'm not quite sure what happens if points 1 and 2 try to restart a hub at the same time.

Doesn't it make sense to have something like that as part of SignalR?

**Comment by shyamal890** [comment]
+1 I just raised a similar [REQUEST](http://stackoverflow.com/questions/35031570/signalr-wait-for-connection-to-be-re-established-before-invoking-methods) on stackoverflow.

I would be great if SignalR could have something like 
```javascript
proxy.invoke('dataToServer',someModel).WaitForSignalRToBeConnected();
```

@halter73 @davidfowl  can you please have a look.

**Comment by halter73** [comment]
@mcctomsk Your workaround should actually be pretty safe. The second call to start on the SignalR client, will simply return the promise from the first call.

So if the client is in the "connecting" state during the second call to start, the done callback won't be triggered until you reach the "connected" state.

**Comment by shyamal890** [comment]
@halter73 Is there a way to for methods invoked from client to wait till signalr is connected? 

http://stackoverflow.com/questions/35031570/signalr-wait-for-connection-to-be-re-established-before-invoking-methods

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
