### ISSUE TITLE
GlobalHost.ConnectionManager.GetHubContext with multiple worker processes in ApplicationPool on IIS 8.5

### ISSUE THREAD

**Issue by CUCO-Ultimate** [SignalR/SignalR#3544]
Hey guys,

there is an issue when you work with multiple worker processes in an ApplicationPool with IIS 8.5.

I try to access the HubContext via 

```
Dim MyHubContext As IHubContext = GlobalHost.ConnectionManager.GetHubContext("MyHub")
MyHubContext.Clients.All.DoSomeShit("SomeMessage")
```

or 

```
Dim MyHubContext As IHubContext = GlobalHost.ConnectionManager.GetHubContext(Of MyHub)
MyHubContext.Clients.All.DoSomeShit("SomeMessage")
```

If i have multiple wokers in my ApplicationPool in my IIS 8.5 sometimes some requests (picked up by another worker) wont send anything, which is coused by no clients in the list.

If i have only one worker in my ApplicationPool in my IIS 8.5 everything works fine.

**Comment by chbomtempo** [comment]
Maybe you need to use some kind of backplane: http://www.asp.net/signalr/overview/performance

**Comment by S3NS4Ti0N** [comment]
I am not using multiple server's. Then it's clear to use a backplane. I am using one server, with just multiple workers. I think there should be some kind of process pipeline communication.

**Comment by michaeltheyeti** [comment]
This is also happening to me.  I have a static method that is called by a worker process.  The redis backplane appears to not be picking up the message when sent via the globalhost

This is the method from my hub class:
```
//Here is the hub for the static call, and yes it is strongly typed
public static IHubContext<ICentralHub> CentralHubContext
{
       get
       {
                return GlobalHost.ConnectionManager.GetHubContext<CentralHub, ICentralHub>();
       }
}
       
internal static async Task SendConnectedUsers(IList<SignalRClient> users)
{
       await CentralHubContext.Clients.All.SendConnectedUsers(users);
}
```
Thoughts?

**Comment by S3NS4Ti0N** [comment]
Still no progress here ?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
