### ISSUE TITLE
Windows Azure deployment - not loads file or assembly Newtonsoft.Json

### ISSUE THREAD

**Issue by sanooptharavattath** [SignalR/SignalR#3545]
I created MVC 4 application with Web API. It works good in local environment. When I deployed it to Azure, it gives following error.

Exception information: Exception type: HttpException Exception message: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) at System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) at System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) at System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) at System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) at System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter..ctor() at System.Net.Http.Formatting.JsonMediaTypeFormatter..ctor() at System.Net.Http.Formatting.MediaTypeFormatterCollection.CreateDefaultFormatters() at System.Web.Http.HttpConfiguration.DefaultFormatters(HttpConfiguration config) at System.Web.Http.HttpConfiguration..ctor(HttpRouteCollection routes) at System.Web.Http.GlobalConfiguration.b__0() at System.Lazy1.CreateValue() at System.Lazy1.LazyInitValue() at System.Lazy1.get_Value() at System.Web.Http.GlobalConfiguration.get_Configuration() at System.Web.Http.GlobalConfiguration.Configure(Action1 configurationCallback) at Activity.Web.Monitor.UI.MvcApplication.Application_Start()

Any idea how to resolve this?

**Comment by King-G** [comment]
Make sure every project in your assembly targets the right .Net Framework.
The reason you get this is because it just can't find newtonsoft.json. Go
to your project, go to references and then to the properties of
Newtonsoft.json and put Copy Local = true.
This way when you deploy your project it creats the Newtonsoft BLL and
deploys it with it.
Try that?

2015-09-07 23:04 GMT+02:00 sanooptharavattath <notifications@github.com>:

**Comment by sanooptharavattath** [comment]
Thanks. I reinstalled and created a new deployment structure in Azure. It worked.
Once again thanks for your time and support.

**Comment by King-G** [comment]
You're welcome ;)
