### ISSUE TITLE
SignalR Scaleout Bug. Messages that require ACK times out.

### ISSUE THREAD

**Issue by MikaelGRA** [SignalR/SignalR#3549]
I have discovered something which I am 99% certain MUST be a bug in the Scaleout implementation of SignalR.

I have a setup where I am using SignalR 2.2 and Scaleout using Redis.

The setup involves two different kinds of (signalr server) applications:
- One, which is primarily a producer of messages
- Another, which is primarily consumer of messages (in the sense that clients subscribes to this application!)

The producing applications produces a LOT of messages that the client applications can consume. We're talking in the range of more than a 1000000 per day.

And this brings me to my issue.

I am experiencing the following scenario:
- I have the producing and consuming application running for more than 1 day without actually using the consuming application.
- After having done this, all calls from the the consuming application to methods such as 'Groups.Add' and 'Groups.Remove' starts timing out. (methods that require an Ack (I looked at the source code for signalr))
- These methods will keep hanging until I restart the consuming application, at which point, they will start working again... until another day has passed where the consuming application has not been used and another ~1000000 messages has been sent.

Now, this sounds odd to me, and frankly, is fairly difficult to reproduce without having a larger setup. As such, I have included a solution, which produces the same issue, but in a much simpler way. In this setup, I have a method on a hub which sends ~1000000 messages to some non-existing group and then attempts to join another group. The call to 'Groups.Add' will fail single every time.

Now, I say ~1000000 messages, but in fact, it is 1015808 messages that causes the issue (this is the amount of entries available in the ringbuffer in the ScaleoutStore in Signalr for a 64-bit architecture, which I am running). If I decease the number of messages sent by 3 (don't ask me why exactly 3), then the call to 'Groups.Add' will SUCCEED every single time.

In order to run the repro code, you must provide your own redis store. I am currently using a Azure Redis Cache scaled to S1.

``` code
   public class Startup
   {
      public void Configuration( IAppBuilder app )
      {
         app.MapSignalR();
         GlobalHost.DependencyResolver.UseRedis( "[provide hostname]", 6379, "[provide key]", "testkey" );
      }
   }
```

Once you run the repro project, simply open up the "Home/Index" page of the web application and click the "SendAlotThenJoin" button once. Then wait for the server method for complete (it never will). The application will trace out the number of messages has been sent during the operation, so you can get a rough idea of how far it is. With my setup, the method will take a few minutes to complete (or fail!).

After that, you can then try subtracting 3 from the count of messages that will be sent in the Hub method 'SendAlotThenJoin', in which case, the entire operation completes successfully.

I have added the repro code to a github repository which can be found here:
https://github.com/MikaelGRA/SignalRedisBugRepro

I am hoping someone can shed some light on this issue, because it is driving me absolutely nuts.

**My environment for the provided test setup:**
I am using Windows 8.1 and VS2013 and all code is running through IIS Express in VS2013. I have installed Web Sockets for IIS on my machine.

But as said, roughly the same issue occurs when I run it in an Azure Website hosted in Azure.

**Comment by Quethrosar** [comment]
did you ever get anywhere with this ?

**Comment by MikaelGRA** [comment]
No. I assume it is still an issue. I dropped using signalr for my scenario and instead decided to use raw redis, as signalr was not absolutely required.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
