### ISSUE TITLE
Azure host with SignalR Silverlight

### ISSUE THREAD

**Issue by grendizerufo** [SignalR/SignalR#3550]
Hi,,
I have ported whole examples of Signalr2 asp.net to Silverlight ... hard work!!
the original ASP.Net examples are working on the azure host as you can see on the link
http://signalrasp.azurewebsites.net/

BUT

with ported examples of Silverlight didn't work on the Azure host cloud even on my local PC are working!!
as you can see on the bellow link
http://signalrasp.azurewebsites.net/silverlight.html

hope to get good answer with write code please
thanks

**Comment by grendizerufo** [comment]
hello any answer plz

**Comment by grendizerufo** [comment]
up

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
