### ISSUE TITLE
Better logging api

### ISSUE THREAD

**Issue by dealproc** [SignalR/SignalR#3552]
right now, the C# client api uses a TextWriter for "trace".  Is there any way to get a better logging mechanism, like https://github.com/damianh/LibLog into the SignalR client?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
