### ISSUE TITLE
Allow additional fields in Negotiate response structure and make it available in client

### ISSUE THREAD

**Issue by sondreb** [SignalR/SignalR#3553]
### Allow additional fields in Negotiate response

Allow additional fields in Negotiate response structure and make it available in client.

The initial request to /negotiate is the first call from the SignalR client to the server, it would be great if it was possible to add additional fields/properties to the structure returned from this call.
### Repro steps

I have done this by manually "hacking" the serialization of the anonymous structure returned and populated with some additional fields (in my case, user roles and permissions from a database).

My change makes the returning JSON structure like this:

``` json
ConnectionId: "c840fc23-2327-407d-9252-46f2ce72718e"
ConnectionTimeout: 110
ConnectionToken: ""
DisconnectTimeout: 30
Functions: ["function:canExecuteY", "module:HelloWorld", "function:canExecuteX"]
KeepAliveTimeout: 20
LongPollDelay: 0
ProtocolVersion: "1.5"
Roles: ["administrator", "contributor", "reader"]
TransportConnectTimeout: 5
TryWebSockets: true
Url: "/signalr"
```

To avoid conflicts, SignalR could perhaps have a ViewBag or Metadata property that contains all custom properties that is supplied by the server.

Next step would obviously be to add the returning structure to the SignalR objects on the client, making it possible to read them and use them in the app or website.

Until that is supported, one have to hack by manually editing the jquery.SignalR.js file, which is clearly not a good solution.

Above this line:

``` javascript
keepAliveData = connection._.keepAliveData;
```

I had to add this:

``` javascript
connection.permissions = { functions: res.Functions, roles: res.Roles };
```

Now my permissions settings is available through the $.connection.hub object.
### What is the use case for such a need?

In the querystring (.qs) of the SignalR client, I provide the auth token provided by ADAL (Azure Active Directory), which is sent to the server and validated using a HubPipelineModule.

Currently the Azure AD does not return roles, so roles either have to be retrieved from ADD through the ADD API, or in my case, we have a more finely granular custom permission system where all details are stored in a database.

This is a much better solution in terms of performance, compared to doing a regular Hub call AFTER Start have completed. It reduces the time of initial startup and loading of the UI, since it relies on the functional permissions that a user have.

The data is already available when the negotiate completes, so it makes sense to return the custom data structures in the first initial call to the server.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
