### ISSUE TITLE
Transport fallback causes client to never receive method invocation.

### ISSUE THREAD

**Issue by JeremyJalpha** [SignalR/SignalR#3555]
while playing around with the Selfhost and CsharpClient projects in Gustavo's [CookieAuthenticationSample](https://github.com/gustavo-armenta/CookieAuthenticationSample) when the client attempts to create a new connection to the hub using Server Sent events if the connection times out and falls back to LongPolling the hubReceived method in the hub's onConnected method is executed on the server but never received by the client.

If the client successfully connects using Server Sent events or Long Polling hubReceived is executed on the client fine.

This sounds like it could be vaguely related to [WebSockets selected as transport but send from server fails #3275](https://github.com/SignalR/SignalR/issues/3275)

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
