### ISSUE TITLE
Bower-SignalR doesn't deliver via a dist folder

### ISSUE THREAD

**Issue by LeeCheneler** [SignalR/SignalR#3556]
A very common theme for Bower packages is to provide production files within a 'dist' folder within the package. By conforming to this standard it makes building gulp/grunt scripts to handle packages en mass quite simple. 

Due to to SignalR not conforming though we have to explicitly include SignalR during our gulp pipeline after we've already dealt with all the other Bower packages together.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
