### ISSUE TITLE
Active server connection stopped

### ISSUE THREAD

**Issue by VETWorks** [SignalR/SignalR#3557]
I have setup signalR (2.2.0, obtained through NuGet) to report feedback during a controller action in an ASP.NET MVC 4.5 project. Everything works great, but sometimes signalR gives me an error message in the javascript console. See below the result of the javascript logging:

```
[02:07:08 GMT+0200] SignalR: Client subscribed to hub 'progresshub'.
[02:07:08 GMT+0200] SignalR: Negotiating with '/signalr/negotiate?connectionData=%5B%7B%22name%22%3A%22progresshub%22%7D%5D'.
[02:07:09 GMT+0200] SignalR: Attempting to connect to SSE endpoint 'http://www.notimportant.com/signalr/connect?transport=serverSentEvents&connec…ZvTR%2BVLf&connectionData=%5B%7B%22name%22%3A%22progresshub%22%7D%5D&tid=2'.
[02:07:09 GMT+0200] SignalR: EventSource connected.
[02:07:09 GMT+0200] SignalR: Now monitoring keep alive with a warning timeout of 13333.333333333332 and a connection lost timeout of 20000.
****[02:07:09 GMT+0200] SignalR: There has not been an active server connection for an extended periord of time. Stopping connection.
[02:07:09 GMT+0200] SignalR: Stopping connection.
[02:07:09 GMT+0200] SignalR: Fired ajax abort async = true.
[02:07:09 GMT+0200] SignalR: Stopping the monitoring of the keep alive.
[02:07:09 GMT+0200] SignalR: EventSource calling close().
Uncaught Error: SignalR: Connection must be started before data can be sent. Call .start() before .send()
```

Please note the marked line: the connection has been established and is immediatly aborted because of "no active server connection". When looking to the source code in SignalR, the error message originates from Transporthelper.cs:

``` c#
public static bool VerifyLastActive(IConnection connection)
{
    if (connection == null) {
           throw new ArgumentNullException("connection");
    }
    // Ensure that we have not exceeded the reconnect window
    if (DateTime.UtcNow - connection.LastActiveAt >= connection.ReconnectWindow)
    {
        connection.Trace(TraceLevels.Events, "There has not been an active server connection for an extended period of time. Stopping connection.");
        connection.Stop(new TimeoutException(String.Format(CultureInfo.CurrentCulture, Resources.Error_ReconnectWindowTimeout,
        connection.LastActiveAt, connection.ReconnectWindow)));
        return false;
    }
    return true;
}
```

The error message makes no sense, as it happens immediatly after connecting to the server. There is no period of inactivity. It also doesn't happen always, I would guess in 5% of all cases. When refreshing the page in the browser, and doing the same thing it often works withouth any issue.

Please note that the code mentions "extended period", while in javascript the error is "extended periord" (spelling mistake). Which makes me wonder how up-to-date the NuGet package is.

**Comment by alexidsa** [comment]
We found a similar problem. SignalR stops conection (long-polling in our case) right after it was established under a corporate network (proxy and stuff). Seems like something was broken in version 2.1.0. The version 2.0.3 does not have such a problem.

**Comment by ZhangKF2** [comment]
I have a same question, how to resovle it?

**Comment by moozzyk** [comment]
In the original issue the author is using a non-released version of the JavaScript client. If found a PR that has the typo mentioned by OP here: https://github.com/SignalR/SignalR/pull/2527/commits/b51ddaa5d6418591fc5cd8cd0a67244a1ee89419#diff-7db02d6e1dd70f9d433d1ac4013c68cc but it does not seem to have been merge to the dev branch let alone released. The version the OP is using is also pre 2.0.2 (the PR is from 9/2013) and the javascript client changed since then. 

If you are seeing this with the latest bits please post the following details - traces from the client and the http requests/responses the client received from the server. Otherwise this issue is not actionable.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Comment by satish2832** [comment]
We experience similar behaviour 100% under corporate network (proxies and stuff). SignalR stops conection (long-polling in our case) right after it was established. in 2.4.1 version
