### ISSUE TITLE
SignalR with Option Strict Set

### ISSUE THREAD

**Issue by JulianWigman** [SignalR/SignalR#3562]
Trying to use Option Strict in my visual studio project on my SignalR Hub project

It complains about "Clients.All.XXXX" calls with error.

"Error  BC30574 Option Strict On disallows late binding."   

Is there a way to work around this of do i have to leave "Option Strict" disabled?

Using the latest Nuget versions BTW.

Julian

**Comment by ChristopherSchaefer** [comment]
I'm using SignlaR with vb 2012 and I have the same issue.

Hope someone can help.

Thx

**Comment by bryanrideshark** [comment]
I'm also running into this issue.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
