### ISSUE TITLE
issue null reference error

### ISSUE THREAD

**Issue by syndicatedshannon** [SignalR/SignalR#3565]
Issue #372 closing notes forward all visitors to the empty repository for a future version of the client. However, an authoritative/Microsoft commenter for that empty repository says that no new client is currently needed, so one would think issues still belong in _this_ respository.

It is quite understandable if no work has been completed on this issue that at one time was a high-priority issue. However, the communication of the issue itself has been pretty mangled. Would you please help fix it?

I recommend reopening issue #372, commenting that the issue is still on the radar but lower priority than previously planned, and leaving it open until it and all other issues are migrated to the new repo.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
