### ISSUE TITLE
Virtual call in DefaultDependencyResolver constructor makes the virtual method pointless and breaks resolution

### ISSUE THREAD

**Issue by Worthaboutapig** [SignalR/SignalR#3567]
In `Microsoft.AspNet.SignalR.DefaultDependencyResolver`
we have `[SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Justification = "It's easiest")]`

It's all very well suppressing messages because it's 'easiest', but they're there for a reason...  ;)

The constructor makes a virtual call to: `Register` via `RegisterDefaultServices` and `RegisterHubExtensions`, but also implements `void Register(Type serviceType, Func<object> activator)` as `virtual` from `IDependencyResolver` (and `void Register(Type serviceType, IEnumerable<Func<object>> activators)`).

Therefore, anyone deriving from `DefaultDependencyResolver` (which one needs to do for DI) and choosing to implement the virtual `Register` methods will be stuck in a confusing/ impossible state, where your `overriding` implementation of `Register` gets called by the base constructor and breaks because your constructor hasn't finished running, so the `virtual`-ness is not really useful.

The 'easiest' way out of this is remove the `virtual` keyword from the `Register` methods, then the virtual call goes away.  This obviously means any derived resolver becomes read-only with respect to types, which isn't too helpful- though one could do that directly on the internal container as a work-around.

A better solution might be to refactor the constructor calls into a (`virtual`?) `Initialise` method that gets called when the resolver has been constructed?  Or maybe a static `Configuration` property could be available on `SignalR` like `Nancy` uses, not that I like that pattern ;)

At the moment the type initialisation is mixed up with the type registration/resolution.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
