### ISSUE TITLE
OnConnected periodically not authorized 

### ISSUE THREAD

**Issue by Leogiciel** [SignalR/SignalR#3570]
Problem seen in a MVC5 application : client browser has owin token in headers, but periodically doesn't pass it in start request.

Problem appears on any browser, on our test server (VM, Srv2012, IIS8.5).
I has never appeared on my local IIS (7.5 on Win7) with exactly the same code.

CORS enabled didn't change the comportment, neither "longpolling, transport" fix did.

Seems periodical : all start requests are authentified (or unauthentified) by period.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
