### ISSUE TITLE
Group.Add and Group.Remove return a task but are not prefixed with Async

### ISSUE THREAD

**Issue by niemyjski** [SignalR/SignalR#3572]
I never awaited these methods and I think this is one of the issues I was running into. The roslyn analyzers never picked up the missing awaits because the prefix was missing.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
