### ISSUE TITLE
unable to get property 'state' of undefined or null

### ISSUE THREAD

**Issue by akiander** [SignalR/SignalR#3575]
We see the following errors a lot coming from client machines:

```
 unable to get property 'state' of undefined or null
```

in [this location](https://github.com/SignalR/SignalR/blob/master/src/Microsoft.AspNet.SignalR.Client.JS/jquery.signalR.core.js#L90)

When this happens, our signalr connection never recovers, so the clients remain disconnected which causes problems for our application.

The following [pull request should fix it](https://github.com/SignalR/SignalR/pull/3571)

Note: This also contains a fix for the related issue: 

```
 unable to get property 'json' of undefined or null reference
```

in the following file: [jquery.signalR.transports.foreverFrame.js](https://github.com/SignalR/SignalR/blob/master/src/Microsoft.AspNet.SignalR.Client.JS/jquery.signalR.transports.foreverFrame.js#L159) 

This is all happening with the most current version of signalr ... version 2.2.0

Can you review the pull request and apply it or an alternative fix for these issues?

**Comment by moozzyk** [comment]
@akiander - can you provide logs (and, ideally, also a repro for this)? Before taking a fix we would like to understand conditions when this happens.

**Comment by akiander** [comment]
I'll be happy to provide what I can, although please let me know how you normally collect logs and repros and I'll do my best to provide them. When we get javascript errors, we don't have a stack trace - just the error reported from the browser as I provided it above. Is there some guidance on what you use to collect a stack trace and/or a repro here? Don't assume I know how this is normally done because I haven't had luck getting a reliable javascript stack trace logged from my applications yet :-) 

What I can provide is some context here... we have overhead monitors that display our web application in a full-screen browser window using Angular and SignalR so we can push changes to the monitors real-time. The overhead monitors are running all the time, 24 x 7, for weeks or months at a time. What we tend to see is that over the course of many weeks, the signalr connection will occasionally die with the above error. We have logic that should recover and reconnect the monitor's signalr connection, but in the case of this particular error, it never recovers. 

The fix I provided seems to clear this up. That fix went in early October and we have not seen this issue come back ever since, despite two months of constant use. 

I can't tell you what part of signalr is allowing this method to be called without a connection, but just that we do see it happen so, so I wanted to share the fix so others may benefit and so I don't have to reapply this fix when new versions come out.

**Comment by moozzyk** [comment]
[Here](http://www.asp.net/signalr/overview/testing-and-debugging/enabling-signalr-tracing#javascript) are the steps to enable tracing in the javascript client.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
