### ISSUE TITLE
(De)Serialization silently fails when two attributes are used.

### ISSUE THREAD

**Issue by caseymarquis** [SignalR/SignalR#3579]
Combining the following two attributes, 

**Newtonsoft.Json.JsonIgnore**
and
**System.ComponentModel.DataAnnotations.Schema.NotMappedAttribute**

likely causes either hub side serialization or client side deserialization to silently fail.

This occurs when using IHubProxy and HubConnection to connect from a .NET client.

IHubProxy.Invoke will successfully make a request to the hub, but will then hang indefinitely.

Perhaps this is an issue with Json.Net? It would be very helpful if this threw an error of some kind if it can't be worked around. I've been a little verbose describing this as, after two days of tracking down the cause of the silent failure, I'm hoping others in the same situation might come across this in a search.

Followup: JsonIgnore on a field causes the same issue.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
