### ISSUE TITLE
Hub callbacks get overwritten if they have the same string representation.

### ISSUE THREAD

**Issue by simon-q** [SignalR/SignalR#3580]
In this line:
https://github.com/SignalR/SignalR/blob/master/src/Microsoft.AspNet.SignalR.Client.JS/jquery.signalR.hubs.js#L109

using `callback` as an index to an object triggers implicit `toString` invocation which from my experience returns the source code (if available, for native functions it just puts `[native code]` in the function body)

Very roughly said, for an event, it allows just one callback per function definition not per instance.

I think it is a bug.

**Comment by 6finger** [comment]
did some more testing and it seems that the callbacks get overwritten in the `callbackMap` but still get registered with jQuery:
https://github.com/SignalR/SignalR/blob/master/src/Microsoft.AspNet.SignalR.Client.JS/jquery.signalR.hubs.js#L113

the problem then is with deregistering:
```javascript
// suppose we have a hub with a 'change' event on it
var fn1 = function() {console.log(1);};
var fn2 = function() {console.log(2);};
var fn3 = function() {console.log(3);};
hub.on('change', fn1);
hub.on('change', fn2);
hub.on('change', fn3);
hub.off('change', fn3);
```
the `fn3` will be still firing although `off` was called

**Comment by MaKCbIMKo** [comment]
Faced with the same behavior.

Is there any news about that? Maybe some ideas how to fix that (we could create the PR if possible).

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
