### ISSUE TITLE
Unable to start connection when using large authentication tickets (or maybe headers

### ISSUE THREAD

**Issue by VGavara** [SignalR/SignalR#3583]
We're developing a solution in which authentication is based on IIS authentication tickets that are bound to the SignalR connection as cookie. Solution works fine but we have noticed that when the authentication tickets get a given lenght SignalR is unable to perform the connection.

This behaviour has been reproduced using both .Net and Android Clients. We discard the problem being on the IIS side because we can access different protected webserver resources using the authentication ticket that fails when used with SignalR.

As an example I attach a ticket working and a ticket failing. Saddly we cannot set what is the ticket length that generates the error, but we suspect that the limit is 200 characters.

Ticket working:
.ASPXAUTH=4552A090E034DEC8C9393D66FB994C76F884E060F31DE33AE772CB6748A0E387BE7CC6AE1A6B33993DB96463C79CED5E9FCC337D4C156A34693FB7F33B5728D64C4DF5A5AAAA2D3CE153CAF6E8D3A94D6365F010923832AF37CC71D94C6C09C9; expires=Fri, 23-Oct-2015 12:05:34 GMT; path=/; HttpOnly

Ticket failing:
.ASPXAUTH=9F10B60C89759B250C6F7826DCAB46F9353E693F00DFR78839C5AEEA1BF6733D1FCFC027A8ABD24CBC99B146559450B63944AD3E6E4F24E50728264E534528E847D7572122746959D230F5C3B76942B8F8F3C4AD6F7C8D4C9F56DD6EC4DFDE51CA8C8D6F7B1ED2220BA030188B55F4F0; expires=Fri, 23-Oct-2015 12:02:44 GMT; path=/; HttpOnly

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
