### ISSUE TITLE
Unable to connect to persistent connection until second or third try.

### ISSUE THREAD

**Issue by niemyjski** [SignalR/SignalR#3584]
I thought I was running into this: https://github.com/SignalR/SignalR/issues/3116 Here is a link to my code: https://github.com/exceptionless/Exceptionless/tree/master/Source/Api/Hubs

![screen shot 2015-10-22 at 4 17 06 pm](https://cloud.githubusercontent.com/assets/1020579/10731255/81f7e99a-7bc2-11e5-80da-11790659b1b7.png)

On a side note, we removed the Signalr redis backplane because we are already using a message bus to deliver messages to every app instance via our [MessageBusBroker](https://github.com/exceptionless/Exceptionless/blob/master/Source/Api/Hubs/MessageBusBroker.cs). We were also seeing many other performance issues where our app was using thousands of threads and many gbs of ram from the redis backplane... Do we need the backplane for this to work?

I've been trying to track this down without any luck.

**Comment by ejsmith** [comment]
Yes, please help us track this issue down!

**Comment by ejsmith** [comment]
Here is a link to where we are configuring SignalR:
https://github.com/exceptionless/Exceptionless/blob/master/Source/Api/AppBuilder.cs#L150

**Comment by niemyjski** [comment]
I do have an await in my OnConnected but I'm not wiring up to any handlers. I'm getting the following exception thrown one the first x attempts and then it succeeds:

```
System.Threading.Tasks.TaskCanceledException: A task was canceled.
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task task) at offset 38
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task) at offset 40
at Exceptionless.Api.Hubs.MessageBusConnection.<OnConnected>d__2.MoveNext() at offset 322 in C:\projects\exceptionless\Source\Api\Hubs\MessageBusConnection.cs:line 23:col 17
```

**Comment by niemyjski** [comment]
@DamianEdwards could it be related to https://github.com/SignalR/SignalR/issues/3387 (but we are no longer using the redis scale out)

**Comment by niemyjski** [comment]
This issue sounds exactly like our setup as well: https://github.com/SignalR/SignalR/issues/3423

**Comment by ejsmith** [comment]
So maybe we do have to have a backplane setup even though the messages are already being distributed to all the nodes by the messagebus. We were trying to avoid using the backplane because it seems like it is basically duplicating the work of the messagebus that we already have in place. It seems like a websocket connection would be to a single node and we would be fine since each server node gets all the messages and can send them down to any clients that are connected to that node.  Why would the signalr connection be jumping nodes?

**Comment by niemyjski** [comment]
@ejsmith I don't think it's jumping nodes, it's three different requests (negotiate, connect (WS) and start) and the azure load balancer is sending them to different nodes.

**Comment by ejsmith** [comment]
We set sticky sessions on in Azure and that seems to have fixed the problem. So apparently the backplane is needed if you want to keep your servers doing round robin. That really sucks because it means we are broadcasting all the messages multiple times (our message bus and then signalr's message bus).

**Comment by davidfowl** [comment]
@niemyjski You're not using scale out anymore?

**Comment by niemyjski** [comment]
@davidfowl, nope we are not using scale out anymore because we have our own message bus that we hook up to a message bus broker we created whose sole purpose is to get the connection and send out the messages on each node.

https://github.com/exceptionless/Exceptionless/blob/master/Source/Api/Hubs/MessageBusBroker.cs

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
