### ISSUE TITLE
Cannot connect from Android

### ISSUE THREAD

**Issue by janniksam** [SignalR/SignalR#3588]
Hey guys,

yesterday I was about to try out SignalR, because it was recommended to me by @rdavisau.

So, I was trying to connect my Android to my local Server (both running in debug on the same PC). I was running Visual Studio as admin and also tried a few different URLs for the server, which appears to work just fine.

Unfortunately, no matter what I try, if I'm connecting to my Servers URL, I am getting a WebException, when I await HubConnection.Start()..

Tried different URLs (localhost, 192.168.178.100,  *, +...)  for the server and different URLs on the client (localhost [which makes no sense imo] & 192.178.178.100), I tried different ports... But nothing works.

Further more I am able to connect to my PCs http-port on my android phone (, because I have XAMPP running).

I am using the selfhost package for the server (it is a console app) and the standard client package for my android app.

What could be wrong? Does my debugging phone need special settings to be able to use a WLAN connection with my app or what else could be the issue.

Thanks in advance.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
