### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Shahrooze** [SignalR/SignalR#3589]
After 3 month that my signlar self host was run,i found that the process get 1.5  gigabyte  memory.We use version 2.1.1  of signalr.
I check it with Dot memory and i found that Microsoft.AspNet.SignalR.Messaging.DefaultSubscription getting more memory and don't release.

Is this memory leak?

**Comment by Shahrooze** [comment]
![untitled](https://cloud.githubusercontent.com/assets/5137630/10880484/bcb1c3b8-8170-11e5-9122-db721ebee1fd.jpg)

**Comment by georgemcz** [comment]
Second to that. It seems that it fills memory with strings like hc-Realtime.20e13545-e77c-4873-9d55-fe9c14e3a058
(guid varies by instance of course, but after few minutes of profiling, I have few hundreds instances of string like that in memory

<img width="987" alt="memleak" src="https://cloud.githubusercontent.com/assets/15940416/11296998/bc906a98-8f75-11e5-896e-6d37004acb26.png">

**Comment by davidfowl** [comment]
How big are the messages?

**Comment by georgemcz** [comment]
we're trying to keep them small - in last run, in average 300 chars (payload), with max of 1742 chars (we send just plain strings, no json on signalr side), sometimes it peeks up to say 5k

**Comment by EirikVea** [comment]
![image](https://cloud.githubusercontent.com/assets/4248990/15922155/95698eae-2e26-11e6-93d1-1b4160b6be81.png)

I seem to have the same problem. Running now for three days, and DefaultSubscription instances are steadily increasing.

**Comment by heyou93** [comment]
We are experiencing the same problem here. How to fix this kind of issue? (Memory leak)

**Comment by davidfowl** [comment]
That original dot trace profile looks suspicious. Why are there so many message bus instances. There should be one.

**Comment by maltow** [comment]
We are seeing the same here. (v2.2.0)

My tests show that it seems to be related to pinned memory that the GC cannot collect. When our application is exposed to 1-2K customers connecting in a short period of time memory seems to be pinned very fast. I even received some OutOfMemoryExceptions in busy hours.

Ants profiler shows that the unused memory allocated to .NET is growing steady. It points to byte array used in Microsoft.AspNet.SignalR.Messaging.Message 

![ants_profile_signalrapp](https://cloud.githubusercontent.com/assets/19927916/18292049/87576024-748b-11e6-87b1-f37855266652.png)

How can we circumvent this ? Is it possible to tweak initial buffer sizes or message chunk size through the API or something like that?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
