### ISSUE TITLE
signalr/hubs generated script doesn't call client function which defined in prototype.

### ISSUE THREAD

**Issue by Epsil0neR** [SignalR/SignalR#3590]
I have such class, which will be used as client for hub connection:

``` typescript
class HubMoveShapeClient {
    public $shape: JQuery = null;
    public model: IShape = {
        left: 0,
        top: 0
    };

    public constructor($shape: JQuery) {
        if ($shape instanceof jQuery === false)
            throw new Error("Shape must be instance of jQuery.")
        if ($shape.length < 1)
            throw new Error("Shape must contain at least one element.")

        this.$shape = $shape.first();
    }

    public UpdateShape(model: IShape): void {
        console.info('Update shape: ', model);
        this.model = model;
        this.$shape.css({
            top: model.top,
            left: model.left
        });
    }
}
```

And used as:

``` typescript
var hub = $.connection['MoveShape'];
var client = new HubMoveShapeClient($shape);
hub.client = client;
```

Note that client has method **UpdateShape** which is defined in class HubMoveShapeClient and in instance inherits that method.

When server tries to call **UpdateShape** method in client, **client.UpdateShape** won't be executed because generated script _/signalr/hubs_ contains method **registerHubProxies** which loops through all members on the hub and find client hub functions (to subscribe/unsubscribe)
which are defined in _client_ object and not from inherited from class or even from parent class.

I found a dirty hack which allows me to use instance of class, but I still need to override all methods which will be used from server:

``` typescript
var hub = $.connection['MoveShape'];
var client = new HubMoveShapeClient($shape);
hub.client = client;
hub['client'].UpdateShape = client.UpdateShape.bind(client);
```
## How to fix that bug

To fix that bug you need modify script which is generated by signalr (_/signalr/hubs_).
Generated script contains method registerHubProxies which loops through all members on hub and checks if hub has that own property:

``` javascript
function registerHubProxies(instance, shouldSubscribe) {
...
// Loop through all members on the hub and find client hub functions to subscribe/unsubscribe
for (memberKey in hub.client) {
    // NEXT LINE SHOULD BE REMOVED
    if (hub.client.hasOwnProperty(memberKey)) {
        memberValue = hub.client[memberKey];
            if (!$.isFunction(memberValue)) {
                // Not a client hub function
                continue;
            }

            subscriptionMethod.call(hub, memberKey, makeProxyCallback(hub, memberValue));
        } // THAT LINE ALSO SHOULD BE REMOVED
    }
...
```

And that method should be fixed to:

``` javascript
function registerHubProxies(instance, shouldSubscribe) {
...
// Loop through all members on the hub and find client hub functions to subscribe/unsubscribe
for (memberKey in hub.client) {
        memberValue = hub.client[memberKey];
        if (!$.isFunction(memberValue)) {
            // Not a client hub function
            continue;
        }

        subscriptionMethod.call(hub, memberKey, makeProxyCallback(hub, memberValue));
    }
...
```

**Comment by IanYates** [comment]
You could also avoid the prototype altogether and just have

```
class HubMoveShapeClient {
    public $shape: JQuery = null;
    public model: IShape = {
        left: 0,
        top: 0
    };

    public constructor($shape: JQuery) {
        if ($shape instanceof jQuery === false)
            throw new Error("Shape must be instance of jQuery.")
        if ($shape.length < 1)
            throw new Error("Shape must contain at least one element.")

        this.$shape = $shape.first();
    }

    public UpdateShape = (model: IShape): void => {
        console.info('Update shape: ', model);
        this.model = model;
        this.$shape.css({
            top: model.top,
            left: model.left
        });
    }
}

```

That way the `this`, after TypeScript transforms it to `_this`, can be relied upon in all cases too.

**Comment by Epsil0neR** [comment]
But this declares a property, not a method of a class.

**Comment by Epsil0neR** [comment]
Why **client.hasOwnProperty(methodName)** check is required in */signalr/hubs* when it's still checks if client[methodName] is a function before subscribe that method to call from server side?

**Comment by IanYates** [comment]
Maybe so, but for all practical purposes when you're making a call to it the calling-site code looks the same - it's a property that's a function.  I write 99% of my functions that way and needn't worry about .bind, etc.

I haven't checked the SignalR code, but depending on how it's call your function you may need .bind, or the TypeScript _this transformation, to be applied anyway for your `this` to be bound correctly.

In any case it'll work for your use case :smile_cat: 

I appreciate what you're asking for, but from watching this repo for quite a few months now, not much has changed and nothing seems likely to change until after ASP.Net v5 is out.  The hasOwnProperty check is a definite restriction placed on the loop, presumably for a reason (and if there is no reason then let's pull it out).

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
