### ISSUE TITLE
SignalR Connection Received event not consistent (JS vs .NET Client)

### ISSUE THREAD

**Issue by rsegerink** [SignalR/SignalR#3592]
According to the docs: http://www.asp.net/signalr/overview/guide-to-the-api/hubs-api-guide-net-client#connectionlifetime, the Connection Received event should trigger when any data is received on the connection. This is true when using the JS client, but not true when you use the .NET client, the Received event is only triggered when you receive a client event message and not for a progress or invoke message. See: https://github.com/SignalR/SignalR/blob/master/src/Microsoft.AspNet.SignalR.Client/HubConnection.cs#L154

**Comment by davidfowl** [comment]
How is this affecting you?

**Comment by moozzyk** [comment]
No response, closing.
