### ISSUE TITLE
TypeLoadException occurring when using Strongly typed Hub

### ISSUE THREAD

**Issue by Rytom71487** [SignalR/SignalR#3594]
Hi, 

I'm encountering a TypeLoadException when I use a strongly typed hub. My interface is:

    public interface IClientCallback
    {
        void callback<T>(T msg, string eventType);
        void test(string msg, string eventType); 
    }

All the methods are inside a single interface, and the interface does not inherit from any other interface. 

My Hub class is: 

    public class ServiceHub : Hub<IClientCallback>
    {
        public static readonly string ServiceHubName = "ServiceHub";

        public void Register(string name, string eventType)
        {
            Clients.All.test("hello", "world");
        }
    }

When I use my client app to invoke the Register method on the hub, on the Hub application I receive an exception when it is at Clients.All.test(...): 

Method 'callback' in type 'Microsoft.AspNet.SignalR.Hubs.TypedClientBuilder.IClientCallbackImpl' from assembly 'Microsoft.AspNet.SignalR.Hubs.TypedClientBuilder, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

I haven't been able to narrow down what exactly is causing this exception to be thrown. A little help or suggesting would be greatly appreciated.

**Comment by moozzyk** [comment]
Fixed in 41555309f54184905fe34c7197aa274155faed8c and fbbafd30456a6597b44d4d9b20fac4a3ba8eecfd.
