### ISSUE TITLE
ajaxAbort is always sequential

### ISSUE THREAD

**Issue by yesoreyeram** [SignalR/SignalR#3598]
In the https://github.com/SignalR/SignalR/commit/458589c299dfab2fd4441f27ff44f75f7eb6b7bf commit , there is a code block

```
  var asyncAbort = !!connection.withCredentials && firefoxMajorVersion(window.navigator.userAgent) >= 11;
```

Where does the value "connection.withCredentials" is coming from? For me it is always undefined and so my asyncAbort is always false. This makes my long running abort call blocking everything in chrome and IE. Note: I am not using any cross domain calls.

Ref: http://stackoverflow.com/questions/33759013/async-signalr-abort-call?noredirect=1#comment55320300_33759013 

What should be the value for "async" inside ajaxAbort method?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
