### ISSUE TITLE
signalr 2 enable cross domain error

### ISSUE THREAD

**Issue by hamedgibago** [SignalR/SignalR#3600]
Hi
I want to create a signalr version 2 crossplatform service
but got the error:

Error: SignalR: SignalR is not loaded. Please ensure jquery.signalR-x.js is referenced before ~/signalr/js.

and 

TypeError: $.connection is undefined

everythnig works find in same domain, but here got error,

I know that in version 1 we should set 

EnableCrossDomain=true in HubConfiguration 

and in version 2 should 

EnableJSONP = true

and in html page source should add :

$.connection.hub.start({ jsonp: true }).done(function () {

what should I do? whats the problem?

I see that in firebug all these scripts loads correctly and return 200 header code

from server:

jquery-1.6.4.min.js
jquery.signalR-2.2.0.min.js
hubs

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
