### ISSUE TITLE
SignalR negotiate request JSON in querystring

### ISSUE THREAD

**Issue by Svmali84** [SignalR/SignalR#3601]
When client sends negotiate request to server the URL contains the encoded JSON structure which has the hub name details.

Ex: /signalr/negotiate?connectionData=%22...

My webserver has the policy which restricts certain characters in url. The server blocks the URL because of double quotes (") in URL (even if they are encoded). I cant change those settings on webserver as the settings are enterprise wide. I did not find any option in Signal guide to change above pattern.

My question is why SignalR hub connection rely on JSON in querystring and why cant we use simple querystring which most of the webserver dont have any issues.

**Comment by davidfowl** [comment]
The initial connection is a GET request because some transports require it like websockets, server sent events, and forever frame.

**Comment by Svmali84** [comment]
Ok.Issue is with the ConnectionData querystring parameter in the GET request. which is a JSON structure and my webserver does not allow it. Is there anyway to specify the hubname in simple parameter like negotiate?hub=myHub.

**Comment by davidfowl** [comment]
Nope
