### ISSUE TITLE
New transport for Android clients that need long lasting two way persistent connections

### ISSUE THREAD

**Issue by florin-nitulescu** [SignalR/SignalR#3603]
Do you think it is possible to make a new ClientTransport implementation that uses Google Cloud Messaging (GCM) Cloud Connection Server (CCS), which is an XMPP endpoint, for transmitting messages back and forth between server and Android clients?
<p>The application I'm developing it's from the chat application type. But the Android platform makes it very hard for someone to keep a web-socket connection open for a long time. The device goes to sleep, the connection it's lost, and you get notified too late. If you keep the device awake enough to process every incoming keep-alive from the signalr server (not all the time, only when the keep-alive is received), the battery usage becomes pretty high. Then you have to deal with their recently introduced "doze and standby modes". The problem becomes a lot more complex.</p>
It would be much easier if I had a "transport" for my mobile clients that hides this complexity from me using GCM CCS XMPP endpoint and I can continue enjoying life with SignalR.
<p>Do you think it is possible to introduce this with a new SignalR version?</p>

**Comment by davidfowl** [comment]
No, this isn't a fit for SignalR. SignalR is all about persistent connections. Push notifications are something you would use in conjunction with SignalR but one doesn't replace the other.

**Comment by florin-nitulescu** [comment]
Sorry, but I don't really understand. Maybe I'm missing something. I thought that XMPP protocol could be just another transport for SignalR. Can you help me understand, please?

**Comment by moozzyk** [comment]
Closing as per @davidfowl comment.
