### ISSUE TITLE
SignaR phonegap

### ISSUE THREAD

**Issue by mohsinali1317** [SignalR/SignalR#3610]
So I am using SignalR persistent connection in my .net app to send events from server to attached clients. It works like a charm.

Now I have built Ios and Android apps using cordova phonegap. The event system seems to not work.

Is it because that of web socket issues on mobile apps or what?

I have cors on the server so it can't be cross domain related issues.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
