### ISSUE TITLE
ConnectionToken is not url decoded before processing it

### ISSUE THREAD

**Issue by cwt237** [SignalR/SignalR#3613]
It looks like the connectionToken querystring parameter that is sent to SignalR when creating a new connection is read directly without URL decoding it.

The raw value is used directly when converting from base 64 (called from TryGetConnectionId in PersistentConnection.cs).

It is perfectly valid to have characters in the tokens that are url encoded by the SignalR client library (js client), but not decoded when hitting the server. 

SignalR respons with 400 bad request when this happen.

I have searched the release notes and issue list without finding anyone who reported this issue.

Are you guys already aware of this?

We are running with SignalR 2.0.3 on server and client. I have checked latest version and it appears that the bug is still there.

Example of connectionToken that will not be base 64 decoded unless url decoded first:
4XkLCrdxRkFakJ%2BsWqDVKYvwSg6SHzNm6wcr%2BdUEEbgECGqUEIq1WYc9C7YN1fGBmOkmpfyZEM3oq8nwBeADZFJlO%2FcDieD81ma6QWL%2BPrlsRHFT

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
