### ISSUE TITLE
Redis Backplane System.TimeoutException for some users when connecting

### ISSUE THREAD

**Issue by KJee85** [SignalR/SignalR#3617]
We are using the Redis backplane for SignalR in our application. We had this deployed to Azure, and had also tested it locally and it seemed to be working fine.

Recently only one of our developers has been able to successfully deploy/debug locally. Even though the code has not changed for everyone else, weather you deploy to azure or run locally when we try and connect a test client we get a "System.TimeoutException: The transport connection has timed out". That seems to be the only error we get, it doesn't even seem to make it to the signal r hub even though we are able to call other methods on the API.

I don't think we are doing anything special we use
GlobalHost.DependencyResolver.UseRedis() to configure the backplane and just use the SignalR client app in a console application to try and join some groups and see data coming through.

If we comment out UseRedis it seems to work for everyone again, is there a good way to debug the redis side of this? I"m not even sure what I would be looking for.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
