### ISSUE TITLE
Defer reconnection

### ISSUE THREAD

**Issue by jamiewinder** [SignalR/SignalR#3618]
I'm using the SignalR JS client, and the 'qs' property of `HubConnection` as a means of passing up an authorization token to my service. These tokens intentionally expire quite quickly.

I have a problem in that if the connection is dropped unexpectedly, then SignalR will immediately try to reconnect and there is a good chance that my authorization token will no longer be valid. Is it possible to delay the reconnect attempt until I've had a chance to refresh my token? This'll basically involve me firing off a web call to get a new token, and updating the 'qs' property again - all of which would be subsecond (so no risk of the connection timing out during the delay). 

Is there any way to do this at the moment?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
