### ISSUE TITLE
CORS not working when using HttpModule

### ISSUE THREAD

**Issue by SSCodeChamp** [SignalR/SignalR#3619]
In my SignalR application, I have enabled CORS as per the guide and it was working fine for requests from other domains.

Now I have created custom http module and handled BeginRequest and EndRequest events to achieve some functionality. Since from that day CORS stopped working. If disable the custom written module , CORS works fine.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
