### ISSUE TITLE
http://ci.signalr.net/ redirects to invalid URL

### ISSUE THREAD

**Issue by jzabroski** [SignalR/SignalR#3622]
Uh... do you guys still do CI?  If so, where is the link?

The readme.md is clearly out of date or the website is down.  See as how the website it forwards to is http://aspnetci/ , which doesn't look like a valid URL... I am wondering who is even paying attention to whether the CI build passes/fails?

**Comment by moozzyk** [comment]
`http://ci.signalr.net/` was taken down. `http://aspnetci` is a link to the CI used internally

**Comment by jzabroski** [comment]
Wait, what?  http://aspnetci doesn't resolve.  Is this something on Microsoft's internal DNS?

**Comment by moozzyk** [comment]
Yes.
