### ISSUE TITLE
Access Is Denied starting web app on Windows 10

### ISSUE THREAD

**Issue by thnk2wn** [SignalR/SignalR#3623]
I'm self hosting SignalR inside a console app / windows service. On my Windows 7 box it worked fine. I'm now running it on a Windows 10 Surfacebook and I consistently get Access Is Denied when starting the web app. I confirmed the same code works fine on Windows 7 and Windows Server 2012.

Sample repo is here: https://github.com/thnk2wn/OwinAccessDeniedOnStartup

Not sure where to go from here; issue could lie with Owin, Windows 10, Surfacebook, or some combination.

    System.Reflection.TargetInvocationException occurred
 
    HResult=-2146232828
    Message=Exception has been thrown by the target of an invocation.
    Source=mscorlib
    StackTrace:

      at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
       at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
       at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
       at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
       at Microsoft.Owin.Hosting.Engine.HostingEngine.StartServer(StartContext context)
       at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
       at Microsoft.Owin.Hosting.Starter.DirectHostingStarter.Start(StartOptions options)
       at Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
       at Microsoft.Owin.Hosting.WebApp.StartImplementation(IServiceProvider services, StartOptions options)
       at Microsoft.Owin.Hosting.WebApp.Start(StartOptions options)
       at Microsoft.Owin.Hosting.WebApp.Start[TStartup](StartOptions options)
       at Microsoft.Owin.Hosting.WebApp.Start[TStartup](String url)
       at OwinAccessDeniedOnStartup.Program.Start_01() in C:\Source2013\Cyrus.MicroServices\ProofOfConcept\OwinAccessDeniedOnStartup\OwinAccessDeniedOnStartup\Program.cs:line 42
    InnerException: 
       ErrorCode=5
       HResult=-2147467259
       Message=Access is denied
       NativeErrorCode=5
       Source=System
       StackTrace:
            at System.Net.HttpListener.AddAllPrefixes()
            at System.Net.HttpListener.Start()
            at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
            at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
       InnerException:

**Comment by thnk2wn** [comment]
Should mention I've tried netsh http add (though I'm running as admin) and have gone through a few posts such as:

* http://stackoverflow.com/questions/16642651/self-hosted-owin-and-urlacl
* http://stackoverflow.com/questions/22293445/http-503-service-is-unavailable-when-trying-to-browse-signalr-hubs
* http://stackoverflow.com/questions/27885836/web-api-2-selfhost-access-is-denied-for-everything-but-localhost

**Comment by moozzyk** [comment]
Can you check if any other app is registered for the port you are trying to use? Because if there is an app registered you won't be able to use that port.
Also, check if the port is not in use by a different app (use netstat).
Does it work if you try a different port?
If you bind to non-localhost you need to run as admin.

**Comment by thnk2wn** [comment]
Yeah I previously used netstat and CurrPorts (http://www.nirsoft.net/utils/cports.html) and the ports I used were not in use (multiple different ones). Running as an admin.

**Comment by thnk2wn** [comment]
Any update on this? Still an issue months later.

**Comment by davidfowl** [comment]
It's unlikely there's a SignalR bug here. The error is coming from the hosting layer and all signs point to urlacl not being setup properly. What happens if you try to host on localhost. Does it work?

**Comment by hamishebahar** [comment]
i have some error,
"run visual studio as administrator" works.

**Comment by moozzyk** [comment]
Seems like a configuration issue. I am able to run SignalR apps on Windows 10.

**Comment by thnk2wn** [comment]
@moozzyk The problem was as @hamishebahar suggested. On Windows 7 I never had to explicitly run Visual Studio as Administrator. On my Windows 10 box, I have to right click Visual Studio shortcut each time and say Run as Admin, even if I change a shortcut to have it always run as an Admin and despite being a local admin on the box. Kind of annoying but Owin appears to be the only thing so far requiring this elevated security as far as I can see.

**Comment by moozzyk** [comment]
I think this happens if you want your app to listen on non-localhost. You either need to run as administrator or pre-register the prefix your application will listen on using netsh.

**Comment by thnk2wn** [comment]
It's all localhost in my use case

**Comment by gauravkohirkar-infotrack** [comment]
Thanks.. Run as administrator solved the issue..

**Comment by devocalypse** [comment]
Running as admin is **never** a proper solution and in many cases **not an option**. Reserving ports via netsh is not one either for the same reason.
I tried self-hosting SignalR inside a wpf application which needs to be hosted on client computers with limited access rights and would send and receive live commands to browsers inside their virtual machines. It looked promising while testing on localhost until I tried to bind to a real IP.

Reserving acls and whatnot are not required when using System.Net.Sockets.TcpListener which only pops up a firewall warning when the server is initiated for the first time.

I am aware this project is more asp.net-centric but we can't ignore the possibilities for the self-hosted implementations. Now I'm forced to go back to an alternative node-js implementation.

**Comment by SignalGo** [comment]
hi devocalypse, why you dont use signalgo? that is faster and better than signalR and support java script and java as well,and file streaming and more that features...

**Comment by devocalypse** [comment]
Sounds interesting. I'll take a look at that. Thank you. 
Too bad it never came up in my search results until now.

**Comment by neoraltech** [comment]
@SignalGo 
Interesting library to use. However, I wonder or maybe I have no idea at all for now, how does this differ from Mqtt?

**Comment by queBurro** [comment]
@neoraltech  Mqtt sends text. SignalR can do RPC, and is a bit cleverer with the web bit. e.g. Mqtt does "long polling" whereas SignalR tries to use better tech (e.g. WebSockets) before falling back to long polling.

**Comment by SignalGo** [comment]
@neoraltech SignalGo support websockets connections for javascript signalGo clients but that (SignalGo) have "Dedicated Protocol" independent of websocket, that is open source for server and client and works on tcp socket for send and receive data.
i have many project running with signalGo that is very easy and faster and more reliable to use and transferring data, I careated signalGo because before this i used wcf and signalR, we have java programmer for android client and c# programmer for server that is very hard for us to manage signalR json data (like datetime and objects or return data from client to server and ...) and we could not make sure to "client received server calls" or return data to server from clients,so i created signalGo for those problems.

**Comment by LanceUppercut** [comment]
> Reserving ports via netsh i

Has there been any update to the Run As Admin user when self hosting SignalR?  Ran into problem today as soon as I switched from localhost in a WPF application. 

Thanks.

**Comment by anurse** [comment]
This error is generally caused by HttpListener not being able to bind to the URL. Running as an Admin resolves the issue but is definitely not recommended. What is the URL you're trying to bind to?

**Comment by LanceUppercut** [comment]
> This error is generally caused by HttpListener not being able to bind to the URL. Running as an Admin resolves the issue but is definitely not recommended. What is the URL you're trying to bind to?

The URL binding that is working for me is:

**http://192.168.0.100:8080**    where 192.168.100 is the server IP Address. 

Adding **http://+8080/** to the url reservation list results in Access Denied also.  I've also tried binding to http://+8080/

Non Admin Self hosting will only run if I  reserve url using **netsh http add urlacl url=http://192.168.0.100:8080/ user=users** and bind to 192.168.0.100:8080.

I guess this issue (the need to run as admin or use netsh) is not confined to SignalR.  Just wondering why HttpListener behaves differently to TcpListener for example. 

Thanks.

**Comment by anurse** [comment]
HttpListener and TcpListener use completely different OS networking entrypoints. Windows has a Kernel-level HTTP server that HttpListener uses.

I'm surprised that adding the wildcard binding with `user=users` wouldn't be working for you, but I'm not an expert with these URL bindings unfortunately :(.

What is the URL you *want* to listen on? Is it `192.168.0.100`? Or a specific host name?

**Comment by fifteenzhang** [comment]
The same problem.
I solved by use cmd with Administrator then input：
netsh http add urlacl url=http://+:[your_port]/ user=[your_computer_name]
By the way:[your_port] use your port like 1234
replace [your_computer_name] with your real compute name like fifteenzhang
