### ISSUE TITLE
SignalR Javascript Client not able to send message to server

### ISSUE THREAD

**Issue by rrshah-TBA** [SignalR/SignalR#3626]
Hi,

We have created real time application using signal library in asp.net and its working fine.In this application sever and client can send message to each other.

Recently we are facing issue that Client is not able to send message to server but Server is able to send message to client and its only happened sometimes.

We already checked event viewer and logs and found internal server error.

So please guide me for the same because its our live product.

Thanks in advance

**Comment by mandarkamate** [comment]
I have few methods in Home controller where i have created ,
RecordCreated method
var hubContext = GlobalHost.ConnectionManager.GetHubContext<RealTimeJTableDemoHub>();
  hubContext.Clients.All.RecordCreated (clientName, student);
this way,

on clientside,in html
var realTimeHub = $.connection.realTimeJTableDemoHub;
        alert('okss');
        //Define a function to get 'record created' events
        realTimeHub.RecordCreated = function (clientName, record) {
            if (clientName != myClientName) {
                $('#StudentTableContainer').jtable('addRecord', {
                    record: record,
                    clientOnly: true
                });
            }

            writeEvent(clientName + ' has <b>created</b> a new record with id = ' + record.StudentId, 'event-created');
        };
but its not working .messages are not sent .when I see the developer tools in browser F12,i can see the message the hub is undefined

any help most appreciated

Thanks in advance

**Comment by dhinterlang** [comment]
Your client method name needs to start with a lowercase letter.

Also, you are missing defining it as a server callable method.

realTimeHub.client.recordCreated

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
