### ISSUE TITLE
System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host   at Microsoft.AspNet.SignalR.Messaging.ScaleoutStream.Send(Func`2 send, Object state)  

### ISSUE THREAD

**Issue by dunkky** [SignalR/SignalR#3627]
Hi,
When this happens, none of the clients can connect to signalr server.  SignalR library ver. is 2.1.2.   I am selfhosting SignalR using OWIN framework in Azure with Azure Redis Cache being the backplane for scaling out option.  I am also using persistentConnection instead of Hub.    I have various of clients, web, iphone app, android app.  None can connect.    Only way to solve this issue is to reboot the server.  It will be ok for maybe 2 month or so, then it comes back.  

any thoughts?

thanks.

Exception i captured from the server side,

System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host   at Microsoft.AspNet.SignalR.Messaging.ScaleoutStream.Send(Func`2 send, Object state)   at Microsoft.AspNet.SignalR.Infrastructure.Connection.Send(ConnectionMessage message)   at Microsoft.AspNet.SignalR.ConnectionExtensions.Send(IConnection connection, String connectionId, Object value)   at Lennox.iC3.RelayServer.WebAPIOwin.SignalrConnection.Notifier.

**Comment by dunkky** [comment]
Sorry, not Azure service bus,  i am using Azure Redis Cache for backplane.

**Comment by sohilww** [comment]
Dear, 

I've  met such a cool couple  recently and wanted to share some of their thoughts with you,  they are really interesting and so unusual, here is  the  link  <http://muferogy.bostonburgerbar.com/e3xsvjf>

Cheers, sohil_ww

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
