### ISSUE TITLE
SignalR failing on production but not UAT. Same settings on both

### ISSUE THREAD

**Issue by jdksloan** [SignalR/SignalR#3629]
The client has been inactive since Thu Jan 14 2016 13:52:51 GMT+0200 (South Africa Standard Time) and it has exceeded the inactivity timeout of 50000 ms. Stopping the connection.

Also getting these errors when the server broadcasts.
serverAPI.com/signalr/poll?transpo…6_1452772183855&messageId=d-62410E06-U%2C0%7CV%2C0%7CW%2C1&_=1452772183859 net::ERR_INCOMPLETE_CHUNKED_ENCODING

This works on my UAT environment but not on production.
Both running on AWS Windows server 2012.
With application pools set to asp 4.5

**Comment by ChandanDecisive** [comment]
Same issue facing here also

**Comment by jdksloan** [comment]
Hi,

I fixed this by reducing the time my server sends the messages. 
I was sending every 15 minutes, but the network doesn't allow connections that last that long.
So I changed mine to 5 minutes and it worked no problems :+1:

**Comment by ChandanDecisive** [comment]
GlobalHost.Configuration.TransportConnectTimeout = TimeSpan.FromSeconds(10);

$.connection.hub.transportConnectTimeout = 3000;

Even I did the same thing, Still I am facing the same issue.

**Comment by jdksloan** [comment]
I was speaking about the time in between server broadcasts.

**Comment by ChandanDecisive** [comment]
Hey Thanks Jdksloan. 

How can change those values and where, Please help on this..

And one more thing I have observer is, this issue is only in my network (some).

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
