### ISSUE TITLE
"res is undefined"

### ISSUE THREAD

**Issue by Znow** [SignalR/SignalR#3632]
Hi

``` js
var connection = $.hubConnection("signalrtesturl");
var hub = connection.createHubProxy("ApiHub");

connection.start();
```

When above was run, with jquery and jquery SignalR, "res is undefined" appeared in the log.

Packages: 
Microsoft.AspNet.SignalR.JS 2.2.0
JQuery 2.2.0

**Comment by IanYates** [comment]
Can you have your F12 browser tools set to stop at any exception?  (by default they don't stop for many exceptions). That way you'll see exactly where the exception is occurring and get a better idea of the problem.

Also, referring to http://www.asp.net/signalr/overview/guide-to-the-api/hubs-api-guide-javascript-client#connequivalence
you'll see that usually it's $.hubConnection("/signalr", ...)
Is your server configured to use signalrtesturl?  Do you need the leading `/`?

I generally use the generated proxy (see above URL again) - have you tried that (assuming there's not a reason why you're avoiding it)?

**Comment by Znow** [comment]
Hi @IanYates 

We use the leading "/", yes, I just missed it in the example.

More specific we are using "/someurl/signalr".

![image](https://cloud.githubusercontent.com/assets/265719/12447570/1aed3eb0-bf71-11e5-8bab-64f8c1d70b86.png)

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
