### ISSUE TITLE
who can help me figure out the use of the variable

### ISSUE THREAD

**Issue by echofool** [SignalR/SignalR#3634]
PersistentConnection.cs line 152.  
var response = new OwinResponse(environment);

        /// <summary>
        /// OWIN entry point.
        /// </summary>
        /// <param name="environment"></param>
        /// <returns></returns>
        public Task ProcessRequest(IDictionary<string, object> environment)
        {
            var context = new HostContext(environment);

            // Disable request compression and buffering on IIS
            environment.DisableRequestCompression();
            environment.DisableResponseBuffering();

            var response = new OwinResponse(environment);

            // Add the nosniff header for all responses to prevent IE from trying to sniff mime type from contents
            response.Headers.Set("X-Content-Type-Options", "nosniff");

            if (Authorize(context.Request))
            {
                return ProcessRequest(context);
            }

            if (context.Request.User != null &&
                context.Request.User.Identity.IsAuthenticated)
            {
                // If the user is authenticated and authorize failed then 403
                response.StatusCode = 403;
            }
            else
            {
                // If we failed to authorize the request then return a 401
                response.StatusCode = 401;
            }

            return TaskAsyncHelper.Empty;
        }

**Comment by hayer** [comment]
It seems to be used to set the response codes. Line 169 and 174.
