### ISSUE TITLE
Group name cannot contain colons

### ISSUE THREAD

**Issue by ERobishaw** [SignalR/SignalR#3635]
If you use a colon in the group name to register a group on the server, group method calls fail to send to the client (or at-least to the javascript client).

There are no errors reported in any logs, no messages, just a silent failure.

I'm not sure if ONE colon is a problem, but two are for sure:
**My specific case, the group names that failed were:**
- CTRL:123:flow
- CTRL:123:valve
- CTRL:123:schedule

**When I changed the colon to a pipe ("|"), it works as designed.**

That's four hours I'll never get back!

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
