### ISSUE TITLE
Remote stack trace is lost on client during deserialization

### ISSUE THREAD

**Issue by DmitryNaumov** [SignalR/SignalR#3637]
I'm trying to log SignalR remote stack trace exception in test's output. Initially it was looking promising - HubConfiguration.EnableDetailedErrors property allows serialize it to wire. Unfortunately it didn't work.

Further investigations shown that HubDispatcher writes stack trace into HubResponse and then it is serialized into transport. On the client side initially response is treated as string or as JObject. Then it is deserialized into HubResponse's counterpart - HubResult. Let's compare them:

```

public class HubResponse
{
    [JsonProperty("E", NullValueHandling=NullValueHandling.Ignore)]
    public string Error { get; set; }

    [JsonProperty("D", NullValueHandling=NullValueHandling.Ignore)]
    public object ErrorData { get; set; }

    [JsonProperty("I")]
    public string Id { get; set; }

    [JsonProperty("H", NullValueHandling=NullValueHandling.Ignore)]
    public bool? IsHubException { get; set; }

    [JsonProperty("P", NullValueHandling=NullValueHandling.Ignore)]
    public object Progress { get; set; }

    [JsonProperty("R", NullValueHandling=NullValueHandling.Ignore)]
    public object Result { get; set; }

    [JsonProperty("T", NullValueHandling=NullValueHandling.Ignore)]
    public string StackTrace { get; set; }

    [JsonProperty("S", NullValueHandling=NullValueHandling.Ignore)]
    public IDictionary<string, object> State { get; set; }
}


public class HubResult
{
    [JsonProperty("E")]
    public string Error { get; set; }

    [JsonProperty("D")]
    public object ErrorData { get; set; }

    [JsonProperty("I")]
    public string Id { get; set; }

    [JsonProperty("H")]
    public bool? IsHubException { get; set; }

    [JsonProperty("P")]
    public HubProgressUpdate ProgressUpdate { get; set; }

    [JsonProperty("R")]
    public JToken Result { get; set; }

    [JsonProperty("S")]
    public IDictionary<string, JToken> State { get; set; }
}

```

As you can see HubResponse.StackTrace is serialized as "T" json property and deserialized into... /dev/null !

The only hope I had is that stack trace can be processed before response is deserialized into HubResponse, while working with raw string/JObject. Unfortunately I was unable to find any traces of such behavior

**Comment by moozzyk** [comment]
Have you tried enabling detailed errors on the server? (https://msdn.microsoft.com/en-us/library/microsoft.aspnet.signalr.hubconfiguration.enabledetailederrors(v=vs.118).aspx)

**Comment by DmitryNaumov** [comment]
In the code above it's quite clear that remote stack simply not deserialized from JSON.

**Comment by moozzyk** [comment]
Oops, sorry. I think I have seen this indeed before.

**Comment by DmitryNaumov** [comment]
Can I help somehow with it?

**Comment by moozzyk** [comment]
Found this in my [own post](https://blog.3d-logic.com/2015/03/29/signalr-on-the-wire-an-informal-description-of-the-signalr-protocol/):

_T – stack trace (if detailed error reporting (i.e. the HubConfiguration.EnableDetailedErrors property) is turned on on the server). Note that none of the clients currently propagate the stack trace to the user but if tracing is turned on it will be logged with the message_

**Comment by moozzyk** [comment]
@DmitryNaumov - I guess the question is what would you do with the stack trace when you have it and why is it helpful and safe to pass it to the application itself? For diagnostic purposes it will be logged as per the quote above.

**Comment by DmitryNaumov** [comment]
@moozzyk As far as I can remember, it was quite a while ago, I need remote stack trace to put it into exception which will be stored in InnerException of our application one. Later whole exception hierarchy will be catched by app's exception handler and logged as a whole into our log sink. This is very useful for our CI, when I see client scenarios failing due to error on server, but it takes time to find out root cause exception in server logs.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
