### ISSUE TITLE
Update Wiki page to suggest using HTTPS

### ISSUE THREAD

**Issue by darakimaia** [SignalR/SignalR#3638]
Some proxies are buffering responses and this causes Server Sent Events to fail.
Since these proxies might be out of the control of the developer (e.g. an ISP's proxy), the only way to fix this is to use HTTPS which prevents this proxies from buffering the response.
This is especially important for Xamarin apps that don't use web sockets (since they're running on mono which does not support it yet). 
Mobile carriers also usually have proxies that interfere with SSE.
Combine this together and you get Xamarin apps that usually degrade to long polling if you're using HTTP. 
Even though most production apps will use HTTPS, it is very common to test things on HTTP. And this when you find out you're down to long polling and need to figure out why.
It is very hard to figure this out alone because there is no indication that a proxy is in the way.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
