### ISSUE TITLE
.Net clients do not set Content-Type

### ISSUE THREAD

**Issue by TheBlueSky** [SignalR/SignalR#3639]
I created simple ASP.Net 5 (Core) SignalR server that uses SignalR.Server v3.0.0-rc1-final, web application that uses SignalR jQuery plugin v2.2.0, a .Net 4.5 Console application that uses SignalR .Net client v2.2.0, and an Android application that uses Java and Android client that I compiled from the source.
I noticed that Android and web applications were able to connect to the server and send and receive message without issue; however, Console application gets HTTP error 500 (Internal Server Error) from Kestrel.
After checking the requests going from Android and Console, I noticed the missing Content-Type HTTP header, so, I checked SignalR .Net client source code and found out that .Net clients, other than .Net 4.0; e.g., .Net 4.5, Portable, and Store, do not set the header.
The issue is in `Post` methos in "src\Microsoft.AspNet.SignalR.Client45\Http\DefaultHttpClient.cs" file. I believe we need to add `requestMessage.Content.Headers.Add("Content-Type", "application/x-www-form-urlencoded");` after `if (postData == null) { ... } else { ... }`.
If this project is not in hibernation, I can create a pull request :)

**Comment by moozzyk** [comment]
Is this only a problem when connecting to a Signalr 3.0 server?

**Comment by TheBlueSky** [comment]
Well, I'm not sure it's related to SignalR version. It was Kestrel who didn't like to see a POST without Content-Type header; i.e., it was failing in Kestrel before reaching SignalR middleware... at least from my understanding.

**Comment by moozzyk** [comment]
https://github.com/aspnet/SignalR-Server/issues/91

**Comment by moozzyk** [comment]
SignalR server will no longer reject requests from managed clients. Leaving the bug open - it would still be good to fix this on the client side.

**Comment by TheBlueSky** [comment]
@moozzyk, is this the right repository to create such a pull request?

**Comment by moozzyk** [comment]
Yes, this is the repo.

**Comment by moozzyk** [comment]
Triage: this does not meet the bar for a servicing release.

**Comment by TheBlueSky** [comment]
@moozzyk, What is a servicing release bar? :)

**Comment by moozzyk** [comment]
One of the criteria is to not take unnecessary churn/risk. We agreed that this change is good but on the other hand it's not breaking anything or anyone so it falls into the unnecessary churn category.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
