### ISSUE TITLE
Client hangs by sending Data to Server

### ISSUE THREAD

**Issue by ajgreiner** [SignalR/SignalR#3640]
Hi, I have an SignalR App (latest Version 2.2) running on an azure Virtual Server. The SignalR Server is a self hosted Console App and I use 3 Clients (Website with Javascript, Console App and and WPF App). The Apps based on the the following Githup Projekt [https://github.com/damienbod/SignalRMessaging][1] 
Website and Console App works fine, but the WPF App starts normal, connect to the Server and beginn sending Messages. After 50-100 Messages, the App stopped and after 3-4 Minutes an Exception is thrown: 

```
Connection started reconnecting before invocation result was received
```

The WPF App recieves Data from an external Host (multithreading) and save the data in an BlockingCollection. I take the Data from this Collection and send it to the Server. Thats all. Here is my code (the App hangs at the .Wait() Command.

```
      Thread = new System.Threading.Thread(() =>
        {
            Connection = new HubConnection("http://192.168.0.4:8089/");
            myHubProxy = Connection.CreateHubProxy("MyHub");
            ServicePointManager.DefaultConnectionLimit = 10;

            Connection.Start().Wait();
            Active = true;
            while (Active)
            {
                System.Threading.Thread.Sleep(10);
                LiveWetteModel livewette = blockingCollection.Take();
                   Application.Current.Dispatcher.Invoke(DispatcherPriority.Normal, new Action(() =>
                    {
                        myHubProxy.Invoke<LiveWetteModel>("SendLiveWetteObject", livewette).Wait();
                    }));
            }
        })
        { IsBackground = true };
        Thread.Start();
```

If you have any ideas, please help!!!

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
