### ISSUE TITLE
Error "attempt to compare boolean with string" on Redis backplane

### ISSUE THREAD

**Issue by bsoulier** [SignalR/SignalR#3641]
We are using SignalR as part of a site running in Azure App Service.
Site on web page was failing, showing an HTTP 502 "Bad gateway" error when trying to connect to Websockets, EventSource & LongPolling.

Taking out of the App Service **eventlog.xml** shows this error:
`ERR Error running script (call to f_c883e7b82acc1c2a0bb1f2ee805f928afa1c1abb): @user_script:2: user_script:2: attempt to compare boolean with string`

I just attached log trace for record.

Restarting the App Service fixed the issue, but that's not a recurrent action to put in place.

[eventlog.txt](https://github.com/SignalR/SignalR/files/129040/eventlog.txt)

**Comment by duszekmestre** [comment]
I fixed this with that: https://github.com/SignalR/SignalR/pull/3563

**Comment by JaYmZ666** [comment]
Seems like a match thanks

Any ETA to have this merged with main Signalr branch?

**Comment by bsoulier** [comment]
Has been fixed with #3731 under release v2.2.1
