### ISSUE TITLE
Wrap the .net 4.5 version of AutoTransport with platform detection

### ISSUE THREAD

**Issue by dealproc** [SignalR/SignalR#3643]
https://github.com/SignalR/SignalR/blob/dev/src/Microsoft.AspNet.SignalR.Client/Transports/AutoTransport.cs#L30

Can we do something to the affect of:

``` C#
#if NET45 || WINDOWS_UWP || WINDOWS_APP
if (Environment.OSVersion.Platform == PlatformID.MacOSX || Environment.OSVersion.Platform == PlatformID.Unix) {
                new WebSocketTransport(httpClient),
}
#endif
```

Even if the transports are pushed from a private getter and you would yield them back, it would be better.

the use case here is that the main lib i'm building is .net 4.5.2, and when you transport that over to Mono, the system abruptly fails without issue.  Making this change would allow the same binaries to run on both platforms.

**Comment by moozzyk** [comment]
You can actually pass transports you want to use using [this ctor](https://github.com/SignalR/SignalR/blob/dev/src/Microsoft.AspNet.SignalR.Client/Transports/AutoTransport.cs#L38)

**Comment by dealproc** [comment]
I agree with this, however, if you are on a platform that does not support a particular transport, why would the defaults ever construct the type?  Seems like bad juju in my book.  I am going to do a deep dive and see if I can get back to the 4.5 binding after realizing this, but it's an awful lot of manual work that seems as if it should be unnecessary.

**Comment by davidfowl** [comment]
Because we don't test on mono, so the check you have isn't really relevant

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
