### ISSUE TITLE
MongoDB as messaging backplane

### ISSUE THREAD

**Issue by namelesstwice** [SignalR/SignalR#3644]
Hi, everyone!

I've implemented MongoDB messaging backplane for SignalR, and now I'm stuck with some issues. It all has started with misterious timeouts for some users on connection start (i.e. /start url). I found that  the reason was `OperationCancelledException` when addind user to group, because command to add an user to a group was missing it's acknowledgement. After some time spent with SignalR sources I realized that we have the following issue:
1. I use MongoDB `timestamp` type to provide unique id for `OnReceived` method call
2. It is garantied to be unique within one MongoDB server instance, but there is a possibility to have an older record with timestamp, that is greater then the newer one - it can happend because timestamp generation and record insert is not atomic operation.
3. There is some code in `ScaleoutSubscription` class that expect identifiers to monotonically increase, that's why some messages doesn't reach subscribers.

So, it seems like a dead end.
1. I can't figure out effective way to generate such id's with MongoDB - and now I am using capped collections and tailable cursors, that are designed especially for high throughput queues, and it work very fast.
2.  I don't want to introduce unnecessary dependency such as Redis or MS SQL just for my messaging backplane
3. I can generate id sequence in memory for every server in my cluster, but the code, that use scaleout message ids is quite complicated, so I can't be sure I don't break anything.

And now here is my questions:
1. Can you briefly explain the meaning of `MappingId` property of `Message` class, especially usages in scaleout infrastructure - `ScaleoutStore`, `ScaleoutMapping` etc
2. Do you see any way to solve my issue? 
3. Is there any possibility to get rid of autoincrement integer id as a part of ScaleoutMessageBus contract in future releases? It can provide an opportunity for a large variety of ScaleoutMessageBus implementation.

Your framework is great and I hope to continue using it :)

**Comment by Gentlehag** [comment]
I'm also very interessted in that as redis with signalr just makes a lot of problems

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
