### ISSUE TITLE
SignalR Client Receives enormous duplicate messages 

### ISSUE THREAD

**Issue by karthiik007** [SignalR/SignalR#3645]
**Environment**
2 WebAPI Server: Windows Server 2012 R2, IIS 8.5, .NET 4.5, SignalR 2.1.1 (client) , SigalR Server 2.1.2 with SqlScaleout

**DBMS:** Microsoft SQL Server 2012 R2 (SP1) - 11.0.3000.0 (X64)

**SqlScaleoutConfiguration:**

string sqlConnectionString = ConfigurationManager.ConnectionStrings["SignalRDB"].ConnectionString;
            GlobalHost.DependencyResolver.UseSqlServer(sqlConnectionString);
            //app.MapSignalR();
            Microsoft.AspNet.SignalR.HubConfiguration huc = new Microsoft.AspNet.SignalR.HubConfiguration();
            huc.EnableDetailedErrors = true;
            app.MapSignalR(huc);

**Description**
Clients receive a lot of duplicate messages. But signalR server has sent the Message only once to all the clients.

when we checked the SignalRDB database logs , there is lot of payload with messages like as follows : 

**{"WaitForAck":false,"Id":"9f7d2c6f-7ffa-4771-9353-7c767403a15b","CommandType":0,"Value":null}$9f7d2c6f-7ffa-4771-9353-7c767403a15bb**

We are not very sure what is that WaitForAck and why its false.Moreover the WaitForAck count ~4000 , but each client has recevied the duplicate message ~20000.

Any clues what could trigger this to client to receive ~20000 messages ?

**Comment by moozzyk** [comment]
Do you know what transport did you use? Also, is there any way to repro this?

**Comment by karthiik007** [comment]
it looks like if we make the SignalR DB very busy we can repro it , but i havent tried reproducing it  ,Let me try and get back if i can repro it ,

Checked the connection object of the client code while debugging and its LongPolling Transport.

**Comment by moozzyk** [comment]
If you can repro this - can you capture traces from the client and from the server. Here is an article describing how to enable tracing http://www.asp.net/signalr/overview/testing-and-debugging/enabling-signalr-tracing

**Comment by karthiik007** [comment]
Sure , let me revert once i repro this.
Many thanks Moozzyk

**Comment by allenjzhang** [comment]
We are also seeing occasionally 10's thousands duplicate messages with Service Bus Scale out. @moozzyk Since we are in production, it is difficult to capture process dump.

**Comment by moozzyk** [comment]
I am in the process of adding more detailed tracing to be able to diagnose the problem. It's probably a race condition somewhere in scaleout but since there is no consistent repro it's impossible to debug.

**Comment by allenjzhang** [comment]
Let us know when 2.2.2 is out and we can grab trace logs for investigation. We have to add de-dup logic in our client in the meantime. Thanks.

**Comment by moozzyk** [comment]
2.2.2-preview1 is now on NuGet

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Comment by curtkauf** [comment]
I am experiencing the same issue using SignalR 2.4.1 with SQL server 2008R2 and Windows Server 2008R2 IIS 7.0 in my MVC web app. My scenario is I have one SQL server and one web server. Maximum number of connected users would be 500. I am pushing one tables updates from sql server to clients every 15 minutes. Users don't push anything to SQL. The data sent from the server is exactly 400 records each time.  The transport method is ServerSentEventsTransport. I am new to this and I have tracing on and logging enabled. How can I fix this issue! Can anyone assist me in correcting this or point me in the right direction to a solution! Duplicates can be from as little as 2 to as high as 50 per user. Any assistance would be appreciated! Thanks!
