### ISSUE TITLE
Jquery .load(event) has been depreciated

### ISSUE THREAD

**Issue by geofili** [SignalR/SignalR#3646]
The Jquery Load Event has been deprecated as of version 1.8
See: https://api.jquery.com/load-event/

You should change the following code line in jquery.signalR-2.2.0.js:

`_pageWindow.load(function () { _pageLoaded = true; });`

Please update to something like this:

`_pageWindow.on('load', function () { _pageLoaded = true; });`

**Comment by ymoradi** [comment]
+ I've the same issue.

**Comment by the-spyke** [comment]
Yes, I can't load SignalR with jQuery 3.0.x, but it works just fine with jQuery 2.2.x because of this.

**Comment by moozzyk** [comment]
This is going to be fixed in 2.2.1. The change is already in: signalr-signoff.redis.cache.windows.net:6380,password=I3HTpum3DjK4C+wvK2Cd4DIk/yeB+6SCY5AMaIOOFDs=,ssl=True,abortConnect=False

**Comment by moozzyk** [comment]
https://github.com/SignalR/SignalR/issues/3710
