### ISSUE TITLE
how many groups can signar make?

### ISSUE THREAD

**Issue by elther** [SignalR/SignalR#3648]
hi. i'm doing little project about stock trading
i want to send market price to people belong to groups
so i need to know how many groups signalR make

how do i check large of groups? 

thx~~

**Comment by IanYates** [comment]
Hi @elther - I strongly recommend you read through the tutorials at http://www.asp.net/signalr.  You'll find they have examples detailing breaking users in to groups, sending messages to them (such as changes of a stock price being received from some external service), etc.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
