### ISSUE TITLE
SignalR allows connection without negotiation 

### ISSUE THREAD

**Issue by Svmali84** [SignalR/SignalR#3651]
As per my understanding SignalR client sends negotiation request first. In the negotiate request it receives JSON response which has connection details like connectionid,connectiontoken , Trywebsockets etc...Now client sends the connect request with received connectionToken in querystring. SignalR server establishes the connection.

If someone directly sends connect or reconnect request with any of the previously issued connectiontoken without negotiate request , server still allows the connection. Actually this should not happen. SignalR should allow the connection to the connectionToken which is actually issued by him.

**Comment by moozzyk** [comment]
You need to authorize requests.
