### ISSUE TITLE
SignalR does not have mechanism to report the gaps.(Messages dropped from buffer)

### ISSUE THREAD

**Issue by SSCodeChamp** [SignalR/SignalR#3652]
The default message count buffer  size allocated to each client is 1000 messages per connection. Does SignalR drops the old messages to accommodate new messages if buffer is full ? How to get the count of how much messages dropped by SignalR in this case ? This is extremely important to identify slow clients and network issues.

**Comment by vpatel-TBA** [comment]
what is 1000 here? and what is buffer size in kb?

**Comment by Svmali84** [comment]
vpatel ,

1000 is max number of messages per connection in memory . They did not mention the buffer size.

Please read below on official SignalR site:

http://www.asp.net/signalr/overview/performance/signalr-performance

SignalR configuration settings

DefaultMessageBufferSize: By default, SignalR retains 1000 messages in memory per hub per connection.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
