### ISSUE TITLE
Signalr With redis in Loadbalancer Scenario SocketFailure on EVAL

### ISSUE THREAD

**Issue by BoasE** [SignalR/SignalR#3653]
We have a site running in IIS on two webservers. Bevore the websites we ahve a loadbalancer which currently splits the requests in a round robin system.

For this we needed to use Redis as Backplane. But we get very often big problem with this.

in my log I can see that there are errors on connect , abort and on returning results

```
StackExchange.Redis.RedisConnectionException: SocketFailure on EVAL
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Owin.Cors.CorsMiddleware.<Invoke>d__0.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
```

and 

```

StackExchange.Redis.RedisConnectionException: SocketFailure on EVAL
 at Microsoft.AspNet.SignalR.Messaging.ScaleoutStream.Send(Func`2 send, Object state)
 at Microsoft.AspNet.SignalR.Infrastructure.Connection.Send(ConnectionMessage message)
 at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.Outgoing(IHubOutgoingInvokerContext context)
 at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.<>c__DisplayClass1b.<BuildOutgoing>b__19(IHubOutgoingInvokerContext context)
 at Microsoft.AspNet.SignalR.Hubs.SignalProxy.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)


```

Also some times the side doesn't recover and can't connect to redis again.

At the given points in time there are nod redis errors in the logs and i can access redis with the redis client desktop manager. 
We also use some caches on redis (They use ServiceStackRedis) and they don't create errors in this cases. 
So there is a possibility that this error isn't related to redis but to signalR.

In the redis group they told me that older versions of StackExchange Redis they experienced this kind of problems as some connection handles were not resolved and only a client connection reset has fixed the issue in the client. This would also explain why a IISReset or Redis start is helping.

We also updated SignalR in December (from where on we seem to have the issues). Which also seems to be related to the signalR .

Can any one help me to see wether it is a SignalR/StackExchange bug  ? Is there a way to ingetrage **ServiceStack**.Redis instead of **StackExchange**.Redis ?

**Comment by Gentlehag** [comment]
I had a look at the default SignalR.Redis assembly and it refrences StackExchange.Redis 1.0.316.0

but the when i log foor stackexchangeredis the most current version is 1.0.488
![image](https://cloud.githubusercontent.com/assets/4619513/13553143/fec5d8d2-e37e-11e5-9483-34ce0f3275c5.png)

maybe the bug is related to this?

**Comment by Quethrosar** [comment]
its not related to stackexchange. I found in signalr they use a _error variable that is never cleared out of it keeps rethrowing the same exception even if stackexchange reconnects. I'm trying to get a response from them but they are ignoring this issue.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
