### ISSUE TITLE
Get rid of redis backplane with sticky sessions

### ISSUE THREAD

**Issue by BoasE** [SignalR/SignalR#3654]
To keep track: I also posted this issue: https://github.com/SignalR/SignalR/issues/3653

In some posts I saw that if the loadbalancer is set to use sticky sessions the redis backplane  could be deactivated. But I can't find any details on this. 

So is this true?
Would redis this recognize automatically. What would I have to configure ? A link to a ressource would be very nice - Can someone help me here?

**Comment by sondreb** [comment]
This would not work if you have code that is triggered in multiple backend machines. If your backend logic connects to any of the gateway services running SignalR, the message will not be distributed correctly. One option is to call all gateway (SignalR) machines every time you have a message to send, that would remove the need for backplane, and in my experience, it can lead to better performance even though in many cases it will be duplicate messages sent to SignalR nodes which doesn't have the correct client connected, but there is obviously some work needed to be done to handle the backplane logic which adds resources as well.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
