### ISSUE TITLE
GET /signalr/hubs 404 error

### ISSUE THREAD

**Issue by oloer2014** [SignalR/SignalR#3655]
I'm trying to host a sample signalr project in IIS.
When I start from VisualStudio, it works fine, but hosting on IIS gives this error
   GET <>/signalr/hubs 404 error

**Comment by DOMZE** [comment]
Which version are you using?
Which ASP.NET version are you using?

**Comment by moozzyk** [comment]
Looks like a configuration issue. If you still hit it please reopen and provide more details so that it is possible to reproduce.
