### ISSUE TITLE
.Net Client receives InvalidOperationException instead of original thrown CustomException

### ISSUE THREAD

**Issue by Kooki** [SignalR/SignalR#3656]
Hi,

is it possible that there is an issue on signalr 2.2.0, when you try to receive an custom exception ? Is there any workaround to receive a custom exception on a c# signalr client ?

Client Code :

       public MyObject GetMyObject()
        {
            var result = hub.Invoke<MyObject>("GetMyObjectById", "id=1");
            result.ContinueWith(task =>
                                {
                                    if (result.IsFaulted)
                                    {
                                        result.Exception.Handle((x) =>
                                        {
                                            if (x is MyCustomException) 
                                            {
                                               //codse
                                            }
                                            return true; handled  
                                        });
                                        return null;
                                    }
                                    //yiehaa
                                });
            return null;
        }
Server Code:

        public async Task<MyObject> GetMyObjectById(string query)
        {
            if (query == "id=1")
            {
                throw new MyCustomException("damn",CustomExceptionType.SOMETHING);
            }
            return new MyObject();
        }
On client side I got an Name = "InvalidOperationException" FullName = "System.InvalidOperationException" with my message 'damn', but without any other properties like 'CustomExceptionType' .

I already tried : 
appBuilder.MapSignalR(new HubConfiguration() { EnableJSONP = true , EnableDetailedErrors = true}); 

Any suggestions?

**Comment by moozzyk** [comment]
SignalR does not preserve the exception type. (Also note that the client does not have to run C# so how would you translate this exception type to JavaScript or C++).
