### ISSUE TITLE
Issue with dynamic assemblies. 

### ISSUE THREAD

**Issue by Lette** [SignalR/SignalR#3657]
In the `ReflectedHubDescriptorProvider` class' private `GetTypesSafe`method, calling the `Location`property on a dynamic assembly throws a `NotSupportedException`. This effectively hides the expected warning message and aborts the entire discovery of hub types.

A pull request for this issue was created in 2014: #3368

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
