### ISSUE TITLE
Restart connection while UWP app is suspended

### ISSUE THREAD

**Issue by bbougot** [SignalR/SignalR#3660]
This post is not really a SignalR _issue_, but a question.

I'm developing a UWP application, which uses SignalR to send realtime messages to an API.

Everything works fine, even if my app enters the suspended state (for example user goes to lock screen), signalr succeed in keeping connections alive.

Problem is, when the internet connection is lost while app is suspended, web socket connection goes down and I'd like to reopen the connection as soon as internet access is up again.

But I can't manage making this works, calling:
`await HubConnection.Start();`

hangs indefinitely, it never returns and connection does not restart. I've investigated a little, and it seems IHubConnection.Start() calls a new thread, which is queued because app is suspended. The same way I tried to call the dispatcher like this:

`Windows.ApplicationModel.Core.CoreApplication.MainView.CoreWindow.Dispatcher.RunAsync(CoreDispatcherPriority.Normal,
async () =>
{
    await HubConnection.Start(); // 1
});`

The statement // 1 is never called during suspended state, but as soon as the app is resumed, it is executed.

Is it possible to restart the SignalR connection while app is suspended? Or does it need a new thread which has to be queued until app resumes?

(N.B: the original post has been posted on SO, but not received enough attention: 
http://stackoverflow.com/questions/35963571/understand-how-suspended-state-works-uwp-app?noredirect=1#comment59583584_35963571)

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Comment by ali-h2010** [comment]
@bbougot  Hi,
How did you deal with app close by user? Once app is closed, the session will be terminated.
You could send a push notification to the user once a new message comes which will allow the user to open the app and get it but i am trying to create an on-premise solution so i can't use WNS.
