### ISSUE TITLE
hanging on waiting for localhost

### ISSUE THREAD

**Issue by sudhirgoswami** [SignalR/SignalR#3661]
![image](https://cloud.githubusercontent.com/assets/5566851/13804858/7d6478e8-eb76-11e5-8a01-3fee113b2dd8.png)

Above screen shot , It is not showing me my default.aspx. First time when I ran it , it worked but I don't know what went wrong , Not It is not responding me. I followed  "http://www.dotnetcurry.com/signalr/914/stress-testing-signalr-crank-utility"
 
please help me asap.

**Comment by IanYates** [comment]
This probably isn't a SignalR thing.  I appreciate you're following some instructions from a site about SignalR but if you're not even getting data back for your HTML then that's before SignalR even enters the picture.

I think you'd have better luck on StackOverflow but you'll also need to post some extra information.  Have you opened your F12 dev tools?  Can you see a network request being made and then responding?

I can imagine that given what you're doing, is it possible you've got Visual Studio active debugging the website and it's paused at a breakpoint?

**Comment by sudhirgoswami** [comment]
@IanYates Thanks for reply , I found some article so now it is working.


![image](https://cloud.githubusercontent.com/assets/5566851/13811606/d6588c98-eb9c-11e5-8784-85d588121ff0.png)
