### ISSUE TITLE
ObservableDbOperation.Dispose Hang

### ISSUE THREAD

**Issue by smbecker** [SignalR/SignalR#3663]
I have a self-hosted server application that I noticed periodic hangs when trying to shutdown. It currently appears to be blocked in the ObservableDbOperation.Dispose method waiting on [_stopHandle.Wait](https://github.com/SignalR/SignalR/blob/fa864e866bea4737dbd888f993892694f2f6b1a6/src/Microsoft.AspNet.SignalR.SqlServer/ObservableDbOperation.cs#L258). Any ideas why this event handle is never being released?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
