### ISSUE TITLE
Unable to connect to busy server

### ISSUE THREAD

**Issue by smbecker** [SignalR/SignalR#3664]
I have self-hosted application that executes jobs using Quartz.net and reports progress to a desktop UI using SignalR. When the service gets particularly busy executing jobs, I can no longer connect the SignalR client to the service. However, the WebAPI endpoints that are also exposed through the service all remain entirely accessible. This behavior only seems to happen when using SQL Server message bus. The bizarre thing is that I can connect to the service using web sockets (or any other transport) but for some reason the initialization data is never sent across, which eventually causes a TimeoutException. If I comment out [this 'if' block](https://github.com/SignalR/SignalR/blob/dev/src/Microsoft.AspNet.SignalR.Client/Transports/ClientTransportBase.cs#L186) and always call `InitReceived`, which would only ever be called once due to the [CompareExchange](https://github.com/smbecker/SignalR/blob/dev/src/Microsoft.AspNet.SignalR.Client/Infrastructure/TransportInitializationHandler.cs#L96) call, the client connects without issue. Is it possible that under load, the initialization messages are somehow getting purged before they can be sent to pending clients? Is there another solution to this besides commenting out that piece of code.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
