### ISSUE TITLE
Server Sent Events connections not closing

### ISSUE THREAD

**Issue by ghristov88** [SignalR/SignalR#3665]
I think I am having a similar issue with SSE like #369.
1. When I debug on my local machine I have a connection with SSE and then I kill the page, from chrome (48.0.2564.116 m) task manager and then I close the page. The connection does not disconnect at all. I've waited at least 15-20 mins. I checked it in ITransportHeartbeat.GetConnections() and the IsAlive property remains true for the described time.  I caught this on my live environment where I have 1000+ connections with SSE mostly on mobile devices. The users have multiple connections for the same userID (which should not happen and it doesn't happen for other transports). I guess that on mobile devices they close the tab from the task manager and the same thing happens as if you killed the process (haven't been able to reproduce it).
2. There is another thing that our QA team simulated, not sure if is related. When a mobile device is connected with SSE, then the browser is minimized, then the device is locked (iPhone) or the internet is stopped (Android tablet) and after 30 seconds it is brought back, we end up with a new connection on SSE and the old one is still alive and keeps being alive after 10-15 mins. I haven't had the time to simulate it in an isolated project, but I decided to write it anyway, because it might help knowing about it regarding the first issue. 

We are using signalR  2.2.0 server and js client.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
