### ISSUE TITLE
-Client Command Missing updated crank

### ISSUE THREAD

**Issue by sudhirgoswami** [SignalR/SignalR#3666]
Hi Team,

I am following document "http://www.dotnetcurry.com/signalr/914/stress-testing-signalr-crank-utility"
So I have one question , like given below command will open 100 client connections. but I think now in updated crank project this feature has been disabled. means I am not fine any clients parameter. but I have to test more than 100 client how I can do it?

crank /Clients:100 /Url:http://localhost:29573/TestConnection /BatchSize:10 /Duration:120

![image](https://cloud.githubusercontent.com/assets/5566851/13872960/224fbef0-ed14-11e5-852f-b76079011981.png)

This command throwing some error you can see in the attached image

So If in the given help , they introduced NumClient command , I also tried it but it is not taking more than 1000 client . so please help me

Thanks

**Comment by insulind** [comment]
[/Connections] is the one you want I think

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
