### ISSUE TITLE
This page '/signalr/abort' does not set a Content-Type header value

### ISSUE THREAD

**Issue by tahazayed** [SignalR/SignalR#3667]
This page '/signalr/abort' does not set a Content-Type header value. This value informs the browser what kind of data to expect. If this header is missing, the browser may incorrectly handle the data. This could lead to security problems.

**Comment by moozzyk** [comment]
The response to `/signalr/abort` is always empty (i.e. there is no data to handle).

**Comment by tahazayed** [comment]
If it is always empty it should return 204 status code instead of 200

Response:
HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Expires: -1
Server: Microsoft-IIS/8.5
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Date: Wed, 23 Mar 2016 14:53:28 GMT
Content-Length: 0

**Comment by moozzyk** [comment]
I don't think we are going to change it at this point - at least not in 2.x. If you feel strongly about this feel free to file an issue in the https://github.com/aspnet/Signalr-Server repo.
