### ISSUE TITLE
Authorize attribute on methods

### ISSUE THREAD

**Issue by Stalso** [SignalR/SignalR#3668]
Hello. When I mark my hub with Authorize attribute ( I am using jwt token middleware for authorization), everything is OK. Server responds with 401 code, if user is unathorized and is not connected. But if I mark only one method of my hub with this attribute, method is not called (it is correct) , but server responds with 200 code (with Execption data) . How can I retrun 401 code from server, when protected method of hub was called?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
