### ISSUE TITLE
Convert Entity Framework object and send as parameter to Client

### ISSUE THREAD

**Issue by B6692** [SignalR/SignalR#3669]
I would like to pass some of my Entity Framework objects using Signal R as parameters to the clients either during push or pull calls, how can I do this for example, for a customer and his/her orders?

Thanks in advance.

**Comment by moozzyk** [comment]
@DamianEdwards has a [sample](https://github.com/DamianEdwards/RealTimeEntityFramework) of EF and SignalR looking together. This might give you some ideas. 

Not a product issue.
