### ISSUE TITLE
Is anyone working on this still or should I use something else

### ISSUE THREAD

**Issue by ByronAP** [SignalR/SignalR#3671]
It seems there is a major lack of work being done on this project, is it dead, should I switch to something else?

**Comment by NKnusperer** [comment]
Looks like development continues in [aspnet/SignalR-Server](/aspnet/SignalR-Server).

**Comment by Lakritzator** [comment]
Does anyone know if there is an official statement on this, I can't seem to find anything on the future of SignalR and the move to that repository...?

**Comment by ByronAP** [comment]
sorry I don't have an answer but it looks like there is some activity on the new git but the backlog says mid 2014 soooo ya I assume M$ is leaving us dead in the water

**Comment by IanYates** [comment]
Watching the ASP.Net community stand-up videos, they're putting 99% of their effort into ASP.NET Core.  Once that's out - and that's the end of this month, they are working on SignalR 3.0 as it is not going to be part of the first release.  I suspect the core stuff has taken longer than anyone expected - not unheard of with software! - but there is definitely a future for SignalR.  I think many members of the community are looking forward to the next 2.x point release to fix a few issues that continue to crop up in this issues forum.

**Comment by Lakritzator** [comment]
To both: thanks for the quick answers
@IanYates: this makes sense, although it's unfortunate that there currently is a bit of a lack of communication.

It's amazing how many issues and pull requests are hanging around :astonished: 

I myself am using it "self-hosted" in an internal application, and am thinking about also using it for Greenshot (open-source which I develop) to support browser extensions to communicate with it. So it's important to have an idea about if this would be supported in the near future. I probably need to have a look at a different "host"... considering the amount of work is put into Kestrel?

**Comment by ByronAP** [comment]
sadly I am considering jumping ship if an interim release is not done as the current build is long in the tooth and socket.io is looking a bit more apealing by the day although it is not as easy to work with.

**Comment by halter73** [comment]
@IanYates Is correct. I wouldn't expect any work to start on SignalR before the end of the month, but we are planning to reassemble a SignalR team after ASP.NET Core 1.0 ships.

**Comment by Lakritzator** [comment]
@halter73 thanks for the update, much appreciated!
If all the work will be in the aspnet/SignalR-Server, maybe a reference on that project should be added?

**Comment by stto3703** [comment]
@halter73 Would you know why 2.2.1 hasn't been released / published to nuget?

**Comment by Worthaboutapig** [comment]
@halter73 Surely you either support a project or you don't?  It's not reasonable to develop a well-used library and then just disappear to work on something unrelated and leave this hanging-around until Microsoft feels it's important enough to look at again.

**Comment by ByronAP** [comment]
agreed... very sad state for this project right now and it should be handed to the community if nothing else

**Comment by moozzyk** [comment]
2.2.1 servicing release was shipped in July. https://github.com/aspnet/SignalR-Server/issues/196 contains discussions for the next version.

**Comment by Lakritzator** [comment]
@moozzyk  Thanks for the update, I will be following it.
