### ISSUE TITLE
Kill connection from server

### ISSUE THREAD

**Issue by Bortxx** [SignalR/SignalR#3672]
There seems to be no way to kill client connections from the server. Moving to SignalR from WCF which has this feature. Imagine an unwanted client that you want to ban at least temporarily based on IP. How would this be done in SignalR?

**Comment by nullspark** [comment]
Why don't you just use the ASP.NET equivalent to similar to PHP `exit()`? Doing this would prevent the client from getting anything because the script would just stop.

**Comment by Bortxx** [comment]
Using self hosted OWIN not ASP.NET. Not sure what this has to do with PHP. Call exit() on what class? Script?! what script?

**Comment by moozzyk** [comment]
It is very unlikely that this feature would be implemented in v2 server. We are however discussing it for the Core server see: aspnet/SignalR-Server#162 and aspnet/SignalR-Server#196

Related #3740
