### ISSUE TITLE
Send message to a user, handled by only one client

### ISSUE THREAD

**Issue by programcsharp** [SignalR/SignalR#3676]
We have the capability to send a message to a user through #2401.

Is there any way to make sure the message is handled by only one of that user's clients if they happen to have multiple tabs open?

In this case, the goal is to trigger a download for the user... right now the download happens once for each tab they have open, and I'm trying to figure out a way to make it happen only once per user.

**Comment by programcsharp** [comment]
I've been able to work around this, sort of, by tagging each window with a GUID and filtering based on that.

Still wondering if there is a better way to do this in SignalR proper.

**Comment by moozzyk** [comment]
You can also send using the ConnectionId. Each connection has a unique Id so even if the same user has multiple connections open only the one with the ConnectionId will get the message.
