### ISSUE TITLE
how to use websocket in server side

### ISSUE THREAD

**Issue by aazjcom** [SignalR/SignalR#3677]
i only need websocket in server side ,how to ban other transport in server side?

**Comment by echofool** [comment]
`var transportManger= (ITransportManager)GlobalHost.DependencyResolver.GetService(typeof(ITransportManager));
transportManger.Remove("foreverFrame");
transportManger.Remove("serverSentEvents");
transportManger.Remove("longPolling");`

**Comment by aazjcom** [comment]
thank you very much!
var transportManger= ( 

TransportManager(not ITransportManager)


)GlobalHost.DependencyResolver.GetService(typeof(ITransportManager)); transportManger.Remove("foreverFrame"); transportManger.Remove("serverSentEvents"); transportManger.Remove("longPolling");
