### ISSUE TITLE
Use WinRTWebSocket  for store client websocket transport

### ISSUE THREAD

**Issue by moozzyk** [SignalR/SignalR#3681]
https://github.com/dotnet/corefx/tree/master/src/System.Net.WebSockets.Client/src/System/Net/WebSockets

It means we can drop this implementation:

https://github.com/SignalR/SignalR/blob/dev/src/Microsoft.AspNet.SignalR.Client.Store/Transports/WebSocketTransport.cs

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
