### ISSUE TITLE
SignalR 2.2.0 and MVC6

### ISSUE THREAD

**Issue by pantonis** [SignalR/SignalR#3683]
Hi,

I was wondering if SignalR 2.2.0 is compatible with ASP.NET Core 1 ?

Thanks

**Comment by DOMZE** [comment]
I had it working with RC1, but since Core is really different than 4.5, as it's being rewritten, I suggest just using SignalR 3 RC1

you can get it from the ASP.NET master branch:
Add a nuget package source with url: https://www.myget.org/F/aspnetmaster/api/v3/index.json

Cheers!
