### ISSUE TITLE
Deserialize object passed as abstract class by SignalR

### ISSUE THREAD

**Issue by shlatchz** [SignalR/SignalR#3684]
I have a WebAPI server that has a Hub that replies to Subscribe requests by publishing an `Dictionary<long, List<SpecialParam>>` object.

The list of `SpecialParam` contains items of type `SpecialParamA` & `SpecialParamB` which both inherit `SpecialParam`.

When I try to capture the publish on the client:

```
hubProxy.On<Dictionary<long, List<SpecialParam>>>(hubMethod, res =>
{
    DoStuff();
});
```

The `DoStuff()` method isn't called. If I change the publish return value to `string`, and change the proxy to receive a `string` value, the `DoStuff()` method is called. Therefore, the problem is with the deserialization of the `SpecialParam` Item.

I tried configuring on the server-side:

```
var serializer = JsonSerializer.Create();
serializer.TypeNameHandling = TypeNameHandling.All;
var hubConfig = new HubConfiguration();
hubConfig.Resolver.Register(typeof(JsonSerializer), () => serializer);
GlobalHost.DependencyResolver.Register(typeof(JsonSerializer), () => serializer);
```

But it didn't help.

I also tried adding to the client:

```
HubConnection hubConnection = new HubConnection(hubPath);
hubConnection.JsonSerializer.TypeNameHandling = Newtonsoft.Json.TypeNameHandling.Auto;
hubProxy = hubConnection.CreateHubProxy(hubName);
hubProxy.JsonSerializer.TypeNameHandling = Newtonsoft.Json.TypeNameHandling.Auto;
```

And it also didn't help.

In other solutions I found that people defined a new `IParameterResolver`, but it is only called when the server receives the input to the hub method, and not when the output is published from the hub.

Please help!

**UPDATE**

Here is what I caught with fidler:

```
{"$type":"Microsoft.AspNet.SignalR.Hubs.HubResponse, Microsoft.AspNet.SignalR.Core","I":"0"}
```

This is what the server replies to the client.

**Comment by IanYates** [comment]
If you remove the custom JSON serializer on the server-side, what do you capture with Fiddler?  

You may need to annotate your server-side and client-side types with some JSON.Net attributes, write a custom contract resolver on the client (so you don't have to rely on type name handling) or perhaps make some simple DTOs that allow you to return a couple of lists rather than a dictionary with varying types.

**Comment by shlatchz** [comment]
I managed to make the client receive a json object with all the data.

I did it by removing the expected type:

	hubProxy.On(hubMethod, res =>
	{
		DoStuff();
	});

Now I'm trying to figure out how to receive it already deserialized as `Dictionary<long, List<SpecialParam>>`.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
