### ISSUE TITLE
Websocket protocol is not working using windows 10 universal apache cordova for client

### ISSUE THREAD

**Issue by zhikin2207** [SignalR/SignalR#3689]
I am using windows 10 universal apache cordova application for client and windows server 2012 R2 + IIS 8.5 for server. Server has enabled websoket protocol. Server works just fine with other clients. Under the hood cordova using ms edge. And it works for windows 8.1. What can it be? 

Thank you in advance.

**Comment by DOMZE** [comment]
Not working how?
Try to be a little more descriptive to help users give you the best answer possible!

**Comment by georgechond94** [comment]
I think he means that the method UWP uses is Server Sent Events instead of WebSockets which is true.

**Comment by moozzyk** [comment]
In 2.2.0 websocket transport is in a separate package - Microsoft.AspNet.SignalR.Client.Store. You need to add this package to your project *and* configure the connection to use this transport. In 2.2.1 there will be a separate client for UWP/Store apps (as opposed to using a PCL) and it will have websockets transport included and enabled like a regular .NET Client.
