### ISSUE TITLE
Error during WebSocket handshake: 'Sec-WebSocket-Accept' header is missing

### ISSUE THREAD

**Issue by DOMZE** [SignalR/SignalR#3691]
SignalR 3-RC1 user on ASP.NET 5 RC1

Getting the following error when trying to get websocket going.

Using Chrome 50.0.2661.87

Headers are the following:

Request header:
Date:Fri, 29 Apr 2016 13:51:54 GMT
Server:Kestrel
Transfer-Encoding:chunked
Upgrade:websocket
X-Content-Type-Options:nosniff
X-Powered-By:ASP.NET

Response Header:
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8,fr;q=0.6
Cache-Control:no-cache
Connection:Upgrade
Cookie: ...ASP.NET cookie
DNT:1
Host: host.tld
Origin: http://host.tld
Pragma:no-cache
Sec-WebSocket-Extensions:permessage-deflate; client_max_window_bits
Sec-WebSocket-Key:liIKiClt7Z057EwteJYJXQ==
Sec-WebSocket-Version:13
Upgrade:websocket
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.87 Safari/537.36

Using Microsoft.AspNet.WebSockets.Server 1.0.0-rc1

Server Setup:
Windows Server 2012 R2
IIS 8.5

Anything I can do to get that fixed?

**Comment by moozzyk** [comment]
Does this still happen with latest bits? If so, can you file this in the https://github.com/aspnet/SignalR-Server repo?

**Comment by DOMZE** [comment]
I actually have the RC2 bits and it is still happening....

**Comment by DOMZE** [comment]
To those who might have the same problem. Install WebSocket on IIS. That solved the problem

**Comment by MaklaCof** [comment]
I can confirm that DOMZE solution also works for WebSocket Core on IIS.
`<PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.0.0-alpha2-final" />`
