### ISSUE TITLE
Signalr Not working on Internet Explorer 11

### ISSUE THREAD

**Issue by RakeshYadvanshi** [SignalR/SignalR#3695]
hi 
I am working on signalr2. 
chatting app.

Every thing working fine on firebox and chrome but same app not working on IE 11

then i download the moving shape demo from asp net site to  confirm whether i miss something in my code.

but same problem occur.
so can any one tell me is there any problem signalr or any compatibility or i have problem in my code

you can check my chatting app on signalr2.somee.com

**Comment by ravikp** [comment]
What error are you getting?

**Comment by IanYates** [comment]
Are you using promises?  IE11 doesn't have a built-in promise object and you'll need to use a polyfill.

Also, if you're using IE 11 on Win 7 then websockets aren't available?  Are you forcing use of websockets perhaps?

**Comment by rakeshyadvanshi** [comment]
Thanks @ravikp  and @IanYates 

when i call server message, it always goes to failed call back..

New thing i noticed is that its only my internet explorer, i have checked on my office IE 11 . it is working.
I more thing it is very hard to troubleshoot in internet explorer. any guidance !!

**Comment by rakeshyadvanshi** [comment]
I enabled logging and get this message

[17:09:24 GMT+0530 (India Standard Time)]  SignalR: Invoking chathub.SendToFriend
[17:09:26 GMT+0530 (India Standard Time)] SignalR: chathub.SendToFriend failed to execute. Error: Error: Send failed.

**Comment by ravikp** [comment]
Hi, can you use fiddler to trace requests and responses?

**Comment by rakeshyadvanshi** [comment]
POST /signalr/send?transport=foreverFrame&clientProtocol=1.5&Name=sjlfs&connectionToken=Kho%2BBZzIyZCwuh7wIAKVkxzRc%2F%2BKFcrBu8rPVI5yytq8INjy3qyuwqIe9CpCeaBhEMcPqBVXxpXX%2ByASucxJRsi0bE1Fpz7%2F0fRltsEDJF2LXb5lmrtqHL0EgeysGBH1&connectionData=%5B%7B%22name%22%3A%22chathub%22%7D%5D HTTP/1.1


when i start my page where signalr is implemented, i get 500 server error on above call 


![request](https://cloud.githubusercontent.com/assets/12479939/15627475/11159c46-2503-11e6-904d-86928afe7d00.png)
![response](https://cloud.githubusercontent.com/assets/12479939/15627477/1121d10a-2503-11e6-86a9-40683853ec57.png)
![response web view 1](https://cloud.githubusercontent.com/assets/12479939/15627476/111ee328-2503-11e6-908b-4eb446b804d2.png)


Same error came when is send message

**Comment by moozzyk** [comment]
@RakeshYadvanshi - do you do anything special in your app? Can you share the code? It seems like the same issue as #3697 where the send request is sent with empty body. Does it work if you use https instead of http?

**Comment by RakeshYadvanshi** [comment]
Hi @moozzyk  . First thing first.
First open Facebook in IE 11 where signal r is not working. and try to  send message from the messenger
if your message get delivered.

Then i think your problem is not same as that of me

if not delivered then i suggest try to send message from another machine's IE 11. 
i Hope your message would be send.

At last I think this is problem with IE 11 ,not with signalR ,same code was working on one machine not on other

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
