### ISSUE TITLE
CustomUserIdProvider : IUserIdProvider Exception

### ISSUE THREAD

**Issue by zyz** [SignalR/SignalR#3698]
/// <summary>
    /// 时间：2016.02.21
    /// 描述：自定义signalr连接id
    /// </summary>
    public class CustomUserIdProvider : IUserIdProvider
    {
        /// <summary>
        /// 时间：2016.02.21
        /// 描述：使用当前登录的用户id作为连接id
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        public string GetUserId(IRequest request)
        {
            var curUser = LoginManager.CurrLoginUser;
            return curUser?.UserId.ToString() ?? string.Empty;
        }
    }

System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Met365.Tool.CommonHelper.GetPlatformType()
   在 Met365.Common.LoginManager.IsProxy(LoginUser& loginUser)
   在 Met365.Common.LoginManager.get_CurrLoginUser()
   在 Met365.Profile.Hubs.CustomUserIdProvider.GetUserId(IRequest request)
   在 Microsoft.AspNet.SignalR.PersistentConnection.ProcessRequestPostGroupRead(HostContext context, String groupsToken)
   在 Microsoft.AspNet.SignalR.PersistentConnection.<ProcessRequest>b__0(String g, PersistentConnection pc, HostContext c)
   在 Microsoft.AspNet.SignalR.TaskAsyncHelper.GenericDelegates`5.<>c__DisplayClass5a.<ThenWithArgs>b__59(Task`1 t)
   在 Microsoft.AspNet.SignalR.TaskAsyncHelper.TaskRunners`2.<>c__DisplayClass45.<RunTask>b__44(Task`1 t)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 Microsoft.Owin.Mapping.MapMiddleware.<Invoke>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 Microsoft.Owin.Cors.CorsMiddleware.<Invoke>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage.<RunApp>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.<DoFinalWork>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 Microsoft.Owin.Host.SystemWeb.Infrastructure.ErrorState.Rethrow()
   在 Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar)
   在 Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.EndFinalWork(IAsyncResult ar)
   在 System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   在 System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Excuse me what reason be?How to solve?
请问是什么原因？如何解决？

**Comment by IanYates** [comment]
The exception is coming from whatever `Met365.Tool.CommonHelper.GetPlatformType()` is.  That's not a SignalR type.  My guess is that the method `Met365.Profile.Hubs.CustomUserIdProvider.GetUserId(IRequest request)` doesn't have sufficient information to get the userId and ends up passing some null reference deeper into that `Met365` code (maybe the user's not found?) and you get your null reference exception.

In any case, it's not a SignalR issue.  I suggest you post some more code and context (does this happen all the time, what is `Met365`, etc) on a site like stackoverflow.com.

**Comment by zyz** [comment]
Signalr
HttpContext.Current.Request.Cookies
I use HttpContext in Signalr
How do I use the Httpcontext?

**Comment by moozzyk** [comment]
Have you tried this: http://stackoverflow.com/questions/12472940/signalr-and-httpcontext-session
