### ISSUE TITLE
NPM Package

### ISSUE THREAD

**Issue by Vaccano** [SignalR/SignalR#3700]
Most of the web development world uses NPM.  It would be nice if there were a package for this in NPM that was created by Microsoft.  (I could not find one.)

**Comment by drcmda** [comment]
Please do. SignalR is a foreign element in any modern build system right now.

**Comment by Vaccano** [comment]
I have to admit that I am astounded that Microsoft does not push this to NPM.  

It is like creating a masterpiece of art and then only showing it to those in your neighborhood.

**Comment by alextkachuk** [comment]
There is unofficial NPM package - https://github.com/dfrencham/ms-signalr-client

It would be extremely useful to have official NPM package, but it needs a lot of work, For example, SignalR strongly depends on window.jQuery.

**Comment by sondreb** [comment]
The "signalr" package has changed ownership to Microsoft, so I guess perhaps this is now the official package now?

https://www.npmjs.com/package/signalr

(Updated to 2.2.2 today)

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
