### ISSUE TITLE
Ordered message delivery issue

### ISSUE THREAD

**Issue by saurabhvats007** [SignalR/SignalR#3701]
Hi,

I am using SignalR client libraries(both .Net & Javascript version 2.0.3) persistent connection functionality for getting realtime data from a Api. I noticed that signalr is intermittently raising "received" event for a message received at later timestamp earlier. I noticed that this happens when the timegap between the two messages is in milliseconds. So say if two messages M1 and M2 arrives at websocket in that order within a difference of milliseconds intermittently "received" event for M2 is getting raised earlier. I relied on Chrome (Web socket frame filter) and Fiddler logs  for checking delivery time of messages. So in chrome and fiddler M2 message was logged after M1 but in signal R I got the event of M2 message first.

thanks,
Saurabh

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
