### ISSUE TITLE
Provide cancellation token to signalr client

### ISSUE THREAD

**Issue by shlatchz** [SignalR/SignalR#3702]
How do I provide a cancellation token to a signalr client, so that I'll be able to stop a long-polling operation?

Can I somehow add it to the `HubConnection` or `HubProxy` or the underlying `HttpClient`?

I didn't find anything on Google :(

Please help.

**Comment by moozzyk** [comment]
Can't you just stop the connection?

**Comment by shlatchz** [comment]
I prefer not to have to stop it explicitly.

**Comment by moozzyk** [comment]
You can't just stop pending long polling connection without stopping the client. Can you register a callback which will stop the client when your token is cancelled?

**Comment by shlatchz** [comment]
I tried what you ask, but for some reason when I run

    hubConnection.Close();

the connection doesn't close! I tried

    hubConnection.Dispose();

and in different Task contexts, but nothing helped. Why won't it close? :(

**Comment by moozzyk** [comment]
Stop should just close the connection. If it still does not work for you open a new issue and provide the repro. Not sure what do you mean by "connection wasn't successfully created" - if starting connection fails an exception will be thrown you will know that there is no point in stopping the connection. In any case - stopping a stopped connection is a no-op - https://github.com/SignalR/SignalR/blob/dev/src/Microsoft.AspNet.SignalR.Client/Connection.cs#L633
