### ISSUE TITLE
SignalR sometimes decoding with wrong charset (.NET client)?

### ISSUE THREAD

**Issue by petermorlion** [SignalR/SignalR#3704]
I have a Windows service that publishes data to a .NET (WPF) client and a web client over SignalR. I'm having some funny issues with the .NET client, but can't quite get a consistent behavior.

The problem lies in serializing the degrees sign, i.e. "°C". Most of the time it is serialized correctly, but I've had a few times where I see the following in my debugger:

![](http://i.stack.imgur.com/h49uS.png)

See how the first time the "°" is serialized correctly, but the second time we see the question marks in the diamonds?

I've read this means it is an invalid UTF-8 character. But then why do all the other properties serialize correctly? This is a screenshot where you see one correct and one incorrect, but the entire JSON contains hundreds of these "°C" strings that look correct.

Using Fiddler, I can see what bytes are being sent:

![](http://i.stack.imgur.com/oBEo4.png)

Notice how it says "Â°C" instead of "°C". This may be due to Fiddler using the wrong encoding? I believe SignalR uses UTF-8. UTF-8 uses 0xC2 0xB0 for '°', but in Windows-1252, this maps to "Â°", which is what we're seeing.

This doesn't seem to be a problem initially, as all these 0xC2 0XB0 bytes are being decoded to "°", so using UTF-8. But apparently, a few of them are being decoded as "Â°". So is SignalR using Windows-1252 at some points? That would seem strange to me.

I realize this is a challenging issue (at least for me). So I'm not expecting an immediate solution, but any help on how to debug or investigate this issue would be greatly appreciated.

**Comment by jetshi0125** [comment]
hi,i have met the same errors. Have you find a way to correct it ? Thanks!

**Comment by petermorlion** [comment]
Hi @jetshi0125, I am no longer on the project so I can't follow-up on this. Though I never found a way, and I don't think it is a priority at the moment. If there ever is a solution, I will send it to the team, but as for now, I can no longer check this out. I'm sorry and hope you find a solution.

**Comment by Shaddix** [comment]
having exactly the same issue.
My data is mostly in Russian, and 99% of the text is correct, but few random symbols are received as (0xEF 0xBF) which is wrong.
Will try to do base64 encoding, but that's really awful :(

**Comment by capfy** [comment]
Thank you Shaddik.
Thai language found about this problem too. I found issue occured with OS's client which below Windows 8.

**Comment by moabtools** [comment]
Found the same issue for russian language. Windows 7, both server and client are .NET (no JQuery).

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
