### ISSUE TITLE
Impersonated Account Lost in Threading

### ISSUE THREAD

**Issue by lkspencer** [SignalR/SignalR#3706]
In some situations, the threading used for the SQL scale out causes the impersonated account to be lost. If IIS is setup to use impersonation for a vdir on an app inside of an app pool, and the app pool has its own identity, the threading inside of the Sql MessageBus and SqlReceiver do not hand off the impersonated identity properly.

**Comment by moozzyk** [comment]
I was not aware of this issue and the PR you made. Can you provide repro steps (unless you think the setup you described in the description is enough). We are closing on 2.2.2 release now so I put this bug in the vNext milestone so that we not miss it again.

**Comment by lkspencer** [comment]
Hi, thank you for reaching out to me about this pull request. I'm working
with our server admins to see if these coding changes are actually needed.
I did further research and we *might* be able to get around this issue by
using the settings per the following SO post:
http://stackoverflow.com/a/31526599/1016754

If that's the case, I might just change the pull request to clarify the
documentation for those of us that are running applications with
impersonation. If you have any experience with setting
<alwaysFlowImpersonationPolicy enabled="true"/> and
<legacyImpersonationPolicy enabled="false"/>, we have a meeting later today
with our admins and our MS reps, so any insight you can provide that I can
bring to them would be helpful. If you would like to join the meeting, Mike
Finley (one of our MS reps) setup the meeting and could probably get you
added in.

I'll let you know if we get this tested out on our dev servers as the
change to SignalR might not be needed, but better documentation around this
situation would be good to have and I can submit a PR for that if you would
like.

Thanks!
Kirk

**Comment by moozzyk** [comment]
Thanks @lkspencer - please update this thread with your finding. Unfortunately I don't know how alwaysFlowImpersonationPolicy/legacyImpersonationPolicy affect impersonation.

**Comment by lkspencer** [comment]
I wanted to follow up on the settings mentioned above. After getting time within our company to test the `<alwaysFlowImpersonationPolicy enabled="true"/>` and `<legacyImpersonationPolicy enabled="false"/>` settings on the server I can confirm that it does cause the identity to properly flow to the child threads.

More information about these flags can be found [here](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/alwaysflowimpersonationpolicy-element) and [here](https://weblogs.asp.net/owscott/setting-an-aspnet-config-file-per-application-pool).

There's an important requirement for those settings to work: Windows Server 2008 R2 (IIS 7.5) or higher, so this could still be considered a bug if you intend to support older platforms.

For anyone seeing this through a google search I'd also like to point out that if you attempt to pull and implement #3707 on your own, it only has updates to the code where threads are being created manually in the SqlServer backplane project. You many encounter other issues with threads being created randomly when the server is under load which has to do with all the async/await code in SignalR that #3707 does not address.

Lastly, I still think an option to manually hand off impersonated identities to child threads should be added in since not everyone has the capability on their servers to make the changes listed above.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
