### ISSUE TITLE
jQuery v3.0.0 is unsupported

### ISSUE THREAD

**Issue by AntiFreez** [SignalR/SignalR#3710]
I have updated to jQuery v3.0.0 and caught error:
```
Uncaught TypeError: url.indexOf is not a function
jQuery.fn.load @ jquery.js:9612
(anonymous function) @ jquery.signalR.js:250
(anonymous function) @ jquery.signalR.js:976
```

**Comment by gerardolima** [comment]
Hi, guys, this event is deprecated since [jQuery version 1.8](http://api.jquery.com/load-event/). What do you think about checking other deprecated dependencies from times to times?

**Comment by FlexHelper** [comment]
I dont understand.. 

Oka Jquery don't have .load anymore..? eh

Hmm when i read Document of jquery and Signalr Javascript

I understand the issue

Signalr Use old style


So lets fix the issue


Go in ur Signalr File  ex.:  jquery.signalR-2.2.0.min.js

Replace e.load with $


:) dooone now it will work ;) good luck
