### ISSUE TITLE
ITransportHeartbeat.GetConnections() gets me disconnected connections

### ISSUE THREAD

**Issue by raghav-khunger** [SignalR/SignalR#3711]
We are getting the exact problem mentioned here http://stackoverflow.com/questions/17402726/itransportheartbeat-getconnections-gets-me-disconnected-connections

i.e ITransportHeartbeat.GetConnections() is giving us the connections which do not exist anymore.

We are calling that method after every minute to maintain presence of all users

Is this a known issue? 

We are using the latest version of Signalr i.e Microsoft.AspNet.SignalR.Core.dll (2.2.0)

**Comment by dimkanewtown** [comment]
Are you looking at the IsAlive property on the retrieved connection.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
