### ISSUE TITLE
Redis Scaleout - Default Db from ConnectionString is ignored

### ISSUE THREAD

**Issue by zivillian** [SignalR/SignalR#3714]
The StackExchange.Redis Connectionstring allows to specify the default db id ([Documentation](https://github.com/StackExchange/StackExchange.Redis/blob/master/Docs/Configuration.md#configuration-options)). This option is currently overwritten by the default value (0) of RedisScaleoutConfiguration.Database

**Comment by rpannell** [comment]
+1  I like to have the database separate for functionality and was shocked that this forced database 0 which I don't want to move around.

**Comment by moozzyk** [comment]
Fixed in 38405a7d5f6944528ee9a70201f30f176e0355e1
