### ISSUE TITLE
signalR and network programming

### ISSUE THREAD

**Issue by masoud-moghini** [SignalR/SignalR#3717]
Hi ,
I'm gonna learn signalR and network programming by C#.one question that raised for me is that is there any overlap between their functionalities ?about differences ?
and by deep-learning of signalR is there any reason to study
[Network Programming in the .NET Framework](https://msdn.microsoft.com/enus/library/4as0wz7t(v=vs.110).aspx)?
excuse me if the question was so trivial.

**Comment by moozzyk** [comment]
SignalR is built on top of HTTP protocol. Network programming is at much lower level. When working with SignalR you don't deal directly with sockets TCP/IP etc.
