### ISSUE TITLE
SingalR didn't invoke server side method and broadcast data back to client side

### ISSUE THREAD

**Issue by LarissaChangLiu** [SignalR/SignalR#3719]

**Comment by ChunkNorriss** [comment]
Hello!
I have same problems, but I found solution. Probably you creates subscriptions on hubs after calling $.connection.hub.start().

It's important to create all subscriptions before calling $.connection.hub.start().
On http://www.asp.net/signalr/overview/guide-to-the-api/hubs-api-guide-javascript-client
in section 
"How to establish a connection"
Before you can establish a connection, you have to create a connection object, create a proxy, and register event handlers for methods that can be called from the server. When the proxy and event handlers are set up, establish the connection by calling the start method.

I believe it help you!
