### ISSUE TITLE
Error when starting a signalr selfhost server, stopping, then starting it again

### ISSUE THREAD

**Issue by togakangaroo** [SignalR/SignalR#3720]
[Cross posted from StackOverflow](http://stackoverflow.com/questions/37870118/cannot-shut-down-and-start-new-signalr-using-owin-self-host) because I'm really at the limit of my resources here and trying everything.

I've gotten it down to the bear minimum and I'm at an absolute loss

I start a SignalR webserver using owin selfhost (katana), connect to it. I shut it down, and then I start it and try to connect to it again. 

On the **second** time through (it works just fine the first time) I get an error while trying to initiate a connection:

```
public partial class App : Application
{

    void App_Startup(object sender, StartupEventArgs e)
    {
        using (var server = new TestWebServer()) {
            server.Start();
            using (var hubConnection = new HubConnection(TestWebServer.Host)) {
                var proxy = hubConnection.CreateHubProxy("testHub");
                hubConnection.Start().Wait();
                Debug.Assert(hubConnection.State == ConnectionState.Connected);
            }
        }

        // Makes it here fine

        using (var server = new TestWebServer()) {
            server.Start();
            using (var hubConnection = new HubConnection(TestWebServer.Host)) {
                var proxy = hubConnection.CreateHubProxy("testHub");
                hubConnection.Start().Wait(); //<-throws "Transport timed out trying to connect"
                Debug.Assert(hubConnection.State == ConnectionState.Connected);
            }
        }
    }
}
```

With `TestWebServer`:

```
public class TestWebServer : IDisposable {
    public const string Host = "http://localhost:8081/";
    public void Start() {
        if (null != server) return;
        this.server = WebApp.Start(Host, app => {
            var cfg = new HubConfiguration { };
            app.MapSignalR(cfg);
        });
    }
    IDisposable server;

    //Super-duper-for-real disposable https://lostechies.com/chrispatterson/2012/11/29/idisposable-done-right/
    bool _disposed;
    public void Dispose() {
        Dispose(true);
        GC.SuppressFinalize(this);
    }
    ~TestWebServer() {
        Dispose(false);
    }
    protected virtual void Dispose(bool disposing) {
        if (_disposed)
            return;
        if (disposing) {
            if (null == server) return;
            server.Dispose();
            server = null;
        }
        _disposed = true;
    }

}
```

And `TestHub`

```
[HubName("testHub")]
public class TestHub : Hub {
    public void Ping() => Clients.All.pong();
}
```

This is using SignalR 2.2.0 and I've tried both on .Net 4.5 and 4.6.1

This is as simple a SignalR application as I possibly know how to make it and you notice it works! Once. Then it fails when I dispose and try the exact same code again.

What is going on? Is there something else that I need to do to dispose of things?

Yes, I've tried to `Thread.Sleep` between the two.

[Here is a tester project demonstrating the issue](https://github.com/togakangaroo/SignalRHasIssues)

**Comment by moozzyk** [comment]
Seems to be resolved on SO.

**Comment by togakangaroo** [comment]
What is SO?

**Comment by togakangaroo** [comment]
@moozzyk It is resolved on SO but if this is intended behavior then 

a) I would suggest revisiting that since it causes incredibly confusing sideffects
b) Documenting the crap out of it. It's a nightmare to track down

**Comment by moozzyk** [comment]
OK. I am reopening for now and will revisit to get to the bottom of this.

**Comment by togakangaroo** [comment]
Thanks. I appreciate it. Hope something can be decided on in the future.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
