### ISSUE TITLE
Redis scale out duplicate messages

### ISSUE THREAD

**Issue by bakman23** [SignalR/SignalR#3721]
Hi, 
I receive lot of duplicate (flood) message when using Redis scaleout on azure.

Here my conf on my server
`var redidString = "xxx.redis.cache.windows.net:6380,password=xxx ssl=True,abortConnect=False";
            RedisScaleoutConfiguration conf = new RedisScaleoutConfiguration(redidString, "xxx");
            GlobalHost.DependencyResolver.UseRedis(conf);
app.MapSignalR();`

If I remove the conf the messages works normaly

Any idea?

**Comment by moozzyk** [comment]
Are you using a Redis cluster? If so you are probably running into this: https://github.com/SignalR/SignalR/issues/3765

If this is not this issue then you need to provide more details.
