### ISSUE TITLE
.Net Core support?

### ISSUE THREAD

**Issue by ryanlin1986** [SignalR/SignalR#3723]
.Net Core is RTM now, is there any roadmap update for singlar? We having a large project depend on this feature, please give us a little hint.

**Comment by IanYates** [comment]
It's on Twitter, so it must be true 😜 

https://twitter.com/davidfowl/status/747476833994629121

It's consistent with what was stated during some of the ASP.Net standups - they'd get back to SignalR after ASP.Net Core was released.  On a recent DotNetRocks episode they mentioned they've got a new release (2.2.1?) that just needs some internal stress testing and it's good to go - I guess it'd be much the same as what's already in master in this repo.

**Comment by Janisku7** [comment]
it's in working now as it's shipped Scott Hunter told that Damian and David fowl are working on it

**Comment by ryanlin1986** [comment]
Thanks for the heads up, it is the main road blocker to migrate .Net Core.

**Comment by moozzyk** [comment]
https://github.com/aspnet/SignalR-Server/issues?q=is%3Aissue+is%3Aopen+label%3Aplanning
