### ISSUE TITLE
Remove Chat Room Link from README.md 

### ISSUE THREAD

**Issue by TheXenocide** [SignalR/SignalR#3725]
Just as a matter of not misleading people; if nobody from the team is going to be in the room, it isn't useful (and is, in fact, counterproductive) to direct those who would be seeking guidance there.

**Comment by rogersachan** [comment]
I honestly think it would be better if we based ourselves in ASP.NET gitter instead, since that's actually where most people *complain* about SignalR and the **inaction** with fixing jQuery issues.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
