### ISSUE TITLE
Connection was disconnected before invocation result was received

### ISSUE THREAD

**Issue by eisbear77** [SignalR/SignalR#3726]
In one of my WCF-Services (stateless), I want to send a message via SignalR. Because the service is stateless, and the hub is on another machine, I connect to SignalR, send the message, and disconnect.

proxy.Connect().Wait();
proxy.SendMessageToUsers(receiverUserNames, message).Wait();
proxy.Disconnect();

From time to time, there are InvalidOperationExceptions (Connection was disconnected before invocation result was received).

I understand from this post (http://stackoverflow.com/questions/32315651/c-sharp-signalr-exception-connection-started-reconnecting-before-invocation-re) that .Wait is not a good idea. But I think I need to wait for Connect and SendMessage to complete, before disconnect.

So, what else can I do?

Best regards,
Stefan

**Comment by moozzyk** [comment]
Closing based on the SO thread.

**Comment by vivekbrnl** [comment]
@moozzyk  I did not understand the solution or reason of closing this issue. can you please elaborate.
