### ISSUE TITLE
Enforce Strict Transport Security 

### ISSUE THREAD

**Issue by maquert85** [SignalR/SignalR#3728]
Hi:

There is a way to enforce Strict Transport Security in SignalR request? 

Regards...

**Comment by davidfowl** [comment]
Are you asking if it's possible to set a header?

**Comment by maquert85** [comment]
Thanks for reply.

Well, thats the main idea, yes. Im only interested in Strict Transport Security flag be enabled in SignalR request. I tried this threads, with no result:

http://forums.asp.net/t/1910020.aspx?Add+custom+HTTP+header+on+client+side+connect+call+SignalR+1+1+1+

https://github.com/SignalR/SignalR/issues/2099

https://github.com/SignalR/SignalR/issues/270

Im sendig requests in a MVC project using default MVC`s engine ([HttpPost] and [HttpGet]). I was able to enforce the Strict Transport Security, but I cant see a way to do the same with SignalR request.

I´ll post a couple of pictures about this soon.

Thanks in advance...

**Comment by navcoder** [comment]
Hi,
Any update on how to add header in the JSclient?

Thanks in advance.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
