### ISSUE TITLE
Race in Redis scaleout when the connection is restored

### ISSUE THREAD

**Issue by moozzyk** [SignalR/SignalR#3729]
Looks like when a connection to Redis is restored the event handler can be called more than 1 time. 

![image](https://cloud.githubusercontent.com/assets/1438884/16677402/60e513b8-448a-11e6-8efb-cc579e6a2977.png)

We would then reset the key in Redis multiple times.

**Comment by davidfowl** [comment]
Seems like a bug in the redis client... (not saying we shouldn't try to be resilient)

**Comment by moozzyk** [comment]
Agreed. Getting more than one event is unexpected. We are however using quite an old version of StackExchange.Redis so before raising this it would be good to verify it actually does happen with the latest.

**Comment by moozzyk** [comment]
Looks like the ConnectionType for the events is different - one of the events has ConnectionType.Interactive while the other has ConnectionType.Subscription. I also found this: https://github.com/StackExchange/StackExchange.Redis/issues/60 which tells me this is most likely by design and we should handle this on our side.
