### ISSUE TITLE
Azure issues [serverSentEvents transport failed during the start request]

### ISSUE THREAD

**Issue by awesomegithubusername** [SignalR/SignalR#3734]
Hello everyone;

SignalR version: 2.2.0.0

I'm having an issue with running SignalR in Azure. Locally, everything's fine but in Azure, the log looks like this

```
[15:07:15 GMT+0100 ] SignalR: EventSource connected.
[15:07:15 GMT+0100 ] SignalR: serverSentEvents transport connected. Initiating start request.
[15:07:15 GMT+0100 ] SignalR: serverSentEvents transport failed during the start request. Stopping the connection.
[15:07:15 GMT+0100 ] SignalR: Stopping connection.
[15:07:15 GMT+0100 ] SignalR: EventSource calling close().
[15:07:15 GMT+0100 ] SignalR: Fired ajax abort async = true.
[15:07:15 GMT+0100 ] SignalR: The start request aborted because connection.stop() 
```

I've got to mention that it DOES work from Microsoft Edge in Windows 10 Mobile. 

Tested in Windows 7 from the following browsers:

```
          -Google Chrome Version 51.0.2704.106 m (64-bit)
         - Mozilla Firefox 47.0.1 and Firefox Dev Edition 49.0a2 (2016-07-12)
          -Opera Beta 39.0.2256.21 
```

**Comment by awesomegithubusername** [comment]
[This](https://github.com/SignalR/SignalR/issues/3659) worked for me. Not sure if it's safe though.

**Comment by moozzyk** [comment]
Are you running multiple servers?

**Comment by awesomegithubusername** [comment]
> Are you running multiple servers?

No

**Comment by moozzyk** [comment]
You should not have to implement `IDataProtectionProvider` to use SignalR. I would recommnend digging into the issue and understand what the problem is - it is on the server side so from your description it is impossible to tell what's going on. Check the exception that is being thrown on the side. 

I believe that with the IDataProtectionImplementation you showed above SignalR  will send things that are supposed to be encrypted as cleartext.

**Comment by awesomegithubusername** [comment]
That is my concern, too. Could anyone confirm that messages are no longer encrypted with this implementation?

**Comment by moozzyk** [comment]
It's not about messages - the messages are not being encrypted by SignalR - rather you should use https. It is about the url parameters like connectionToken etc.

**Comment by awesomegithubusername** [comment]
Thanks for clearing that up.

**Comment by moozzyk** [comment]
Likely a machine key does not exist and needs to be generated.

**Comment by JerryCBH** [comment]
This worked for me: Azure WebApps is configured to not load user profile by default, this causes the exception. In Azure App Settings, create an Application Setting called WEBSITE_LOAD_USER_PROFILE and set it to 1. This will load the user profile.

https://www.magnetismsolutions.com/blog/jaredjohnson/2015/12/18/resolving-cryptography-issues-with-the-dynamics-crm-sdk-in-azure-web-apps
