### ISSUE TITLE
Mismatch between package dependency and assembly reference in UWP Client

### ISSUE THREAD

**Issue by anurse** [SignalR/SignalR#3736]
The UWP Client DLL has a reference to Newtonsoft.Json 7.0.0, but the Microsoft.AspNet.SignalR.Client nuspec references 6.0.4, resulting in Assembly Load failures.

**Comment by akgaurav** [comment]
I am facing the same issue. Not able to use Newtonsoft 9.0.0.0. Please let me know the fix.

**Comment by moozzyk** [comment]
This was a mismatch between the dependency in project.json file and the generated nuspec and it was fixed. I believe NuGet should add binding redirects if to your web.config file if you try to use a later version of JSON.NET in your project which should enable using JSON.NET 9.0.0.0 and SignalR.
