### ISSUE TITLE
SignalR Javascript Cannot work With JQuery

### ISSUE THREAD

**Issue by Vaccano** [SignalR/SignalR#3738]
When I run my app I get the following error:

> Uncaught TypeError: url.indexOf is not a function

This is beasue of the following line in jquery.signalr-2.2.0.js:

      _pageWindow.load(function () { _pageLoaded = true; });

JQuery no longer supports the `.load` method.  These all need to be changed to `.on('load'`.  `.unload` and `.error` are also dropped from JQuery.

**I really like using SignalR, but Do I somehow need to download both an old and a new version of JQuery to use it?**  

If so, how can I have all my code use the real JQuery, but have SignalR use the old stuff?

**Comment by moozzyk** [comment]
Dupe of https://github.com/SignalR/SignalR/issues/3710. This is getting fixed in 2.2.1

**Comment by FlexHelper** [comment]
Replace e.load whit $ in your signalr file

Then done :)
