### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pinginterval' of undefined" error+signalR

### ISSUE THREAD

**Issue by rajaashutosh** [SignalR/SignalR#3739]
Hi @Xiaohong Tang,

I am using MVC4, jquery.signalR-2.0.2.js, some time we are getting below error 

"Uncaught TypeError: Cannot read property 'pinginterval' of undefined" error"

Any idea or solution for the same.

Thanks and Regards,
Raja

**Comment by moozzyk** [comment]
A dupe of #2865. Seem like you need to update to a newer version of the client.
