### ISSUE TITLE
Needs server-side forcible disconnect of client.

### ISSUE THREAD

**Issue by uclaitsscott** [SignalR/SignalR#3740]
Unwanted users can flood server and server admins/devs are left with no recourse. Implementing authorization only slows the malicious user down long enough to register another account and it is impossible to keep up with malicious users creating accounts. There should be a forcible disconnect of a client from the server code upon whatever conditions the developer deems logical.

**Comment by moozzyk** [comment]
It is very unlikely that this feature would be implemented in v2 server. We are however discussing it for the Core server see: https://github.com/aspnet/SignalR-Server/issues/162 and https://github.com/aspnet/SignalR-Server/issues/196
