### ISSUE TITLE
Accessing connection id in context of IRequest?

### ISSUE THREAD

**Issue by HassanHashemi** [SignalR/SignalR#3742]
Is there a way to access connection id in context IRequest interface which is used in implementation of IUserIdProvider?

I have also asked  question here on [SO](http://stackoverflow.com/questions/38409991/signalr-access-connection-id-in-custom-useridprovider).

**Comment by davidfowl** [comment]
What exactly are you trying to do?

**Comment by HassanHashemi** [comment]
i want to map ConnectionId to UserId which i generate some how.
more curious why it`s not available in IRequest context?
