### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found) signalr/hubs

### ISSUE THREAD

**Issue by hamadKhan21** [SignalR/SignalR#3745]
Hi there, 
I have deployed my project of Signalr in mvc 5, which works fine locally but gives this error 404 not found signalr/hubs js file on server IIS8.
Please i need ur help how to fix it? i have spent hours but couldnt find the solution
Regards

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
