### ISSUE TITLE
Only support .NET4.5? Is not support .NET CORE?

### ISSUE THREAD

**Issue by SkyWaterXXS** [SignalR/SignalR#3746]

**Comment by Worthaboutapig** [comment]
Who knows what's going on?  MS seems to have just left people hanging on this.

The .NET Core project is completely separate and over here: https://github.com/aspnet/SignalR-Server

**Comment by SkyWaterXXS** [comment]
thank you

**Comment by davidtillery** [comment]
What about a .NET Core client?

**Comment by moozzyk** [comment]
This repo is for 1.x 2.x versions of SignalR. The repos for the ASP.NET Core version of SignalR are under the aspnet organization (e.g. https://github.com/aspnet?utf8=%E2%9C%93&query=SignalR). Planning for the ASP.Net Core version has started. You can find some here: https://github.com/aspnet/SignalR-Server/issues/196
