### ISSUE TITLE
IHubProxy.Invoke in foreach

### ISSUE THREAD

**Issue by 12343954** [SignalR/SignalR#3747]
my code doesn't execute

`
private void button1_Click(object sender, EventArgs e)
        {
            var hubConnection = new HubConnection("http://cruise.uniway.org:48008/");
            
            textBox2.Text = "";
            textBox2.Text += string.Format("hubConnection.State = {0} \r\n\r\n", hubConnection.State);

            IHubProxy myHubProxy = hubConnection.CreateHubProxy("BookingHub");

            hubConnection.Start().Wait();
            textBox2.Text += string.Format("start hubConnection.State = {0} \r\n\r\n", hubConnection.State);

            Control.CheckForIllegalCrossThreadCalls = false;

            #region //call "StopBooking" server method
            //StopBooking(string cruise, string room, string saler, string roomType, bool flag)

            string[] rooms =  "1234,1232,1230,1228".Split(',');
            string message = "";

            foreach (var room in rooms)
            {
                myHubProxy.Invoke("StopBooking", "Cruise-01-20140701", room, "console", "EP", checkBox1.Checked).ContinueWith(task =>
                {
                    if (task.IsFaulted)
                    {
                        //message += string.Format("!!! There was an error opening the connection:{0} \r\n\r\n", task.Exception.GetBaseException());
                    }
                    else
                    {
                        //message += string.Format("StopBooking success  {0}\r\n\r\n", room);
                    }

                }).Wait();            **// seemed the UI thread to be blocked**
            }
            //textBox2.Text = message;
            checkBox1.Checked = !checkBox1.Checked;

            #endregion

            hubConnection.Stop();
        }
`

but `**string[] rooms =  "1234";**` can be executed !
why ?

**Comment by 12343954** [comment]
i got it ！ thought i don't know why ！

`}).Wait(10);            **// seemed the UI thread to be blocked** `

**Comment by sickboy** [comment]
@12343954 use ```private async void button1_Click(object sender, EventArgs e)```
and instead of `.Wait()` at the end of the calls, use await in front of the calls.

**Comment by 12343954** [comment]
@sickboy thank you, i will try

**Comment by moozzyk** [comment]
You are causing a deadlock using the .Wait() function on the UI thread. You can find more details here: http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html
