### ISSUE TITLE
JS Client methods not called after reconnect

### ISSUE THREAD

**Issue by gtiguy92** [SignalR/SignalR#3749]
After a reconnect event, methods on the JS Client are not called if there are no methods registered with the proxy before a call to the start method. I was able to repro this bug consistently by taking the following steps:
1. Open an instance of the SignalR App, we'll call this instance **A**.
2. Recycle the IIS Application Pool that is running the SignalR App.
3. Open a second instance of the SignalR App, we'll call this instance **B**.

At this point, hub methods that are called from **A** will propagate to **B**, but methods that are called from **B** will never propagate to **A**. In this case, propagation is handled using Clients.OthersInGroup on the SignalR hub.

I identified the root cause of the issue when I noticed that my overrides for OnConnected, OnDisconnected, and OnReconneted were not being called in the SignalR hub when a method is not registered with the JS Client Hub Proxy. This seemed strange, so I tried registering a NoOp function before the call to start is made. Oddly enough, this change fixed the issue.

In summary, making the change shown below allowed the JS Client to receive method invocations after a reconnect.

**Before**
`_this.proxy = _this.connection.createHubProxy(hubName);`

`_this.connection.start(startOptions);`

**After**
`_this.proxy = _this.connection.createHubProxy(hubName);`
`_this.proxy.on('noOp', function() { });`

`_this.connection.start(startOptions);`
# **_Follow Up_**

So there is a note about this [here](http://www.asp.net/signalr/overview/guide-to-the-api/hubs-api-guide-javascript-client#establishconnection):

> Note: Normally you register event handlers before calling the start method to establish the connection. If you want to register some event handlers after establishing the connection, you can do that, but you must register at least one of your event handler(s) before calling the start method. One reason for this is that there can be many Hubs in an application, but you wouldn't want to trigger the OnConnected event on every Hub if you are only going to use to one of them. When the connection is established, the presence of a client method on a Hub's proxy is what tells SignalR to trigger the OnConnected event. If you don't register any event handlers before calling the start method, you will be able to invoke methods on the Hub, but the Hub's OnConnected method won't be called and no client methods will be invoked from the server.

I agree that no client methods will be invoked from the server, but it should specify that no client events will be invoked from the server, **_after reconnect_**.

**Comment by NickMaev** [comment]
Have the same trouble. Any ideas?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
