### ISSUE TITLE
NetworkError: 500 Internal Server Error 

### ISSUE THREAD

**Issue by zwkenyen** [SignalR/SignalR#3751]
"NetworkError: 500 Internal Server Error - http://localhost:54321/signalr/negotiate?connectionData=%5B%7B%22name%22%3A%22mtthub%22%7D%5D&callback=jQuery17202954190620542164_1469781289245&_=1469781295226"

when the web send a message to server

**Comment by zwkenyen** [comment]
my server is a console program

**Comment by moozzyk** [comment]
The server is failing to handle the request (most likely an exception is thrown on the server side). Impossible to tell what's going on with the details you provided.
