### ISSUE TITLE
OnConnected() method not invoked on Microsoft Edge with jQuery 3.1.0

### ISSUE THREAD

**Issue by erwinkramer** [SignalR/SignalR#3752]
The `public override Task OnConnected()` method is not invoked on Microsoft Edge with jQuery 3.1.0 and `jquery.signalR-2.2.1.js`.

 It's working most of the times on Firefox, IE and Chrome but i feel like it's not always calling the OnConnected() every time there as well (not tested that much). 

If I rollback to jQuery 2.2.4. everything is fine. I don't need the newest jQuery so i'm not really bothered, just letting you guys know.

**Comment by kovalevskyartur** [comment]
+1

signalr 2.2.1
jQuery 2.2.4

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
