### ISSUE TITLE
SignalR.Client exception when trying to invoke hub method from WPF application. Web proxy is present.

### ISSUE THREAD

**Issue by rgaston** [SignalR/SignalR#3753]
I get exception in SignalR.Client when I try to invoke hub method in my WPF application.

C# signature of the hub method: 

public string GetStreamingSettings()
(simple parameterless method that returns string)

Operating system: Windows 7.
Computer is a part of Windows domain.
Client: WPF application.
Server: web-application
Windows proxy server settings:  
- Automatic proxy detection. 
- Use proxy for local connections
- Don't use proxy for local adresses

Exception log:

Message :StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Transfer-Encoding: chunked
  Connection: keep-alive
  Proxy-Connection: keep-alive
  Cache-Control: private
  Date: Thu, 28 Jul 2016 16:57:50 GMT
  Server: Microsoft-IIS/8.0
  Via: 1.1 xxx.xxx.xxx:80 (Cisco-WSA/9.0.1-162)
  X-AspNet-Version: 4.0.30319
  X-Powered-By: ASP.NET
  Content-Type: text/html; charset=utf-8
}
Source :Microsoft.AspNet.SignalR.Client
Stack Trace :   в Microsoft.AspNet.SignalR.Client.Http.DefaultHttpClient.<>c__DisplayClass6_0.<Post>b__1(HttpResponseMessage responseMessage)
   in Microsoft.AspNet.SignalR.TaskAsyncHelper.<>c__DisplayClass31_0`2.<Then>b__0(Task`1 t)
   in Microsoft.AspNet.SignalR.TaskAsyncHelper.TaskRunners`2.<>c__DisplayClass3_0.<RunTask>b__0(Task`1 t)
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
TargetSite :Microsoft.AspNet.SignalR.Client.Http.IResponse <Post>b__1(System.Net.Http.HttpResponseMessage)

**Comment by moozzyk** [comment]
This is an error on the server side so the details from the client are not very helpful.

**Comment by rgaston** [comment]
moozzyk, here is zip-archive with files with the details. Please write if that's is enough to understand the problem. There is no such problem on a computer with Windows Vista that is not in the windows domain. 
[details.zip](https://github.com/SignalR/SignalR/files/406623/details.zip)

**Comment by moozzyk** [comment]
The issue seems to be that the body of the http request is missing. Can you use fiddler or turn on network tracing (https://msdn.microsoft.com/en-us/library/ty48b824(v=vs.110).aspx) to capture what is being send? 

There are several issues like this (e.g. https://github.com/SignalR/SignalR/issues/3697 https://github.com/SignalR/SignalR/issues/3374) but we have never been able to get to the bottom of it.

**Comment by rgaston** [comment]
Thank you for the answer! Here is zip-archive with Fiddler sessions captured on the client side. It is interesting that everything works fine almost all the time when Fiddler is working at the same time with the signalr client application.
[fiddler_sessions.zip](https://github.com/SignalR/SignalR/files/434529/fiddler_sessions.zip)

**Comment by moozzyk** [comment]
@rgaston - does it work if you use https instead of http?

**Comment by rgaston** [comment]
I didn't try that. And I'm not sure that I will be able to try https anytime soon.

**Comment by moozzyk** [comment]
I was wondering if this is not a proxy that is interfering and modifying the request by removing the request body. With https it wouldn't be able to look into requests and modify them.

**Comment by rgaston** [comment]
I'll definitely try that when I'll be able to.

**Comment by Perfekcjonista1618** [comment]
[https://github.com/SignalR/SignalR/issues/3697](3697)

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
