### ISSUE TITLE
SignalR is overwriting all my href and src attributes 

### ISSUE THREAD

**Issue by b26** [SignalR/SignalR#3755]
Hi, 

This doesn't happen all the time, but it happens often. Not sure exactly what's going on. 
![Here is a screenshot.](http://i.imgur.com/TxRH9f9.png)
Thanks for the help!

**Comment by b26** [comment]
I thought the issue could be when its auto generating the dynamic proxy but thats not the case. I've tried creating a physical copy of the hubs file but that also did not work. This only happens in production and not on my localhost. Has anyone had these issues before? Thanks

**Comment by moozzyk** [comment]
Not a known issue and not actionable as reported. Feel free to reopen if you have a repro or know more details.
