### ISSUE TITLE
/signalr/hubs error 404 after some time

### ISSUE THREAD

**Issue by AndrewSpec** [SignalR/SignalR#3756]
SignalR is just working fine but after some time it somehow shuts down and any client can't connect to it because of http 404 in /sirnalr/hubs...

It's nasty because it's random.

**Comment by moozzyk** [comment]
Not a known issue and not actionable as reported. A workaround can be to generate the hub.js with the ghp.exe tool as described [here](http://www.asp.net/signalr/overview/guide-to-the-api/hubs-api-guide-javascript-client) but if the server is acting up it is likely just a tip of the iceberg.

Feel free to reopen if you have more details.
