### ISSUE TITLE
Long Poll transport fails to establish connection when SQL scale out parameter TableCount is greater than 1

### ISSUE THREAD

**Issue by henkedel** [SignalR/SignalR#3757]
### Title

Long Poll transport fails to establish connection when SQL scale out parameter TableCount is greater than 1.
### Functional Impact

If TableCount is set to the value 3 then intermittently (though quite frequently) the establishment of a long poll transport connection fails and SignalR client aborts the attempt to connect and never tries again.
Client will only attempt to connect again if page is refreshed. Issue is resolved immediately if TableCount is reconfigured to the value 1.
### Minimal repro steps
1. Enable SQL scale out with TableCount value of 3 (QueueLength remains at default value)
2. Open our application's web page with long polling transport
3. Observe that ~/signalr/negotiate request succeeds
4. Observe that ~/signalr/connect request fails after 4.75s
### Expected Result

Expected the connect request to succeed.
### Actual Result

The client's connect request is responded to by the server however the response, while containing header information, has no JSON body as the client expects and this results in the connection attempt being aborted by the client.
### Technical Details

This occurs intermittently but frequently. There are no errors observed in bus/transport logs in SignalR server (verbose level).

As soon as we reconfigure the TableCount parameter to 1 the issue is immediately resolved. I did confirm that the additional tables are created in back plane database for SignalR when it is configured for 3 tables so I know that the SQL provisioning succeeded.

I have provided a summarized view of what I observe in Wireshark when the issue occurs.

28995   19:41:03.110358 10.8.10.252 10.8.11.30  HTTP    685 GET /signalr/negotiate?clientProtocol=1.5&agentKey=LmYinYinUAT-1-NotifyKey&checkAge... HTTP/1.1     44783

28998   19:41:03.113337 10.8.11.30  10.8.10.252 HTTP    60  HTTP/1.1 200 OK  (application/json) 8092

> Response to the negotiate request contains the following body:
> {
>   "Url":"/signalr",
>   "ConnectionToken":"vWgBJrsOR7Zt132RgseqK5ubK..",
>   "ConnectionId":"0f188c7c-f012-48d6-9d73-2a3105f0e420",
>   "KeepAliveTimeout":40.0,
>   "DisconnectTimeout":60.0,
>   "ConnectionTimeout":110.0,
>   "TryWebSockets":true,
>   "ProtocolVersion":"1.5",
>   "TransportConnectTimeout":5.0,
>   "LongPollDelay":0.0
> }

29028   19:41:03.369236 10.8.10.252 10.8.11.30  HTTP    820 POST /signalr/connect?transport=longPolling&clientProtocol=1.5&agentKey=LmYinYinUAT... HTTP/1.1     44783

29418   19:41:08.119486 10.8.11.30  10.8.10.252 HTTP    60  HTTP/1.1 200 OK  (application/json) (application/json)  8092

> Response to the connect request appears to arrive after some kind of timeout (~5s) within SignalR server and is empty. It does contain header information however - just no JSON body as client expects.
### Environment

Microsoft.AspNet.SignalR.Core 2.2.1.0
ASP.NET SignalR JavaScript Library v2.2.0 (and also reproduced with v2.2.1)

SignalR Server is..
Windows Server 2012R2
IIS8
ASP.NET 4.0.30319.0
SQL Server 2008

Client is..
Google Chrome Version 52.0.2743.116

**Comment by BrennanConroy** [comment]
Unable to repro the issue. You could be getting intermittent sql connection failures.
