### ISSUE TITLE
Receiving complex json with javascript client

### ISSUE THREAD

**Issue by shlatchz** [SignalR/SignalR#3760]
Hello,

I have a SignalR server written in .NET and a client in Javascript.
In the server, I have turned on the setting:

```
config.Formatters.JsonFormatter.SerializerSettings.TypeNameHandling = TypeNameHandling.All;
```

because the object that I return is very complex and contains a collection of an abstract class an so forth.
When I use a .NET client, the method that receives SignalR's result works well, but in javascript the returning data is _undefined_.

When I add the following code:

```
connection.received(function (data) {
    console.dir({received: data});
})
```

I can see that the server indeed returns the complex data, but the `.on('Bla', ...)` method doesn't get it.
Can I somehow make JQuery's json handle it? 

Thanks!

**Comment by IanYates** [comment]
Could it just be that you're subscribing to your hub client methods *after* connecting?  If you do that then it won't work without some extra hoops.  Set up your client callbacks and then start the SignalR hub connection.

**Comment by shlatchz** [comment]
My last line of code is `connection.start()` and in it my call to `proxy.invoke()`.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
