### ISSUE TITLE
FailResponse has the wrong content type & no charset

### ISSUE THREAD

**Issue by tomap** [SignalR/SignalR#3761]
Hi, 
### Actual behavior

Currently, the Content Type is set to "Text/html" and have a charset defined when the response fails.
### Expected  behavior

It should be set to "text/plain" & be utf-8
### Steps to reproduce

call /signalr/abort  url and you should get a "Protocol error: Unknown transport"

This comes from https://github.com/SignalR/SignalR/blob/799d9bc32524066344cb3656e5f28f2fd03ba9b3/src/Microsoft.AspNet.SignalR.Core/PersistentConnection.cs#L557
You should add 
response.ContentType = "text/plain";
response.Charset = "utf-8";
It might not be possible at this point to change the contenttype or charset, to you might want to try & catch this.

Note that this issue has been raised to me during a security audit with the following references:
issue#A-116 (Information) HTML does not specify charset on /site/signalr
CVSS: 3.5(AV:N/AC:M/Au:S/C:N/I:P/A:N)

Regards,

Thomas P.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Comment by gfox1984** [comment]
Well this is still actual and reported by a BURP security scan. See attached picture.

![No charset](https://user-images.githubusercontent.com/14998184/62128031-cf767000-b2d3-11e9-9a51-4d5db63c79ab.png)

**Comment by gfox1984** [comment]
@tomap , you might reopening this issue?

**Comment by tomap** [comment]
I don't mind, but cannot :)
