### ISSUE TITLE
failed: Error during WebSocket handshake: Unexpected response code: 400 

### ISSUE THREAD

**Issue by na3er-faraji** [SignalR/SignalR#3762]
hi.
The issue is handled for chrome but not for Internet Explorer
I get this error on the browser console after open 6 or 7 tab for any user:
WebSocket connection to 'ws://46.209.255.190/MabnaERP_Version/signalr/connect?transport=webSockets&clientProtocol=1.5&connectionToken=QiSFHH4jmJgSDrTEbXq%2BaKZHnewSFHuIRuEoR5jMYtyH6%2FXu3ggbyYmI4tv9l99346qdWaxXCvLYVpIApQ895vfu%2FJPJ%2B9LI3HFsbZV0RtazB%2BK5lwWnAx4sivTPzEPB&connectionData=%5B%7B%22name%22%3A%22mabnahub%22%7D%5D&tid=5' failed: Error during WebSocket handshake: Unexpected response code: 400.
Hava any advice?

**Comment by moozzyk** [comment]
Most likely you are hitting a browser limit - https://github.com/SignalR/SignalR/issues/1744

**Comment by synergyit** [comment]
I was having same issue in .Net Core Web API with Angular 8 front end. The issue in my case was the Websocket protocol was not installed on server. Installed it from Server manager -> Add Roles and Features and it worked
![2020-04-08_12-18-09](https://user-images.githubusercontent.com/10277633/78766722-10666e80-79a3-11ea-96ba-cd4686071d6b.png)

**Comment by akshaybhuradia2020** [comment]
@na3er-faraji did you solve this issue? i am getting same error when using with signalr server's farm.
#4489 please see this issue.

**Comment by na3er-faraji** [comment]
> @na3er-faraji did you solve this issue? i am getting same error when using with signalr server's farm.
> #4489 please see this issue.

yes, I just installed WebSocket on the server as @synergyit mentioned
