### ISSUE TITLE
one Hub, two path on the client Side

### ISSUE THREAD

**Issue by colbeaf** [SignalR/SignalR#3763]
Hello, 
I'm encountred issue with anonymous signal R  connexion.
On my IIS server i have two virtual url : 
- One is an authentifcated url, pointing on a website **("localhost/website/")** with windows authentification. it carry on webapi controllers and a signalr hub class named **"hubA"**. On the client Side I setup a connexion on the hub "hubA" which listen the server function. Everything works till now.

To deals with Anonymous web api call i created a second url : 
- the second one is anonymous **("localhost/website_anonymous/")** and it pointing one the same directory thant the first. 

What I want to do when i call my webApi Actions from a third party (new asp.net anonymously instance) is communicate  throught SignalR with my authentificated asp.net instance 

This is what i did on the client side : 
I created two connexion on the same Hub **"hubA"** but on two different **rootPath** : **"localhost/website/"** and **"localhost/website_anonymous/"** to listen the function call from the signalR server.

But it's not seems to work. 
Any idea ? 
Thank you

**Comment by leeroydan** [comment]
How did you get on with this?

I have a similar issue where we have one hub with 2 different client URL's accessing it, URL1 works, while URL2  doesn't. Clients accessing URL2 get disconnected after trying to connect.

I'm wondering if a SignalR hub doesn't support more than one URL, could anyone confirm this?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
