### ISSUE TITLE
404 /signalr/negotiate for deployed app in Azure

### ISSUE THREAD

**Issue by Andrey-Pavlov** [SignalR/SignalR#3769]
SignalR works on localhost but doesn't work when is deployed in Azure

Asp.net Core 1.0.0 (.Net Framework 4.6.1)
SignalR.Core 2.2.1
```
        public static void UseSignalR2(this IApplicationBuilder app)
        {
            app.UseAppBuilder(appBuilder => {
                appBuilder.MapSignalR(new HubConfiguration());
            });
            GlobalHost.HubPipeline.AddModule(new ErrorHandlingPipelineModule());
            GlobalHost.HubPipeline.AddModule(new LoggingPipelineModule());
        }
```

SignalR.js 2.2.1 with default settings
`            $.connection.hub.url = '/signalr';`

### Expected  behavior
200 for url:
https://(**name**).azurewebsites.com/signalr/negotiate?clientProtocol=1.5&connectionData=%5B%7B%22name%22%3A%22productsimporthub%22%7D%5D&_=1472811629592

### Actual behavior
_/signalr/negotiate_ - on localhost returns 200 but for deployed app in azure returns 404
_/signalr_ - works on both - Protocol error: Unknown transport.
_/signalr/hubs_ - works on both - returns the SignalR js correctly

**Comment by moozzyk** [comment]
Seems like a configuration/deployment issue and not a SignalR issue. I have a 2.2.1 site running on Azure. I also am not sure if you use Core anywhere. For the client - SignalR 2.2.1 is not ASP.NET and not ASP.NET Core base (so it's not Core). `GlobalHost` does not exist in the Core version of SignalR so it does not seem you are using these either. I would suggest asking this question on stackoverflow.
