### ISSUE TITLE
signalR showing connection timeout error even network connection is back

### ISSUE THREAD

**Issue by SusanYong123** [SignalR/SignalR#3770]
### Expected  behavior
My client has a network drop previously and error message on the timeout shown. After that, the connection is back and when user try to save, the same error message show again. Since the network is back online, it should allow saving to database without any error.

### Actual behavior
I tried to force a connection stop and connection start and reload the page, the previous connection timeout error message still showing and saving to database is not happening.

**Comment by moozzyk** [comment]
Where is the error SignalR is returning? Is it exception? If it is show the stack trace. Please provide more detailed information - the way it is filed now does not make it possible to pinpoint the issue or if the issue even is related to SignalR. Alternatively, ask the question on stackoverflow. 

Closing for now. Feel free to reopen with more details which would make this issue actionable.
