### ISSUE TITLE
In IIS, two WebApp call each other's Hub, called a second time is a problem.

### ISSUE THREAD

**Issue by linqingfeng** [SignalR/SignalR#3772]
In IIS, two WebApp call each other's Hub, called a second time is a problem.

E.g:
```
var testNum1 = myHubProxy.Invoke<string>("TestGetData", 1).Result;
var testNum2 = myHubProxy.Invoke<string>("TestGetData", 2).Result;
var testNum3 = myHubProxy.Invoke<string>("TestGetData", 3).Result;
```

The second line will always be in "WaitingForActivation" state,
If we allow them to perform, after testing, there are two ways

1. Each time you stop the connection, and then open the connection is very time-consuming

```
var testNum1 = myHubProxy.Invoke<string>("TestGetData", 1).Result;
hubConnection.Stop();
hubConnection.Start().Wait();
var testNum2 = myHubProxy.Invoke<string>("TestGetData", 2).Result;
hubConnection.Stop();
hubConnection.Start().Wait();
var testNum3 = myHubProxy.Invoke<string>("TestGetData", 3).Result;
```

2. Also open thread, barely acceptable performance, but still not convenient

```
Task.Run(() =>
{
	var testNum1 = myHubProxy.Invoke<string>("TestGetData", 1).Result;
	var testNum2 = myHubProxy.Invoke<string>("TestGetData", 2).Result;
	var testNum3 = myHubProxy.Invoke<string>("TestGetData", 3).Result;
}).Wait();
```

If the other client, calling the deployment of IIS Hub have not had this problem, which is the bug yet?
There are solutions to solve this problem?
thank you very much!

**Comment by moozzyk** [comment]
I think you are deadlocking yourself. await your tasks instead of calling `.Result`/`.Wait`
