### ISSUE TITLE
Socket not being disposed if server is not available

### ISSUE THREAD

**Issue by goransd** [SignalR/SignalR#3773]
I am having some difficulties with socket's Dispose not being properly called on the sockets used by SignalR inside my Windows Forms application. Here is how to reproduce the behavior. Start a new .net forms (or console) application. In that application add a button and paste the code below (Code A). Click the button and observe number of connections. On each pass new socket is opened and never disposed. Note, I am using www.google.com as the url but it does not really matter. Any web server will work. I have not tested what happens if web server does not exists (TCP level error) rather than the url not existing (HTTP level error). Note: _this project came about in answer to the questions: what happens to sr client if server goes down for a long period of time and sr client is set to retry the connection every 5 seconds_.

After looking through memory dumps it became apparent that Dispose is not being called on the Socket class. Note that socket class is being referenced by items that on the finalizer queue. If you uncomment GC.Collect() problem disappears since GC goes through and cleans it all up. I was however interested to see why Dispose is not called.

Next, I decided to step through the code and see what might be happening. Since I only had limited time you will have to excuse technical inaccuracy and limited understanding of the source code. Looking at the memory profiler, it saw that Socket is being referenced by the exception that was waiting to be throw when Wait method is called. I also noticed that at that point it seems that Dispose is not called. I would think that at this point socked should be disposed. I then followed the code into TransportHelper.cs where I think SignalR is trying to see if it can nego WebSockets by calling HttpClient.Get. In turn in HttpClient.Get method on lines 79+ SignalR sets the response to be disposed (83) or throws (87). Since this call fails (obviously google is not hosting sr), local HttpClient does not get disposed and the stream that returns the error is never disposed in the exception either. So I added a line `httpClient.Dispose(); `right before throw (87) and added line `responseMessage.Content.Dispose(); `to HttpClientException.cs as line 34.

I only added these two lines as a test to see if disposing of the socket would solve the problem. I am not recommending it as a solution. I am really not familiar with the source to recommend a solution. After adding those two lines socket is disposed properly and no socket creep happens. Obviously, I can work around this problem by calling GC.Collect but that is not a solution for our production code. If you think I am wrong and am misusing the stack somehow, please let me know. It is pretty late so I might be missing something obvious. Thank you for your hard work and support.

You can see from the two wiresharks that sockets are not being closed in the first instance (even though google sends FIN) while in the second instance socket is closed properly with FIN, ACK on both sides.

Code A
Imports Microsoft.AspNet.SignalR.Client
Imports System.Net
Imports System.Reflection

Public Class SignalRTest
	Dim Uri As String = "http://www.google.com/signalr"

	Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
		For counter As Integer = 0 To 500
			Connect()
			Threading.Thread.Sleep(100)
			MsgBox("done with connect")
			'GC.Collect()
		Next
	End Sub

	Private Sub Connect()
		Using Conn As New Connection(Uri)
			Dim t As Task = Conn.Start()
			Try
				t.Wait()
			Catch ex As Exception
				t.Dispose()
				ex = Nothing
			End Try
			Conn.Stop()
		End Using
	End Sub
End Class

Sockets A
 
![connectionlist](https://cloud.githubusercontent.com/assets/22034486/18299621/31366ed8-7477-11e6-8b15-23e9dc2d5e48.png)

Wireshark after change
 
![socketssignalrwithtwofinack](https://cloud.githubusercontent.com/assets/22034486/18299636/3de042da-7477-11e6-84e4-3f1436326ff2.png)

**Comment by moozzyk** [comment]
SignalR does not own the HttpClient it is using. All the transports allow the user to pass their own implementation of HttpClient. On top of that HttpClient instance is being reused (it is not recommended to create a new HttpClient each time you want to send a request; for more details see: http://stackoverflow.com/questions/22560971/what-is-the-overhead-of-creating-a-new-httpclient-per-call-in-a-webapi-client). So if SignalR disposed the http client it wouldn't be able to send a request. When you stop the connection I believe the OS will eventually take care of the lingering connections. I actually don't think I remember users complaining of running out of TCP/IP sockets when using SignalR especially given that a typical usage is to start a connection and use it for an extended period of time instead of opening and closing it ad hoc/frequently.

As a side note - even though `Task` implements `IDisposable` it is not necessary to dispose of tasks: https://blogs.msdn.microsoft.com/pfxteam/2012/03/25/do-i-need-to-dispose-of-tasks/

**Comment by goransd** [comment]
> SignalR does not own the HttpClient it is using. 

Who does then? I am not defining it in my code above so who owns it?

> When you stop the connection I believe the OS will eventually take care of the lingering connections. 

You don't have to believe it because I tested it in my sample above. **Eventually** when there is memory pressure and GC runs the socket will get disposed. Until then however it will linger. The problem is that even your recommendation to schedule connection start again inside Disconnect event will cause the problem I am describing if the server is **down.** Forget my example above, I can see that creation of the connection is causing confusion. How about this sample? The sample below tries to open a connection and when it discos it tries to open it again. SO and your documents suggest this very approach (sometimes with a 5s delay using a timer, omitted here for brevity). Would you expect the code below to run out of ports and leave sockets open? Is that what you are suggesting? If you run this code below on your machine, do you see sockets stacking up because I do? I appreciate your primer on HttpClient and Tasks, but am I doing something incorrectly in using SignalR? This code is just to show the problem I am running into. Again, thanks for your time.


```
Public Class SignalRTest
	Dim Uri As String = "http://www.google.com/signalr"
	Dim WithEvents mConn As New Connection(Uri)

	Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
		mConn.Start()
	End Sub

	Private Sub mConn_Closed() Handles mConn.Closed
		System.Threading.Thread.Sleep(100)
		mConn.Start()
	End Sub
End Class

```

**Comment by moozzyk** [comment]
If you don't provide an implementation of IHttpClient SignalR will create a default one for you but in general you can provide your own implementation and SignalR cannot dispose it. As I said above it is much more efficient to reuse the same HttpClient across multiple calls. 
Even if you open and close a SignalR connection multiple times I don't think you can run out of TCP sockets. If you are still concerned about that you can provide your own HttpClient implementation and dispose it after you stopped the connection.

**Comment by goransd** [comment]
I am not _concerned_ about it, that IS what is happening in my code that I pasted above, there is no need to think about it. If you run that code sample, you will run out of sockets. Did you run that code snippet? Is my code wrong in some way?
Are you saying that you ran my code and do not see the behavior I have described or are you saying that my code above is not using the SignalR stack properly?
Or are you saying that endless socket creation when server is not available is normal and by-design feature of SignalR client stack that I can overcome by implementing my own HttpClient and manage its lifetime myself?

**Comment by goransd** [comment]
I want to clarify that this only happens when server is not available on an http level. As in you are getting a 404, or front end proxy is returning 500 because back end SR server is down. If you just can't get a TCP syn, everything gets disposed properly. You can test that by putting in a bogus server name (no TCP listener) in the code sample.
