### ISSUE TITLE
Self Host AuthorizeAttribute

### ISSUE THREAD

**Issue by nogamegit** [SignalR/SignalR#3774]
I am using SignalR in self hosted server. And trying to override the AuthorizeHubConnection method. But its never calling.

```
public class CustomAuthAttribute : AuthorizeAttribute
    {
        public override bool AuthorizeHubConnection(Microsoft.AspNet.SignalR.Hubs.HubDescriptor hubDescriptor, IRequest request)
        {
            var token = request.QueryString.Get("token");
            Console.WriteLine(token);
            return true;
            //return base.AuthorizeHubConnection(hubDescriptor, request);
        }
}
```

```
[CustomAuth]
    public partial class SocketHub : Hub
    {
        public void Ping()
        {
            Console.WriteLine("Ping received : {0}", DateTime.Now);
}
}
```

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
