### ISSUE TITLE
Error after install SignalR on Xamarin Forms PCL

### ISSUE THREAD

**Issue by LuigiMaestrelli** [SignalR/SignalR#3775]
I just installed the last SignalR client package to a Xamarin Forms PCL application.
The iOS build looks like is working just fine.
But on Android I got this error: 

Could not load assembly 'System.Net.Http.Extensions, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Perhaps it doesn't exist in the Mono for Android profile?

Am I missing some configuration to make it work?

The target framework profile is Profile111, the default value when I created the project.

Thanks

**Comment by moozzyk** [comment]
@anurse - I think you tried it before we shipped 2.2.1 and it worked? Or what you tried was a different scenario?

**Comment by moozzyk** [comment]
Where does it try to load the System.Net.Http.Extensions from? Is the dll there? Or maybe loading is failing because one of the dependencies are missing? Since the iOS build works it looks to me it is not related to the package itself but external or environmental.

**Comment by LuigiMaestrelli** [comment]
I have no ideia about where it try to load the dll.
I just install de SignalR client throw a nuget package and the Android App doesn't build any more.
Before that everything was working. 

Just attached a simple repo with some packages that we use. 
Just install the last version of SignalR Client and the Android build will break.

[TestSignalR.zip](https://github.com/SignalR/SignalR/files/487913/TestSignalR.zip)

**Comment by anurse** [comment]
I don't think I tried Xamarin Forms, I tried other PCL scenarios though.

**Comment by LuigiMaestrelli** [comment]
So, a strange thing happened.
I was using VisualStudio 2015 to develop.
I tried to add the SignalR packages to my project using VisualStudio 2013, and now, the Android build works.

**Comment by moozzyk** [comment]
@LuigiMaestrelli - is it good to close then?

**Comment by Bibo1978** [comment]
Same problem here I don't have visual studio 2013 to test it

**Comment by cabbytech** [comment]
Visual Studio 2015 Android project with Signalr will not build. I CAN NOT USE VS2013

**Comment by moozzyk** [comment]
@Bibo1978 @cabbytech - thanks for confirming

**Comment by Asimkhan-developer** [comment]
Please see the [following solution ](http://stackoverflow.com/a/40436152/3565879)to connect as a signalR client using **VS2015**

**Comment by TMox** [comment]
I was having this problem as well. I used nuget to add signalR.Client to my PCL. However, the http.extensions.dll and newtonsoft.json.dll didn't get copied along with the PCL to my app, so I had to add signalR.Client to the app as well.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
