### ISSUE TITLE
Message delay after install of 2.2.1 in Portable Library UWP client

### ISSUE THREAD

**Issue by bjamesdev** [SignalR/SignalR#3778]
I was previously using the nightly 2.2.0 versions from the asp.net nightly repository without any issues.
I upgraded to 2.2.1 and am now noticing delays receiving messages. My client is a UWP client with the Signalr code within a portable library. When I overload the HubConnection.Start to specify longpolling the delay goes away. Debugging on the server the delay seems to only occur with serversentevents.

**Comment by moozzyk** [comment]
Do you see constant reconnects and the messages are only sent when the connection is closed during the reconnect? If so, I think you might be hitting this: https://github.com/SignalR/SignalR/issues/3011 - there is a bug in HttpClient on Windows Phone where streaming does not work: https://github.com/SignalR/SignalR/issues/3011#issuecomment-41966230. If this is the same issue I don't know how it could work in 2.2.0. If it is a different issues please provide client traces and a repro.
As a side note - in 2.2.1 we merged the websocket transport into the client so it should be used as the first transport when connecting to the server. Any reason not to use this transport (or why it is not being chosen?)

**Comment by bjamesdev** [comment]
> Do you see constant reconnects and the messages are only sent when the connection is closed during the reconnect? 

No both logs appear normal just a delay on the the receive messages on the client. 
 
> As a side note - in 2.2.1 we merged the websocket transport into the client so it should be used as the first transport when connecting to the server. Any reason not to use this transport (or why it is not being chosen?) 

The Signalr funcitonality is in a portable library which doesn't support websockets.

Please remember this issue is resolved if I specify LongPolling on the client, which I didn't have to do in the previous version.

**Comment by moozzyk** [comment]
Are you using http or https protocol? If you are using http try https. If it still does not work please provide traces and a repro.

**Comment by moozzyk** [comment]
No follow up. Closing.
