### ISSUE TITLE
SignalR client connection timeout does not call error event on ios 10

### ISSUE THREAD

**Issue by Framnk** [SignalR/SignalR#3780]
### Expected  behavior

When attempting a signalr client connection to a non-existent (or temporarily down) hub address, signalr should call the connection.error() event for client-side handling.
### Actual behavior

This functions properly on desktop and Android platforms, however on iOS 10 the error event handler is never called if the signalr hub connection times out.  You only see 'Failed to load resource.  The request timed out' in the browser console.
### Steps to reproduce

Attempt to connect to any non-existent hub URL on iOS 10 and set a breakpoint or log message in the connection.error() handler.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
