### ISSUE TITLE
Custom NoCache Attribute works for WebAPI but does not appear to work for SignalR - Need to disable HTTP Cache for SignalR

### ISSUE THREAD

**Issue by Codepoet77** [SignalR/SignalR#3781]
### Expected  behavior

We have large customers who are using our product which currently uses SignalR and they have security requirements which state that applications shouldn't cache HTTP responses in browsers (in our case Chrome). We need to know how to do this urgently in order to complete our project and we are hoping we receive a answer quickly if possible.

Need to know how to disable HTTP Cache Headers for SignalR requests. This is possible in Web API by applying a custom attribute like the following:

```
public class NoCacheAttribute : ActionFilterAttribute
   {
      /// <summary>
      /// This method is invoked when an action method is executed. The context can be modified to change the behaviour.
      /// </summary>
      /// <param name="context">The context of the action method being executed</param>
      public override void OnActionExecuted(HttpActionExecutedContext context)
      {
         context.Response.Headers.CacheControl = context.Response.Headers.CacheControl ?? new CacheControlHeaderValue();
         context.Response.Headers.CacheControl.NoCache = true;
         context.Response.Headers.CacheControl.NoStore = true;
         context.Response.Headers.CacheControl.MustRevalidate = true;

         // Expire to prevent caching.
         if (context.Response.Content != null)
         {
            context.Response.Content.Headers.Expires = DateTimeOffset.Now.AddHours(-12);
         }

         context.Response.Headers.Add("pragma", "no-cache");
      }
   }
```

I need to know how to accomplish the same for SignalR.

We started to configure these HTTP headers programtically because Web API  allows this but another possibility if SignalR does not allows is that we would remove the NoCache custom attribute from our Web API controllers and configure IIS to return these headers which should also cover SignalR.
### Actual behavior

When I apply this custom attribute to SignalR it does not appear to work as expected. If I check the cache in the chrome browser I still see these routes and I still see data from push notifications (via the chrome cache viewer which can be seen when browsing to chrome://cache in Chrome).
### Steps to reproduce

See the description

**Comment by davidfowl** [comment]
Action filters are MVC specific and do not work in SignalR. You need a piece of middlware to make this work.

**Comment by moozzyk** [comment]
I was thinking that you could probably hack AuthorizationAttribute...

**Comment by Codepoet77** [comment]
Thanks for suggestions. Can you anyone provide an example of how this would work for both SignalR and Web API? I am assuming this would be Owin Midlleware/

Thanks in advance.

**Comment by dominusbelial** [comment]
are you building and deploying your application in release mode?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
