### ISSUE TITLE
SignalR long polling timeout 

### ISSUE THREAD

**Issue by awcd** [SignalR/SignalR#3782]
Hi.

When doing a SignalR ping using IP address, we get a response.
However, when doing the same ping using the domain name (corresponding to the IP address), a timeout occurs.

So, this gets a response:
http://xx.xx.xx.xxx/SomeApp/SignalR/ping?_=4545454455

This times out:
http://somedomain/SomeApp/SignalR/ping?_=4545454455

We can reach web services WSDL no problem using the domain name.  

This gets a response:
http://somedomain/SomeApp/Services/SomeService?WSDL

So it appears to be SignalR related.  Does anyone know what could be the issue?

Thanks.

**Comment by moozzyk** [comment]
Are you saying that you are able to start a connection just fine and only `ping` does not work?

**Comment by awcd** [comment]
No, ping is just one example that doesn't work.  Other calls using signalr using IP work.  But other calls using fully qualified domain name don't work either.

**Comment by moozzyk** [comment]
Are SignalR requests reaching the webserver? If they are, what is the status code when the requests finishes?

**Comment by awcd** [comment]
Thanks for your help.  I don't believe they are reaching the server.  The code when it is finished was simply 'timeout'.

**Comment by moozzyk** [comment]
Do you see anything when you run `http://somedomain/SomeApp/SignalR/negotiate` directly from your browser?
Can you show traces?

**Comment by awcd** [comment]
When I do http://somedomain/SomeApp/SignalR/negotiate in browser, I get a directory not found error.

Also, I am not sure how to show traces.

**Comment by moozzyk** [comment]
So, the requests are actually reaching some server. It feels that when the requests are sent with the ip they go to a different server than ones that are sent with the domain name. You need to figure out why this: `http://somedomain/SomeApp/SignalR/negotiate` returns "directory not found" while this: `http://{ip}/SomeApp/SignalR/negotiate` works. I don't think this is really SignalR related - rather it seems as kind of a configuration issue.

**Comment by awcd** [comment]
Sorry, I failed to run the negotiate with the IP address.

when I do http://{IP}/SomeAppSignalR/negotiate, that gets a directory not found error as well.

**Comment by awcd** [comment]
Should have said in previous message: http://{IP}/SomeApp/SignalR/negotiate

**Comment by moozzyk** [comment]
if `http://{IP}/SomeApp/SignalR/negotiate`  then you are not able to start the connection neither using the ip nor using the domain name. It seems that you have not configured SignalR on the server correctly or at all.

**Comment by awcd** [comment]
Ok, if you say that should be able to get a connection using that url (and clearly we can't), something doesn't make sense.  Let me talk to the another developer and get back to you.

**Comment by awcd** [comment]
My mistake.  I was going to the wrong url.  We just tested and the negotiate works with both IP and domain.
