### ISSUE TITLE
No Websocket connection from Windows 7 SignalR client to Windows Server 2012 SignalR

### ISSUE THREAD

**Issue by AnthonyBr** [SignalR/SignalR#3783]
SignalR Server version 2.2.1
IIS 8.5 on IIS Windows Server 2012, WebSockets Activated.

### Expected  behavior
Windows 7 clients are connected to the Signal R server via Websocket transport protocol.

### Actual behavior
The connection is established with "server-sent events" transport protocol.
When connecting from Windows 10 / Chrome 52, the Websocket connection is established.
When connecting from Windows Server 2012 / IE 11, the Websocket connection is established.
When connecting from Windows 7 / Chrome 48, Firefox 48.0, IE11, the Server-sent events connection is established.

### Steps to reproduce
Install SignalR service on a IIS 8.5 Windows Server 2012.
Use Chrome 48 / Firefox 48.0, on Windows 7 Client
Execute $.connection.hub.start() from javascript

**Comment by moozzyk** [comment]
Windows 7 does not support websockets.

**Comment by AnthonyBr** [comment]
ju
