### ISSUE TITLE
Multiple Hubs, only one gets OnConnected/OnDisconnected events

### ISSUE THREAD

**Issue by gkinsman** [SignalR/SignalR#3786]
Microsoft.AspNet.SignalR.Client: 2.2.1.0
Micosoft.AspNet.SignalR.Core: 2.2.1.0

### Expected  behavior
I implement multiple hubs on the server, with my client creating hub proxies from a single connection. I'd expect each hub to get an OnConnected/OnDisconnected event for each client. I understand that since there's one connection it makes sense that there's only one OnConnected event, but there doesn't appear to be a way to specify which hub is the 'primary' hub that should handle these connection events. It seems to be arbitrary.

### Actual behavior
One of the hubs handles the OnConnected/OnDisconnected event, the others don't get anything.

### Steps to reproduce
Standard config, setup two hubs that create proxies from a single connection. Connect a client and register both hubs, and the connect. Only one of the hubs will hit OnConnected.

Is this behavior by design? It's not well documented under the 'Multiple Hubs' section on the ASP.NET website, and I can't find anyone else running into problems with this. 

My current solution is to just use one hub...it's messy, but it means I don't have to put an abstraction around the hub OnConnected/OnDisconnected so that all my hubs work the same. 

Thanks,
George

**Comment by gkinsman** [comment]
This turned out to be my fault, I had an error in my autofac config that was preventing the hub from being activated. Ugh!

**Comment by davidfowl** [comment]
Are you connected to all hubs? Events will only get raised for hubs that you have subscribed to. What does your client code look like?
