### ISSUE TITLE
Parsing response error with serverSentEvents

### ISSUE THREAD

**Issue by attiqeurrehman** [SignalR/SignalR#3789]
Hi,

I am getting the parsing response error with serverSentEvent. Here are my logs:

> SignalR: Client subscribed to hub 'chalkhub'.
> SignalR: Negotiating with '/signalr/negotiate?clientProtocol=1.5&connectionData=%5B%7B%22name%22%3A%22chalkhub%22%7D%5D'.
> SignalR: serverSentEvents transport starting.
> SignalR: Attempting to connect to SSE endpoint 'https://localhost:44300/signalr/connect?transport=serverSentEvents&clientPr…%2B1Ehw%3D%3D&connectionData=%5B%7B%22name%22%3A%22chalkhub%22%7D%5D&tid=2'.
> SignalR: EventSource connected.
> SignalR: serverSentEvents transport connected. Initiating start request.
> SignalR: The start request succeeded. Transitioning to the connected state.
> SignalR: Now monitoring keep alive with a warning timeout of 13333.333333333332, keep alive timeout of 20000 and disconnecting timeout of 30000
> SignalR: Invoking chalkhub.AddComment
> SignalR: Invoked chalkhub.AddComment
> SignalR error: Error: Failed at parsing response: {"C":"d-7520081E-B,2|F,0|D,0|G,1","M":[{
> SignalR: Stopping connection.
> SignalR: EventSource calling close().
> SignalR: Fired ajax abort async = true.
> SignalR: Stopping the monitoring of the keep alive.

Following is the code:

```
$.connection.hub.logging = true;
$.connection.hub.start({
    transport: 'serverSentEvents'
}).done(function() {
    console.log("ding");
});
$.connection.hub.error(function(error) {
    console.log('SignalR error: ' + error);
});
```

**Note**: _it works fine if serverSentEvents is not selected. But had the issue with it as well because on one machine it's selecting serverSentEvents be-default and thus we investigated this issue with it specifically._

After some debugging I found that the exact error that is coming up in the following line in **jquery.signalR-2.2.1.js** :

`connection.eventSource.addEventListener("message", function (e)`

Exact error coming is:

> "Unexpected end of JSON input"

and e.data value and connection.messageId is :

> "{"C":"d-7520081E-H,1|I,0|J,0|K,1","M":[{"

Thanks,
Attiqe

**Comment by umermughal** [comment]
I have same issue on chrome Windows 7 @attiqeurrehman  what OS you are using?

**Comment by attiqeurrehman** [comment]
@umermughal I am using Windows 10 with Chrome.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Comment by silkyjainMS** [comment]
Facing the same issue in my application
