### ISSUE TITLE
How to handle client side when hub server is disconnected

### ISSUE THREAD

**Issue by Robert969696** [SignalR/SignalR#3792]
How to handle exception on my code in this line, when the server is down or similar.
In below line when server is not connected i receive error - what should be done in that case?
`Task.Run(Sub() hubConnection.Start().Wait())`

When server is disconnected i get an error from that line - how to catch that error and try to reconnect again after X seconds? By the way am i doing it correctly?

```
Sub Main()
        Dim hubConnection = New HubConnection("http://localhost:21/")
        Dim myHubProxy As IHubProxy = hubConnection.CreateHubProxy("myHub")

        myHubProxy.[On](Of String, String)("addMessage", Sub(name, message) Console.Write("Recieved addMessage: " + name + ": " + message + vbLf))

        Try
            Task.Run(Sub() hubConnection.Start().Wait())
            Console.WriteLine("-----------------")
            Console.WriteLine("Connection initiated")
            Console.WriteLine("-----------------")         
        Catch ex As Exception
            Console.WriteLine(ex.ToString())
        End Try

        While True
            Dim key As String = Console.ReadLine()
            If key.ToUpper() = "R" Then
                Dim hello As New HelloModel() With {
                    .Age = 10,
                    .Molly = "clientMessage"
                }

                Try
                    myHubProxy.Invoke(Of HelloModel)("SendHelloObject", hello).ContinueWith(Function(task)
                                                                                                If task.IsFaulted Then
                                                                                                    Console.WriteLine("There was an error opening the connection:{0}", task.Exception.GetBaseException())
                                                                                                Else
                                                                                                    Console.WriteLine(("dd"))
                                                                                                End If
                                                                                            End Function).Wait()
                    Console.WriteLine("client sendHelloObject sent to server" & vbLf)
                Catch ex As Exception
                    Console.WriteLine(ex.ToString())
                End Try
            End If
            If key.ToUpper() = "C" Then
            End If
        End While
    End Sub
```

**Comment by moozzyk** [comment]
My advise would be to `await` async calls. Please use stackoverflow for asking questions.

**Comment by Robert969696** [comment]
Would you be so kind and show how based on my code?

**Comment by moozzyk** [comment]
Because it seems to be a command line app I think you can get away with .Wait. Task.Run() is not needed here and is causing issues - e.g. because it is not awaited you might be trying to send messages before you started the connection. I also don't think you will see exceptions thrown from `Start()`. Now you can use a loop to retry starting the connection if it fails.

**Comment by Robert969696** [comment]
so what you are saying is instead of this: 

`Task.Run(Sub() hubConnection.Start().Wait()) `

just use this:?
` Sub() hubConnection.Start()`

and why i should not use task?

**Comment by moozzyk** [comment]
No. Just `hubConnection.Start().Wait()`

**Comment by Robert969696** [comment]
if i use like this:   
Try
```
_hubConnection.Start()
 Catch ex As Exception
            Console.WriteLine(ex.ToString())
End Try
```
 i do not get any error

 but if i use like this:   
```
Try
_hubConnection.Start().Wait()
 Catch ex As Exception
            Console.WriteLine(ex.ToString())
End Try
```
_
i am getting this error just one time:

> System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred whi
> le sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.Soc
> ketException: No connection could be made because the target machine actively refused it 127.0.0.1:4848
>    at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
>    at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddr

**Comment by moozzyk** [comment]
without .Wait()/await you run on a different thread and you are not observing exceptions. You can subscribe to the [UnobservedTaskException](https://msdn.microsoft.com/en-us/library/system.threading.tasks.taskscheduler.unobservedtaskexception(v=vs.110).aspx) event to see them.

**Comment by Robert969696** [comment]
Thx moozzyk for you answer, can you help me with this as if i put it in this form:

`Await _hubConnection.Start().Wait()`

then it's says : 

> "Await can only be used in method marked as async"

What should i change to makes this works.

**Comment by moozzyk** [comment]
Because you are running a console application it is fine to just `.Wait()`. In non-console app you would make your method async return Task and await the call. I would encourage you to read a bit more about async in .NET. 

Are you saying that catch is not catching the exception? You may see it when debugging in VS if VS is set to break on first chance exceptions but when you run the application without VS the exception should be caught and in your handler.

**Comment by Robert969696** [comment]
No.

If i use this:

`_hubConnection.Start().Wait()`

i get an error from catch

if i use this:

`_hubConnection.Start()`

i do not get any error from catch

and if i use as in previous post i get also an error from catch

**Comment by moozzyk** [comment]
As I said: https://github.com/SignalR/SignalR/issues/3792#issuecomment-254935393

**Comment by Robert969696** [comment]
so i am mixed now should i just use this: _hubConnection.Start().Wait() and then use this: UnobservedTaskException 

or to use with await - but then i ran into error:


_as it is in Main function, should i do it like this?:
create separated method:

Async Function  InitiateConnection As Task(Of HubConnection)
         Await _hubConnection.Start()
    End Function

then in Main?:

try
InitiateConnection.Wait()
  Catch ex As Exception
            Console.WriteLine(ex.ToString())
        End Try

but then i still get an error from catch (note that server is not running) so does it mean i implemented it correctly and i have to see that error?

    System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:4848_

**Comment by Robert969696** [comment]
would appreciate you answer if i learn it right way :)

**Comment by moozzyk** [comment]
The problem with a command line application is that you cannot make it async all the way because the Main method can't be async. It is also not a good idea to mix await and .Wait because they are different beasts (http://stackoverflow.com/questions/9519414/whats-the-difference-between-task-start-wait-and-async-await). What I typically do in a command line application I block at the top level (in Main) with .Wait() and use async/await everywhere else. In non-command-line applications .Wait() should be avoided as much as possible - methods should be just made async and tasks should be awaited.

````C#
class Program
{
    static void Main(string[] args)
    {
        new Program().Run().Wait();
    }

    private async Task Run()
    {
        var connection = new HubConnection("http://localhost:5001/signalr");
        var proxy = connection.CreateHubProxy("ChatHub");
        await connection.Start();
        ...
    }
}
````

**Comment by Robert969696** [comment]
Hi moozzyk, i thought you never answer on this - thanks. See my whole starting code, i took what you wrote and that's how it looks here now. I got two problems still:

1st case: When server is down and i run this code i get error from try/catch of Main function, see console output: https://1drv.ms/i/s!AkQvbwpYPYoIhzf_gSwITCTW9wYF

2nd case: If i run server after client was ran then client will nto connect to it, see console output:
https://1drv.ms/i/s!AkQvbwpYPYoIhzY0VK5j6vlHVf57

Hope it better explains my current situation

And here the whole code:

```
Module Module1
    Dim _hubConnection As HubConnection
    Dim _myHubProxy As IHubProxy

    Async Function InitiateConnection() As Task
        _hubConnection = New HubConnection("http://localhost:4848")

          AddHandler _hubConnection.Closed,
           Sub()
               Console.BackgroundColor = ConsoleColor.White
               Console.ForegroundColor = ConsoleColor.Red
               Console.WriteLine("CONNECTION STATE: CLOSED")
               Console.ResetColor()
           End Sub

        AddHandler _hubConnection.[Error], Sub(e)
                                               Console.BackgroundColor = ConsoleColor.Red
                                               Console.ForegroundColor = ConsoleColor.White
                                               Console.WriteLine("Hub connection error: " & e.ToString())
                                               Console.ResetColor()
                                           End Sub
        AddHandler _hubConnection.StateChanged, Sub(state)
                                                    Console.BackgroundColor = ConsoleColor.DarkYellow
                                                    Console.ForegroundColor = ConsoleColor.Black
                                                    Console.WriteLine("Connection State Changed From {0} To {1}", state.OldState, state.NewState)
                                                    Console.ResetColor()
                                                    If state.NewState = ConnectionState.Disconnected Then
                                                        Console.BackgroundColor = ConsoleColor.Blue
                                                        Console.ForegroundColor = ConsoleColor.White
                                                        Console.WriteLine("Reconnecting in 500 ms")
                                                        Console.ResetColor()
                                                        Thread.Sleep(500)
                                                        _hubConnection.Start()    ' Will never reconnect. Workaround: Recreate connection      Task.Run(Sub() hubConnection.Start().Wait())                                                   _hubConnection.Start();     ' Will never reconnect. Workaround: Recreate connection CreateConnection().Start();

                                                    ElseIf state.NewState = ConnectionState.Connected Then
                                                        Console.BackgroundColor = ConsoleColor.Green
                                                        Console.ForegroundColor = ConsoleColor.Black
                                                        Console.WriteLine("CONNECTION STATE: CONNECTED")
                                                        Console.ResetColor()
                                                    End If
                                                End Sub

        _myHubProxy = _hubConnection.CreateHubProxy("myHub")
        Await _hubConnection.Start()

        _myHubProxy.[On](Of String, String)("addMessage", Sub(name, message) Console.Write("Recieved addMessage: " + name + ": " + message + vbLf))
        _myHubProxy.[On](Of String)("heartbeat", Sub() Console.Write("Recieved heartbeat " & vbLf))
        _myHubProxy.[On](Of HelloModel)("sendHelloObject", Sub(hello) Console.Write("Recieved sendHelloObject {0}, {1} " & vbLf, hello.Molly, hello.Age))

     
    End Function
    Sub Main()
        Try
            InitiateConnection().Wait()

        Catch ex As Exception
            Console.WriteLine( ex.ToString())
        End Try
End Sub
End Module

```

**Comment by Robert969696** [comment]
i also created the same post on stackoverflow if you would like to answer: http://stackoverflow.com/questions/40164820/client-connection-reconnection-to-hub-server
