### ISSUE TITLE
Possible Memory Leak when attempting to Continuously Reconnect

### ISSUE THREAD

**Issue by sjones512** [SignalR/SignalR#3793]
Hello.

We are using the technique outlined in the [documentation](https://www.asp.net/signalr/overview/guide-to-the-api/handling-connection-lifetime-events#continuousreconnect) to attempt to continuously reconnect to the SignalR server. 

In situations where the client is disconnected, and retrying, for an extended period of time, the client side JS memory usage climbs steadily.

Attempting to investigate the issue, it looks like it has to do with onStart event handlers being leaked.

I'm not sure where the issue is, but was wondering if you all had any insight.

We are seeing the issue with SignalR 2.2.0 and jquery 1.10.2.

Thanks for looking.

![image](https://cloud.githubusercontent.com/assets/1839534/19572457/2c640822-96b7-11e6-8d50-05cfd67715ca.png)

![image](https://cloud.githubusercontent.com/assets/1839534/19572638/f7111632-96b7-11e6-9e50-be3c64af6fb7.png)

**Comment by bigswede74** [comment]
I have submitted a pull request above. I tested this fix over a 72hr time period with the JS client continuously reconnecting every 5 seconds and the memory usage was stable.

**Comment by moozzyk** [comment]
Putting tentatively to vNext milestone.

**Comment by bigswede74** [comment]
Sorry that was the pull request to my local repo, I have submitted the real one here #3804

**Comment by sbabeal** [comment]
I was seeing the same type of behavior however i attributed it to the console.log filling up with error messages.  How can handle the errors so they don't appear in the console.log?  I have tried everything window.error => () => {}, etc.  Nothing works.

zone.js:1274 GET http://163.185.149.209:9300/signalr/signalr/negotiate?clientProtocol=1.5&connectionData=%5B%7B%22name%22%3A%22timedatahub%22%7D%5D&_=1478838862781 net::ERR_CONNECTION_REFUSEDscheduleTask @ zone.js:1274ZoneDelegate.scheduleTask @ zone.js:216Zone.scheduleMacroTask @ zone.js:153(anonymous function) @ zone.js:1304send @ VM1769:3send @ jquery.js:9175ajax @ jquery.js:8656ajax @ jquery.signalR.js:1163start @ jquery.signalR.js:667(anonymous function) @ signalr-connection.js:98Observable.subscribe @ Observable.ts:95RetryWhenSubscriber.notifyNext @ retryWhen.ts:124InnerSubscriber._next @ InnerSubscriber.ts:17Subscriber.next @ Subscriber.ts:95MergeMapSubscriber.notifyNext @ mergeMap.ts:144InnerSubscriber._next @ InnerSubscriber.ts:17Subscriber.next @ Subscriber.ts:95TimerObservable.dispatch @ TimerObservable.ts:70AsyncAction._execute @ AsyncAction.ts:121AsyncAction.execute @ AsyncAction.ts:96AsyncScheduler.flush @ AsyncScheduler.ts:33ZoneDelegate.invokeTask @ zone.js:236onInvokeTask @ core.umd.js:6197ZoneDelegate.invokeTask @ zone.js:235Zone.runTask @ zone.js:136ZoneTask.invoke @ zone.js:304
index.js:25 SignalRConnection: Error: Error during negotiation request. - http://163.185.149.209:9300/signalr

**Comment by stefanzvonar** [comment]
We are getting a memory leak too, and our client application attempts to always reconnect.  Here is a screenshot of our memory dump.  The SignalR objects keep piling up to the top of the list.

![image](https://cloud.githubusercontent.com/assets/3641969/20289801/8b651fbc-ab27-11e6-85e1-e3ce9e1f0fc9.png)

**Comment by bigswede74** [comment]
Hello Stefan,
If you look at the pull request #3804, by unbinding the OnStart event in the SignalR js client this fixes the memory leak when disconnected.


Brad Lindberg | Senior Software Engineer PTG R&D | Networked Game Services

Scientific Games | 702-532-6613 | 702-403-2052 (M)


[Description: cid:image004.png@01D0947B.C2037880]
May be privileged. May be confidential. Please delete if not the addressee.

**Comment by moozzyk** [comment]
@bigswede74 - shouldn't we also unbind the other events then? I assume that one of the columns I marked is object count so it seems that other event handlers are leaking too but at a much smaller rate.

![image](https://cloud.githubusercontent.com/assets/1438884/22357891/06b6c7fa-e3f0-11e6-83c4-f4e4f40a364b.png)

**Comment by moozzyk** [comment]
I looked a little bit more into this and concluded that other events should not actually be unbound because they are set by the user so if they were unbound things would actually stopped working (or the user would have to re-bind them before starting the connection again). `onStart` on the other hand is the only event that is being bound automatically. It is also not exposed so unbinding the event will not break users.

**Comment by moozzyk** [comment]
Fixed in 5c609d17cd556d9c1b8c3eda0b4e37f00a4fc535
