### ISSUE TITLE
Long pool request fail from chrome browser when modify default value of keepalive, disconnecttimeout and connectiontimeout.

### ISSUE THREAD

**Issue by vpatel-TBA** [SignalR/SignalR#3798]
We have modified the default timespan for keepalive, disconnecttimeout and connectiontimeout. And we are facing error in web that long pool is not completed error=timeout. It will work ok if we use default timespan for all 3(keepalive, disconnecttimeout and connectiontimeout). 

### Expected  behavior
If we use default timeout it works ok. But why it is failing if we modify the settings like below.
"ConnectionTimeout" ="300"
"DisconnectTimeout" ="100" 
"KeepAliveTimeout" ="33"

### Actual behavior
I am not sure why it is failing and not able to complete long pull request and giving error of timeout even we are using large timeout which is default 110seconds.
If we use default timeout it works ok.
### Steps to reproduce
Just set the 
"ConnectionTimeout" ="300"
"DisconnectTimeout" ="100" 
"KeepAliveTimeout" ="33"
and use long polling and just keep the screen idel for 10 minutes.

While working
![working](https://cloud.githubusercontent.com/assets/12032460/19684796/ea0b74c8-9ad6-11e6-9493-67a0592d3b17.PNG)

While not working
![notworking](https://cloud.githubusercontent.com/assets/12032460/19684802/eff78ae8-9ad6-11e6-8dd1-f45c69a9710a.PNG)

**Comment by moozzyk** [comment]
The default connection timeout in IIS is 120 secs meaning IIS will terminate requests that run longer than 120 secs. This is why the default connection timeout in SignalR is set to 110 secs.
