### ISSUE TITLE
SignalR

### ISSUE THREAD

**Issue by dsprabhu4** [SignalR/SignalR#3800]
# Issues related to the Asp.NET Core version of SignalR should be filed in the corresponding SignalR repo: https://github.com/aspnet/?utf8=%E2%9C%93&query=Signalr

We have a desktop signalr host and client. There are few instances in which we do not want to allow client to connect to host. Say host is busy doing some critical setup activity, we do not want client to connect. Is there any api on host to provide a busy status to client during connection?

We tried throwing an exception from OnConnected of host, but this exception is not propagated to client. Client receives a generic connection failure message. We would like to show exception message on client thrown by host code. 

_hubConnection = new HubConnection(url);
 _hubConnection.Start()
                    .ContinueWith(task =>
                    {
                        if ((task.IsCanceled || task.IsFaulted) && task.Exception != null)
                        {
                           Exception e = _hubConnection.LastError;
                            msg = "Connect Failed:\r\r" + task.Exception.Flatten().GetBaseException().Message;
                            Console.WriteLine(msg);
                            Dispose();
                        }
                    }).Wait();

I am sorry if this is a wrong mailing list to post this question.

**Comment by moozzyk** [comment]
One way would be to throw from Authorize to prevent the client from connecting.
