### ISSUE TITLE
ITraceManager Registration overridden when host.TraceOutput provided

### ISSUE THREAD

**Issue by BrettJaner** [SignalR/SignalR#3801]
The TraceManager is unable to be configured in code, because the registration is overridden if the OWIN app builder property of host.TraceOutput is provided.  I'm still not too familiar with OWIN so I'm not sure where this property comes from, but it must be removed if I want to configure the TraceManager in code.  I felt this wasn't very intuitive and required debugging the SignalR source to figure out the problem.  Here is what my "working" Configuration method looks like:

```
    public void Configuration(IAppBuilder app)
    {
        app.Properties.Remove("host.TraceOutput");

        GlobalHost.TraceManager.Switch.Level = SourceLevels.Error;

        foreach (string traceSource in new string[] {
            "SignalR.SqlMessageBus",
            "SignalR.ServiceBusMessageBus",
            "SignalR.RedisMessageBus",
            "SignalR.ScaleoutMessageBus",
            "SignalR.Transports.WebSocketTransport",
            "SignalR.Transports.ServerSentEventsTransport",
            "SignalR.Transports.ForeverFrameTransport",
            "SignalR.Transports.LongPollingTransport",
            "SignalR.Transports.TransportHeartBeat",
            "SignalR.ReflectedHubDescriptorProvider" })
        {
            GlobalHost.TraceManager[traceSource].Listeners.Add(new LoggingTraceListener(container.GetInstance<ILogger>()));
        }

        app.MapSignalR();
    }
```

If the host.TraceOutput property isn't removed, the TraceManager registration gets overridden in UseSignalRMiddleware extension method here:

```
            TextWriter traceOutput = env.GetTraceOutput();
            if (traceOutput != null)
            {
                var hostTraceListener = new TextWriterTraceListener(traceOutput);
                var traceManager = new TraceManager(hostTraceListener);
                resolver.Register(typeof(ITraceManager), () => traceManager);
            }
```

Seems like instead of overriding the registration, we could just add the hostTraceListener to all existing TraceSources.  Would be happy to provide the pull request if it is determined that a change should be made.  Thanks!

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
