### ISSUE TITLE
Memory leak on server (IIS)

### ISSUE THREAD

**Issue by stefanzvonar** [SignalR/SignalR#3809]
Hi all,

We have a web site where the memory consumption in IIS begins to be a large problem, requiring us to restart the application for it to start responding again.

Below is an example of the memory dump when the memory is about 1,100MB and at 75% CPU.
![image](https://cloud.githubusercontent.com/assets/3641969/20289867/1cef583a-ab28-11e6-99b4-cc9a595d2ae8.png)

Notice how the SignalR classes are consuming the top spots.

Below is an example of the memory dump taken approx 10 mins after restarting IIS, the memory is about 700MB and at about 2% CPU.

![image](https://cloud.githubusercontent.com/assets/3641969/20289904/596d1b30-ab28-11e6-8766-1465dcf445ba.png)

You can see that the SignalR classes overtake and land in poll position.

Note:  We are using SignalR 2.2.0.   We are also using Kendo UI on the client.   The application has two hubs, and each hub maintains about 5 groups of users.   There is really only about 2-10 max users concurrently on the application.  The client application does always try to reconnect to the hub after 5 seconds.  We also have web jobs that connect to the signalr hub to broadcast messages to users.

Any help would be appreciated, thanks :)

**Comment by stefanzvonar** [comment]
Just following up, after leaving it run for another 2 hours, it reached 2,500MB and still increasing.  With the SignalR.Messaging.Topic class being the main culpirt.

Also CPU is continually running also which is weird for an IIS process (~40-60%) without it going back down to idle.
![image](https://cloud.githubusercontent.com/assets/3641969/20292971/baa6c788-ab3d-11e6-979f-f5931482b695.png)

**Comment by stefanzvonar** [comment]
And it crashed again with close to 95% CPU, following dump.
We'll try and change our DefaultMessageBufferSize down to 32 and see if that helps limit the memory footprint.  Our messages are not critical and can be missed by the client, and picked up by a following one.

![image](https://cloud.githubusercontent.com/assets/3641969/20295372/4b765f64-ab50-11e6-973f-de82534e1002.png)

**Comment by cdmdotnet** [comment]
I can second this. We've got continuous reliability issues with SignalR using the Servicebus backpane. Randomly messages won't be delivered. Sporadic groups of messages just don't arrive, so it's not like a window of an outage... lots of other messages get delivered (we have something in the order of a ten thousand messages spreed constantly and evenly out over an hour) and memory usage goes nuts (it does level out around 90%... although that triggers Azure memory consumption alerts). I can't say for sure the two are related, but the reliability issues go away after an app recycle and memory comes back down.

![untitled](https://cloud.githubusercontent.com/assets/135006/20325586/36dcefa6-abea-11e6-8b9b-d75311519a26.png)

**Comment by moozzyk** [comment]
@cdmdotnet - you will be able to configure this when https://github.com/SignalR/SignalR/pull/3805 is merged.

**Comment by cdmdotnet** [comment]
Which is nice... although I note that's not in a milestone yet. Is that a categorisation issue in your bug tracker or are there other factors at play as to why there's no indication of when a release of #3805 will be?

**Comment by moozzyk** [comment]
It's actually tracked as https://github.com/SignalR/SignalR/issues/3031. It will be in the next servicing release (2.2.2). No dates at this point though.

**Comment by stefanzvonar** [comment]
It might be early days ... but we changed the configuration to have a ring buffer of 32 per signal (instead of 1000).  Also, we stopped a web job that was pulse hitting the signalr hub (we still have other signalr traffic).  This has improved the memory and CPU usage.

![image](https://cloud.githubusercontent.com/assets/3641969/20335144/d245bef2-ac0b-11e6-83a0-770ed641071b.png)


Here's a link to my stackoverflow question regarding the web job - seperate (yet related) issue:
http://stackoverflow.com/questions/40623832/azure-web-jobs-timer-trigger-surge-of-signalr-messages-in-batches

**Comment by moozzyk** [comment]
Depending on how many messages you send 32 might be to small. Look for missed messages (especially during reconnects) - if you see many/too many you may want to increase the value.

**Comment by stefanzvonar** [comment]
I finally found the root cause for my scenario.   If you have an Azure Web Job that sends a message to a hub, you must ensure you explicitly stop the hub connection afterwards.  This solved both the memory 'leak' and CPU issue.

Details in my stackoverflow question and answer:
http://stackoverflow.com/questions/40623832/azure-web-jobs-and-signalr-memory-leak/40775126#40775126

**Comment by stefanzvonar** [comment]
Closing issue - although I would be interested to determine why it still keep the connection alive and why the server never disconnects the web job client

**Comment by moozzyk** [comment]
2.2.2-preview1 is now on NuGet

**Comment by sufianmehmood** [comment]
which memory profiler are you using?
