### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by Alex-Vaduva** [SignalR/SignalR#3810]
Hi,

Can you please provide more info about the following license SignalR/xamarin/SignalRPackage/component/License.md?
Because is not an open source license like Apache-2.0.
I'm more curious because the name of the package on which applies is named SignalR, but this component is license under Apache. Or are there 2 version of SignalR, one license under Apache and one under Microsoft License Term?

Thanks,
Alex

**Comment by moozzyk** [comment]
I believe I missed this file when moving the repo from MS Open Tech to .NET Foundation (https://github.com/SignalR/SignalR/commit/799d9bc32524066344cb3656e5f28f2fd03ba9b3). @Eilon - to make sure - everything in this repo should be Apache-2.0 and I need to update this license accordingly.

**Comment by moozzyk** [comment]
This sample was not being kept up-to-date and we decide to [remove it](https://github.com/SignalR/SignalR/commit/6f5c68bb602f72922df80dd3dbf7690d8728567d) from the repo. We are thinking about creating a new xamarin sample for the new version of [SignalR](https://github.com/aspnet/SignalR) we are working on.
