### ISSUE TITLE
Cursor payload is too big compared to the useful payload

### ISSUE THREAD

**Issue by maxcherednik** [SignalR/SignalR#3811]
### Actual behavior
![image](https://cloud.githubusercontent.com/assets/4208513/20434499/add2d216-adb0-11e6-9908-52b2fba9632c.png)

![image](https://cloud.githubusercontent.com/assets/4208513/20434826/53d0ce42-adb2-11e6-9df1-66fd8bfc4da2.png)

### Steps to reproduce
The logic of the application assumes that there are number of data sources on the server which are handled by groups.
If client wants to subscribe to the specific data source, it calls:
myhub.Subscribe(dataSourceId);

On the server side, we just add the client to the specific group:
await Groups.Add(Context.ConnectionId, dataSourceId.ToString());

Then all the messages are sent with huge cursor payload and the size of it grows with every subscription.
Am I doing something wrong?

**Comment by maxcherednik** [comment]
[Asked on the stackoverflow](http://stackoverflow.com/questions/40713987/cursor-payload-is-too-big-compared-to-the-useful-payload)

**Comment by moozzyk** [comment]
Unfortunately this is how cursors work. Cursor contains references to all topics the connection is subscribed to. Besides the cursor getting bigger there is one more limitation to using many groups. The more groups the client is a member of the bigger the groups token. The groups token is sent back to the server when the client is reconnecting and if it gets too big it may exceed the url size limit causing reconnect failures.

**Comment by SaroTasciyan** [comment]
@moozzyk I'm trying to figure out a way to reduce the size of cursor payload. Apparently it's not possible to reduce it while registering for many groups. Is there any other suggestion? One approach may be handling grouping ourselves on the server side and broadcast separately to each user. Is this a common/suggested scenario?

**Comment by davidfowl** [comment]
> @moozzyk I'm trying to figure out a way to reduce the size of cursor payload. Apparently it's not possible to reduce it while registering for many groups. Is there any other suggestion? One approach may be handling grouping ourselves on the server side and broadcast separately to each user. Is this a common/suggested scenario?

Yes, that's one way to avoid the bloat and possibly the only way if you want to do group membership.
