### ISSUE TITLE
System.Net.Http.Extensions Not Found.

### ISSUE THREAD

**Issue by sujadkar** [SignalR/SignalR#3815]
I am working on Xamarin Android project.In that,I am using SignalR Client.I have added package reference using Nuget Package Manager.But when I try to build it gives me following error

Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly
'System.Net.Http.Extensions, Vrsion=1.5.0.0,Culture=neutral,PublicKeyToken=b03f5f7f11d50a3a'
Perhaps it doesn't exist in the Mono for Android profile?

I want to know that,Is SignalR support Xamarin.Android?

**Comment by Cheesebaron** [comment]
This is because it depends on Microsoft.Net.Http, it does not install into Xamarin projects anymore.

Would be really neat with a nuget package without this dependency and if SignalR client used a PCL profile, which did not include Silverlight so HttpClient didn't need to come from Microsoft.Net.Http.

**Comment by kashifshaikh** [comment]
@sujadkar I had the same problem. Don't install the SignalR client nuget into Xamarin projects. Instead, Xamarin has created a Component for Signalr, so install that via the Component Store.

**Comment by Cheesebaron** [comment]
@kashifshaikh I can't believe the recommended way of using SignalR is to use an almost 2 year old version of SignalR.

**Comment by moozzyk** [comment]
Possibly a duplicate of https://github.com/SignalR/SignalR/issues/3775

**Comment by sujadkar** [comment]
I solved it by adding a reference to System.Net.Http.Extensions.dll to my Xamarin Android Project.
