### ISSUE TITLE
Since 2.2.0 initial invoke is invoked twice

### ISSUE THREAD

**Issue by yentheo** [SignalR/SignalR#3816]
### Expected  behavior
When doing invoke on a hub proxy, it should only call it once
### Actual behavior
Since 2.2.0 (also in 2.2.1, tested with the cdn https://www.asp.net/ajax/cdn#ASPNET_SignalR_Releases_on_the_CDN_17)
the initial invoke is done twice.
### Steps to reproduce
```typescript
this._hub = $.connection['hub'];
let options: SignalR.ConnectionOptions = { jsonp: true };
$.connection.hub.start(options).done(() => { 
    this._hub.invoke('invoke_something');
});
```

`invoke_something` gets invoked twice on the 'server' the first time.

**Comment by mikaelm12** [comment]
I can't seem to reproduce this behavior. I'm going to close this issue. Feel free to reopen this with more details.
