### ISSUE TITLE
cors and authentication

### ISSUE THREAD

**Issue by siggebecker** [SignalR/SignalR#3819]
### Expected  behavior
I am using signalR with CORS and authentication attribute on the hub.

### Actual behavior
When CORS will be detected while negotiation, the connecting process is stopped and will not finally connect to the hub.

**Comment by moozzyk** [comment]
This issue lacks any details that could make it actionable (e.g. error message/status code, code, repro steps). I would suggest asking this on http://stackoverflow.com with necessary details - it's likely that it will get resolved quicker.
