### ISSUE TITLE
Long pooling error while do ctrl+s in chorme.

### ISSUE THREAD

**Issue by vpatel-TBA** [SignalR/SignalR#3820]
### Expected  behavior
When user press ctrl+s in chrome long pooling get error 'long polling request failed'. This error is not there in Mozilla. So must work ok in all browser.

### Actual behavior
In chrome, it should also works same as Mozilla browser and must do not get an error like long polling request failed.

### Steps to reproduce
Open any signalr client which is connected by long polling protocol in chrome and press ctrl+s, you will get below error.

![image](https://cloud.githubusercontent.com/assets/12032460/20743591/40cd3a3e-b6fd-11e6-8638-5e40b124bedd.png)

**Comment by moozzyk** [comment]
I can see that pressing ctrl+s in chrome does cancel the pending poll request which causes a reconnect:

![image](https://cloud.githubusercontent.com/assets/1438884/20765615/ea76ed84-b6e7-11e6-967c-f636c1288741.png)

but I don't see the error you have. 

Given that this is a browser specific behavior I don't think we can do much about this. Trying to mess with browser events in a library is very likely going to have side effects which will break people. You could file a bug against chrome that it should not abort pending http requests when pressing ctrl+s.

**Comment by moozzyk** [comment]
I actually found this: https://bugs.chromium.org/p/chromium/issues/detail?id=111589 which was resolved as won't fix.
