### ISSUE TITLE
Connect from Silverlight Client is inestable

### ISSUE THREAD

**Issue by augugiacoEnta** [SignalR/SignalR#3821]
Hi everyone,

I have an Silverlight 5 App and I'm trying to add SignalR to this but I have a problem when the client perform the connection to the hub.

Basically, the problem is this:

Sometimes the client connect's successfully and everything is okey(I can send and receive messages) but anothers the connection fails.(arbitrary).

This is my code for the connection:

```
 private HubConnection CreateHubConnection(string url)
        {
            string serverUri = new Uri(url).ToString();
            var connection = new HubConnection(serverUri, true);
            return connection;
        }

        public async Task<IHubProxy> CreateHub(string hubName)
        {
            string serverUri = new Uri(HtmlPage.Document.DocumentUri, "/").ToString();
            var connection = CreateHubConnection(serverUri);
            var hub = connection.CreateHubProxy(hubName);
            try
            {
                await connection.Start();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return hub;
        } 
```

When the connection fails, I receive a HttpClientException with this information:

_"StatusCode: 404, ReasonPhrase: 'Not Found', Version: 0.0, Content: System.Net.Http.StreamContent, Headers:\r\n{\r\n  Content-Length: 0\r\n}"_

I tried solve with this but I have not lucky:
https://www.asp.net/signalr/overview/testing-and-debugging/troubleshooting#other

I will wait for your comments!

Thanks a lot!

**Comment by moozzyk** [comment]
You need to figure out why the server is sending an empty response.

**Comment by augugiacoEnta** [comment]
Hi

**Comment by moozzyk** [comment]
Check server/iis logs to see what url returns 404 this should give you a hint.
