### ISSUE TITLE
(0x80070026): Reached the end-of-file. Web sockets not working on IIS 8.5

### ISSUE THREAD

**Issue by hankir** [SignalR/SignalR#3823]
### Expected  behavior
Not working websockets

**Server trace**
SignalR.Transports.WebSocketTransport Error: 0 : OnError(720b06e6-02cc-4b5f-b07a-e805008e3442, System.Net.WebSockets.WebSocketException (0x80070026): Reached the end-of-file
   в System.Web.WebSockets.WebSocketPipe.<>c__DisplayClass9_0.<ReadFragmentAsync>b__0(Int32 hrError, Int32 cbIO, Boolean fUtf8Encoded, Boolean fFinalFragment, Boolean fClose)
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Web.WebSockets.AspNetWebSocket.<DoWork>d__45`1.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Web.WebSockets.AspNetWebSocket.<>c__DisplayClass36_0.<<ReceiveAsyncImpl>b__0>d.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Microsoft.AspNet.SignalR.WebSockets.WebSocketMessageReader.<ReadMessageAsync>d__3.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Microsoft.AspNet.SignalR.WebSockets.WebSocketHandler.<ProcessWebSocketRequestAsync>d__25.MoveNext())

**Chrome Console**
[12:12:01 GMT+0400 (RTZ 3 (зима))] SignalR: Client subscribed to hub 'chathub'.
jquery.signalR-2.2.1.min.js:9 [12:12:01 GMT+0400 (RTZ 3 (зима))] SignalR: Negotiating with '/signalr/negotiate?clientProtocol=1.5&connectionData=%5B%7B%22name%22%3A%22chathub%22%7D%5D'.
jquery.signalR-2.2.1.min.js:9 [12:12:01 GMT+0400 (RTZ 3 (зима))] SignalR: webSockets transport starting.
jquery.signalR-2.2.1.min.js:9 [12:12:01 GMT+0400 (RTZ 3 (зима))] SignalR: Connecting to websocket endpoint 'ws://w697w81/signalr/connect?transport=webSockets&clientProtocol=1.5&connectionToken=rB6t7Qmn%2B2jyyxRBQcSjewGfWt6ZySBZ5mWmXCozwe9DhoNeZYCHmY%2BByK2jlYnfE3ufBFI3NYQOmM5mMefUL9HxIblFt56AYGn34b6S4MpoWRWOD98skTdQEOEzF4%2Bq&connectionData=%5B%7B%22name%22%3A%22chathub%22%7D%5D&tid=1'.
jquery.signalR-2.2.1.min.js:9 [12:12:01 GMT+0400 (RTZ 3 (зима))] SignalR: Websocket opened.
jquery.signalR-2.2.1.min.js:9 [12:12:01 GMT+0400 (RTZ 3 (зима))] SignalR: Unclean disconnect from websocket: [no reason given].
jquery.signalR-2.2.1.min.js:9 [12:12:01 GMT+0400 (RTZ 3 (зима))] SignalR: Closing the Websocket.
jquery.signalR-2.2.1.min.js:9 [12:12:01 GMT+0400 (RTZ 3 (зима))] SignalR: webSockets transport failed to connect. Attempting to fall back.
jquery.signalR-2.2.1.min.js:9 [12:12:01 GMT+0400 (RTZ 3 (зима))] SignalR: No fallback transports were selected.
jquery.signalR-2.2.1.min.js:9 [12:12:01 GMT+0400 (RTZ 3 (зима))] SignalR: Stopping connection.
jquery.signalR-2.2.1.min.js:9 [12:12:01 GMT+0400 (RTZ 3 (зима))] SignalR: Fired ajax abort async = true.

### Actual behavior
web sockets works

### Steps to reproduce
1. I get sample from https://code.msdn.microsoft.com/SignalR-Getting-Started-b9d18aa9
2. Configure IIS 8.5 (version 8.5.9600.16384) for use web socket.
3. Change javascript "$.connection.hub.start({ transport: ['webSockets'] }).done(..." to use only web sockets
4. Configure tracing on server and browser Chrome (version 54.0.2840.99 m)
5. Web sockets not working

**Comment by moozzyk** [comment]
The error is propagated from OS webSocket implementation. SignalR [closes](https://github.com/SignalR/SignalR/blob/1fba14fa3437e24c204dfaf8a18db3fce8acad3c/src/Microsoft.AspNet.SignalR.Core/Owin/WebSockets/WebSocketHandler.cs#L251) the connection when it receives this error. Unfortunately it is external to SignalR and I don't think there is anything that can be done in SignalR to fix or prevent this error. 

I did try the sample but I could not repro this.

**Comment by hankir** [comment]
Thank's. The problem was the antivirus. He blocked connections web sockets over http, but over https everything is fine.

Sorry for the false alarm :)

**Comment by moozzyk** [comment]
Glad you were able to figure this out!
