### ISSUE TITLE
WPF webBrowser hangs when using signalR

### ISSUE THREAD

**Issue by Dagur** [SignalR/SignalR#3825]
Hi

We have a WPF client that uses tabs and the embedded browser in those tabs. If I use SignalR in one of the of displayed pages, the browser becomes slower and slower each time I make some request (open a new page or do an ajax call). After just a few web requests everything becomes so slow that the client is unusable and has to be restarted. 

I noticed that if I turn on fiddler then everything starts to run smoothly and there are absolutely no problems. I can also view all the pages in any browser (including IE) without these problems. I found [this page](http://www.telerik.com/blogs/help!-running-fiddler-fixes-my-app-) but I don't know if any of those are applicable

We are using signalR 1.2.2.

Thanks

**Comment by moozzyk** [comment]
Have you tried using 2.2.1? Also, if you can view pages using a regular browser but not with the embedded browser control then there seems to be some issue with the control. Do you know what browser the control is based on, what transport is being used and what is causing the slowness?

**Comment by Dagur** [comment]
I'm kind of stuck with the 1.x releases. I'm pretty sure we're using the WPF webrowser https://msdn.microsoft.com/en-us/library/system.windows.controls.webbrowser(v=vs.110).aspx  which uses the latest IE on the user's system so longpolling is the only option that works.

The good news is that I found a way to fix (or at least improve) this by increasing the number of connections that the application is allowed to have at any one time. The default is only 2 so I increased it to 16. See http://stackoverflow.com/a/14458562/1257347

I think it's safe to say that this is not a problem with SignalR

**Comment by moozzyk** [comment]
Thanks for the update. Long Polling tries to keep one pending request (poll) all the time to listen for data from the server. Sending data requires to be able to start a new request - these are short lived though. There are also ping requests (again short lived). So if in your application you are opening other http requests and the limit is 2 there will be some queuing. Increasing the limit is a good workaround so I am going to close this issue.
