### ISSUE TITLE
HubProxy.Subscribe is not threadsafe

### ISSUE THREAD

**Issue by MansVestin** [SignalR/SignalR#3828]
###Expected behavior

HubProxt.Subscribe(eventName) should be thread safe, according to documentation here:
https://www.asp.net/signalr/overview/guide-to-the-api/hubs-api-guide-net-client
 And here:
http://stackoverflow.com/questions/16089876/signalr-hubproxy-invoke-thread-safety

(However, it's stated to be non-thread safe here:
https://msdn.microsoft.com/en-us/library/microsoft.aspnet.signalr.client.hubs.hubproxy(v=vs.111).aspx)

###Actual behavior

HubProxy.Subscribe() accesses the _subscriptions list in a non-thread safe manner. This can cause data to be sent to the wrong subscribtion.

###Steps to reproduce

If you call IHubProxy.On(eventName, onData) (which in turn calls HubProxy.Subscribe) lots of times from different threads at the same time, data from one event may be delivered to another onData callback.
 Adding a lock around the On() call prevents the issue.

**Comment by JuanOnGit** [comment]
What is occurring that causing the application to be non-thread safe? Is user not able to create custom classes, and they have to use static ones to be sure that HubProxy is thread safe?

**Comment by MansVestin** [comment]
The client calls `IHubProxy.On()` lots of times from different threads, because we have one client application which wants set up listeners to many subscriptions at the same time:

```csharp  
        Parallel.For(0, 100, i =>
          {
            var subscriptionName = $"sub{i}";
            hubProxy.On(subscriptionName, data => 
              {
                Console.WriteLine($"Received {data} from {subscriptionName}");
              }); 
          });
```

Since the documentation states that the HubProxy is thread-safe, we assumed that this was ok.
However, the result is that data which the server sent to one subscription might be recieved by another subcription's callback. In the example above, if the data is the same as the event name, we might get the following output:

```
Recieved sub0 from sub0
Recieved sub1 from sub1
Recieved sub3 from sub2   <= This is not expected
...
```
(Data may also be lost completely, depending on the nature of the race conditions which might happen in `HubProxy.Subscribe()`.)

I can of course add a lock around the `HubProxy.On()` calls, but if that's the case I think the documentation should be updated.

**Comment by moozzyk** [comment]
We should fix documentation.

**Comment by moozzyk** [comment]
The documentation has been updated. The question on stackoverflow is asking about `IHubProxy.Invoke` which is indeed thread safe. `IHubProxy.On` is not thread safe.
