### ISSUE TITLE
unload: use navigator.sendBeacon and stop freezing the browser

### ISSUE THREAD

**Issue by MosheL** [SignalR/SignalR#3831]
### Expected  behavior
SignalR can use `navigator.SendBeacon` and do not block the navigation.

### Actual behavior

    e.bind("unload",function(){a.log("Window unloading, stopping the connection.");a.stop(f)})

the browser needs to wait until the server will respond. on a disconnected client or failed server the browser hangs.

### Steps to reproduce

unplug the network
hit `back`

What I think need to do:
```` JS
    var blob= new Blob([JSON.stringify({disconnectInfo:1})], {type : 'application/json; charset=UTF-8'}); // the blob
    navigator.sendBeacon('disconnectAddress', blob )

````

**Comment by FarajiA** [comment]
Adding this update might be a little to cutting edge. It looks like not all browser have this navigator capability.
[(https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon)]

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
