### ISSUE TITLE
Include in ASP.Net 5 app

### ISSUE THREAD

**Issue by paddyfay** [SignalR/SignalR#3833]
Hi,

How is it possible to use signalr with ASP.Net 5, is there any documentation. I have created a new ASP.Net project targeting 4.5.1 framework and added "Microsoft.AspNet.SignalR.Server": "3.0.0-*" to my dependencies in the project.json file.

The referenced dependency is successfully added however no extension methods are available on the injected IServiceCollection or IApplicationBuilder interfaces in my Startup.cs file.

Am i missing a namespace for these extension methods or is this a known issue. Is there documentation outlining out to get this working,

**project.json**
`{
  "userSecretsId": "aspnet5-WebApplication3-cd508da7-56cd-4dd4-a099-4c1d3e76831b",
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-rc1-final",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-rc1-final",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc1-final",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-rc1-final",
    "Microsoft.Extensions.CodeGenerators.Mvc": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc1-final",
    "Microsoft.AspNet.SignalR.Server": "3.0.0-*"
  },

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel",
    "ef": "EntityFramework.Commands"
  },

  "frameworks": {
    "dnx451": {
      "dependencies": {
        "Microsoft.AspNet.SignalR": "2.2.1"
      }
    }
  },

  "exclude": [
    "wwwroot",
    "node_modules"
  ],
  "publishExclude": [
    "**.user",
    "**.vspscc"
  ],
  "scripts": {
    "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ]
  }
}
`

**Comment by moozzyk** [comment]
RC1 are very old bits that are no longer supported. In the meantime we decided to redesign SignalR and it is being worked on in this repo: https://github.com/aspnet/SignalR. Note that these are very early bits that evolve quickly.
