### ISSUE TITLE
JSON custom parser not used when "foreverFrame" transport used

### ISSUE THREAD

**Issue by JiriZidek** [SignalR/SignalR#3834]
From SignalR a WebAPI we need on client to obtain typed Date object instead of plain string. We use this **custom JSON serializer** extension  https://github.com/RickStrahl/json.date-extensions .

We found, that it **works well with websocket or longpolling**. But for **foreverFrame transport it does not work**. The custom JSON deserializer is not used, so instead of Date object we get strings in the fields.

### Expected  behavior
After arrival of data, JSON custom deserializer should be used, when foreaverFrame is transport method.

### Actual behavior
After arrival of data, JSON standard deserializer is used, when foreaverFrame is transport method.

### Steps to reproduce
Attached SLN with Chat example reproducing behavior. Open in IE  Chat.html page.

[SignalR.zip](https://github.com/SignalR/SignalR/files/687896/SignalR.zip)

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
