### ISSUE TITLE
After disconnect. Client is still able to send messages to ServerHub

### ISSUE THREAD

**Issue by AwsomeCode** [SignalR/SignalR#3838]
In some situation I my client is getting disconnected from server side but still I am able to send messages to server but I don't received messages back from server. Its ok. 
But my concerned is why context is still not disposed? I am still able to access my connectionId, objects and other things when I send message from disconnected client. If server is considering that client is disconnected then why his objects and connectionID for that session are still in memory?

Transport type : serverSentEvent

**Comment by moozzyk** [comment]
There is not enough details in the report to make it actionable. How the client is getting disconnected from the server? What context is not disposed and why it needs to be disposed? What do the traces show? How do you know the server is considering the client disconnected? Why would it be required to clean reset connectionId of a disconnected client?

**Comment by AwsomeCode** [comment]
I have found some bug in my code. I have to do more debugging. There is some magic in Asp.net/Signalr. I have to do more test and if required I will reopen this issue. Thanks.
