### ISSUE TITLE
500 Internal Server Error SignalR

### ISSUE THREAD

**Issue by user1890** [SignalR/SignalR#3839]
Getting the below error in one server alone. In all the other servers, it works with out any issue.
HTTP/1.1 500 Internal Server Error
Content-Length: 0
Server: Microsoft-HTTPAPI/2.0
Date: Sat, 21 Jan 2017 03:42:01 GMT

Both SignalRHub and Client is Windows Form Application.

Request:
GET http://deve080:8085/signalr/negotiate?clientProtocol=1.4&connectionData=[%7B%22Name%22:%22MyHub%22%7D] HTTP/1.1
User-Agent: SignalR.Client.NET45/2.2.1.0 (Microsoft Windows NT 6.1.7601 Service Pack 1)
Host: deve080:8085

Any help is appreciated!!

**Comment by moozzyk** [comment]
There is an exception happening on the server side which results in the 500 response. You need to debug the server to see where the exception is coming from.

**Comment by sobelito** [comment]
Seeing the same intermittently. Any hints on where/how to be able to capture this failure event in code?

**Comment by anurse** [comment]
> Will look at this:
> [docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server#handleErrors](https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server#handleErrors)

Yep, that document is likely to help. You can also try accessing the `/signalr` URL from a browser and see if an ASP.NET Error page appears with details.

I would recommend opening a *new* issue if you do get more details **and** believe the error is a problem in SignalR itself. It's easy for comments on closed issues to get lost :).

**Comment by sobelito** [comment]
Thanks for the tip - we will try that if/when it again resurfaces. We are grabbing latest from github (not nuget preview) and will add some logging to see what we see when we cease being able to publish from server and also are unable at same time to signalr/negotiate --- tl;dr; we'll create an issue if we get there and feel so bold. Thanks for the reply.
