### ISSUE TITLE
Question: client side connectionId

### ISSUE THREAD

**Issue by enriko-riba** [SignalR/SignalR#384]
Is it OK to use: var id = myHub._.connection().id; 
to get the clients connection id or is there a more obvious way?

**Comment by AamirNakhwa** [comment]
https://github.com/SignalR/SignalR/issues/384#issuecomment-5629838 this link isn't working, can you please help?

**Comment by BrennanConroy** [comment]
https://github.com/SignalR/SignalR/blob/0ba22650e6eb1e4e4bf523c70951952a559db65d/samples/Microsoft.AspNet.SignalR.Samples/Hubs/ConnectDisconnect/Status.js#L21
