### ISSUE TITLE
Support for Asp.Net Core 1.1

### ISSUE THREAD

**Issue by AbrarJahin** [SignalR/SignalR#3840]
# Issues related to the Asp.NET Core version of SignalR should be filed in the corresponding SignalR repo: https://github.com/aspnet/?utf8=%E2%9C%93&query=Signalr

I am trying to use SignalR with ASP.Net Core 1.1
But failed to get support for Asp.Net Core 1.1, so could not use it in there.
Is there any way to use that in 

### Expected  behavior
Create a basic demo app using signalR and ASP.Net Core 1.1

### Actual behavior
Finding error with - https://www.nuget.org/packages/Microsoft.AspNet.SignalR.Core/

### Steps to reproduce

- Create a new project with AP.Net Core 1.1
- Run command:

        Install-Package Microsoft.AspNet.SignalR.Core

**Comment by moozzyk** [comment]
The version of SignalR for Asp.NET Core is being developed here: https://github.com/aspnet/SignalR. Note this is still work in progress.

**Comment by AbrarJahin** [comment]
Thanks :)

**Comment by yasin-uohyd** [comment]
Hi @moozzyk , Is there any way I can set up signalr in ASP .Net Core 1.1, as we have our code running in production and we do not have any plans upgrade any near future. Any workaround I can till we upgrade to asp net core 2.X.

**Comment by anurse** [comment]
> Is there any way I can set up signalr in ASP .Net Core 1.1, as we have our code running in production and we do not have any plans upgrade any near future.

No, SignalR is only supported in ASP.NET Core 2.1 or higher.

**Comment by yasin-uohyd** [comment]
Thank @anurse.
