### ISSUE TITLE
Could not install package 'Microsoft.AspNet.SignalR.Client 2.2.1' to xamarinmac20

### ISSUE THREAD

**Issue by tofutim** [SignalR/SignalR#3851]
### Expected  behavior
Can install SignalR into xamarinmac20 project

### Actual behavior
Cannot!

You are trying to install this package into a project that targets 'Xamarin.Mac,Version=v2.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

### Steps to reproduce
Start a new Unified API Xamarin Mac library. Try to add Microsoft.AspNet.SignalR.Client 2.2.1 from nuget. Argh!

**Comment by tofutim** [comment]
https://components.xamarin.com/view/signalr suggest there is a 2.2.1.2 version that supports Mac Unified API. But this is not in nuget. Help!

**Comment by moozzyk** [comment]
2.2.1.2 is published by Xamarin. I don't know where/how they publish.

**Comment by tofutim** [comment]
Sorry I'm wrong, it is 2.1.2.2.  I just noticed it SignalR installs onto a Xamarin.iOS Unified API

**Comment by tofutim** [comment]
I just checked, and the SignalR lib looks like

![image](https://cloud.githubusercontent.com/assets/157766/22447264/678fdf80-e706-11e6-95f4-97f3c97179fa.png)

the Newtonsoft.Json lib (which works) looks like

![image](https://cloud.githubusercontent.com/assets/157766/22447272/74142978-e706-11e6-9f62-eac7b03b6417.png)

**Comment by moozzyk** [comment]
I wonder if we just need to target netstandard.

**Comment by moozzyk** [comment]
It seems netrstandard should work for xamarinmac if we are able to target 1.4 - https://docs.microsoft.com/en-us/nuget/schema/target-frameworks

**Comment by tofutim** [comment]
I am targeting netstandard1.3 on all my components. I think if SignalR targeted that it would work.

**Comment by tofutim** [comment]
@moozzyk Pawel, it is possible netstandard is not required. I just checked, and in the latest stable Xamarin Studio, if I make a new Portable library, it is

    <TargetFrameworkProfile>Profile111</TargetFrameworkProfile>

I can add this into my xamarinmac20 project. I think if a portable class was made with Profile111 it would work. I'll try it.

**Comment by moozzyk** [comment]
I'd rather not create yet another portable profile. I think using netstandard is the way to go (either replace netcore50 or add a new TFM).

**Comment by tofutim** [comment]
If you just add the current Profile 344 (lib\portable-net45+sl5+win8+wpa81+wp8
lib\portable-net45+sl50+win+wpa81+wp80) library to lib\netstandard1.1 it will work just fine.

**Comment by tofutim** [comment]
Closed the PR, added note that I confirm xamarinmac20 has ClientWebSocket, but netstandard <2.0 does not.

**Comment by tofutim** [comment]
@moozzyk Are you thinking you might end up with
Microsoft.AspNet.SignalR.Client.Mac
Microsoft.AspNet.SignalR.Client.iOS
Microsoft.AspNet.SignalR.Client.Android

**Comment by tofutim** [comment]
https://github.com/SignalR/SignalR/pull/3855

**Comment by moozzyk** [comment]
netstandard2.0 is to high. I am trying to [cross compile](https://github.com/SignalR/SignalR/compare/pawelka/netstandard) the portable library for netstandard1.3.

**Comment by tofutim** [comment]
did you find WebSockets in 1.3?

**Comment by moozzyk** [comment]
No. The portable library which I am using to cross compile does not have websockets. I originally thought websockets were in one of the netstandard1.x.

**Comment by tofutim** [comment]
I think you might still want these other ones as they will enable
WebSockets in Android, iOS, tvOS, watchOS, and Mac. Those projects merely
contain links to everything in the Client45 project.

**Comment by tofutim** [comment]
@moozzyk I have an idea. How do you feel about making a Shared Library containing the extra bonus WebSocket+ stuff in Client45. This could then be added to the Xamarin flatforms so that linked files don't have to be maintained (if that is the issue).

**Comment by moozzyk** [comment]
I am afraid we cant/won't do that. This all boils down to maintenance, building, testing etc. Also, we tried this approach once with the signalR client for store apps and it did not go well. It was not used by default so people did not know that they were not using websockets and they had to be explicitly configured.  Eventually we ended up creating a complete client since it was much easier to use. It is still hard to maintain - I actually think that warnings and errors you mentioned in your PR are related to this project (this is part of what I refer to as "maintenance" above)

**Comment by tofutim** [comment]
Well let me ask you. If we add the portable nuget package, and then add
another dll that contains the websocket code, will it automatically make it
possible to use websockets? (is it modular?)

I see that the code currently produces the identically named .Client.dll
for all platforms. But it makes me wonder if a scenario where one adds

.Client.Portable.dll (the core SignalR)

and then

.Client.Platform.dll (e.g., .Client.Client45 or .Client.Mac or ...: the
extra goodies)

would work. So that the nuspec delivers both .Portable dll and the
.Platform dll. But I see the issue about "maintenance" - though maybe I
just did not configure things correctly in the build script. If it compiles
in VS shouldn't it work in the build script?

**Comment by moozzyk** [comment]
It wouldn't work automatically. This was the issue with Store webSocket transport I mentioned above. Here is why: https://github.com/SignalR/SignalR/blob/dev/src/Microsoft.AspNet.SignalR.Client/Transports/AutoTransport.cs#L31-L33 - the auto transport cannot be compiled with WebSockets transport because it is in a separate library which it can't take a dependency on.

**Comment by moozzyk** [comment]
Fixed in ff815cf392e47b331b423e900f2dad72f506ff4e c60ba831c040f24e312f6dafa792a976fe9705d2 ed4a08d989bf32a1abf06cd71a95571a8790df82 by creating a netstandard version of the client package.

**Comment by tofutim** [comment]
@moozzyk will this show up in the nightly?

**Comment by moozzyk** [comment]
@tofutim - it should show up here: https://www.myget.org/gallery/aspnetwebstacknightly (unless there is some work on CI needed because of the new dll in the package).

**Comment by moozzyk** [comment]
So, CI has failed. Working with @joeloff on fixing this.

**Comment by moozzyk** [comment]
@tofutim - the packages are now on the aspnetwebstacknigthly feed.
