### ISSUE TITLE
Create IHubProxy from IHubConnection

### ISSUE THREAD

**Issue by connelhooley** [SignalR/SignalR#3852]
### Expected  behavior
Create IHubProxy using an IHubConnection (means everything can be mocked). IHubConnection should do everything a HubConnection can do (e.g. implement IDisposable). If it shouldn't (for whatever reason) there should be an interface available that does. 

### Actual behavior
Concrete HubConnection is required to start and dispose of connection as well as creating proxies. This makes it impossible to mock and unit test.

### Steps to reproduce
The following class is really easy to test using mocks:

    public class Connection
    {
        private readonly IHubConnection _hubConnection;
        private IHubProxy _proxy;

        public Connection(IHubConnection hubConnection)
        {
            _hubConnection = hubConnection;
        }

        //Test 1 - verify connect is called only once
        //Test 2 - verify proxy is created with correct name
        public async Task ConnectAsync()
        {
            await _hubConnection.Start(new WebSocketTransport());
            _proxy = _hubConnection.CreateHubProxy("name");
        }

        //Test 3 - verify connection is disposed
        public void Disconnect()
        {
            _hubConnection.Dispose();
        }
    }

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
