### ISSUE TITLE
Memory Leak in SignalR

### ISSUE THREAD

**Issue by NativeCodeX** [SignalR/SignalR#3857]
All the SignalR functions are using up a lot of memory and when a connection gets released it is not garbage collected.

Here is my dump bin.

https://ufile.io/090e4

**Comment by moozzyk** [comment]
Server or Client? Possibly a duplicate of https://github.com/SignalR/SignalR/issues/3850. Closing for now - please reopen with more details if this is not a dupe of #3850 et al.
