### ISSUE TITLE
How to utilize signalr with Ionic2?

### ISSUE THREAD

**Issue by shyamal890** [SignalR/SignalR#3858]
Trying to utilize signalr in Ionic2.

Steps taken:

- Installed signalr@2.2.1 and jquery@2.2.3 with npm.

- Importing them with
```
 import * as $ from 'node_modules/jquery';
 import 'node_modules/signalr';
```

- Trying to establish connection with server with $.hubConnection(..)

- Fails on run, giving following error:

> jQuery was not found. Please ensure jQuery is referenced before the SignalR client JavaScript file.

**Comment by moozzyk** [comment]
This is how signalR checks if jquery is present: https://github.com/SignalR/SignalR/blob/5c609d17cd556d9c1b8c3eda0b4e37f00a4fc535/src/Microsoft.AspNet.SignalR.Client.JS/jquery.signalR.core.js#L44-L47. Also note that  SignalR relies on `window`.

**Comment by Usman235** [comment]
@shyamal890  i have found any solution to utilize SignalR in ionic 2 ? .I have tried this but fail. 

http://stackoverflow.com/q/43818474/4154016
