### ISSUE TITLE
Task cancelled issue on await Groups.Add(groupId, Context.ConnectionId);

### ISSUE THREAD

**Issue by mfarooqbabar** [SignalR/SignalR#3861]
Task cancelled issue on await Groups.Add(groupId, Context.ConnectionId); still exists with WebSockets on Win8.
How can i increase signalr time out if this request is taking over 30 seconds.

A task was canceled.mscorlibStackTrace: ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Please help me out.

**Comment by moozzyk** [comment]
This seems like a duplicate of https://github.com/SignalR/SignalR/issues/3861. This has not been fixed since we were not able to reproduce this. Please enable tracing on the server and provide logs. If you have a consistent repro please provide a project so that we could investigate.
