### ISSUE TITLE
Second connecting is endless

### ISSUE THREAD

**Issue by Patriack** [SignalR/SignalR#3863]
*English wasn't my first language, sorry for my English.

The issue I got is when I close my server, for testing a server crash, and wait after the reconnecting delay, if I call my connection procedure, the connection status stay at "reconnecting".

For the information about my connection procedure simply loop on connection status string as long is not "Connecting" or "Reconnecting" value. After the loop, I normally got "Connected" or "Disconnected" status. So when I attempt the second connection I stay in my loop as "Connecting" status.

On server side, my custom connection authorization always return true, but he never enter in OnConnection procedure. He also enter in OnDecconnection procedure, but I mind is cause by the  connection timeout.

So my question, what cause this problem? Because the first time the connection append without any problem. Thanks.

**Comment by Patriack** [comment]
For the moment, I just reinitialise my signalR variable to make it work.

But there is a problem who should be check.

**Comment by moozzyk** [comment]
Hard to tell what's happening without seeing the code. Closing. Feel free to reopen with a repro or ask on [stackoverflow](https://stackoverflow.com).
