### ISSUE TITLE
Crank improperly removes connections from ConcurrentBag

### ISSUE THREAD

**Issue by qwoz** [SignalR/SignalR#3865]
The [code for Crank](https://github.com/SignalR/SignalR/blob/dev/src/Microsoft.AspNet.SignalR.Crank/Client.cs#L277) has the following:
```
                connection.Closed += () =>
                {
                    Connections.TryTake(out connection);
                };
```
Where `Connections` is of type `ConcurrentBag<Connection>`. However, `TryTake` removes an arbitrary object from the bag. The fact that `out connection` is passed in doesn't mean you are removing that specific closed connection, which I believe ought to be the intent here. Instead, the code should probably use a `HashSet` or similar where you can remove a specific item, namely, the closed connection.

**Comment by moozzyk** [comment]
Yeah. Seems to be broken. You can't really remove items from a ConcurrentBag. This code should use ConcurrentDictionary.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
