### ISSUE TITLE
SignalR disconnected after POST request on Firefox / IE

### ISSUE THREAD

**Issue by leebarbara** [SignalR/SignalR#3869]
Hello,

I'm using SignalR (2.2.1 with JQuery 1.9.1) to set up a notifications system on my website (asp.net mvc).
Messages are only send by the server to the client. 
Notifications are usually sent through ActionResult method (submitting a form with http post request), then stored in browser local storage, and shown after refreshing the actual page.

```
public ActionResult DoSomeThings()
{
       //doing things..

       //alert client of the result
       var hubContext = GlobalHost.ConnectionManager.GetHubContext<NotificationHub>();
       hubContext.Clients.Client(connectionId).sendNotification("Info", "Your profile has been updated successfully!");

        //redirection
        return RedirectToAction("Index", "Home");
}
```

### For Firefox:
Every time I do POST request, SignalR closes connection. So when I'm inside ActionResult method I cannot send message to my client.

### For Internet Explorer (Microsoft Edge):
In this case, SignalR won't close connection if there's a POST request. But if I send a message and then redirect, it won't be received in time by the client because it takes too long to get it and the page is refreshing.

### For Chrome:
It works like a charm.

**Comment by moozzyk** [comment]
SignalR client closes the connection when the page is navigated from reloaded etc. You seem to be trying relying on SignalR responses beating page reload. I don't think it can work reliably or that it can even be "fixed" in SignalR.
