### ISSUE TITLE
.NET Client HubProxy Invoke stops working after reconnect

### ISSUE THREAD

**Issue by andrewgale** [SignalR/SignalR#3870]
I'm connecting to my SignalR hub via a .Net Client, and invoking a function on the server works fine until the connection is lost from resetting IIS. Once the connection is restored automatically, the Invoke no longer works.

I verified in the web app's logging that the .Net client is successfully reconnecting, and the client's connection state is changing back to Connected. But the Invoke call isn't doing anything. Additionally, if I call Wait() on the invoke, it hangs forever.

Code:

```
//Works fine before connection lost, but hangs after connection restored
myProxy.Invoke("MyServerFunction", param1).Wait(); 
```

Any ideas? I should note that this doesn't happen when the .Net client is running locally and connecting to localhost; it only happens when the connection is made to a remote server.

**Comment by moozzyk** [comment]
If you call `.Wait()` you are likely deadlocking yourself. You should `await` async calls.

**Comment by andrewgale** [comment]
I tried that and it didn't work unfortunately.  Removing the Wait() also doesn't help.  I added Trace logging to the hub connection and you can see the Invoked server function name in the log before the reconnect.  But after reconnect, the log shows no sign of the call anymore.

Any suggestions ?

**Comment by moozzyk** [comment]
Show traces. Show your code.

**Comment by dbakuntsev** [comment]
I've got this problem as well.

Not only that, but also .NET Clients don't detect the disconnection from the server sometimes and continue happily invoking server Hub methods while the server doesn't see any of these calls.

Yeah, I'm moving on to something more reliable. Good luck resolving your issue!

**Comment by andrewgale** [comment]
I ended up just resetting the hubConnection object upon Reconnect state;  I'm not explicitly disposing the connection beforehand, hopefully garbage collection will take care of that.  Doing this seems to be a work-around for my issue.

**Comment by andrewgale** [comment]
I think I finally got this figured out.  For some reason, if you call Invoke without await during reconnect, it prevents the function from working again.  You then have to forcibly disconnect, which causes additional issues.  So I ended up with the following code:

```
if (connected)			
				try
				{
					await notify.Invoke("MyFunction", param);
					Console.WriteLine("Invoke fired");
				}
				catch (Exception ex)
				{
					logger.Error(ex);
				}
```

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
