### ISSUE TITLE
Your public website has broken support links

### ISSUE THREAD

**Issue by cdmdotnet** [SignalR/SignalR#3871]
Visiting http://signalr.net/ you state 

> The SignalR team hangs out in the signalr room at on JabbR.

With two links to a website that throws an azure error. Do you hang out in that broken space anymore? Also "at on JabbR" isn't grammatically accurate.

**Comment by gaurav0106** [comment]
Above issue is there at https://github.com/SignalR/SignalR and http://signalr.net/. 
Also http://signalr.net/ mentions 

> We have a CI Server (http://ci.signalr.net/)

But the link again is broken

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
