### ISSUE TITLE
SignalR Server broadcast with scale out

### ISSUE THREAD

**Issue by cdmdotnet** [SignalR/SignalR#3872]
We've got two competing designs having read https://docs.microsoft.com/en-us/aspnet/signalr/overview/performance/scaleout-in-signalr.

In short what we have is multiple applications across a network of multiple servers broadcasting events/messages to multiple browsers over multiple machines via SignalR. Importantly browsers/clients never connect to an application directly. All clients connect to a server who's sole responsibility is to receive the messages from the server applications and proxy them down to the connected clients - these are called the message-to-client-proxy servers.

The two approaches are:

All servers drop messages on the SignalR Hub and the SignalR scale-out backpane distributes those messages to all the message-to-client-proxy servers which push them down to the browsers.

All servers connect to the message-to-client-proxy servers using a singalR client, pushes the messages via the signalR client directly to A single message-to-client-proxy server which thens pushes that back up to the SignalR scale-out backpane message-to-client-proxy server, which then all them down to the browsers.

The reason we're struggling with this is all example assume the applications / server raising the messages also allow clients to connect to them... which is definitely not our case. 

As the designers of SignalR and it's scaleout pattern, how did/do you intend the above situation be implemented?

**Comment by cdmdotnet** [comment]
Does anyone have a comment on how they'd approach this?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
