### ISSUE TITLE
Multple Hubs OnConnected not fired

### ISSUE THREAD

**Issue by whebz** [SignalR/SignalR#3873]
When I defined 2 hubs like these:
```
public class Hub1 : Hub {
        public override Task OnConnected()
        {
            // some code here
            return base.OnConnected();
        }
}
public class Hub2 : Hub {
        public override Task OnConnected()
        {
            // some code here
            return base.OnConnected();
        }
}
```
after doing:
`$.connection.hub.start();`
none of those ovveride OnConnected method is triggered.
Is not possibile to have OnConnected defined on every hub?

**Comment by cdmdotnet** [comment]
Do you have any public methods?

If you hub has not methods that the client can call... for some reason the onConnected event is never fired. It's a weird design, but it is how it is for now.

You don't even have to call that method from the connected client... one just needs to exist.

**Comment by whebz** [comment]
Yes I do have public methods on both hubs..

**Comment by moozzyk** [comment]
I just verified and it works. I suggest you ask this question on stackoverflow and provide details. What you have provided is not enough to tell why your OnConnected methods are not invoked - maybe the connection is actually not started succesfully?
