### ISSUE TITLE
Zombie .NET Clients after an Azure Web App update

### ISSUE THREAD

**Issue by gsferreira** [SignalR/SignalR#3876]
I have an environment where my SignalR Hub (version 2.2.1) is hosted in a Azure Web App, with a single instance and without backplane. The clients are .net clients (version 2.2.1 also).

### Expected  behavior
I was expecting that after an update to my Web App, the SignalR clients being reconnect without problems.

### Actual behavior
I figured out that sometimes that doesn't happen. 
After every update, I try to broadcast a message and sometimes the clients don't receive the message, but the they continue to trace the KeepAlive message:

`15:39:53.2401116 - ead191e6-807e-471f-8d8e-bc641dbfa8a3 - SSE: OnMessage(Data: {})`

So I assume that for some reason, after some updates, the client isn't in the Hub Connection Context.

### Steps to reproduce

To figure out if the problem is related to my implementation I set up the following scenario.

I have a web application in Azure with a Chat Hub (Root), and a Virtual Directory in the same Web App with another hub.
I created 2 clients that are connected to the hubs (one to the Root site and the other to the Virtual Directory). 

To update the website, I setted up an ARM Template and a powershell script to update the Web App every minute.
After an update, I invoke each Hub sending a Ping to see if anyone reply to my request (to check if anyone is connected)

After 750 attempts I have 5 Pings that doesn't return a response (2 for the Root Hub and 3 for the Virtual Directory Hub). In those cases clients go to a "Zombie" mode and they just recover after another update.

Any recommendation here to deal with it? Is it a bug or am I seeing it wrong?

**Comment by josemaia** [comment]
This issue is still ongoing for us.

An update to the web app caused ~10 different instances of an on-prem service we have executing on different customers to all simultaneously stop communicating with the cloud app.

This is very worrying, and makes us start considering alternatives to SignalR.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Comment by tioazhh** [comment]
This is a really well-documented scenario — I’ve noticed similar issues in Azure Web Apps where SignalR clients occasionally lose hub context after updates, especially without a backplane. The transient “zombie” connections you’re describing often occur when the reconnection logic doesn’t fully reset the negotiation state after a deployment.

You might want to test enabling sticky sessions or using Azure SignalR Service to handle connection persistence more reliably. It helps avoid session drops during app restarts.

It’s interesting how this kind of synchronization reminds me of maintaining an [anime profile](https://jjkcharacters.org/jujutsu-kaisen-characters/yuta-okkotsu/)
 — each connection (or character) has to retain its state and attributes consistently, even after resets or changes. Applying that mindset to connection management often leads to more resilient architectures.
