### ISSUE TITLE
Signal r windows service is not accessible via IP.  400 Bad Request

### ISSUE THREAD

**Issue by abulrehman** [SignalR/SignalR#3878]
# Issues related to the Asp.NET Core version of SignalR should be filed in the corresponding SignalR repo: https://github.com/aspnet/?utf8=%E2%9C%93&query=Signalr

### Expected  behavior
Signal R windows service should be accessible from network and IP instead of localhost.
### Actual behavior
I have hosted the Signal R as a windows service. It is working fine with localhost
protected override void OnStart(string[] args)
        {
            new Logger().WriteLogToTextFile("service started " + DateTime.Now.ToString());
            SqlDependency.Start(connectionString);
            new Logger().WriteLogToTextFile("dependency started " + DateTime.Now.ToString());
            string url = "http://localhost:8089";
            myServer = WebApp.Start(url);

        }
I have changed the localhost with + and * string url = "http://+8089"  , string url = "http://*8089" but still i am getting the same error.  
But when i changed my localhost to my ip it is giving me error **Access is denied**. When i tried to access it from my network it is giving me 404 bad request. Below are the configurations of signalR .
 public void Configuration(IAppBuilder app)
        {
            new Logger().WriteLogToTextFile("configuration initialized");
            app.UseCors(CorsOptions.AllowAll);
            app.MapSignalR();

            //app.Use()
        }

**Comment by shrik36** [comment]
Abul,

Did you try bypassing port from the firewall wherever service is being hosted, if not try doing so and access through IP.

Thanks,
SS

**Comment by abulrehman** [comment]
I have disabled the windows firewall it is still not working, kindly suggest me the appropriate solution. Looking forward for your kind response.

**Comment by abulrehman** [comment]
I have telnet the server successfully working but when i run this code from other machine on network it is giving me an error BAD REQUEST. Do you need any other thing for explanations any code or application i can provide you . But kindly sort out the issue, below is the client code
 var name = textBox1.Text;
            HubConnection hubConnection;
            IHubProxy hubProxy;
            hubConnection = new HubConnection("http://XXX.XX.XX.XX:8089/signalr");
            hubProxy = hubConnection.CreateHubProxy("CustodianHub");
          hubProxy.On<string>("send", (message) => showMessages1(message));
            //hubProxy.On<string>("recieveMessage", (message) => showMessages1(message));
            hubConnection.Start().Wait();

**Comment by moozzyk** [comment]
Binding to non "localhost" requires admin privileges. Bad request may indicate missing machine key. Using `.Wait` or `.Result` in WPF/WinForm applications may cause a deadlock. 

I recommend asking questions on stackoverflow.

**Comment by shrik36** [comment]
Abul,

Based on the codes shared by you here, I've made some changes and posting here, try this and let me know if it works.

HubConnection hubConnection;
IHubProxy hubProxy;
bool isActiveSensing = true;

/// <summary>
/// receives message from Signalr , put this method in form load event.
/// </summary>
 public void SignalRSenseMsg()
`{`
            isActiveSensing = true;
            Thread = new System.Threading.Thread
            (() =>
            {
                try
                {
                    hubConnection = new HubConnection("http://XXX.XX.XX.XX:8089/signalr");
                    hubProxy = hubConnection.CreateHubProxy("CustodianHub");
                    hubProxy.On<string>("send", (message) => showMessages1(message));
                    hubConnection.Start().Wait();
                    while (isActiveSensing)
                    {
                        System.Threading.Thread.Sleep(100);
                    }
                }
                catch (Exception ex)
                {
                    MessageBox.Show(ex.Message);
                }
            }
            ) { IsBackground = true };
            Thread.Start();
        }

**Comment by zhanglong19891129** [comment]
I have the same problem,   SignalR Start in Windows Server. the port is 8080(Firewall installed).But It's Working in localhost. Clients that run on other computers cannot be connected
