### ISSUE TITLE
Windows Server 2012 SignalR IIS configuration help.

### ISSUE THREAD

**Issue by whebz** [SignalR/SignalR#3879]
Hello,
I have my made a simple SignalR and deployed to our Production Server but it does perform poorly. 
I am testing it now with 2 connected users and clients does not recieve their respected message.
I am deployed it under IIS but uses owin.host.systemweb?
What is the minimum IIS server configuration?

One more thing. Every time I tried to invoke server method it always fails get badrequest(400) and respond with "The ConnectionId is in the incorrect format."

And I dont understant why it use LongPolling when websocket is available.

thanks

**Comment by moozzyk** [comment]
We have customers running SignalR with a few thousands SignalR clients connected to a single server. You can find minimal requirements in [this article](https://docs.microsoft.com/en-us/aspnet/signalr/overview/getting-started/supported-platforms). Bad request typically indicates issues with machine key. 
I am closing this ticket as there is nothing to indicate an issue with SignalR. I recommend asking questions on stackoverflow.
