### ISSUE TITLE
Unable to uninstall 'Microsoft.AspNet.SignalR.JS.2.2.0' because 'Microsoft.AspNet.SignalR.2.2.0' depends on it.

### ISSUE THREAD

**Issue by flyfishMT** [SignalR/SignalR#3884]
I want to uninstall Microsoft.AspNet.SignalR.JS.2.2.0 in nuget, but keep the C# libraries. I am using a different package manager for javascript.  It won't let me uninstall the JS because of a dependency, I don't think this is truly dependent on the JS?

Unable to uninstall 'Microsoft.AspNet.SignalR.JS.2.2.0' because 'Microsoft.AspNet.SignalR.2.2.0' depends on it.

**Comment by moozzyk** [comment]
Microsoft.AspNet.SignalR.2.2.0 is a meta package that makes it easy to install all packages you need. It uses dependencies to do the job. If you wan to control each package separately or want to opt-out for some packages you can just uninstall it. This will allow uninstalling the Microsoft.AspNet.SignalR.JS.2.2.0 package.
