### ISSUE TITLE
The serialisation loses information about derived types 

### ISSUE THREAD

**Issue by ghost** [SignalR/SignalR#3885]
Derived type information as lost when serialized in SignalR

### Steps to reproduce
Create a class definitions which looks something like this

```
public class MessageType
{
  primitive type prop1;
  primitive type prop2;
  List<BaseAction> Actions {get;set;}
}
```

> Create two or more derived types for BaseAction; HealAction, HitAction.

> Populate a dummy instance of MessageType with combination of HealAction and HitAction and saving it to the List<BaseAction>.

> Now send the instance of the above created instance of MessageType using `Hub.Invoke("methodName",` InstanceOfMessageType");

Check the object that has been received the type information about the HealAction and HitAction would be replaced with BaseAction.

**Comment by moozzyk** [comment]
I think it might be possible if you register your own serializer in the DI. By default SignalR does not serialize type names so the client does not know what type needs to be used on the client side to deserialize. I wrote it "might" be possible because there is a [bug](https://github.com/SignalR/SignalR/pull/3343) where the server sometimes does not use the registered JsonSerializer (although I think this is in the other direction - payloads sent from the server to the client). 
Also, it seems to be a bit similar to this: https://github.com/SignalR/SignalR/issues/3684 where the OP was able to get type names in the payload to the client. Unfortunately he did not update the thread with the final status.

**Comment by ilanassah** [comment]
Hi Moozzyk,
Thanks for getting back. I have tried quite a tips. I think this is what you mean when registering your own serializer in the DI ?

`
		var myHubJsonSetting = new JsonSerializerSettings()
		{
			TypeNameHandling = TypeNameHandling.All
		};

		var serializer = JsonSerializer.Create(myHubJsonSetting);
		Log.LogInfo("Starting server...");
		_signalR = WebApp.Start(
			GetStartupOptions(),
			builder =>
			{
				builder.UseCors(CorsOptions.AllowAll);
				GlobalHost.DependencyResolver.Register(typeof(JsonSerializer), () => serializer);
				builder.MapSignalR(
					serviceName,
					new HubConfiguration
				{
					EnableJSONP = false,					
					EnableDetailedErrors = _detailedErrors,
					EnableJavaScriptProxies = true
				});
				builder.RunSignalR();
									});

`
It does not work for some reason maybe i am doing something wrong here. But when i try to serialise the .NET object using the serialiser with the TypeHandling property set to All the serilized JSON includes the TypeInformation.

I have been looking at the HubProxy code as well to see if can find something; i observed few things the serialization done here uses the Connection.JsonSerializer property which encapsulates field; which i think is hard referenced to a default JsonSerializer instance.

`
private JsonSerializer _jsonSerializer = new JsonSerializer();
`

So i though maybe i can try to access that instance of JsonSerializer and set its TypeHandling property to include all types, but that gives a Server 503 error.

I am trying out things here; will update if i find anything noteworthy.

**Comment by Mirrawrs** [comment]
I'm experiencing the same issue. I recommend looking at the `JsonSerializeObject` method in the `Microsoft.AspNet.SignalR.Client.ConnectionExtensions` class. As a workaround, set the `TypeNameHandling` property to `TypeNameHandling.All` in the server and use a template similar to the one below in your client:

```csharp
hubProxy.JsonSerializer.TypeNameHandling = TypeNameHandling.All;
await hubProxy.Invoke("MethodName", value);
hubProxy.JsonSerializer.TypeNameHandling = TypeNameHandling.Auto;
```

**Comment by ilanassah** [comment]
Interesting it works for you. Whenever i try to manually set the JsonSerializer's TypeNameHandling to All and then invoke hubProxy.Invoke("MethodName", instance). It always returned a 503 Server error. Remove that type handling messages flow is back to normal. I have decided to workaround this issue by manually serializing the object and then send it to a method as a string and then deserialize it at the receiving end.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
