### ISSUE TITLE
How to set ServerCertificateCustomValidationCallback in .Net Core

### ISSUE THREAD

**Issue by jchannon** [SignalR/SignalR#3886]
For testing purposes I have a self signed cert running in nginx with an app in kestrel behind that. I have a signalr client wanting to invoke a method in a hub. When the code that does this, it fails.  In pre .NetCore times I could do:
```
ServicePointManager.ServerCertificateValidationCallback +=
                  (sender, certificate, chain, sslPolicyErrors) => true;
```

This cannot be done now. I can add a `ServerCertificateCustomValidationCallback` to a `HttpClientHandler` but I can't seem to find a way to do this with the SignalR client as that doesn't use a `HttpClient`. It does ahve a IHttpClient but there is nothing in there that can be used to solve this problem.

### Expected  behavior
Connection allowed to server

### Actual behavior
```
---- System.AggregateException : One or more errors occurred. (An error occurred while sending the request.)
      -------- System.Net.Http.HttpRequestException : An error occurred while sending the request.
      ------------ System.Net.Http.CurlException : Peer certificate cannot be authenticated with given CA certificates
```

### Steps to reproduce
Have a asp.net core server with signalr (`"Microsoft.AspNetCore.SignalR.Server": "0.2.0-preview1-22509",`) running on https.
Create a hub connection and hub proxy, setup some `proxy.On` handlers.
Try to invoke a hub method, get the above error

**Comment by moozzyk** [comment]
As per https://github.com/aspnet/SignalR-Server/blob/dev/README.md Microsoft.AspNetCore.SignalR.Server is deprecated and no longer maintained.

**Comment by jchannon** [comment]
Where did I say I was using SignalR server?

**Comment by moozzyk** [comment]
Have a asp.net core server with signalr ("Microsoft.AspNetCore.SignalR.Server": "0.2.0-preview1-22509",) running on https.

**Comment by jchannon** [comment]
However I'm using `"Microsoft.AspNet.SignalR.Client": "2.2.1",` which I realised I missed

**Comment by moozzyk** [comment]
The thing is that there is no ASP.NET Core SignalR  server SignalR 2.x client can talk to since the one you use is deprecated. For this scenario to be valid you need both the client and the server and you said that in _pre .NetCore times_ things worked. 

The Asp.NET Core SignalR is developed in [this repo](https://github.com/aspnet/SignalR) and it has a new server and a new client. I would recommend checking this version and file an issue in that repo if things are not working.
