### ISSUE TITLE
C# Client can't connect to IIS

### ISSUE THREAD

**Issue by Patriack** [SignalR/SignalR#3888]
hi, (sorry for the English)

To explain the issue, I have to put a context. So, my application is break in two parts : a signalr server and a c# application, which using signalr. In the debug each of the work well, but I have to put the signalr server on a IIS server (not the express) to be able to access with a URL.

As I said, using the URL in debug is pretty well. But when the server is on IIS, the application cannot connect.

To try to debug I also create a web page to try the connection, and it work. So the problem not came from a wrong IIS binding.

**Comment by moozzyk** [comment]
Unfortunately this report lacks details that would allow us to investigate. I recommend asking questions on http://stackoverflow.com.

**Comment by Patriack** [comment]
Alright, I find out what is the problem.

The application had difficulty to connect to the IIS server, because my signalr server was in a virtual folder.

When I use directly the root path, my application be able to connect to my server.

Hope that will help someone else.

**Comment by moozzyk** [comment]
Thanks for reporting back
