### ISSUE TITLE
SignalR connections are not disposing - causing Azure App socket exhaustion

### ISSUE THREAD

**Issue by nomorechickenstrips** [SignalR/SignalR#3889]
SO Post here: http://stackoverflow.com/questions/42637488/azure-and-signalr-system-net-sockets-socketexception-an-attempt-was-made-to-ac

I'm currently experiencing this issue at a high frequency: 

> System.Net.Sockets.SocketException: An attempt was made to access a
> socket in a way forbidden by its access permissions

Sometimes it happens when connecting to Azure Storage from my web app (code below), but most of the time it happens with SignalR.

Based on debug diag, I see the following: 

> 394 client connections in w3p.dmp have been executing a request for more than 90 seconds.

Based on the memory dump, there are a significant number of connections being made to `/signalr/connect` and `/signalr/reconnect`.

It looks like I'm using AspNet.SignalR.WebSockets.WebSocketHandler to make SignalR connections from within code.  At this point I'm not sure what to look for though - what could be the culprit?  We have a web service living in Azure, with web apps and mobile apps connecting to a SignalR backplane (redis).  

**Screen from debug diag**

[![enter image description here][1]][1]

**Code for Azure Storage**

        public void EnqueueRequest(int requestId)
        {
            // Retrieve storage account from connection string.
            CloudStorageAccount storageAccount = CloudStorageAccount.Parse(ConfigurationManager.AppSettings.Get("AzureStorageConnectionString"));

            // Create the queue client.
            CloudQueueClient queueClient = storageAccount.CreateCloudQueueClient();

            // Retrieve a reference to a queue.
            CloudQueue queue = queueClient.GetQueueReference(ConfigurationManager.AppSettings.Get("requestQueueName"));

            // Create a message and add it to the queue.
            CloudQueueMessage message = new CloudQueueMessage(castingCallId.ToString(CultureInfo.InvariantCulture));

            queue.AddMessage(message);
        }

**Hub Proxy Code**

    var baseUrl = _dbContext.CurrentTenant.BaseUrl;
    _hubConnection = new HubConnection(baseUrl);
    _hubProxy = _hubConnection.CreateHubProxy("appHub");
    await _hubConnection.Start();
    string serialized = null;
    try
    {
       serialized = JsonSerializerExtensions.SerializeObject(data).SanitizeData();
       await _hubProxy.Invoke((isTypingNotification ? "SendTypingNotification" : "SendClientNotification"), serialized, username);
    }
    catch (Exception exception)
    {
        LogError("1: " + exception);
    }

  [1]: https://i.stack.imgur.com/eL7A1.png

**Azure Support feedback** 

It looks like you are using AspNet.SignalR.WebSockets.WebSocketHandler to make SignalR connections.
ASP.NET WebSockets are automatically disposed of when the code finishes executing, so unless you are doing something custom with the management of websocket connections, you shouldn’t need to explicitly dispose of them (although calling a method to close the connection after no longer needed, such as calling CloseAsync, might be an extra step you can take).
 
The other possibility is that the connections can’t be optimized and that scaling is the best option. WebSockets can inherently consume a lot of connections under load since the app / server is making a connection back to the client, so this is a likely possibility.
 
This is the furthest visibility we have into what is happening. Hope this is helpful to you for narrowing things down.

- The bulk of these connections appear to be WebSocket over HTTPS connections. For example:
GET request for   /signalr/reconnect?clientProtocol=1.4&transport=webSockets&connectionData={snipped}&connectionToken={snipped}
Mapped To URL   /signalr/reconnect
HTTP Version   HTTP/1.1
SSL Request   True
Time alive   00:31:51
QueryString   clientProtocol=1.4&transport=webSockets&connectionData={snipped}&connectionToken={snipped}
Request mapped to   
- The limit for connections is 3968 connections per instance in Medium tier, and 8064 per instance in Large tier (which is the largest tier available in App Service).
- There isn’t a way to get more connections allocated to instance in a given tier.
- Correct: signalR, storage client, etc all share the same pool of connections on the machine. So if, for example, signalR is using up the connections, Storage, etc will encounter the issue even if they aren’t using many connections.
- Unfortunately no definite guidance on how to mitigate this. With Websockets, the connection disposal is automatically managed by .NET.  However, there is an example posted at the following GitHub respository on how to manage closing & disposing of WebSockets connections via code:
https://github.com/paulbatum/WebSocket-Samples/blob/master/HttpListenerWebSocketEcho/Server/Server.cs
-Based on IPs in the Client Connections the dump, it looks like a significant number of connections are coming from other App Services (IPs in the 137.117.x.x range). Unfortunately it isn’t determinable from this information which App Services these connections are coming from.
-In this particular situation, the most relevant section was the Client Connections section that I was referring to. I was able to extrapolate that these are System.Web.WebSockets.AspNetWebSocket calls by looking at the Previous .NET Exceptions Report in the Analysis Summary. At this point, I’m not seeing anything further in the dump to narrow down the issue further, so at this point it would be a matter of reviewing the app to see if you can possibly optimize the connections (eg, the above example, although this might not have noticeable effect).

**Comment by nomorechickenstrips** [comment]
I'm down for paying someone to help out with this if there's anyone familiar with socket management / signalr.  In a bit of a pickle here.

**Comment by moozzyk** [comment]
Do you close the connections on the client? What is causing reconnects? Do you have any reconnection logic on the client (e.g. in the Closed event)? Have you tried using  a newer version of SignalR (protocol=1.4 tells me that the version you are using is quite old)?

**Comment by nomorechickenstrips** [comment]
@moozzyk I believe so.  Let me post more code so you can see all things SignalR in my app.  Are you available for paid consultation by the way?

**AppHub**

        [HubName("appHub")]
        public class AppHub : Hub {

        private ConnectionService _connectionService;
        public AppHub() {
            _connectionService = new ConnectionService(new DbContext());
        }

        // called from chatVm.js
        public async Task ConnectUserToChat() {
            var username = Context.GetUsername();
            // the user has just opened up chat
            // add user connection for individual chats
            await _connectionService.AddConnectionAsync(username, Context.ConnectionId, ConnectionType.Chat);
        }

        public async Task DisconnectUserFromChat()
        {
            var username = Context.GetUsername();
            await _connectionService.RemoveConnectionAsync(username, Context.ConnectionId, ConnectionType.Chat);
        }

        public async Task SendMessage(String key, MessageDto message)
        {
            var type = ConnectionType.Chat;
            // Key parameter is polymorphic
            var connections = await _connectionService.GetConnectionsAsync(key, type);
            foreach (var connectionId in connections) {
         Clients.Client(connectionId).addChatMessage(JsonConvert.SerializeObject(message).SanitizeData());
            }
        }

        // used when user joins chat
        [Authorize]
        public async Task SendOnlineUserUpdate(string key, OnlineUserViewModel dto, bool isOnline)
        {
            var connectedUsers = await _connectionService.GetConnectionsAsync(key, ConnectionType.Chat);
            foreach (var connectionId in connectedUsers) {
                Clients.Client(connectionId).updateOnlineUser(JsonConvert.SerializeObject(new { user = dto, isOnline = isOnline }).SanitizeData());
            }
        }

        // used for typing notifications
        public async Task SendTypingNotification(string notification, string key)
        {
            var navbarClients = await _connectionService.GetConnectionsAsync(key, ConnectionType.Chat);
            foreach (var connectionId in navbarClients) {
                Clients.Client(connectionId).clientNotification(notification);
            }
        }

        // consumed by .NET client - _hubProxy.Invoke fails on localhost and staging for some reason.  Only works in prod (urls are correct) 
        public async Task SendClientNotification(string notification, string key)
        {
            var navbarClients = await _connectionService.GetConnectionsAsync(key, ConnectionType.Navbar);
            foreach (var connectionId in navbarClients) {
                Clients.Client(connectionId).clientNotification(notification);
            }
        }

        [Authorize]
        public async Task BroadcastChatNotification(string notification)
        {
            // send message to only other users that are connected to chat, nobody else cares 
            var navbarClients = await _connectionService.GetConnectionsAsync(ConnectionType.Chat);
            foreach (var connectionId in navbarClients) {
                Clients.Client(connectionId).clientNotification(notification);
            }
        }

        public override async Task OnConnected() {
            await HandleConnectionAsync(Context);
            await base.OnConnected();
        }

        public override async Task OnDisconnected(bool stopCalled) {
            await HandleConnectionAsync(Context, true);
            await base.OnDisconnected(stopCalled);
        }

        public override async Task OnReconnected() {
            await HandleConnectionAsync(Context);
            await base.OnReconnected();
        }

        private async Task HandleConnectionAsync(HubCallerContext context, bool shouldDisconnect = false) {

            if (Context.User == null)
                throw new InvalidDataContractException("Error");
            var username = Context.GetUsername();            
            
            // I put all connection logic into HandleConnection because I didn't want to repeat code between OnReconnected and OnConnected
            if (username == null && context != null && context.User != null && context.User.Identity != null) {
                username = context.User.Identity.Name;
            }

            if (shouldDisconnect) {
                // remove navbar connections, and chat connections if there are any

                // handle navbar + chat disconnects
                await _connectionService.RemoveConnectionAsync(username, Context.ConnectionId, ConnectionType.Navbar);
                await _connectionService.RemoveConnectionAsync(username, Context.ConnectionId, ConnectionType.Chat);
            }
            else {
                await _connectionService.AddConnectionAsync(username, Context.ConnectionId, ConnectionType.Navbar);
            }
        }
    }


**Client code**

           var startSignalR = function () {
                window.hubReady = $.connection.hub.start({ transport: 'longPolling' }); // to alleviate issues until I identify a fix
                //window.hubReady = $.connection.hub.start();
                window.hubReady.done(function () {
                    heartbeatService.startbeat($.connection.hub.id);
                });
            }

            $.connection.hub.logging = true;

                $.connection.hub.disconnected(function () {
                    startSignalR();
                });

                $.connection.hub.connectionSlow(function () {
                    //toastr.warning("slow");
                });

                $.connection.hub.reconnecting(function () {
                    //toastr.warning("reconnecting");
                });

                var hub = $.connection.appHub;

                hub.client.clientNotification = function (notification) {// do stuff}

**NotificationService**

        public NotificationService(CommService commservice, DbContext dbContext)
        {
            _commService = commservice;
            _baseUrl = ConfigurationManager.AppSettings["BaseUrl"];
            //_baseUrl = "http://localhost:56472/";
            _dbContext = dbContext;
            _hubConnection = new HubConnection(_dbContext.CurrentTenant.BaseUrl);
            _hubProxy = _hubConnection.CreateHubProxy("appHub");
        }

        public async Task SignalObjectToUser(object data, string username, bool isTypingNotification = false)
        {
            try
            {
                await _hubConnection.Start();
                var serialized = JsonSerializerExtensions.SerializeObject(data).SanitizeData();
                await _hubProxy.Invoke((isTypingNotification ? "SendTypingNotification" : "SendClientNotification"), serialized, username); // fails everywhere but production
            }
            catch (Exception e)
            {
                LogError("1: " + e);
            }
        }

**Startup.cs**

         public void Configuration(IAppBuilder app)
         {
            // Any connection or hub wire up and configuration should go here
            var hubConfiguration = new HubConfiguration { EnableDetailedErrors = true };
            var redisConfiguration = new RedisScaleoutConfiguration(ConfigurationManager.AppSettings.Get("RedisConnection"), "sss");
            TurnOfForeverFrame(GlobalHost.DependencyResolver);
            GlobalHost.DependencyResolver.UseRedis(redisConfiguration);
            ServicePointManager.DefaultConnectionLimit = 10;
            app.MapSignalR(hubConfiguration);
        }

        public static void TurnOfForeverFrame(IDependencyResolver resolver)
        {
            var transportManager = resolver.Resolve<ITransportManager>() as TransportManager;
            transportManager.Remove("foreverFrame");
        }

**Comment by moozzyk** [comment]
I don't see the connection in SignalObjectToUser to be closed.

**Comment by nomorechickenstrips** [comment]
@moozzyk is that as simple as `_hubConnection.Stop();`?

**Comment by nomorechickenstrips** [comment]
@moozzyk also - if you're open to it, I'd appreciate a chance to capture feedback from you on my overall implementation.  I'm preparing for scale and want to make sure I'm doing this right - I'm absolutely open to paying as I'm a junior dev desperate for some learnings here.

**Comment by moozzyk** [comment]
@nomorechickenstrips - Yes, you just need to call Stop() on the connection (ideally in a `finally` block so the connection gets closed even if and exception is thrown) or use the `using` statement. Also, it is not clear to me from your code but if you open a connection to send just one message then it is very expensive. You should open the connection once and keep using it instead of opening and closing continuously. Opening a connection requires sending 3 http requests to the server and requires a lot of work on the serve side.

**Comment by nomorechickenstrips** [comment]
@moozzyk I'm not sure where `_hubConnection.Start()` should be then - the constructor of this `NotificationService` gets called every time a request comes through (typing notifications, messages, etc).  Thoughts?

**Comment by moozzyk** [comment]
Can't tell because I have no idea how it is being called - in the code you provided nothing references it.

**Comment by nomorechickenstrips** [comment]
@moozzyk do you have a way that I can share my screen with you and then post up my learnings around best practices to this question and the SO post to benefit the community?

**Comment by moozzyk** [comment]
@nomorechickenstrips - I think you now have some ideas to implement. As the first step make sure you are stopping the connection. Test if this helps. Opening just one connection is the second step.

**Comment by nomorechickenstrips** [comment]
@moozzyk Thank you for the response.  The challenge is that these issues only occur on production (high load).  When the issue happens it kills usability for many users.  I've implemented long-polling and the connection closure which so far seems to have done the trick at alleviating the above issue, but I am interested in a more in-depth form of code review from someone that knows the tooling, proper architecture for scaling etc... is there some kind of support channel I can use for this (other than forums / SO)?  It's a relatively simple implementation as you can see above.  Again, if you were to offer this kind of support I would be more than happy to do a write-up on the things that are learned and share on SO/wherever else you think would help.  Some kind of "Best practices for SignalR scaleout and architecture" tips.
