### ISSUE TITLE
SignalR 2.2.1 ASP.NET MVC 5 Edge/IE issue

### ISSUE THREAD

**Issue by E75** [SignalR/SignalR#3890]
I have a problem with Signal r 2.2.1 ASP.NET MVC 5.  On chrome the SignalR server works great, but on Edge or IE he doesn't work.

The Signal R server is an ASP.NET MVC 5 Project.

Microsoft Edge SignalR Logging
![edge](https://cloud.githubusercontent.com/assets/9724772/23797818/fa6ebf56-05a1-11e7-931f-c6c5afe26aac.png)

Chrome Logging
![chrome](https://cloud.githubusercontent.com/assets/9724772/23797825/01514898-05a2-11e7-9994-afbce43a9a5f.png)

Can someone help me with this issue?

**Comment by moozzyk** [comment]
You seem to have websockets disable on the server side. Edge and IE does not support SSE so the client falls back to long polling. Looking at the log you seem to have multiple connections running.  - I can see you have a negotiate request after connect. Maybe you are hitting a browser limit of simultaneous connections?

**Comment by E75** [comment]
Chrome use also WebSocket and that's doing very well. Problem is Edge/IE falls back to long polling. When i build SignalR as an Service (dll) it's doing very good, but when i build SignalR Server as Web.Application, (ASP.NET MVC5) then Edge/IE doesn't working anymore

**Comment by moozzyk** [comment]
Both IE and Edge support webSockets. As I said above - you seem to have webSockets disabled on the server side since even chrome is trying to use serverSentEvents. You also seem to have multiple connections running.
