### ISSUE TITLE
Use of signalR into embedded device

### ISSUE THREAD

**Issue by pburgio** [SignalR/SignalR#3891]
Hello,

I am trying to create a very simple WebSockets client (send and receive text data - JSON objects) from within an Arduino, where I cannot run a full .net stack.  To do so, I firstly  set up a simple server using your "Microsoft.AspNet.SelfHost.Samples" example, and then I tried to start a client connection to it using raw http Exchange with fiddler.

Unfortunately, it seems that my request fails due to some missing params to the http request ("transport", "connectionToken"). So, my question is: is there some example I can use as an example to build a WebSocket client to a SignalR server? Ever looking inside the C# code of your examples would be enough

Best
Paolo

**Comment by moozzyk** [comment]
To be able to start a SignalR 2.x connection you need to follow the SignalR protocol. I described the protocol SignalR 2.x uses [here](https://blog.3d-logic.com/2015/03/29/signalr-on-the-wire-an-informal-description-of-the-signalr-protocol/). You can find C# and JavaScript implementations of this protocol in this repo and a C++ implementation [here](https://github.com/aspnet/SignalR-Client-Cpp). The new version of SignalR is being developed [here](https://github.com/aspnet/SignalR) allows using bare WebSockets to connect to SignalR server.
