### ISSUE TITLE
Closing the tab in the Safari browser in iOS10 does not trigger the server's OnDisconnected event

### ISSUE THREAD

**Issue by mishengqiang** [SignalR/SignalR#3896]
### Expected  behavior

Close the Safari tab to trigger the server's OnDisconnected event.

### Actual behavior

Close the Safari tab does not trigger the server's OnDisconnected event, but the refresh will trigger.

### Steps to reproduce

In the UIWebView is correct, but in WKWebView will be the above problems.

I guess it may be related to the unload event.

[Apple Safari Supported Events](https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/HandlingEvents/HandlingEvents.html#//apple_ref/doc/uid/TP40006511-SW5)

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
