### ISSUE TITLE
Consuming high memeory when data is sent at faster rate

### ISSUE THREAD

**Issue by suhasjgtp** [SignalR/SignalR#3897]
We are sending data to a group every  having single connection onlys. We are sending around 7000 Messages each containing around 7KB of data every minute. Messages are getting received by the browser however, the memeory usage of  W3WP instance gradually increases over the time finally reaching over 3GB. 

We have captured a memory dump. You can download the same from https://www.dropbox.com/s/62w3s3wtpjdq47y/w3wp.rar?dl=0

We found that the SignalR-Message objects are consuming high memory.

![capture3](https://cloud.githubusercontent.com/assets/26618298/24241218/0d507d02-0fda-11e7-9243-ca8f99aaba22.PNG)

**Comment by moozzyk** [comment]
https://github.com/SignalR/SignalR/issues/3850#issuecomment-276149895
