### ISSUE TITLE
Is version 2.2.2 due for release soon?

### ISSUE THREAD

**Issue by paulduran** [SignalR/SignalR#3900]
Hey guys,

Just wondering if version 2.2.2 is due for release soon. We're experiencing some issues that #3093 will hopefully resolve and so I'm just wondering whether to wait a little bit longer or whether I should build it from source?

**Comment by moozzyk** [comment]
No exact date but it's going to be soon. You can try nightly builds from https://www.myget.org/gallery/aspnetwebstacknightly

**Comment by paulduran** [comment]
Thanks for the update @moozzyk !

**Comment by moozzyk** [comment]
2.2.2-preview1 is now on NuGet

**Comment by sondreb** [comment]
Couldn't find anywhere it was announced that 2.2.2 is released, but in case someone searches up 2.2.2 on issues here, it appears to be released on NuGet! 👍

**Comment by sondreb** [comment]
2.2.2 is not out on NPM just yet, please make sure whoever is in charge to get it updated: https://www.npmjs.com/package/signalr

**Comment by moozzyk** [comment]
@sondreb - the repo [was updated](https://github.com/SignalR/bower-signalr/blob/master/package.json#L3) and you can use the repo to install the module into your project. We are not the owners of the package in the npm registry.

**Comment by sondreb** [comment]
I sent an e-mail to the owner of the "signalr" package, he apparently don't own it any longer, think it's moved to Microsoft/SignalR, he communicated with NPM registry and I think they will be updating it soon to 2.2.2 :-)

**Comment by moozzyk** [comment]
@sondreb - I was not aware of this but I just spoke to @muratg who says we actually can now push the package to the registry. @muratg is going to do this. Thanks for bringing this to my attention.

**Comment by muratg** [comment]
@sondreb Yes, just pushed 2.2.2 to npm this morning. Thanks, and please let us know if you hit any issues.
