### ISSUE TITLE
PreserveCultureAwaiterPreservesCulture fails after updating xUnit from 1.9.1 to 2.2.0. 

### ISSUE THREAD

**Issue by moozzyk** [SignalR/SignalR#3901]
PreserveCultureAwaiterPreservesCulture fails after updating xUnit from 1.9.1 to 2.2.0. 
(We actually saw exactly the same in SignalR-Server https://github.com/aspnet/SignalR-Server/blob/9680e9c2c185a19604390003a6f10489d0538a56/test/Microsoft.AspNetCore.SignalR.Server.Tests/TaskAsyncHelperFacts.cs#L127-L128.) Maybe worth asking xUnit folks if they have any ideas.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
