### ISSUE TITLE
Fix how we close Redis connection

### ISSUE THREAD

**Issue by moozzyk** [SignalR/SignalR#3913]
https://github.com/SignalR/SignalR/blob/5d9611358db7fa069ea69b68428cddc9e7cc0fef/src/Microsoft.AspNet.SignalR.Redis/RedisConnection.cs#L46-L51

I don't think anyone reported this but it is still wrong and can cause issues.

**Comment by sondreb** [comment]
Not sure if this is the issue we've had, but we had to drop Redis backplane as it's was very buggy. Hoping 2.2.2 will have all the fixes to make Redis stable.

Some details on the investigation I did earlier with Redis problems: https://stackoverflow.com/questions/42975051/signalr-does-not-drop-websocket-connections-perf-connections-current-websocke

**Comment by moozzyk** [comment]
@sondreb - I don't think you are hitting this issue. IMHO this is a benign bug which honestly should never surface. I read your SO post (in fact I commented on it back in March) but I don't think it is possible to tell why you see connection leaks with Redis without seeing the code and the repro. We did fix a number of Redis releated issues in 2.2.2 (the full list is here: https://github.com/SignalR/SignalR/issues?q=is%3Aissue+milestone%3A2.2.2+is%3Aclosed) but none of them resembles what you are seeing. There was however a webSocket connection leak on the server side that was fixed in 2.2.2 - https://github.com/SignalR/SignalR/issues/3910. It could happen if the client dropped a webSocket immediately after connecting. I wonder if using  Redis made the window when this could happen bigger and therefore it was harder to observe without Redis. Can you try 2.2.2-preview1 (it is on NuGet now) to see if the issue is fixed? If it is not please open a new issue with some minimal repro app and repro steps so that it is possible to investigate.

**Comment by sondreb** [comment]
The WebSocket connection leak and the Redis problem might not be related, but the WS leak (at least in the perf counters) was just something that manifested on the servers, but the actual connection problem was Redis issues which at random times failed and stopped accepting any SignalR connections at all.

I'll do some testing on TEST with 2.2.2, but can't test it in production easily, hoping that 2.2.2 RTM will be out soon, but will test the preview on a TEST environment.

**Comment by sondreb** [comment]
I was hoping that the problems with Redis as backplane for SignalR was fixed in 2.2.2, but this is not the case for a problem we are seeing.

Just out of the blue, with not a lot of load on the servers, SignalR stops accepting connections and new users receive errors such as "No transport could be initialized successfully. Try specifying a different transport".

And issues such as: "The Web Socket transport is in an invalid state, transitioning into reconnecting."

This triggered clients to starting reconnecting, etc. which created an 100% CPU spike on Redis, and doubled the amount of Set operations on redis cache until the service with SignalR was restarted.

**Comment by moozzyk** [comment]
Were you able to debug the server? Do you know if there were any exceptions on the server? Do you have any traces from the server and/or a dump?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
