### ISSUE TITLE
System.Net.Http defined in two assemblies when installing SignalR.Client to .NETStandard 1.6 project

### ISSUE THREAD

**Issue by dagrooms52** [SignalR/SignalR#3914]
### Expected  behavior
Project compiles

### Actual behavior
Project fails to compile with error message:

```error CS0433: The type 'HttpRequestMessage' exists in both 'System.Net.Http, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'```

### Steps to reproduce

- Create a project targeting .NET standard 1.6
- Install Microsoft.AspNet.SignalR.Client (.NETStandard v1.3 listed as dependecy)
- Build

### Further Information
Issue was originally reported [here](https://github.com/dotnet/corefx/issues/16993)

**Comment by moozzyk** [comment]
I created a library targeting Net Standard 1.6 and installed SignalR client 2.2.2-preview1 and was able to build the project without errors. I used VS 2017. Here is my csproj file:

```Xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.6</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.SignalR.Client" Version="2.2.2-preview1" />
  </ItemGroup>

</Project>
```
Please provide more details so I can repro the issue.

**Comment by dagrooms52** [comment]
I left out that I have a package fallback tag in the csproj targeting PCL profile78 (portable-net45+win8+wp8); I wonder if this could be mixing up the install.

**Comment by moozzyk** [comment]
I don't think it is the culprit. I updated my test project like this:
```Xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.6</TargetFramework>
    <PackageTargetFallback>portable-net45+win8+wp8</PackageTargetFallback>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.SignalR.Client" Version="2.2.2-preview1" />
  </ItemGroup>

</Project>
```
restored packages and it still builds fine. I think you have something that pulls/references the other version of System.Net.Http. Why do you need the fallback in the first place? Because you might have added the callback to be able to force installing a non-netstandard package which pulls/depends on a conflicting version of System.Net.Http.

**Comment by dagrooms52** [comment]
It seems that we got caught in a little version issue, with the help of the TargetFallback; I was installing the 2.2.1 stable version, and getting this error - I'm unable to install this version without the TargetFallback. However, 2.2.2-preview1 installs and works. It may be wise to consider a clearer versioning strategy, but I won't press the matter; my issue is resolved.

**Comment by moozzyk** [comment]
netstandard client is new in 2.2.2.
