### ISSUE TITLE
CRANE for hub connection

### ISSUE THREAD

**Issue by srirams007** [SignalR/SignalR#3915]
Hi All

Will the CRANE tool works for hub connection. I see the code merged with the dev branch. Is this integrated and tested in the latest release?. Can I use the crane for the doing the performance testing for the hub connection in signalR project.

**Comment by moozzyk** [comment]
I assume you are talking about the Crank tool. Crank does not support testing Hubs - only PersistentConnections. You can find an article about using Crank for load testing [here](https://docs.microsoft.com/en-us/aspnet/signalr/overview/performance/signalr-connection-density-testing-with-crank). Also take a look at [this stackoverflow thread](http://stackoverflow.com/questions/10628926/what-is-the-best-way-to-load-test-a-signalr-hubs-application) for ideas how to test hubs.
