### ISSUE TITLE
Signalr fails to deliver messages after IIS site stop/start

### ISSUE THREAD

**Issue by janitha000** [SignalR/SignalR#3916]
We have a implementation where there is one server and several clients connected via signalr. The server is host in IIS 8.5. The issue occurs when I stop and start the IIS website (Not the IIS itself). I noticed that by doing that clients does not fire disconnect event for how long I keep the IIS web site stopped. It keeps sending the keepalive message from the signalr without disconnecting. 
 
Some trace file log lines while the IIS web site is stopped. 
```
2017-04-20 09:29:54.2823 DEBUG [TID:18 TName:]  03:59:54.2823549 - 39267535-7ed1-409e-8ac0-f3634e5c3fb7 - WS: OnMessage({})
 (PrintConnector.Util.SignalrTraceWriter.Write) 
2017-04-20 09:30:04.3127 DEBUG [TID:15 TName:]  04:00:04.3127357 - 39267535-7ed1-409e-8ac0-f3634e5c3fb7 - WS: OnMessage({})
 (PrintConnector.Util.SignalrTraceWriter.Write) 
2017-04-20 09:30:14.3444 DEBUG [TID:18 TName:]  04:00:14.3444044 - 39267535-7ed1-409e-8ac0-f3634e5c3fb7 - WS: OnMessage({})
 (PrintConnector.Util.SignalrTraceWriter.Write) 
2017-04-20 09:30:24.3623 DEBUG [TID:15 TName:]  04:00:24.3623745 - 39267535-7ed1-409e-8ac0-f3634e5c3fb7 - WS: OnMessage({})
 (PrintConnector.Util.SignalrTraceWriter.Write) 
2017-04-20 09:30:34.3916 DEBUG [TID:19 TName:]  04:00:34.3916956 - 39267535-7ed1-409e-8ac0-f3634e5c3fb7 - WS: OnMessage({})
 (PrintConnector.Util.SignalrTraceWriter.Write) 
2017-04-20 09:30:44.4224 DEBUG [TID:15 TName:]  04:00:44.4224868 - 39267535-7ed1-409e-8ac0-f3634e5c3fb7 - WS: OnMessage({})
 (PrintConnector.Util.SignalrTraceWriter.Write) 
2017-04-20 09:30:54.4543 DEBUG [TID:19 TName:]  04:00:54.4543222 - 39267535-7ed1-409e-8ac0-f3634e5c3fb7 - WS: OnMessage({})
 (PrintConnector.Util.SignalrTraceWriter.Write) 
2017-04-20 09:31:04.4895 DEBUG [TID:15 TName:]  04:01:04.4895952 - 39267535-7ed1-409e-8ac0-f3634e5c3fb7 - WS: OnMessage({})
 (PrintConnector.Util.SignalrTraceWriter.Write) 
2017-04-20 09:31:14.5298 DEBUG [TID:3 TName:]  04:01:14.5298402 - 39267535-7ed1-409e-8ac0-f3634e5c3fb7 - WS: OnMessage({})
 (PrintConnector.Util.SignalrTraceWriter.Write) 
2017-04-20 09:31:24.5476 DEBUG [TID:15 TName:]  04:01:24.5476131 - 39267535-7ed1-409e-8ac0-f3634e5c3fb7 - WS: OnMessage({})
 (PrintConnector.Util.SignalrTraceWriter.Write) 
2017-04-20 09:31:34.5637 DEBUG [TID:3 TName:]  04:01:34.5637110 - 39267535-7ed1-409e-8ac0-f3634e5c3fb7 - WS: OnMessage({})
 (PrintConnector.Util.SignalrTraceWriter.Write) 
2017-04-20 09:31:44.6306 DEBUG [TID:15 TName:]  04:01:44.6306158 - 39267535-7ed1-409e-8ac0-f3634e5c3fb7 - WS: OnMessage({})
 (PrintConnector.Util.SignalrTraceWriter.Write) 
2017-04-20 09:31:54.6333 DEBUG [TID:3 TName:]  04:01:54.6333490 - 39267535-7ed1-409e-8ac0-f3634e5c3fb7 - WS: OnMessage({})
 (PrintConnector.Util.SignalrTraceWriter.Write) 
2017-04-20 09:32:04.6612 DEBUG [TID:17 TName:]  04:02:04.6612578 - 39267535-7ed1-409e-8ac0-f3634e5c3fb7 - WS: OnMessage({})
 (PrintConnector.Util.SignalrTraceWriter.Write) 
2017-04-20 09:32:14.7017 DEBUG [TID:14 TName:]  04:02:14.7017865 - 39267535-7ed1-409e-8ac0-f3634e5c3fb7 - WS: OnMessage({})
 (PrintConnector.Util.SignalrTraceWriter.Write) 
2017-04-20 09:32:24.7792 DEBUG [TID:20 TName:]  04:02:24.7792149 - 39267535-7ed1-409e-8ac0-f3634e5c3fb7 - WS: OnMessage({})
 (PrintConnector.Util.SignalrTraceWriter.Write) 
2017-04-20 09:32:34.7509 DEBUG [TID:14 TName:]  04:02:34.7509888 - 39267535-7ed1-409e-8ac0-f3634e5c3fb7 - WS: OnMessage({})
```
The issue is that after we start the IIS web site it fails to deliver messages to the clients although it manages to send the callback for the keepalive without any issue. I checked the log files both keepalive and other failing messages are sent to the same connection id. The only difference is that keepalive is sent from client to server and then back to the client and other methods are starting from the server. In order to confirm this we created a similar method to keepalive from the clients where it calls for the server and server returns a boolean true value. That method also works even after IIS web site stop/start. 

 
### Expected  behavior

As for my knowledge when we stop the site from IIS it should fire the disconnect event from the clients after keepalive messages failing. But even if not if the connection is not disconnected after starting the IIS web site it should be able to deliver messages from server to client. Not only from client to server and then back to clients. 

### Actual behavior
IIS web site stop does not fire disconnect in clients. After starting the site from IIS it fails to deliver messages from server to client. A manual restart of the connection makes all the communication success again. So seems like even though clients send the keepalive message server can't communicate in the instances where server first starts the communication. 
### Steps to reproduce

1. Host the server in IIS.
2. Stop the site from IIS manager.
3. Check the trace files to identify whether disconnected is fired.
4. After like one minute start the site from IIS manager.
5. Try to send a message from the server. Make sure to compare the keepalive connectionid and current connectionid to confirm. 

IIS - 8.5
Microsoft.AspNet.SignaR - 2.2.1
Microsoft.AspNet.SignaR.Cleint - 2.2.1

P.S.

Strangely we found that by enabling backplane ( we used a sql  backplane previously which we disabled since we were using only one server) the messages from the server were also able to deliver messages successfully. We checked in the logs to see whether while the IIS site is stopped the clients get connected to another server, but we found that it does not do something like that and there are no other server connected to the same backplane.

**Comment by janitha000** [comment]
Ok I found from this [issue ](https://github.com/SignalR/SignalR/issues/1148) that when stopping only the site the diconnect does not fire. In order to do that we need to do a iisreset or recycle to app pool. But why does it fails to deliver messages even after we start the site?

**Comment by moozzyk** [comment]
What do you see in the logs when you restart the server? What do you see in the logs when you just stop the server? Do you see rconnects?

**Comment by janitha000** [comment]
No, there are no recconects from the clients.

**Comment by moozzyk** [comment]
Are you sure you are connected to the server that is being shutdown? What happens if you shutdown the server and try sending messages from the client that appears/thinks to be connected?

**Comment by janitha000** [comment]
yes that is the issue, when client appears/thinks to be connected it successfully sends the messages to the server and server also replies back. I checked on the stacktrace and I can see that the keepalive sent by client is a success and isconnectionalive(implemented by us) also is a success. Only when server starts to send a message it gets failed.

**Comment by Xyclade** [comment]
I'm having the same issue. I also found that restarting the client does not help. It is the IIS app pool that has to be recycled for it to work.  As if there is some orphaned process that still accepts  the signalR connections, even after a website stop has been called.

**Comment by Xyclade** [comment]
To Add some information:
The protocol that the connection is operating on in my case is WebSockets V1.4
SignalR Core version 2.2.2
Dot.net 4.6.2

The client behaves like it is connected, however when a message is sent from client to server, the server never receives it (we are logging those) and the client gets a timeout on sending the message. A workaround in which we completely stop en recreate the client hub to connect does not work. Even restarting the client fails to resolve the issue. The only way to get it to work again is to do a full app pool recycle of the IIS website.

**Comment by scottieslg** [comment]
Is there any update to this?  It's very disruptive to my users when I have to cycle the app pool and it takes the site down for 10-30 seconds while it cycles.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Comment by VeliborP** [comment]
Any solution on this? I am having troubles with this same thing.
Client .netcore 2.2.2 console app as win service
Server .net 4.6
?
