### ISSUE TITLE
Some connections never close

### ISSUE THREAD

**Issue by zyxel** [SignalR/SignalR#3917]
Some of connections remains open forever. In the end of the day I have 5 000-10 000 stuck connections (which are 2-10 hours old) with online 200 people.

And when I try to send some data to all clients through SignalR - application hangs with 100% CPU load.

I tried to comment everything to find cause of the problem. Now this is only SignalR related code that remains:

```
[HubName("notificationHub")]
public class NotificationHub : Hub
{
	public NotificationHub()
	{
	}
}
```

```
[assembly: OwinStartup(typeof(Startup))]
namespace MyProject
{
	public class Startup
	{
		public void Configuration(IAppBuilder app)
		{
			app.MapSignalR();
		}
	}
}
```

But connections are still stuck.
SignalR 2.2.1
Windows Server 2008 R2
IIS 7.5.7600.16385

I have no idea how to reproduce it.

Connections list after only 2 hours of uptime:

![Connections](http://i.imgur.com/HcHCHmw.png)

**Comment by zyxel** [comment]
Also here is profiler results from one of 100% CPU loads.

![Profiler](http://i.imgur.com/mCXMbs3.png)

**Comment by moozzyk** [comment]
Unfortunately this report is not actionable. I don't remember seeing issues similar to this so without a repro it is basically impossible to tell what's going on.

**Comment by zyxel** [comment]
Thanks for your reply. I will try to move SignalR related functionality to new empty project and see how it works.

I will get back to you if I find way to reproduce issue.
