### ISSUE TITLE
Fail to Start HubConnection in Xamarin.Android using SignalR 2.2.2 client

### ISSUE THREAD

**Issue by dagrooms52** [SignalR/SignalR#3921]
### Expected  behavior
SignalR Client succeeds in connecting to SignalR server. This succeeds in .NET Standard 1.4 projects and NetFramework 4.6.1 projects.

### Actual behavior
Attempting to connect results in different failures. I have observed silent failures, as well as the following exception:

```
04-27 17:13:06.606 I/MonoDroid(15704): UNHANDLED EXCEPTION:

04-27 17:13:06.631 I/MonoDroid(15704): System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: SecureChannelFailure (The authentication or decryption has failed.) ---> System.IO.IOException: The authentication or decryption has failed. ---> System.IO.IOException: Error while sending TLS Alert (Fatal:InternalError): System.IO.IOException: The authentication or decryption has failed. ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer

04-27 17:13:06.631 I/MonoDroid(15704):   at System.Net.Sockets.Socket.EndReceive (System.IAsyncResult result) [0x0002d] in /Users/builder/data/lanes/4468/f913a78a/source/mono/mcs/class/System/System.Net.Sockets/Socket.cs:2000 

04-27 17:13:06.631 I/MonoDroid(15704):   at System.Net.Sockets.NetworkStream.EndRead (System.IAsyncResult asyncResult) [0x0005f] in /Users/builder/data/lanes/4468/f913a78a/source/mono/mcs/class/referencesource/System/net/System/Net/Sockets/NetworkStream.cs:858 

04-27 17:13:06.631 I/MonoDroid(15704):    --- End of inner exception stack trace ---

04-27 17:13:06.631 I/MonoDroid(15704):   at Mono.Security.Protocol.Tls.RecordProtocol.EndReceiveRecord (System.IAsyncResult asyncResult) [0x0003a] in /Users/builder/data/lanes/4468/f913a78a/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/RecordProtocol.cs:430 

04-27 17:13:06.631 I/MonoDroid(15704):   at Mono.Security.Protocol.Tls.SslClientStream.SafeEndReceiveRecord (System.IAsyncResult ar, System.Boolean ignoreEmpty) [0x00000] in /Users/builder/data/lanes/4468/f913a78a/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslClientStream.cs:256 

04-27 17:13:06.631 I/MonoDroid(15704):   at Mono.Security.Protocol.Tls.SslClientStream.NegotiateAsyncWorker (System.IAsyncResult result) [0x00071] in /Users/builder/data/lanes/4468/f913a78a/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslClientStream.cs:418 

04-27 17:13:06.631 I/MonoDroid(15704):    --- End of inner exception stack trace ---

04-27 17:13:06.631 I/MonoDroid(15704):   at Mono.Security.Protocol.Tls.SslClientStream.EndNegotiateHandshake (System.IAsyncResult result) [0x00035] in /Users/builder/data/lanes/4468/f913a78a/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslClientStream.cs:396 

04-27 17:13:06.631 I/MonoDroid(15704):   at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (System.IAsyncResult asyncResult) [0x0000c] in /Users/builder/data/lanes/4468/f913a78a/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslStreamBase.cs:101  ---> System.IO.IOException: Unable to write data to the transport connection: The socket is not connected. ---> System.Net.Sockets.SocketException: The socket is not connected

04-27 17:13:06.631 I/MonoDroid(15704):   at System.Net.Sockets.Socket.BeginSend (System.Byte[] buffer, System.Int32 offset, System.Int32 size, System.Net.Sockets.SocketFlags socket_flags, System.AsyncCallback callback, System.Object state) [0x00021] in /Users/builder/data/lanes/4468/f913a78a/source/mono/mcs/class/System/System.Net.Sockets/Socket.cs:2551 
```

### Steps to reproduce
Install SignalR client package 2.2.2-preview1 in Xamarin.Android project
Attempt to connect to a SignalR server using `HubConnection.Start()`
Note that the server is running SignalR version 2.2.1

**Comment by moozzyk** [comment]
This looks like an issue in Mono or an issue with the certificate. The connection fails due to: `Error while sending TLS Alert (Fatal:InternalError): System.IO.IOException: The authentication or decryption has failed`. Can you try sending a negotiate request directly (i.e. without SignalR) using HttpClient? You would send a GET request to `https://{your-server}/signalr/negotiate`. I expect it will fail with the same error showing it is an external issue.

**Comment by dagrooms52** [comment]
`/signalr/negotiate` returns a 200, with the following content:

```
{
   "Url":"/signalr",
   "ConnectionToken":"", // Intentionally shortened
   "ConnectionId":"9403fe94-7798-4ac3-9889-f11b6adeea5e",
   "KeepAliveTimeout":20.0,
   "DisconnectTimeout":30.0,
   "ConnectionTimeout":110.0,
   "TryWebSockets":true,
   "ProtocolVersion":"1.2",
   "TransportConnectTimeout":5.0,
   "LongPollDelay":0.0
}
```

**Comment by moozzyk** [comment]
Did you send the request with HttpClient on Xamarin?

**Comment by dagrooms52** [comment]
Yes, absolutely

**Comment by moozzyk** [comment]
Can you put up a repro (ideally as a github repo)? I assume the problem happens only when you use https and not http. Are you using a self signed certificate? Also, what do you use to host your server (IIS, IISExpress, selfhost)?

**Comment by dagrooms52** [comment]
We are actually using the `modernhttpclient 2.4.2` package for our HttpClient. 
Will work on a repro; I had something throwing out of the connection's Start method but unable to catch that exception or see output, figured it had to do with Xam.Android being the way it is.
The cert is not self signed. The SignalR server is running on Owin.

**Comment by dagrooms52** [comment]
The repro solution was not able to hit the `/signalr/negotiate` endpoint; it failed with the same message as the client's Connection.Start() method as you expected. Do you still want me to post the repro code?

**Comment by moozzyk** [comment]
Yes. I think the problem is that negotiate was not hit because of the TLS handshake error. However you were able to request negotiate just fine without SignalR client so there is an issue somewhere.

**Comment by dagrooms52** [comment]
Here is a gist of MainActivity.cs; this can replace the MainActivity.cs of a new Xamarin.Android project to repro. Uses `SignalRClient 2.2.2-preview1`. Same result was observed with or without `modernhttpclient 2.4.2` installed.
https://gist.github.com/dagrooms52/a7ce14f9d03da157f2328586e8a566c6

**Comment by moozzyk** [comment]
I used your code to connect over https to an application on Azure and I don't see this exception.

**Comment by moozzyk** [comment]
I found a few reports of this issue on Mono bugzilla: https://bugzilla.xamarin.com/show_bug.cgi?id=39850 or https://bugzilla.xamarin.com/show_bug.cgi?id=29347 but they did not get any traction and there are no solutions/workarounds provided. There is also [this thread](https://emby.media/community/index.php?/topic/21017-ssl-errrors-with-startssl-cert/) which can shed some light on the issue. 

There are two things you can try:
- try using a specific transport instead of auto transport (e.g. longPolling)
- try connecting to this app in azure https://testsignalrchat.azurewebsites.net (use `_hubName = "chatHub"`) - this is the application used for testing

**Comment by dagrooms52** [comment]
I can connect to the app you linked; this means there is likely a server issue I can resolve, correct?

**Comment by moozzyk** [comment]
...or the certificate. In one of the linked threads someone said _that if there is an embedded key it fails_. Honestly I don't know a lot about certificates so I am not sure what it means. 
One thing that is still a mystery is why you were able to connect just fine when you used bare HttpClient.

**Comment by dagrooms52** [comment]
It is interesting that the only successful action was to the `/signalr/negotiate` endpoint, but only out of our running app; with the test app, I was unable to successfully hit this endpoint, so the issue may be fragile under the hood. Regardless, I'm working on getting the server devs to resolve any certificate issues (they renewed the cert last week and knocked the environment out for a day, so there have been issues). I may also try a bug report with the Mono guys if I can dig up more information on the cert issue. Thank you for your help.

**Comment by dagrooms52** [comment]
We finally got to the bottom of the issue here; there is a bug in VS 2017 with setting the Android HttpClient through the properties tab, in which the csproj is not updated to reflect the setting. This bug seems to be combined with the recent adoption of the usage of this variable. Although the setting was not set previously, since moving to vs 2017 and using signalR 2.2.2 the setting started being used and was empty, causing TLS to be turned off in our app. Setting the tag `<AndroidTlsProvider>btls</AndroidTlsProvider>` got it working again.

**Comment by moozzyk** [comment]
Thanks for the update! I am glad you were able to figure this out.

**Comment by dagrooms52** [comment]
And thanks for your help
