### ISSUE TITLE
IHubProxy.Invoke() hangs forever when called during disconnect/reconnect

### ISSUE THREAD

**Issue by kskog** [SignalR/SignalR#3925]
### Expected  behavior
When calling a method on the Hub by calling IHubProxy.Invoke() the Task should stop and throw an exception if the signalr connection is being disconnected during the call.

### Actual behavior
The Invoke() method hangs indefinitely. It seems like the Task running the method gets into a deadlock state when the signalr connection is disconnected during the call. This happens from time to time in our product and causes the application to fail.

### Steps to reproduce
1. Make a simple Hub on the server with one method:

public void NewLogEntry(string msg)
{
    Clients.Others.newLogEntry(msg);
}

2. Make a simple console client that calls the method on the hub repeatedly in a loop.

while (true)
{  
  hubProxy.Invoke("NewLogEntry", "Test message").Wait();
  Console.WriteLine("Message sent");
}

3. While the client is running stop the server/iis. The console application hangs.

We are using version 2.2.1. 
We are using WebSocket.

**Comment by moozzyk** [comment]
Can you turn on logging on the client and show the logs? Wait a couple minutes after you think the client is hung - I need to see if the client logs anything.

**Comment by kskog** [comment]
At the time of the the exception  (sequence number 1270) IIS was restarted. The restart takes a very short time so the reconnect afterwards succeeds. After the the reconnect the Invoke call hangs and it seems like only pings are being sent.

[signalrClient.txt](https://github.com/SignalR/SignalR/files/978267/signalrClient.txt)

**Comment by kskog** [comment]
This is a serious issue for us since it causes our service to hang completely. Do you have any idea when this will be looked into?

**Comment by AgentFire** [comment]
The hangs are still there. Whenever the server is down and I call "disconnect" on the client, everything hangs for at least half a minute. Sometimes it doesn't unfreeze at all.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
