### ISSUE TITLE
proxy.off('eventName', handler) removes all "similar" event handlers

### ISSUE THREAD

**Issue by taras-d** [SignalR/SignalR#3926]
### Actual behavior
```javascript
var handler1 = function (res) { console.log(res); }
var handler2 = function (res) { console.log(res); }
// ...
proxy.off('eventName', handler1) // removes handler1 and handler2
```

### Expected  behavior
`proxy.off('eventName', handler1)` - should remove only *handler1*

### Steps to reproduce
```javascript

// Create connection
var connection = $.hubConnection('http://localhost:49738/signalr');

// Create hub proxy
var echoHub = connection.createHubProxy('echoHub');

var handler1 = function (res) { console.log(res); }
var handler2 = function (res) { console.log(res); }

// Register handlers
echoHub.on('newMessage', handler1);
echoHub.on('newMessage', handler2);

// !!! After unregistering 1st handler - 2nd handler unregistered too
echoHub.off('newMessage', handler1);

// Start connection
connection.start().done(function () {
    // Invoke server method, which executes "newMessage" for all clients
    echoHub.invoke('ping');
});
```

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
