### ISSUE TITLE
StateChange event is never raised on wifi lost with UWP client using ServerSentEvent

### ISSUE THREAD

**Issue by Barbu1234** [SignalR/SignalR#3927]
Hi, 

We're developing a UWP version of our app which run on different mobile devices and thus often have connectivity issue, wifi lost, etc. Currently in Signal 2.2.1 and 2.2.2 with ServerSentEvents, when we lose the wifi, the StateChanged event never happens SignalR just stays in the Connected state. Looking at the traces we see the ConnectionSlow event is raised and then "Connection Timed-out : Transport Lost Connection" happens but no actual Reconnecting or Disconnected event occurs. So far this only happens in a UWP client, the Xamarin Android version works fine and a basic console app running on Win10 works fine too.

I would have expected at least a Reconnecting attempt to happen.

Also if this is of any importance, the server is self-hosted on a Windows Server 2008 OS. We tried on a Windows Server 2012 with websocket and we have the same problem in 2.2.1 but not in 2.2.2, (i.e. We do see a Reconnecting event in 2.2.2 using WebSocket only). However, running on Windows Server 2012 might not always be a possibility in production.

Is this a bug or is there some sort of configuration/authorization to activate for this to work on a UWP client?

Thanks

**Comment by moozzyk** [comment]
Please show traces and maybe some repro code (especially if you do anything in StateChanged, Closed etc. event handlers).

**Comment by jakeb16** [comment]
Seems very similar to what I was seeing https://github.com/SignalR/SignalR/issues/3919

**Comment by Barbu1234** [comment]
I can repro with this basic connection code without doing anything in Statechanged, Closed, Etc.:

`public async Task StartTestConnection()`
`{`
  `var connection = new HubConnection("http://XX.XX.XX.XX:YYYY")`
  `{`
    `TraceLevel = TraceLevels.All,`
    `TraceWriter = new LoggerStringWriter(_logger)`
  `};`
  `await connection.Start(new ServerSentEventsTransport());`
  `await Task.Delay(TimeSpan.FromHours(1));`
  `connection.Stop();`
`}`

If this is code is ran from within an UWP app we get the problem if it's ran on a console app on Win10 we don't get the problem. 

Here's the trace on UWP

> 17:32:26.2658834 - null - ChangeState(Disconnected, Connecting)
17:32:31.6909009 - 45f58dac-da89-4990-bad2-bc70bb3c559a - SSE: GET http://XX.XX.XX.XX.YYYY/signalr/connect?clientProtocol=1.4&transport=serverSentEvents&connectionData=[]&connectionToken=45f58dac-da89-4990-bad2-bc70bb3c559a%3A
17:32:33.9668647 - 45f58dac-da89-4990-bad2-bc70bb3c559a - SSE: OnMessage(Data: initialized)
17:32:35.4188834 - 45f58dac-da89-4990-bad2-bc70bb3c559a - SSE: OnMessage(Data: {"C":"d-C6C4A7F9-Bu,1","S":1,"M":[]})
17:32:35.4586844 - 45f58dac-da89-4990-bad2-bc70bb3c559a - ChangeState(Connecting, Connected)
17:32:35.9511442 - 45f58dac-da89-4990-bad2-bc70bb3c559a - SSE: OnMessage(Data: {})
17:32:40.9513118 - 45f58dac-da89-4990-bad2-bc70bb3c559a - SSE: OnMessage(Data: {})
17:32:47.6893815 - 45f58dac-da89-4990-bad2-bc70bb3c559a - Connection Timeout Warning : Notifying user
17:32:47.6973819 - 45f58dac-da89-4990-bad2-bc70bb3c559a - OnConnectionSlow
17:32:52.9953914 - 45f58dac-da89-4990-bad2-bc70bb3c559a - Connection Timed-out : Transport Lost Connection
> 

After the last OnMessage I closed the wifi and waited about a minute and nothing happened. I was expecting a ChangeState (Connected, Reconnecting)

**Comment by Barbu1234** [comment]
Any feedback on this? Should we try to implement our own ping module for UWP to palliate to this issue?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
