### ISSUE TITLE
Pause in my breakpoint debug mode, not call OnDisconnected.

### ISSUE THREAD

**Issue by alexandresmoraes** [SignalR/SignalR#3928]
I have used SignalR in my projects, but still none in production, I realized by debugging, while taking to debug my breakpoints, I realized that some clients drop the connection and do not call OnDisconnected, so my ConcurrentDictionary where I keep my clients does not remove certain connections, this can Be by the debug mode and the stop I make in the breakpoints?

**Comment by moozzyk** [comment]
I guess you might be hitting some timeouts but it is hard to be more specific than that. If you are able to repro this please provide repro app, repro steps and logs.
