### ISSUE TITLE
UWP Problem with Dispatcher in Multi Window scenario.

### ISSUE THREAD

**Issue by RikardoPons** [SignalR/SignalR#3932]
### Expected  behavior
After to connect to SignalR update all the properties in the UI Thread in a Secondary Window.
### Actual behavior
I get this error when I try to update some property  that implements INotifyPropertyChanged
InvalidCastException: Unable to cast COM object of type 'System.ComponentModel.PropertyChangedEventHandler' to class type 'System.ComponentModel.PropertyChangedEventHandler'. Instances of types that represent COM components cannot be cast to types that do not represent COM components; however they can be cast to interfaces as long as the underlying COM component supports QueryInterface calls for the IID of the interface.

Interesting things about this. 

Before to call signalR to connect I can get Windows.Current after that 
I get ----> Windows.Current=null this is the reason why I can not update the UI from the VM

### Steps to reproduce
In a secondary window just connect to SignalR

  hubConnection = new HubConnection(url);
            hubProxy = hubConnection.CreateHubProxy("CompanyHub");
            await hubConnection.Start();

after that try to update some property from the ViewModel

This is a big issue for my project I can not work anymore for now I need to fix this problem asap, any ideas?

Thank you so much!

**Comment by moozzyk** [comment]
Have you tried dispatching to the UI thread?

**Comment by RikardoPons** [comment]
Yes Windows.Current.Dispatcher is always null

**Comment by moozzyk** [comment]
Please create a repo containing a simple repro.

**Comment by bakamaru** [comment]
any solution found for this problem?

**Comment by RikardoPons** [comment]
Yes I found a solution. Tomorrow morning I'll share the solution I found.

**Comment by bakamaru** [comment]
@RikardoPons  thanks for the quick response. 
I just did something like this,
 private CoreDispatcher projectionDispatcher;   //variable to hold instance of dispatcher 
and set value inside constructor 
 projectionDispatcher= Window.Current.Dispatcher;
later when signalr invokes method 
 projectionDispatcher.RunAsync(CoreDispatcherPriority.Normal,
                    async () => {   DOWORK HERE ..  }
                );
and finally after 2 hours it working as expected.

**Comment by anurse** [comment]
Given that it appears you've got a solution, I'm going to close this issue. Feel free to comment further if you have questions. We can re-open the issue if there's a fix to be considered.

**Comment by RikardoPons** [comment]
Here is my Solution I wrote an Extension to  work with SignalR and UWP without problems

`
  public static class ActionExtensions
    {

        public async static Task SendDataToUIAsync(this Action action, SynchronizationContext context)
        {
            var tcs = new TaskCompletionSource<object>();
            if (context == null)
            {
                tcs.SetResult(null);
                await tcs.Task;
            }
            context.Post(a =>
            {
                try
                {
                    action();
                    tcs.SetResult(null);
                }
                catch (Exception ex)
                {
                    tcs.SetException(ex);

                }


            }, null);
            await tcs.Task;
        }
    }
`

Example How to use it:

`
 var action = new Action(() => 
            {
                             Status = order.Status;
              
            }).SendDataToUIAsync(Context);
         
`
