### ISSUE TITLE
hook "invoke" after and befor

### ISSUE THREAD

**Issue by mohamadpk** [SignalR/SignalR#3935]
in client of signalr  . i need to log every "invoke" or every "on". how do i write this code ?
  how do i write hook for after and before call to "invoke" or "on" or other method in hub proxy client for logging?

**Comment by gragra33** [comment]
[https://docs.microsoft.com/en-us/aspnet/signalr/overview/testing-and-debugging/enabling-signalr-tracing](url)

**Comment by mohamadpk** [comment]
ok tanx  gragra33  but i need custom log all call to db no in console window.in signalr server i user "app.use" for log. in signalr client i dont know.anyway tanx again . for resolving problem i use your link and TraceWriter .
