### ISSUE TITLE
Open Solution in visual studio 2017 will appear convertion error report

### ISSUE THREAD

**Issue by akira32chen** [SignalR/SignalR#3938]
I open the solution file with visual studio 2017. and then automatically convert the projects.
But the projects convert fall with some problem:

Microsoft.AspNet.SignalR.Client.WP8.Samples
Microsoft.AspNet.SignalR.Client.Silverlight.Samples
Microsoft.AspNet.SignalR.Client.WindowsStoreCSharp.Samples
Microsoft.AspNet.SignalR.Client.WinRT

The detail converting problem as below:

Microsoft.AspNet.SignalR.Client.Silverlight.Samples
Message
samples\Microsoft.AspNet.SignalR.Client.Silverlight.Samples\Microsoft.AspNet.SignalR.Client.Silverlight.Samples.csproj: The application which this project type is based on was not found. Please try this link for further information: http://go.microsoft.com/fwlink/?LinkID=299083&projecttype=A1591282-1198-4647-A2B1-27E5FF5F6F3B
Microsoft.AspNet.SignalR.Client.WindowsStoreCSharp.Samples
Message
samples\Microsoft.AspNet.SignalR.Client.WindowsStoreCSharp.Samples\Microsoft.AspNet.SignalR.Client.WindowsStoreCSharp.Samples.csproj: The application which this project type is based on was not found. Please try this link for further information: http://go.microsoft.com/fwlink/?LinkID=299083&projecttype=BC8A1FFA-BEE3-4634-8014-F334798102B3
Microsoft.AspNet.SignalR.Client.WinRT
Message
src\Microsoft.AspNet.SignalR.Client.WinRT\Microsoft.AspNet.SignalR.Client.WinRT.csproj: The application which this project type is based on was not found. Please try this link for further information: http://go.microsoft.com/fwlink/?LinkID=299083&projecttype=BC8A1FFA-BEE3-4634-8014-F334798102B3
Microsoft.AspNet.SignalR.Client.WP8.Samples
Message
samples\Microsoft.AspNet.SignalR.Client.WP8.Samples\Microsoft.AspNet.SignalR.Client.WP8.Samples.csproj: The application which this project type is based on was not found. Please try this link for further information: http://go.microsoft.com/fwlink/?LinkID=299083&projecttype=C089C8C0-30E0-4E22-80C0-CE093F111A43

Does somebody know how to resolve this problem?

**Comment by moozzyk** [comment]
This projects are the main reason why the repo was not converted to VS2017. We need to take a look if they are needed at all and possibly remove some of them and update the rest accordingly. The workaround at the moment is to keep using VS2015.

**Comment by akira32chen** [comment]
Thanks！I use Visual Studio 2015 open the solution. But seem to have a problem about Nuget. My computer installed Kaspersky. I cannot confirm whether is a factor about Nuget problem. But I another computer also windows 10 does not have this problem. The computer is installed Norton on it.

**Comment by moozzyk** [comment]
You need to provide more details about _seem to have a problem about Nuget_

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
