### ISSUE TITLE
ConnectingMessageBuffer for message buffering

### ISSUE THREAD

**Issue by zsybupt** [SignalR/SignalR#3939]
I am sorry, it is not an issue of using SignalR.
I find that other clients' code do not have a ConnectingMessageBuffer for message buffering when connecting, but the JS client has this mechanism. Can some guys help me to figure it out, because I am now working on implementation of SignalR client, Thanks!

**Comment by moozzyk** [comment]
C# client has a task queue that is [blocked until ](https://github.com/SignalR/SignalR/blob/dev/src/Microsoft.AspNet.SignalR.Client/Connection.cs#L461) until the transport is started. So, even if the client received some messages before receiving the response to the init (i.e. start) request they won't be processed until the response to the init messages is received and the [queue is unblocked](https://github.com/SignalR/SignalR/blob/dev/src/Microsoft.AspNet.SignalR.Client/Connection.cs#L523-L525).

**Comment by zsybupt** [comment]
Thanks for answering, but HubConnection override the OnMessageReceived method, and the callbacks or invokeEvent is called immediately, only the base.onMessageReceived will blocked until it is connected, right? So I wonder why it is designed like this. Thanks!

**Comment by moozzyk** [comment]
`OnMessgeReceived` is queued in [`OnReceived`](https://github.com/SignalR/SignalR/blob/dev/src/Microsoft.AspNet.SignalR.Client/Connection.cs#L784-L797) until the queue is blocked no queued task will be run hence OnMessageReceived won't be invoked.

**Comment by zsybupt** [comment]
@moozzyk  I got it, really thanks for answering!
