### ISSUE TITLE
the client received multiple init messages.

### ISSUE THREAD

**Issue by fqybzhangji** [SignalR/SignalR#3940]
# I use the SignalR + Redis cluster

# When I use "SignalR", it is normal to load the page for the first time. When I refresh the page is not normal, the browser output window prompts "SignalR: WARNING! The client received multiple init messages."

# **Normal output information：**

> [11:47:25 GMT+0800 (中国标准时间)] SignalR: Client subscribed to hub 'chathub'.
> jquery.signalR-2.2.2.js:82 [11:47:25 GMT+0800 (中国标准时间)] SignalR: Negotiating with '/signalr/negotiate?clientProtocol=1.5&connectionData=%5B%7B%22name%22%3A%22chathub%22%7D%5D'.
> jquery.signalR-2.2.2.js:82 [11:47:26 GMT+0800 (中国标准时间)] SignalR: webSockets transport starting.
> jquery.signalR-2.2.2.js:82 [11:47:26 GMT+0800 (中国标准时间)] SignalR: Connecting to websocket endpoint 'ws://localhost:57974/signalr/connect?transport=webSockets&clientProtocol=1.5&connectionToken=RksoDm6KTlA8KoMEsLXS29xx%2F1dwlKl5u76mrcoSJifYPDCddSQfuO57BrOgVa81myZpYrCzoHdJSZ5PUOznEBXL2r4Gxem3poWlGBm0hPj1VQLIT9I7BZLfSW3EqccG&connectionData=%5B%7B%22name%22%3A%22chathub%22%7D%5D&tid=3'.
> jquery.signalR-2.2.2.js:82 [11:47:26 GMT+0800 (中国标准时间)] SignalR: Websocket opened.
> jquery.signalR-2.2.2.js:82 [11:47:26 GMT+0800 (中国标准时间)] SignalR: webSockets transport connected. Initiating start request.
> jquery.signalR-2.2.2.js:82 [11:47:26 GMT+0800 (中国标准时间)] SignalR: The start request succeeded. Transitioning to the connected state.
> jquery.signalR-2.2.2.js:82 [11:47:26 GMT+0800 (中国标准时间)] SignalR: Now monitoring keep alive with a warning timeout of 13333.333333333332, keep alive timeout of 20000 and disconnecting timeout of 30000

# **Abnormal output information：**

> [11:45:47 GMT+0800 (中国标准时间)] SignalR: Client subscribed to hub 'chathub'.
> jquery.signalR-2.2.2.js:82 [11:45:47 GMT+0800 (中国标准时间)] SignalR: Negotiating with '/signalr/negotiate?clientProtocol=1.5&connectionData=%5B%7B%22name%22%3A%22chathub%22%7D%5D'.
> jquery.signalR-2.2.2.js:82 [11:45:47 GMT+0800 (中国标准时间)] SignalR: webSockets transport starting.
> jquery.signalR-2.2.2.js:82 [11:45:47 GMT+0800 (中国标准时间)] SignalR: Connecting to websocket endpoint 'ws://localhost:57974/signalr/connect?transport=webSockets&clientProtocol=1.5&connectionToken=lckDbENHthTHhMeKXio8fn%2BvyNkn9No3kR%2FeiEoWT0olXsaXroBpqmbrFv8vYH01DARyE6AWDMARe6tnAAiVYL4xdNNrRWFV71z6BE5HI4nhb2W2cSCsHWyP%2Fl%2FB5HDu&connectionData=%5B%7B%22name%22%3A%22chathub%22%7D%5D&tid=7'.
> jquery.signalR-2.2.2.js:82 [11:45:47 GMT+0800 (中国标准时间)] SignalR: Websocket opened.
> jquery.signalR-2.2.2.js:82 [11:45:47 GMT+0800 (中国标准时间)] SignalR: webSockets transport connected. Initiating start request.
> 13jquery.signalR-2.2.2.js:82 [11:45:47 GMT+0800 (中国标准时间)] SignalR: WARNING! The client received multiple init messages.
> jquery.signalR-2.2.2.js:82 [11:45:47 GMT+0800 (中国标准时间)] SignalR: The start request succeeded. Transitioning to the connected state.
> jquery.signalR-2.2.2.js:82 [11:45:47 GMT+0800 (中国标准时间)] SignalR: Now monitoring keep alive with a warning timeout of 13333.333333333332, keep alive timeout of 20000 and disconnecting timeout of 30000
> 1045jquery.signalR-2.2.2.js:82 [11:45:47 GMT+0800 (中国标准时间)] SignalR: WARNING! The client received multiple init messages.
> .
> .
> .
> .
> .
> .

## **The difference between the two messages is " SignalR: WARNING! The client received multiple init messages".**

**Hope to have a master to help solve.Thanks.**

@moozzyk @anurse @paulbatum @runesoerensen @thecodejunkie @

**Comment by fqybzhangji** [comment]
[SignalR scaleout with Redis does not support Redis clusters.](https://docs.microsoft.com/en-us/aspnet/signalr/overview/performance/scaleout-with-redis)

**Comment by moozzyk** [comment]
Closing as per your finding - SignalR Redis scaleout does not support Redis clusters.
