### ISSUE TITLE
Signal R Performance Counter

### ISSUE THREAD

**Issue by matheuscanela** [SignalR/SignalR#3942]
Hi all,

I am trying to use the SignalR Performance monitor with the Windows Server 2016 but I am not getting the counters properly, so it just gets some counters when I use the method context.Clients.Clients(connectionsId), all other calls & connections are not counting into the monitor.

Counters that barely work
- Msg Buss Messages Published Total
- Msg Bus Subscribers Current
- Msg Bus Subscribers Total
- Msg Bus Topics Current

I am using these packages below

  <package id="Microsoft.AspNet.SignalR" version="2.2.2" targetFramework="net462" />
  <package id="Microsoft.AspNet.SignalR.Core" version="2.2.2" targetFramework="net462" />
  <package id="Microsoft.AspNet.SignalR.JS" version="2.2.2" targetFramework="net462" />
  <package id="Microsoft.AspNet.SignalR.SystemWeb" version="2.2.2" targetFramework="net462" />
  <package id="Microsoft.AspNet.SignalR.Utils" version="2.2.2" targetFramework="net462" />

Also, I've tried to add the user administrator to run the pool and added everyone to all monitoring groups; however, it didn't go through.

My startup is like this

            app.Map("/signalr", map =>
            {
                // Gets the token from the Signal R connection to authorize the call
                map.UseWindowsAzureActiveDirectoryBearerAuthentication(new 
                 WindowsAzureActiveDirectoryBearerAuthenticationOptions
                {
                    Provider    = new QueryStringOAuthBearerProvider(),
                    #pragma warning disable 618
                    Audience    = ConfigurationManager.AppSettings["ida:Audience"],
                    Tenant      = ConfigurationManager.AppSettings["ida:Tenant"],
                });

                // Setup the CORS middleware to run before SignalR.
                //map.UseCors(CorsOptions.Value);
                map.UseCors(HttpContext.Current.IsDebuggingEnabled ? Microsoft.Owin.Cors.CorsOptions.AllowAll : CorsOptions.Value);

                // Setup a pipeline for exceptions
                // https://stackoverflow.com/questions/36135484/how-to-handle-signalr-server-exception-at-client
                //GlobalHost.HubPipeline.AddModule(new SoHubPipelineHelper());

                // Change the serialization process for the signal r
                // https://stackoverflow.com/a/20290472/3141018
                var jsonSerializer = JsonSerializer.Create(new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore });
                GlobalHost.DependencyResolver.Register(typeof(JsonSerializer), () => jsonSerializer); 

                // Use the Hub Configuration var if the JsonP needs to be enabled
                var hubConfiguration = new HubConfiguration {EnableDetailedErrors = HttpContext.Current.IsDebuggingEnabled};

                // Run the SignalR pipeline. We're not using MapSignalR
                // since this branch already runs under the "/signalr"
                // path.
                map.RunSignalR(hubConfiguration);
            });

Could you guys help me please?

**Comment by matheuscanela** [comment]
I have some updates!

So, the front end developer is using the signalr-bower and it is not counting; however, when I use my local script for testing (simple html) it works perfectly. See both codes below. Is he doing anything wrong?

SIMPLE SCRIPT

		'<!doctype html>
		<html lang="en">
  		<head>
    		<meta charset="utf-8">
    		<meta name="viewport" content="width=device-width, initial-scale=1">
    		<title>React App</title>
    		<script
   		 src="https://code.jquery.com/jquery-2.2.4.min.js"
   		 integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
  		  crossorigin="anonymous"></script>
    		<script src="https://ajax.aspnetcdn.com/ajax/signalr/jquery.signalr-2.2.2.min.js"></script>
    		<script src="https://xxxxx.com.au/signalr/hubs"></script>
    		<script>
		var chat 					= $.connection.preStartHub;
		//$.connection.hub.url 		= "https://localhost:44381/signalr";
		$.connection.hub.url 		= "https://xxxxx.com.au/signalr";
		
		$.connection.hub.qs = { 
		'access_token': "XXXXXX",
		'actionById': 'XXXXX' // User Rafael Grilli
		};
		
		$.connection.preStartHub.client.supervisorRefreshScreen = function (preStart) {
			console.log(preStart);
		}
		
		$.connection.preStartHub.client.exceptionHandler = function (error) {
			console.log(error);
		}; 
		
		$.connection.preStartHub.client.driverReceiveAnswer = function(supervisorName,supervisorNumbers,isApproved,preStartId, preStartComments){
			console.log(supervisorName,supervisorNumbers,isApproved,preStartId, preStartComments);
		};
		
		$.connection.preStartHub.client.supervisorUpdateScreenBoxLockerStatus = function (preStartId, status) {
			console.log(preStartId + " " + status);
		}

		$.connection.hub.start().done(function () {
		console.log('connected')
		
		$.connection.preStartHub.server.supervisorLoadPreStartList().done(function(result) { 
			if (result) {
				console.log('Server', result);
			}
		});
		});

		$.connection.preStartHub.client.connected = function(){
		}
		

		
    </script>
  </head>
  <body>
  
  </body>
</html>`

BOWER
        `this.connection = $.hubConnection('https://xxxxx.com.au');
        this.preStartHub = this.connection.createHubProxy('preStartHub');
        this.preStartHub.on('supervisorRefreshScreen', this.supervisorRefreshScreen);
        this.preStartHub.on('supervisorUpdateScreenBoxLockerStatus',                                                 
        this.supervisorUpdateScreenBoxLockerStatus);
		
		
        connectToServer = () => {
        this.setState({ isConnecting: true, error: null });
        this.connection.qs = { 
            access_token: 'XXXXX', 
            actionById: 'XXXXX'
        };

        this.connection.start()
        .done(() => { 
            console.log('Now connected, connection ID=' + this.connection.id); 
            this.setState({ isConnecting: false });
        })
        .fail(error => {
            console.error(error);
            this.setState({ isConnecting: false, error });
        });

        this.connection.connectionSlow(() => {
            toastr.info('Your connection seems to be slow', 'Connection Problem')
        })

        this.connection.reconnecting(() => {
            this.setState({ isReconnecting: true });
        })

        this.connection.reconnected(() => {
            this.setState({ isReconnecting: false });
        })
    }

    /**
     * Get the List of All Pre-Starts invoking the server method
     */
    fetchPreStartList = () => {
        this.setState({ isFetchingPreStartList: true, error: false });
        console.log('fetchPreStartList')
        this.preStartHub.invoke('supervisorLoadPreStartList')
        .fail(error => {
            console.error(error)
            this.setState({ isFetchingPreStartList: false, error });
        })
    }

    /**
     * @param {string} preStartId 
     * @param {boolean} isLocked Array list with current opened Pre-Start
     */
    supervisorChangeBoxLockerStatus = (preStartId, isLocked) => {
        console.log('supervisorChangeBoxLockerStatus', preStartId, isLocked)
        this.preStartHub.invoke('supervisorChangeBoxLockerStatus', preStartId, isLocked)
        .fail(error => {
            console.error(error)
            this.setState({ isFetchingPreStartList: false, error });
        })
    }
    
    /**
     * When the Pre-Starts List changes on server
     * @param {array} preStartList Array list with current opened Pre-Start
     */
    supervisorRefreshScreen = (preStartList) => {
        console.log('supervisorRefreshScreen', preStartList)
        if (preStartList) {
            for (var i = 0; i < preStartList.length; i++) {
                let { preStart } = preStartList[i];
                let issues = this.renderAllIssuesObject(preStart)
                preStartList[i] = {
                    ...preStartList[i],
                    ...issues
                }
            }
            this.setState({ preStartList, isFetchingPreStartList: false });
        }
    }

    /**
     * When someone lock a Pre-Start
     * @param {string} preStartId ID of the Pre-Start that is being locked
     * @param {boolean} isLocked If it's locked or not
     */
    supervisorUpdateScreenBoxLockerStatus = (preStartId, isLocked) => {
        let { preStartList } = this.state;
        preStartList.find(p => p.preStartId === preStartId).isLocked = isLocked;
        this.setState({ preStartList });
    }		`

**Comment by moozzyk** [comment]
Performance counters are collected on the server so the client used to connect to the server should not matter. Check if both clients are connecting to the same server.

**Comment by matheuscanela** [comment]
Yes, they are connected to the same server.

If I am using the react code that is the code above, I only collect a few counters like I've described on the ticket; however, if I use the pure html, it collects everything as normal.

Is there any "initialization" that we may be missing on the bower code?

**Comment by matheuscanela** [comment]
See these images below, same server different client code

![loghtml](https://cloud.githubusercontent.com/assets/6635137/26428489/52e2adb4-4125-11e7-89ee-5e5acdbe41c7.PNG)
![logreact](https://cloud.githubusercontent.com/assets/6635137/26428488/52e06dd8-4125-11e7-99fb-f35704c0f6f3.PNG)

**Comment by moozzyk** [comment]
It just looks like in the second case no-one is connected (Connection Connected is 0) the server has not received any messages (Connection Messages Received Total is 0) so there is nothing to show. As I said above, performance counters are server side concepts and are independent on the client so if your client is working it seems to be connecting to a different server or the client cannot connect to the server and is not working. You can turn on tracing on the client to see what's going on. You can also track requests in browser developers tools to see what requests the client is sending and where they are going. If none of these helps please create a minimal but runnable repro (ideally as a github repo so that it is easy just to clone and run) and post it to the thread.

**Comment by matheuscanela** [comment]
@moozzyk you were completely right, sorry for my mistake. 

So, the react was connecting to a different server only for the signalR and the normal API was connecting to the server that I was checking the performance. My question is, why I was getting counters on the server that the signalR wasn't pointing?

If it is the normal behaviour, I believe that we can close this thread and once again, sorry for this.

**Comment by moozzyk** [comment]
Connections Connected is 1 on the first server so **someone** is being connected and sending/receiving messages and counters are just counting it.

**Comment by matheuscanela** [comment]
Yes, the first screenshot is correct, but if you see the react screen shot which there is no one connected except the react html that is pointing to another server, you will be able to see messages going in and out on the bus without the connection that is showing 0.

**Comment by moozzyk** [comment]
AFAIR the server sends some messaged over the bus when it starts. I also think it is counted as a subscriber.

**Comment by matheuscanela** [comment]
@moozzyk thanks for your help.

I don't have time now to check it deeply, so I will leave it to a later analysis.

Thanks,
