### ISSUE TITLE
OnDisconnected behind load balancer

### ISSUE THREAD

**Issue by izverev-aexsoft** [SignalR/SignalR#3944]
I run two identical SignalR servers locally (at 81 and 82 ports) and nginx as a load balancer at port 80.
I use Redis as a backplane. Messages are delivered properly between server instances.
Using long polling protocol.

So internally each request is routed to either server and it causes strange behavior. OnDisconnected server event is called each time server is changed and timeout reached and it happens very often. OnConnected is never called (except initial connection). OnReconnected also never called. Client events are also fine (and I do not get client-side "disconnected" event once OnDisconnected happen at the server).

The issue doesn't happen when one server is behind LB. It is reproduced at Amazon EC2 instance with ALB.

Is it something expected that under LB server will face lots of OnDisconnected events? If so, how should I handle it - to distinct from real connection loss?
If not, what could be an issue?
Thanks a lot!

**Comment by izverev-aexsoft** [comment]
Here is my nginx config
`http {
	upstream lsp {
		least_conn;  
            server localhost:81;
             server localhost:82;
        }
    keepalive_timeout  65;
    server {
        listen       80;
        server_name  localhost;

        location / {
			proxy_pass http://lsp;
			proxy_buffering off;
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection keep-alive;
			proxy_set_header Host $host;
			proxy_cache_bypass $http_upgrade;
              }
        }
}`

**Comment by moozzyk** [comment]
The timeouts sound smelly. I would not expect any timeouts when connecting to localhost. Can you show some logs and code?

**Comment by izverev-aexsoft** [comment]
So basically it is not expected?
The most suspisious thing in our setup I think is that we on asp.net core and have to use netcore 461 full framework to support SignalR. 

I'll try to attach debugger to SignalR source code and investigate more, because it seems I have nothing specific to show you in my code/logs. Something should be wrong with LB setup or possibly netcore inconsistency is somewhere.

**Comment by izverev-aexsoft** [comment]
More debugging information (does something looks suspicious?)
1) Both instanes share one ConnectionId
2) OnConnected happens only at one instance
3) True/manual OnDisconnected happen at both instances, but only at one with stopCalled = true
4) Junk OnDisconnected happens from time to time at any of the instances, never at both, sometimes does not happen for a long time. Probably when LB routes request to the second instance and does not switch back to first one in SignalR ReconncetTimeout.

**Comment by moozzyk** [comment]
Note: We don't really support running 2.x SignalR in Asp.NET Core projects.

With regards to the debug information you provided - what does "both instances share one ConnectionId" means? What transport do you use? Did you track the traffic to tell what requests are being sent to which instance?

**Comment by izverev-aexsoft** [comment]
For tracking, I've attached separate debugger to each process and got same ConnectionId in both debuggers. Shouldn't it be so? Transport is long polling.

**Comment by izverev-aexsoft** [comment]
@moozzyk some updates here

I've debugged SignalR code and found out that Microsoft.AspNet.SignalR.Transports.TransportHeartbeat class which is used for long polling transport, uses ConcurrentDictionary to store connections metadata. DateTime LastMarked property is part of this metadata and if it is expired, OnDisconnected event is fired.
But this is not scalable... In case of using Redis backplane, I expect that such information should be shared across instances. Am I missing something?

Then, I was able to run websockets as transport, they do not use this TransportHeartbeat and everything worked just fine.

**Comment by davidfowl** [comment]
OnDisconnected has a bool that tells you it was the default of an explicit Stop `stopCalled ` or not. The transport heartbeat's job is to track connections on a particular machine, not across the farm. When a connection dies, it cleans up the local state and raises the appropriate events.

The truth is that when you scale out, you can't really rely on those connection events to fire exactly once for connections. A more scalable approach would be to query the connections on each machine and have logic that updates shared connection state.

**Comment by izverev-aexsoft** [comment]
@davidfowl thanks for pointing it out. Bad it wasn't mentioned anywhere in tutorials/docs about scalability, and so looked just like a bug when I encounter it. 

Please tell whether client connection is guaranteed to have one ConnectionId across multiple servers behind LB. I've tried with two PCs as well as with different ports at the same PC and I always got same ConnectionId, so considering it is (or looks like) GUID I guess that ConnectionId is shared.

If it is true, then it seems that modifying TransportHeartbeat to use shared storage for LastMarked will effectively resolve the issue?

+ I also have to say that stopCalled won't help in my case because I have to handle exactly "unintentional" OnDisconnected events, and I can not distinct them from these LastMarked timeouts.

**Comment by resetKelly** [comment]
@izverev-aexsoft - did you have any more findings on this?   I'm seeing the same thing...

**Comment by izverev-aexsoft** [comment]
@resetKelly I found three options: 
-  modify code to persist LastMarked in Redis/SQL DB 
-  use only websockets, they do not use TransportHeartbeat class
-  use sticky session of the load balancer, so your requests are routed to the same server

**Comment by resetKelly** [comment]
Thanks for the update, @izverev-aexsoft !

We aren't overly worried by the odd OnDisconnected - more that we were getting unstable SignalR reliability using Long Polling, particularly in an AWS load-balanced environment.  We suspect that the long-poll interval (2 mins) was too long, as was getting intermittently cut off by the AWS load-balancer's idleTimeout interval... we're testing..

Thanks again!

**Comment by cgyqu** [comment]
@resetKelly ,I‘ve had this problem,too! The connection will be broken in about half  an hour.The server client Client.Caller.doSomething() and Client.Client(connectionId).doSomething()  will not receive int the customer client.This means the connectionId is disconnected,but there was no notifucation. Only one server ,it's works very well !How did you do then?I also use redis  and LB;
blew is the Tengine server time out configm,

- proxy_connect_timeout 300s;
- proxy_send_timeout 300s;
- proxy_read_timeout 300s;

**Comment by resetKelly** [comment]
Hi @cgyqu - so, we changed the SignalR long-poll timeout to less than 1 min (50 seconds) - we only had one timing parameter on the AWS LB to play with.  Since then, we have had far better reliability in a load-balanced environment.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Comment by satish2832** [comment]
what is solution for this ?
