### ISSUE TITLE
Microsoft.AspNet.SignalR.Client，Microsoft.Extensions.DependencyInjection Conflict

### ISSUE THREAD

**Issue by atliuhui** [SignalR/SignalR#3945]
### Install-Package
Install-Package Microsoft.AspNet.SignalR.Client
Install-Package Microsoft.Extensions.DependencyInjection

### run this code
var connection = new Connection("signalr-url");
connection.Start();

### 发生了 System.TypeLoadException
  HResult=0x80131522
  Message=类型“System.Net.Http.WebRequestHandler”违反了继承安全性规则。派生类型必须与基类型的安全可访问性匹配或者比基类型的安全可访问性低。
  Source=Microsoft.AspNet.SignalR.Client
  StackTrace:
   在 Microsoft.AspNet.SignalR.Client.Http.DefaultHttpClient.CreateHandler()
   在 Microsoft.AspNet.SignalR.Client.Http.DefaultHttpClient.Initialize(IConnection connection)
   在 Microsoft.AspNet.SignalR.Client.Transports.TransportHelper.GetNegotiationResponse(IHttpClient httpClient, IConnection connection, String connectionData)
   在 Microsoft.AspNet.SignalR.Client.Transports.AutoTransport.GetNegotiateResponse(IConnection connection, String connectionData)
   在 Microsoft.AspNet.SignalR.Client.Transports.AutoTransport.Negotiate(IConnection connection, String connectionData)
   在 Microsoft.AspNet.SignalR.Client.Connection.Negotiate(IClientTransport transport)
   在 Microsoft.AspNet.SignalR.Client.Connection.Start(IClientTransport transport)
   在 Microsoft.AspNet.SignalR.Client.Connection.Start()

**Comment by moozzyk** [comment]
This sounds like package/project mismatch (e.g. installing a UWP package to a non-UWP project)

**Comment by atliuhui** [comment]
You're right.
Error in the ConsoleApp of .NET Framework 4.6, Right in ConsoleApp of .NETCoreApp 1.1

**Comment by moozzyk** [comment]
The netcoreapp1.1 should use netstandard1.3 version of the dll from the package. .NET Framework 4.6 should use net45 version.
