### ISSUE TITLE
Not response from hub methods after IISReset

### ISSUE THREAD

**Issue by trucnguyentrung** [SignalR/SignalR#3946]
Hi All,

I created an ASP.NET MVC app and added SignalR, It works well in IIS Express of Visual Studio.

After deploy to the server
- Windows 2012 R2
- IIS 8 (enabled Web Socket)

The first time, the web app works well on server, data returned from hub method, but after that I run IISRESET on server, can not get data from hub method. Enabled log in console, noticed that the method on hub is keep invoking and not going to invoked.

It should always return data from hub methods whenever restart IIS.

Sometime, data is returned, sometime data is not returned (not stable)

Step 1: Create 6 websites on IIS (same source code, different config for data fetching in web.config) . Binding different port. Separate application pool for each.
Step 2: Run the first time and check whether 6 applications are working.
Step 3: Restart IIS
Step 4: Some websites within 6 websites are not returned data from hub method.

[Logging] SignalR state changed from: disconnected to connecting
jquery.signalR-2.2.1.js:82 [19:59:15 GMT+0530 (India Standard Time)] SignalR: Client subscribed to hub 'supportgrouphub'.
dashboard.js:1 
[Logging] Connection is starting
jquery.signalR-2.2.1.js:82 [19:59:15 GMT+0530 (India Standard Time)] SignalR: Negotiating with '/signalr/negotiate?clientProtocol=1.5&connectionData=%5B%7B%22name%22%3A%22supportgrouphub%22%7D%5D'.
jquery.signalR-2.2.1.js:82 [19:59:15 GMT+0530 (India Standard Time)] SignalR: webSockets transport starting.
jquery.signalR-2.2.1.js:82 [19:59:15 GMT+0530 (India Standard Time)] SignalR: Connecting to websocket endpoint 'ws://**host:port**/signalr/connect?transport=webSockets&clientProtocol=1.5&connectionToken=9lwGLl5OMf10qK%2FuKoz2kXQjxX4m7zAe7%2Fs7rGK%2BNIEPnSnhySSPBAYj%2FBifMxfp0NiqfSzpUSQeEBYsrBebN2LBlA7jezH7Lc0lLm1KnpUFY1sJGXxPzvNm%2FTtqsYA5om0pfZ7AqhQFPjGDS6AsdA%3D%3D&connectionData=%5B%7B%22name%22%3A%22supportgrouphub%22%7D%5D&tid=8'.
jquery.signalR-2.2.1.js:82 [19:59:16 GMT+0530 (India Standard Time)] SignalR: Websocket opened.
jquery.signalR-2.2.1.js:82 [19:59:16 GMT+0530 (India Standard Time)] SignalR: webSockets transport connected. Initiating start request.
jquery.signalR-2.2.1.js:82 [19:59:16 GMT+0530 (India Standard Time)] SignalR: The start request succeeded. Transitioning to the connected state.
jquery.signalR-2.2.1.js:82 [19:59:16 GMT+0530 (India Standard Time)] SignalR: Now monitoring keep alive with a warning timeout of 13333.333333333332, keep alive timeout of 20000 and disconnecting timeout of 30000
dashboard.js:1 [Logging] SignalR state changed from: connecting to connected
dashboard.js:1 [Logging] Current State connected
dashboard.js:1 [Logging] Connected ID: 4b53408c-51d8-4049-a311-8232da4d1366
dashboard.js:1 [Logging] Calling Method At: Mon May 29 2017 19:59:17 GMT+0530 (India Standard Time)
jquery.signalR-2.2.1.js:82 [19:59:17 GMT+0530 (India Standard Time)] SignalR: Invoking supportgrouphub.GetSupportGroupOverviewListItem
jquery.signalR-2.2.1.js:82 [19:59:17 GMT+0530 (India Standard Time)] SignalR: Invoking supportgrouphub.StartMonitoring

Two server methods above are not invoked. Stopped at invoking....and data is not returned.
//js
$.connection.hub
        .start()
        .done(method1)
        .done(method2)

function method1() {
        return supportGroupHub.server.getSupportGroupOverviewListItem().done(function (response) {
            //logic after responsed
        }).fail(function (response) {
            console.error("SignalR disconnect occurred at: " + new Date().toString());
            console.error(response);
        });
    }
function method2() {      
        supportGroupHub.server.startMonitoring();
    }

Thanks for helps!!!

**Comment by zigamacss** [comment]
Having this issue too
