### ISSUE TITLE
SqlDependency with class Hub not work

### ISSUE THREAD

**Issue by matmiranda** [SignalR/SignalR#3948]
Follow the code:

**Components.cs:**

```
void SqlDep_OnChange(object sender, SqlNotificationEventArgs e)
{

    //from here we will send notification message to client
    NotificationHub notHub = new NotificationHub();
    notHub.SendNotification("User1586");

    //...
}
```
**NotificationHub : Hub**

```
private readonly static ConnectionMapping<string> _connections = new ConnectionMapping<string>();

public void SendNotification(string who)
{
    foreach (var connectionId in _connections.GetConnections(who))
    {
        var result = Clients.Client(connectionId); //< ------ Null

        Clients.Client(connectionId).addNotification(who);  // Here  <------- problem
        //Error: System.NullReferenceException: 'Object reference not set to an instance of an object.'
    }
}
```

**_Layout:**

```
$(function () {
    var connection = $.connection.notificationHub;

    //signalr method for push server message to client
    connection.client.addNotification = function (who) {
        //send notification here
        console.info("Send Notification")
    };

    // Start hub
    $.connection.hub.start().done(function () {
        console.log("SignalR Started")
    });
});
```
Does not work in class "Hub", please check image: [Here](https://s14.postimg.org/opqkw7nc1/devenv_2017-06-02_01-16-46.png)

Connection, HubName and Invoker are null.  Button Click of Jquery work fine. Does not work with SqlDep_OnChange.

Example click jquery: (This code works)

```
$(function () {
        var connection = $.connection.notificationHub;

        //signalr method for push server message to client
        connection.client.addNotification = function (who) {
            //send notification here
            console.info("Send Notification")
        };

        // Start hub
        $.connection.hub.start().done(function () {
            $("#testeclick").click(function () {
                connection.server.sendNotification("User15248");
            });
            console.log("SignalR Started")
        });
    });
```

Any solution to work with SqlDependency + SignalR?

**Comment by moozzyk** [comment]
Connection Id is a guid and you seem to provide a user name.

**Comment by matmiranda** [comment]
@moozzyk  I do not understand, can you give me an example?

**Comment by moozzyk** [comment]
When you are in a hub method you can get the connectionId by calling `Context.ConnectionId`. You will see it is a guid. If you authenticate users and you will have user names and you will need to map the name to the connection id to know connection id for a given name. SignalR works on connection level and not user names (note that using authentication with SignalR is not required so it is possible that you will never have a name). Here is an article that shows how to map user names to connection ids: https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/mapping-users-to-connections

**Comment by matmiranda** [comment]
@moozzyk The link that you sent, I already have it in my project. Please look at the hub class on the line:

`private readonly static ConnectionMapping<string> _connections = new ConnectionMapping<string>();`

Please check  4 images: (Fields Connection, HubName and Invoker are null. )

Image 1 : https://s23.postimg.org/wu720t5ff/devenv_2017-06-02_16-11-19.png

Image 2 : https://postimg.org/image/p3uujuaiv/

Image 3 : https://s13.postimg.org/sg6kxztbr/devenv_2017-06-02_16-21-28.png

Image 4 : https://s11.postimg.org/9qey1e0sj/devenv_2017-06-02_16-19-19.png

**Comment by moozzyk** [comment]
I don't see how you add connections to this mapping.

**Comment by matmiranda** [comment]
@moozzyk Tried another way and almost solved problem.

Please, follow code:

**NotificationHub : Hub**

```
private readonly static ConnectionMapping<string> _connections = new ConnectionMapping<string>();
public static void SendNotification(string who)
        {
            IHubContext context = GlobalHost.ConnectionManager.GetHubContext<NotificationHub>();
            foreach (var connectionId in _connections.GetConnections(who))
            {
                var result = context.Clients.Client(connectionId);
                if (result != null)
                {
                    result.addNotification(who);
                }
            }
        }
```
**Components.cs:**

```
void SqlDep_OnChange(object sender, SqlNotificationEventArgs e)
{

    //from here we will send notification message to client
    NotificationHub.SendNotification("User1586");
    //...
}
```
If you have 50 users online, send 50 times to users "User1586".

Problem on line: `NotificationHub.SendNotification("User1586");` //<--50 passes here.

Any solution ?
