### ISSUE TITLE
ScaleoutStream can deadlock if Send called before OpenStream fails and queuing is enabled

### ISSUE THREAD

**Issue by moozzyk** [SignalR/SignalR#3950]
If queuing is enabled ScaleoutStream will queue all Send requests received before Open. On the first Send after Open ScaleoutStream will try to drain the queue by waiting for the [drain task to complete](https://github.com/SignalR/SignalR/blob/b73cbabe69bc48c4cb8d768148e157712a264ce9/src/Microsoft.AspNet.SignalR.Core/Messaging/ScaleoutStream.cs#L105). This draining happens after acquiring a lock. The problem is that if one of the Send task waiting in the queue throws we would try to report the [error](https://github.com/SignalR/SignalR/blob/b73cbabe69bc48c4cb8d768148e157712a264ce9/src/Microsoft.AspNet.SignalR.Core/Messaging/ScaleoutStream.cs#L186). To do that we try to acquire a lock but the lock is being already held by the thread that is draining the queue which results in a deadlock.

A simple repro: https://github.com/SignalR/SignalR/compare/pawelka/scaleoutstream-deadlock

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
