### ISSUE TITLE
Cannot use custom SSL certificate validation callback in UWP Client

### ISSUE THREAD

**Issue by YakhontovYaroslav** [SignalR/SignalR#3951]
Both [ServicePointManager.ServerCertificateValidationCallback](https://msdn.microsoft.com/en-us/library/system.net.servicepointmanager.servercertificatevalidationcallback(v=vs.110).aspx) and [HttpClientHandler.ServerCertificateCustomValidationCallback](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.servercertificatecustomvalidationcallback) are unsupported on UWP platform. For custom SSL certificate validation UWP platform developers should use [Windows.Web.Http.HttpClient](https://docs.microsoft.com/en-us/uwp/api/windows.web.http.httpclient) with validation based on [HttpBaseProtocolFilter](https://docs.microsoft.com/en-us/uwp/api/windows.web.http.filters.httpbaseprotocolfilter).

### Expected  behavior
Developer being able to use self-signed certificates with invalid domain names for developing purposes and in production environments where DNS server in not available.

### Actual behavior
There is no support in built-in client for such functionality, thus developer must write client class from scratch.

### Steps to reproduce
Follow instruction [here](https://github.com/YakhontovYaroslav/FoundationHttpClientDemo)

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Comment by rgaufman** [comment]
I'm experiencing a problem still, I posted details here: https://github.com/SignalR/SignalR/issues/4697

@YakhontovYaroslav were you able to get this working, if so can you please share how?
