### ISSUE TITLE
Delay of 6- 30 Seconds in UWP client

### ISSUE THREAD

**Issue by ipsitg-optimus** [SignalR/SignalR#3955]
I have a SignalR server which sends certain messages to all the clients connected to it. I have created two sample clients one in UWP and another one is a simple console application in C#. I simply log a message once the client's method is called from SignalR.

Dramatically the console application logs the data as soon as the server sends, but the UWP application adds a delay of about 6-30 seconds in it. Although it triggers frequently sometimes but able to reproduce the issue 6 out of 10 times.

**Comment by moozzyk** [comment]
Please post a repro.

**Comment by ipsitg-optimus** [comment]
Below is the code for the UWP client, similar code is written in console application.

async Task SetupSignalR()
    {

        var conn = new HubConnection(baseUrl);
        Writer.Text += (string.Format("Creating hub proxy with :{0}\n", baseUrl));
        var proxy = conn.CreateHubProxy("PumpStatusHub");


        Writer.Text += "Starting Connection\n";


        try
        {
            conn.Start().Wait();
            Writer.Text += "Connection started\n";
            proxy.Invoke("OpenPortReading").Wait();//, UserName, TextBoxMessage.Text);
            Writer.Text += "Port invoked\n";
            proxy.On<string>("ReadUdpData", OnMessage);
        }
        catch (HttpRequestException ex)
        {
            Writer.Text += "Unable to connect to server: Start server before connecting clients.\n";
            Writer.Text += ex.Message + "\n";
        }
        catch (Exception ex)
        {
            Writer.Text += ex.Message + "\n";
            Task.Delay(3000).Wait();
            SetupSignalR().Wait();
        }
    }

    private void OnMessage(string obj)
    {
        Windows.ApplicationModel.Core.CoreApplication.MainView.
            Dispatcher.RunAsync(CoreDispatcherPriority.High, (DispatchedHandler)(() =>
            {
                Writer.Text += string.Format("Message received: {0}\n", counter++);
            }));
    }

**Comment by moozzyk** [comment]
You are likely deadlock because you use .Wait(). You need to `await` async calls - especially in UWP.

**Comment by ipsitg-optimus** [comment]
I have also tried that but it also gives the same result

**Comment by moozzyk** [comment]
You probably want to enable logging on the client to see what is happening.

**Comment by ipsitg-optimus** [comment]
I have added logs on the UWP app and the Console application and following are the observations from the logs

First Message got received at same time in both the apps, but for second message delay was observed in the UWP app.

Console Application Logs-
08:44:45.3689067 - cfee7a0d-7fcb-4c0e-95d7-ef8ebfc16658 - SSE: OnMessage(Data: {})
08:44:55.3850190 - cfee7a0d-7fcb-4c0e-95d7-ef8ebfc16658 - SSE: OnMessage(Data: {})
08:44:56.1073597 - cfee7a0d-7fcb-4c0e-95d7-ef8ebfc16658 - SSE: OnMessage(Data:  .... Data

UWP Application Logs-
08:44:45.3821041 - 37a2a4a9-d430-4869-adb9-23ceb72ffcca - SSE: OnMessage(Data: {})
08:44:55.3840407 - 37a2a4a9-d430-4869-adb9-23ceb72ffcca - SSE: OnMessage(Data: {})
08:45:05.4011226 - 37a2a4a9-d430-4869-adb9-23ceb72ffcca - SSE: OnMessage(Data:  ... Data

You can clearly see the difference of 9 seconds in the UWP app logs.

**Comment by moozzyk** [comment]
How do you send the data from the server? The transport logs as soon as it receives the message so it might not be an issue with the client. Do you use scaleout?
Can you provide a minimal but complete repro (ideally as a github repo)?

**Comment by ipsitg-optimus** [comment]
Following is the code for the server side

This is the hub class


    [HubName("PumpStatusHub")]
    public class PumpStatusHub : Hub
    {
        /// <summary>
        /// On Connected
        /// </summary>
        /// <returns></returns>
        public override Task OnConnected()
        {
            return Clients.All.joined();
        }

        /// <summary>
        /// 
        /// </summary>
        public void OpenPortReading()
        {
            PumpStatusCache.Instance.ReadUdpPort();
        }
    }


And there are these two method which as soon as reads data from our UDP service sends the message through SignalR


        private void ReadDataFromUdpPort()
        {
            _fuelPumpManager = GetFuelPumpManagerObject();
            try
            {
                try
                {
                    UDPAgent.Instance.OpenPort();
                }
                catch (Exception ex)
                {
                }
                try
                {
                    string strPacket = UDPAgent.Instance.ReceiveData();
                    Variables.Sleep(200);
                    _pumplog.Debug(strPacket);
                    var msg = _fuelPumpManager.ReadUdp(strPacket);
                    if (msg != null)
                    {
                        var hubContext = GlobalHost.ConnectionManager.GetHubContext<PumpStatusHub>();
                        var camelCaseFormatter = new JsonSerializerSettings();
                        camelCaseFormatter.ContractResolver = new CamelCasePropertyNamesContractResolver();
                        var json = JsonConvert.SerializeObject(msg, camelCaseFormatter);
                        _pumplog.Debug(json);
                        hubContext.Clients.All.readUdpData(json);
                        _pumplog.Debug("Data populated");
                    }
                }
                catch (Exception ex)
                {

                }
            }
            catch (Exception ex)
            {
                WriteToLogFile("SignalR Exception Message: " + ex.Message);
                WriteToLogFile("SignalR Exception StackTrace: " + ex.StackTrace);
            }
        }


        internal void ReadUdpPort()
        {
            if (_executing && _th != null && _th.ThreadState == ThreadState.Running)
                return;

            Task.Run(async () =>
            {
                _executing = true;
                while (_executing)
                {
                    _th = new Thread(ReadDataFromUdpPort);
                    _th.Start();
                    _th.Join();
                }
            });
        }

**Comment by moozzyk** [comment]
Do you see the same delay when sending directly to the client instead of when you read from udp? You seem to be swallowing a lot of exceptions - can it be that you are missing a message because of an exception that was ignored?

**Comment by ipsitg-optimus** [comment]
No I dont think this is the issue because the console application client receives all the messages very frequently and there is delay only in UWP app.

I also have recorded certain stats which are noted timestamps of the SignalR logs on console app and UWP app, These logs are for 17 consecutive messages sent from server to both the connected clients

UWP        Console App 
15:21:47	15:21:46
15:21:48	15:21:47
15:21:53	15:21:48
15:21:54	15:21:53
15:22:01	15:22:01
15:22:14	15:22:11
15:22:19	15:22:19
15:22:34	15:22:25
15:22:39	15:22:39
15:22:50	15:22:49
15:22:54	15:22:50
15:23:14	15:23:07
15:23:24	15:23:19
15:23:28	15:23:28
15:23:33	15:23:33
15:23:35	15:23:35
15:23:44	15:23:40

**Comment by moozzyk** [comment]
One more thought - have you tried using a different transport? Ideally webSockets (or even long polling)? Now I remember that  there was an issue in SL and Store httpClient where messages were not delivered immediately when using chunked encoding transfers which is what ServerSentEvent transport is using: https://github.com/SignalR/SignalR/issues/763.

**Comment by ipsitg-optimus** [comment]
@moozzyk  It actually worked, I used Long polling on your recommendation and now the UWP application is also receiving the messages on desired time.

Thanks for your great help, I really appreciate your contribution towards fixing this issue.

**Comment by moozzyk** [comment]
SignalR 2.2.2 contains a dedicated UWP client which, when used, will pick the webSocket transport automatically.
