### ISSUE TITLE
Access is denied error in signalr script while using iframes in IE

### ISSUE THREAD

**Issue by D-Aon** [SignalR/SignalR#3956]
I am rendering report inside an iframe and their domains are not same. While rendering I am getting 'Access is denied' error in IE. Works fine in other browers.

Jquery version: 1.10.2
Signalr version: 2.1.2

**Note:** Tried by upgrading signalr to 2.2.2 also. It is not working.

    //Signalr scripts goes here
        <script>
                $(document.ready(function () {
                    var response = $.connection.signalrHub;
                    response.client.connection = function () {
                       //connection
                    };
                    SJ.iwc.SignalR.start();
                });
        </script>

https://stackoverflow.com/questions/44690103/access-is-denied-error-in-signalr-script-while-using-iframes-in-ie

**Solution tried:** 

    $.connection.hub.start({ transport: ['webSockets', 'serverSentEvents', 'longPolling'] });

Tried by adding this inside `document.ready` but not working.

Anyone faced this issue ? Is there is any work around for this ?

**Comment by moozzyk** [comment]
Can it be this: https://stackoverflow.com/questions/1886547/access-is-denied-javascript-error-when-trying-to-access-the-document-object-of

**Comment by D-Aon** [comment]
Also, SJ.iwc is undefined in IE. 
![image](https://user-images.githubusercontent.com/29620022/27466566-4d6a6ae4-57f9-11e7-8acf-a834feee93a7.png)

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
