### ISSUE TITLE
No transport could be initialized successfully (server error, client not connect after a while)

### ISSUE THREAD

**Issue by nombrote** [SignalR/SignalR#3957]
### Expected  behavior
After having run for a long time a desktop application, running SignalR over Owin, and leaving at least one client connected, after an indeterminate time (can be about 10 hours), clients are disconnected and can no longer connect to the server. SignalR, even deleting cache or entering from another computer, the server does not allow them to connect.

The javascript gives the following error: "No transport could be initialized successfully. Try specifying a different transport or none at all for auto initialization" (it is in car)

The server, which is the problem, passes directly from the OnBeforeAuthorizeConnect method to OnBeforeDisconnect. (Returning true methods)

**Comment by moozzyk** [comment]
Can you capture HTTP traffic from the client to the server? I wonder if server is returning any errors or just times out.

**Comment by nombrote** [comment]
I paste there the chrome traces...

I understand that the server response is not a valid connection

There are 3 lines: (abobe a request and response of one of that)

#	Result	Protocol	Host	URL	Body	Caching	Content-Type	Process	Comments	Custom	
15	200	HTTP	10.146.7.37:6969	/signalr/hubs/signalr/negotiate?clientProtocol=1.5&token=8F8BW4BMTA7sa%2F8h%2BoETug%3D%3D&connectionData=%5B%7B%22name%22%3A%22eccohub%22%7D%5D&_=1498480632877	642		application/json; charset=UTF-8	chrome:9868			
16	 - 	HTTP	10.146.7.37:6969	/signalr/hubs/signalr/connect?transport=serverSentEvents&clientProtocol=1.5&token=8F8BW4BMTA7sa%2F8h%2BoETug%3D%3D&connectionToken=AQAAANCMnd8BFdERjHoAwE%2FCl%2BsBAAAANO%2Bm4kjeBE%2BIdWwyniXYQAAAAAACAAAAAAAQZgAAAAEAACAAAAD1D2tQ%2B4EOC5DMf5mLq3vVruNzhPx8pCqCVbN9rjMDVgAAAAAOgAAAAAIAACAAAACC9dE3lThkimdLR2xk17GqBsCv2Q3JLvci1IGWdgjjgTAAAAB3Fi5fn1%2BWwmahh%2Fetgm1YbY%2BaElu4Mx698ZxMce7pmz9E63edfYcRiQO5xO11GHdAAAAANsJ2rQCMRvUbgl7Jhp9Fs0RQChY1CKQLlJO79r6fUd6AymRbzt3uVKpKQRd8JvEOmjFht9N0xS4jF4IIAHNbFQ%3D%3D&connectionData=%5B%7B%22name%22%3A%22eccohub%22%7D%5D&tid=10	-1			chrome:9868			
17	 - 	HTTP	10.146.7.37:6969	/signalr/hubs/signalr/connect?transport=longPolling&clientProtocol=1.5&token=8F8BW4BMTA7sa%2F8h%2BoETug%3D%3D&connectionToken=AQAAANCMnd8BFdERjHoAwE%2FCl%2BsBAAAANO%2Bm4kjeBE%2BIdWwyniXYQAAAAAACAAAAAAAQZgAAAAEAACAAAAD1D2tQ%2B4EOC5DMf5mLq3vVruNzhPx8pCqCVbN9rjMDVgAAAAAOgAAAAAIAACAAAACC9dE3lThkimdLR2xk17GqBsCv2Q3JLvci1IGWdgjjgTAAAAB3Fi5fn1%2BWwmahh%2Fetgm1YbY%2BaElu4Mx698ZxMce7pmz9E63edfYcRiQO5xO11GHdAAAAANsJ2rQCMRvUbgl7Jhp9Fs0RQChY1CKQLlJO79r6fUd6AymRbzt3uVKpKQRd8JvEOmjFht9N0xS4jF4IIAHNbFQ%3D%3D&connectionData=%5B%7B%22name%22%3A%22eccohub%22%7D%5D	-1			chrome:9868			


And there a request and a response detailed:
http://10.146.7.37:6969/signalr/hubs/signalr/negotiate?clientProtocol=1.5&token=8F8BW4BMTA7sa%2F8h%2BoETug%3D%3D&connectionData=%5B%7B%22name%22%3A%22eccohub%22%7D%5D&_=1498480632876

RESPONSE:


HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Server: Microsoft-HTTPAPI/2.0
Access-Control-Allow-Origin: http://urlservice:8000
Access-Control-Allow-Credentials: true
X-Content-Type-Options: nosniff
Date: Mon, 26 Jun 2017 12:37:48 GMT
Content-Length: 630

{"Url":"/signalr/hubs/signalr","ConnectionToken":"AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAANO+m4kjeBE+IdWwyniXYQAAAAAACAAAAAAAQZgAAAAEAACAAAAAHvED1JfvMwVtoycYsa//vxs/gsaoXc/MZKI5mqMDuIgAAAAAOgAAAAAIAACAAAABv9L2VRkjmFNubRG+Y3k0elLGYJ0KF6MTgj/JFQurjKjAAAABxILdvKd3I6r7wyqo8JeXY4kt0rf55di2lBrUosBZXPJB8A0TiTXzd4vTHG85T27JAAAAAYgl0yU4/whFxTHqx8SOdXrGJVM/L6gvO4uFOutyIJjn9BCQ8S1sD/HX393ka1tDeLXRNsdu4JGyVoMhgQiGBfg==","ConnectionId":"0f0d95e2-1179-4bda-b7d5-35e45d4275ac","KeepAliveTimeout":20.0,"DisconnectTimeout":30.0,"ConnectionTimeout":110.0,"TryWebSockets":false,"ProtocolVersion":"1.5","TransportConnectTimeout":10.0,"LongPollDelay":0.0}

**Comment by nombrote** [comment]
I understand the server returns it is not a valid connection

**Comment by nombrote** [comment]
My project have signalr and webapi self hosted.

**Comment by moozzyk** [comment]
Not sure what you mean by _I understand the server returns it is not a valid connection_. Have you ever received a response to the connect request? I also don't see a start request - did the client send the start request? Has it completed successfully?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Comment by 1489919738** [comment]
I seem to have the same problem

**Comment by 1489919738** [comment]
Use nginx in case of prompt : "No transport could be initialized successfully. Try specifying a different transport or none at all for auto initialization"
