### ISSUE TITLE
SignalR and C# MVC Bundler

### ISSUE THREAD

**Issue by IgorJakovljevic** [SignalR/SignalR#3960]
# Issues related to the Asp.NET Core version of SignalR should be filed in the corresponding SignalR repo: https://github.com/aspnet/?utf8=%E2%9C%93&query=Signalr

### Expected  behavior
Using the "BundleConfig" Class and specifying the path to the location of the Autogenerated script should include the autogenerated script in the bundle.

### Actual behavior
The autogenerated script is not added to the bundle, because it is generated after the generation of the bundle/s. 

### Steps to reproduce
.) Create a MVC Project and include SignalR
.) In the "BundleConfig.cs" file include all necessary scripts and "~/signalr/hubs" 
.) Start Project 
.) The hubs file is not added to the bundle but it is present when included with the use of "<script>" tag

### Suggestion
The generation of these hubs could be included to the build event of a MVC App.

**Comment by moozzyk** [comment]
hubs file is dynamically generated when you request it for the first time. You can generate proxy manually using the signalr.exe tool as described [here](https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-javascript-client#manualproxy) to include it in your bundle. If you do this you most likely will want to disable proxy generation for the hub by setting `EnableJavaScriptProxies` configuration property to `false`.
