### ISSUE TITLE
SignalR server not able to send notification to SignalR client after idle the connection

### ISSUE THREAD

**Issue by msinha53** [SignalR/SignalR#3962]
Today I have disabled TLS1.0 and only enable TLS1.2 on the server. Before this activity my SignalR server & SignalR client working properly without any issue. But after this changes getting some different type of issue. SignalR server deployed with OWIN(.NET 4.6.1) in IIS. I am using .NET client and java client.
 We have two method(PublisherTopic & SubscribeTopic) under the hub.
 User 1 connect with server(Long Polling & Web Socket) and subscribe the topic-----Successful.
 User 2 connect with server(Long Polling & Web Socket) and published the same topic----- User 1 is receiving publish data.
 User 2 stop publishing and stop the connection.
 Now after 1 hour again User 2 connect with SignalR and start to publish but User 1 not able to received published data.
 I have enabled trace on the client side and server side but no any issue reported.
 SignalR subscribe client does not received any error events and connection is exist.

Please help me to resolve this issue.
 Mukesh

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
