### ISSUE TITLE
Connect Self Hosted SignalR

### ISSUE THREAD

**Issue by Sourabh721992** [SignalR/SignalR#3965]
Hi,

I have self hosted SignalR at my localhost.

Now, I want my colleague to connect to the SignalR server from his machine. I have tried numerous method but was not able to connect from different machine in the LAN network.

I request you to guide me.

**Comment by moozzyk** [comment]
make sure you bind to an ip and not localhost (you will have to run your app as an administrator to do that) and open the port on firewall.

**Comment by Sourabh721992** [comment]
I tried running as an admin. Also my firewall is off and I have bind the app to ip. But in vain :( 

Request you to guide me.

**Comment by moozzyk** [comment]
Are you binding to an IP or localhost?
