### ISSUE TITLE
How to use strongly typed api in .net client?

### ISSUE THREAD

**Issue by wavebit** [SignalR/SignalR#3966]
Hello,
I know how ot use strongly typed Hub in server for invoking client methods, but I don't know how to invloke/subscribe server-side menthods/messages using strongly typed api in .net client. After a quick searching, I got nothing.

**Comment by moozzyk** [comment]
There is no strongly typed api on the client side.

**Comment by wavebit** [comment]
Please bring balance to the SignalR.

**Comment by milkinllc** [comment]
https://github.com/AndreasBieber/SignalR.Client.TypedHubProxy

**Comment by wavebit** [comment]
Thanks @milkinllc 
It seems to be stopped, but I will try it.

**Comment by luetm** [comment]
> There is no strongly typed api on the client side.

What's the point of having it, if we have to use magic strings on the client anyway?
