### ISSUE TITLE
Exception thrown in ForeverTransport

### ISSUE THREAD

**Issue by Jestosteron** [SignalR/SignalR#3968]
Hi.
We implement a new HubPipelineModule to log the errors on the hub, but in one case we have a problem to log an unexpected exception if it is thrown in the PerformSend of the ForeverTransport class.

### Expected  behavior
The exception must be logged on the server side and the client must received the exception.

### Actual behavior
In the class ForeverTransport, the method PerformSend serialize the object. If the object is very large, the JSON serializer throw a System.OutOfMemory exception which we saw passing in the Debug Console of Visual Studio, but the OnIncomingError on our HubPipelineModule is not executed.
On the client side, the HttpResponse returns OK with an empty result, but the clients expects to receive not an empty result.

### Steps to reproduce
In the hub, return a large object.

**Comment by amccool** [comment]
how big?

**Comment by Jestosteron** [comment]
90 MB

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
