### ISSUE TITLE
How manage the online/offline status of the user in SignalR

### ISSUE THREAD

**Issue by Jenan** [SignalR/SignalR#3970]
I have created the chat application with `SignalR version 2.2.1` and I would like to create the information about user status - that means online/offline state.

I have tried use the method:
```
    public override Task OnConnected()
    {
      var token = Context.QueryString["token"];
            if (string.IsNullOrEmpty(token)) return Task.FromResult(0);

            using (var dbContext = new AppDbContext())
            {
                dbContext.UserConnections.Add(new UserConnection { ConnectionKey = Context.ConnectionId, UserId = token.GetUserId() });
                dbContext.SaveChanges();
            }

            Clients.Others.UserConnected(token.GetUserId());

            return Task.FromResult(0);
    }
  
    public override Task OnDisconnected(bool stopCalled)
    {
        using (var dbContext = new AppDbContext())
            {
                var connection = dbContext.UserConnections.First(x => x.ConnectionKey == Context.ConnectionId);

                var userId = connection.UserId;

                if (connection == null) return Task.FromResult(0);

                dbContext.UserConnections.Remove(connection);
                dbContext.SaveChanges();
            }

            Clients.Others.UserDisconnected(userId);

            return Task.FromResult(0);
    }
```

I don't know how correctly work with disconnect method on the client - because when user refresh the browser automaticly is called the `OnDisconnected` event with parameter `stopCalled=true` - I can now send some information about disconnection this user and set the icon for offline but immediately is user connect again and the icon is set to the online state and the user experience is strange.

How can I manage the disconnect state on javascript client without blinking the online/offline status especialy through refresh page?

**Comment by cgyqu** [comment]
Write a cookie in browser ,use this cookie to identify user.

**Comment by Jenan** [comment]
@cgyqu Thanks for your reply - I have forgotten close this issue. I have solved this use craete a delay in OnDisconnected method - where I wait some seconds and after that I remove the connectionid from database and if it is refresh - another connectionid for that user will be added in this delay. Works perfectly. :)
