### ISSUE TITLE
Hub.OnDisconnected event not fire with .NET client

### ISSUE THREAD

**Issue by fabercs** [SignalR/SignalR#3974]
**Client Side**
Server: localhost
Project: Windows Forms
Target framework: 4.6.1
SignalR version: Microsoft.AspNet.SignalR.Client 2.2.2

**Server Side**
Server: web server in local network
Project: Asp.Net Web API 2 / Runtime 4.0
Target framework: 4.6.1
SignalR version: Microsoft.AspNet.SignalR.Core 2.2.2
### Expected  behavior
When the client explicitly disconnects from the hub OnDisconnected event on server should trigger

### Actual behavior
OnConnected event is triggered after client starts the connection, However, OnDisconnected event on server never triggered when the client either explicitly or implicitly stops the connection.

### Steps to reproduce
Client side project is a class library which holds some custom windows forms, so inside the login form I start connection to ASP.NET WEB API server side. Transportation type is "serverSentEvents"

Codes as follows;
 **Client side:**

```
try
{
       dicQueryString = new Dictionary<string, string>();
       dicQueryString.Add("UserId", userId);

       Connection = new HubConnection(AppConstant.SignalrServerUrl, dicQueryString);
       Connection.Error += Connection_Error;
       Connection.StateChanged += Connection_StateChanged;
       Connection.Reconnecting += Connection_Reconnecting;
       Connection.Closed += Connection_Closed;
       Connection.Received += Connection_Received;
                
       Hub = Connection.CreateHubProxy("Macellum");
       Hub.On<string, string, string>("Receive", (data1, data2, data3) => Handle(data1, data2, data3));
       Connection.Start().Wait();
}
catch (Exception ex)
{
       using (StreamWriter sw = File.AppendText(@"C:\idealLog\log.txt"))
       {
            sw.WriteLine(string.Format(@"[{0}]: Error, ConnectToSignalRServer, Exception: {1} ", 
            DateTime.UtcNow.ToString("hh:mm:ss.f"), ex.Message));
        }
}
```
**Server Side**
```
public class Startup
{
        public void Configuration(IAppBuilder appBuilder)
        {
             //GlobalHost.Configuration.ConnectionTimeout = TimeSpan.FromSeconds(20);
             //GlobalHost.Configuration.DisconnectTimeout = TimeSpan.FromSeconds(6);
             GlobalHost.HubPipeline.AddModule(new LoggingPipelineModule());
             appBuilder.MapSignalR(new HubConfiguration { EnableDetailedErrors = true });
         }
}
```
```
public override Task OnConnected()
{
            try
            {
                var user = UserHandler.UserList.Find(u => u.UserId == Context.QueryString["UserId"]);
                if (user == null)
                {
                    UserHandler.UserList.Add(new UserConnection
                    {
                        UserId = Context.QueryString["UserId"],
                        ConnectionId = Context.ConnectionId
                    });
                    using (StreamWriter sw = (File.Exists(activityLoglogFilename)) ? File.AppendText(activityLoglogFilename) : File.CreateText(activityLoglogFilename))
                    {
                        sw.WriteLine(string.Format(@"[{0}]: ClientId:{1} ConnectionId: {2} connected",
                            DateTime.UtcNow.ToString("hh:mm:ss.f"), Context.QueryString["UserId"], Context.ConnectionId));
                    }
                }
            }
            catch (Exception ex)
            {

            }

            
            return base.OnConnected();
 }

 public override Task OnDisconnected(bool stopCalled)
{
            UserConnection user = UserHandler.UserList.Find(x => x.ConnectionId == Context.ConnectionId);
            if (user != null)
            {
                using (StreamWriter sw = (File.Exists(activityLoglogFilename)) ? File.AppendText(activityLoglogFilename) : File.CreateText(activityLoglogFilename))
                {
                    sw.WriteLine(string.Format(@"[{0}]: ClientId:{1} ConnectionId: {2} disconnected",
                        DateTime.UtcNow.ToString("hh:mm:ss.f"), user.UserId, user.ConnectionId));
                }
                UserHandler.UserList.Remove(user);
                
            }
            return base.OnDisconnected(stopCalled);
}
```
#Update

I am adding the server side logs (Connect the .Net client, hang on for a while then exit )

> SignalR.Transports.TransportHeartBeat Information: 0 : Connection 9499e332-038a-48a3-83bb-9c22b910ec51 is New.
> SignalR.Transports.ServerSentEventsTransport Verbose: 0 : Sending outgoing message. Connection id: 9499e332-038a-48a3-83bb-9c22b910ec51, transport: ServerSentEventsTransport, message: data: {"C":"d-3B28BF90-B,0|C,0|D,1","S":1,"M":[]}
> 
> 
> SignalR.Transports.TransportHeartBeat Verbose: 0 : KeepAlive(9499e332-038a-48a3-83bb-9c22b910ec51)
> SignalR.Transports.TransportHeartBeat Verbose: 0 : KeepAlive(9499e332-038a-48a3-83bb-9c22b910ec51)
> SignalR.Transports.TransportHeartBeat Verbose: 0 : KeepAlive(9499e332-038a-48a3-83bb-9c22b910ec51)
> SignalR.Transports.TransportHeartBeat Verbose: 0 : KeepAlive(9499e332-038a-48a3-83bb-9c22b910ec51)
> SignalR.Transports.TransportHeartBeat Verbose: 0 : KeepAlive(9499e332-038a-48a3-83bb-9c22b910ec51)
> SignalR.Transports.ServerSentEventsTransport Information: 0 : Abort(9499e332-038a-48a3-83bb-9c22b910ec51)
> SignalR.Transports.TransportHeartBeat Information: 0 : Removing connection 9499e332-038a-48a3-83bb-9c22b910ec51
> SignalR.Transports.ServerSentEventsTransport Information: 0 : End(9499e332-038a-48a3-83bb-9c22b910ec51)
> SignalR.Transports.ServerSentEventsTransport Verbose: 0 : DrainWrites(9499e332-038a-48a3-83bb-9c22b910ec51)
> SignalR.Transports.ServerSentEventsTransport Information: 0 : CompleteRequest (9499e332-038a-48a3-83bb-9c22b910ec51)
>

**Comment by fabercs** [comment]
On server hub, I was using `HttpContext.Current.Server.MapPath("~")`, OnConnected it was OK, but when disconnecting, HttpContext.Current is `null`, so hub was implicitly throws exception which I was unaware.
Using a static field or `HttpRuntime.AppDomainAppPath` solved the problem.

**Comment by moozzyk** [comment]
OnDisconnected is invoked from a background thread. In case of disgraceful disconnect there is no corresponding request - the connection was inactive for extended amount of time and is just being killed. Also in scaleout scenarios the abort request (which is used to close a connection) can be sent to any server.
