### ISSUE TITLE
How to get SignalR client for ARM linux ?

### ISSUE THREAD

**Issue by jacksonjim** [SignalR/SignalR#3975]
### Expected  behavior
The SignalR client does not support the ARM linux ! the client code language is the C or CPP! 
so How to get Client for ARM Linux!

**Comment by moozzyk** [comment]
Mono does support ARM - see: http://www.mono-project.com/docs/about-mono/supported-platforms/arm/
Also see my comment here: https://github.com/SignalR/SignalR/issues/3969#issuecomment-317039149
