### ISSUE TITLE
The latency is too high even though both client-side and server-side running on local

### ISSUE THREAD

**Issue by wavebit** [SignalR/SignalR#3977]
Hello,
I created a  a self-hosted SignalR server to test performance
https://github.com/wavebit/SRSelfHostTest.git
The result is here:
![cap](https://user-images.githubusercontent.com/11334491/28505974-90b793c0-705a-11e7-9f25-b920d3272be4.PNG)
The latency is too high even the concurrent connection under 10. I thought it should be 0~1 ms.
And I have done this test on Window Server 2016 and CentOS, the latency is still high.
If the server is running on remote, the waitting time will be about 500ms, that will be too high for a real time online game.

Below is the configuration:
From nuget packages.config
Server side:
![cap](https://user-images.githubusercontent.com/11334491/28506459-3cfe5c38-705e-11e7-8775-c13a4a9c375f.PNG)
Client side:
![cap](https://user-images.githubusercontent.com/11334491/28506478-5ec8987e-705e-11e7-9208-99a47b377749.PNG)
OS:
Windows 10 Pro, CPU i7-6700K, RAM 16G
Windows Server 2016 in VMware, CPU i7-6700K , RAM 4G
Centos 7.3 with Mono 5.0.1.1 in VMware, CPU i7-6700K, RAM 4G

**Comment by ralsu091** [comment]
I think the issue is that you are blocking on asynchronous code.
See https://stackoverflow.com/questions/22528694/signalr-invoke-not-returning-when-used-in-an-async-method

and http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

**Comment by petemclean** [comment]
Yes I think ralsu is right. Those waits look like they might be the problem, Perhaps you need something like this to get a better measure...

        static void Main()
        {
            MainAsync().GetAwaiter().GetResult();
        }

        public static async Task MainAsync()
        {
            var connection = new HubConnection($"http://127.0.0.1:8081");
            ServicePointManager.DefaultConnectionLimit = 500;
            var nhubProxy = connection.CreateHubProxy("Actor");

            await connection.Start();
            
            var tasks = Enumerable.Range(0, 100)
                .Select(async i =>
                {
                    var st = new Stopwatch();
                    st.Start();

                    var r = await nhubProxy.Invoke<float>("Move", 0f, (float)i);
                    Console.WriteLine($"{i} resulted in {r} in {st.ElapsedMilliseconds}ms on thread {Thread.CurrentThread.ManagedThreadId}");
                    return r;
                });

            await Task.WhenAll(tasks);

            connection.Stop();

            Console.WriteLine("Press any key to exit...");
            Console.ReadKey();
        }

**Comment by wavebit** [comment]
Thank you ralsu091 and ghost. You are right. And I found that the Parallel.For() seems use only 8 worker threads, and it seems that it is impossible to controll the the min-number of concurrent tasks.
