### ISSUE TITLE
Cannot read property 'client' of undefined

### ISSUE THREAD

**Issue by kofarrell1076** [SignalR/SignalR#3978]
Having a problem getting signalr running in my app. It fails on 👍 

 chat.client.addNewMessageToPage = function (name, message) {
              // Add the message to the page.
              $('#discussion').append('<li><strong>' + htmlEncode(name)
                  + '</strong>: ' + htmlEncode(message) + '</li>');
          };
with "cannot read property 'client' of undefined. This was working previously and also works in another test project. Same code in both projects, same server in both.

I suspect there is something else in the project that is interfering with signalr but after days of looking I cannot find anything.

any ideas?

**Comment by moozzyk** [comment]
If it worked before and not it does not check what changes you made to identify the one that broke it. 
This does not seem to be a product bug so I suggest asking this question on stackoverflow.
