### ISSUE TITLE
WIKI: Dead link on https://github.com/SignalR/SignalR/wiki/SQL-Server

### ISSUE THREAD

**Issue by hiredgunhouse** [SignalR/SignalR#3979]
# Issues related to the Asp.NET Core version of SignalR should be filed in the corresponding SignalR repo: https://github.com/aspnet/?utf8=%E2%9C%93&query=Signalr

### Expected  behavior
Link is not dead.

### Actual behavior
Link is dead.

### Steps to reproduce
Go to https://github.com/SignalR/SignalR/wiki/SQL-Server then click on the link and see it is dead.

**Comment by moozzyk** [comment]
Updated the link.
