### ISSUE TITLE
Problem with multi clients

### ISSUE THREAD

**Issue by slasia** [SignalR/SignalR#3984]
Hi I use SignalR for view a progress from method in C#
but I have a problem, when I have more than one client connected to my server the progress is mixed between them. For example:

The client one starts the method and the progres is  5%, 10%, 15%, 20% 
The client two starts the method and the progres is 5%, 15%, 10% 20%, 15% 

this clients works in differents places so is a big problem because this component do not support multi clients?  

My code is: 

```
 [HubName("progressHub")]
    public class ProgressHub : Hub
    {
        public static void SendMessage(string msg)
        {
            var hubContext = GlobalHost.ConnectionManager.GetHubContext<ProgressHub>();
            hubContext.Clients.All.sendMessage(string.Format(msg));
        }
    }

```

`ProgressHub.SendMessage("Generando Grafico: " + Math.Round(acum, 2).ToString()  + " %");`

**Comment by moozzyk** [comment]
You seem to start a method that reports progress from two clients and report the progress to all clients. As per your implementation all clients are receiving all progress updates. If you want the progress to be reported only to the client which started the method that reports progress you need to send progress messages only to the given client and not all clients (i.e. `Clients.Client(connectionId)` and not `Clients.All`).
