### ISSUE TITLE
how to use signalr with https server by self-host(windows form project)

### ISSUE THREAD

**Issue by akira32chen** [SignalR/SignalR#3985]
My ASP.NET uses SignalR 2.2.2 (Javascript client). My windows form is installed with SignalR 2.2.2 and  SelfHost. Now they run without no problem. But I wish change http to https.
I deploy ASP.NET to  IIS server and use https. I wish my windows form's self-host can also use https address.

ASP.NET javascript

```
	<script src="https://myweb.com.tw:9000/signalr/hubs"></script>
	<script src="https://myweb.com.tw:9000/signalr/js"></script>

connection = $.connection("https://myweb.com.tw:9000/realtime/echo");

			connection.error(function (err) {
				
				var bShowErrorMsg = true;
				if (bShowErrorMsg == true) {
					alert("Uups! It seems there is a problem. \n" + "Error: " + err.message);
				}
			});
```

Windows form

```
private IDisposable SignalR { get; set; }

					else if (comboBoxHttp.Text == "https")
					{
						fullIP = @"https://*:9000";
                                                SignalR = WebApp.Start(fullIP);
					}
```
But the connection is still not successful. The connection.error appears the Error of "Error:Error during negotiation request". Does somebody know how to use SignalR under https address? If I want to use https in Signal Server(Windows form) and Signal Client(ASP.NET client).

**Comment by moozzyk** [comment]
Did you setup certificates correctly? [This](https://stackoverflow.com/questions/18150758/signalr-with-self-signed-ssl-and-self-host) stackoverflow post have a lot of information. Also check [this](https://weblog.west-wind.com/posts/2013/Sep/23/Hosting-SignalR-under-SSLhttps) post.

**Comment by zhujinhu21** [comment]
@akira32chen how did you solve it
