### ISSUE TITLE
SignalR counter instance not displaying after IIS recycle. 

### ISSUE THREAD

**Issue by msinha53** [SignalR/SignalR#3986]
When IIS restarted then able to add SignalR counter with instance in performance monitor. But when IIS recycle then not able to add SignalR counters in performance monitor because SignalR counters instance not available.

**Comment by moozzyk** [comment]
Doesn't ring a bell. Not sure if there is anything we can do in SignalR - maybe try to restart performance monitor after IIS is recycled?

**Comment by msinha53** [comment]
Yes, I have restarted performance monitor after IIS is recycled but issue is the same(SignalR counters instance not available). This issue is only happen only in case of IIS recycled, if IIS restart then issue is not happen. 
I have tested on multiple server but have the same issue.
Please help me.

**Comment by moozzyk** [comment]
Do you see any performance counter related errors in the event log? I wonder if this can be happening: https://stackoverflow.com/questions/344018/using-custom-performance-counters-across-appdomain-recyclyes

**Comment by msinha53** [comment]
No, I have verified event logs but no any error logs reported in application event.

**Comment by msinha53** [comment]
When I set "Disable Overlapped Recycle" property to true then instance name available. But I can't set true because this is a web api and many requests in process and I don't want to lost the previous requests. Please give me any other solution for this issue.

**Comment by msinha53** [comment]
After changed host.AppName of IAppBuilder properties then issue is resolved and every time when IIS restart or recycled then created new instance name. This code added before SignalR mapping.
           var env = appBuilder.Properties;
            if (env.ContainsKey("host.AppName"))
            {
                int nProcessID = Process.GetCurrentProcess().Id;
                string appName = env["host.AppName"] + "/" + nProcessID.ToString();
                env["host.AppName"] = appName;
            }

**Comment by moozzyk** [comment]
Glad you found a workaround. I actually filed this [bug](https://github.com/SignalR/SignalR/issues/3993) yesterday. I think what might have happened in your case that the AppName changed during recycle and after recycle you continued to look at the counters for the old instance.
