### ISSUE TITLE
Credentials flag was set to true, but Access-Control-Allow-Credentials was not present or was not set to "true".

### ISSUE THREAD

**Issue by HeroSpha** [SignalR/SignalR#3987]
I have an api app, i have deployed it to azure. i have set the CORS in azure my localhost works fine if im querying data, i get an error when im trying to intergrate signalR to my system. i get this error
`Credentials flag was set to true, but Access-Control-Allow-Credentials was not present or was not set to "true".`
`XMLHttpRequest: Network Error 0x80070005, Access is denied.`

The app fails during negotiation
my server side signalR is like this
```
            ConfigurationOAuth(app);

            GlobalConfiguration.Configure(WebApiConfig.Register);
            //WebApiConfig.Register(config);
            UnityConfig.RegisterComponents();
            WebApiConfig.InitialiseShardMapManager();
           
            // SwaggerConfig.Register(config);
            // For more information on how to configure your application, visit http://go.microsoft.com/fwlink/?LinkID=316888
            // Branch the pipeline here for requests that start with "/signalr"
            app.Map("/signalr", map =>
            {
                map.UseCors(CorsOptions.AllowAll);
                var hubConfiguration = new HubConfiguration { EnableJavaScriptProxies = true};
                hubConfiguration.EnableJSONP = true;
                map.RunSignalR(hubConfiguration);
                
            });
            HttpConfiguration config = new HttpConfiguration();
            app.UseWebApi(config);
```

Im using OWIN bearer token 
and my angularjs client side i this
```
var issuehub = $.connection.MyHub;
issuehub.client.addIssue = function (issue) {
        alert(issue);
    };
    $.connection.hub.url = "https://sitename.azurewebsites.net/signalr";
  
    $.connection.hub.logging = true;
    $.connection.hub.start().done(init);`
```

I only get error when im trying to user signalR, any help will be much appreciated

**Comment by HeroSpha** [comment]
in chrome this is what im getting
`XMLHttpRequest cannot load https://sitename.azurewebsites.net/signalr/negotiate?client…ol=1.5&connectionData=%5B%7B%22name%22%3A%22myhub%22%7D%5D&_=1502363602556. The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. Origin 'http://localhost:35609' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.`

**Comment by jeffersoneagley** [comment]
Same problem for me.

**Comment by queryquandary** [comment]
I have the exact same problem.

**Comment by Andymax7** [comment]
Please, your help!!! I have the same problem.

**Comment by HeroSpha** [comment]
Are you using Owin Startup class?

**Comment by HeroSpha** [comment]
Probably your are setting cors(Make sure the cors is not set on Azure) morethan once or something to do with OAuthAuthorizationServerProvider.

**Comment by enginnerFrankLiu** [comment]
Same problem for me.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Comment by moab2486** [comment]
include a mode and set it to cors

**Comment by inexuscore** [comment]
> On the client side, pass a `{withCredentials: false}` parameter to the connection.start() function:
> 
> ```
> connection
> .start({ withCredentials: false })
> .done(() => { ... });
> ```

Note that this option is enabled by default and is required for sticky sessions. If you're hosting your app with multiple servers (e.g. Azure App Service with multiple instances), you'll need to enable this for affinity cookies, etc.
