### ISSUE TITLE
Expose instance name of performance counters (and category?)

### ISSUE THREAD

**Issue by moozzyk** [SignalR/SignalR#3993]
Currently it is impossible to get the instance name of performance counters. The name is generated at runtime. If there are multiple SignalR applications running it might be hard to tell which instance to pick for the given application. In some cases (e.g. appName is null) the instance name can be just GUID. Another scenario where accessing the instance name could be useful is tracking performance counters with AppInsights - the user could configure performance counters in code (as described here: https://blogs.msdn.microsoft.com/devops/2015/04/01/application-insights-choose-your-own-performance-counters/). Enabling setting the name of the instance (e.g. in configuration) could be even more useful - it would enable configuring performance counters in ApplicationInsight.config

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
