### ISSUE TITLE
Setting KeepAlive has no effect

### ISSUE THREAD

**Issue by wmmihaa** [SignalR/SignalR#3995]
I'm running an ASP.NET MVC (4.5.2) with SignalR to communicate with browser- and node.js clients. As the node.js clients are connected over LTE(4G), I'd like to minimize the traffic a bit. The server sends KeepAlive messages every 10 seconds which adds upp to ~240MB/month. If I could decrease this number by half, I'd save ~$10 on each SIM card per month.

### Expected  behavior
The default settings for KeepAlive is 10 seconds and DisconnectTimeout 30 seconds. I would have expected these values to be sent to the client upon negotiating initial connection. After which the hub would "ping" the client every 10 seconds.

### Actual behavior
The hud does ping the clients every 10 seconds, however, the negotiatedOptions I get on the node.js client says the KeepAlive is 20 seconds, which I though was odd: 

```
{
  "Url": "/signalr",
  "ConnectionToken": "...",
  "ConnectionId": "...",
  "KeepAliveTimeout": 20,
  "DisconnectTimeout": 30,
  "ConnectionTimeout": 110,
  "TryWebSockets": true,
  "ProtocolVersion": "1.3",
  "TransportConnectTimeout": 5,
  "LongPollDelay": 0,
  "Hubs": [
    {
      "name": "integrationhub"
    }
  ]
}
```

But the important part is, -changing the setting in the **Startup :: Configuration** has no effect on either the _negotiatedOptions_ sent to the client nor the actual ping frequency.:

```
GlobalHost.Configuration.DisconnectTimeout = TimeSpan.FromSeconds(90);
GlobalHost.Configuration.KeepAlive = TimeSpan.FromSeconds(30);
app.MapSignalR();

```

**Comment by wmmihaa** [comment]
Some input to the matter... I removed the SignalR nuget packages 2.2.2 and cloned the code from github, set the references and it all worked...

**Comment by moozzyk** [comment]
`KeepAliveTimeout` is something different than `KeepAlive`. KeepAlive tells the server how often to send KeepAlive (setting null disables sending KeepAlive messages completely). KeepAliveTimeout tells the client how much time from seeing the last message it needs to wait before it tries to reconnect.
