### ISSUE TITLE
Possibly remove Microsoft.AspNet.SignalR.JS as a dependency?

### ISSUE THREAD

**Issue by jsaunders92** [SignalR/SignalR#3997]
I'm not sure if having this as a dependency necessarily makes sense. 

Firstly, many people don't need to the JavaScript client and can seek it out themselves in they need it. I'm not using it with a JavaScript client at all and it seems wasteful to need it to be download each time. Secondly, having it as a dependency meant I had to download the NuGet manually and remove the dependency to install the NuGet in MonoDevelop because (obviously) the JS dependency doesn't target the .NET framework.

**Comment by moozzyk** [comment]
I assume you are talking about Microsoft.AspNet.SignalR package - it's just a metapackage that brings other dependencies. You can go more granular and install only packages you need instead of using metapackage.
