### ISSUE TITLE
SignalR.Redis use connection string to redis cluster will sent duplicate message

### ISSUE THREAD

**Issue by mywand** [SignalR/SignalR#3998]
# Issues related to the Asp.NET Core version of SignalR should be filed in the corresponding SignalR repo: https://github.com/aspnet/?utf8=%E2%9C%93&query=Signalr

### Expected  behavior
Send a message.
### Actual behavior
A large number of duplicate messages are sent.
![default](https://user-images.githubusercontent.com/13902074/29597534-c7855100-87f5-11e7-930b-a6fc8003b489.png)

### Steps to reproduce
var connectionString = "10.99.7.181:16379,10.100.45.4:8106,10.100.45.6:8110,10.99.7.182:16379,10.100.45.8:8092,10.99.7.183:16379, name=tcweb.livechattest_1.0.1.32588,keepAlive=15,syncTimeout=5000,connectTimeout=25000,abortConnect=False,resolveDns=False,responseTimeout=10000";
GlobalHost.DependencyResolver.UseRedis(new RedisScaleoutConfiguration(connectionString, "LiveChatSignalRBus02"));

**Comment by mywand** [comment]
Received message 23: '{"H":"ChatHub","M":"broadcastMessage","A":["郭笙a6d26444-60d6-4071-91a7-beda093399d3","asdf"]}' over ScaleoutMessageBus
Sending hub invocation result to connection a6d26444-60d6-4071-91a7-beda093399d3 using transport ServerSentEventsTransport
SignalR.ScaleoutMessageBus Verbose: 0 : Message id: 23, stream : 0, eventKey: 'h-ChatHub' saved with local id: 0
SignalR.Transports.ServerSentEventsTransport Verbose: 0 : Sending outgoing message. Connection id: a6d26444-60d6-4071-91a7-beda093399d3, transport: ServerSentEventsTransport, message: {"I":"0"}
SignalR.ScaleoutMessageBus Verbose: 0 : Scheduling eventkeys: h-ChatHub
SignalR.ScaleoutMessageBus Information: 0 : OnReceived(0, 23, 1)
SignalR.ScaleoutSubscription Verbose: 0 : Extracting message for scaleout mapping: 23, stream index 0, [a6d26444-60d6-4071-91a7-beda093399d3]
SignalR.ScaleoutMessageBus Verbose: 0 : Received message 23: '{"H":"ChatHub","M":"broadcastMessage","A":["郭笙a6d26444-60d6-4071-91a7-beda093399d3","asdf"]}' over ScaleoutMessageBus
SignalR.ScaleoutSubscription Verbose: 0 : Adding 1 message(s) for mapping id: 23, event key: 'h-ChatHub', event id: 0, streamIndex: 0
SignalR.ScaleoutSubscription Verbose: 0 : Updated cursor for mapping id 23 stream idx 0 to 23 [a6d26444-60d6-4071-91a7-beda093399d3]
SignalR.ScaleoutMessageBus Verbose: 0 : Message id: 23, stream : 0, eventKey: 'h-ChatHub' saved with local id: 1
SignalR.ScaleoutSubscription Verbose: 0 : Setting cursor 0 value 22 to 23 [a6d26444-60d6-4071-91a7-beda093399d3]
SignalR.ScaleoutMessageBus Verbose: 0 : Scheduling eventkeys: h-ChatHub
SignalR.ScaleoutMessageBus Information: 0 : OnReceived(0, 23, 1)
SignalR.ScaleoutMessageBus Verbose: 0 : Received message 23: '{"H":"ChatHub","M":"broadcastMessage","A":["郭笙a6d26444-60d6-4071-91a7-beda093399d3","asdf"]}' over ScaleoutMessageBus
SignalR.Transports.ServerSentEventsTransport Verbose: 0 : Sending outgoing message. Connection id: a6d26444-60d6-4071-91a7-beda093399d3, transport: ServerSentEventsTransport, message: data: {"C":"s-0,17","M":[{"H":"ChatHub","M":"broadcastMessage","A":["郭笙a6d26444-60d6-4071-91a7-beda093399d3","asdf"]}]}


SignalR.ScaleoutMessageBus Verbose: 0 : Message id: 23, stream : 0, eventKey: 'h-ChatHub' saved with local id: 2
SignalR.ScaleoutMessageBus Verbose: 0 : Scheduling eventkeys: h-ChatHub
SignalR.ScaleoutSubscription Verbose: 0 : Extracting message for scaleout mapping: 23, stream index 0, [a6d26444-60d6-4071-91a7-beda093399d3]
SignalR.ScaleoutSubscription Verbose: 0 : Adding 1 message(s) for mapping id: 23, event key: 'h-ChatHub', event id: 1, streamIndex: 0
SignalR.ScaleoutSubscription Verbose: 0 : Updated cursor for mapping id 23 stream idx 0 to 23 [a6d26444-60d6-4071-91a7-beda093399d3]
SignalR.ScaleoutSubscription Verbose: 0 : Extracting message for scaleout mapping: 23, stream index 0, [a6d26444-60d6-4071-91a7-beda093399d3]
SignalR.ScaleoutSubscription Verbose: 0 : Setting cursor 0 value 23 to 23 [a6d26444-60d6-4071-91a7-beda093399d3]
SignalR.Transports.ServerSentEventsTransport Verbose: 0 : Sending outgoing message. Connection id: a6d26444-60d6-4071-91a7-beda093399d3, transport: ServerSentEventsTransport, message: data: {"C":"s-0,17","M":[{"H":"ChatHub","M":"broadcastMessage","A":["郭笙a6d26444-60d6-4071-91a7-beda093399d3","asdf"]}]}


SignalR.ScaleoutSubscription Verbose: 0 : Extracting message for scaleout mapping: 23, stream index 0, [a6d26444-60d6-4071-91a7-beda093399d3]
SignalR.ScaleoutSubscription Verbose: 0 : Adding 1 message(s) for mapping id: 23, event key: 'h-ChatHub', event id: 1, streamIndex: 0
SignalR.ScaleoutSubscription Verbose: 0 : Updated cursor for mapping id 23 stream idx 0 to 23 [a6d26444-60d6-4071-91a7-beda093399d3]
SignalR.ScaleoutSubscription Verbose: 0 : Extracting message for scaleout mapping: 23, stream index 0, [a6d26444-60d6-4071-91a7-beda093399d3]
SignalR.ScaleoutSubscription Verbose: 0 : Setting cursor 0 value 23 to 23 [a6d26444-60d6-4071-91a7-beda093399d3]
SignalR.Transports.ServerSentEventsTransport Verbose: 0 : Sending outgoing message. Connection id: a6d26444-60d6-4071-91a7-beda093399d3, transport: ServerSentEventsTransport, message: data: {"C":"s-0,17","M":[{"H":"ChatHub","M":"broadcastMessage","A":["郭笙a6d26444-60d6-4071-91a7-beda093399d3","asdf"]}]}


SignalR.ScaleoutSubscription Verbose: 0 : Extracting message for scaleout mapping: 23, stream index 0, [a6d26444-60d6-4071-91a7-beda093399d3]
SignalR.ScaleoutSubscription Verbose: 0 : Adding 1 message(s) for mapping id: 23, event key: 'h-ChatHub', event id: 1, streamIndex: 0
SignalR.ScaleoutSubscription Verbose: 0 : Updated cursor for mapping id 23 stream idx 0 to 23 [a6d26444-60d6-4071-91a7-beda093399d3]
SignalR.ScaleoutSubscription Verbose: 0 : Extracting message for scaleout mapping: 23, stream index 0, [a6d26444-60d6-4071-91a7-beda093399d3]
SignalR.ScaleoutSubscription Verbose: 0 : Setting cursor 0 value 23 to 23 [a6d26444-60d6-4071-91a7-beda093399d3]
SignalR.Transports.ServerSentEventsTransport Verbose: 0 : Sending outgoing message. Connection id: a6d26444-60d6-4071-91a7-beda093399d3, transport: ServerSentEventsTransport, message: data: {"C":"s-0,17","M":[{"H":"ChatHub","M":"broadcastMessage","A":["郭笙a6d26444-60d6-4071-91a7-beda093399d3","asdf"]}]}

**Comment by moozzyk** [comment]
Do you use Redis clusters?

**Comment by mywand** [comment]
yes, use Redis clusters.

**Comment by moozzyk** [comment]
As stated in the [docs](https://docs.microsoft.com/en-us/aspnet/signalr/overview/performance/scaleout-with-redis) Redis clusteres are not supported for SignalR scaleout. Sorry.
