### ISSUE TITLE
404 on "Apache 2.0 License" click on signalr.net

### ISSUE THREAD

**Issue by VPashkov** [SignalR/SignalR#3999]
### Expected  behavior
I can see license text

### Actual behavior
I see 404 error

### Steps to reproduce
Open [signalr.net ](http://signalr.net) in browser
Click to "Apache 2.0 License"

#3797

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
