### ISSUE TITLE
Cors issue with signalR 2x

### ISSUE THREAD

**Issue by bhasker412** [SignalR/SignalR#4000]
I had a working signalR hosted in godaddy. But now am facing cors issue as mentioned below.

Tried in Firefox: 56 and Edge 40 facing the same issue.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http:///signalr/negotiate?clientProtocol=1.5&group=&connectionData=%5B%7B%22name%22%3A%22imageshub%22%7D%5D&_=1503813812427. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

I have tried all the CORS configurations mentioned in tutorial nothing worked.

Here is my startup.cs which i am using now.

```C#
public class Startup
{

    public void Configuration(IAppBuilder app)
    {
        app.UseCors(CorsOptions.AllowAll);
        app.Map("/signalr", map =>
        {
            // Setup the CORS middleware to run before SignalR.
            // By default this will allow all origins. You can 
            // configure the set of origins and/or http verbs by
            // providing a cors options with a different policy.
            
            //map.UseCors(CorsOptions.AllowAll);                

            HubConfiguration hubConfiguration = new HubConfiguration();
            //hubConfiguration.EnableDetailedErrors = true;
            //hubConfiguration.EnableJavaScriptProxies = true;
            
            map.RunSignalR(hubConfiguration);

        });

        **
       //app.Map("/cors", map =>
        //{
        //    map.UseCors(CorsOptions.AllowAll);
        //    map.MapSignalR();
        //});**

    }
}
```

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
