### ISSUE TITLE
NullReferenceException on Dispose 

### ISSUE THREAD

**Issue by maggarwal** [SignalR/SignalR#4004]
### Expected  behavior

On calling HubConnection.Dispose it shouldn't throw exception.

### Actual behavior

On calling HubConnection.Dispose I am seeing a NullReferenceException thrown.

I believe it may be because server connection doesn't exist anymore. 

call stack 

   at Microsoft.AspNet.SignalR.Client.Connection.Stop(TimeSpan timeout)
![image](https://user-images.githubusercontent.com/1377993/29929861-9108b252-8e21-11e7-9c79-dd8a6a6f176b.png)

![image](https://user-images.githubusercontent.com/1377993/29929895-b20a03d4-8e21-11e7-895a-c04b01c872d1.png)

**Comment by moozzyk** [comment]
Can you show the repro? I am not sure which reference could be null. Or is it happening when you try to Stop connection that has not been started?

**Comment by SytecSoftwareTeam** [comment]
Good afternoon, 
I'm having the same issue.  If I dispose the connection from a Console Application the exception is not thrown, but stopping the self host windows service that keep the connection alive I got the exception.  Every time.

Can you please help us?
Regards Enrico

**Comment by Skuriles** [comment]
We have the same problem: 
Server as console app works, Server as service crashes client if the server is not available

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
