### ISSUE TITLE
Hub failed to send message to client on Windows 10 laptop when laptop resume from sleep mode

### ISSUE THREAD

**Issue by crushonme** [SignalR/SignalR#4005]
### Expected  behavior
Client reconnect to hub and normally receive messages from hub.
### Actual behavior
Client failed to reconnect since the Reconnect window timeout reached.
### Steps to reproduce
1. Deploy client on Windows 10 laptop and let Windows 10 in sleep mode more than 50 seconds;
2. Resume Windows 10 laptop to normal mode;
3. Client cannot automatically reconnect to hub;

**Comment by moozzyk** [comment]
Most likely the client exceeded the reconnect timeout and you need to restart the connection.
