### ISSUE TITLE
SignalR With Redis Cluster 

### ISSUE THREAD

**Issue by cgyqu** [SignalR/SignalR#4006]
When use singalr as real-time communication，My Partner modify redis client  to  use redis cluster; 
As we test , there was a bug.One client send one message to the other ,the other client received  thousand of message.
If we don't use lua script,   we change send message In 2 steps.First：Increase  ; Second:Publish message;
In this condition ,we will lose message,the probability is between  0.01% to  0.1%;

So are these  the reasons why  signalr don't support redis cluster

**Comment by moozzyk** [comment]
> As we test , there was a bug.One client send one message to the other ,the other client received thousand of message.

This is the reason. The script is replayed on all nodes in the cluster and cause the same event to happen multiple times.
