### ISSUE TITLE
Send signalr notification from web api to application site

### ISSUE THREAD

**Issue by ghost** [SignalR/SignalR#4007]
I have Web API application in which I need to send notification using SignalR Hub to application site.

**Web api**

```C#
HubConnection connection = new HubConnection("http://localhost:52620/");
var hub = connection.CreateHubProxy("TestHub");
if (connection.State == ConnectionState.Disconnected)
{
    await connection.Start();
}
await hub.Invoke("SendNotifications", Id.ToString());
```

**Web application**

```C#
public class TestHub : Hub
{
    public void SendNotifications(string Id)
    { }
}
```

But notification not appended in application. What have I missed in this ?

It returns method not found exception.

 
![image](https://user-images.githubusercontent.com/12719187/30271521-3acceb38-970e-11e7-9a2b-97e563e3fe08.png)

I have tried to fix this by updating url format as below but doesn't work.

http://localhost:52620/signalr

http://localhost:52620/signalr/hubs

Note: I am using 2.2.1.0 version of signalr and 6.0.0.0 version of newtonsoft.json

Please help me to resolve this. 

Thanks in advance.

**Comment by moozzyk** [comment]
Please post a repro as a github repo so that I can clone and try it. The code you showed should not fail like this and I don't know where this exception is thrown. JValue in version 6 does contain CreateNull:

![image](https://user-images.githubusercontent.com/1438884/30288125-74bdcaf6-96dc-11e7-8d2b-ba86af867529.png)

So either you are unknowingly using a lower version which did not contain this function (I don't know if such a version existed though) or something else is going on.

**Comment by priyankaaravind** [comment]
FYI, now i didn't make any changes. but some time while starting connection(mentioned code below) itself it look long time to execute. Invoke method not at all triggering.
`await connection.Start(); `
Can you please share any reference link or sample to implement signalr in web api and send notification to the application site

**Comment by moozzyk** [comment]
You could use `GlobalHost` to do that. Take a look [here](https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server#callfromoutsidehub) for more details.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
