### ISSUE TITLE
 StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.StreamContent

### ISSUE THREAD

**Issue by AwsomeCode** [SignalR/SignalR#4008]
I have multiple signalr server with load balancer in azure. I am trying to connect this servers via c# client. In UWP app its working fine but in xamarin android/ios app I am getting below error at client side. My transport mode is SSE, I tried to debug further I found that on single server everything is working fine but if tired to load balance below error is occurring. So after further debugging I found that on xamarin signalr client is sending every new request using new tcp port.
[0:] StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
Cache-Control: no-cache
Pragma: no-cache
Transfer-Encoding: chunked
Server: Microsoft-IIS/10.0
X-Content-Type-Options: nosniff
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Wed, 13 Sep 2017 12:51:55 GMT
Content-Type: text/html
Expires: -1
}

### Expected  behavior
Signalr should send every request using same tcp port.

### Actual behavior
Signalr should sending every new request using different tcp port.

### Steps to reproduce
User Signalr client on any xamarin app with server side load balancer.

**Comment by moozzyk** [comment]
You need to set the same machine key on each server.

**Comment by AwsomeCode** [comment]
Hi Mozzyk thanks for replay. Can you please tell me what is same machine key? Is it related to Azure?
