### ISSUE TITLE
Works after deployment for a few hours, then stops.

### ISSUE THREAD

**Issue by BadDub** [SignalR/SignalR#4009]
# Issues related to the Asp.NET Core version of SignalR should be filed in the corresponding SignalR repo: https://github.com/aspnet/?utf8=%E2%9C%93&query=Signalr

I have a website that has some siganlR on one page.

### Expected  behavior
SignalR should continue to work.
### Actual behavior
SignalR stops working after a few hours. An APP POOL recycle causes SignalR to start working again. Is there something I can do to find out what is causing the SiganlR to stop working?

**Comment by moozzyk** [comment]
This issue does not contain enough details to tell where the problem is.
