### ISSUE TITLE
SignalR with redis in High concurrency condition

### ISSUE THREAD

**Issue by cgyqu** [SignalR/SignalR#4010]
In High concurrency condition ,I Send 10000 message in about 10s ,in most cases，the client lost  5 ~10 per 1,0000 message.In redis client ,run get SignalRBus,the number  increase 10000,so what causes missing data?
Does Redis  publish/subscribe model  reliable ?

**Comment by moozzyk** [comment]
Were you able to identify why/when the messages were lost? Did you see any reconnects on the client that missed messages?

**Comment by cgyqu** [comment]
Connections Reconnected: 1
 Connections Disconnected: 1
 Connections Current ForeverFrame: 0
 Connections Current LongPolling: 1
 Connections Current ServerSentEvents: 0
 Connections Current WebSockets: 0
 Connections Current: 0
 Connection Messages Received Total: 9998
 Connection Messages Sent Total: 10000
 Connection Messages Received/Sec: 9998
 Connection Messages Sent/Sec: 10000
 Message Bus Messages Received Total: 9998
 Message Bus Messages Received/Sec: 9998
 Scaleout Message Bus Messages Received/Sec: 10001
 Message Bus Messages Published Total: 10001
 Message Bus Messages Published/Sec: 10001
 Message Bus Subscribers Current: 2
 Message Bus Subscribers Total: 6614
 Message Bus Subscribers/Sec: 2

I see in the code that the number of messages sent grows when the message is received,
and the number of messages received grows when response;
As you see,Messages Sent Total equals my send count, and Messages Received Total equals client received count;
but Messages Sent Total not equals Messages Received Total，I reset the counter when begin the test.
I’ve tested this many time,and can't find out the reason.
what do you think of this situation ?

**Comment by cgyqu** [comment]
it's redis cluster problem,If you are not using a script to execute redis, you can't guarantee transaction consistency
