### ISSUE TITLE
empty Messages - last connection loses

### ISSUE THREAD

**Issue by amccool** [SignalR/SignalR#4016]
autofac / signalr 2.2 / asp.net 4.6.1

using the owinstartup to deliver an IObservable<T> to my hub
all good (AFAICT)

However in my JavaScript client I see a issue where:
start 1st client - get no messages (no successful call to my javascript callbacks)
start 2nd client - now the 1st client starts to work, 2nd client gets no messages
start 3rd client - now 1st, 2nd client work, 3rd gets no messages

Here's a message the 2nd client was sent (when it was not working)
`Sending outgoing message. Connection id: 12e1a17f-5f48-4e66-aece-166957d645cf, transport: WebSocketTransport, message: {"C":"d-142AA7E2-B,0|J,0|K,2|E,B3","M":[]}`

then after the 3rd client is connected
2nd client gets this (which does work):

`Sending outgoing message. Connection id: 12e1a17f-5f48-4e66-aece-166957d645cf, transport: WebSocketTransport, message: {"C":"d-142AA7E2-B,0\|J,0\|K,2\|E,B4","M":[{"H":"StreamHub","M":"receiveCallCanceled","A":[{"BaseTime":717006987,"BedIndex":2,"CallIndex":4,"EscalationIndex":5,"CallPlacedUTCTime":"2017-09-20T04:52:12.9831051Z","ServerSentUTCTime":"2017-09-20T04:52:15.4492756Z","FacilityGuid":"11111111-1bad-f00d-1111-111111111111","DialString":"1*111"}]}]}`

It appears that the "M":[] is the reason the client isn't receiving the callbacks.  Whats causing this?

can post autofac Startup.cs as needed

**Comment by moozzyk** [comment]
Is this from the same browser? You might be hitting browser limits.

**Comment by amccool** [comment]
negative - multiple browsers, multipe browser variations.   Same behavior

**Comment by amccool** [comment]
confirmed that the browser is getting a frame for the sent messages.  However its clearing missing the "routing" data to get it to a JS callback.  as shown with the "M":{} in this screen capture.

![missing_js_routing data](https://user-images.githubusercontent.com/191144/30665122-d64b516a-9e04-11e7-8f2c-b76a6304260b.png)

**Comment by amccool** [comment]
linking in the sources and running, I added this at
```
                var rendereddata = Encoding.UTF8.GetString(buffer, 0, data.Count);
                Debug.Assert(! "{}".Equals(rendereddata));
```
https://github.com/SignalR/SignalR/blob/dev/src/Microsoft.AspNet.SignalR.Core/Infrastructure/Connection.cs#L232

and the data always looks good.   Seems like something wrong in the sender-DoWork side?

**Comment by amccool** [comment]
I attempted to do a check of the data actually being sent
https://github.com/SignalR/SignalR/blob/dev/src/Microsoft.AspNet.SignalR.Core/Transports/WebSocketTransport.cs#L167

by adding this:

                        var s = context.State as Microsoft.AspNet.SignalR.Transports.PersistentResponse;
                        if (!s.Messages[0].Array[0].IsCommand)
                        {
                            var dataX = s.Messages[0].Array[0].Value;

                            var bufferX = new byte[dataX.Count];
                            Buffer.BlockCopy(dataX.Array, dataX.Offset, bufferX, 0, dataX.Count);
                            rendereddataX = Encoding.UTF8.GetString(bufferX, 0, dataX.Count);
                            Debug.WriteLine(rendereddataX);
                        }
                    }
                    finally
                    {
                    }

                    context.Transport.JsonSerializer.Serialize(context.State, writer);
                    writer.Flush();

                    var data = writer.Buffer;
                    var buffer = new byte[data.Count];
                    Buffer.BlockCopy(data.Array, data.Offset, buffer, 0, data.Count);
                    rendereddata = Encoding.UTF8.GetString(buffer, 0, data.Count);


What i see is:
rendereddata	`"{\"C\":\"d-3A34E600-B,0|E,0|F,2|G,1\",\"M\":[]}"`	string
rendereddataX	`"{\"H\":\"StreamHub\",\"M\":\"receiveCallPlaced\",\"A\":[{\"BaseTime\":717163573,\"BedIndex\":2,\"CallIndex\":4,\"EscalationIndex\":5,\"CallPlacedStartTimeUtc\":\"2017-09-22T00:21:55.1165821Z\",\"CallTagMessage\":\"\",\"AllTouchAdditionalText\":null,\"AllTouchVendorAlias\":null,\"AllTouchEventName\":null,\"ServerSentUTCTime\":\"2017-09-22T00:21:55.063293Z\",\"FacilityGuid\":\"11111111-1bad-f00d-1111-111111111111\",\"DialString\":\"1*111\"}]}"`	string


Why don't I see the rendereddataX in the "M":  json property ???

**Comment by amccool** [comment]
looks like its the groups.  Previously we had a `subscribe` inbound call that asked to subscribe to particular group.
I changed all `Clients.OthersInGroup.XXX` to `Clients.All.XXX` and magically things are working.   Looks like a bug to me.   The correct message meant for the group is "right", and delivered, buts its payload is empty.

Perhaps the "excluded message logic?" - or are the rats abandoning this ship and swimming to signalr3?

**Comment by kbalint** [comment]
I think I have a similar problem. When trying to send any data to Clients.Group.(x) the first frame is always null: {"C":"d-5A3A6552-B,0|L,0|D,0|M,0|N,5|G,7E|H,12","M":[{"H":"addressHub","M":"AddressAdded","A":[null]}]}

If I repeat the call in a cycle, the first message is always null, and the following are arriving as expected.
@amccool did you have any workaround for not sending all data to .All (that'd not work in production obviously)?

**Comment by amccool** [comment]
We had to change the following items to no longer receive empty messages.

- We had to completely remove DI from the implementation.
- We had to do a `AddToGroup` directly from the client after the connection completed (make sense due to a load balanced environment).

We suspect that the DI setup was the root cause.

**Comment by kbalint** [comment]
thanks, that's interesting, I too use Autofac but have group subscription from the client as well. 
Will try to go without any DI.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
