### ISSUE TITLE
When too many clients connect at the same time the system gets in a malfunctioning state from which it can not recover

### ISSUE THREAD

**Issue by pauldendulk** [SignalR/SignalR#4018]
### Some context
In our environment about 500+ clients have a SignalR connection to our server. This works fine under normal circumstances but if there is a network interruption or a server restart all clients try to reconnect at the same time. The load this generates does not just cause a longer time before all clients reconnect but can cause a malfunctioning state from which it can  not recover. 

### Question
Is there a way to prevent this? Is there a way to 'throttle' the number of the connecting clients server side to prevent this? Are there any other practices you could advice to prevent this? 

### Expected  behavior
When too many clients connect at the same time we expect this to take longer than just a few but they should still connect eventually.

### Actual behavior
When the number of clients is too high we see a initial rise in connected clients but before all clients are connected the clients that were already connected start to fall back to 'reconnect' or 'disconnected'.

### Steps to reproduce
- Run a signalr server. We ran Microsoft.AspNet.SelfHost.Samples on port 8080
- Run crank with 1000 clients and no connection interval:
```
crank /Connections:1000 /Url:http://localhost:8080/signalr /BatchSize:1 /ConnectInterval:0
```
Screenshot of crank output:
![image](https://user-images.githubusercontent.com/963462/30911667-d4ace2b2-a389-11e7-83aa-f25496442b43.png)

**Comment by moozzyk** [comment]
What kinds of errors do you see on the client when it can't reconnect/is disconnected?

**Comment by pauldendulk** [comment]
I logged the errors received on Connection.Error. What I see is mostly this error:
```The client has been inactive since 9/28/2017 4:12:43 PM and it has exceeded the inactivity timeout of 00:00:50. Stopping the connection.```

Some of these:
```Couldn't reconnect within the configured timeout of 00:00:30, disconnecting.```

**Comment by moozzyk** [comment]
I talked to @Tratcher and he suspects threadpool starvation on the server side. He said that initially the pool is small and when needed threads are added to the threadpool but this happens at a quite slow rate (like 1 thread per 0.5 seconds).

**Comment by pauldendulk** [comment]
I will do some further testing on that this week. Can I use ThreadPool.GetAvailableThreads for that or should I use something else?

**Comment by IanYates** [comment]
I set MinThread to a higher value on site startup on purpose.  It wasn't to solve this issue specifically but I can verify it certainly helps with thread pool starvation / slow growth.

ThreadPool.SetMinThreads([workerThreads], [completionPortThreads])

Try call GetMinThreads, store the two out values, and use SetMinThreads to double them.  See if your problem is mitigated...

**Comment by pauldendulk** [comment]
@IanYates Thanks for your suggestion. I tried 5 iterations on a version with and without MinThread set to 1000 but see no signification difference yet. I will do some more testing next week.

**Comment by pauldendulk** [comment]
Our immediate problems are fixed by other optimizations. I will close this now. I will reopen when it becomes relevant again.
