### ISSUE TITLE
Redis: Provide mechanism to recreate connection if it gets in a bad state

### ISSUE THREAD

**Issue by JonCole** [SignalR/SignalR#4019]
### Expected  behavior
If a connection gets into a bad state, there needs to be some way for the system to recover, presumably by recreating the underlying StackExchange.Redis.ConnectionMultiplexer either automatically or by exposing a way for customers to do it from their applications.

### Actual behavior
only rebooting the SignalR server fixes the issue

### Steps to reproduce
None - no known good repro of problem exists.  See https://github.com/StackExchange/StackExchange.Redis/issues/559 for reference

Also, example code given to customers using Redis directly is here: https://gist.github.com/JonCole/925630df72be1351b21440625ff2671f#reconnecting-with-lazyt-pattern

**Comment by moozzyk** [comment]
We should either implement the reconnect pattern or expose the ConnectionMultiplexer so the user can do it on their own (e.g. allow passing a connection multiplexer when registering Redis Scaleout)

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
