### ISSUE TITLE
Potential data race within Client.cs of Crank

### ISSUE THREAD

**Issue by MSIC-HSR** [SignalR/SignalR#4021]
### Expected behavior
No potential data race

### Actual behavior
Potential data race within [Client.cs](https://github.com/SignalR/SignalR/tree/master/src/Microsoft.AspNet.SignalR.Crank/Client.cs) of Crank.

### Steps to reproduce
...

### SignalR / Crank Version
latest master as of 5.10.2017 @ 13:06, latest commit is [799d9bc on Jul 10, 2016](https://github.com/SignalR/SignalR/blob/799d9bc32524066344cb3656e5f28f2fd03ba9b3/src/Microsoft.AspNet.SignalR.Crank/Client.cs)

### Additional Notes
Hello

As part of an evaluation with a new static checker of our research, we think we have probably identified a potential (not necessarily critical and maybe very seldom occurring) data race. (A data race is an unsynchronized concurrent read/write or write/write access on the same variable or array element that has undefined behavior in the programming language, thus possibly considered as a formal issue as instructions could be reordered/optimized.)

One potential data race is located in the file Client.cs on the lines [84](https://github.com/SignalR/SignalR/tree/master/src/Microsoft.AspNet.SignalR.Crank/Client.cs#L84) and [162](https://github.com/SignalR/SignalR/tree/master/src/Microsoft.AspNet.SignalR.Crank/Client.cs#L162) (lines selected for illustration):
```cs
private static async Task Run()
{
    // ...
    while (TestPhase != ControllerEvents.Connect)
    {
        if (TestPhase == ControllerEvents.Abort)
        {
            Console.WriteLine("Test Aborted");
            return;
        }
    
        await Task.Delay(CrankArguments.ConnectionPollIntervalMS);
    }
    // ...
}
// ...
internal static void OnPhaseChanged(ControllerEvents phase)
{
    Debug.Assert(phase != ControllerEvents.None);
    Debug.Assert(phase != ControllerEvents.Sample);

    TestPhase = phase;

    if (!Arguments.IsController)
    {
        Console.WriteLine("Running: {0}", Enum.GetName(typeof(ControllerEvents), phase));
    }
}
```

While it is very unlikely -especially with the use of the `await` keyword and the related context switches,- the compiler or CPU might decide to avoid refreshing the value of `TestPhase` and keep it in a register. As a consequence, the `Run` method might never see the changes issued by the method `OnPhaseChanged`.
One possible fix for this data race is adding the `volatile` modifier to the variable `TestPhase`.

Maybe the constellation is impossible or the issue is very minor (given that Crank is meant for load testing) or unlikely, we just wanted to hint it.

**Comment by moozzyk** [comment]
Thanks for the heads up!

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
