### ISSUE TITLE
Change layout of microsoft.aspnet.signalr.js; microsoft.aspnet.signalr.sample;  

### ISSUE THREAD

**Issue by moozzyk** [SignalR/SignalR#4022]
microsoft.aspnet.signalr.js; microsoft.aspnet.signalr.sample;  were flagged by NuGet as not compatible with [PackageReference](https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html) due to one of the following:

> 1.	Lib without TFM issue: Please update your package so that the assemblies in the packages are available against the framework they target. Currently one or more assemblies in these packages are directly put under the “lib” directory. Please put these assemblies under the right framework folder. i.e. From lib/<Assembly.dll> to lib/<TFM>/<Assembly.dll> 
> 2.	Content issue: Please update your packages so that it has both content (which is only supported with packages.config) and contentFiles (which is supported with PackageReference) by following this [documentation](https://docs.microsoft.com/en-us/nuget/schema/nuspec?#including-content-files) and [blog post](https://blog.nuget.org/20160126/nuget-contentFiles-demystified.html)
> 3.	Install.ps1/Uninstall.ps1 issue: Please update your packages to remove install.ps1 and uninstall.ps1 scripts dependency, instead use msbuild props/ targets to achieve the similar behavior. Follow this documentation to know how to include these msbuild props/ targets into your package.

I think this is because of 2. - these packages contain Content files but do not have the structure as described in the blogpost/documentation.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
