### ISSUE TITLE
SignalR do not start on Android 7, 6 and 5 with latest android webview/chrome version.

### ISSUE THREAD

**Issue by Marcosmemo** [SignalR/SignalR#4026]
Hi, I have an error with the latest version of Android webview(for android 5 and 6) and chrome(for android 7) with my signalR client side, i have an application that runs google maps on the android webview, with that map the application do some tracking to units like ambulances and firebuses

This tracking works with signalR client side, everything was working fine until last update of android webview, since that moment the app is not able to start signalR ($.connection.hub.start()), and gives no error or alert, it just doesn't start.

On ios and web browser still working correctly but in Android is not possible to start the process, if i downgrade my android webview to factory version everything goes on again, but i can not tell our clients to do that. 

Does any one else having trouble with this signalr integration with android webview? 

this is how my hubconfiguration goes

var hubConfiguration = new HubConfiguration
            {
                EnableDetailedErrors =true,
                EnableJSONP = true
            };
            app.Map("/signalr", map =>
            {
                    map.UseCors(Microsoft.Owin.Cors.CorsOptions.AllowAll);
                    map.RunSignalR(hubConfiguration);
            });

this is my client side code

$.connection.hub.url ="https://tracking.iamresponding.com/signalr"

$.connection.hub.start()
                        .done(function () { console.log("connection done")})
                       .fail(function(error){console.log("connection failed : "+error)});

as i said above start function is not responding anything just in android 7, 6 and 5 with the latest update of android webview.

**Comment by moozzyk** [comment]
Check what requests are being send when starting the connection and what are the responses.

**Comment by Marcosmemo** [comment]
my request header just go my version app and an authorization token that we use to autenticate  an user.
The response retrieve an HTML with 3 url's one of them is the Javascript that the map will use, the other one is the CSS and the last one is the map https://maps.googleapis.com/maps/api/js?

checking on chrome inspect on the network conectivity i realized that on the old version of android web view the start conection of signalR is being executed just after the QuotaService.RecordEvent is executed just like this image shows
![image](https://user-images.githubusercontent.com/7934319/31622430-0331a276-b262-11e7-8945-16403b543c5d.png)

But in the newest version is not longer happening.

![image](https://user-images.githubusercontent.com/7934319/31622451-149798cc-b262-11e7-8519-dcf559cfb417.png)


Actually the start and the negotiate part never happens.

**Comment by moozzyk** [comment]
Looks like you will need to dig deeper to understand why the negotiate/connect/start requests are not happening. These requests are used by  SignalR to start the connection and if they are not being sent the connection is just not being started. Looks like this is external to SignalR.

**Comment by Marcosmemo** [comment]
Thank you @moozzyk  i've already started an issue in chronium
https://bugs.chromium.org/p/chromium/issues/detail?id=775158

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
