### ISSUE TITLE
SignalR JS library uses string representation of event listeners, so adding event listeners can overwrite previous listeners, and removing event listeners can remove the wrong one

### ISSUE THREAD

**Issue by icopp** [SignalR/SignalR#4027]
### Expected  behavior

```js
const serverHubProxy = connection.createHubProxy('whateverHubName')

serverHubProxy.on('SomeEventTypeHere', someFunctionHere)
serverHubProxy.off('SomeEventTypeHere', someFunctionHere)
```

This should add and remove the specific `someFunctionHere` object.

### Actual behavior

SignalR will instead add/remove using the **string representation of the function** as a key in a hash, which means that any functions with identical string representations will collide. This breaks lots of use cases, especially anything where listener functions are dynamically created/added/removed/destroyed as part of wrapping a SignalR interface in another API.

See [`jquery.signalR.hubs.js`](https://github.com/SignalR/SignalR/blob/b73cbabe69bc48c4cb8d768148e157712a264ce9/src/Microsoft.AspNet.SignalR.Client.JS/jquery.signalR.hubs.js#L109) line 109, where the callback function itself is used as a key in the hash:

```js
// Map the callback to our encompassed function
callbackMap[eventName][callback] = function (e, data) {
    callback.apply(that, data);
};
```

This implicitly converts the callback to a string representation, which breaks anything that relies on separate but identically defined callbacks.

Instead of a hash, callbackMap[eventName] should be using an array and object equality comparisons on each item when adding and removing listeners.

### Steps to reproduce

See above.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
