### ISSUE TITLE
OnDisconnected Is not called when the server instance dies gracefully 

### ISSUE THREAD

**Issue by AlameerAshraf** [SignalR/SignalR#4028]
### Expected  behavior
In my project we persist the users connection Ids in a database table , every thing is works fine except only one case when the server instance it self goes down the OnDisconnected , Logically can't be called, 
So , we look back at the SignalR documentation for OnDisconnected event handler it sais that this handler executes at the end of signalR connection  and specifically 

> If the server stops running, the client tries to reconnect (re-create the transport connection), and then ends the SignalR connection after the disconnect timeout period. 

### Actual behavior
SignalR connection is end but the OnDisconnected is never called , so i have a problem all the connected users to the application are still in the database ! 
### Steps to reproduce
is there any way to delete the users connection ids . in SignalR handlers ?

**Comment by moozzyk** [comment]
If the client cannot reconnect it will raise the `OnClosed` (C# client) `onDisconnect` (JS client) event on the client side.
