### ISSUE TITLE
serverSendEvents transport not work well in https

### ISSUE THREAD

**Issue by cgyqu** [SignalR/SignalR#4029]
Recently，We launch a website , using signalr with auto transport model.
Our domin supports htts and http .Using the HTTP,everything work very well.
But using https ,sendSendEvent transport connect costs about 10s, so our site doesn't work ,
we have to designated use of longpolling.I can't find out What caused it. Any Suggestion?

**Comment by moozzyk** [comment]
It should work just fine. You need to provide more details otherwise it is not possible to tell what's going on. I would also encourage making sure that websockets transports is being used in most of the cases because it is the most efficient and reliable transport.
