### ISSUE TITLE
0x80004005

### ISSUE THREAD

**Issue by QJesus** [SignalR/SignalR#4030]
I use signalr to send Fingerprint image, about 124,320 bytes. 

主机名:           DESKTOP-S48FPFO
OS 名称:          Microsoft Windows 10 企业版
OS 版本:          10.0.16299 暂缺 Build 16299
OS 制造商:        Microsoft Corporation
OS 配置:          独立工作站
OS 构件类型:      Multiprocessor Free

self host signalR 

``` c#
var signar = WebApp.Start<Startup>($"http://*:8001");

var hubConnection = new HubConnection($"http://127.0.0.1:{SignalRPort}")
{
    // enable client-side logging
    TraceLevel = TraceLevels.All,
    TraceWriter = Console.Out,
};
SfraHubProxy = hubConnection.CreateHubProxy("hwSfraHub");
hubConnection.Start().Wait();

```

```

var proxy = Hardware.SfraHubProxy ;
proxy?.Invoke("ExtractResult", score, message, image);

```

BUT I **ALWAYS** GOT ERROR.

13:53:36.0876889 - 7cba1db5-64f1-4b94-847e-def7fdff8681 - OnError(System.Net.WebSockets.WebSocketException (0x80004005): 发生了内部 WebSocket 错误。有关详细信息，请参见 InnerException (如果存在)。 ---> System.Net.Sockets.SocketException (0x80004005): 远程主机强迫关闭了一个现有的连接。
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Net.WebSockets.WebSocketConnectionStream.<ReadAsync>d__21.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   在 System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__19.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__45.MoveNext()
   在 System.Net.WebSockets.WebSocketBase.ThrowIfConvertibleException(String methodName, Exception exception, CancellationToken cancellationToken, Boolean aborted)
   在 System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__45.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.AspNet.SignalR.WebSockets.WebSocketMessageReader.<ReadMessageAsync>d__3.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.AspNet.SignalR.WebSockets.WebSocketHandler.<ProcessWebSocketRequestAsync>d__25.MoveNext())
13:53:36.1157070 - 7cba1db5-64f1-4b94-847e-def7fdff8681 - WS: OnClose()
13:53:36.1177084 - 7cba1db5-64f1-4b94-847e-def7fdff8681 - ChangeState(Connected, Reconnecting)

**Comment by moozzyk** [comment]
Most likely you have not change the maximum size of an incoming websocket message which by default is set to 64KB. When a message exceeds this limit the connection is closed.

**Comment by QJesus** [comment]
thx
