### ISSUE TITLE
Client does not get Closed event when Transport protocol is Server Sent Events

### ISSUE THREAD

**Issue by alexiordan** [SignalR/SignalR#4031]
Setup: internet source is a 3G dongle via a router.
After connection is established this is what happens if unplug 3G dongle:
If transport protocol is **WebSockets**: **Connection Slow, Reconnecting** and in the end **Closed** events are fired.

If transport protocol is **Server Sent Events**(*): **Connection Slow** event is fired and nothing else.

Is there a technical reason why for SSE Reconnecting and Closed event are never fired ?

(*) This happened in my case due to lack of any more websocket connections available in Azure plan, but I don't think it is necessary relevant.

using Microsoft.AspNet.SignalR.Client 2.2.2

**Comment by moozzyk** [comment]
SSE should behave the same way. I would recommend turning on traces to see what's going on.

**Comment by alexiordan** [comment]
Strange how from the last line of traces, it seems that at protocol level disconnection is sensed in a timely manner, whilst never firing the Closed event.

Traces below:

21:40:17.0934505 - 193f3c3f-9c40-49b2-94fe-051fea31970b - WS Connecting to: ws://xxx.azurewebsites.net/signalr/connect?clientProtocol=1.4&transport=webSockets&connectionData=[{"Name":"updater"}]&connectionToken=CfDJ8PFWga%2BIraVEoZwjGcudnx2WWg6hRf1cYdOFMwcIKl7mD%2F12W6ilO%2F5gVEdayA%2FFHc9%2F%2BU5aXoZfuXs%2F3PK%2FR9X9tRRTBVKGS9rvwx7CkWgnfMWsT3os%2FePx%2BEfVjIhNnbv1%2F6h8Dt
21:40:28.7776556 - 193f3c3f-9c40-49b2-94fe-051fea31970b - Auto: Failed to connect to using transport webSockets. System.Exception: Service unavailable (503). (Exception from HRESULT: 0x801901F7)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SignalR.Client.Transports.WebSocketTransport.<OpenWebSocket>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SignalR.Client.Transports.WebSocketTransport.<StartWebSocket>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SignalR.Client.Transports.WebSocketTransport.<Start>d__14.MoveNext()
21:40:29.2230013 - 193f3c3f-9c40-49b2-94fe-051fea31970b - SSE: GET http://xxx.azurewebsites.net/signalr/connect?clientProtocol=1.4&transport=serverSentEvents&connectionData=[{"Name":"updater"}]&connectionToken=CfDJ8PFWga%2BIraVEoZwjGcudnx2WWg6hRf1cYdOFMwcIKl7mD%2F12W6ilO%2F5gVEdayA%2FFHc9%2F%2BU5aXoZfuXs%2F3PK%2FR9X9tRRTBVKGS9rvwx7CkWgnfMWsT3os%2FePx%2BEfVjIhNnbv1%2F6h8DttGaO3Q%2B%2FGhsDA2wYGocf1e8VcSNIUNzQlW
21:40:29.5528809 - 193f3c3f-9c40-49b2-94fe-051fea31970b - SSE: OnMessage(Data: initialized)
21:40:29.5664064 - 193f3c3f-9c40-49b2-94fe-051fea31970b - SSE: OnMessage(Data: {"C":"d-F482C92E-Z,0|a,0|b,1","S":1,"M":[]})
21:40:29.8635105 - 193f3c3f-9c40-49b2-94fe-051fea31970b - SSE: OnMessage(Data: {"C":"d-F482C92E-Z,0|a,0|b,2|c,0","G":"CfDJ8PFWga+IraVEoZwjGcudnx2wom0o6VSInPRZhDUz+mu+gD01YHJOFc5CcohWmQuH7iKb4IcMZZNweJqzEE8SBJ5ocEtniq1c3npU0Uhb8ap7AiXJ9S4cJmk5Y3lU77zG+oJJFMxrWCWNk5e9+GHZZbVvmxIAl5uR4QgVj/8HwyZvhqdHj6KScNMfOebqabpdr3Ai/Qq8cvEu4GRKxnRaPOMAJFzB+J8nwhoYfidXGsq8go1fshw5XgFATBX1iub/4FcBKP0k3ygwf2NtxI/YmUc=","M":[]})
21:40:30.4274743 - 193f3c3f-9c40-49b2-94fe-051fea31970b - ChangeState(Connecting, Connected)
21:40:30.8265254 - 193f3c3f-9c40-49b2-94fe-051fea31970b - OnMessage({"I":"0"})
21:40:31.0530636 - 193f3c3f-9c40-49b2-94fe-051fea31970b - OnMessage({"I":"1"})
21:40:32.2022707 - 193f3c3f-9c40-49b2-94fe-051fea31970b - SSE: OnMessage(Data: {})
21:40:35.2019941 - 193f3c3f-9c40-49b2-94fe-051fea31970b - SSE: OnMessage(Data: {})
21:40:38.2022404 - 193f3c3f-9c40-49b2-94fe-051fea31970b - SSE: OnMessage(Data: {})
21:40:42.7152065 - 193f3c3f-9c40-49b2-94fe-051fea31970b - Connection Timeout Warning : Notifying user
21:40:42.7309497 - 193f3c3f-9c40-49b2-94fe-051fea31970b - OnConnectionSlow
21:40:44.7160375 - 193f3c3f-9c40-49b2-94fe-051fea31970b - Connection Timed-out : Transport Lost Connection

**Comment by moozzyk** [comment]
I think the issue here might be that sometimes it may take quite a long time for the OS to report that the network is not working and forcibly close outstanding TCP/IP connections. If you look at the code you will see that `HeartBeatMonitor` [calls into transport](https://github.com/SignalR/SignalR/blob/1fba14fa3437e24c204dfaf8a18db3fce8acad3c/src/Microsoft.AspNet.SignalR.Client/HeartBeatMonitor.cs#L113) telling it that the connection seems to be lost. `ServerSentEvents` transport is in this case just [aborting](https://github.com/SignalR/SignalR/blob/dev/src/Microsoft.AspNet.SignalR.Client/Transports/ServerSentEventsTransport.cs#L209) the existing EventSource HTTP request which should result in [raising](https://github.com/SignalR/SignalR/blob/dev/src/Microsoft.AspNet.SignalR.Client/Transports/ServerSentEventsTransport.cs#L173) the `eventSource.Closed` event. I am not sure how long you waited but I think the event is not raised and therefore the client is not trying to reconnect or raise the Closed event. WebSockets have an internal mechanism (ping/pong) which can be used to detect failed connections.

Did you change timeouts in anyway?

**Comment by alexiordan** [comment]
1. I waited for 3 minutes and no event fired. I aborted the client at 21:44:00.
2. I have changed the timeouts in  following way:
```
 transports.DisconnectTimeout = TimeSpan.FromSeconds(9);
 transports.KeepAlive = TimeSpan.FromSeconds(3);
```
I'm didn't set the TransportConnectionTimeout, since from documentation seemed to only be used for long polling. However I waited 3 minutes to cover the default 110 s of TransportConnectionTimeout.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Comment by satish2832** [comment]
### any update on this issue ?
