### ISSUE TITLE
SignalR reconnect memory leak

### ISSUE THREAD

**Issue by zonneryx** [SignalR/SignalR#4032]
After quick pool recycle/restart, user can't reconnect to hub. SignalR try to reconnect, but always gets "Websocket closed" error.  If user refresh browser it's be a normal.
Besides, that create a huge memory leak.
How can I fix it?

Version 2.2.1.

![image](https://user-images.githubusercontent.com/15606305/31987488-a3fc4350-b974-11e7-82ae-99ef63a4a1fc.png)

![image](https://user-images.githubusercontent.com/15606305/31987306-1322f162-b974-11e7-9b85-f8cb87cfa794.png)

**Comment by mraj2508** [comment]
I am also experiencing the similar issue. Do we have an update about how to fix this issue?

**Comment by zonneryx** [comment]
@mraj2508 The problem was in exception that has been throw at reconnect.
We used connections table with connectionid primary key and after reconnect we trying add connection with same primary key to base.
**Unhandled exception throwed on connect/reconnect do memory leak**. I don't know why, but this is.
