### ISSUE TITLE
There is no Logo for SignalR

### ISSUE THREAD

**Issue by Nepomuceno** [SignalR/SignalR#4033]
### Expected  behavior
To have a logo

### Actual behavior
No logo present

### Steps to reproduce
Try to get SignalR logo for your powerpoint at the last minute ;)

**Comment by v-karbovnichy** [comment]
Actually it has, you need to search 😄 
http://lmgtfy.com/?t=i&q=SignalR+logo

**Comment by anpetral-msft** [comment]
Is there an official image from the team that can be used?
