### ISSUE TITLE
Error: Client isn't compatible with the server

### ISSUE THREAD

**Issue by ibrahimyilmaz7** [SignalR/SignalR#4035]
I'm getting this error:
> Error: You are using a version of the client that isn't compatible with the server. Client version 1.5, server version 1.4

Any suggestion for resolving this error?

**Here is my package diagram:**

![signalr](https://user-images.githubusercontent.com/5227444/32480774-7307cd5a-c3a1-11e7-8a43-c2885b60ec5f.PNG)

**Comment by moozzyk** [comment]
The protocolVersion on the server side was updated to 1.5 in 2.2.0 so you seem to be using an older version than that.

**Comment by ibrahimyilmaz7** [comment]
How can i update protocolVersion? I couldn't figure out how to change it. 
Thanks for help.

**Comment by moozzyk** [comment]
You cannot change that. What I am saying is that you seem to have an older package somewhere. Double check all your references and make sure you are not copying any SignalR dlls from random places. Clean your project and nuget cache (`nuget locals -clear all`). If nothing works post a *minimal* repro as a github repo.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
