### ISSUE TITLE
How to send message from outside of HubContext (SignalR Core)

### ISSUE THREAD

**Issue by zdeneksejcek** [SignalR/SignalR#4037]
Hi,

in my situation, I need to send message to selected clients every couple of seconds, so I was thinking of using Timer. Problem is how to get instance of HubContext in SignalR Core version, there seems to be no GlobalHost or ConnectionManager available.

Any thoughts?

**Comment by zdeneksejcek** [comment]
I just found out that injecting simple IHubContext<THub> works, not sure about Hub lifecycle, which is supposed to be transient, but for my singleton Timer it will exist for ever.

Is this right?

**Comment by moozzyk** [comment]
When you use IHubContext hubs are not created and IHubContext is already a singleton.

As a side note - for issues related to the ASP.NET Core version of SignalR use this repo: https://github.com/aspnet/SignalR
