### ISSUE TITLE
Adding SSL on SignalR

### ISSUE THREAD

**Issue by hadeef** [SignalR/SignalR#4040]
Is there any way to add ssl certificate to SignalR on localhost?

**Comment by hadeef** [comment]
I have an application on MVC5 which needs interaction by client side desktop application using SignalR. The issue I have is When switching to SSL on MVC application, chrome identifies SignalR as Not Secure.  Based on latest tightened rules by chrome on SSL, my questions is:

How can I make chrome to accept my SignalR on localhost as  secure using any self signed certificate or other third party certificate?

**Comment by hadeef** [comment]
How can I make chrome to accept my SignalR on localhost as secure using any self signed certificate or other third party certificate?

**Comment by zhujinhu21** [comment]
@hadeef i want to know that ,how did you solve it

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
