### ISSUE TITLE
.net 4.6.1 compatiblity

### ISSUE THREAD

**Issue by abhissha** [SignalR/SignalR#4041]
After upgrading all our projects to target 4.6.1 from 4.5, signalr 2 stopped working. We are not getting any server error, when we run the app we see "net::ERR_CONNECTION_RESET " in the network traffic under the browser console. 
Could you help us find where we should be looking to troubleshoot the issue?

**Comment by ralsu091** [comment]
turn on logging on the server and the client.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
