### ISSUE TITLE
Upgrade Newtonsoft.JSON to 10.0 and Signalr 2.2.2 stops loading

### ISSUE THREAD

**Issue by adamstewart1980** [SignalR/SignalR#4042]
We recently upgraded our project to Newtonsoft.JSON version 10.0 and our site stopped working, this turns out to be a conflict with SignalR 2.2.2

[FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)]  [FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)]    Microsoft.AspNet.SignalR.DefaultDependencyResolver.RegisterDefaultServices() +0    Microsoft.AspNet.SignalR.DefaultDependencyResolver..ctor() +116    Microsoft.AspNet.SignalR.GlobalHost.<.cctor>b__0() +31    System.Lazy`1.CreateValue() +737    System.Lazy`1.LazyInitValue() +431    Microsoft.AspNet.SignalR.GlobalHost.get_DependencyResolver() +62    Owin.OwinExtensions.UseSignalRMiddleware(IAppBuilder builder, Object[] args) +174    Owin.<>c__DisplayClass1.<MapSignalR>b__0(IAppBuilder subApp) +71    Owin.MapExtensions.Map(IAppBuilder app, PathString pathMatch, Action`1 configuration) +210    Owin.MapExtensions.Map(IAppBuilder app, String pathMatch, Action`1 configuration) +131    Owin.OwinExtensions.MapSignalR(IAppBuilder builder) +52

**Comment by moozzyk** [comment]
You need a binding redirect in the config.
