### ISSUE TITLE
Is it not recommended to await Clients.Caller on events?

### ISSUE THREAD

**Issue by yaananth** [SignalR/SignalR#4043]
See this issue https://github.com/SignalR/SignalR/issues/3245 for some context on why we mikght have to do this.

We also did this to ensure we get latest events back.

Normal:
```
public override Task OnReconnected()
{
    return Clients.Caller.ensureReconnected();
}
```
Problematic code:
Is it not recommended to have, something like:

```
public override async Task OnConnected()
{
     await base.OnConnected();
     await Clients.Caller.someMethodHere();
}
```

We have seen time being spent on await for  Clients.Caller for around 10-20 seconds.
Any one has any insight on this? Is this not recommended pattern?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
