### ISSUE TITLE
Signalr client in winform start().await() very slow.

### ISSUE THREAD

**Issue by StevenXuxl** [SignalR/SignalR#4046]
I use 2.1.2.0 version.

I try to connect and start like this:

                _hubConnection = new HubConnection(url);
                _hubProxy = _hubConnection.CreateHubProxy("NotificationHub");
                _hubProxy.On("handleMessage", msg => {});
                _hubConnection.Start().Wait();

but it was so slow when i run the app in first time.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
