### ISSUE TITLE
SignalR Subscriber client(.NET/Java Script) connected but not received message after few minutes  

### ISSUE THREAD

**Issue by msinha53** [SignalR/SignalR#4048]
Getting this type of issue on some machines.
Issue Details:
SignalR server deployed on Windows Server 2012. 
When client subscriber the topic and wait for data & Publisher client published data then subscriber received data.
Subscriber idle some time(5-10 minutes).
Again Publisher Client start to published data but didn't received at subscriber client side.    
Subscriber client already connected but unable to received data.
I have verified SignalR trace on client side and server side but not any issue detected.
If subscriber client rejoin the topic then able to received data.
I think some how topic released from groups but we are unable to find out the root cause.
Already verified IIS Logs & Event viewer logs but didn't found any issue.

Please help us..

**Comment by Pokoto** [comment]
I am experiencing the same issue with version 2.2.2

- I have been running 2.2.1 smoothly for more than a year on multiple Windows Server 2012 machines
- simply upgraded the client and server to 2.2.2  - default settings with no tweaks.
- using the Redis backplane (RedisLabs redis_version 2.8.12)
- randomly, after 5-25 minutes idle js clients stop receiving messages BUT a) can still send messages over the connection, b) after sending them the connection is aborted and a reconnect triggered, eventually the client starts to receive messages again
- tried with multiple browser tabs connected to different servers BUT subscribed to the same topic, they stop receiving messages at the same time
- the issue affects WebSockets but haven't tried with other protocols yet
- can't repro on the dev machine, is working fine (W10/VS2015/IISEXPRESS)

had to rollback to 2.2.1 as it's failing silently on both client and server...

Any Idea? :)

**Comment by davidfowl** [comment]
Turn client side logging on. That should provide more details.

**Comment by msinha53** [comment]
I have already enable SignalR trace log on client side and server side but no any issue detected. 
For connection testing, i have created KeepAlive function under Hub and client called KeepAlive on every 1 minute interval time and connection is working fine.
Publisher is publishing message on 5 minute interval time but subscriber unable to received.
If i have started new instance of Subscriber and join the topic then received 1 time published message but didn't received next message.
I think some how topic expired/removed from Group.
Any idea Group have any expiration time???

**Comment by MarcoCestari** [comment]
Same issue described by @Pokoto here.
Seems to occurs only with remote connections.

**Comment by VladimirMakaev** [comment]
We are experiencing the same behavior. We are not using groups though just sending messages by connection id. At some point the messages are not being delivered although the TransportHearbeat is still keeping connection active (we have extended the default implementation with a bunch of additional logs)

Downgrading to 2.2.1 helps but we'd really want this to be fixed as 2.2.2 contains important fixes we'd like to keep. 

Important part of the setup is Redis backplane as it works just fine without it.

**Comment by cgyqu** [comment]
We have the same problem,the client still poll message,but can't receive any message from server.
And ping service work well.Our log show the request processed.I have no idea about solving this problem.

**Comment by FantasticFourDevelopments** [comment]
We are seeing this issue with 2.2.2 as well in our multi-server Azure environment using ServiceBus as the backplane. 

It appears to be completely sporadic as we have seen the issue manifest both after a short period (10-15 minutes) and also only after a period of hours. 

As others have mentioned there is no indication of an issue in the trace log and the keep-alive messages are logged as expected.

**Comment by msinha53** [comment]
We are also facing this issue with 2.2.2.

**Comment by anurse** [comment]
We recently fixed a similar issue (https://github.com/SignalR/SignalR/issues/4121), so it's possible this is resolved now. Can you try updating to 2.3.0 (which has this fix) and see if that resolves the issue? If not, collecting some traces from the server (using the docs here: https://docs.microsoft.com/en-us/aspnet/signalr/overview/testing-and-debugging/enabling-signalr-tracing) would help.

**Comment by MarcoCestari** [comment]
We're running 2.2.3 for the past five days and the issue seems to be fixed.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
