### ISSUE TITLE
connectionData is stripped from negotiate when starting a hub connection in Xamarin Android

### ISSUE THREAD

**Issue by scott-m-snyder** [SignalR/SignalR#4049]
I'm trying to connect to my SignalR hub using a PCL.  It works fine within a C# Winforms project however when calling from within a Xamarin Android project, I lose the connectionData. Here are the messages intercepted with Wireshark:

Works from: C# WinForms project:
GET /ScottSignalR/signalr/signalr/negotiate?clientProtocol=1.4&connectionData=[%7B%22Name%22:%22scottHub%22%7D]

Not working from a Xamarin Android project: (connectionData is missing the hub name):
GET /ScottSignalR/signalr/signalr/negotiate?clientProtocol=1.4&connectionData=[%7B%7D] HTTP/1.1\r\n

Without the hub name, I receive a 500 internal error.

**Comment by davidfowl** [comment]
This should be filed on github.com/SignalR/SignalR. This repository is for the ASP.NET Core version of SignalR.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
