### ISSUE TITLE
SignalR (SSE) keeps reconnecting

### ISSUE THREAD

**Issue by cubitus81** [SignalR/SignalR#4050]
I'm using SignalR version 2.2.1 with .NET 4.5.2.

I noticed that when IIS is recycled, SignalR keeps reconnecting (between 15-45 minutes). This doesn't happen every time. No issue with IIS recycle, the app was recycled normally.

 Please see below for client log.
[client.txt](https://github.com/SignalR/SignalR/files/1527440/client.txt)

Below is a snippet of the code I used to connect to SignalRChannelConsumer (attached).
[SignalRCode.txt](https://github.com/SignalR/SignalR/files/1527445/SignalRCode.txt)

'
      m_Consumer = new SignalRChannelConsumer(Name, m_ReceiverMethodName, m_ServerURI, m_OnMessageReceivedEventHandler, m_LogHandler, this);
                    // start
                    m_Consumer.Start().Wait();
'

On the server, I set the following SignalR configurations

   GlobalHost.Configuration.DisconnectTimeout= 60;
   GlobalHost.Configuration.KeepAlive = 20;
   GlobalHost.Configuration.DefaultMessageBufferSize = 10000; 

Would someone be able to help me with this issue?

Thank you.

**Comment by bishrtabbaa** [comment]
I notice the same issue in my environment and have a similar configuration.  Is there continued support for SignalR on the .NET Framework or have all efforts shifted to .NET Core?  Please advise.  Thanks.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
