### ISSUE TITLE
.Net SignalR 2.2.2 WebSocketException

### ISSUE THREAD

**Issue by Steve0212a** [SignalR/SignalR#4052]
I am attempting to provide a constantly connected .NET SignalR client.  If the client loses connection, it will call Start() again per this article:  https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/handling-connection-lifetime-events#how-to-continuously-reconnect.  The problem is, the client just hangs and never reconnects.  I have turned on tracing on the client and the server.  The server is throwing an exception.

### Expected  behavior
the client should reconnect

### Actual behavior
unhandled exception, failure to reconnect, client just hangs on call to Start()

### Steps to reproduce
1. Host a SignalR Server in a Windows Service (code is below)
2. Connect a client to the server.  The client is using the nuget package Microsoft.AspNet.SignalR.Client v2.2.2.
3. Shut down the SignalR Server service to simulate a disaster
     a. At this point, the client goes into reconnecting mode.  If the Windows service is restarted while the client is "reconnecting", all is good and it reconnects.
     b. Leave the service down long enough for the client to go to disconnected.
4. Per the article above, I am listening for the Closed event on the connection in the client and call Start() again.
5. I then restart my event service and it should reconnect, but does not.

**Here is the client trace log:**
          20:18:19.2200013 - null - ChangeState(Disconnected, Connecting)
          20:18:19.7973700 - 11609944-3ec6-4b67-a89d-58f77aa6358a - WS Connecting to: ws://10.0.0.31:8096/signalr/connect?clientProtocol=1.4&transport=webSockets&connectionData=[{"Name":"UtilityHub"}]&connectionToken=AQAAANCMnd8BFdERjHoAwE%2FCl%2BsBAAAAJReMEbEw8kiS2iLgRsnYIgAAAAACAAAAAAAQZgAAAAEAACAAAAAA7sjyYq9lGA0TRYO97d3Bax60COC63mYzR%2F7%2BxWEqZgAAAAAOgAAAAAIAACAAAAB90c%2BI3gfpMkDYbOw4Sqx4udvEDrHtqsxHfKaAcZrx7TAAAACCaMQP5jekmivQ5CGNv%2BSKUAH69EVU7phnVf1l76QId61ha9h9H%2Be%2Fr3y8LXgZO5ZAAAAAPxdwl7jNZGt%2FfSvw6FLroC2ZbnDUYL7GDTf3Fab%2BqjzAeM4fGbCluKE3Vvmten7iPreedNlBl4Ityk%2B4PHI8yg%3D%3D
          20:18:24.8059902 - 11609944-3ec6-4b67-a89d-58f77aa6358a - Auto: Failed to connect to using transport webSockets. System.TimeoutException: Transport timed out trying to connect
          20:18:24.8109885 - 11609944-3ec6-4b67-a89d-58f77aa6358a - SSE: GET http://10.0.0.31:8096/signalr/connect?clientProtocol=1.4&transport=serverSentEvents&connectionData=[{"Name":"UtilityHub"}]&connectionToken=AQAAANCMnd8BFdERjHoAwE%2FCl%2BsBAAAAJReMEbEw8kiS2iLgRsnYIgAAAAACAAAAAAAQZgAAAAEAACAAAAAA7sjyYq9lGA0TRYO97d3Bax60COC63mYzR%2F7%2BxWEqZgAAAAAOgAAAAAIAACAAAAB90c%2BI3gfpMkDYbOw4Sqx4udvEDrHtqsxHfKaAcZrx7TAAAACCaMQP5jekmivQ5CGNv%2BSKUAH69EVU7phnVf1l76QId61ha9h9H%2Be%2Fr3y8LXgZO5ZAAAAAPxdwl7jNZGt%2FfSvw6FLroC2ZbnDUYL7GDTf3Fab%2BqjzAeM4fGbCluKE3Vvmten7iPreedNlBl4Ityk%2B4PHI8yg%3D%3D
          20:18:30.3381713 - 11609944-3ec6-4b67-a89d-58f77aa6358a - Auto: Failed to connect to using transport serverSentEvents. System.TimeoutException: Transport timed out trying to connect
          20:18:30.3431646 - 11609944-3ec6-4b67-a89d-58f77aa6358a - LP Connect: http://10.0.0.31:8096/signalr/connect?clientProtocol=1.4&transport=longPolling&connectionData=[{"Name":"UtilityHub"}]&connectionToken=AQAAANCMnd8BFdERjHoAwE%2FCl%2BsBAAAAJReMEbEw8kiS2iLgRsnYIgAAAAACAAAAAAAQZgAAAAEAACAAAAAA7sjyYq9lGA0TRYO97d3Bax60COC63mYzR%2F7%2BxWEqZgAAAAAOgAAAAAIAACAAAAB90c%2BI3gfpMkDYbOw4Sqx4udvEDrHtqsxHfKaAcZrx7TAAAACCaMQP5jekmivQ5CGNv%2BSKUAH69EVU7phnVf1l76QId61ha9h9H%2Be%2Fr3y8LXgZO5ZAAAAAPxdwl7jNZGt%2FfSvw6FLroC2ZbnDUYL7GDTf3Fab%2BqjzAeM4fGbCluKE3Vvmten7iPreedNlBl4Ityk%2B4PHI8yg%3D%3D
          20:18:30.4092980 - 11609944-3ec6-4b67-a89d-58f77aa6358a - LP: OnMessage({"C":"d-B44FE45F-B,0|C,0|D,3","S":1,"M":[]})
          20:18:30.4132920 - 11609944-3ec6-4b67-a89d-58f77aa6358a - LP Poll: http://10.0.0.31:8096/signalr/poll?clientProtocol=1.4&transport=longPolling&connectionData=[{"Name":"UtilityHub"}]&connectionToken=AQAAANCMnd8BFdERjHoAwE%2FCl%2BsBAAAAJReMEbEw8kiS2iLgRsnYIgAAAAACAAAAAAAQZgAAAAEAACAAAAAA7sjyYq9lGA0TRYO97d3Bax60COC63mYzR%2F7%2BxWEqZgAAAAAOgAAAAAIAACAAAAB90c%2BI3gfpMkDYbOw4Sqx4udvEDrHtqsxHfKaAcZrx7TAAAACCaMQP5jekmivQ5CGNv%2BSKUAH69EVU7phnVf1l76QId61ha9h9H%2Be%2Fr3y8LXgZO5ZAAAAAPxdwl7jNZGt%2FfSvw6FLroC2ZbnDUYL7GDTf3Fab%2BqjzAeM4fGbCluKE3Vvmten7iPreedNlBl4Ityk%2B4PHI8yg%3D%3D&messageId=d-B44FE45F-B%2C0%7CC%2C0%7CD%2C3
          20:20:24.9528167 - 11609944-3ec6-4b67-a89d-58f77aa6358a - LP: OnMessage({"C":"d-B44FE45F-B,0|C,0|D,3","M":[]})
          20:20:24.9568168 - 11609944-3ec6-4b67-a89d-58f77aa6358a - LP Poll: http://10.0.0.31:8096/signalr/poll?clientProtocol=1.4&transport=longPolling&connectionData=[{"Name":"UtilityHub"}]&connectionToken=AQAAANCMnd8BFdERjHoAwE%2FCl%2BsBAAAAJReMEbEw8kiS2iLgRsnYIgAAAAACAAAAAAAQZgAAAAEAACAAAAAA7sjyYq9lGA0TRYO97d3Bax60COC63mYzR%2F7%2BxWEqZgAAAAAOgAAAAAIAACAAAAB90c%2BI3gfpMkDYbOw4Sqx4udvEDrHtqsxHfKaAcZrx7TAAAACCaMQP5jekmivQ5CGNv%2BSKUAH69EVU7phnVf1l76QId61ha9h9H%2Be%2Fr3y8LXgZO5ZAAAAAPxdwl7jNZGt%2FfSvw6FLroC2ZbnDUYL7GDTf3Fab%2BqjzAeM4fGbCluKE3Vvmten7iPreedNlBl4Ityk%2B4PHI8yg%3D%3D&messageId=d-B44FE45F-B%2C0%7CC%2C0%7CD%2C3
          20:22:14.9942673 - 11609944-3ec6-4b67-a89d-58f77aa6358a - LP: OnMessage({"C":"d-B44FE45F-B,0|C,0|D,3","M":[]})
          20:22:14.9972659 - 11609944-3ec6-4b67-a89d-58f77aa6358a - LP Poll: http://10.0.0.31:8096/signalr/poll?clientProtocol=1.4&transport=longPolling&connectionData=[{"Name":"UtilityHub"}]&connectionToken=AQAAANCMnd8BFdERjHoAwE%2FCl%2BsBAAAAJReMEbEw8kiS2iLgRsnYIgAAAAACAAAAAAAQZgAAAAEAACAAAAAA7sjyYq9lGA0TRYO97d3Bax60COC63mYzR%2F7%2BxWEqZgAAAAAOgAAAAAIAACAAAAB90c%2BI3gfpMkDYbOw4Sqx4udvEDrHtqsxHfKaAcZrx7TAAAACCaMQP5jekmivQ5CGNv%2BSKUAH69EVU7phnVf1l76QId61ha9h9H%2Be%2Fr3y8LXgZO5ZAAAAAPxdwl7jNZGt%2FfSvw6FLroC2ZbnDUYL7GDTf3Fab%2BqjzAeM4fGbCluKE3Vvmten7iPreedNlBl4Ityk%2B4PHI8yg%3D%3D&messageId=d-B44FE45F-B%2C0%7CC%2C0%7CD%2C3

**Here is the server trace log at that time:**
		SignalR.Transports.TransportHeartBeat Information: 0 : Connection 11609944-3ec6-4b67-a89d-58f77aa6358a is New.
		SignalR.Transports.WebSocketTransport Verbose: 0 : Sending outgoing message. Connection id: 11609944-3ec6-4b67-a89d-58f77aa6358a, transport: WebSocketTransport, message: {"C":"d-B44FE45F-B,0|C,0|D,1","S":1,"M":[]}
		SignalR.Transports.WebSocketTransport Error: 0 : OnError(11609944-3ec6-4b67-a89d-58f77aa6358a, System.Net.WebSockets.WebSocketException (0x80004005): An internal WebSocket error occurred. Please see the innerException, if present, for more details.  ---> System.Net.HttpListenerException (0x80004005): The I/O operation has been aborted because of either a thread exit or an application request
		   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		   at System.Net.WebSockets.WebSocketHttpListenerDuplexStream.<ReadAsyncCore>d__30.MoveNext()
		--- End of stack trace from previous location where exception was thrown ---
		   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
		   at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__19.MoveNext()
		--- End of stack trace from previous location where exception was thrown ---
		   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__45.MoveNext()
		   at System.Net.WebSockets.WebSocketBase.ThrowIfConvertibleException(String methodName, Exception exception, CancellationToken cancellationToken, Boolean aborted)
		   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__45.MoveNext()
		--- End of stack trace from previous location where exception was thrown ---
		   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		   at Microsoft.AspNet.SignalR.WebSockets.WebSocketMessageReader.<ReadMessageAsync>d__3.MoveNext()
		--- End of stack trace from previous location where exception was thrown ---
		   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
		   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		   at Microsoft.AspNet.SignalR.WebSockets.WebSocketHandler.<ProcessWebSocketRequestAsync>d__25.MoveNext())
		SignalR.Transports.WebSocketTransport Information: 0 : CloseSocket(11609944-3ec6-4b67-a89d-58f77aa6358a)
		SignalR.Transports.TransportHeartBeat Verbose: 0 : Connection 11609944-3ec6-4b67-a89d-58f77aa6358a exists. Closing previous connection.
		SignalR.Transports.WebSocketTransport Information: 0 : End(11609944-3ec6-4b67-a89d-58f77aa6358a)
		SignalR.Transports.WebSocketTransport Verbose: 0 : Cancel(11609944-3ec6-4b67-a89d-58f77aa6358a)
		SignalR.Transports.ServerSentEventsTransport Verbose: 0 : Sending outgoing message. Connection id: 11609944-3ec6-4b67-a89d-58f77aa6358a, transport: ServerSentEventsTransport, message: data: {"C":"d-B44FE45F-B,0|C,0|D,2","S":1,"M":[]}
		SignalR.Transports.WebSocketTransport Verbose: 0 : DrainWrites(11609944-3ec6-4b67-a89d-58f77aa6358a)
		SignalR.Transports.WebSocketTransport Information: 0 : CompleteRequest (11609944-3ec6-4b67-a89d-58f77aa6358a)

**Here is my server:**
		public class SignalRServer : IDisposable
	    {
	        static IDisposable signalR;
	        
	        public void Start(string url)
	        {
	            // make sure contracts is loaded
	            AppDomain.CurrentDomain.Load(typeof(UtilityHub).Assembly.FullName);

	            // start the server

	            // build the web app
	            signalR = WebApp.Start(url, (builder =>
	            {
	                builder.UseCors(CorsOptions.AllowAll);
	                var hubConfiguration = new HubConfiguration();
	                hubConfiguration.EnableDetailedErrors = true;
	                builder.MapSignalR(hubConfiguration);
	            }));
	        }

	        public void Dispose()
	        {
	            signalR?.Dispose();
	        }
	    }

As a side note, if I new up a new HubConnection upon receiving the Closed Event, it will successfully connect the new client, so I believe this to be an issue with re-using the same connection and calling start again.  However, I prefer not to do that because I then have to reconnect On handlers.  I can do that if there is no other way around, but per the article, what I am doing should work.

Any help would be appreciated.

Thanks.

**Comment by Steve0212a** [comment]
3 weeks and no comments?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
