### ISSUE TITLE
Self hosted server hubconnection.Start().Wait() throwing error in Windows server 2012

### ISSUE THREAD

**Issue by klpatel** [SignalR/SignalR#4053]
# Issues related to the Asp.NET Core version of SignalR 2.1.1 / 2.2.2 
Recently as part of infrastructure upgrade I have moved Self hosted signalr server to windows server 2012 which was working since one year from now in windows 2008 server.
The signalR server is hosted as console application which is picking messages from MSMQ and broadcasting to ASP.NET MVC web application. 
The code below creates and starts hubConnection and use it for sending messages to all clients.
                var hubConnection = new HubConnection("https://subdomain1.server1.com/"); //Actual url is read from Appsettings
                var reportStatusHub = hubConnection.CreateHubProxy("ReportStatusHub");
                hubConnection.Start().Wait(); // Throwing Error
The port 8989 is configured using => netsh add urlacl usr=https://*:8989
SSL is also configured using    => netsh add sslcert  for port 8989
inbound and outbound rules are created in firewall to allow communication to/from  port 8989
The hub is tarted and other applications can start connection and send messages to sever, but server can't send message to client.  it throws error at hubConnection.Start().Wait();

I have tried for hours during this week to figure out the issue in windows server 2012 but couldn't troubleshoot.

### Expected  behavior
Signalr self hosted server should allow start hub connection from within the server. 
### Actual behavior
Throws error at hubConnection.Start().Wait(); 

StartHub Error : One or more errors occurred.::: Stack:   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Vortex.FEC.Notification.ReportStatusClientService.GetHub():::InnerException : An error occurred while sending the request.:::

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
