### ISSUE TITLE
Please clarify how https://github.com/aspnet/SignalR relate to this project?

### ISSUE THREAD

**Issue by Bartolomeus-649** [SignalR/SignalR#4055]
There are a lot of sites/pages claiming/appearing to be "**the**" SignalR page.

I suggest there should be _one and only one_  authoritative page on SignalR, no matter which version, platform or whatever.

That page/site could point to other sites if there's a need for it.

Today when I searched for SignalR I found there pages

1. ASP.NET: Learn About ASP.NET SignalR (https://www.asp.net/signalr)
This site contains links to pages from 2014 on docs.microsoft.com/en-us/aspnet/signalr, there are also links to example code from 2014 on code.msdn.microsoft.com. Documentation from 2014, is this really what people should read to understand and use SignalR the correct way?

2. signalr.net: ASP.NET SignalR (http://signalr.net/)
This site links to documentation from 2013 on github.com/SignalR/SignalR/wiki, a site with less then 50 commits during the last year. It also gives a non working link to SignalR on jabbr, where the "SignalR team is supposed to "hang out"

3. Github: SignalR/SignalR (https://github.com/SignalR/SignalR)
A project on GitHub that claims to be the ASP.NET SignalR "home", and as mentioned previously has less than 50 commits this year and documentation from 2013

4. Microsoft Docs: Docs/ASP.NET/ASP.NET SignalR (https://docs.microsoft.com/en-us/aspnet/signalr/overview/getting-started/introduction-to-signalr)
This is the documentation that the ASP.NET (1) site links to. This site is so outdated that it claims SignalR doesn't work in Edge and the list of supported operating systems does not include Windows 10!

5. Github: aspnet/SignalR (https://github.com/aspnet/SignalR)
This is  a much more active project than SignalR/SignalR, but on the other hand it say it is only SignalR for ASP.NET Core.

So, where should people go to read about SignalR?

**Comment by mikaelm12** [comment]
Just gonna link the answer to this question for anyone here since you also asked it in the https://github.com/aspnet/SignalR repo.
Answer: https://github.com/aspnet/SignalR/issues/1226

**Comment by Bartolomeus-649** [comment]
Which is the main page where I should go read about SignalR, and where I can find all information necessary to decide on what version, packages and so on to use in a new project?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
