### ISSUE TITLE
Implement custom User-Agent support

### ISSUE THREAD

**Issue by siberianguy** [SignalR/SignalR#4056]
Current .NET client implementation doesn't support specifying custom User-Agent header which is problematic for a number of scenarios, particularly, CloudFlare bypassing. [Here's a long thread](https://github.com/elcattivo/CloudFlareUtilities/issues/18) where people tried to overcome this limitation and rewrote parts of SignalR to use websocket-sharp library. Unfortunately websocket-sharp is not maintained and doesn't support .NET Core. So I would like to ask if there's any chance custom User-Agent will be natively supported in SignalR .NET Client (a new version of SignalR supports it but unfortunately it doesn't support communicating with old SignalR servers).

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
