### ISSUE TITLE
Signalr Hub method invocation failure  

### ISSUE THREAD

**Issue by raghu431pk** [SignalR/SignalR#4058]
# Issues related to the Asp.NET Core version of SignalR should be filed in the corresponding SignalR repo: https://github.com/aspnet/?utf8=%E2%9C%93&query=Signalr

We are  invoking signal r hub method from azure function below the sample we are using in our project .
var content = JsonConvert.SerializeObject(responseObj);
                var hub = new HubConnection("xxxxHubUrl");//this is our hub url
                var proxy = hub.CreateHubProxy("BlobFilesPublisher");
                hub.Start().Wait();

               
                proxy.Invoke("xxxHubName", content).ContinueWith(task =>
                {
                    if (task.IsFaulted)
                    {
                        proxy.Invoke("XxHubMethod", content);
                    //log.Info("Log added to database started!");
                    Console.WriteLine("There was an error calling send: {0}", task.Exception.);
                    }
                    else
                    {
                        Console.WriteLine("Success !Send Complete.");
                    }
                });
            }

The hub hosted in azure app service below is the code for the same.
class hubclass:Hub
{
 public void PublishBlobFiles(string inputRequest)
        {
            
            try
            {
                var content = JsonConvert.DeserializeObject(inputRequest);
                //System.Threading.Thread.Sleep(15000);
                LogData(inputRequest);
                Clients.All.NotifyFarmDevices(content);
            }

}

initially azure function sending message to azure app service and azure app service sending push notifications  to UI,

Suddenly it is missing messages at both sides.It is missing messages from azure function to appservice and also appservice to UI.

I put log before sending to UI ,but there is no exception logged,but its displaying message in azure function  in there was an error sending  ,but no exception logged any where,its successfully sending some messages but some messages are missing at both side,

Please hep us on this issue

**Comment by Ryujose** [comment]
Hello @raghu431pk 

Have you done some monitoring to see if there's some communication loss between those services?

If so, then, can you try to do the same on a local environment to see It's behaviour? 

Try to log the deserialized content, to ensure there isn't corrupted data.

Another thing that you can try is to see if the connection is being reconnecting or disconnected with a reconnection on the middle with data being loss. In this case try to log or do something with the OnReconnected() or OnDisconnected() events for example. Take a look of this for more information https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/handling-connection-lifetime-events

Hope it helps!

Regards.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
