### ISSUE TITLE
Error: The time zone ID 'Unknown' was not found on the local computer when running on Azure

### ISSUE THREAD

**Issue by imsam67** [SignalR/SignalR#4061]
I've implemented SignalR Core (alpha 2) on an ASP.NET Core 2.0 app with React front-end.

Everything seems to be working fine locally. I'm able to send messages (in a chat) back and forth between Chrome and Edge.

I then published my app to Azure and enabled web sockets in App Settings on Azure. When I try to send a message from Chrome, I get an error that reads:

> Uncaught (in promise) Error: The time zone ID 'Unknown' was not found on the local computer.
![capture](https://user-images.githubusercontent.com/15844030/34886178-3d77dd7e-f790-11e7-86b1-687e574c208c.PNG)

This message never gets through to Edge. If I send a message from Edge to Chrome, it seems to go through and Chrome picks it up right away.

One more important point: even though the message sent from Chrome doesn't seem to get through and Edge doesn't pick it up, if I refresh the page on Edge, I actually see the message Chrome sent. This means, the message sent by Chrome does reach the hub and get recorded in my database.

Any idea what may be causing this?

**Comment by BrennanConroy** [comment]
Could you move this issue here https://github.com/aspnet/SignalR/issues

This repo is for `ASP.NET SignalR`

**Comment by imsam67** [comment]
I did. Just so I'm clear, what exactly is the difference between these two repos?

**Comment by BrennanConroy** [comment]
This repo is for SignalR 2 on original ASP.NET

The other repo is for the new SignalR Core on ASP.NET Core
