### ISSUE TITLE
Azure Redis Cache Scaleout - empty message in SignalR tracing

### ISSUE THREAD

**Issue by jamesatgithub** [SignalR/SignalR#4065]
The SignalR (NET461) server works well in my project without scaleout, but after added Azure Redis Cache as scaleout, the client couldn't get any message from server. and the tracing reveals that the message seems wrong e.g. the empty M in below log:

`SignalR.Transports.WebSocketTransport Verbose: 0 : Sending outgoing message. Connection id: 458896d4-870c-4919-af1c-909a10d50649, transport: WebSocketTransport, message: {"C":"s-0,43","S":1,"M":[]}`

This might be related to Azure Redis Cache but I didn't find any document that can help, so asked here. anything should to look at if got the above trace?

Without scaleout the project works well and the trace log looks like this:

SignalR.Transports.WebSocketTransport Verbose: 0 : Sending outgoing message. Connection id: 5d4fff18-3f5d-4cb4-a946-19dd392e21d6, transport: WebSocketTransport, message:
{"C":"d-3159C799-E,0|F,1|G,1","M":[{"H":"MyHub","M":"userMessageReceived","A":[{"email":"test@test.com","userFullName":"Jone Don","userId":9,"token":"xxxx"}]}]}

**Comment by anurse** [comment]
We've made some fixes to scale-out in the latest release (2.3.0) including a bug that sounds a little like this one you're describing (though not exactly). Could you try updating and see if the issue still reproduces? I'm going to close this for now but feel free to re-open if you've still got it reproducing on the latest release.
