### ISSUE TITLE
SignalR keeps disconnecting at a higher rate

### ISSUE THREAD

**Issue by rajikaimal** [SignalR/SignalR#4067]
### Expected  behavior

A consistent connection should be established between client and server.

### Actual behavior

- Connection is established between client and server.
- Sudden disconnection of the SignalR connection.
- Connection becomes alive after reconnecting.
- This behavior keeps happening without any consistent time period between the connection and disconnection.

### Steps to reproduce

- This behavior takes place for one of the instance of application that we've created, other instance don't produce this behavior. Yet we can track the cause for this inconsistent disconnection problem with the SignalR logs as well. I have attached a snapshots of the logs.

![image](https://user-images.githubusercontent.com/8940086/35267376-13e9999c-004c-11e8-89b6-10020074edb1.png)

![image](https://user-images.githubusercontent.com/8940086/35267753-4f2ac20a-004d-11e8-8bfe-a5efe606300b.png)

**Comment by anurse** [comment]
Hey, sorry for the delay in responding, as we posted on [our blog](https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/] we left a bit of a backlog and are trying to clear it up.

If you're still encountering this issue, I have some comments/questions. If you've moved past this issue or found a resolution, feel free to let me know!

**Comment by rajikaimal** [comment]
Hi, we haven't experienced this issue lately. Therefore I'll close this issue for now.

**Comment by anurse** [comment]
Glad to hear it! If it comes back up, please feel free to file the issue again and we'll try to follow-up much faster next time :)
