### ISSUE TITLE
SignalR notification using SqlScaleoutConfiguration gives random exception for Rebus.Transport.TransactionContext not serializable

### ISSUE THREAD

**Issue by ilcorvo** [SignalR/SignalR#4068]
I use: 
- SignalR 2.2.2 in SqlScaleoutConfiguration 
- Rebus 3.0.1

Some events stored in Rebus are handled by a notification hub and pushed to the clients using signalR.
Everything works fine, but 3 days ago, after having published a new version, none of the clients received the "new version" message probably because of the following exception:

> 10:39:04.586\| \|ERROR\| \|ProcessId=8196\| \|ThreadId=5\| \|SignalR.SqlMessageBus\| \|Stream 0 : Error starting SQL notification listener: System.Runtime.Serialization.SerializationException: Type 'Rebus.Transport.TransactionContext' in Assembly 'Rebus, Version=3.0.1.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.  Server stack trace:     at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(RuntimeType type)    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)    at System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context)    at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo()    at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)    at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)    at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)    at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)    at System.Runtime.Remoting.Channels.CrossAppDomainSerializer.SerializeMessageParts(ArrayList argsToSerialize)    at System.Runtime.Remoting.Messaging.SmuggledMethodCallMessage..ctor(IMethodCallMessage mcm)    at System.Runtime.Remoting.Messaging.SmuggledMethodCallMessage.SmuggleIfPossible(IMessage msg)    at System.Runtime.Remoting.Channels.CrossAppDomainSink.SyncProcessMessage(IMessage reqMsg)  Exception rethrown at [0]:     at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)    at System._AppDomain.CreateInstance(String assemblyName, String typeName)    at System.Data.SqlClient.SqlDependency.CreateProcessDispatcher(_AppDomain masterDomain)    at System.Data.SqlClient.SqlDependency.ObtainProcessDispatcher()    at System.Data.SqlClient.SqlDependency.Start(String connectionString, String queue, Boolean useDefaults)    at 
Microsoft.AspNet.SignalR.SqlServer.ObservableDbOperation.StartSqlDependencyListener()

The message in Rebus queue results as correctly handled.
The handler is this:
```
public async Task Handle(ApplicationVersionEvent message)
{
    await Clients.All.CheckApplicationVersion(new ApplicationCurrentVersionNotification
        {                    
            CurrentVersion = message.CurrentVersion
        });
}
```
It was resolved by a restart, but I need to understand what happened. 
I similar issues are:

- [https://github.com/SignalR/SignalR/issues/3401](https://github.com/SignalR/SignalR/issues/3401) 
- [https://github.com/SignalR/SignalR/issues/3404](https://github.com/SignalR/SignalR/issues/3404)
- [SQL Query Notifications do not always work in scaleout setup (SQL Server)](https://stackoverflow.com/questions/28504712/sql-query-notifications-do-not-always-work-in-scaleout-setup-sql-server)

but I think this is not the same case.

I previously added this issue on stackoverflow: [SignalR notification using SqlScaleoutConfiguration gives random exception for Rebus.Transport.TransactionContext not serializable](https://stackoverflow.com/questions/48303019/signalr-notification-using-sqlscaleoutconfiguration-gives-random-exception-for-r).

**Comment by anurse** [comment]
First off, sorry for the delay in responding. We're trying to work through our backlog of issues (which grew a little too big :)).

> Error starting SQL notification listener: System.Runtime.Serialization.SerializationException: Type 'Rebus.Transport.TransactionContext' in Assembly 'Rebus, Version=3.0.1.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.

Our SQL Scaleout system uses [`SqlDependency`](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/detecting-changes-with-sqldependency) to detect changes in the database. That component usually needs to serialize the "ExecutionContext" (a set of ambient state .NET maintains) in order to establish a remote connection with the server. It sounds like Rebus is adding some non-serializable data into the ExecutionContext which would cause this error. It's generally expected that ExecutionContext data be serializable, so this change would have to come from Rebus.

Closing this as there isn't anything SignalR can do here. This is an incompatibility between SqlDependency (which SignalR requires) and Rebus. You could consider using a different scale-out system such as Redis.

**Comment by ilcorvo** [comment]
Oh yes, I forgot this issue because I solved it by a workaround 7 month ago.
The problem is that SqlMessageBus is initialized the first time it is retrieved invoking GetHubContext, so I forced its initialization before executing any command.
```
            app.MapSignalR();

            var context = new OwinContext(app.Properties);
            var token = context.Get<CancellationToken>("host.OnAppDisposing");
            if (token != CancellationToken.None)
            {
                token.Register(() =>
                {
                    log.Info("host.OnAppDisposing");
                    // code to run when server shuts down
                    BackendMessageBusConfig.DisposeContainers();
                });
            }

            // this code brings forward SignalR SqlMessageBus initialization 
            var forceInit = GlobalHost.ConnectionManager.GetHubContext<NotificationHub>();

            BackendMessageBusConfig.Register();
```

**Comment by anurse** [comment]
I suspected you had probably found a solution and moved on :). A lot of these issues were left idle because we were focused on ASP.NET Core. Sorry about that! Thanks for posting the solution you found so that others who are searching for this problem can find it!
