### ISSUE TITLE
AuthenticationManager.GetAuthenticationTypes() always empty if transport is WebSockets

### ISSUE THREAD

**Issue by cristian-eriomenco** [SignalR/SignalR#4070]
Within a WebApi 2 solution the authentication is set to be using an OpenIdConnect client library. I am able successfully to use the `OwinContext.Authentication` class for kicking off authentication flow within the context of a Web Api Controller.

If i'm within a hub method, the Authentication manager doesn't work. 

Current setup:

```
public class MyHub: Hub<IMyHub> 
{
   public MyHub(){}

   public Task DoWork(){
        var principal = this.Context.User; // Currently WindowsIdentity as its not authenticated

        var auth = this.Context.Request.GetHttpContext().GetOwinContext().Authentication;
        var types = auth.GetAuthenticationTypes(); // Empty list
        // ....
   }
}
```

```
public class ValuesController: ApiController 
{
   public Task Get(){
      var auth = this.Request.GetOwinContext().Authentication;
      var types = auth.GetAuthenticationTypes(); // List containing one and only "Bearer" authentication type setup.
      //.....
   }
}
```

```
public class Startup 
{
  public void Configuration(IAppBuilder app)
  {
       var httpConfig = new HttpConfiguration();
       // .. Ioc Registering Hubs
       WebApiConfig.Register(httpConfig);
       FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
        app.UseOAuthIntrospection(options =>
        {
                //...
                options.AuthenticationType = OAuthDefaults.AuthenticationType;
                options.ClientId = clientId;
                options.ClientSecret = clientSecret;
                options.RequireHttpsMetadata = false;
                options.AuthenticationMode = AuthenticationMode.Passive;
                options.Events = new OAuthIntrospectionEvents()
                {
                    OnRetrieveToken = context =>
                    {
                        // Getting token from QueryString passed from js app.
                        var token = context.Request.Query["Authorization"];

                        if (!string.IsNullOrWhiteSpace(token))
                        {
                            context.Token = token;
                        }

                        return Task.CompletedTask;
                    }
                 }
                //...
        };
        app.UseCors(CorsOptions.AllowAll);
        app.MapSignalR(new HubConfiguration() { .... });
        app.UseWebApi(httpConfig); // Have tried swapping these 0 effect
}
```
Is there any reason why the `AuthenticationManager` doesn't work within the context of a signalr request?

P.S. I do need manually to trigger an authentication challenge and obtain the principal, cannot use [AuthorizeAttribute] on the hub or methods because they are passthrough.

Observations:

1. If `Context.Environment["security.Authenticate"]` is empty then `Authentication.GetAuthenticationTypes()` returns empty.
2. `Context.Environment["security.Authenticate"]` is set through the [AuthenticationMiddleware](https://github.com/aspnet/AspNetKatana/blob/9f6e09af6bf203744feb5347121fe25f6eec06d8/src/Microsoft.Owin.Security/Infrastructure/AuthenticationMiddleware.cs#L27) by [AuthenticationHandler](https://github.com/aspnet/AspNetKatana/blob/9f6e09af6bf203744feb5347121fe25f6eec06d8/src/Microsoft.Owin.Security/Infrastructure/AuthenticationHandler.cs#L62)
3. At some point if using WebSockets as a transport the `Context.Environment["security.Authenticate"]` gets emptied, if the chosen transport is LongPolling, then everything works as expected
4. I did try different AuthMiddlewares just to prove the point thats its not the `app.UseOAuthIntrospection` implementation doing something wrong.

Any help is appreciated!
Thank you!

**Comment by anurse** [comment]
Hey, sorry for the delay in responding, as we posted on [our blog](https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/] we left a bit of a backlog and are trying to clear it up.

If you're still encountering this issue, I have some comments/questions. If you've moved past this issue or found a resolution, feel free to let me know!

WebSockets are little funky here in that ASP.NET's OWIN implementation can't provide the same Environment information once the WebSocket request is "accepted" (which SignalR does on your behalf). The `security.Authenticate` key won't be present in the environment dictionary inside a WebSocket handler (which is where you are when SignalR invokes a hub method). The idea is that you should be doing your authentication outside the SignalR middleware and loading up the `User` property with the data you need. SignalR will preserve that data into the WebSocket context.

What data are you trying to get within your WebSocket request? The AuthenticationTypes should be mostly the same throughout your application so you shouldn't need to query the data in a Hub method.

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.

Sorry again for the delays. We're actively monitoring these issues again so when you do have some more information we'd be happy to help resolve the issue!
