### ISSUE TITLE
CamelCase Issues

### ISSUE THREAD

**Issue by no1melman** [SignalR/SignalR#4072]
So, I made the JsonSerializer use the CamelCase contract resolver.

Then I got an error saying that signalr couldn't verify the version. Then I found this line in your client js. It doesn't account for the response being in CamelCase.

https://github.com/SignalR/SignalR/blob/44f24335323aa01f22dd5308651d96471ec66442/src/Microsoft.AspNet.SignalR.Client.JS/jquery.signalR.core.js#L727

I'm not sure how you want this to be handled. The quick and dirty fix is to use `(res.Protocol || res.protocol)`

I personally would wrap the response.

I don't know if this has already been addressed somewhere else?

**Comment by anurse** [comment]
This would be a pretty significant protocol change and would break a lot of clients. Our guidance has generally been to ensure custom serializers don't change the casing of these properties (see https://github.com/SignalR/SignalR/wiki/Extensibility#replacing-the-ijsonserializer). We did resolve this in ASP.NET Core SignalR, where the user-specified serializer is only able to affect user payloads, but that would be a major protocol change and client overhaul to do it in ASP.NET SignalR.

I'm going to close this as it's not something we're going to be able to tackle in ASP.NET SignalR. You're certainly welcome to adjust the client on your side to make it work, or to have your custom JSON Serializer leave those properties alone.

**Comment by no1melman** [comment]
Yes, I ended up doing the same as aspnet core and creating a payload where I had my casing in that.
