### ISSUE TITLE
Support for websocket.binaryType = 'arraybuffer'

### ISSUE THREAD

**Issue by voltcode** [SignalR/SignalR#4073]
Feature request.
websockets allow arraybuffer mode, as per:
https://developer.mozilla.org/pl/docs/Web/API/WebSocket

it would be beneficial for high performance applications to be able to stream raw data, perhaps using apache arrow features, onto frontend. It could potentially remove the need for costly two-way JSON serialization.

**Comment by davidfowl** [comment]
We have no plans to support binary with this version of SignalR. The ASP.NET Core version supports binary
