### ISSUE TITLE
[Question] How can I map only specific hubs in SignalR

### ISSUE THREAD

**Issue by zorgoz** [SignalR/SignalR#4077]
I have two hubs in my application. For the one I need NTLM authentication, and IP based filtering for the other. For this to work I need to set HttpListener.AuthenticationSchemes to AuthenticationSchemes.Ntlm for the first, while it remains Anonymous for the other. This means that I can not have both hubs running on the same listener connection. I have my OwinMiddleware to handle the authentication, and I am trying to set up two different endpoints for these two hubs (two different ports). My problem is that when I don't know how to tell SignalR to map only a specific hub to specific IAppBuilder, and not all hubs that it can find. 

This question is unanswered on [StackOwerflow](https://stackoverflow.com/questions/46726692/how-can-i-map-only-specific-hubs-in-signalr) for half a year.

**Comment by anurse** [comment]
You should be able to support both NTLM and Anonymous authentication in HttpListener by simply ORing the two values together (it's a Flags enum not a standard enum): https://docs.microsoft.com/en-us/dotnet/api/system.net.authenticationschemes?view=netframework-4.7.2

For example:

```csharp
httpListener.AuthenticationSchemes = AuthenticationSchemes.Ntlm | AuthenticationSchemes.Anonymous
```

If that doesn't work, can you provide a sample app that reproduces the issue so I can investigate futher?

**Comment by anurse** [comment]
Ah, I see what you're looking for. That would be a pretty major change and we don't have plans to do that in the upcoming 2.4.0 wave of releases. In fact, it's these limitations that are precisely why ASP.NET Core SignalR allows this kind of mapping of different hubs to different endpoints.

Anyway, I'm going to close this. We don't have plans to make this significant a change to the architecture of ASP.NET SignalR at this point.
