### ISSUE TITLE
Question: SignalR and firewalls

### ISSUE THREAD

**Issue by samcov** [SignalR/SignalR#4078]
I have a website operating on port 80, i.e., a normal website. I also have signalr self hosted in a windows service listening on a port(8099).

Everything works fine, but here is my question.

If a company blocks all ports except for 80 and 443, will my signalr service be blocked as well, and if so, what would be the solution?

**Comment by samcov** [comment]
Ok, I fired up a virtual machine and blocked access to the port, and from that client, my SignalR code will not work.

Since my website is operating on port 80, do I need to have signalr on port 80?

Not sure how to resolve this, any info would be appreciated.

**Comment by Ryujose** [comment]
Hello @samcov 

You've more information here about it.

https://stackoverflow.com/questions/37332911/signalr-port-requirement

Hope it helps.

Regards.

**Comment by samcov** [comment]
Thanks, it turns out that the solution is to use the Asp.Net Module for IIS. It effectively puts the process on port 80/443 and solves the problem.
