### ISSUE TITLE
Error during WebSocket handshake: Incorrect 'Sec-WebSocket-Accept' header value

### ISSUE THREAD

**Issue by tranphuongyd** [SignalR/SignalR#4082]
I'm using the SignalR in .Net Core project (Microsoft.AspNetCore.SignalR -Version 1.0.0-alpha2-final). 
It's work very well from 1 week ago. BUT today it's get the error: **WebSocket connection to 'mydomain' failed: Error during WebSocket handshake: Incorrect 'Sec-WebSocket-Accept' header value.** 
![image](https://user-images.githubusercontent.com/7795756/37348375-80c14d36-2706-11e8-8bf1-1bd182fb0fb3.png)

Can someone help me resolve this issue!!

Thanks,
Phuong Tran

**Comment by davidfowl** [comment]
This should be filed on https://github.com/aspnet/SignalR
