### ISSUE TITLE
2.2.3 changelog?

### ISSUE THREAD

**Issue by raRaRa** [SignalR/SignalR#4083]
Hey, I can't find any changelog for the 2.2.3 release. It would be much appreciated.

Thanks!

**Comment by pwnzya** [comment]
I was wondering about it too.  NuGet has v2.2.3 but it seems it's still v2.2.2 here.

**Comment by raRaRa** [comment]
@anurse or @moozzyk you know anything? Thanks!

**Comment by anurse** [comment]
2.2.3 was a very minor release consisting of just a single fix: https://github.com/aspnet/SignalR/issues/1094

We didn't make much in the way of an announcement because of how minor it was :). Hope that clarifies things!

**Comment by MatthewSteeples** [comment]
Is there likely to be a CDN release for the .js files, or (as there appears to be no change) do you recommend we stick with the 2.2.2 ones? (we're affected by that issue, otherwise we'd skip / wait until they were published)

**Comment by anurse** [comment]
@MatthewSteeples I can look in to a CDN release but you are correct in observing there is no change to the JavaScript. The `2.2.2` scripts should work fine with `2.2.3` server.

**Comment by MatthewSteeples** [comment]
@anurse Obviously don't do it on our account, as we're happy to stick with the 2.2.2 version. I suppose it would be the kind of thing that would be useful to highlight in release notes

**Comment by anurse** [comment]
Closing this as the question has been answered. Feel free to comment further if you need clarification on something! We can always re-open the issue if there's something to fix here.
