### ISSUE TITLE
SignalR in Nativescript connection fails

### ISSUE THREAD

**Issue by tuckerjt07** [SignalR/SignalR#4084]
# Issues related to the Asp.NET Core version of SignalR should be filed in the corresponding SignalR repo: https://github.com/aspnet/?utf8=%E2%9C%93&query=Signalr

### Expected  behavior
When calling HubConnection.start() a valid connection should open
### Actual behavior
When calling HubConnection.start() I am getting this error message ```Unexpected token o in JSON at position 1```. I have debugged through the code and cannot see invalid JSON anywhere the flow. At this point ```let negotiateResponse: INegotiateResponse = JSON.parse(<string>negotiatePayload.content); ``` (Line 85, HttpConnection.ts) the JSON is showing up as valid but I have traced it to it being the failure point.
### Steps to reproduce
Attempt to start a SignalR project in Nativescript.

Is there a way to debug deeper to find out what exactly is going on here?

If I run a JSON.stringify() on it in the console I get this output ```"{\"connectionId\":\"6ee34844-1515-4fd8-a15e-de0a50c305af\",\"availableTransports\":[\"WebSockets\",\"ServerSentEvents\",\"LongPolling\"]}"``` which I have ran through jsonlint.com as valid JSON. However, running it through JSON.parse results in the above error.

Update:

I was able to fix the initial error by changing the line to ```let negotiateResponse: INegotiateResponse = typeof negotiatePayload.content === 'object' ? negotiatePayload.content : JSON.parse(<string>negotiatePayload.content); ``` for testing purposes. Now I am getting a Websockets is undefined error.

**Comment by moozzyk** [comment]
You seem to be mixing the new client from the Asp.NET Core version of SignalR with the old server. They are not compatible and will not work together.

**Comment by tuckerjt07** [comment]
No that wasn't the issue. The issue was that I needed to tell it to only use LongPolling explicitly for Nativescript. I didn't see a ready example of that in the docs but did find it when going through the Source Code. The other issue is one I need to make a pull request for. Without the above ternary line the I get the invalid JSON error.

**Comment by moozzyk** [comment]
I guess the issue was filed in a wrong repo which made me draw a conclusion that you were using old SignalR server.

**Comment by tuckerjt07** [comment]
No, the issue is with SignalR itself. Code and documentation as separate issues but both attributed directly to SignalR.

**Comment by anurse** [comment]
This was for ASP.NET Core SignalR, and https://github.com/aspnet/SignalR/issues/1926 was filed to track that.
