### ISSUE TITLE
Dictionary values are changed unexpectedly

### ISSUE THREAD

**Issue by keerthivasanm** [SignalR/SignalR#4085]
I have a property named meta which is of type Dictionary<string, string>. I have a key named "FooTime" and the value is a string (FooTime is a DateTimeOffset on the server-side). While mapping to this dictionary, it is converted to a string format (yyyy-MM-ddTHH:mm:sszzz).

### Example
At server, set FooTime to 2018-03-22T14:54:27+00:00

### Expected  behavior
FooTime value remains the same (2018-03-22T14:54:27+00:00) on the client

### Actual behavior
FooTime value is changed (3/22/2018 09:54:27) on the client [Time zone is changed to local time and format is different]

### Steps to reproduce
Create a property of type Dictionary<string, string> in the server. Set a key with value as above and observe on client.

Workaround: Use UnixTimeInSeconds instead of dealing with string formats :)

**Comment by keerthivasanm** [comment]
Version: 2.2.2

**Comment by anurse** [comment]
This is a known issue in JSON.NET (https://github.com/JamesNK/Newtonsoft.Json/issues/862). It is detecting a date and automatically trying to parse it in to a DateTime, then reserialize it later to a string. You need to change the [DateParseHandling](https://github.com/JamesNK/Newtonsoft.Json/issues/862) setting to `DateParseHandling.None` to prevent it. 

You can configure this by registering a custom `IJsonSerializer` in the `IDependencyResolver` that sets this setting. See https://github.com/SignalR/SignalR/wiki/Extensibility#replacing-the-ijsonserializer for more details. For example:

```csharp
public class Global : System.Web.HttpApplication
{
    protected void Application_Start(object sender, EventArgs e)
    {
        var serializer = new JsonNetSerializer(new JsonSerializerSettings
        {
            DateParseHandling = DateParseHandling.None,
        });

        GlobalHost.DependencyResolver.Register(typeof(IJsonSerializer), () => serializer); 
    }
}
```
