### ISSUE TITLE
Server to catch Hub event

### ISSUE THREAD

**Issue by Robert969696** [SignalR/SignalR#4087]
As far asi know how to catch context of hub on server side i would like to also catch events like OnConnected, OnDisconnected on server code. This is because i would like to update clients list on server side in some control. How can i achieve that?

This is how i can get context and cal some hub's method:
```
  var context = GlobalHost.ConnectionManager.GetHubContext<MyHub>();
            context.Clients.All.DisconnectClient(txtClientId.Text);    
```

**Comment by Ryujose** [comment]
Use the override methods when you've inherited de Hub class.

Source: https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server

Example:

public class ContosoChatHub : Hub
{
    public override Task OnConnected()
    {
        // Add your own code here.
        // For example: in a chat application, record the association between
        // the current connection ID and user name, and mark the user as online.
        // After the code in this method completes, the client is informed that
        // the connection is established; for example, in a JavaScript client,
        // the start().done callback is executed.
        return base.OnConnected();
    }

    public override Task OnDisconnected()
    {
        // Add your own code here.
        // For example: in a chat application, mark the user as offline, 
        // delete the association between the current connection id and user name.
        return base.OnDisconnected();
    }

    public override Task OnReconnected()
    {
        // Add your own code here.
        // For example: in a chat application, you might have marked the
        // user as offline after a period of inactivity; in that case 
        // mark the user as online again.
        return base.OnReconnected();
    }
}

Regards.

**Comment by anurse** [comment]
Closing this as the question has been answered. Feel free to comment further if you need clarification on something! We can always re-open the issue if there's something to fix here.
