### ISSUE TITLE
Problem with SingnalR 

### ISSUE THREAD

**Issue by thanhluan1310** [SignalR/SignalR#4088]
I have on hub like below
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.AspNet.SignalR;
using System.Threading.Tasks;
using Model;
using DataAccess;

namespace TraCuu_ThongTin_DV.Chat_Chit
{
    public class ChatHub : Hub
    {
        private static readonly ConnectionMapping<string> _Connections = new ConnectionMapping<string>();
        public void Counsellor(string User_Send, string User_Receive, string Message)
        {
            var User_Reveive_ID = _Connections.GetConnections(User_Receive);

            if (User_Reveive_ID != Enumerable.Empty<string>())
            {
                SaveMessage(User_Send, User_Receive, Message, false);
                foreach (var ConnectionId in User_Reveive_ID)
                {
                    Clients.Client(ConnectionId).ChatClient(User_Send, Message);
                }
            }
            else
            {
                SaveMessage(User_Send, User_Receive, Message, true);
            }
        }

        public void GetHistoryChat(string Sender, string Receiver)
        {
            ChatInfo chatInfo = new ChatInfo(Sender, Receiver);
            Chat chat = new Chat();
            chatInfo = chat.GetExist(chatInfo);
            Clients.Caller.GetHisChatClient(chatInfo.Content, Receiver);

        }
        private void SaveMessage(string Sender, string Receiver, string Message, bool Missing)
        {
            ChatInfo chatInfo = new ChatInfo(Sender, Receiver);
            Chat chat = new Chat();
            chatInfo = chat.GetExist(chatInfo);
            string content = "<div class='chat-message me'><b>" + Sender
                        + "</b>: " + Message + "</div>";
            if (chatInfo.ID_Chat > 0)
            {
                chatInfo.Content += content;
                chatInfo.MissingContent += Missing ? chatInfo.Content : "";
                chat.UpdateChat(chatInfo);
            }
            else
            {
                chatInfo.Content += content;
                chatInfo.MissingContent += Missing ? chatInfo.Content : "";
                chat.InsertChat(chatInfo);
            }

            chatInfo = new ChatInfo(Receiver, Sender);
            chatInfo = chat.GetExist(chatInfo);
            content = "<div class='chat-message you'><b>" + Sender
                        + "</b>: " + Message + "</div>";
            if (chatInfo.ID_Chat > 0)
            {
                chatInfo.Content += content;
                chatInfo.MissingContent += Missing ? chatInfo.Content : "";
                chat.UpdateChat(chatInfo);
            }
            else
            {
                chatInfo.Content += content;
                chatInfo.MissingContent += Missing ? chatInfo.Content : "";
                chat.InsertChat(chatInfo);
            }
        }
        public void Notifyon(string UserName)
        {
            var User_Send_ID = _Connections.GetConnections(UserName);
            if (User_Send_ID == Enumerable.Empty<string>())
            {
                _Connections.Add(UserName, Context.ConnectionId);
            }
            Clients.All.NotifyOnClient(_Connections.keys);
        }

        public void Notifyoff(string UserName)
        {
            var User_Send_ID = _Connections.GetConnections(UserName);
            if (User_Send_ID != Enumerable.Empty<string>())
            {
                _Connections.Remove(UserName, Context.ConnectionId);
            }
            Clients.All.NotifyOffClient(_Connections.keys);
        }
        //public override Task OnConnected()
        //{
        //    //var User_Send_ID = _Connections.GetConnections(UserName);
        //    //if (User_Send_ID == Enumerable.Empty<string>())
        //    //{
        //    //    _Connections.Add(UserName, Context.ConnectionId);
        //    //}
        //    //Clients.All.NotifyOnClient(_Connections.keys);
        //    return base.OnConnected();
        //}

    }
}
and one page like that 
<%@ Page Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="TraCuu_ThongTin_DV.WebForm1" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <%--   <script src="Scripts/jquery-1.6.4.js"></script>--%>
    <script src="Scripts/jquery.signalR-2.2.3.js"></script>
    <script src='<%: ResolveClientUrl("~/signalr/hubs") %>'></script>
    <style>
        @keyframes down {
            0% {
                position: absolute;
                top: 0;
            }

            50% {
                position: absolute;
                top: 50%;
            }

            100% {
                position: absolute;
                top: 100%;
            }
        }

        .toggle-header {
            position: absolute;
            bottom: 0;
            animation: down linear 0.5s;
        }

        .area-chat-footer {
            position: fixed;
            bottom: 0;
            right: 0;
            margin-right: 5px;
            margin-bottom: 5px;
            overflow: hidden;
            height: 320px;
        }

        .chat-box {
            height: 100%;
            width: 260px;
            float: right;
            margin-right: 10px;
        }

        .chat-header {
            background-color: #337ab7;
            color: white;
            width: inherit;
            height: 30px;
            max-height: 30px;
            padding: 5px;
            border-radius: 5px;
            font-size: 13px;
            border: solid 1px #e9e9e9;
            /*animation: up linear 0.5s;*/
        }

        .chat-body {
            overflow-y: scroll;
            padding: 5px;
            height: 255px;
            max-height: 255px;
            border-left: solid 1px #e9e9e9;
            border-right: solid 1px #e9e9e9;
            font-size: 14px;
        }

        .chat-footer {
            height: 55px;
            max-height: 55px;
            width: 100%;
        }

        .txt-chat {
            height: 35px;
        }

        .grd_list_user {
            border: none;
            padding: 0;
            border-collapse: collapse;
            width: 100%;
        }

            .grd_list_user td {
                border: none;
                padding: 5px;
            }

        .on {
            background: rgb(66, 183, 42);
            border-radius: 50%;
            display: inline-block;
            height: 6px;
            margin-left: 4px;
            margin-right: 5px;
            width: 6px;
        }

        .btn-close {
            float: right;
            font-size: 20px;
            height: 20px;
            width: 20px;
            margin-right: -5px;
            margin-top: -8px;
            opacity: 0.8;
            filter: alpha(opacity=80);
        }

            .btn-close:hover {
                opacity: 1;
                filter: alpha(opacity=100);
            }

        .chat-message {
            padding: 5px;
            word-wrap: break-word;
            border-radius: 10px;
            width: 180px;
            margin-top: 10px;
        }

        .me {
            float: left;
            background-color: #e9e9e9;
        }

        .you {
            background-color: #337ab7;
            float: right;
            color: white;
        }
    </style>
    <div id="body" style="width: 1000px; height: 2000px">
        <div id="item" style="display: none">
            <div class="chat-box" id="{model}">
                <div role="button" class="chat-header">
                    <div class="form-group">
                        <div class="btn-close" style="">x</div>
                        <div class="form-inline float-left">
                            <span class="on" style="display: none"></span>
                            <span id="header">{ReceiveName}</span>
                        </div>
                    </div>
                </div>
                <div id="chat-body" class="chat-body">
                    <div id="content">
                    </div>
                </div>
                <div class="chat-footer">
                    <div class="input-group">
                        <input placeholder="Nhập tin nhắn" data-receiver="{model}" type="text" class="form-control txt-chat" />
                    </div>
                </div>
            </div>
        </div>

        <div id="Chat_Footer" class="area-chat-footer">
            <div class="chat-box">
                <div class="chat-header" role="button">
                    <%= Session["FullName"].ToString() %>
                </div>
                <div class="chat-body">
                    <asp:GridView ID="Grd_List_User" CssClass="grd_list_user" runat="server" AutoGenerateColumns="false"
                        ShowHeader="false">
                        <Columns>
                            <asp:TemplateField>
                                <ItemTemplate>
                                    <div class="user-chat" role="button" data-username="<%# Eval("UserName") %>" data-fullname="<%# Eval("FullName") %>">
                                        <img width="28px" height="28px" src="Image/user.ico" alt="">
                                        <span><%# Eval("FullName") %></span>
                                    </div>
                                </ItemTemplate>
                                <ItemStyle Width="240px" />
                            </asp:TemplateField>
                            <asp:TemplateField>
                                <ItemTemplate>
                                    <span data-username="<%# Eval("UserName") %>" class="on float-right" style="display: none"></span>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                    </asp:GridView>
                </div>
                <div class="chat-footer">
                    <div class="input-group">
                        <input id="search" placeholder="Tìm kiếm" type="text" class="form-control" style="height: 35px;" />
                    </div>
                </div>
            </div>
            <%--<div class="alert-danger" style="width: 300px; height: 300px; display: none">hello</div>--%>
        </div>
    </div>
    <script>
        var users = {};
        var me = '<%=Session["Username"].ToString()%>';
        var song = new Audio();
        song.src = "Sound/DapMoCuocTinh-DanNguyen.mp3";
        song.volume = 1;

        var chat_Sound = new Audio();
        chat_Sound.src = "Sound/chat-sound.mp3";
        chat_Sound.volume = 1;

        $(document).ready(function () {

            var chat = $.connection.chatHub;

            chat.client.chatClient = function (who, message) {
                var you = $("#" + who);
                message = '<div class="chat-message you"><b>' + who + ":</b> " + message + "</div>";
                chatBoxs = $("#Chat_Footer").children(":visible");

                if (you.length) {
                    chat_Sound.play();

                    item = you.find(".chat-header");
                    item.siblings().show();
                    item.removeClass("toggle-header");

                    if (chatBoxs.length >= 4) {
                        if (you.is(":hidden")) {
                            you.show();
                            chatBoxs.last().hide();
                        }
                    }

                    var chatBody = you.find(".chat-body");
                    appendMessage(chatBody, message, true);
                    users[who].chatContent += message
                }
                else {
                    var input = {};
                    item = $("#Grd_List_User").find("div[data-username='" + who + "']");
                    input.userName = who;
                    input.fullName = item.data("fullname");
                    input.display = item.last().first().css("display");

                    var output = $("#item").clone(true, true);
                    output.find("#header").text(input.fullName);
                    output.find("span.on").css("display", input.display);
                    var html = output.html().replace(/\{model\}/g, input.userName)
                    $("#Chat_Footer").append(html);

                    if (users[who] == undefined) {
                        chat.server.getHistoryChat(me, who);
                    }
                    else {
                        item = $("#" + who).find(".chat-body");
                        users[who].chatContent += message;
                        appendMessage(item, users[who].chatContent, true);
                    }
                    if (chatBoxs.length >= 4) {
                        chatBoxs.first().next().hide();
                    }
                }
                focusItemClick($("#" + who));
            };

            chat.client.getHisChatClient = function (content, receiver) {
                users[receiver] = { chatContent: content };
                var item = $("#" + receiver).find(".chat-body");
                appendMessage(item, content, false);
            }

            chat.client.notifyOnClient = function (userNames) {
                loadUserOn(userNames);
            }

            chat.client.notifyOffClient = function (userNames) {
                loadUserOn(userNames);
            }

            var loadUserOn = function (userNames) {
                test = $("#Grd_List_User span.on");
                test.css("display", "none")
                for (var i = 0; i < userNames.length; i++) {
                    var usr = userNames[i];
                    var item = $("#Grd_List_User").find("span[data-username='" + usr + "']");
                    item.css("display", "");
                    if ($("#" + usr).find("span.on").length) {
                        $("#" + usr).find("span.on").css("display", "");
                    }
                }
            };

            var appendMessage = function (item, message, itemExist) {
                if (itemExist) {
                    item.first().append(message);
                    item.animate({ scrollTop: item.prop("scrollHeight") }, 500);
                }

                else {
                    item.first().append(message).animate({ scrollTop: item.prop("scrollHeight") }, 500);
                }
            }

            var newChatBox = function (input) {
                var output = $("#item").clone(true, true);
                output.find("#header").text(input.fullName);
                output.find("span.on").css("display", input.display);
                var html = output.html().replace(/\{model\}/g, input.userName)
                $("#Chat_Footer").append(html);
            }

            var focusItemClick = function (input) {
                var item = $(".area-chat-footer .chat-box .chat-header");
                item.not(":first").css("background-color", "#e9e9e9");
                item.not(":first").css("color", "black");

                var chatHeader = input.find(".chat-header");
                chatHeader.css("background-color", "#337ab7");
                chatHeader.css("color", "white");
            }

            //Dang ky event goi server
            $.connection.hub.start().done(function () {
                chat.server.notifyon(me);

                // su kien chat
                $(document).on("keydown", ".txt-chat",function (event) {
                    if (event.which == 13) {
                        value = $(this).val();
                        user_Receive = $(this).data("receiver");

                        message = '<div class="chat-message me"><b>' + me
                            + "</b>: " + value + "</div>"

                        var item = $(this).parents(".chat-footer").prev();
                        appendMessage(item, message, true);
                        $(this).val("");
                        //song.play();

                        if (users[user_Receive] != undefined) {
                            users[user_Receive].chatContent += message;
                        }
                        else {
                            users[user_Receive] = { chatContent: "" };
                            users[user_Receive].chatContent += message;
                        }
                        chat.server.counsellor(me, user_Receive, value);
                    }
                    //$(".alert-danger").css("display", "");
                });

                //hieu ung thu nho chat box
                $(document).on("click",".chat-header", function () {
                    $(this).siblings().toggle();
                    $(this).toggleClass("toggle-header");
                });
            }).fail(function (error) {
                console.log('Invocation of UserNameInUsefailed. Error: ' + error);
            });

            // su kien dong chatbox
            $(document).on("click",".btn-close", function (event) {
                event.stopPropagation();
                event.preventDefault();
                item = $(".area-chat-footer").children(":hidden");
                item.first().show();
                $(this).parents(".chat-box").remove();
            })

            // event tim nguoi chat
            $(document).on("keyup","#search", function (event) {
                event.stopPropagation();
                event.preventDefault();
                var input = $(this).val();
                $("#" + "<%=Grd_List_User.ClientID%>").find("tr").each(function () {
                    var td = $(this).first()
                    var re = new RegExp(input.toUpperCase(), 'g');
                    if (td.text() != undefined) {
                        if (td.text().toUpperCase().match(re) != undefined) {
                            $(this).show();
                        }
                        else {
                            $(this).hide();
                        }
                    }
                })
            });

            //event chon user de chat
            $(document).on("mousedown",".user-chat", function () {
                var you = $("#" + $(this).data("username"));
                var chatHeader = you.find(".chat-header");
                chatHeader.css("background-color", "white");
                chatHeader.css("color", "black");
            });

            $(document).on("mouseup",".user-chat", function () {
                var you = $("#" + $(this).data("username"));
                focusItemClick(you);
            });

            $(document).on("click",".user-chat", function () {
                var you = $("#" + $(this).data("username"));

                if (!you.length) {
                    focusItemClick(you);

                    var input = {};
                    input.userName = $(this).data("username");
                    input.fullName = $(this).data("fullname");
                    input.display = $("#Grd_List_User").find("span[data-username='" + input.userName + "']").css("display");
                    newChatBox(input);

                    if (users[input.userName] != undefined) {
                        var chatBody = $("#" + input.userName).find(".chat-body");
                        appendMessage(chatBody, users[input.userName].chatContent, true);
                    }
                    else {
                        chat.server.getHistoryChat(me, input.userName);
                    }

                    var item = $(".area-chat-footer").children(":visible");
                    if (item.length > 4) {
                        $(item[1]).hide();
                    }
                }
                else {
                    var item = $(".area-chat-footer").children(":visible");
                    if (item.length == 4 && you.is(":hidden")) {
                        you.show();
                        item.last().hide();
                    }
                }
                //return false;
            });
            // end event

            $(window).unload(function () {
                chat.server.notifyoff(me);
            });

        });

    </script>
</asp:Content>
i have one problem that when i call hub via chat event my page redirect to login.aspx
i don't know what happenning
Can anybody  help

**Comment by anurse** [comment]
First off, sorry for the delay in responding. We're working through some of the backlog of issues here.

Can you reduce the code down to a simple repro that illustrates the problem and describe exactly what steps you take and how the behavior is different from what you expected?

> i have one problem that when i call hub via chat event my page redirect to login.aspx

This generally indicates you haven't provided authentication information properly. Make sure you've configured authentication for your SignalR Hub property (see our [documentation](https://docs.microsoft.com/en-us/aspnet/signalr/overview/security/hub-authorization) for more guidance)

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
