### ISSUE TITLE
How to connect to SignalR server on ASP.NET MVC WEBAPI in Angular 4/5 ?

### ISSUE THREAD

**Issue by biapar** [SignalR/SignalR#4089]
How to connect to SignalR server on ASP.NET MVC WEBAPI in Angular 4/5 ?
I'm able to do it with JQUERY, but not in Angular 4/5.
Thanks.

**Comment by biapar** [comment]
Any news?

**Comment by anurse** [comment]
Can you provide more details? I'm not aware of any specific problem with Angular 4/5. Please provide details such as the package versions you are using, the error you are seeing, snippets of code illustrating the problem, etc.

**Comment by biapar** [comment]
Yes. SignalR don't work If you use it with Angular 4+ and on the other side MVC Web Api ( no .NET Core Web Api ). It's not able to read the SignalR proxy on the other side and so to work.
No problem with ASP.NET Core.

**Comment by anurse** [comment]
I need details in order to investigate this. What kind of errors are you getting in the browser console? How are you loading the scripts into the browser? What _exact_ package versions are you using (posting your `package.json` would help here).

Without details, I have nothing to investigate.

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.

**Comment by biapar** [comment]
I I haven't solved with asp.net core 2.
