### ISSUE TITLE
Thousands of hanging /rt/connect?transport=websockets requests on server

### ISSUE THREAD

**Issue by guylando** [SignalR/SignalR#4095]
While trying to improve our servers performance, I discovered that there are thousands of hanging /rt/connect?transport=websockets and also /rt/reconnect?transport=websockets on our productions server.
Some of the requests have "Time Elapsed" of more than a day.
They all have ExecuteRequestHandler state AspNetCoreModule module name.
We are using a kestrel net core website behind an iis on windows server 2016.
Is this the expected behavior? Because I am sure it causes performance problems if the server is not being restarted for a few days.
Also in case this is not the correct behavior, is there some configuration to limit the length of the requests? if the requests time will be limited it won't hurt anything?

I am not sure if this issue should be placed here or at aspnet/KestrelHttpServer or at aspnet/IISIntegration

**Comment by halter73** [comment]
WebSocket connections are designed to last until the client disconnects, so having some lasting days is not at all surprising.

What's the name and version of the SignalR package BTW? The new repo for SignalR on ASP.NET Core is at https://github.com/aspnet/SignalR. This repo is for the System.Web/OWIN version of SignalR.

**Comment by guylando** [comment]
@halter73 
websocket connections must have the rt/connect or rt/reconnect request active as long as they work? this limits the amount of concurrent websocket connections and for example on non-server window it allows only 10 concurrent clients.

we use Microsoft.AspNetCore.SignalR.Server (waiting for .net core 2.1 to upgrade) on server and signalr 2.2.2 on client.

I will move the issue to the repository you suggested but would be great if you can help understand if this issue is by design as you are saying, because this is problematic and will create problems for the server after several days. what can we do to prevent that in case this is by design?
