### ISSUE TITLE
caused.AggregateException(s) System.Threading.Tasks.TaskCompletionSource.SetResult(TResult result)

### ISSUE THREAD

**Issue by haohighview** [SignalR/SignalR#4100]
I am getting following exceptions
Version 2.2.3
caused.AggregateException(s)
System.Threading.Tasks.TaskCompletionSource.SetResult(TResult result)<386f2ea706ca4cb59d198306aa65506b>:0
Microsoft.AspNet.SignalR.Infrastructure.DispatchingTaskCompletionSource.<>c__DisplayClass6_0.b__0():0
Microsoft.AspNet.SignalR.TaskAsyncHelper.<>c__DisplayClass77_0.b__0():0
System.Threading.Tasks.Task.InnerInvoke()<386f2ea706ca4cb59d198306aa65506b>:0
System.Threading.Tasks.Task.Execute()<386f2ea706ca4cb59d198306aa65506b>:0
--- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
System.Threading.Tasks.TaskCompletionSource.SetResult(TResult result)<386f2ea706ca4cb59d198306aa65506b>:0
Microsoft.AspNet.SignalR.Infrastructure.DispatchingTaskCompletionSource.<>c__DisplayClass6_0.b__0():0
Microsoft.AspNet.SignalR.TaskAsyncHelper.<>c__DisplayClass77_0.b__0():0
System.Threading.Tasks.Task.InnerInvoke()<386f2ea706ca4cb59d198306aa65506b>:0
System.Threading.Tasks.Task.Execute()<386f2ea706ca4cb59d198306aa65506b>:0

    public class SignalRHelper
    {
    private static bool TryingToStart;
    private static HubConnection _hubConnection;
    private static IHubProxy _chatHubProxy;
    private static IHubProxy ChatHubProxy
    {
        get
        {
            if (_chatHubProxy == null)
                _chatHubProxy = HubConnection.CreateHubProxy("CoachHub");
            return _chatHubProxy;
        }
     }
    private static Action _connectedAction;

    private static HubConnection HubConnection
    {
        get
        {
            if (_hubConnection == null && App.UserId != 0)
            {
                var queryStringData = new Dictionary<string, string>
                {
                    { "TenancyName", App.TenancyName },
                    { "UserId", App.UserId.ToString() }
                };
                _hubConnection = new HubConnection(CommHelper.SignalrBaseUrl, queryStringData)
                {
                    DeadlockErrorTimeout = TimeSpan.FromSeconds(10)
                };
                _hubConnection.Headers.Add("Authorization", "Bearer " + App.Token);
                _hubConnection.StateChanged += HubConnection_StateChanged;
                _hubConnection.Error += HubConnection_Error;
                _hubConnection.Closed += HubConnection_Closed;
                _hubConnection.ConnectionSlow += HubConnection_ConnectionSlow;
                _hubConnection.Reconnected += HubConnection_Reconnected;
                _hubConnection.TransportConnectTimeout = TimeSpan.FromSeconds(3);
                _hubConnection.EnsureReconnecting();

            }
            return _hubConnection;
        }
    }

    public static bool Connected
    {
        get
        {
            if (HubConnection == null)
                return false;
            return HubConnection.State == ConnectionState.Connected;
        }
    }

    private static void HubConnection_Reconnected()
    {

    }

    private static void HubConnection_ConnectionSlow()
    {
    }

    private static void HubConnection_Closed()
    {
        TryToStart().Continue();
    }

    private async static Task TryToStart()
    {
        if (TryingToStart)
            return;

        await Task.Delay(500);
        while (_hubConnection != null && HubConnection.State != ConnectionState.Connected)
        {
            TryingToStart = true;
            try
            {
                if (HubConnection.State == ConnectionState.Disconnected)
                    await HubConnection.Start(new ServerSentEventsTransport(new NativeHttpClient()));
                break;
            }
            catch (Exception)
            {
            }
            finally
            {
                if (App.PlatformService.HasNetwork())
                    await Task.Delay(500);
                else
                    await Task.Delay(2000);
            }
        }
        TryingToStart = false;
    }

    public class NativeHttpClient : IHttpClient
    {
        private HttpClient _client;
        private IConnection _connection;

        public void Initialize(IConnection connection)
        {
            _connection = connection;
            _client = new HttpClient
            {
                Timeout = TimeSpan.FromMilliseconds(-1) //NOTE: infinite timeout because upper SignalR layer handles timeouts
            };
        }

        public async Task<IResponse> Get(string url, Action<IRequest> prepareRequest, bool isLongRunning)
        {
            var request = new Request(HttpMethod.Get, url);
            prepareRequest(request);
            return await Send(request, isLongRunning);
        }

        public async Task<IResponse> Post(string url, Action<IRequest> prepareRequest, IDictionary<string, string> postData, bool isLongRunning)
        {
            var request = new Request(HttpMethod.Post, url)
            {
                Content = new FormUrlEncodedContent(postData)
            };
            prepareRequest(request);
            return await Send(request, isLongRunning);
        }

        private async Task<IResponse> Send(Request request, bool isLongRunning)
        {
            var option = isLongRunning ? HttpCompletionOption.ResponseHeadersRead : HttpCompletionOption.ResponseContentRead;
            var httpResponse = await _client.SendAsync(request, option, request.Cancellation.Token);
            var response = new Response(httpResponse);
            await response.ReadStream();
            return response;
        }

        private class Request : HttpRequestMessage, IRequest
        {
            public Request(HttpMethod method, string url) : base(method, url) { }

            public CancellationTokenSource Cancellation = new CancellationTokenSource();

            public string UserAgent { get; set; }

            public string Accept { get; set; }

            public void Abort()
            {
                Cancellation.Cancel();
            }

            public void SetRequestHeaders(IDictionary<string, string> headers)
            {
                if (UserAgent != null)
                {
                    Headers.TryAddWithoutValidation("User-Agent", UserAgent);
                }
                if (Accept != null)
                {
                    Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(Accept));
                }
                foreach (KeyValuePair<string, string> headerEntry in headers)
                {
                    Headers.Add(headerEntry.Key, headerEntry.Value);
                }
            }
        }

        private class Response : IResponse
        {
            private HttpResponseMessage _response;
            private Stream _stream;

            public Response(HttpResponseMessage response) => _response = response;

            public async Task ReadStream() => _stream = await _response.Content.ReadAsStreamAsync();

            public Stream GetStream() => _stream;

            public void Dispose()
            {
                _stream?.Dispose();
                _stream = null;

                _response?.Dispose();
                _response = null;
            }
        }
    }

    private static void HubConnection_Error(Exception obj)
    {
        App.PlatformService.TrackEvent("CoachHubConnectionError", new Dictionary<string, string>
        {
            ["Message"] = obj.Message
        });
        TryToStart().Continue();
    }

    private static void HubConnection_StateChanged(StateChange obj)
    {
        System.Diagnostics.Debug.WriteLine(obj.NewState.ToString());
        if (obj.NewState == ConnectionState.Connected)
        {
            _connectedAction?.Invoke();
        }
    }

    private static async Task<bool> WaitUserLoaded(CancellationTokenSource cancelSource)
    {
        if (cancelSource.IsCancellationRequested)
        {
            cancelSource.Dispose();
            return false;
        }
        if (HubConnection != null)
            return true;
        await Task.Delay(100);
        return await WaitUserLoaded(cancelSource);
    }

    public static async Task<IEnumerable<IDisposable>> StartConnection(Action<CoachStatusMessage> action, Action<MessageModel> receivedAction, Action connectedAction)
    {
        try
        {
            //after loaded user info, then try to connect the signalr.
            var userLoaded = await WaitUserLoaded(new CancellationTokenSource(10000));
            if (!userLoaded)
                return null;
            _chatHubProxy = null;
            _connectedAction = connectedAction;
            if (_hubConnection != null)
            {
                _hubConnection.StateChanged -= HubConnection_StateChanged;
                _hubConnection.Error -= HubConnection_Error;
                _hubConnection.Closed -= HubConnection_Closed;
                _hubConnection.ConnectionSlow -= HubConnection_ConnectionSlow;
                _hubConnection.Reconnected -= HubConnection_Reconnected;
                await DisConnectSignalr();
            }
            var statusUpdatedDisposable = ChatHubProxy.On("statusUpdated", (CoachStatusMessage status) => action?.Invoke(status));
            var sendUserMessageDisposable = ChatHubProxy.On("sendUserMessage", (MessageModel model) =>
            {
                System.Diagnostics.Debug.WriteLine("received signalr push");
                if (model == null)
                    return;
                model.CreatedAt = model.CreatedAt.ToUniversalTime();
                receivedAction?.Invoke(model);
            });

            TryToStart().Continue();

            return new[] { statusUpdatedDisposable, sendUserMessageDisposable };
        }
        catch (Exception ex)
        {
            return null;
        }
        finally
        {
            
        }
    }

    public static Task RestartConnection()
    {
        if (_hubConnection == null || _chatHubProxy == null)
            return null;
        return TryToStart();
    }

    public static Task DisConnectSignalr()
    {
        return Task.Factory.StartNew(() =>
        {
            try
            {
                _hubConnection?.Stop();
                _hubConnection = null;
                _chatHubProxy = null;
            }
            catch
            {
            }
        });
    }
}

**Comment by anurse** [comment]
I'm not seeing a situation where we should be causing this exception. All our calls to `SetResult` should be in places where it is only being called once, and I don't want to switch to `TrySetResult` until we know more about what's going on. Would you be able to collect [.NET client-side traces](https://docs.microsoft.com/en-us/aspnet/signalr/overview/testing-and-debugging/enabling-signalr-tracing#net_client) from the immediately before, during and after the exception? That would help us understand the flow of events that lead to this exception (since the callstack isn't terribly useful unfortunately).
