### ISSUE TITLE
Max count SignalR client connections from the same machine

### ISSUE THREAD

**Issue by arsamigullin** [SignalR/SignalR#4101]
Working on an application which is going to simulate a work of many SignalR clients. What is the max count SignalR client connections from the same machine can be created?

**Comment by Ryujose** [comment]
It doesn't have a limitation, in case of IIS you've to configurate it on your settings.

**Comment by davidfowl** [comment]
Limits are based on machine capability, mostly memory. Do you own scale testing on your own hardware.
