### ISSUE TITLE
Not reciving messages with Microsoft.AspNet.SignalR.Client in client .Net Core 2.0 

### ISSUE THREAD

**Issue by georginacm** [SignalR/SignalR#4103]
Hi,

I have a SingalR server with .Net Framework 4.5.2, and a SignalR Client ( Console Application)  with .Net Framework 4.5.2 using:

Server:
![image](https://user-images.githubusercontent.com/29973878/39358193-a3139d44-4a15-11e8-8754-2e9afb01da87.png)

Client:
![image](https://user-images.githubusercontent.com/29973878/39358467-67452c8c-4a16-11e8-9e48-5a1e78eb1596.png)

All of them are working fine since months ago.

But currently I have another SignalR client in a .Net Core 2.0 Console Application using the same version of  Microsoft.AspNet.SignalR.Client. It is connecting fine, but is not reciving messages from the hub connection. Is there any issue with this nuget in .Net Core? 

This is the code:

            var hubProxy = hubConnection.CreateHubProxy("MyHub");

            hubProxy.On("created", data =>
            {
                Console.WriteLine("Incoming Created  data: {0}", data);
            });

            hubProxy.On("deleted", data =>
            {
                Console.WriteLine("Incoming Deleted data: {0}", data);
            });

            hubConnection.Start().ContinueWith(x =>
            {
                hubProxy.Invoke("subscribe", "firstFeature", "secontFeature");
            }).Wait();

            Console.WriteLine("Connected to {0}", hubConnection.Url.ToString());

Thanks!

**Comment by Ryujose** [comment]
Hello @georginacm 

Try to do the question here https://github.com/aspnet/SignalR this repository is the one related to signalR net core.

Regards.

**Comment by georginacm** [comment]
Hi!

I already did it: https://github.com/aspnet/SignalR/issues/2156  and they redirected me here...

**Comment by anurse** [comment]
You are in the correct repo. So to clarify, since you brought up .NET Core, does this only fail when the SignalR client is used from a .NET Core application? I.e. does the same code work in .NET Framework?

Can you post an example that reproduces the issue?

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.

**Comment by amccool** [comment]
I would like to re-open this issue, as I nearly the exact scenario and "probably" the same failure.

net461 server running Microsoft.AspNet.SignalR" Version="2.2.3"
net461 client running Microsoft.AspNet.SignalR.Client" Version="2.2.3"

all is wonderful, connected with websockets, does a invoke (`call it subscribe or join group`)

but if I change the client project from
`    <TargetFramework>net461</TargetFramework>`
to
`    <TargetFramework>netcoreapp2.0</TargetFramework>`

I can get connected, but only with SSE, and I mostly get InvalidOperation exceptions when `invoke` is called.  Occasionally the `invoke` succeeded, but its unclear the scenario for success.

**Comment by amccool** [comment]
looks like I had a load balancer issue.   The connection was being made to one server, but invoke was going to a different server.  LB in question was an F5 big-ip, it needed default persistence setup.

**Comment by anurse** [comment]
> The connection was being made to one server, but invoke was going to a different server

This should be fine in ASP.NET SignalR as long as you have a backplane registered. See the scale-out documentation here: https://docs.microsoft.com/en-us/aspnet/signalr/overview/performance/scaleout-in-signalr

**Comment by amccool** [comment]
I dont have a backplane, and dont want one.   Each Server was supplied with a eventsource of equal data.  the group membership was the key `fault` that was corrected by getting the client to the right server.
