### ISSUE TITLE
Custom `IUserIdProvider` does not set `Context.User` for anonymous requests

### ISSUE THREAD

**Issue by cyberjacob** [SignalR/SignalR#4104]
### Expected  behavior
A custom implementation of `IUserIdProvider` should set the `Context.User` for anonymous requests, allowing access to the returned value as `Context.User.Identity.Name`.

### Actual behavior
`Context.User` remains null.

### Steps to reproduce
Create a hub with anonymous access and implementation of `IUserIdProvider`.

**Comment by anurse** [comment]
The UserID provider is not for setting `Context.User`, it's extracting a value **from** `Context.User` that can be used by `Clients.User(...)`. The only way to set `Context.User` is through authentication.
