### ISSUE TITLE
How to change ajax content type

### ISSUE THREAD

**Issue by zsybupt** [SignalR/SignalR#4111]
Hi, I recently test my code in my test environment, and the server do not support WebSocket, and the transport roll back to ServerSentEvents automatically, some of the data became invalid because some data are Base64 encoded and the "+" is translated to " " with content-type= **"application/x-www-form-urlencoded; charset=UTF-8"**
Is it possible to change the content-type?

**Comment by zsybupt** [comment]
My arguments has a json object, in order to solve this issue, maybe I need to go through the object recursively to encode the key and value, otherwise, maybe the payload should do a encodeURIComponent in ajaxSend?
` xhr = transportLogic.ajax(connection, {
                url: url,
                type: connection.ajaxDataType === "jsonp" ? "GET" : "POST",
                contentType: signalR._.defaultContentType,
                data: {
                    data: encodeURIComponent(payload)
                },
                success: function (result) {
                    var res;

                    if (result) {
                        try {
                            res = connection._parseResponse(result);
                        }
                        catch (error) {
                            onFail(error, connection);
                            connection.stop();
                            return;
                        }

                        transportLogic.triggerReceived(connection, res);
                    }
                },
                error: function (error, textStatus) {
                    if (textStatus === "abort" || textStatus === "parsererror") {
                        // The parsererror happens for sends that don't return any data, and hence
                        // don't write the jsonp callback to the response. This is harder to fix on the server
                        // so just hack around it on the client for now.
                        return;
                    }

                    onFail(error, connection);
                }
            });`

**Comment by anurse** [comment]
Unfortunately the `Content-Type` value is set this way for compatibility. The recommended solution to this is to ensure a URL-safe encoding yourself before sending the message.
