### ISSUE TITLE
Unresponsive after few hours/days - No events nor signals received

### ISSUE THREAD

**Issue by jandieg** [SignalR/SignalR#4112]
Client: SignalR version 2.2.3 on a Windows Forms app
Server: Windows Azure App Service

### Expected  behavior
The **StateChanged** must report any change of state.

### Actual behavior
After running fine for a while (5 hours or so), suddenly stops receiving signals from server. The **ConnectionState** reports as 'Connected' but nothing is received.

### Steps to reproduce
- Execute version 2.2.3 on a Windows Desktop Forms app
- Setup a CreateHubProxy with an event
- Fire the event, note the reception
- Wait few hours, or days
- Note no StateChanged event is raised
- Fire the event, never get reception
- Check ConnectionState says 'Connected'

**Comment by anurse** [comment]
Are you using a scale-out system like Redis to support multiple servers? We just fixed a major issue in scale-out that occurs in exactly this kind of situation. Can you try the latest version (`2.3.0`) and see if your issue is resolved?

**Comment by jandieg** [comment]
Hi anurse, not sure how it works internally but I am using Azure auto-swap slots. Means that a new build of the app is deployed, warmed up, and then swapped with the current one. Will try 2.3.0

**Comment by anurse** [comment]
Do you have more than one instance in each slot? If so you'll need to have a backplane (like Redis). If you've only got one server at active at a time, then this may be something different.

**Comment by anurse** [comment]
Also: has a deployment slot swap happened during this time window?

**Comment by jandieg** [comment]
It is only one instance. Yes slot swaps several times.

**Comment by anurse** [comment]
What transport are you using on the client that loses the connection? When you swap servers like that, existing long-running connections (like WebSockets) may stay connected to the old server (it depends on how Azure App Service works), so even though other connections are sending messages, they are being sent to the new server and the existing client isn't getting them anymore.

I'm not sure how Auto Swap slots handles existing connections. Ideally you want a system that terminates existing connections after the swap completes, which would cause SignalR to try reconnecting, and it would connect to the new server.

**Comment by jandieg** [comment]
Just using the defaults of the dll for Winforms app.
But swap is not the problem, it works ok.
This other problem only happens after long periods, or maybe upon other kinds of network changes.
Only way I found to keep it alive is by client reconnecting every 3 minutes.

**Comment by anurse** [comment]
> But swap is not the problem, it works ok.
> This other problem only happens after long periods, or maybe upon other kinds of network changes.

The swap itself may execute successfully, but if the swapped-out server is still running, SignalR may stay connected. Does the issue occur at all if the swapping is disabled? Could you collect [client-side traces](https://docs.microsoft.com/en-us/aspnet/signalr/overview/testing-and-debugging/enabling-signalr-tracing#javascript) from the period immediately before, during and after the connection loss?

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
