### ISSUE TITLE
Memory leak in signalr.core.js

### ISSUE THREAD

**Issue by kunalgarg1986** [SignalR/SignalR#4116]
# Issues related to the Asp.NET Core version of SignalR should be filed in the corresponding SignalR repo: https://github.com/aspnet/?utf8=%E2%9C%93&query=Signalr

### Expected  behavior
When stopping the connection, all jquery events should be unbind or user should have a way to unregister all events.

### Actual behavior
User can subscribe to many events like connection slow, reconnecting. However there is no way to unsubscribe. This cause memory leak after stopping the connection

**Comment by davidfowl** [comment]
Stopping the connection doesn't remove event handlers by design. You need to call unbind if you want to remove the event handlers. There's no leak if you only wire up the events once. What are you doing that's causing those events to be re-bound every time?

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
