### ISSUE TITLE
HubPipeline not functional using dependency injection

### ISSUE THREAD

**Issue by arijoon** [SignalR/SignalR#4117]
Using .NetCore dependency injection extensions, the HubPipeline will not work:

```cs
// In Configure
app.UseSignalR(routes =>
{
...
});

// In ConfigureServices
services.AddSignalR();
```

### Expected  behavior
An instance of IHubPipeline to be added to the DI to add modules to it
```cs
// In Configure
GlobalHost.HubPipeline.AddModule(new ErrorHandlingModule());
//OR
app.ApplicationServices.GetService<IHubPipeline>().AddModule(new ErrorHandlingModule());

```

### Actual behavior
No IHubPipeline instances bootstrapped and the GlobalHost instance does not work or get used

**Comment by davidfowl** [comment]
I'm not sure what you mean. You can't use the new ASP.NET Core SignalR with ASP.NET SignalR. What exactly are you trying to do?

**Comment by arijoon** [comment]
I see, my bad, that must be the issue, mixing up Core Signal R with the ASP.NET version.
