### ISSUE TITLE
Please add WebRTC support

### ISSUE THREAD

**Issue by AceHack** [SignalR/SignalR#4122]
I would like to use SignalR as a mediator/rendezvous/fallback for WebRTC.  It would be great if I could facilitate direct peer to peer communications via signal r.

I realize this is a big enhancement.

Thanks for all your hard work.

**Comment by anurse** [comment]
We don't have any plans to add WebRTC support to ASP.NET SignalR. It looks like you also filed this in the repo for ASP.NET Core SignalR, and we can consider it there, but we don't plan to add major features like this to ASP.NET SignalR at this time.
