### ISSUE TITLE
win 10 iot simple example fail

### ISSUE THREAD

**Issue by BucurCosmin** [SignalR/SignalR#4125]
Using RPI with win 10 iot with 17134 build, a simple example with UWP client fail with:
 connection = new HubConnectionBuilder()
            .WithUrl("https://localhost:5000/MessagingUWP/SendMessage1")
            .Build();

the error is:
System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.'

**Comment by moozzyk** [comment]
Looks like this is ASP.NET Core so should go to this repo: https://github.com/aspnet/SignalR

**Comment by moozzyk** [comment]
Actually it might be a dupe of https://github.com/aspnet/SignalR/issues/2406

**Comment by anurse** [comment]
Closing, as this is indeed a duplicate.
