### ISSUE TITLE
Unhandled exception in override of HubBase.OnDisconnected(bool) causes SignalR to leak memory

### ISSUE THREAD

**Issue by BigBadBleuCheese** [SignalR/SignalR#4126]
# Formal bug report

## Expected behavior

Allowing an exception to travel up the call stack from a hub's `OnDisconnected(bool)` override does not, in any circumstance, cause SignalR to retain internal buffers and/or meta data for a given connection indefinitely.

## Actual behavior

Allowing an exception to travel up the call stack from a hub's `OnDisconnected(bool)` override will cause SignalR to retain internal buffers and/or meta data for a given connection indefinitely if the client subscribed to events on the hub, therefore causing SignalR to invoke the connection lifecycle virtual methods of `HubBase`.

## Steps to reproduce

1. Throw an exception inside the `OnDisconnected(bool)` override of a hub
2. Override `HubBase.OnConnected` to trigger at least one thousand events with large arguments on the connected client, causing SignalR to fill its internal ring buffer for the connection with some bulky data (this is not done to cause the problem, merely to exagerate its effect so it can be more easily seen when profiling memory), then raise another event to signify when this process is finished
3. Create a proxy for the hub in the client and subscribe to the signal event, instructing the client to then disconnect by invoking the hub connection object's stop method or function
4. Execute the following test:
    1. Start the server and take a memory snapshot with the debugger or a profiler
    2. Start the client and let it run until finished
    3. Take a snapshot after the period at which the connection should have been ruled as disconnected and cleaned up

# Included example

[This ZIP archive](https://github.com/SignalR/SignalR/files/2060409/SignalRDisconnectTest.zip) contains a clone of the SignalR repository, but with disconnect test server and client projects added, as well as a new solution file that incorporates them. This was done so that it would be possible to step into SignalR and experiment with changes made to it (although this archive contains no such changes to SignalR). The server automatically forces a GC every second to make it possible to just watch memory usage over time without the developer forcing GC's via taking snapshots herself.

The server will ask the developer to select from among three testing modes:

* Normal: do not throw any exceptions in the `OnDisconnected(true)` override
* Throw: throw an exception in the `OnDisconnected(true)` override
* FaultedTask: return a faulted task from the `OnDisconnected(true)` override (such as what would occur if the method were decorated with async and the throw took place after an await)

Here are screenshots of the Visual Studio 2017 memory profiler displaying my results when running the server in each of these modes.

Normal:
![normal](https://user-images.githubusercontent.com/25014958/40812822-e115e9f2-6505-11e8-929b-7625f1f42c3d.png)

Throw:
![throw](https://user-images.githubusercontent.com/25014958/40812832-e6b5b31a-6505-11e8-8298-9f369425bd82.png)

Faulted Task:
![faultedtask](https://user-images.githubusercontent.com/25014958/40812835-eb2b7d6c-6505-11e8-9055-9e6ba639b77b.png)

# A final word

I sincerely hope that no one accuses me of being lazy! ;)

I started with the intention of creating a PR to fix this problem. Unfortunately, finding exactly where to fix it elluded me, leaving aside the question of how. So, here I am, reporting what I know and providing the community with the test bench with which I replicated the issue in the hope that someone better than me can pick up where I left off and score a touchdown.

**Comment by anurse** [comment]
Thanks for the report @BigBadBleuCheese ! I think I managed to get that touchdown in #4248. We really appreciate the detailed approach, and the repro project was extremely helpful!
