### ISSUE TITLE
SignalR future

### ISSUE THREAD

**Issue by cblaze22** [SignalR/SignalR#4127]
This is a simple question, but we are needed a library like SignalR since we are using .NET.  My question is, is this project going to be around for a while?  I assume it's not losing steam, and version 3 might be coming out also soon.  I don't want to pick a library that may not have much contribution within a year.

**Comment by MatthewSteeples** [comment]
As Microsoft are in the process of launching a managed backend for it (https://azure.microsoft.com/en-us/services/signalr-service/) I'd say it's going to be around for a while!

**Comment by cblaze22** [comment]
Awesome!

**Comment by anurse** [comment]
We shifted our focus to ASP.NET Core for a while, as may have observed. [ASP.NET Core has it's own version of SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/introduction?view=aspnetcore-2.1)

Having said that, we're now looking to bring some love to ASP.NET SignalR (this library) for those still using ASP.NET 4.x. More details will be coming soon.

If you are building a new web application using .NET I'd strongly recommend you consider [ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-2.1) and the version of SignalR it provides.

Closing this as the question has been answered. Feel free to comment further if you need clarification on something! We can always re-open the issue if there's something to fix here.
