### ISSUE TITLE
Idea to update jQuery?

### ISSUE THREAD

**Issue by 1Jesper1** [SignalR/SignalR#4129]
Idea to update the jQuery package?

https://github.com/SignalR/SignalR/blob/d659127dc411af94d029188d98eb7bdfca80886f/src/Microsoft.AspNet.SignalR.Client.JS/packages.config#L3

**Comment by anurse** [comment]
SignalR doesn't set a maximum bound on the jQuery package we reference. We reference `>= 1.6.2` because the lowest version we work with is `1.6.2` but you're free to upgrade. We won't be increasing this version because that would block the usage of SignalR with older versions of NuGet.
