### ISSUE TITLE
Clients.All.myJsfunction cannot trigger the function in js file

### ISSUE THREAD

**Issue by Kriegthor23** [SignalR/SignalR#4130]
so Here is my issue

i might be doing something wrong but what i basicly try is im trying to connect two peers with a video chat
and while i try that in text chat part i use

in ChatHub.cs part
public void Send(string name, string message)
{
// Call the broadcastMessage method to update clients.
Clients.All.broadcastMessage(name, message);
}
and corresponding JS part of it

chat.client.broadcastMessage = function (name, message) { //my function does is job }

and this works very well

but for video call
in ChatHub.cs

some function in ChatHub calls

    public void GetConnectionIDandSet()
    {
        var users = JsonConvert.SerializeObject(ConnectedUsers);
        Clients.All.getConnectionIDandSet(users);
    }
and corresponding JS part of it

chat.client.getConnectionIDandSet = function (users) { // do the job }

and when i try to debug it on console
Clients.All.getConnectionIDandSet(users); does not trigger

chat.client.getConnectionIDandSet = function (users) { // do the job }

so what am i doing wrong at here

Versions of Server-Side NuGet Packages: SignalR 2.2.3
Versions of Client-Side NuGet/NPM Packages: SignalR 2.2.3
Are you using the C# client or the JavaScript client:
The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): IIS Express
The Operating System on the Server (Windows/Linux/macOS): Windows
The Operating System on the Client (Windows/Linux/macOS): Windows
The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): Chrome 66.0.3359.181 (official) (64 bit)
The gist for full project
https://gist.github.com/Kriegthor23/54c1a246cba6e9fb9096c161edc99a59

Thanks for helps in advance
And if this is a dupp of an issue maybe i missed in closed sections i appologize from the members in advance

opening in the right repo this time

**Comment by Kriegthor23** [comment]
well found the solution actually i had to put the querystrings before the connection but still even it triggers 
the function CreateAnswer does not happens and video chat does not start
 guess need to edit the gist and maybe the title of the issue

**Comment by anurse** [comment]
Can you clarify this issue? There's a lot of code in your example, and I don't understand from your description how it's supposed to all connect together. Can you reduce this down to a simple example that illustrates the failure you're seeing?

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
