### ISSUE TITLE
AsyncManualResetEvent. which performance is better?and the differences between the two implementation

### ISSUE THREAD

**Issue by stacklesshaha** [SignalR/SignalR#4134]
https://github.com/SignalR/SignalR/blob/dev/tests/Microsoft.AspNet.SignalR.Tests.Common/Infrastructure/AsyncManualResetEvent.cs

**I found a different implementation of AsyncManualResetEvent from here**

 https://github.com/StephenCleary/AsyncEx/blob/master/src/Nito.AsyncEx.Coordination/AsyncManualResetEvent.cs

I think the latter is better in view of one article here

https://blogs.msdn.microsoft.com/pfxteam/2012/03/24/should-i-expose-asynchronous-wrappers-for-synchronous-methods/

can someone  reply .thanks a lot

**Comment by anurse** [comment]
The AsyncManualResetEvent in SignalR is not designed for general use. It's just there to support SignalR development. I'd definitely suggest using Stephen's version in your own applications.

Closing this as the question has been answered. Feel free to comment further if you need clarification on something! We can always re-open the issue if there's something to fix here.
