### ISSUE TITLE
Cann't send System.Type to clients

### ISSUE THREAD

**Issue by Mansu12135** [SignalR/SignalR#4135]
Hi everyone,

I need to send Dto which consists from object and type of this object. When I remove System.Type from this Dto my clients recive the input message. It's possible to transfer type from server to client?

**Comment by anurse** [comment]
It's not possible to send a `System.Type` value by default. In general, only primitives (`string`, `int`, etc.), Dictionaries (`IDictionary`), Lists/Arrays (`IEnumerable`) and objects made up of only those types can be sent.

Sending the type of an object along with the value is generally very dangerous as it allows a malicious client to send any type they want and your code might try to create an instance of that object.

If you need to support different kinds of objects, you should send your own custom "type" value, which is restricted to only the values you expect to see on the server. As always with Web development, never trust what the client sends you, always verify it.

Closing this as the question has been answered. Feel free to comment further if you need clarification on something! We can always re-open the issue if there's something to fix here.
