### ISSUE TITLE
SIgnalR not working in Edge

### ISSUE THREAD

**Issue by strrranger** [SignalR/SignalR#4138]
I have a simple hub with two methods
``` C#
public class LobbyKioskHub : Hub
{
	public async Task RefreshKiosk(Guid kioskID, bool soft)
	{
		await Clients.Group(kioskID.ToString()).refreshClient(soft);
	}

	public Task JoinGroup(Guid kioskID)
	{
		return Groups.Add(Context.ConnectionId, kioskID.ToString());
	}
}
```
And simple client code
``` javascript
var settings = { transport: ['webSockets', 'serverSentEvents', 'longPolling'] };
var onHubConnection = function () {
	console.log("Hub connected");
	$.connection.lobbyKioskHub.server.joinGroup(token)
}
$.connection.hub.start(settings)
	.done(onHubConnection)
	.fail(function () { console.log('SignalR could not Connect!'); });
			
$.connection.lobbyKioskHub.client.refreshClient = function (soft) {...}
```
### Expected  behavior
refreshClient function should be trigerred for all clients with specific token every time when I have called `$.connection.lobbyKioskHub.server.refreshKiosk(token, true)`.
### Actual behavior
It works for Chrome, IE and not working in Edge.
### Steps to reproduce
It works on IISExpress locally but when I publish that code to Azure it stop working in edge.

**Comment by moozzyk** [comment]
Make sure you enable websockets on Azure (although the longpolling transport should kick in). Edge does not support serverSentEvents AFAIR.

**Comment by strrranger** [comment]
@moozzyk WebSockets is enabled. Something else causes that problem.

**Comment by anurse** [comment]
Can you enable client tracing using the instructions here: https://docs.microsoft.com/en-us/aspnet/signalr/overview/testing-and-debugging/enabling-signalr-tracing#enabling-tracing-in-the-javascript-client ?

Once that's enabled, can you check the browser console and see if there are any errors reported there?

**Comment by strrranger** [comment]
No errors. All the same as in other browsers.

**Comment by anurse** [comment]
Are there any messages reported at all? Even non-error messages? I'll try to test this today and see if I can reproduce it.

**Comment by anurse** [comment]
I just tried running our Chat sample app with Edge (which uses groups) and I'm not seeing any errors. Can you post a complete sample that reproduces the issue? We need to try and track down what might be different.  It might also help to collect network traces. You can do this in Edge using the Dev Tools. Just open the Network tab, run the test and collect network traffic. Once that's done you can export the trace using the save icon:

![Edge Network Tab Save Icon](https://user-images.githubusercontent.com/7574/39794415-0d58deb6-52ff-11e8-9949-cea9f7840151.png)

Save the file with a `.txt` extension and drag and drop it on to the comment box in GitHub to attach it.

**Comment by strrranger** [comment]
Hi guys. Sorry for bothering you. I have tested app again and today it starts working in the edge. Looks like Azure has fixed something because I have tested on multiple devices and it's not working before today.

**Comment by mmmert2** [comment]
I'm so bored of this damn thing.
