### ISSUE TITLE
Install SignalR on angular 5 app.

### ISSUE THREAD

**Issue by TomBuyvoets** [SignalR/SignalR#4139]
### Expected  behavior

SignalR will install without errors

### Actual behavior

When I install SignalR in my angular 5 project I get errors saying 'unmet-peer-dependency @angular/core@5.2.11"

I think the SignalR package is not up to date for angular 5?
Is this right?

### Steps to reproduce
npm install signalr

**Comment by anurse** [comment]
The signalr NPM package is not officially published by us, so while it's possible there's an authoring bug there, there's not a lot we can do there.

Can you post your `package.json` so I can see what packages you have installed and try to reproduce this issue?

**Comment by TomBuyvoets** [comment]
I have create a new angular project and install signalr without errors. But when I build a connection, It throws errors in console.

'ERROR TypeError: signalr_1.HubConnectionBuilder is not a constructor'

my package.json:
``` json
{
  "name": "signalr-test",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "core-js": "^2.4.1",
    "jquery": "^3.3.1",
    "rxjs": "^5.5.6",
    "signalr": "^2.2.3",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "~1.7.1",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
}
```

my app.component.ts:

``` javascript
import { Component, OnInit } from '@angular/core';
import { HubConnectionBuilder } from 'signalr';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'app';

  ngOnInit() {
    var connection = new HubConnectionBuilder()
      .withUrl('http://localhost:6182/signalr')
      .build();
    connection
      .start()
      .then(() => console.log('Connection started!'))
      .catch(err => console.log(err));

    connection.on('finishedJob', () => {
      console.log('Het is gelukt')
    });
  }
}
```

**Comment by BrennanConroy** [comment]
Which version of SignalR are you trying to use? Your npm reference is for ASP.NET SignalR (this repo), but the code you're trying to write is for ASP.NET **Core** SignalR (https://github.com/aspnet/SignalR).

The two versions are not compatible.

**Comment by TomBuyvoets** [comment]
@BrennanConroy 
Do I have to do this to setup a connection? I must use the webapi version, not the Core version
``` typescript
this._hubConnection = new HubConnection(myUrl)
```

@anurse I dont know where I can find the package id's.

This are the includes in de package.config in my api.
``` xml
  <package id="Microsoft.AspNet.SignalR" version="2.2.3" targetFramework="net461" />
  <package id="Microsoft.AspNet.SignalR.Core" version="2.2.3" targetFramework="net461" />
  <package id="Microsoft.AspNet.SignalR.JS" version="2.2.3" targetFramework="net461" />
  <package id="Microsoft.AspNet.SignalR.SystemWeb" version="2.2.3" targetFramework="net461" />
```

**Comment by TomBuyvoets** [comment]
I also tried this:

``` typescript 
ngOnInit() {
    var connection = new  HubConnection();
    connection
      .start()
      .then(() => console.log('Connection started!'))
      .catch(err => console.log(err));

    connection.on('finishedJob', () => {
      console.log('Het is gelukt')
    });
  }
```
Then I get an error:
ERROR TypeError: signalr_1.HubConnection is not a constructor

I think this is due to the issue above.  (SignalR import error)

**Comment by anurse** [comment]
Ok, so the package IDs on the server are for ASP.NET SignalR (this repo).

The errors you're getting are because you are using the wrong APIs, those APIs don't exist in that package. I'm not sure what documentation you're following to get those APIs. Those APIs are for ASP.NET **Core** SignalR, which requires that you are running ASP.NET **Core** on the server.

> Try npm install @types/signalr if it exists or add a new declaration (.d.ts) file containing `declare module 'signalr';

The above instructions were listed in the error message you are getting. Did you try those instructions? When using an npm module from TypeScript you need to import type definitions for the module in order to access the API.

I'd strongly suggest walking through one of the [getting started guides](https://docs.microsoft.com/en-us/aspnet/signalr/overview/getting-started/) on the docs before jumping straight in to usage in Angular if you aren't familiar with the SignalR JavaScript client. It's not as simple as just importing a module, since it is a jQuery Plugin.

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
