### ISSUE TITLE
Missing SignalR library

### ISSUE THREAD

**Issue by hnikolas** [SignalR/SignalR#4143]
After upgrading to signalR  2.3.0., the libraries are missing.
That is, the js jquery-signalR-2.3.0.js is not included in the update

**Comment by anurse** [comment]
Can you provide more detail? How did you update? The official JavaScript client package (https://www.nuget.org/packages/Microsoft.AspNet.SignalR.JS/) shows a `jquery-signalR-2.3.0.js` file within it and I get that file when I install it into a project.

**Comment by hnikolas** [comment]
The js files were not loaded in the project. Once I manually load them the signalr service works without any issue.
Many thanks for your support

**Comment by anurse** [comment]
I'm still a little confused and would like to understand the issue in case other run in to this. Can you clarify which packages you updated (specific package IDs) and what script files you had before the update?

**Comment by hnikolas** [comment]
When I updated from SignalR-2.2.3 to version 2.3.0 I couldn't find the js files. Note that I updated the following packages:
- Microsoft.AspNet.SignalR
- Microsoft.AspNet.SignalR.Core
- Microsoft.AspNet.SignalR.JS
- Microsoft.AspNet.SignalR.SystemWeb

After searching further, I realized that whilst the latest js files where downloaded, they were not loaded in the project. So I had to manualy load the js files in order signalR to operate as normal

**Comment by anurse** [comment]
Interesting. Thanks for the details, that helps a lot. So the files were placed on disk but not added to the project? Glad you were able to get the scripts, and thanks for the extra info!

**Comment by anurse** [comment]
Closing this as the discussion appears to have concluded. Feel free to comment further if you have additional concerns, we can always open new issues to track work to do.
