### ISSUE TITLE
Task exception thrown by finalizer thread on Redis failures.

### ISSUE THREAD

**Issue by salehio** [SignalR/SignalR#4144]
We are running a service hosting SignalR (2.2.3) in Azure Cloud Service (Classic) with OWIN and for the most part, everything seems to be running fine. We are using SignalR.Redis.2.2.3 for scaleout.

Every now and then we see the following exception bubbling up to the top:

```
Type: System.AggregateException
Message: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.
ToString: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.
```
With an inner exception:
```
Type: StackExchange.Redis.RedisConnectionException
Message: No connection is available to service this operation: EVAL; SocketClosed on ams-usea-1-red-cms-1-1.redis.cache.windows.net:6380/Subscription, origin: ProcessReadBytes, input-buffer: 0, outstanding: 0, last-read: 0s ago, last-write: 30s ago, unanswered-write: 514721s ago, keep-alive: 60s, pending: 0, state: ConnectedEstablished, in: 0, ar: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, mgr: Inactive, err: never; IOCP: (Busy=2,Free=998,Min=4,Max=1000), WORKER: (Busy=3,Free=32764,Min=4,Max=32767), Local-CPU: n/a
ToString: StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: EVAL; SocketClosed on ams-usea-1-red-cms-1-1.redis.cache.windows.net:6380/Subscription, origin: ProcessReadBytes, input-buffer: 0, outstanding: 0, last-read: 0s ago, last-write: 30s ago, unanswered-write: 514721s ago, keep-alive: 60s, pending: 0, state: ConnectedEstablished, in: 0, ar: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, mgr: Inactive, err: never; IOCP: (Busy=2,Free=998,Min=4,Max=1000), WORKER: (Busy=3,Free=32764,Min=4,Max=32767), Local-CPU: n/a ---> StackExchange.Redis.RedisConnectionException: SocketClosed on ams-usea-1-red-cms-1-1.redis.cache.windows.net:6380/Subscription, origin: ProcessReadBytes, input-buffer: 0, outstanding: 0, last-read: 0s ago, last-write: 30s ago, unanswered-write: 514721s ago, keep-alive: 60s, pending: 0, state: ConnectedEstablished, in: 0, ar: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, mgr: Inactive, err: never
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException)
   at Microsoft.AspNet.SignalR.Owin.OwinWebSocketHandler.<>c__DisplayClass5_0.<<RunWebSocketHandler>b__0>d.MoveNext()
StackTrace:
    at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException)
   at Microsoft.AspNet.SignalR.Owin.OwinWebSocketHandler.<>c__DisplayClass5_0.<<RunWebSocketHandler>b__0>d.MoveNext()
Data - redis-command: EVAL
Data - request-sent-status: WaitingToBeSent
```

Given the nature of web services, I do expect Redis to sometimes be unavailable, and this is normal behavior. Things seem to recover fine afterwards.

But is there a way to prevent these exceptions from bubbling to the top? Our application has a global exception handler to prevent the application from crashing, but we would prefer it if this can be caught downstream.

### Expected  behavior
A (possibly configurable) exception handler that logs these errors and does not throw task exceptions. Preferably logs to one of the hooked up providers.

### Actual behavior
Task exception is thrown to the top of the application.

### Steps to reproduce
No repro steps yet, but I'm guessing exercising SignalR with Redis backplane and taking down Redis would trigger this.

**Comment by anurse** [comment]
The exceptions should be benign (in that they shouldn't crash the application), but I can understand if they feel like noise. The issue here is identifying the most flexible behavior. I'd definitely encourage you to gather telemetry on these kinds of exceptions since even if they are benign, they do indicate the possibility of a lost message, so tracking them is important. I don't think we'd want to completely suppress the exception since that would restrict a user's ability to gather that data.

The main option I'd suggest is to simply filter out the exception by type (`RedisConnectionException`; of course you may have to dive into `AggregateException` to find it as you noticed) if you aren't interested in catching it.

> Our application has a global exception handler to prevent the application from crashing

Can you clarify exactly which handler (which class and member are you attaching a handler to) is getting the exception right now? I'd like to understand exactly where the exception is escaping to :)

**Comment by salehio** [comment]
Yes, the ideal thing to do here would be to have an exception handler that can be configured by the user. Then they should be able to log these things gracefully. Currently, this error was surfaced on our side via System.Threading.Tasks.TaskScheduler.UnobservedTaskException delegate exception handler. Since this task was a fire and forget somewhere in the SignalR stack, the delegate was called, and we logged it as an error.

**Comment by anurse** [comment]
> the ideal thing to do here would be to have an exception handler that can be configured by the user

Isn't this what `TaskScheduler.UnobservedTaskException` is?

**Comment by salehio** [comment]
While this can be used, it is still considered an ungraceful exit. Technically, the application is normally killed when it hits this point. Currently, we are specifically calling SetObserved() on the unhandled task exception to prevent it from killing our role.

Normally, if a library is dealing with fire-and-forget code, they will do a ContinueWith() call on the resulting task, and handle exceptions there. If the user should be notified of an exception, the exception can be routed to an error handler where a user can log, and possibly take action. Throwing all the way to the top indicates to me that you are in a dead state, and I should either reload SignalR somehow, or I should reboot my instance. But in the case of this exception, everything continues to go smoothly after Redis recovers.

**Comment by anurse** [comment]
> Technically, the application is normally killed when it hits this point.

Ok, this is new information. So the application crashes if you don't explicitly observe this exception in the `TaskScheduler.UnobservedTaskException` handler?

**Comment by anurse** [comment]
Ah, I see, so it does crash the process in .NET 4.0 but it shouldn't be crashing in .NET 4.5. We'll consider what we could do about this.l

**Comment by anurse** [comment]
> Starting with the .NET Framework 4.5, you can use the configuration element to revert to the behavior of the .NET Framework 4 and terminate the process:

SignalR requires .NET 4.5 or higher, can you clarify if you've configured this behavior? We generally avoid suppressing these exceptions because we're designed to run in the .NET 4.5 environment, where the process doesn't crash (and you will likely want to log the failure).

**Comment by salehio** [comment]
We do not allow the process to crash (even when we were operating on .NET 4, since we observed the exception).

But allowing exceptions to bubble up to the Unobserved task exception handler is a misuse of the handler. It is there to shed light on unexpected issues.

I agree that users need this information. We currently log this data and actively use it to diagnose issues. The correct way to do this would be to expose a delegate in the SignalR library where these unhandled task exceptions are routed to. That way I don't have to sift through stack traces to determine if this is an exception coming from the SignalR stack. Right now if I get a redis exception, I have to look at the stack trace to see if this is coming from my SQL cache (due to bad code that I will eventually fix to no longer show up in the exception handler) or SignalR. But if SignalR task exceptions were routed to a SignalR exception handler, I would know the origin of these exceptions.

If done right, I would expect every Task that doesn't have an associated await to have a ContinueWith (or a more modern routing method) to push it into an exception handler that is configurable by the user.

**Comment by anurse** [comment]
Hrm, are you `await`ing or otherwise observing the tasks returned by calls to `Clients.[signal].[method]` (i.e. `await Clients.All.foo()`)? Errors sending messages through Redis are flowing up through that task when I try and the only time they fire the `UnobservedTaskException` event is when they aren't observed in the hub code itself.

It's a little unclear because of `dynamic` (one on many reasons we moved away from `dynamic` in ASP.NET Core SignalR 😸 ) but calls to `Clients.All.foo()` (and friends) return `Task`s. If you `await` the task, your Hub method will throw and SignalR will observe the exception for you, but if you don't `await` the task, or observe the exception yourself, then the Task is left dangling and the `UnobservedTaskException` event will be called when the Task is garbage collected.

**Comment by anurse** [comment]
The docs aren't very clear on this need to `await` the task though, I'll look in to updating that.

**Comment by anurse** [comment]
It looks like this is a documenation issue, based on my findings above. @salehio, let me know if `await`ing (or otherwise observing exceptions) on the Tasks returned by `Clients.All.foo()` (etc.) doesn't fix your issue and we can dig deeper to see if there are any other exceptions going unobserved.

**Comment by salehio** [comment]
Hey, thanks for the response.

I would like to point out that we currently do await all SignalR calls (even Groups.Add where we were advised to not await, we still observe the tasks there)

But looking at the inner stack trace at the top of this issue, it is not apparent that this is coming from our stack, since the base of the exception is the SignalR owin module. Since we do not explicitly call into that, it implies to me that there might be something there that isn't awaiting. Do you agree?

**Comment by anurse** [comment]
> I would like to point out that we currently do await all SignalR calls (even Groups.Add where we were advised to not await, we still observe the tasks there)

Awesome, glad to hear that. That should mean most of these are properly observed.

Async stacks have a lot of quirks and I think this one is misleading us, unfortunately. The stack trace doesn't really make sense since those two frames are completely unrelated. Nothing in `OwinWebSocketHandler` calls this method.

```
at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException)
at Microsoft.AspNet.SignalR.Owin.OwinWebSocketHandler.<>c__DisplayClass5_0.<<RunWebSocketHandler>b__0>d.MoveNext()
```

We need to see if we can track down which task is going unawaited, because all the Redis calls I can dig up should have exceptions observed. Are you able to get a consistent repro for this? I realize you're seeing it intermittently, but I'm not able to get a repro from most of the scenarios I've tried so I'm looking to try and track down what might be different here.

**Comment by salehio** [comment]
Alright, I went ahead and took a look at some other unhandled task exceptions that contain SignalR in the stacktrace. One of the stack traces we're seeing is:

```
Type: System.AggregateException
Message: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.
ToString: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: EVAL; SocketClosed on <REDACTED>.redis.cache.windows.net:6380/Interactive, origin: ProcessReadBytes, input-buffer: 0, outstanding: 0, last-read: 0s ago, last-write: 0s ago, unanswered-write: 48425s ago, keep-alive: 60s, pending: 0, state: ConnectedEstablished, in: 0, ar: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, mgr: Inactive, err: never; IOCP: (Busy=2,Free=998,Min=4,Max=1000), WORKER: (Busy=1,Free=32766,Min=4,Max=32767), Local-CPU: n/a ---> StackExchange.Redis.RedisConnectionException: SocketClosed on <REDACTED>.redis.cache.windows.net:6380/Interactive, origin: ProcessReadBytes, input-buffer: 0, outstanding: 0, last-read: 0s ago, last-write: 0s ago, unanswered-write: 48425s ago, keep-alive: 60s, pending: 0, state: ConnectedEstablished, in: 0, ar: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, mgr: Inactive, err: never
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException)
   at Microsoft.AspNet.SignalR.Messaging.ScaleoutStream.Send(Func`2 send, Object state)
   at Microsoft.AspNet.SignalR.Infrastructure.Connection.Send(ConnectionMessage message)
   at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.Outgoing(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.<>c__DisplayClass6_0.<BuildOutgoing>b__0(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.<>c__DisplayClass6_0.<BuildOutgoing>b__0(IHubOutgoingInvokerContext context)
   at Microsoft.AspNet.SignalR.Hubs.HubPipelineModule.<>c__DisplayClass6_0.<BuildOutgoing>b__0(IHubOutgoingInvokerContext context)
   at <REDACTED>.<PublishToAudienceAsync>d__7`1.MoveNext() in E:\bt\926734\<REDACTED>.cs:line 0
   at <REDACTED>.<>c__DisplayClass5_0.<<PublishNotificationAsync>b__0>d.MoveNext() in E:\bt\926734\<REDACTED>.cs:line 96
```
REDACTED here implies namespaces from my service.

As you can see, my code is showing up in that stack trace. I'm not sure if this is the same issue, but maybe it will help figure out where the other unobserved exceptions are coming from.

`PublishNotificationAsync()` essentially does the following
```
                    await hubConnection.Group("MyGroupName")
                            .HandleNotification(notification.SchemaVersion, notification);
```
Here, hubConnection is of type `IHubConnectionContext<INotificationClient<Notification>>` where my INotificationClient defines the `HandleNotification` method (implemented client side).

Everything from `PublishNotificationAsync()` and upwards is properly awaited. I spent an hour quadruple checking that information. The code that calls `PublishNotificationAsync()` also calls all sorts of other async code, and there are no stack traces coming from those.

Does this new stack trace help out? Maybe it serves as a new entry point to investigate?

My lack of understanding of how these unobserved task exception stack traces are determined is making me hesitant to point fingers. On one hand, we have a stack trace where the root points at my code, while in the other it points at the OWIN extension owned by SignalR.

**Comment by anurse** [comment]
> Everything from `PublishNotificationAsync()` and upwards is properly awaited.

What's the "root" of this async operation (i.e. what triggers all this code to run)? An MVC Controller? `Task.Run`? Since you're using `IHubConnectionContext`, I presume this isn't a in a Hub method?

**Comment by salehio** [comment]
That's a great question. For all intents and purposes, there is a custom task scheduler we have that calls 
and awaits `PublishNotificationsAsync()`. We use this scheduler all over the place for many different types of calls. We never seen an unobserved task exception being emitted from it.

But I agree, it does sound sketchy. Our evidence here is 1-1 for where this problem is happening. I think if we understood what shows up in a stack trace under which circumstances, we'd be able to pinpoint the problem better. Is the missed await call at the root of the stack always?

**Comment by anurse** [comment]
> Is the missed await call at the root of the stack always?

Not necessarily. The bottom of the trace (top of the list, since stack traces are written bottom-to-top) will be where the exception occurs (obviously ;)) and the stack trace will continue up through any `await` calls. However, if you have code that passes around the faulted `Task`, you won't see that in the stack trace.

Is `<REDACTED>.<>c__DisplayClass5_0.<<PublishNotificationAsync>b__0>d.MoveNext()` the end of the trace or are there additional stack frames?

> We never seen an unobserved task exception being emitted from it.

To be clear, you mean you have seen exceptions get thrown from these calls but they **do not** yield unobserved task exceptions? One way to isolate things would be to try using your custom task scheduler to invoke a method that just returns `Task.FromException` with an exception and see if it results in an unobserved exception event (remember the event is only fired when the Task is garbage collected so it won't necessarily happen right away)

**Comment by anurse** [comment]
The docs issue is now resolved and I haven't heard back from you in a while about trying to track down where this unawaited task is. I'm going to close this for now as we're looking to wrap up the next milestone. If you're still seeing this problem and are able to identify an unawaited task in SignalR itself, let me know and we can re-open this!
