### ISSUE TITLE
Variance in hubs

### ISSUE THREAD

**Issue by granthoff1107** [SignalR/SignalR#4147]
I would like to register my hubs dynamically but there are some frustrations I'm encountering.  Hubs are too coupled. I would like more Variance.  Say I have a HubBase using options to know who and when to send.  If I Request My hub for a dependency like so:

        IHubContext<CRUDServiceHubBase<TDTO, TKey>> hubContext

In Order to Get this from my Service I would have to register with the Mapping:

        routes.MapHub<CRUDServiceHubBase<MessageDTO, string>>("/messages");

but If I want to create a wrapper for my CRUDServiceHub<TDTO> : CRUDServiceHub<TDTO, string> so my users can use a default implemetation

    routes.MapHub<CRUDServiceHubBase<MessageDTO>>("/messages");

But now when my user Requests  IHubContext<CRUDServiceHubBase<TDTO, TKey>> hubContext there won't be any client connected because I'm mapping my hubs to the wrapper.

Seeing as the interface has no dependency on the in puts or out puts using THub 

    public interface IHubContext<THub> where THub : Hub
    {
        IHubClients Clients { get; }
        IGroupManager Groups { get; }
    }

it would be nice if variance worked so if I requested a :

     IHubContext<CRUDServiceHubBase<MessageDTO, string>>

I could return a

    IHubContext<CRUDServiceHubBase<MessageDTO>> 

and just register in the implementations with the DI

**Comment by BrennanConroy** [comment]
Hi. It looks like this is a question about how to use SignalR. This repo is in maintenance mode and we only have the resources to fix major issues, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com/).
