### ISSUE TITLE
How to authenticate token from AAD in an aspnet core web api passed through signalR?

### ISSUE THREAD

**Issue by exztinct01** [SignalR/SignalR#4148]
First of all, I'm a bit new to web dev as a whole but I would like to ask this question since we''re using AAD authentication. I created an aspnet core React application and used the authentication scheme generated by aspnet core webapi on the backend and adal js on the frontend. So I added the code below in Startup.cs and `[Authorize]` in my controllers as well as my hubs.

     services.AddAuthentication(AzureADDefaults.BearerAuthenticationScheme)
                .AddAzureADBearer(options => Configuration.Bind("AzureAd", options));

From the client side, I attached the token to the headers of my ajax requests and they all work correctly. Below is the function I use to perform the fetch. The `adalApiFetch` function already adds the authorization inside it
        
         .......
         let response = yield adalApiFetch(axios, "api/securities", {
            method: "GET",
            headers: {
                "Content-Type": "application/json; charset=UTF-8",
                Accept: "application/json"
            }
        }).catch(function(error) {
          throw error;
        });
        .........

For the hubs, I'm using the code below

       const conn = new SignalR.HubConnectionBuilder().withUrl("/myhub", {
          accessTokenFactory: async () => {
              return await getApiToken();
          }
      }).build();

Like I said above, axios fetch and authentication works, but signalR does not. 
Chrome has the following logs

        WebSocketTransport.js:35 WebSocket connection to 'wss://localhost:5001/myhub id=................................&access_token=ey..........................
        failed: HTTP Authentication failed; no valid credentials available
        Error: Failed to start the transport 'WebSockets': undefined

And this is from Edge

        Error: Failed to start the transport 'WebSockets': undefined
        SCRIPT12008: SCRIPT12008: WebSocket Error: Incorrect HTTP response. Status code 401, Unauthorized

Can anyone please guide me on what I am missing?

**Comment by exztinct01** [comment]
I posted this issue yesterday in the aspnet/docs repo but I was pointed to here

Meanwhile, upon looking more at the application and the logs produced, as well as testing the connection itself, I found out it actually worked. However, the errors are still produced.

I decided to create a new application using the aspnet core react template. I added the AzureAD Bearer authentication (the one I showed in the post above), and put the `[Authorize]` tag in the ChatHub class. I also added `adal js` authentication on the react application using the `react-adal` library.

In connection builder, I did this

    const connection = new SignalR.HubConnectionBuilder()
      .withUrl("/chathub", {
        accessTokenFactory: async () => {
          let token = await adalGetToken(authContext, adalConfig.endpoints.api);
          return token;
        }
      })
      .build();
    // added handlers then connection.start().catch(err => console.error(err.toString()));

the connection succeeded but the errors in Chrome still occurred and the server logs below are produced

      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
            Request starting HTTP/1.1 POST https://localhost:5001/chathub/negotiate text/plain;charset=UTF-8 0
      info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[2]
            Successfully validated the token.
      info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
            Authorization was successful.
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
            Request finished in 273.7414ms 200 application/json
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
            Request starting HTTP/1.1 GET https://localhost:5001/chathub?id={firstID}&access_token={MyToken}
      info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
            Authorization failed.
      info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[12]
            AuthenticationScheme: AzureADJwtBearer was challenged.
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
            Request finished in 19.1657ms 401
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
            Request starting HTTP/1.1 POST https://localhost:5001/chathub/negotiate text/plain;charset=UTF-8 0
      info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[2]
            Successfully validated the token.
      info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
            Authorization was successful.
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
            Request finished in 6.6534ms 200 application/json
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
            Request starting HTTP/1.1 GET https://localhost:5001/chathub?id={secondID}&access_token={SameTokenAsAbove}
      info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
            Authorization failed.
      info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[12]
            AuthenticationScheme: AzureADJwtBearer was challenged.
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
            Request finished in 18.2278ms 401
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
            Request starting HTTP/1.1 POST https://localhost:5001/chathub/negotiate text/plain;charset=UTF-8 0
      info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[2]
            Successfully validated the token.
      info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
            Authorization was successful.
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
            Request finished in 6.651ms 200 application/json
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
            Request starting HTTP/1.1 GET https://localhost:5001/chathub?id=rgUlpDdMJw8X2Hcku6VL2A&_=1531225867582
      info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[2]
            Successfully validated the token.
      info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
            Authorization was successful.
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
            Request finished in 17.6661ms 200 application/octet-stream
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
            Request starting HTTP/1.1 GET https://localhost:5001/chathub?id=rgUlpDdMJw8X2Hcku6VL2A&_=1531225867604
      info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[2]
            Successfully validated the token.
      info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
            Authorization was successful.
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
            Request starting HTTP/1.1 POST https://localhost:5001/chathub?id=rgUlpDdMJw8X2Hcku6VL2A text/plain;charset=UTF-8 32
      info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[2]
            Successfully validated the token.
      info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
            Authorization was successful.
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
            Request finished in 17.5539ms 200 text/plain
      info: Microsoft.AspNetCore.SignalR.HubConnectionContext[1]
            Completed connection handshake. Using HubProtocol 'json'.
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
            Request finished in 49.7215ms 200 application/octet-stream
      info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
            Request starting HTTP/1.1 GET https://localhost:5001/chathub?id=rgUlpDdMJw8X2Hcku6VL2A&_=1531225867666
      info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[2]
            Successfully validated the token.
      info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
            Authorization was successful.

**Comment by BrennanConroy** [comment]
> I was pointed to here

I actually pointed you [here](https://github.com/aspnet/SignalR/issues). Could you please move the issue to the correct repo.

This repo is for ASP.NET SignalR, you're using ASP.NET **Core** SignalR.

**Comment by exztinct01** [comment]
oh sorry, transferred the issue there now. I'll close this one
