### ISSUE TITLE
Issue with disposing the signalR hub

### ISSUE THREAD

**Issue by mkermit** [SignalR/SignalR#4149]
### Nuget Packages Used:
Microsoft.AspNet.SignalR.Client version="2.3.0"
Microsoft.AspNet.SignalR.Core version="2.3.0"
Microsoft.Owin version="4.0.0" 
Microsoft.Owin.Host.HttpListener version="4.0.0" 
Microsoft.Owin.Hosting version="4.0.0" 
Microsoft.Owin.Security version="4.0.0" 
Newtonsoft.Json version="11.0.2" 

### Test Code
    class Program
    {
        static void Main(string[] args)
        {
            string baseAddress = "http://localhost:8088/";

            using (WebApp.Start<Startup>(baseAddress))
            {
                var connection = new HubConnection(baseAddress);
                IHubProxy hub = connection.CreateHubProxy("TestHub");
                connection.Start().Wait();
            }

            using (WebApp.Start<Startup>(baseAddress))
            {
                var connection = new HubConnection(baseAddress);
                IHubProxy hub = connection.CreateHubProxy("TestHub");
                connection.Start().Wait();
            }
        }

        public class TestHub : Hub
        {
            public TestHub() { }
        }

        public class Startup
        {
            public void Configuration(IAppBuilder app)
            {
                app.MapSignalR();
            }
        }
    }

### Expected  behavior
Running the code above i would expect to create the SignalR server, the client to connect, dispose the signalr server, create for second time the signalR server, the client to connect and dispose the signalr server.

### Actual behavior - Throws the following exception
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at SignalRTests.Program.Main(String[] args) in C:\Projects\SignalRTests\SignalRTests\Program.cs:line 25
Inner Exception 1:
**TimeoutException: Transport timed out trying to connect**

**Comment by anurse** [comment]
Can you try issuing a standard HTTP request before starting the SignalR connection? It's possible that `WebApp.Start` completes **before** the server is fully initialized. If a standard HTTP request also fails, that would indicate the problem lies in that initialization process. If a standard HTTP request is successful, we can dive deeper in to why it's failing. If you can [enable client and server tracing](https://docs.microsoft.com/en-us/aspnet/signalr/overview/testing-and-debugging/enabling-signalr-tracing) and collect those logs that would help us identify what could be going on.

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
