### ISSUE TITLE
SignalR Groups.Add() timing out with premium sku service bus topic partitioned

### ISSUE THREAD

**Issue by zhulixuan** [SignalR/SignalR#4150]
We are using signalr 2.2.2 server side nuget.  A premium sku azure service bus as backplane.

The call to Groups.Add(Context.ConnectionId, groupName) times out.  

The topics created by signalR are partitioned.  If we manually create topics as not partitioned, the problem is gone.

Premium sku azure service bus does not support partition, but signalR package creates topic as partitioned anyway.  Is there a signalR configure setting to disable topic partition?  Does signalR work with premium sku azure service bus at all?

**Comment by anurse** [comment]
Our code doesn't set the partitioning flag at all when creating topics. I just tested and found that topics were created with the partitioning flag set to `false`. Can you provide the specific packages and version numbers you're using?

Are the topics created with partitioning enabled when you deploy a plain SignalR application? Can you provide a sample application that causes these topics to be created?

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
