### ISSUE TITLE
Context.UserIdentifier is null after switching to Azure SignalR Service

### ISSUE THREAD

**Issue by imsam67** [SignalR/SignalR#4153]
When I use SignalR locally everything works fine but after switching to Azure SignalR Service, I no longer get user id or any claims in `Context.UserIdentifier` or `Context.User.Claims` respectively. Any idea why? Here's my question on SO which provides more details on the issue:
https://stackoverflow.com/questions/51458726/context-useridentifier-is-null-after-switching-to-azure-signalr-service

**Comment by anurse** [comment]
If the issue only occurs when using Azure SignalR, you should file this issue on their repository: https://github.com/azure/azure-signalr , at least as a start :). I see that someone from their team is on the StackOverflow thread as well.

I'm going to close this issue as we should start from the Azure SignalR side on this one. We work very closely with that team though, so if something does come up in our code we can always re-open it.

As a side note: This repository is for ASP.NET SignalR (the version for System.Web-based applications), your application is using ASP.NET Core SignalR which is located at https://github.com/aspnet/SignalR (we're the same team, just different issue trackers ;)).
