### ISSUE TITLE
Signalr Connected even when Signalr server App Pool is stopped.

### ISSUE THREAD

**Issue by johncarlo3910** [SignalR/SignalR#4155]
Im connecting to Signalr Server deployed in Azure.
Im testing the StateChanged event, it was perfectly working in my localhost signalr server but when it is connected to Azure Signalr server in IIS, when I stopped the App pool it turns to Reconnecting which is good.. but then after few seconds the connection state turns to Connected even if the server's app pool is still down.. This has been puzzling me for awhile now. and I think this is a bug

### Expected  behavior
Connection State should be disconnected until I start the app pool of signalr again
### Actual behavior
After reconnecting state it turns to Connected state even when App pool is still off
### Steps to reproduce

just signalr connection with statechange event and debug it by turning on/off the app pool of signalr server in local vs azure server

**Comment by anurse** [comment]
How are you stopping the App Pool? Through the IIS manager? If the state changes to Connected it means the server properly responded which means it's likely it is still running or was restarted by IIS.

**Comment by johncarlo3910** [comment]
yes through IIS manager. I was stopping the app pool while debugging my .net app. it turns reconnecting the after seconds to connected while also checking the signalr server through browser if its accessible and running but its not.

**Comment by anurse** [comment]
> while debugging my .net app

To be clear, you were debugging the **client** app, right?

What happens when you try to send messages in this state?

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
