### ISSUE TITLE
SignalR POST call failed for AntiForgeryValidation

### ISSUE THREAD

**Issue by subhendu-de** [SignalR/SignalR#4156]
Hi,
We are getting exception while SignalR JQuery client is trying to establish the channel. All GET requests are successful but POST are failed due to AntiForgeryToken validation. The application is configured to support AntiForgeryToken Validation for the POST calls and not the GET calls. Any pointers how to resolve it.

**Error snapshot**
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: **The required antiforgery header value "RequestVerificationToken" is not present.  at** Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.<ValidateRequestAsync>d__9.MoveNext()  --- End of stack trace from previous location where exception was thrown ---  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)  at Framework.AntiForgeryTokenValidation.AntiForgeryTokenValidation.<Invoke>d__3.MoveNext()  --- End of stack trace from previous location where exception was thrown ---  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)  at Microsoft.AspNetCore.Authentication.ClaimsTransformationMiddleware.<Invoke>d__6.MoveNext()  --- End of stack trace from previous location where exception was thrown ---  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)  at Framework.CSPResponseHeaders.ResponseHeaders.<Invoke>d__6.MoveNext()  --- End of stack trace from previous location where exception was thrown ---  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()  --- End of stack trace from previous location where exception was thrown ---  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()  --- End of stack trace from previous location where exception was thrown ---  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()  --- End of stack trace from previous location where exception was thrown ---  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()  --- End of stack trace from previous location where exception was thrown ---  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()  --- End of stack trace from previous location where exception was thrown ---  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()  --- End of stack trace from previous location where exception was thrown ---  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)  at HttpsRedirectService.RedirectService.<Invoke>d__4.MoveNext()  --- End of stack trace from previous location where exception was thrown ---  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)  at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext() |  
-- | --

**Comment by anurse** [comment]
Your stack trace indicates you are using ASP.NET Core on the server, but you mention the "SignalR JQuery client". It sounds like you're using the ASP.NET SignalR client with the ASP.NET **Core** SignalR server. The only JavaScript client supported in ASP.NET Core SignalR is the [`@aspnet/signalr`](http://npmjs.com/package/@aspnet/signalr) NPM package.

**Comment by subhendu-de** [comment]
Hi anurse,

Thanks for responding. We are using ASP.NET Core 1.1.3 but on .NET Framework 4.6.2. Since ASP.NET Core 1.1.3 doesn't have SignalR supported, we used ASP.NET Signal 2.3.0(not ASP.NET Core SignalR). I believe JQuery Signal client supports ASP.NET Signal 2.3.0

Thanks
Subhendu

**Comment by anurse** [comment]
> I believe JQuery Signal client supports ASP.NET Signal 2.3.0

You are correct. That is the right client to use with this server.

> we used ASP.NET Signal 2.3.0

How have you configured that? Are you using the OWIN adaptor for ASP.NET Core?

ASP.NET SignalR is not officially supported in an ASP.NET Core application. It's possible something is making an assumption about how Anti-Forgery works in that. I'm happy to try to help you resolve the issue, but you should know that this isn't a combination that's officially supported by Microsoft. The ASP.NET SignalR client will definitely not apply the Anti-Forgery token to it's requests, as it doesn't know anything about them. I notice the exception is originating 
 from `BDO.APT.Framework.AntiForgeryTokenValidation.AntiForgeryTokenValidation.d__3.MoveNext()` (the rest of the stack is just the ASP.NET Core Middleware pipeline, so it's not really relevant, it's just the middleware that ran before the one that caused the failure). Is this your own framework code? Can you provide more information on how that component is validating the anti-forgery token?

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.

**Comment by subhendu-de** [comment]
Thanks. We decided not to move with this hybrid approach.
