### ISSUE TITLE
How to return the connections to WEB Client instantly?

### ISSUE THREAD

**Issue by rex19001** [SignalR/SignalR#4158]
How to return the Connections List  To Web Client Instantly?

` public class ChatHub : Hub
    {
        public List<SignalConntions> Conntionses;

        public override Task OnConnectedAsync()
        {
            if (Conntionses == null)
            {
                Conntionses = new List<SignalConntions>();
            }
            var conn = new SignalConntions() { ConnectionId = Context.ConnectionId };
            Conntionses.Add(conn);

            return base.OnConnectedAsync();
        }

        public override Task OnDisconnectedAsync(Exception exception)
        {
            var conn = Conntionses.Where(c => c.ConnectionId == Context.ConnectionId).SingleOrDefault();
            if (conn != null)
            {
                Conntionses.Remove(conn);
            }

            return base.OnDisconnectedAsync(exception);
        }
    }

    public class SignalConntions
    {
        public string ConnectionId { get; set; }
    }`

**Comment by anurse** [comment]
There is no built-in list of connections because there could be connections on other servers if you are using a scale-out system. If you want to track connections you should store them in some kind of persistent data store that all your servers can access (Database, etc.) and retrieve them from there.

**Comment by rex19001** [comment]
@anurse 
How can I get this list in real time?
Saving to the database won't put pressure on it?

**Comment by anurse** [comment]
> How can I get this list in real time?

It's up to you to maintain this list in your `OnConnectionAsync`/`OnDisconnectedAsync` handlers. SignalR does not expose this information.

> Saving to the database won't put pressure on it?

It will require writing to the database on every connection and disconnection. If this is too much pressure for your application, I would advise you to seek a different solution.

Can you please explain *why* you want a list of connections? Then I can provide better guidance as to how to achieve what you are trying to accomplish.
