### ISSUE TITLE
how to choose  SignalR js clinet with react and Microsoft.AspNet.SignalR

### ISSUE THREAD

**Issue by enginnerFrankLiu** [SignalR/SignalR#4162]
thanks for attention for my issue~

there is my situation

I use mvc 5.2 +Microsoft.AspNet.SignalR +2.3

and how to choose signral js client for my situation ?

@aspnet/signalr is for SignalR.Core

signalr.js  is for  Microsoft ASP.NET SignalR JavaScript Client；it contains jq,I use react,that means there is no need to use jq;

so my situation is embarrassing;

help~please

**Comment by anurse** [comment]
The ASP.NET SignalR client (`signalr` on NPM, `Microsoft.AspNet.SignalR.JS` on NuGet) requires jQuery. It is not possible to remove this requirement.

**Comment by enginnerFrankLiu** [comment]
backend: mvc5.2  ASP.NET SignalR 2.3.0 it work well 

![image](https://user-images.githubusercontent.com/41586100/43879338-3b38832a-9bd6-11e8-9f67-f345d8d41098.png)

font-end:

npm webpack es6 react..... to do spa page
here is my font-end framework:https://ant.design/docs/react/introduce-cn

I install ： npm install signalr    and npm install jquery@1.6.4


import * as signalR from 'signalr';
or
 import $ from "jquery";
 import * as signalR from 'signalr';
or
![image](https://user-images.githubusercontent.com/41586100/43879499-f76556e0-9bd6-11e8-8464-5754d612bbf7.png)


result: the same error，I think I cannot use scirpt tag ro reffer jq, because , all I use about moudle
in debug environment  I npm run dev , in product environment  I  npm run build

to build a spa

![image](https://user-images.githubusercontent.com/41586100/43879463-cf96d81e-9bd6-11e8-9027-918b46c0cd74.png)

**Comment by anurse** [comment]
I'm not familiar with how your front end build system works so I can't really advise you here. What I can say is that SignalR requires that the global object `window.jQuery` be present. You'll have to look in to your front-end build system to determine how to achieve that, if simply including the script tag isn't sufficient.

**Comment by enginnerFrankLiu** [comment]
hi~@anurse  thanks your attention and suggestion for me~


 finally I find this package for my signalR front end library;
here:
https://www.npmjs.com/package/ms-signalr-client

if you are have free time ,
and you can view this issue：
https://github.com/dfrencham/ms-signalr-client/issues/2

have a good day~
