### ISSUE TITLE
A specific class in SignalR loosing all values 

### ISSUE THREAD

**Issue by sudhirsrdev** [SignalR/SignalR#4163]
Am using SignalR Asp.NET with Oracle as backend and its not a core application. I have 3 classes which are connecting to DB to load values in to the properties. 

Microsoft.AspNet.SignalR Version - 2.2.2.
Microsoft.AspNet.SignalR.JS Version - 2.2.2
Microsoft.AspNet.SignalR.SystemWeb Version - 2.2.2

### Expected  behavior
All the classes shows the data in dashboard.

### Actual behavior
When I start the API all the values are loading fine but next day, one class is loosing values which is causing my dashboard to show zeros for that respective class object values. I have Serilog implemented which catches the errors and logs each method with details. There are no errors with this class. The other 2 classes has 2 or 3 errors but doesn't has any dependency on this class. 

Any inputs is greatly appreciated.

**Comment by anurse** [comment]
What do you mean by "losing values"? Are these classes SignalR Hubs? Are they dropping messages? Please describe the expected behavior of the *SignalR components* in your system, so we know what to investigate. If you have a more general architecture and design question, I suggest posting it to [StackOverflow](http://stackoverflow.com/).

**Comment by sudhirsrdev** [comment]
These 3 classes are clients in one SignalR hub. Messages works fine when I start the API but next day its not sending back the messages which I think the objects are becoming null and not sending the values. This I was pointing to class is loosing values. If we do not have any suggestions here I will open a request in StackOverflow.

**Comment by anurse** [comment]
I think I need some code samples in order to properly understand what you're asking. I'm still quite confused. Why do you think the objects are becoming null? Are these objects SignalR Hub Proxies?

**Comment by sudhirsrdev** [comment]
SignalR Hub Connected to
1.	Client1
2.	Client2
3.	Client3
Around 6 clients. Each client has around 10 properties. Here Client 3, is working with all properties when we start API but next day only 2 properties are working and rest 8 properties are not broadcasting the messages. And all these 8 properties has the logging in catch but no errors logged. Can you suggest any points for this situation to fix.

**Comment by BrennanConroy** [comment]
Hi. It looks like this is a question about how to use SignalR. This repo is in maintenance mode and we only have the resources to fix major issues, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com/).
