### ISSUE TITLE
Is there a swift version of signalR client?

### ISSUE THREAD

**Issue by fpfengpan** [SignalR/SignalR#4165]
# Issues related to the Asp.NET Core version of SignalR should be filed in the corresponding SignalR repo: https://github.com/aspnet/?utf8=%E2%9C%93&query=Signalr

**Comment by anurse** [comment]
No, there is no official Swift version of the ASP.NET SignalR client and we have no plans to build one at this time. I believe there are likely some unofficial ones, and the .NET client should work in Xamarin.iOS applications.
