### ISSUE TITLE
[SignalR Service Support]Make functional parts of `UseSignalRMiddleware` public for SignalR Service SDK to use

### ISSUE THREAD

**Issue by vicancy** [SignalR/SignalR#4167]
SignalR Service SDK needs to handle `/negotiate` requests, currently it is implemented by hook into the container https://github.com/Azure/azure-signalr/blob/preview/aspnetsignalr/src/Microsoft.Azure.SignalR.AspNet/OwinExtensions.cs#L62.

It would be clearer if SignalR exposes some parts inside `UseSignalRMiddleware` for SDK to use.

**Comment by anurse** [comment]
Given the need to override Hub dispatching, I think the Service's current approach of overriding the HubDispatcher with it's own `PersistentConnection` is the most appropriate way to do this. What pieces of negotiate functionality are you looking to hook? Right now all that logic lives _inside_ `PersistentConnection` so you're already hooking the right place.

**Comment by vicancy** [comment]
It is heavier to override `PersistentConnection` and it does not sound straight forward, after all, all Service SDK want is to overwrite `negotiate` to return a redirect URL, I'd rather have a pure `NegotiateMiddleware`.

With current implementation, unnecessary code are actually called, such as https://github.com/SignalR/SignalR/blob/master/src/Microsoft.AspNet.SignalR.Core/Owin/OwinExtensions.cs#L193-L216 It would be great if parts inside `UseSignalRMiddleware` are exposed to SDK, for example, `EnsureValidCulture`, `InitializeHost` with `instanceName` and `env.GetShutdownToken`, (not sure if `builder.UseStageMarker` is still needed if using Service SDK). Any comments?

**Comment by anurse** [comment]
I'm not clear why the Service SDK needs SignalR at all to create a negotiate response. Is it not just a standard Owin middleware listening at the correct path returning JSON? All the SDK is doing in the overridden HubDispatcher is looking for the negotiate response and sending back the JSON payload. None of the logic that does that seems to be dependent upon any of SignalR. Is this about the negotiate payload or about plugging in the transport layer?

I think I need to understand more about how the service is plugging in to SignalR to actually understand what changes make sense here. Introducing new public APIs is beyond the scope of what @davidfowl and I talked about for 2.4.0. I'll sync up with him and see if we can get some clarity on what the best structure for this is.

**Comment by anurse** [comment]
After talking with @davidfowl, I think we're not clear on what we want to do here for 2.4.0 and I'd like to get a release out before going on leave. If necessary, we can look at this for a future update.

**Comment by anurse** [comment]
Closing as we haven't come to a specific idea on what we can do to make this cleaner. Let us know if there are specific changes that would make things easier for the service SDK and we can consider them!
