### ISSUE TITLE
.NET Standard 2.0 Client

### ISSUE THREAD

**Issue by anurse** [SignalR/SignalR#4176]
Change the client supported frameworks to: 

* .NET Standard 2.0
* .NET Framework 4.5.

**Comment by msauper** [comment]
The msdn article said that SignalR 2.4.0 would not support Windows 8.  Is this correct?
https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/

**Comment by anurse** [comment]
Our current plan is to drop support for Windows 8 Store apps. Standard apps would work fine on Windows 8. What kind of app are you developing?

**Comment by msauper** [comment]
We are developing a new web/mobile application.  However, I can see that SignalR would be useful to integrate with a desktop app we have.  This app does run on some Windows 8 desktops.

**Comment by anurse** [comment]
SignalR will continue to run fine in a Windows 8 Desktop app (running on .NET Framework 4.5 or higher). It's just Windows 8 **Store** apps that would no longer be supported.

**Comment by anurse** [comment]
This is done in 2.4.0-preview1

**Comment by dlasheen** [comment]
@anurse I have a Windows App running on a windows 8 tablet... We did large investment buying windows 8.1 tablets and we use the windows app for Engineering site inspection.
I updated Signalr for the Server, but I faced difficulty updating the client, which is a Windows App. Will the old release Signlar client work with the Signalr updated on the Server? or should I try to uninstall the Signalr update on the server?

**Comment by anurse** [comment]
If you don't need any of the fixes from 2.4.0 (or support for the Azure SignalR Service), I'd suggest just leaving your server and client on 2.3.0. In theory, I believe the 2.3.0 client will work with the 2.4.0 server, but it's not an officially supported scenario.
