### ISSUE TITLE
Sudden disconnection and inability to reconnect.

### ISSUE THREAD

**Issue by scalise** [SignalR/SignalR#4178]
We are experiencing a sudden disconnection of our ASP.NET web client to the server after a random amount of time and inability to reconnect after this occurs, unless the application pool is recycled. We are using a SQL backplane for scale out.

We receive this error after the issue presents itself and a reconnection is not possible.

    _SignalR error: Error: No transport could be initialized successfully. Try specifying a different transport or none at all for auto initialization_

We are on version 2.2.0 of SignalR running on Windows Server 2008R2.  We have tried upgrading to SignalR 2.3.0 and the same situation occurs.

There is no errors in the server side tracing logs we enabled. Below is a screenshot of the client behavior from Chrome Dev Tools:

![image](https://user-images.githubusercontent.com/1369714/44401310-39ab6000-a51c-11e8-9fd9-e95b2faa14e1.png)

Oddly, running the same code base against the same database, but installed on a Windows Server 2012 machine, the situation does not occur.

We ran Intellitrace on the sever in the hope of finding any exceptions that were going unnoticed. There were none.

**Environment**:
- IIS 7.5
- Windows Sever 2008 R2
- SignalR 2.2.0

Let me know what other information would be helpful.

**Comment by anurse** [comment]
It's very interesting that the application works fine on Windows Server 2012. Do you know of any difference in the IIS configuration for those two servers? Even though there are no errors, are you able to post client and server-side traces (as described in the [SignalR Tracing](https://docs.microsoft.com/en-us/aspnet/signalr/overview/testing-and-debugging/enabling-signalr-tracing) documentation)? There may be more information in there to work from.

**Comment by scalise** [comment]
Here is the transports log:

[transports-keepalive-disabled-from working to failing.txt](https://github.com/SignalR/SignalR/files/2307573/transports-keepalive-disabled-from.working.to.failing.txt)

**Comment by anurse** [comment]
Yeah, I don't see anything odd in that log. Are these the logs collected from *after* the app pool has become unresponsive? Also, can you collect the client-side traces described in the tracing document for the failing connections? More details here: https://docs.microsoft.com/en-us/aspnet/signalr/overview/testing-and-debugging/enabling-signalr-tracing#javascript . The error you're seeing (`No transport could be initialized successfully...`) is just a general error that indicates the individual transports each had an error initializing. Those errors should be in the client-side logs.

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
