### ISSUE TITLE
ASP.NET Identity w/ OAuth 2 and Unrecognized user identity error

### ISSUE THREAD

**Issue by matteobit** [SignalR/SignalR#4185]
I'm getting this error from signalr: Unrecognized user identity. The user identity cannot change during an active SignalR connection.

I had these lines of code:

```
app.MapSignalR();
ConfigureAuth(app);
```

and moved SignalR below auth for supporting Principal in hubs.

This change gives me the error reported above.

My auth configuration is: ASP.NET Identity with CookieAuth, External auth with Google and Microsoft, 2FA, OAuth 2 with Katana.

What am I doing wrong?

**Comment by anurse** [comment]
Can you simplify things down to a sample that can reproduce the problem? That would help us identify the issue. Without more context on how your app code is behaving I'm not sure what to suggest here.

Does the issue occur immediately upon connecting or later in the connection? Is the error occurring on the client or the server? What kind of expiry do you have on your cookie auth tokens?

**Comment by matteobit** [comment]
The error occurs when connecting with javascript client, it is in a view of the same web application. The cookie and oauth token expiration is set to 30 days.

Also the Serilog SignalR sink can't connect to the LogHub, it has no Authorize attribute. The Hub used by the javascript mentioned above has the attribute.

For the sample I'll try to make one in these days.

**Comment by anurse** [comment]
Thanks, even just an basic illustration of what you're trying to do would help us track down the issue.

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
