### ISSUE TITLE
Missing messages in client

### ISSUE THREAD

**Issue by nkfeiyang** [SignalR/SignalR#4187]
I have a small application. The server is self-host signalr program. The client register something to server. when call the server's register method, I will also call some client's methods to notify some status messages. However,  I found when server call client in about 10 messages at the same time, some messages will be lost in client. I checked the logs in server side and client side and found that server has called the client 10. But client's log shows some callback did not receive the call from server.

I have changed the server side
` GlobalHost.Configuration.DefaultMessageBufferSize = 256000;`
But seems no use.
I have googled this question, same scenario have found but could not find a way to solve this. I am wondering how to solve this problem. If it could not be solved, I could not use Signalr in my project.

**Comment by anurse** [comment]
Which client are you using? .NET or JavaScript? Can you provide a sample project that reproduces the issue?

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
