### ISSUE TITLE
Documentation is (possibly) wrong - when to use generated proxy and when not to

### ISSUE THREAD

**Issue by joe-oli** [SignalR/SignalR#4190]
Doco at the following url states:
https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-javascript-client

**When to use the generated proxy**
If you want to register multiple event handlers for a client method that the server calls, you can't use the generated proxy. Otherwise, you can choose to use the generated proxy or not based on your coding preference. 

I have registered multiple client-side handlers, and it works. 
For example
var pxyHub = $.connection.MySRHub;
pxyHub.client.someHandlerOne = function (p1, p2) {... etc...};
pxyHub.client.someHandlerTwo = function (whatever) {... etc...};

**Comment by anurse** [comment]
The docs are referring to multiple handlers for the **same method**. I.e. code like this (note the `+=` operator doesn't work this way in JavaScript so this is pseudo code that **does not actually work**):

```javascript
var pxyHub = $.connection.MySRHub;
pxyHub.client.someHandlerOne += function (p1, p2) {... etc...};
pxyHub.client.someHandlerOne += function (whatever) {... etc...};
```
