### ISSUE TITLE
ASP.NET Web Api Signalr not hitting OnConnected method

### ISSUE THREAD

**Issue by alieniasty** [SignalR/SignalR#4195]
I have a Hub inside my ASP.NET Stateful project hosted on local Service Fabric cluster, and I've overridden the OnConnected method. When putting breakpoint on OnConnected method, it's not entered, but on the same time, messages are properly broadcasted through the Hub.

Hub class:

```
public class NotificationHub : BaseHub
{
    private IFragStateManager _stateManager;
    private static IHubContext _context;

    public NotificationHub(IFragStateManager stateManager) : this(stateManager, _context)
    {
        _stateManager = stateManager;
        _context = GlobalHost.ConnectionManager.GetHubContext<NotificationHub>();
    }

    private NotificationHub(IFragStateManager stateManager, IHubContext context) : base(stateManager, context)
    { }

    /// <summary>
    /// Broadcasts payload to all clients
    /// </summary>
    /// <param name="payload"></param>
    public void Broadcast(object payload)
    {
        try
        {
            _context.Clients.All.broadcast(payload);
        }
        catch (Exception e)
        {
            Log.Error(e.ToString());
        }            
    }

    //Investigate more why it's not hitting breakpoint while it actually connects and broadcasts messages
    public override Task OnConnected()
    {
        return base.OnConnected();
    }

    public override Task OnDisconnected(bool stopCalled)
    {
        return base.OnDisconnected(stopCalled);
    }
}
```

**_context.Clients.All.broadcast(payload);** works well. It delivers payload successfully

Hub's base class:

    public abstract class BaseHub : Hub
    {
        private Guid _userId;

        private IFragStateManager _stateManager;
        private IHubContext _context;

        public BaseHub(IFragStateManager stateManager, IHubContext context)
        {
            _stateManager = stateManager;
            _context = context;
        }        

        public override async Task OnConnected()
        {
            var map = await _stateManager.GetOrAddAsync<FragDictionary<Guid, string>>("UserConnectionMap");

            using (var tx = _stateManager.CreateTransaction())
            {
                var exisingValue = await map.TryGetValueAsync(tx, _userId);
                await map.SetAsync(tx, _userId, Context.ConnectionId);
                await tx.CommitAsync();
            }

            await base.OnConnected();
        }        

        public override async Task OnDisconnected(bool stopCalled)
        {
            var map = await _stateManager.GetOrAddAsync<FragDictionary<Guid, string>>("UserConnectionMap");

            using (var tx = _stateManager.CreateTransaction())
            {
                await map.TryRemoveAsync(tx, _userId); 
                await tx.CommitAsync();
            }

            await base.OnDisconnected(stopCalled);
        }
    }

Hub client:

    $.connection.hub.logging = true;
    $.connection.hub.url = 'http://localhost:8298/api/realtime/70c604f8-7996-4107-9ec3-28d08c869899/131810464642593740/4b98412e-8f09-4460-9c90-1d155cb8efca/signalr';

    var hub = $.connection.notificationHub;

    $.extend(hub.client, {
        broadcast: function (msg) {console.log(msg)}
    });

    $.connection.hub.start().done(function() {
        console.log('Connected');
    });   

Client's scripts:

```
<script src="Scripts/jquery-1.6.4.js"></script>
<script src="Scripts/jquery.signalR-2.1.0.js"></script>
<script src="http://localhost:8298/api/realtime/70c604f8-7996-4107-9ec3-28d08c869899/131810464642593740/4b98412e-8f09-4460-9c90-1d155cb8efca/signalr/hubs"></script>
```

What has been checked already:

- downgrade of SignalR. Went from 2.3 to 2.1. No results,
- js client is already subscribing so propably no issues here,
- when Hub poked from the backend code, it broadcasts messages properly.

**Comment by anurse** [comment]
Can you clarify a few things so I understand? As this is a Service Fabric app, I presume there are multiple running instances of the server? Have you configured a [scale-out provider](https://docs.microsoft.com/en-us/aspnet/signalr/overview/performance/scaleout-in-signalr) ? If so, which provider?

If it's just one node, or if you've properly configured scale-out, it might be something different.

**Comment by alieniasty** [comment]
Yes, it's a Service Fabric app. I haven't configured scale-out provider, yet the app behaves exactly the same on both 1 node and 5 node cluster, regardless replication.

**Comment by anurse** [comment]
First off, without a scale-out provider, SignalR will only operate correctly in a 1-node configuration. So, if you plan to scale, you'll need to configure scale-out as [described in the docs](https://docs.microsoft.com/en-us/aspnet/signalr/overview/performance/scaleout-in-signalr). But since you said this issue reproduces in a 1-node environment, let's try to dive in to that.

> When putting breakpoint on OnConnected method, it's not entered, but on the same time, messages are properly broadcasted through the Hub.

This seems very odd to me. If messages are being broadcasted, then OnConnected should have fired somewhere. Can you collect a [Fiddler](https://www.telerik.com/fiddler) network trace for a single client connection? What I'm looking for is the `connectionData` query string value in all the SignalR requests. When you connect to SignalR that value should contain the list of Hubs you are connected to. We'll only fire `OnConnected` for the hubs listed in that data. The code you posted looks correct (you're subscribing to an event and doing so **before** starting) so I think that should be working, but it would help to confirm that.

Also, it looks like you're using a DI container and putting the Hub in there, can you provide more context on that? Is it possible for you to post an application that reproduces the problem so I can see the full code and get an idea of the context in which this issue is occurring?

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.

**Comment by alieniasty** [comment]
Hello :)

I've set up a greenfield with the issue replicated. 

[repo](https://github.com/alieniasty/stateful-signalr-servicefabric)

Keep in mind that it's a stateful service, therefore after deployment you need to fetch the main replica Id and paste it into the client code (2 places in _scr.html_). After you successfully connect the client with the test hub, you will receive your connectionId directly to the browser console. Copy returned connectionId and call 

`GET api/signalr/{{mainReplicaId}}/test/ping?connectionId={{connId}}`

with a Postman for example. 

You should now have test object broadcasted to your client. It will show up in the console. Keep breakpoint on OnConnected method through the whole process.

I was not collecting Fiddler network trace since I had complete logs in browser's console. Here they are:
```

[14:22:03 GMT+0200 (Central European Summer Time)] SignalR: Auto detected cross domain url. jquery.signalR-2.1.0.js:79:17
[14:22:03 GMT+0200 (Central European Summer Time)] SignalR: Client subscribed to hub 'testnotificationhub'. jquery.signalR-2.1.0.js:79:17
[14:22:03 GMT+0200 (Central European Summer Time)] SignalR: Negotiating with 'http://localhost:8928/api/signalr/f9cdeb75-62e4-4671-b853-8ef41bc3c092/131838200000850673/1e3420a7-344f-4aaa-b8fb-f73ac3582b72/signalr/negotiate?clientProtocol=1.5&connectionData=%5B%7B%22name%22%3A%22testnotificationhub%22%7D%5D'. jquery.signalR-2.1.0.js:79:17
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. src.html
[14:22:04 GMT+0200 (Central European Summer Time)] SignalR: webSockets transport starting. jquery.signalR-2.1.0.js:79:17
[14:22:04 GMT+0200 (Central European Summer Time)] SignalR: Connecting to websocket endpoint 'ws://localhost:8928/api/signalr/f9cdeb75-62e4-4671-b853-8ef41bc3c092/131838200000850673/1e3420a7-344f-4aaa-b8fb-f73ac3582b72/signalr/connect?transport=webSockets&clientProtocol=1.5&connectionToken=AQAAANCMnd8BFdERjHoAwE%2FCl%2BsBAAAAG0IW%2FnSGikGbdWXqlmEs6wAAAAACAAAAAAAQZgAAAAEAACAAAACfdkeZTdnly6ZXjs63Se5iymZ2sasM4CJUuOG844t3owAAAAAOgAAAAAIAACAAAABzN39eNcYXVs1EHBpQkAnLHyShpmPIh7WQqdLF%2FusvtTAAAADJ8QrX1AXmtq3l2h30luG5F62F8I6TwqBmtocsUVdbjyqB0DrVmH0UQjLeuwo9QJVAAAAA0ZR%2F1oc7U30dhtpWz7wihP4QUuH%2BQXbabDD3o9Lom3ycc%2BP8S30oFerfdFKR10A4sM6wFO%2BpGlFM%2F2F15zKRtw%3D%3D&connectionData=%5B%7B%22name%22%3A%22testnotificationhub%22%7D%5D&tid=9'. jquery.signalR-2.1.0.js:79:17
[14:22:04 GMT+0200 (Central European Summer Time)] SignalR: Websocket opened. jquery.signalR-2.1.0.js:79:17
[14:22:04 GMT+0200 (Central European Summer Time)] SignalR: webSockets transport connected. Initiating start request. jquery.signalR-2.1.0.js:79:17
[14:22:04 GMT+0200 (Central European Summer Time)] SignalR: The start request succeeded. Transitioning to the connected state. jquery.signalR-2.1.0.js:79:17
[14:22:04 GMT+0200 (Central European Summer Time)] SignalR: Now monitoring keep alive with a warning timeout of 13333.333333333332, keep alive timeout of 20000 and disconnecting timeout of 30000 jquery.signalR-2.1.0.js:79:17
05f44304-9af5-4b41-9230-5ac4f4bbe633 src.html:23:13
[14:22:27 GMT+0200 (Central European Summer Time)] SignalR: Triggering client hub event 'broadcast' on hub 'TestNotificationHub'. jquery.signalR-2.1.0.js:79:17
Object { Title: "Test" }
```

**Comment by anurse** [comment]
Does this only repro in Service Fabric?

**Comment by alieniasty** [comment]
Yes, works well in standard Web Api application. OnConnected is invoked.

**Comment by anurse** [comment]
Can you clarify the process model for your application in Service Fabric (I'm not familiar with Service Fabric's model here). Are there multiple processes running for your application or only one? It seems extremely odd that OnConnected would not be fired but messages would be successfully broadcasted. Do you have the debugger attached to the process that is receiving the `/start` request?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
