### ISSUE TITLE
SignalR Where/How server calls hub

### ISSUE THREAD

**Issue by forumuser13371** [SignalR/SignalR#4202]
Can anyone tell me how/where in what place signalr server calls hub? Below find my code. How the hell RunServ knows my hub main called "Main" where is the call to it from server. All works well. I've checked when changed name of hub to "Whatever" then i get error means server has somwhere reference to this hub. Where it is?

Server code:

```
Module RunServ

    Private SignalR As IDisposable
    Private Const Address As String = "http://+:4848/"

    Sub Main()
        Task.Run(Sub() StartServer()).Wait()
        Console.ReadLine()
    End Sub

    Private Sub StartServer()
        Try
            SignalR = WebApp.Start(Of Startup)(Address)
            Console.WriteLine("Server is running")

        Catch generatedExceptionName As TargetInvocationException
            Console.WriteLine("Server error")
        End Try
    End Sub

    Private Sub StopServer()
        SignalR.Dispose()
    End Sub

End Module
```

Startup

```
Public Class Startup
        Public Sub Configuration(app As IAppBuilder)
            Dim hubConfiguration = New HubConfiguration()
            hubConfiguration.EnableDetailedErrors = True
            app.UseCors(CorsOptions.AllowAll)
            app.MapSignalR(hubConfiguration)
        End Sub
    End Class
```

Hub itself class called "Main"

```
   <HubName("Main")>
    Public Class HubMain
        Inherits Hub '(Of IHubMain)

        Public Overrides Function OnConnected() As Task
            Clients.All.userJoined("anonymous")
            Console.WriteLine("Connected connection id: " + Context.ConnectionId)
            Return MyBase.OnConnected()
        End Function

        Public Overrides Function OnReconnected() As Task
            Console.WriteLine("Reconnected connection id: " + Context.ConnectionId)
            Return MyBase.OnReconnected()
        End Function
End Class
```

**Comment by anurse** [comment]
I'm a little confused as to what your question is. SignalR scans your app for classes that inherit from `Hub` and makes them available to the client to invoke methods. The default name for a Hub is the class name `HubMain` in your example, but you can change it with the `HubName` attribute (which you've used to change the name to `Main`).

Is there a problem that you need help resolving?

**Comment by forumuser13371** [comment]
Hi Anurse, Does it mean that if i would have two hubs classes in my project like: HubMain and HubSecond then Server automaticly will find them and use? If that's the case i understand why i wasn;t able to find in either Startup where Server calls my hub class.

**Comment by anurse** [comment]
> 1. Does it mean that if i would have two hubs classes in my project like: HubMain and HubSecond then Server automaticly will find them and use?

Yes, that is correct.

> 2\. Does also clients uses hub classes and searching for all available in projects?

Yes, we search all assemblies in the app.

I suggest you review the [ASP.NET SignalR Documentation](https://docs.microsoft.com/en-us/aspnet/core/signalr/?view=aspnetcore-2.1) as it covers these questions and provides a lot of detail on how SignalR works.

**Comment by forumuser13371** [comment]
Hi Anurse,
Yes i know how to use signalr but i never was looking for how server reference to specific hubs. Could you just tell me one more thing - where exactly in signalr code is coding part for server to look over all available hub classes as well as client?
