### ISSUE TITLE
NPM Package

### ISSUE THREAD

**Issue by Vaccano** [SignalR/SignalR#4211]
NPM is how most CI/CD pipelines get their code.

Signal R should have its javascript as part of a NPM package.

This is a re-open of this auto closed issue: https://github.com/SignalR/SignalR/issues/3700

**Comment by anurse** [comment]
SignalR is available in the `signalr` npm package: http://npmjs.com/package/signalr

**Comment by anurse** [comment]
It actually started as an unofficial package, but took it over (with the permission of the publisher). I'll file an issue for updating some of those things you mentioned though :).

**Comment by Vaccano** [comment]
OK.  Thanks!
