### ISSUE TITLE
Hub callbacks add/remove issues

### ISSUE THREAD

**Issue by MaKCbIMKo** [SignalR/SignalR#4213]
### Expected  behavior
Being able to add/remove callbacks properly.

### Actual behavior
- Callbacks get overwritten if the have the same string representation.
- Callbacks get executed even after removing them.

### Steps to reproduce
```
var fn1 = function() {console.log(1);};
var fn2 = function() {console.log(2);};
var fn3 = function() {console.log(3);};

// after this lines
// the string representation of fn1, fn2 and fn3 will be "function bound () { [native code] }"
fn1 = fn1.bind(this);
fn2 = fn2.bind(this);
fn3 = fn3.bind(this);

// suppose we have a hub with a 'change' event on it
hub.on('change', fn1);
hub.on('change', fn2);
hub.on('change', fn3);
hub.off('change', fn1);
```

the `fn1` will be still firing although `off` was called

### Investigation notes
In this line:
https://github.com/SignalR/SignalR/blob/master/src/Microsoft.AspNet.SignalR.Client.JS/jquery.signalR.hubs.js#L109

using callback as an index to an object triggers implicit toString invocation which from my experience returns the source code (if available, for native functions it just puts [native code] in the function body)

Very roughly said, for an event, it allows just one callback per function definition not per instance.

Did some more testing and it seems that the callbacks get overwritten in the callbackMap but still get registered with jQuery:
https://github.com/SignalR/SignalR/blob/master/src/Microsoft.AspNet.SignalR.Client.JS/jquery.signalR.hubs.js#L113

**Comment by anurse** [comment]
Thanks for the report. I'll take a look at it.
