### ISSUE TITLE
Push notification without check user online or not.

### ISSUE THREAD

**Issue by bishopjun11** [SignalR/SignalR#4221]
Here is my scenario :
I have a service to settle user placed orders, and orders will settle in anytime. That means user may be not online. When order settled, this service will push a orderSettleNotification to RabbitMQ, and SignalR service will consume the notification and push them to specified user. 
In my current implement  of signalR. I just push the notification to specified user and without check if the user is online or not.(Use IHubContext<IApiHub>);
Another implement is that I handle user offline and online in SignalR, and store user online information in another place. Then check user is online or not before push notifcation to RabbitMQ. only push notification for online user.

Which implement is better?

**Comment by anurse** [comment]
If the user is offline, do you want them to recieve the push notification when they come back online? Or is it OK to just drop the notification if they're offline? If it's OK to drop the notification, it's probably better to just send the notification through SignalR without checking if the user is online. If you want to store the notification for the user to see when they come online, you'll need to store the notification somewhere persistent and look up any pending notifications when the user comes back online. SignalR doesn't buffer messages for users if they're offline.
