### ISSUE TITLE
Optional parameters - "method could not be resolved"

### ISSUE THREAD

**Issue by alex-jitbit** [SignalR/SignalR#4226]
We're on the latest SignalR (2.3.0) and having a server-side hub method with optional arguments results in a `Signalr Exception System.InvalidOperationException: 'BlahBlah' method could not be resolved. Potential candidates are:`

Adding a server-side overloaded method fixes this.

### Steps to reproduce

Server-side:
`public void MyMethod(int a, bool b = false)`

Client-side
`myHub.server.myMethod(123);`

**Comment by anurse** [comment]
We don't support default values in Hub methods. An overload is the correct way to implement this.
