### ISSUE TITLE
React to the new StackExchange.Redis v2.0 package 

### ISSUE THREAD

**Issue by muratg** [SignalR/SignalR#4230]
StackExchange released a new Redis library `StackExchange.Redis` V2.0.x

We'll be creating a new package: `Microsoft.AspNet.SignalR.StackExchangeRedis` which uses that. 

cc @anurse @Tratcher @DamianEdwards @Eilon

**Comment by ErroneousFatality** [comment]
@muratg Could you give me the link to the new package?
Will the two packages share everything and differ only in which Redis library they use?

**Comment by muratg** [comment]
This is not yet released. You can get the current build from our myget feed: https://dotnet.myget.org/feed/aspnet-signalr/package/nuget/Microsoft.AspNet.SignalR.StackExchangeRedis

**Comment by ErroneousFatality** [comment]
@muratg Thanks for the quick response. Do you have any rough estimate on when it could be released? I ask so I can plan my team's development accordingly.

**Comment by muratg** [comment]
@ErroneousFatality I expect that we'll release this sometime this month, hopefully as early as possible.

I think it shouldn't have any dev code impact for you, just testing.
