### ISSUE TITLE
Websocket support for .net client running on .net core?

### ISSUE THREAD

**Issue by cchoi-solver** [SignalR/SignalR#4232]
### Expected  behavior
SignalR .NET client running on .NET Core negotiates WS connection 
### Actual behavior
SignalR .NET Client running on .NET Core negotiates server sent events connection
### Steps to reproduce

I have a asp net core application(asp net core isn't talking to signalr, its actually a background thread that does) that talks to a SignalR full framework hub. 
When I retarget the application to  full framework and add in the hacks per #435, the asp net core application establishes a websocket connection.  When I switch the project back to net core, it establishes a SSE connection. 

Unfortunately, its not in the cards to port the server to SignalR Core...so is there any hope for websockets on net core for the final release of signalr? 
Thanks!  

edit: I'm sorry, I should've opened this ticket up in the aspnet/signalr issue tracker, I didn't realize which one I was in  😬

**Comment by anurse** [comment]
I think you're in the right place. Are you using the `Microsoft.AspNet.SignalR.Client` package (i.e. **not** `AspNetCore`)?

**Comment by anurse** [comment]
Can you try updating your client to the [`2.4.0-preview1-20180920-03`](https://www.nuget.org/packages/Microsoft.AspNet.SignalR.Client/2.4.0-preview1-20180920-03) build? This  version added support for .NET Standard 2.0 which includes WebSockets. The 2.3.0 (and below) version of the client didn't support .NET Core WebSockets, but the upcoming 2.4.0 release should.

**Comment by cchoi-solver** [comment]
> I think you're in the right place. Are you using the `Microsoft.AspNet.SignalR.Client` package (i.e. **not** `AspNetCore`)?

Yep!


> Can you try updating your client to the [`2.4.0-preview1-20180920-03`](https://www.nuget.org/packages/Microsoft.AspNet.SignalR.Client/2.4.0-preview1-20180920-03) build? This version added support for .NET Standard 2.0 which includes WebSockets. The 2.3.0 (and below) version of the client didn't support .NET Core WebSockets, but the upcoming 2.4.0 release should.

Will do, thanks!

**Comment by cchoi-solver** [comment]
@anurse 

"2018-10-08 12:52:44.3258... SSE: GET https://xxxx/signalr/connect?clientProtocol=2.0&transport=serverSentEvents&connectionData= [xxx]
2018-10-08 12:52:44.6039 .... - SSE: OnMessage(Data: initialized) "

**Comment by anurse** [comment]
Looks like I can reproduce this as well. Investigating now!
