### ISSUE TITLE
For what is `connectionData`?

### ISSUE THREAD

**Issue by Kamikadze4GAME** [SignalR/SignalR#4240]
I'm a little confused with this necessary param for negotiate (connect etc) request.
Why? I checked. Even without this param to request I can call methods of different hubs. So question. For what is `connectionData`?

**Comment by Kamikadze4GAME** [comment]
Maybe, don't allow users fire methods of hub to which they are not connected?

**Comment by anurse** [comment]
We don't have plans to add that functionality. If you need to prevent users from firing methods on a hub, use authentication.
