### ISSUE TITLE
Invoking while in a On response function will cause deadlock (?)

### ISSUE THREAD

**Issue by farlock85** [SignalR/SignalR#4246]
Consider this code:

`
    public class S
    {
        private readonly HubConnection _hubConnection;

        public S()
        {
            _hubConnection = new HubConnectionBuilder()
                             .WithUrl("")
                             .ConfigureLogging(logging => {
                                 logging.AddConsole();
                                 logging.SetMinimumLevel(LogLevel.Trace);
                             })
                             .Build();

            _hubConnection.On<DataRequest>("DataFetch", DataFetch);
        }

        private void DataFetch(DataRequest dataRequest)
        {
            var response = new DataResponse
            {
                RequestId = dataRequest.RequestId
            };

            var dataResponse = Send<DataResponseResult>("DataResponse", response)
                .Result;
        }
        
        public async Task<T> Send<T>(String methodName, params Object[] parameters)
        {
            Log.Information("Sending {methodName} request", methodName);

            try
            {
                var response = await _hubConnection.InvokeCoreAsync<T>(methodName, parameters, new CancellationTokenSource(30000).Token);

                Log.Information("Received {methodName}", methodName);

                return response;
            }
            catch (Exception ex)
            {
                Log.Error(ex, "Error sending {methodName}", methodName);
            }

            return default(T);
        }
    }
`

the Send is called from the DataFetch which comes from _hubConnection.On. 

The trace logger doesn't mention anything special, but you will see that it hangs on InvokeCoreAsync until it times out.

When I wrap the Send method in a Task.Factory.StartNew it works fine.

**Comment by anurse** [comment]
The `HubConnectionBuilder` API is for ASP.NET Core SignalR. This repo is for ASP.NET SignalR. I'll move the issue to the appropriate repo for you.

**Comment by anurse** [comment]
This issue was moved to aspnet/SignalR#3125
