### ISSUE TITLE
SignalR scaleout with Redis Cluster

### ISSUE THREAD

**Issue by pampua84** [SignalR/SignalR#4264]
Hi Guys,
as suggested in this post:

[https://forums.asp.net/p/2148882/6236875.aspx?SignalR+scaleout+with+Redis+Cluster](url)

Is it possible to scaleuot SignalR with Redis Cluster? Can I solve this problem by putting a reverse proxy in front of the redis cluster and SignalR calls it? Or is there any new feature to do it?
Thank you

**Comment by anurse** [comment]
ASP.NET SignalR doesn't support Redis Cluster and we don't have any plans to add support for it.
