### ISSUE TITLE
can we still get the connection id in the latest version ?

### ISSUE THREAD

**Issue by omuleanu** [SignalR/SignalR#4266]
I used to be getting the getting the connection id  (in signalr v1)  like this:
```
$.connection.hub.start().done(function () {
            connId = $.connection.hub.id; // was getting different id (guid) for each browser tab
...

now, using the latest version:
```
        var connection = new signalR.HubConnectionBuilder().withUrl("/myHub").build();

        connection.start().then(function () {
            console.log(connection.id); // always 0 (zero)
```
is getting clientId possible, or is it not allowed  ?

**Comment by anurse** [comment]
This issue was moved to aspnet/SignalR#3285

**Comment by anurse** [comment]
Hey @omuleanu, I moved this to aspnet/SignalR since your question is about ASP.NET Core SignalR, and this repo is for ASP.NET SignalR. We'll have an answer for you over in the other repo (linked in my above comment)
