### ISSUE TITLE
Is there continuous connect time limit?

### ISSUE THREAD

**Issue by stacklesshaha** [SignalR/SignalR#4267]
within my webapi application(on iis),there is a singleton HubConnection which is used to connect to my  Signalr application(on iis)
**private static readonly HubConnection Connection = new HubConnection("http://imrobot.stack.com");**

when I kill and restart the Signalr application,the singleton HubConnection can  reconnect to ,send to,recieve message from the Signalr application.However,when ten or more hours past over, the singleton HubConnection can't send message or recieve message ,but in my logFile the Connection.State is ConnectionState.Connected,this make me confused.Is there continuous Connect time limit?

**Comment by anurse** [comment]
I'm not aware of any limit on the duration of a connection. We've had customers run connections for a very long time.

There was an issue with Redis-based scale-out in long-running connections that was fixed in SignalR 2.3.0, are you using Redis-based scale-out and running on version 2.2.0 or earlier?

**Comment by stacklesshaha** [comment]
sorry for having no time to reply,I am using SignalR 2.2.2 and don't use Redis for scale-out

**Comment by anurse** [comment]
Do you use Scale-Out at all?

**Comment by stacklesshaha** [comment]
> Do you use Scale-Out at all?

No,I don't use Scale-Out  :)

**Comment by BrennanConroy** [comment]
Hi. It looks like this is a question about how to use SignalR. This repo is in maintenance mode and we only have the resources to fix major issues, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com/).
