### ISSUE TITLE
Update bower-signalr to 2.4.0

### ISSUE THREAD

**Issue by tghamm** [SignalR/SignalR#4269]
### Expected  behavior
Repo would be RTM version of SignalR 2.4.0 along with updated bower definition for 2.4.0.
### Actual behavior
Repo is set to 2.4.0-preview1, and bower.json is set to 2.2.3
### Steps to reproduce
N/A

We'd like to upgrade to 2.4.0 and take advantage of the Azure SignalR Service but need this repo to be updated before we can.  Thanks in advance.

**Comment by anurse** [comment]
We can update that repo, but do rememeber that Bower is now deprecated as a front-end library distribution system. I'd strongly recommend you consider Yarn, as [recommended by the Bower authors themselves](https://bower.io/blog/2017/how-to-migrate-away-from-bower/)

**Comment by anurse** [comment]
The repo has been updated.
