### ISSUE TITLE
Please make 2.4 available on ajax.aspnetcdn.com

### ISSUE THREAD

**Issue by MatthewSteeples** [SignalR/SignalR#4270]
Similar to #3119

Can we get 2.4 uploaded to the CDN please?

**Comment by bradygaster** [comment]
We have a discussion related to this ongoing currently. The clients are on a few 3rd-party CDNs already. Would you be ok with a non-MS CDN or are you required to use the aspnetcdn.com one only?

**Comment by anurse** [comment]
Also, note that there is a generic CDN for all of NPM available at `unpkg.com`. So you can access SignalR 2.4.0 using this URL: `https://unpkg.com/signalr@2.4.0/jquery.signalR.js`. Note that this CDN is not controlled by Microsoft. As always, when using a CDN, use [Sub-Resource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) to prevent issues from CDNs changing the content of the scripts out from under you.

**Comment by MatthewSteeples** [comment]
@bradygaster We don't have a strict requirement to use aspnetcdn, but we already use jQuery and something else from there so we thought it made sense to get them from the same place rather than separate DNS lookups and HTTPS connections.

Personally I can't wait until we can cache packages based on SRI hash, then it won't matter where they've loaded it from we can still use the cached version!

**Comment by bradygaster** [comment]
@MatthewSteeples good to know. We'll work on getting these into at least a few of the CDNs, and understand that you'd prefer it be the official CDN, but at this time not sure if it'll land there.

**Comment by muratg** [comment]
@bradygaster more work here, or is this good to close?

**Comment by bradygaster** [comment]
@muratg and @MatthewSteeples - I think the usage of that CDN is waning, and we have no plans on publishing the newer Core scripts to it. As @anurse points out we are using a 3rd party CDN for the ASP.NET SignalR scripts, so they can be obtained from there. We are investigating using CdnJs for the ASP.NET Core scripts in the future.
