### ISSUE TITLE
Microsoft.AspNet.SignalR.zh-Hans--Dependencies 2.4.0

### ISSUE THREAD

**Issue by ghd258** [SignalR/SignalR#4271]
Microsoft.AspNet.SignalR.zh-Hans--Dependencies 
Microsoft.AspNet.SignalR.SystemWeb.en-US (>= 2.4.0)   
（Oops!

Error 404 - Page Not Found

Looks like you might have gotten lost. Let's see if we can help you find your way!）

Microsoft.AspNet.SignalR.SystemWeb.zh-Hans (>= 2.3.0)
![1](https://user-images.githubusercontent.com/4811375/48753219-1aad9d00-ecc8-11e8-802c-ed89418e7cae.png)
![2](https://user-images.githubusercontent.com/4811375/48753225-200ae780-ecc8-11e8-9431-9198e6e77189.png)

**Comment by anurse** [comment]
Weird, we'll look at fixing this.

**Comment by anurse** [comment]
This is fixed in version [2.4.1](https://github.com/SignalR/SignalR/releases/tag/2.4.1) which is now released to NuGet.org and NPM.
