### ISSUE TITLE
Unable to connect to Azure from desktop (v. 2.4.0)

### ISSUE THREAD

**Issue by arteny** [SignalR/SignalR#4273]
Last released version reported as support Azure SignalR, but I didn't find any example of how to connect to Azure SignalR from desktop .net app (WPF for instance). All examples for Azure connect are only for AspNet site. Can anybody advice how to do it?

**Comment by anurse** [comment]
There's no change to the client code needed to connect to Azure SignalR. You change the server and update the client to 2.4.0 and it will automatically connect to the service.

The actual connection flow is something like the following:

1. The client (JS or .NET) connects to the SignalR endpoint on your app
2. On the server, the Azure SignalR SDK intercepts the initial `/signalr/negotiate` request, and returns a payload that tells the client to redirect to the service instead.
3. The client now reattempts to connect to the service.

So the client doesn't need any special configuration to use the service.

**Comment by arteny** [comment]
@anurse Azure SignalR needs connection string specified, where Access Key is provided
Checked again new test with your advice:
`			ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
			var hubConnection = new HubConnection("https://myservicenamehere.service.signalr.net:5001", " /signalr/negotiate", false);
			hubConnection.Start();

			hubConnection.Start().ContinueWith(task =>
			{
				if (task.IsFaulted)
				{
					Debug.WriteLine("There was an error opening the connection:{0}",
														task.Exception.GetBaseException());
				}
				else
				{
					Debug.WriteLine("Connected");
				}
			}).Wait();
`
and got fail result:
There was an error opening the connection:Microsoft.AspNet.SignalR.Client.HttpClientException: StatusCode: 404, ReasonPhrase: 'Not Found', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Connection: keep-alive
  Strict-Transport-Security: max-age=15724800; includeSubDomains
  Date: Wed, 28 Nov 2018 20:33:22 GMT
  Content-Length: 0
}
   в Microsoft.AspNet.SignalR.Client.Http.DefaultHttpClient.<>c__DisplayClass5_0.<Get>b__1(HttpResponseMessage responseMessage)

**Comment by anurse** [comment]
You need to configure the **server** to use Azure SignalR. You put the connection string in the server configuration, not the client.

See the [Azure SignalR Samples](https://github.com/aspnet/AzureSignalR-samples/tree/master/aspnet-samples/ChatRoom) repository.

**Comment by arteny** [comment]
@anurse which server? what do you mean? there is no any server. question is about _Azure_ SignalR service. it is already configurated server itself. and I can use it with a connection string using Microsoft.AspNetCore.SignalR.Client.HubConnectionBuilder but there is no HubConnectionBuilder in AspNet.SignalR.Client

**Comment by anurse** [comment]
I'd suggest taking a look at the samples repo I linked above and walk through some of those samples to get a feel for things.

**Comment by BrennanConroy** [comment]
>If you mean server side which send messages, I don't worry about it, because it is configurated and works well (tested with AspNetCore client)

Are you using an AspNetCore SignalR server with an Asp.Net SignalR Client? Those are incompatible and will never work together. You need to use either both Asp.Net SignalR on client and server, or Asp.Net Core SignalR for both.

**Comment by anurse** [comment]
> I have desktop server side, Azure SignalR service and desktop client side and all works well in this configuration there: server side can send broadcast messages, client side can receive those messages

Yes, this works fine. The sample I linked (https://github.com/aspnet/AzureSignalR-samples/tree/master/aspnet-samples/ChatRoom) shows how to use ASP.NET SignalR (`Microsoft.AspNet.SignalR`, the one for **ASP.NET 4.5**) on both the client and server using the Azure SignalR service.

If you are using ASP.NET **Core** SignalR (`Microsoft.AspNetCore.SignalR.Client` and `Microsoft.AspNetCore.App` on the server) then it **also** works fine with the service, but here you need an **ASP.NET Core** server and an **ASP.NET Core** client.

Perhaps if you shared a project that reproduces the error you're seeing we could do a better job of helping you track down the issue.

**Comment by arteny** [comment]
@anurse , ChatRoom is web app AspNet client, it uses the connection string:
`<connectionStrings>
    <add name="Azure:SignalR:ConnectionString" connectionString="Endpoint=...;AccessKey=..."/>
</connectionStrings>`
but i need client for desktop .net app (console app for instance), there are examples how to use Azure (Microsoft.AspNet.SingalR.Client) with AspNet site, but there is no any how to use it from desktop app, it is the point of my issue

**Comment by anurse** [comment]
> ChatRoom is web app AspNet client, it uses the connection string:

Ok, I think this is the source of the confusion. I presume this AspNet app is where your Hubs are defined? The app is your **server**. The JavaScript code in your app is a **client**. The connection string is configuring the **server** and not the client. The JavaScript client is connecting the same way it would without the Azure SignalR service.

Connecting your desktop client to the server requires no additional configuration related to the service. Just connect to your server as you would in a normal SignalR scenario (without the service). If you haven't customized the URL (by specifying a different path in your call to `MapAzureSignalR`) then the URL will just be `http://[your app base]/signalr`.

> but there is no any how to use it from desktop app

I'd suggest filing an issue with the Azure SignalR team about adding desktop samples. They are a different team and use the GitHub repo https://github.com/Azure/azure-signalr .

**Comment by arteny** [comment]
> then the URL will just be `http://[your app base]/signalr`

Checked again code above with
HubConnection hubConnection = new HubConnection("https://myname.service.signalr.net:5001")
and
HubConnection hubConnection = new HubConnection("https://myname.service.signalr.net")
and it is also not works with same error.

> I'd suggest filing an issue with the Azure SignalR team about adding desktop samples

Waiting for an answer from them.

**Comment by anurse** [comment]
You need to post a sample project for us to be able to understand the structure of your app. From what you've described it sounds like you've got an ASP.NET Server app and you want to build a .NET client app to connect to it, but I've heard a lot of conflicting information in this thread.

Your Web App is the server, that has to be configured with the Azure SignalR Connection String. Your .NET Client app is the client, it doesn't need any Azure SignalR configuration and it **does not connect to `myname.service.signalr.net`**, it connects to whatever URL your WebApp is hosted at.
