### ISSUE TITLE
Self-hosted SignalR server CORS issue when SQL Server Scaled out

### ISSUE THREAD

**Issue by afshinjafari** [SignalR/SignalR#4275]
I have successfully implemented a self hosted SignalR windows service on **HTTPS** using version 2.4.0
now when I tried to scale out the solution using SQL Server the good old CORS issue comes back!
This is my startup:

```
public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            GlobalHost.DependencyResolver.UseSqlServer(ConfigurationManager.AppSettings["SignalRConnectionString"]);
            var hubConfiguration = new HubConfiguration
            {
                EnableDetailedErrors = true,
                EnableJSONP = true,
            };
            app.UseCors(CorsOptions.AllowAll);
            app.MapSignalR(hubConfiguration);
        }
    }

```

**Comment by BrennanConroy** [comment]
>the good old CORS issue comes back!

Could you explain what the issue is?

**Comment by afshinjafari** [comment]
when browsing the SignalRURL/SignalR/hubs I can see the script
however the javascript cannot connect start the hub due to CORS error.
when I comment out the line with 'UseSqlServer' everything works fine

![image](https://user-images.githubusercontent.com/20033439/49838290-b1680800-fdf5-11e8-90aa-522c3ff11f32.png)

**Comment by BrennanConroy** [comment]
Try https://forums.asp.net/t/1987508.aspx?SignalR+SQL+backplane+breaks+CORS

**Comment by afshinjafari** [comment]
Thanks Brennan,
I had seen that thread before and tried the suggestion, unfortunately did not help and still had the same error. I'll give it another go again.

**Comment by muratg** [comment]
Let us know if you're still having issues.

**Comment by afshinjafari** [comment]
I know it's been a long time since this however for the future reference if someone got the same problem: the 500 Internal Server Error was the key! problem was the server did not have access to sql server database 'SignalR' to create required tables. after giving owner permission it was able to create tables on the first call then downgraded to read/write.
interestingly the server did not throw any exceptions only returned 500 error and then CORS error which was totally irrelevant.
