### ISSUE TITLE
Error installing SignalR .NET Client 2.4.0 from NuGet in Visual Studio 2012

### ISSUE THREAD

**Issue by CristianNicolaeMyPOS** [SignalR/SignalR#4276]
### Expected  behavior
Succesfully installing the package

### Actual behavior
Throws the following error, even in an blank web project:
Attempting to resolve dependency 'Newtonsoft.Json (≥ 6.0.4)'.
'Microsoft.AspNet.SignalR.Client' already has a dependency defined for 'Newtonsoft.Json'.

### Steps to reproduce
1. Create a new ASP.NET Empty Web Application project in Visual Studio 2012 Update 5
2. Install "Microsoft ASP.NET SignalR .NET Client"

![signalr_install_error](https://user-images.githubusercontent.com/45711222/49802741-719e1380-fd56-11e8-9577-a326bb836efd.png)

**Comment by jcoutch** [comment]
@CristianNicolaeMyPOS - The latest versions of Microsoft.AspNet.SignalR and Microsoft.AspNet.SignalR.Client are NetStandard NuGet packages, and AFAIK, aren't supported in Visual Studio 2012:
https://github.com/NuGet/Home/issues/3131

You would either need to upgrade to a newer version of Visual Studio, or try installing the last non-NetStandard package (version 2.2.1):
https://www.nuget.org/packages/Microsoft.AspNet.SignalR.Client/2.2.1
