### ISSUE TITLE
signalr/hubs not found

### ISSUE THREAD

**Issue by colotoon** [SignalR/SignalR#4278]
hello...

i start learn signalr lib, i did simple chat app using ur manual:

https://docs.microsoft.com/ru-ru/aspnet/signalr/overview/getting-started/tutorial-getting-started-with-signalr

All works fine, BUT, then i publish app to IIS - its not work, brouser console says: signalr/hubs 404 not found!
startup class

`namespace chat
{
    public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            // Any connection or hub wire up and configuration should go here
            app.MapSignalR();
        }
    }
}`

hubs class
`namespace chat
{
    public class ChatHub : Hub
    {
        public void Send(string name, string message)
        {
            // save msg to DB //
            this.saveMSG(name, message);
            // Call the broadcastMessage method to update clients.
            Clients.All.broadcastMessage(name, message);
        }
}}`

index.html
```
<!DOCTYPE html>
<html>
<head>
    <title>SignalR Simple Chat</title>
    <style type="text/css">
        .container {
            background-color: #99CCFF;
            border: thick solid #808080;
            padding: 20px;
            margin: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <input type="text" id="message" />
        <input type="button" id="sendmessage" value="Send" />
        <input type="hidden" id="displayname" />
        <ul id="discussion">
        </ul>
    </div>
    <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="Scripts/jquery-1.6.4.min.js"></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.4.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <!--Add script to update the page and send messages.--> 
    <script type="text/javascript">
        $(function () {
            // Declare a proxy to reference the hub. 
            var chat = $.connection.chatHub;
            // Create a function that the hub can call to broadcast messages.
            chat.client.broadcastMessage = function (name, message) {
                // Html encode display name and message. 
                var encodedName = $('<div />').text(name).html();
                var encodedMsg = $('<div />').text(message).html();
                // Add the message to the page. 
                $('#discussion').append('<li><strong>' + encodedName
                    + '</strong>:&nbsp;&nbsp;' + encodedMsg + '</li>');
            };
            // Get the user name and store it to prepend to messages.
            $('#displayname').val(prompt('Enter your name:', ''));
            // Set initial focus to message input box.  
            $('#message').focus();
            // Start the connection.
            $.connection.hub.start().done(function () {
                $('#sendmessage').click(function () {
                    // Call the Send method on the hub. 
                    chat.server.send($('#displayname').val(), $('#message').val());
                    // Clear text box and reset focus for next comment. 
                    $('#message').val('').focus();
                });
            });
        });
    </script>
</body>
</html>
```

SignalR installed over NuGet!
.Net 4.7.2

**Comment by colotoon** [comment]
and yes, i read this:

https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-javascript-client#genproxy

all of this - not help:

<script src="~/signalr/hubs"></script>

<script src="@Url.Content("~/signalr/hubs")"></script>  (this is not working like code)

<script src='<%: ResolveClientUrl("~/signalr/hubs") %>'></script> (this is not working like code)

Then i did server.js over signalr tools - signalr/hubs error was gone!

But, i have new error:

jquery-1.6.4.min.js:4

GET http://localhost/signalr/negotiate?clientProtocol=2.0&connectionData=%5B%7B%22name%22%3A%22chathub%22%7D%5D&_=1544875075171

404 (Not Found)

At VS all woking fine, but at IIS - no =\

**Comment by BrennanConroy** [comment]
Have you taken a look at the self-hosting docs? https://docs.microsoft.com/aspnet/signalr/overview/deployment/tutorial-signalr-self-host
