### ISSUE TITLE
Offline installation

### ISSUE THREAD

**Issue by ShiraGrin** [SignalR/SignalR#4282]
Expected  behavior
Successfully install when running build.cmd

Actual behavior
The command try to download Korebuild 3.0.0-alpha1-20180911.2 but getting this error:

Downloading KoreBuild 3.0.0-alpha1-20180911.2
Get-RemoteFile : Download failed: 'https://aspnetcore.blob.core.windows.net/buildtools/korebuild/artifacts/3.0.0-alpha1
-20180911.2/korebuild.3.0.0-alpha1-20180911.2.zip'.
At C:\Users\Shira\Desktop\SignalR-master\run.ps1:115 char:13
+             Get-RemoteFile $remotePath $tmpfile $ToolsSourceSuffix
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-RemoteFile

Steps to reproduce:
1. Download the repository from https://github.com/SignalR/SignalR
2. Open cmd as administrator
3. Run build.cmd from the cmd. 

I want to use SignalR on Offline machine. Is it possible to to install SignalR without internet connection?

tnx

**Comment by BrennanConroy** [comment]
If you just want to install SignalR then restore the packages from NuGet.

If you are actually wanting to build the repo then offline builds aren't an interesting scenario for us and will not be supported.
