### ISSUE TITLE
SignalR Subscriber client(.NET Core/Angular 4) connected but not received message after few minutes

### ISSUE THREAD

**Issue by meerajoy4** [SignalR/SignalR#4283]
> I have done a signalR application using asp .net core and angular 4.
> using aspnet core signalR version 1.1.0 and @aspnet/signalr 1.1.0 in client side.
> using the Redis backplane (redis_version 1.1.0)
> We are not using groups though just sending messages by connection id.
> after 5 minutes idle js clients stop receiving messages(client already connected but unable to received data).
> need to connect again for recieving message from sever.

Any idea?

**Comment by mikaelm12** [comment]
Sorry it's a bit unclear to me. Are you saying that you're trying to mix using classic asp.net and asp.net core on the server and client, because that will not work.
Or are you just saying that in the past you have used SignalR on asp.net?

**Comment by muratg** [comment]
@meerajoy4 Are you using a backplane? Or the Signalr service? Or neither?

**Comment by nikunj231991** [comment]
I am using signalR with websockets and facing same issue. In local its works fine but when i will deploy in Azure and also enabling websockets there after some time not receiving signals client side. Also traced all logs server is sending signals but client not receiving. If i restart azure webapp then it will work for 2-3 minute then same issue.
Don't know it is code issue or azure or library.

**Comment by muratg** [comment]
This issue was moved to aspnet/AspNetCore#6923
