### ISSUE TITLE
[Azure SignalR]Support query string for RedirectUrl for JS and C# client

### ISSUE THREAD

**Issue by vicancy** [SignalR/SignalR#4284]
When using Azure SignalR, it is possible that `/negotiate` returns `RedirectUrl` with query string inside, however, current JavaScript and C# client do not support such scenario

**Comment by mikaelm12** [comment]
Hmm yeah, looks as though you are right. We just set the redirect url as the new negotiate url. In what scenario would the Azure SignalR Service return a redirect url with a query string? I don't think I've seen this before.
https://github.com/SignalR/SignalR/blob/fc475fa161eaf94150c4aaa4ba71830fd976eb6c/src/Microsoft.AspNet.SignalR.Client/Connection.cs#L520
https://github.com/SignalR/SignalR/blob/fc475fa161eaf94150c4aaa4ba71830fd976eb6c/src/Microsoft.AspNet.SignalR.JS/jquery.signalR.core.js#L749

**Comment by vicancy** [comment]
Currently the core version of SignalR uses this to preserve original path and query string, see https://github.com/Azure/azure-signalr/issues/108#issuecomment-414355646 for one scenario. I am thinking if the ASP.NET one has similar requirements.

**Comment by muratg** [comment]
Do we have any customer complaints? Is the broken scenario more of a corner case? Is there any workaround for customers? Trying to get a sense of patch-worthiness.

cc @bradygaster

**Comment by bradygaster** [comment]
thanks for adding - i'd like to know if we've had many customer complaints on this before we dive in.

**Comment by vicancy** [comment]
> Do we have any customer complaints that?

No, not yet. 

> Is there any workaround for customers

Yes, kind of, they can add the info to a custom claim.

**Comment by muratg** [comment]
Thanks @vicancy. Let's see if we get any customer feedback on this to decide if we want to roll a patch.

**Comment by vicancy** [comment]
Hi @muratg We now have one feature that dependent on this one https://github.com/Azure/azure-signalr/issues/346

**Comment by muratg** [comment]
@vicancy thanks for the update. 

cc @davidfowl and @halter73 for their thoughts.

**Comment by anurse** [comment]
This is fixed in version [2.4.1](https://github.com/SignalR/SignalR/releases/tag/2.4.1) which is now released to NuGet.org and NPM.
