### ISSUE TITLE
OWIN service does't send all messages to clients (ONLY AZURE, locally working)

### ISSUE THREAD

**Issue by patsadow2** [SignalR/SignalR#4286]
Hello,

I've got a problem like in a title. 

Locally everything is working correctly.
On azure sometimes i get messages sometimes they are lost.

I use "App Service" for mobile app.
App Service Plan: Small 
Websocket: True
Always On: True

LOG:
useragent : SignalR.Client.NetStandard/2.4.0.0 (Microsoft Windows NT 10.0.16299.0)
1/7/2019, 11:41:09 AM - REQUEST
POST /signalr/poll
Request URL host: https://XXX.azurewebsites.net/Response code: 200Server response time: 1 min 54 s

Version:
Microsoft.AspNet.SignalR 2.4.0

Mobile: 
Also 2.4.0
Client default/long polling

   ```
         app.MapSignalR();
            GlobalHost.Configuration.DefaultMessageBufferSize = 8000;
            GlobalHost.Configuration.KeepAlive = TimeSpan.FromSeconds(2);
```

 ```
    public class EventHub : Hub
    {
        public static readonly ConnectionMapping<string> Connections = 
            new ConnectionMapping<string>();

        public override Task OnConnected()
        {
            Connections.Add(GetUserId(), Context.ConnectionId);
            return base.OnConnected();
        }

        public override Task OnDisconnected(bool stopCalled)
        {
            Connections.Remove(GetUserId(), Context.ConnectionId);
            return base.OnDisconnected(stopCalled);
        }

        public override Task OnReconnected()
        {
            string identityId = GetUserId();
            if (!Connections.GetConnections(identityId).Contains(Context.ConnectionId))
            {
                Connections.Add(identityId, Context.ConnectionId);
            }
            return base.OnReconnected();
        }

        private string GetUserId()
        {
            return Context.Headers["user_id"];
        }
    }


```

**Comment by bradygaster** [comment]
Does it send some messages at all? Is it intermittent? Have you any logs? 

Also - this seems like a scale-out issue. Are you using a backplane? Or the SignalR Service? Thanks!

**Comment by patsadow2** [comment]
I use App Service [Old mobile service in Azure portal] with Owin.

 sometimes it send some messages, for example 3 message received, 2 not, 4 received, 1 not etc. Sometimes when i restart the service it doesn't get any messages and sometimes when i restart, the client receive 3 messages then 2 are missing then 4 messages then 3 missing etc.

I was thought it was connected with buffer but when i increased a size it didn't help ;/

During the process handshake is working correctly, the problem is only with messages.

**Comment by muratg** [comment]
@patsadow2 Are you using a backplane? Or are you using the Signalr Service? Or neither?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
