### ISSUE TITLE
HttpContext.Current.User no longer set in OnReconnected

### ISSUE THREAD

**Issue by dnallicus** [SignalR/SignalR#4289]
### Expected  behavior
HttpContext.Current?.User?.Identity?.Name is set correctly OnReconnected method in the Hub
### Actual behavior
HttpContext.Current?.User?.Identity?.Name is null when running OnReconnected method in the Hub
### Steps to reproduce
When using Windows Authentication, we did an IIS reset and the OnReconnected no longer has the HttpContect.Current.User variable set.  This was working in 2.2.1, but doesn't work in 2.4.0.  I was able to fix by using Context.User.Identity.Name, but I don't know if it was expected that HttpContext.Current no longer worked.

**Comment by muratg** [comment]
@dnallicus AFAIK, we haven't made any changes to the reconnect logic in the last few releases. 

@tratcher can you think of why this may be the case?

**Comment by ashrafsabrym** [comment]
This issue occurs to me too and it breaks my logic
