### ISSUE TITLE
Update server-side data through a client message

### ISSUE THREAD

**Issue by killdary** [SignalR/SignalR#4291]
Good afternoon,
I am building a Supervisory System that monitor certain equipments. Using SignalR this easy send datafrom server to clients through IHubContext.

My question is how I can send data from a client to server in a classs different of the Hub?

I need update a data in Server out of the Hub Class.

**Comment by muratg** [comment]
Why don't you make the changes in wherever through the Hub class methods?

**Comment by killdary** [comment]
My equipment is factory machines, they only accept a single connection, when the server is started it makes a continuous connection with all the equipment, when the equipment executes some change of state then all the clients are updated, using IContext.

My problem is that I need clients to send new status as soon as the server identifies that it has received these new statuses, it sends to the devices, but I do not know how to send Hub commands to the main server class as it is in the main class that the connections with the equipment were made.

**Comment by muratg** [comment]
Your Hub class and your main server class are on the same machine, right? I don't know your architecture, but can you use delegates you can call from the hub? Or call main server methods from the hub methods?

There's a thing called `PersistentConnection`, but I do not recommend it, hub is an abstraction around that and makes things _much_ easier.

**Comment by killdary** [comment]
Yes my hub class and main class are on the same machine, I tried put delegates in the hub, but I dont know how I use of the hub in main because I used the ```Icontext```.

My main class initialize the SignalR: 
```c#
 var iniciar_signalr = WebApp.Start(url);
```

and in some one in my code I use the hub 
``` c#
IHubContext ContextoClient = GlobalHost.ConnectionManager.GetHubContext<SomeHub>();
...
ContextoClient.Clients.Group("Group_1").updateStatus(EquipmentWhithNewStatus);
```

How I use delegate in my architecture? And how I call the methods  of the main class inside the methods of the hub  class ?

**Comment by muratg** [comment]
Sorry, without better understanding your architecture I can't help much. Perhaps try StackOverflow?

**Comment by killdary** [comment]
I appreciate your help,

But I can explain my architecture:
I have, briefly, 3 classes:

- **Main Class**: has a list of connection data of the equipment that I must communicate, and the server SignalR;

- **Equipment Class**: which receives the communication data and communicates with the equipment, this class has an event that is executed whenever the status change (ChangeStatus);

- **EquipmentHub Class**: class with functions that updates my clients;


When the system starts, the connection data is picked up and a connection is made to each device, the equipment is placed in a list.
```c#
static List<Equipments> lst_equipments;
Main(){
	List<string> lst_data_connection = getEquipments();
	lst_equipments = new List<Equipments>();

	var iniciar_signalr = WebApp.Start(url);

	foreach(string _tmp_data in lst_data_connection){
		 Equipment _tmp_equipment = new Equipment();
		 _tmp_equipment.ChangeStatus += EventForUpdateStatus;
		 _tmp_equipment.start(_tmp_data );

		 lst_equipments.Add(_tmp_equipment);
	}
}

private void EventForUpdateStatus(SomeType data_status){
	IHubContext ContextoClient = GlobalHost.ConnectionManager.GetHubContext<EquipmentHub >();
	ContextoClient.Clients.All.updateStatus(data_status);
}
```

This is it, I need the client to send me a command, my ```EquipmentHub``` class receives this command, the``` EquipmentHub``` class must pass to the ```main``` class the command and the ```main``` class update the desired equipment on my equipment list.
