### ISSUE TITLE
Issues with MS DTC after changing to SQL Server backplane

### ISSUE THREAD

**Issue by ajbeaven** [SignalR/SignalR#4292]
I've recently made a change to move to a SQL Server backplane in order to facilitate SignalR communication between clients connected to two separate domains. Those sites are hosted on the same server but they share the same database hosted on a separate remote server.

Soon after pushing this live I started getting error reports related to MS DTC:

```
System.Runtime.InteropServices.COMException: The transaction manager has disabled its support for remote/network transactions
```

I hadn't used MS DTC before so the servers were not configured correctly. I configured them assuming that perhaps this was necessary for the SQL Server backplane. Now I'm getting exceptions like the following:
```
System.Data.SqlClient.SqlException: Current Microsoft Distributed Transaction Coordinator (MS DTC) transaction must be committed by remote client
```
```
System.Data.SqlClient.SqlException: Transaction context in use by another session
```
```
System.Data.SqlClient.SqlException: The transaction operation cannot be performed because there are pending requests working on this transaction
```

That second lot of exceptions occur when running usual queries on my database inside a transaction scope ie. queries unrelated to the backplane. I've never before received these exceptions with these queries, so I assume they're now being promoted to a distributed transaction due to something happening in the backplane?

Note these exceptions are intermittent but frequent - I can't reliably produce.

So why does the SQL Server backplane cause MS DTC to become involved? If it's possible, how do I stop this from occurring?

**Comment by ajbeaven** [comment]
I note that the [DataReader opened in DbOperation.cs](https://github.com/SignalR/SignalR/blob/3c07d7bebc15ec9cbf6ac9d7339b5d2d54f6fab3/src/Microsoft.AspNet.SignalR.SqlServer/DbOperation.cs#L89) is never explicitly closed or disposed of, which seems to be best practice. The underlying connection is disposed so perhaps this is of no relevance.

**Comment by anurse** [comment]
@ajbeaven do you have any usage of `TransactionScope` in your code? This can occur if two `SqlConnection`s are created within the same transaction scope, because the DTC is required to coordinate the transaction across both connections.

**Comment by ajbeaven** [comment]
Yep, I use `TransactionScope`. It's fine if DTC is required, I would just expect the SQL Server Backplane to not fall over when it used it and instead handle the case gracefully. I have since moved to Azure Service Broker so this so longer impacts me.

**Comment by anurse** [comment]
> It's fine if DTC is required, I would just expect the SQL Server Backplane to not fall over when it used it and instead handle the case gracefully.

It's not really something we control. Unfortunately, in this case, you've defined a transaction scope and the SQL backplane has to participate in that. One option may be for us to create a new `TransactionScope` and suppress the ambient scope, but that would also be a pretty significant breaking change at this point since our current behavior participates in whatever transactions you have.

> I have since moved to Azure Service Broker so this so longer impacts me.

I'm glad you have found a resolution that works for you.

**Comment by ajbeaven** [comment]
Fair enough, though the docs should at least be updated to say that the SQL Server Backplane doesn't work with `TransactionScope`, if they haven't already. Thanks for the triage :)

**Comment by anurse** [comment]
Good idea, I'll take a look at making that update.
