### ISSUE TITLE
Hub methods are not invoked after an exception

### ISSUE THREAD

**Issue by Floppe** [SignalR/SignalR#4293]
In some rare cases using SignalR on mobile devices an error is thrown. I guess when there is a really bad network.

`SignalR: Connection has not been fully initialized. Use .start().done() or .start().fail() to run logic after the connection has started.
`

Nothing is ever sent anymore to the server on that hub after that error is thrown. I guess a promise is dangling loose. Only way to fix it is to stop the hub connection and start it back up.

I could not see anything related in current release logs so still using SignalR version 2.2.2

### Expected  behavior
Log an error and keep on working after that

### Actual behavior
Error logged
No hub method are invoked anymore

### Steps to reproduce
Can't find any good way, but fix a breakpoint on connection.send and make it trigger the exception is one way by modifying the connection state manually and continue code execution.

**Comment by muratg** [comment]
Can you share the code that reproduces this problem?

**Comment by Floppe** [comment]
I haven't been able to reproduce it so I see no idea to start breaking out the code. I've gone through the logs today and found another device which I believe encountered the same issue.

Could be the description of this issue is totally wrong. What is common is that both devices had logged "...exceeded the inactivity timeout of 500000 ms. Stopping the connection."

And afterwards they connect again with webSockets. Then yet again it times out and exact same timestamp the above exception is thrown. Time resolution in seconds so do not know which log message was sent first to the server. Anyhow, seems something is trying to send data although not connected. And after that nothing is sent to to the hub. No error, nothing.

A workaround I've made is to catch the first error and re-start the hub connection.

I'm using a promise to get the $.connection.hub which makes sure it's started. Perhaps something there if no-one have experienced same issue.

```
        // start hub
        var startHub = function () {
            if (!hubDeferred || hubDeferred.state() === 'rejected') {
                hubDeferred = $.Deferred();

                $.connection.hub.start()
                    .done(function (hub) {
                        try {
// removed code which saves all states, id and so on for logging
                            hubDeferred.resolve(hub);
                        } catch (error) {
                            hubDeferred.reject(error);
                        }
                    })
                    .fail(function (result) {
                        if (hubDeferred && hubDeferred.reject) {
                            hubDeferred.reject(result);
                        }
                    });
            }

            return hubDeferred.promise();
        };

```

And somewhere I've this code which re-connects the hub if disconnected.

```
                $.connection.hub.disconnected(function () {
                    if (hubDeferred && hubDeferred.reject) {
                        hubDeferred.reject();
                    }

                    hubDeferred = undefined;
                    // restart connection after 15 seconds
                    setTimeout(function () { startHub(); }, 15000);
                });

```

**Comment by anurse** [comment]
@Floppe are you still experiencing this issue? What does the code that calls `startHub` look like?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
