### ISSUE TITLE
The redis Strongname Package has been discontinued and not been updated in a year

### ISSUE THREAD

**Issue by dmartensson** [SignalR/SignalR#4294]
### Expected  behavior
It should depend on the live version av StackExchangeRedis as the strngname package 
This prevents projects depending on SignalR.Redis from switching from the strongname to the normal Redis package (which now is strongnamed by default)

### Actual behavior
It depends on a package that are no longer being maintained
https://github.com/Azure/aspnet-redis-providers/issues/107

**Comment by BrennanConroy** [comment]
We released a new version of the reids package that uses the StackExchange 2.0 package. https://www.nuget.org/packages/Microsoft.AspNet.SignalR.StackExchangeRedis

And made a blog post about the new updates https://blogs.msdn.microsoft.com/webdev/2018/11/14/asp-net-signalr-2-4-0/
