### ISSUE TITLE
"NetworkError: 500 Internal Server Error

### ISSUE THREAD

**Issue by khcc** [SignalR/SignalR#430]
When I am running the web site on my local computer it works properly, but when I uploading to my domain, its starts to generates this error. I am in rush, and it is very critical for me, I have done the whole project based on Signal and I m confused now, please please please help me soon.

Regards

**Comment by raddevus** [comment]
It's August, 2017 and I have a GoDaddy account also.  I have a very small sample app using SignalR which runs perfectly on localhost but will not run at my GoDaddy Site.
I have given full trust in web.config.  I have set up virtual directories for signalr/hubs (in a vain hope that somehow the .NET generated hub would work). Nothing actually works and you always get the 500 internal server error.
Finally, I got a free account at [smarterasp.net](http://www.SmarterASP.NET/index?r=100758111), dropped in the same code that is running on my localhost and it worked perfectly.
You can see the article I wrote and see the sample at [SignalR - @ codeproject](https://www.codeproject.com/Articles/1188400/Beginners-Guide-to-Using-SignalR-via-ASP-NET)
