### ISSUE TITLE
Got error when Install web farm(ARR)

### ISSUE THREAD

**Issue by cseppd** [SignalR/SignalR#4302]
I work .net 4.5 with mvc5. When I use a  web farm(ARR) with 2/3 worker application servers  then got error: WebSocket connection to 'wss://www.amarstock.com/signalr/connect?transport=webSockets&clientProtocol=1.5&connectionToken=Qir%2B%2BU3hfQvhD9LCcsiCrx%2Fg0rjvHa7Kl828HCUsoSZK6d2MFxRvYZAusWTMNa6rhXbgkvROc6Fvj%2FO%2BhZ2N0UWyewCnwQ7b%2BA%2FsCX4m9mJhFe%2FG2gTOJ%2BElb8wGMy0z&connectionData=%5B%7B%22name%22%3A%22alertcenterhub%22%7D%5D&tid=3' failed: Error during WebSocket handshake: Unexpected response code: 400.
I use a common machine key to all application servers but the error still exists. 
Please help me asap.

**Comment by cseppd** [comment]
Hi, If I disable (uncheck) request consolidation, then the error disappear. Is it efficient to resolve this error??
But if I need this option for live streaming request optimization, then what I do??

**Comment by bradygaster** [comment]
Is there some way if you could tell if the request getting to your actual service back-end is unchanged? We're thinking the ARR configuration might change the HTTP request in-flight, as that's the only idea we can have as to why you'd be getting a "bad request" 4xx error.

**Comment by akshaybhuradia2020** [comment]
i am getting same issue with nginx load balancer

Please see these issue #4489 

@cseppd did you get work around?
