### ISSUE TITLE
Upgrading Microsoft.AspNet.SignalR.de fails

### ISSUE THREAD

**Issue by AlexanderPilhar** [SignalR/SignalR#4308]
Upgrading NuGet package `Microsoft.AspNet.SignalR.de` (2.3.0 to 2.4.0) fails because it depends on `Microsoft.AspNet.SignalR.SystemWeb.en-US` which cannot be found.

**Comment by halter73** [comment]
Thanks for the report! This is a dupe of #4271. We are working to quickly release a 2.4.1 update to fix the issue.
