### ISSUE TITLE
Js: hub methods get fired n+1 times on restarting connection

### ISSUE THREAD

**Issue by elgerm** [SignalR/SignalR#4310]
This new 'feature' came up while putting 2.4.0 in production a while ago. Users started getting duplicate or even sometimes 10x the same messages or any hub related events. In my code I have some reconnection logic as described in the [docs.](https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/handling-connection-lifetime-events#how-to-continuously-reconnect)

Turns out every time you invoke start, all hub methods get an additional subscription, causing all of them to get fired twice (or as many times as you invoke hub.start()).

### Expected  behavior

 hub.start() checks if subscriptions are in place and if so, doesn't add another one.

### Actual behavior

hub.start() adds extra subscription to all hub methods, causing them to fire multiple times.

### Steps to reproduce

install 2.4.0 js client: 
- start a simple signal chat program, with an js hub method onmessage or something. Disconnect signalr and start hub again.
- invoke hub method via a second browser, see message appearing twice

install 2.3.0 js client:
- do the same and see message appearing only 1 time.

**Comment by bradygaster** [comment]
do you have any sample code? it would be helpful in helping troubleshoot. also - are you re-attaching the on handlers? 

 thanks!

**Comment by elgerm** [comment]
> do you have any sample code? it would be helpful in helping troubleshoot. also - are you re-attaching the on handlers?
> 
> thanks!

No, not re attaching anyting, just call $.connection.hub.stop() and then start() a few times on the js client of any project. You'll see it immediately.

Here's a sample project I forked from some other issue and just installed the 2.4.0 js client over it and added some buttons (dont look at the title):

https://github.com/elgerm/SignalRConnectionLimitIssue

I'm quite suprised that nobody else stubled on this issue.

**Comment by elgerm** [comment]
Did you have time to check it out? It's really a nasty bug. Downgrading to 2.3 (js only) seems to work for me for the moment.

**Comment by rpeh** [comment]
I just tried this myself in my own project (because it would present a huge problem if I were to get the same behaviour) and couldn't replicate this issue. I don't see anything wrong with your code though.

**Comment by elgerm** [comment]
Are you using the 2.4.0 js client (jquery.signalR-2.4.0.js)? With both projects (the one I forked above and my own project) I can repro this issue by simply switching version from 2.4 to a lower one.

**Comment by rpeh** [comment]
> Are you using the 2.4.0 js client (jquery.signalR-2.4.0.js)? 

Yes. First thing I checked. I'm not using your own code, I'm testing it on my own. These are the steps I took:
1) Connect two clients to the server.
2) Send a message from one client to the other - one message received.
3) Stop the hub on one client
4) Start the hub several times (I tried various numbers of restarts).
5) Send another message - one message received.

I also modified my code to display the connection id after each Start. The first restart generated a different id but subsequent starts returned the same id - as I'd expect.

**Comment by halter73** [comment]
@elgerm I was able to run your sample, and I found the issue happens when a newer client client (Microsoft.AspNet.SignalR.JS 2.4.0) connects to an older server (Microsoft.AspNet.SignalR.Core 2.2.1). If you update the server to 2.4.0, you should no longer see this issue.

This is still a bug, since newer clients should be able to connect to older servers without issue.

**Comment by anurse** [comment]
This is fixed in version [2.4.1](https://github.com/SignalR/SignalR/releases/tag/2.4.1) which is now released to NuGet.org and NPM.
