### ISSUE TITLE
Portable Class Library

### ISSUE THREAD

**Issue by gdorigo** [SignalR/SignalR#4311]
# Issues related to the Asp.NET Core version of SignalR should be filed in the corresponding SignalR repo: https://github.com/aspnet/?utf8=%E2%9C%93&query=Signalr

### Expected  behavior

2.4.0 do not support Portable Class Library

### Steps to reproduce

Try to update 2.3.0

**Comment by halter73** [comment]
Sadly, if you need PCL support you have to use 2.3.0. You can also look into netstandard and see if that target works for your scenario.
