### ISSUE TITLE
Most all samples project unloaded when loading full Solution

### ISSUE THREAD

**Issue by vRITHNER** [SignalR/SignalR#4313]
### Expected  behavior
Load Microsoft.AspNet.SignalR.sln
See all samples

### Actual behavior
Load Microsoft.AspNet.SignalR.sln
Most all samples' project are unloaded

### Steps to reproduce
git clone SignalR repo
Load .sln
When I try to reload any project, I got an error:

> Project file is incomplete. Expected imports are missing.

![2019-02-21_11h17_09](https://user-images.githubusercontent.com/238842/53163775-25314880-35cf-11e9-8482-eed6e52ed60a.png)

Thanks
-Vince

**Comment by d1trut5r** [comment]
Hi - if you find this is this still a problem - here is a possible solution - see image attached.

Step 1: In the Solution Explorer - "switch view" See Image Step 1.
Step 2: Find global.json file,
Step 3: If you HAVE downloaded DotNet CoreSDK then update your version number to the relevant version (See image Step 3) --- Run Powershell "dotnet --info" to find your version. (https://dotnet.microsoft.com/download/dotnet-core/)
Step 4: Save file.
Step 5: Switch View (Same as Step 1)
Step 6: Reload Project(s) or Solution

Hope this help. 

![SignalR](https://user-images.githubusercontent.com/3378958/71836651-2111fa80-30bd-11ea-9b67-4411d49276ac.png)

**Comment by BrennanConroy** [comment]
Opening this solution requires VS 2017, that looks like VS 2019 so your mileage may vary.
