### ISSUE TITLE
SignalR Memory Leak when SQL backplane connection is not available or misconfigured

### ISSUE THREAD

**Issue by dotneteval** [SignalR/SignalR#4314]
### Expected  behavior
When the SignalR hub server is misconfigured e.g. DB Server incorrect, when a client connects and fails any memory should be freed up. Also would expect to be able to catch an exception showing the misconfiguration to enable logging and remedial action.

### Actual behavior
In IIS the memory keeps increasing as the clients attempt to make a new connection. There doesn't seem to be a away of detecting this misconfiguration and therefore being able to log the error and take remedial action.

### Steps to reproduce
Pass an invalid connection string to GlobalHost.DependencyResolver.UseSqlServer method in Startup.cs class. Then have a client attempt to connect at regular intervals, for example 20 seconds. The memory increases in IIS. The attached file shows the signalr bus error. The error shown below just repeats forever

SignalR.SqlMessageBus	Error	0	Error trying to install SQL server objects, trying again in 2 seconds: System.Threading.ThreadAbortException: Thread was being aborted.
   at Microsoft.AspNet.SignalR.SqlServer.SqlInstaller.Install()
   at Microsoft.AspNet.SignalR.SqlServer.SqlMessageBus.Initialize(Object state)

I original found the bug in version 2.2.1 but it is also doing this with 2.4.0

 I am using the .NET version of SignalR for both client and server.

[SignalRBusLog-2019-02-26.log](https://github.com/SignalR/SignalR/files/2905059/SignalRBusLog-2019-02-26.log)

**Comment by m-mccool** [comment]
Further update, even if I stop the process which is trying to connect , the error continues to be logged and the memory increases. Does anyone know why Signalr is calling these methods to install SQL server objects

**Comment by m-mccool** [comment]
Further update, event after stopping the service which is attempting to connect, the SignalR Bus Log is still showing attempts to install SignalR objects. I'm assuming this is attempting to create the SignalR tables in the database. However this is never going to happen as I have set the wrong database server (on purpose) in the connection string.

I'm assuming that it keeps trying to do this as the database server and the configured database may appear at some point. However it seems to be leaking quite badly, and it is happening every two seconds.

**Comment by m-mccool** [comment]
Further update - If I set the correct SQL connection string, and my client connects successfully, then I take the database offline. The same cycle occurs, it keeps occurring even when I put the database back online.

The problem here is that you may intermittently lose connection to your database in normal operation. If the IIS process is going to start leaking then this is a problem.

Is there anyway to control this behaviour or handle being unable to connect to the SignalR backplane database?

**Comment by m-mccool** [comment]
Further investigation scenarios

**Scenario 1.** 
There have been no previous connection attempts made to the SignalR hub. If I take the signalR database off line and start the client, wait for the client to fail once, then stop it again. SignalR continuously attempts to install the database tables, when this fails it seems to leak memory. The memory leak is significant, the memory increases to 1GB within the hour

If I bring the signalR database back on line, the signalR can then create the tables and starts operating correctly. The memory does not increase once the database is back on line. However the memory leaked is never recovered

**Scenario 2.**
There have been no previous connection attempts made to the SignalR hub. Ensure the signalR database is available and start the client, wait for the client to connect successfully, then stop it again. I then take the SignalR database offline. Then SignalR continuously attempts to read from the database and fails. This still leaks memory but not as significantly. About 30K an hour.

If I bring the signalR database back on line, the signalR can then read from tables and starts operating correctly. The memory does not increase once the database is back on line. However the memory leaked is never recovered

**Comment by m-mccool** [comment]
Further investigation
I downloaded the SignalR code. It seems that the leak is happening when attempting to install the signalr sql tables (SQLMessageBus.Initialize()). However it doesn't event attempt to this because the call to SQLInstaller.IsSqlEditionSupported throws and exception because the database is not available. I cannot see what is leaking. If I comment out the contents of SQLMessageBus.Initialize there is no memory leak. I tried commenting code further down the call stack but I cannot seem to isolate what is causing the leak. I also tried to memory profile the app but with no success.

Any ideas?

**Comment by m-mccool** [comment]
Seems to be related to accessing the database. When I change the code to hard code true being returned from SQLInitiliase.ISqlEditionSupported this reduced the memory leak significantly. 

However when I keep connecting with this scenario the memory in the IIS app pool keeps increasing, although not as badly as before

**Comment by m-mccool** [comment]
I was hoping someone from the SignalR team could chip in with some suggestions or understanding of what is happening. It would be a great help as I am not an expert in the inner workings of SignalR

When I uncomment the code to let the database access run as normal, I noticed that every so often I would see an unhandled exception in the EventViewer on my PC. 

What seems to be happening is that when the database access to check the version of SQL Server or attempt to install the SIgnalR tables fails it sets the _error member variable in Microsoft.AspNet.SignalR.Infrastructure.Connection to be the SQLException received. 

When my client attempts to connects (call initiates at HubDispatcherMiddleware.Invoke()) SignalR tries to send a connection message, it seems that the if the _error member variable is set in Microsoft.AspNet.SignalR.Infrastructure.Connection , then the exception that it holds is then thrown. 

This is what is causing the unhandled exception within SignalR. I wonder if this is contributing to the memory leak.

I have changed the code to catch this error and run the following code, it seems to have reduced the memory used in the app pool. IT still rises but not at a fast rate. Could someone in the team have a look at this problem and let me know whether my local change is going to have some side effects?

```
var taskCompletionSource = new TaskCompletionSource<object>();
taskCompletionSource.TrySetResult(null);
return taskCompletionSource.Task;
```

**Comment by halter73** [comment]
Is there a problem when SQL server is up and correctly configured? What's wrong with restarting the SignalR server after SQL server is back up?

**Comment by m-mccool** [comment]
I'm not sure restarting the server is practical in a live deployment. 
I ran my server all day with my fix in it and the leak did not occur. So I'm assuming the leak is cause by the unhandled exception being propagated through the OWIN pipeline.
How should an error be returned in these cases? Is the problem that the exceptions thrown should be handled somewhere else, or is throwing the exceptions the wrong approach. If it is the wrong approach how it handled errors?

**Comment by halter73** [comment]
@m-mccool Can you collect a memory dump of your application after it's leaked a significant amount of memory?

You can then used Visual Studio Ultimate's [Debug Managed Memory feature.](https://devblogs.microsoft.com/devops/using-visual-studio-2013-to-diagnose-net-memory-issues-in-production/) to see what objects are leaking. Or, if you don't have a license for Visual Studio Ultimate, you can use WinDbg/SOS, and run [dumpheap -stat](https://blogs.msdn.microsoft.com/tess/2005/11/25/dumpheap-stat-explained-debugging-net-leaks/) to get the same info.

**Comment by m-mccool** [comment]
Here is the output of the WinDbg dumpheap of the memory leak when the SignalR backplane database cannot be reached
[SignalRSqlBackplaneDumpHeap.txt](https://github.com/SignalR/SignalR/files/2945535/SignalRSqlBackplaneDumpHeap.txt)

**Comment by halter73** [comment]
The SignalR types don't seem to be taking more than a few megabytes of heap space. The most allocated object by size is string, but even that only accounts from ~25MB. Have you ran !gcroot on any of the string objects?

**Comment by m-mccool** [comment]
Not yet.
I think the root of the problem is the unhandled exception, this is initiating the leak. From what you are saying the leak may not be in the SignalR, but I think it is causing it to happen further up the stack causing the application pool to leak.
