### ISSUE TITLE
SignalR 1.2.2 Persistence Connection Cross Domain Problem

### ISSUE THREAD

**Issue by akira32chen** [SignalR/SignalR#4315]
I meet two problem about cross domain problems. The errors as below in  chrome console: 

Failed to load resource: the server responded with a status of 403 (Forbidden: SignalR cross domain is disabled.) 

Access to XMLHttpRequest at 'http://localhost:6684/realtime/echo/negotiate?_=1551086197209' from origin 'http://localhost:3596' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. 

 I use SignalR 1.2.2 and my code as below: 

 Client Javascripts .netframework 4.5 

`connection = $.connection("http://localhost:6684/realtime/echo", '', false, { xdomain: true }); `

Server .netframework 4.0 

```
 public class Global : System.Web.HttpApplication 

 { 

  protected void Application_Start(object sender, EventArgs e) 

  { 

    //RouteTable.Routes.MapConnection<EchoConnection>("EchoConnection", "/realtime/echo"); 

   RouteTable.Routes.MapConnection<EchoConnection>("EchoConnection", "/realtime/echo", new ConnectionConfiguration { EnableCrossDomain = true }); 

  } 
```

 
How do I solve this cross problem during development in the sameple computer. I deploy the SignalR Server and SignalR Client Web to IIS and test them. I can use my ipad pro to connect to SignalR Server and communicate with json data. But I hope I can do it in my Visual Studio 2017. Does someobody have some ideas to solve this problem? 
 
I hope I can keep the SignalR 1.2.2 and use persistence connection. If I upgarde the SignalR version to newest, the code of c# or javascript will be modified?

**Comment by halter73** [comment]
https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-javascript-client#how-to-establish-a-cross-domain-connection
