### ISSUE TITLE
Sql backpane active connections.

### ISSUE THREAD

**Issue by xjpmauricio** [SignalR/SignalR#4316]
Is there a way to know the active connections on all servers of a farm, using sql backpane, sitting behind a load balancer.

**Comment by anurse** [comment]
SignalR provides Windows Performance Counters on each server that indicate the number of active connections. You can install the performance counters using the instructions [in our documentation](https://docs.microsoft.com/en-us/aspnet/signalr/overview/performance/signalr-performance#perfcounters) and then view them in the Windows "Performance Monitor" tool.

In a farm scenario, these counters only tell you the number of connections on each individual server. It's up to you to aggregate this data if you want to view the total connections across the entire farm.
