### ISSUE TITLE
SignalR client(js) connectionId is always 0, how to match client connectionId with server side connectionId?

### ISSUE THREAD

**Issue by handsomeyao77** [SignalR/SignalR#4318]
# Issues related to the Asp.NET Core version of SignalR should be filed in the corresponding SignalR repo: https://github.com/aspnet/?utf8=%E2%9C%93&query=Signalr

**Comment by halter73** [comment]
Can you provide the code you are using to read the connection id?

**Comment by handsomeyao77** [comment]
![image](https://user-images.githubusercontent.com/7311188/53383445-ac593480-39b2-11e9-89e9-8ba789332b42.png)

![image](https://user-images.githubusercontent.com/7311188/53383467-c0049b00-39b2-11e9-8fa4-81aefc39cbad.png)

Print connection object, the id is 2 now, confused...

**Comment by halter73** [comment]
This issue was moved to aspnet/AspNetCore#8108

**Comment by halter73** [comment]
Thanks for the report. This is the repo for the pre-ASP.NET Core version of SignalR. It looks like you're using the ASP.NET Core version though. I moved the issue to the current ASP.NET Core repo.
