### ISSUE TITLE
Link in the Wiki for documentation is possibly wrong

### ISSUE THREAD

**Issue by lstr168** [SignalR/SignalR#4325]
Hi I'm just starting to use SignalR and I've found that the Link in the Wiki might be wrong.

> Documentation is moving to http://www.asp.net/signalr

All links inside http://www.asp.net/signalr are refering to asp.net core / SignalR for asp.net core but this repository is for asp.net signalr.

### Expected  behavior
Link that goes to asp.net signalr docu
### Actual behavior
Link goes to asp.net core signalr docu
### Steps to reproduce
Go to https://github.com/SignalR/SignalR/wiki and click on the Link 
> Documentation is moving to http://www.asp.net/signalr

**Comment by bradygaster** [comment]
I have updated the Wiki page with links to both ASP.NET and ASP.NET Core SignalR. Thanks for the heads-up.
