### ISSUE TITLE
Make SignalR AMD Compliant

### ISSUE THREAD

**Issue by hamishcrittenden** [SignalR/SignalR#433]
To make SignalR AMD Compliant out of the box for integration into UI Frameworks using RequireJS

**Comment by amoerie** [comment]
For people who want to use this today, an AMD compatible signalR 2.2.0 is available on NPM at https://www.npmjs.com/package/signalr-amd

**Comment by Worthaboutapig** [comment]
Why was this closed?  It seems to be something else pretty important that's disappeared into nothingness.

**Comment by gregveres** [comment]
@amoerie any chance of getting that npm updated for 2.3.0? Thank you for putting that out BTW,  I have been using it for the last 6 months. 
This issue definitely shouldn't be closed. It seems like such a simple thing. I guess I am missing something

**Comment by amoerie** [comment]
@gregveres Afraid I can't, actually. That package was posted under the company NPM account and I no longer work at that company anymore. 

But looking at the latest SignalR documentation, aren't they webpack compatible nowadays? See https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-2.1&tabs=visual-studio
