### ISSUE TITLE
Transfer massive data Performance?

### ISSUE THREAD

**Issue by nkfeiyang** [SignalR/SignalR#4333]
When I want to transfer several hundred objects in a list from server to client, it seems take 30-60 seconds. Both serve and client are in same intranet. Is it normal?

### Expected  behavior
Transfer data should take a short time, we would like to just load like from a SQL server database.

### Actual behavior
Sending from serve to client with signalr takes much more time  than loading data directly from database.

**Comment by muratg** [comment]
What kind of objects are you sending? Size, complexity, etc?

Are these EF objects (or some other ORM?) with complex relationships?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
