### ISSUE TITLE
Windows Authentication & Anonymous authentication not working

### ISSUE THREAD

**Issue by lstr168** [SignalR/SignalR#4336]
Hi I'm using version 2.4.0 of signalr and I did not found a way to make windows authentication to work without to require the user being authenticated.

I have crated a CustomAutorizeAttribute to allow anonymous impersonation based on config.
And then using a webapi mehtod to send the ntlm chanlange and then catch error callback of the connection and trying to stop and start the connection on the clientside. The 403 error will occur multiple times and once the new connection is established the Context.User.Identity stays unauthenticated.

Altough when I add the line in Startup.Configuration it works but does not allow anonymous authentication anymore.

GlobalHost.HubPipeline.RequireAuthentication();

### Expected  behavior
User is authenticated after reconnection

### Actual behavior
User is not authenticated after reconnection

### Steps to reproduce
```
    public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            app.MapSignalR();
            //GlobalHost.HubPipeline.RequireAuthentication();
        }
    }
```
```
        public async Task<string> TryLogin()
        {
            return await Task.Run(() =>
            {
                string connectionID = Context.ConnectionId;

                if (Context.User?.Identity?.IsAuthenticated == true)
                {
                    return Context.User.Identity.Name;
                }
                return "";
            }
        }
```
```
           this.signalRConnection = $.hubConnection();
            this.hub = this.signalRConnection.createHubProxy("testHub");
            this.signalRConnection.start({ transport: 'longPolling', withCredentials: true }).then(() => {
                fetch("api/login").then(res => res.json() as Promise<boolean>).then((s: boolean) => {
                    if (s) {
                        this.hub.invoke("tryLogin", (name: string) => alert(name));
                    }
                });
            });
            this.signalRConnection.error((error) => {
                this.signalRConnection.stop();
                this.signalRConnection.start({ transport: 'longPolling', withCredentials: true }).then(onStarted);
            });
```

**Comment by lstr168** [comment]
![grafik](https://user-images.githubusercontent.com/16594967/54316021-fca1da80-45df-11e9-86db-dda6c5100b8b.png)
Also when I set allowAnoymous to false the client will never connect, am I missing somthing?

**Comment by halter73** [comment]
Can you give us a repro project in a github repository?

I'm suspicious about the Task.Run causing the HttpContext to disappear. Can you remove it?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
