### ISSUE TITLE
JS client receiving high frequency messages performance

### ISSUE THREAD

**Issue by AlexeyBudko** [SignalR/SignalR#4342]
I have IIS Web service, which hosting SignlaR hub. Hub sends to JS clients messages cyclically 20 times per second. For test purpose messages are empty JSON("{}"). Real data has approximately 1kb of data.

JS client doing nothing except just message receiving.

My PC: 16gb RAM, SSD, Intel i5-3470

PS. I've read SignalR performance guidelines. As advised there, my hub uses a singleton with data handler.

### Expected  behavior
I expect to see 0 percent of CPU usage of the client web browser.
### Actual behavior
CPU usage with empty messages is about 0.8%. With real data: 1.8%.
### Steps to reproduce
Create a hub and send messages to JS cyclically.

**Comment by anurse** [comment]
I'm trying to understand what your concern here is. There is indeed some CPU overhead in receiving, parsing, etc. messages. Why would you expect to see 0 CPU usage when the client is receiving messages?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
