### ISSUE TITLE
Is there any official Python signalr client library?

### ISSUE THREAD

**Issue by nkfeiyang** [SignalR/SignalR#4343]
Because my many clients use python, I use some python client signalr library, but those code are maintained by personal, and sometimes there are bugs or some features are not supported.

So if Microsoft team could publish this kind of python client library?

Thanks a lot.

**Comment by Rjtsahu** [comment]
No, there is no official client library for python.

**Comment by halter73** [comment]
Thanks for answering @Rjtsahu.
