### ISSUE TITLE
HubException in OnConnect becomes internal error to clients

### ISSUE THREAD

**Issue by larslarsson** [SignalR/SignalR#4346]
HubException thrown in OnConnect becomes internal error for client. Is this expected behavior? If it is where would you throttle client sessions or other sanity checks/limits releated to connectivity such that the client get a understandable message? Alt. use subscribe/unsubscribe to limit sessions but felt like OnConnect or something related would be more appropriate as protection of system/server resources.

Versions
``` 
<package id="Microsoft.Owin" version="4.0.0" targetFramework="net462" />
<package id="Microsoft.Owin.SelfHost" version="4.0.0" targetFramework="net462" />
<package id="Microsoft.AspNet.SignalR.Core" version="2.2.3" targetFramework="net462" />
<package id="Microsoft.AspNet.SignalR.SelfHost" version="2.2.3" targetFramework="net462" />
```

**Comment by halter73** [comment]
@larslarsson Is the issue that the exception message thrown from your Hub.OnConnected() override isn't included in the exception thrown from HubConnection.Start()? Would having your client app check a WebAPI endpoint for throttling/sanity-checks/limits prior to calling HubConnection.Start() be a reasonable work-around?

**Comment by larslarsson** [comment]
So my assumption was that hubexception would fall thru to the client just as a normal call, that is the bug report. If you have another way/recommended way to propagate an error with a readable message to the client in OnConnect? Using another technology and telling client to do stuff to retrive error message is not acceptable.

**Comment by BrennanConroy** [comment]
You could also send a message in OnConnect to a client method that handles the error as appropriate.
