### ISSUE TITLE
JS disconnected event not fired with Server Sent Events transport

### ISSUE THREAD

**Issue by alex-jitbit** [SignalR/SignalR#4349]
Since SignalR does not support HTTP/2  it falls back to "Server Sent Events" transport.

And the JS "diconnected" event is **not fired** when you're on this transport and the connection drops.

### Steps to reproduce

1. Connect to a server using serverSent.Events transport (AKA "any server that supports HTTP/2")
2. Set up a `$.connection.hub.disconnected` handler and put a breakpoint in there.
2. Open browser dev tools - Network - check "OFFLINE"
3. You can see SignalR actually trying to reconnect unsuccessfuly!
`https://server/signalr/ping?_=XXXXXXX net::ERR_INTERNET_DISCONNECTED`
3. The `disconnected` NEVER FIRES in JS.

Works fine on websockets.

**Comment by alex-jitbit** [comment]
Any reaction on this, team? If you're not willing to fix this in the near future, what would be the workaround?

**Comment by halter73** [comment]
`https://server/signalr/ping` These are not coming from the server-sent events transport. The transport may still think the connection is active. Eventually, I would expect a keep alive timeout to fire if the network was really down though. Do you have any [client-side traces](https://docs.microsoft.com/en-us/aspnet/signalr/overview/testing-and-debugging/enabling-signalr-tracing#enabling-tracing-in-the-javascript-client) from when this happens?

**Comment by alex-jitbit** [comment]
Ok, so it turns out there's a bug in Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=423246 the offline switch does not actually terminate the underlying connection
