### ISSUE TITLE
Bump the 2.4.1 C# and JS client's clientProtocol from 2.0 to 2.1

### ISSUE THREAD

**Issue by halter73** [SignalR/SignalR#4353]
This will allow the service to detect the patched client that will merge query strings.

It's important to verify that older servers (e.g. the 2.4.0 server) will not choke on the higher protocol version, but older servers should simply respond to a 2.1 clientProtocol with a 2.0 ProtocolVersion in the negotiate response. This means older servers should continue to behave as if the clientProtocol was 2.0 which should be fine.

**Comment by anurse** [comment]
This is fixed in version [2.4.1](https://github.com/SignalR/SignalR/releases/tag/2.4.1) which is now released to NuGet.org and NPM.
