### ISSUE TITLE
API/SignalR/Connect

### ISSUE THREAD

**Issue by chiranjeevi-puvvula-ascendlearning-com** [SignalR/SignalR#4354]
We are load testing our ASP.NET WEB API using Neoload and using new relic for monitoring. Seeing really high response times for API/SignalR/Connect.

Our app uses SQL server as the back plane(100 tables for scaling and Service broker is enabled).

Our application is run as a seperate instance on 8 servers and is load balanced.

### Expected  behavior
API/SignalR/Connect should not see high response times

### Actual behavior
API/SignalR/Connect is showing really high response times

### Steps to reproduce
Not able to reproduce since this only happens during load testing.

Looking at the trace of the call, majority of the time is spent on sql connection and basically stuck in a loop I think. Here is a screenshot of it

![image](https://user-images.githubusercontent.com/47794875/55429034-12a41a80-5550-11e9-8e3a-01ab26fe4708.png)

I want to understand when this call is actually made. My understanding is that it should only happen during the initialization of the connection.  But our monitoring found that this call is happening more frequently , here is the throughput of the call

![image](https://user-images.githubusercontent.com/47794875/55429150-657dd200-5550-11e9-8e13-b6df005b5a11.png)

We are testing the app for a load of 10,000 users.  Loading 100 users every minute.

why does the connect call stuck in a loop and opening a sql connection every 20-30 second. Refer to my first screenshot

@anurse , I tagged you to this post because I have seen in other posts that you provided some valuable information.

Your help is much appreciated

**Comment by anurse** [comment]
That's entirely expected. The `/signalr/connect`, `/signalr/reconnect` and `/signalr/poll` requests are the persistent connection itself, so these requests last for the entire duration of the connection *by design*.

As for the SQL connections, if your clients are triggering database activity by invoking Hub methods, that activity would show up as part of the `/signalr/connect` request.

**Comment by anurse** [comment]
In general, you should ignore these three endpoints (`connect`, `reconnect` and `poll`) when measuring response duration since they will completely throw off any reporting you're doing.

**Comment by chiranjeevi-puvvula-ascendlearning-com** [comment]
Thank you so much for your reply @anurse . What is the best way to monitor signalr ?

**Comment by anurse** [comment]
There are Windows Performance Counters which can be used to understand how connections are behaving in your system. See our [documentation](https://docs.microsoft.com/en-us/aspnet/signalr/overview/performance/signalr-performance#using-signalr-performance-counters) for more detail.
