### ISSUE TITLE
c# call to hub method hangs app

### ISSUE THREAD

**Issue by chartierpw** [SignalR/SignalR#4357]
I'm having a hang issue with Microsoft.AspNet.SignalR.Client v2.4,  I call a hub method from android client (Xamarin) and it hangs. Client code is:

    public List<string> ConnectedUsers()
    {
        // Hangs on this line
        List<string> Users = _proxy.Invoke<List<string>>("getConnectedUsers").Result;

        return Users;
    }

Hub method code is:

    public List<string> getConnectedUsers()
    {
        List<string> UserNames = new List<string>();

        foreach (var ConnectedUser in Users)
        {
            UserNames.Add(ConnectedUser.Name );
        }
        
       return UserNames;
    }

The call to the hub works with javascript, 
Clicking the get users button executes the following:

                $('#getusers').click
                (
                    function () 
                    {
                        chat.server.getConnectedUsers().done(function (result) {
                            alert(result);
                        });
                    }
                );

This call to the same hub works fine.

**Comment by chartierpw** [comment]
After reading this document (https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#avoid-using-taskresult-and-taskwait) provided by David Fowler at GitHub, I changed my code as follows:

 I changed my code in accordance with the information in the document and now it works as expected. For those researching the same issue, I changed my code to:

On the client:
From:

public List<string> ConnectedUsers()
{
    // Hangs on this line
    List<string> Users = _proxy.Invoke<List<string>>("getConnectedUsers").Result;

    return Users;
}

To:

    public async Task <List<string>> ConnectedUsers()
    {

        List<string> Users = await _proxy.Invoke<List<string>>("getConnectedUsers");

        return Users;
    }

The call to the ConnectedUsers function in Client.cs was changed as well:
From:

            List<string> userList = client.ConnectedUsers();

To:
            List<string> userList = await client.ConnectedUsers();

No changes to the hub code were necessary.

**Comment by halter73** [comment]
Perfect. You found the https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#avoid-using-taskresult-and-taskwait doc before I could link you to it. I'm glad you fixed the issue 😄
