### ISSUE TITLE
Hello,can i use it for real-time  web RPG Games?

### ISSUE THREAD

**Issue by 840900649** [SignalR/SignalR#4358]
Hello,can i use it for real-time  web RPG Games?

**Comment by halter73** [comment]
[This tutorial](https://docs.microsoft.com/en-us/aspnet/signalr/overview/getting-started/tutorial-high-frequency-realtime-with-signalr) on creating high-frequency real-time apps with SignalR demonstrates how to use SignalR to set up a simple game loop on your server and clients.
