### ISSUE TITLE
Update packages to use 'license' expression and 'iconFile'

### ISSUE THREAD

**Issue by anurse** [SignalR/SignalR#4360]
Our packages produce the following warning when pushed to NuGet.org:

```
WARNING: <licenseUrl> element will be deprecated,please consider switching to specifying the license in the package. Learn more: https://aka.ms/deprecateLicenseUrl.
```

We need to update before we ship the next version :).

**Comment by anurse** [comment]
Let's also update to embedded icons at the same time. ASP.NET Core is doing this, so @dougbu or @wtgodbe can probably help with how to do this (ASP.NET SignalR isn't using Arcade, but they'll probably know the NuGet incantations and we can hack that in to this legacy build system).

**Comment by wtgodbe** [comment]
For the embedded icons, you should be able to just add `<icon>` metadata to your .nuspec's (e.g. here: https://github.com/SignalR/SignalR/blob/61c1a688f6a4e714e43c5b82b10f6d8b7c612dd6/src/Microsoft.AspNet.SignalR/loc/Microsoft.AspNet.SignalR.satellite.nuspec#L10), by setting an `icon` property that points to a `.png`/.jpeg` checked into the repo, and passing it here: https://github.com/SignalR/SignalR/blob/e5f12b318491996eb6a09fc100df94d5453cfb37/build/loc/SatellitePackage.csproj#L18

Here's what we did in Blazor, as an example: https://github.com/aspnet/Blazor/pull/1897/files. Only the changes to the .csproj & the .nuspec are relevant (plus the checked-in image)

**Comment by dougbu** [comment]
@wtgodbe does your suggestion have an off-by-one error? And, don't the .nuspec files need both the `<icon>` element and a new `<file>` element for the icon in every TFM?

**Comment by halter73** [comment]
What's the best way to test metadata changes worked? Examining the nupkg with NuGet Package Explorer?

**Comment by wtgodbe** [comment]
> does your suggestion have an off-by-one error?

Do you mean in that I linked the `licenseUrl`? That was probably unclear - I just meant that the `icon` metadata should be included in a similar place.

> And, don't the .nuspec files need both the <icon> element and a new <file> element for the icon in every TFM?

Whoops, yes - you should also explicitly include the `icon` as a file in the .nuspec, like so: https://github.com/aspnet/Blazor/pull/1897/files#diff-dbaf4f8c863cf1321dcf8c9ddb59b4f1R12

> What's the best way to test metadata changes worked? Examining the nupkg with NuGet Package Explorer?

I imagine there's a Nuget.exe command to verify .nuspec's, but I'm not sure. I just manually verified that the locally built .nupkg's had the icon image included at the root, and the icon metadata in their .nuspec.

**Comment by BrennanConroy** [comment]
Couple things in case we look back at this:
1. licenseUrl is still used by dotnet/Runtime and dotnet/AspNetCore
2. Removing licenseUrl and using license instead while having requireLicenseAcceptance=true fails to pack with older nuget client due to a bug

**Comment by dougbu** [comment]
> licenseUrl is still used by dotnet/Runtime and dotnet/AspNetCore

**Only** in 2.1.x e.g. `<licenseUrl>https://raw.githubusercontent.com/aspnet/AspNetCore/2.0.0/LICENSE.txt</licenseUrl>` in Microsoft.AspNetCore.App.2.1.26.nupkg. 3.1 and later use license expressions e.g. `<license type="expression">Apache-2.0</license>` in microsoft.aspnetcore.app.ref.3.1.10.nupkg.

@BrennanConroy I suggest we follow up on #4533 with a switch to the recommended license expressions.

@Pilchie should we have a bug to fix the 2.1 license element in dotnet/aspnetcore❔

> `license` instead while having `requireLicenseAcceptance=true` fails to pack

How is this a concern❔ We have a much newer NuGet client and numerous packages with this combination are broadly used.

**Comment by BrennanConroy** [comment]
> How is this a concern

It's extra work in this repo that isn't really needed IMO.

> **Only** in 2.1.x

That's just not true, look at https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR.Client/6.0.0-preview.1.21103.6, it has licenseUrl set in the nuspec.

**Comment by dougbu** [comment]
> it has `licenseUrl` set in the nuspec

I'm confused; I see `<license type="expression">Apache-2.0</license>` there too

**Comment by dougbu** [comment]
OIC, the .nuspec files contain **both** forms. That's weird.
