### ISSUE TITLE
Upgrade from 2.0.3 to 2.4.1 

### ISSUE THREAD

**Issue by Khilborn** [SignalR/SignalR#4361]
I upgraded from 2.0.3 to 2.4.1 and now getting lots of warning and 1 error.

Error	eqeqeq	(ESLint) Expected '===' and instead saw '=='.

Its on line 257 inside the jquery.signalR-2.4.1.js file	

` if (typeof _pageWindow.on == "function") {`

I am getting lots of warning about the following

Warning	no-extra-parens (ESLint) Gratuitous parentheses around expression. This is throughout the jquery.signalR-2.4.1.js file

**Comment by halter73** [comment]
It looks like this regressed in [2.2.1]( https://github.com/SignalR/SignalR/commit/f8adbeba7fae4d48d7150e04b39ba6875f2a13ae). We'll have to look into adding ESLint to the build if we wind up fixing this and don't want to regress in future releases.

**Comment by Khilborn** [comment]
Anything I can do moving forward or should I just revert back to 2.0.3?

**Comment by halter73** [comment]
If 2.0.3 works for you, I don't see the harm in reverting.

That said, if you really need to run ESLint on jquery.signalR-2.4.1.js, you could just put [/* eslint-disable */](https://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments> at the top of your jquery.signalR-2.4.1.js file for now.
