### ISSUE TITLE
After send message to android client i received below error?

### ISSUE THREAD

**Issue by KooshkakiH** [SignalR/SignalR#4363]
HubConnection: HubConnection disconnected with an error Only the original thread that created a view hierarchy can touch its views.

**Comment by anurse** [comment]
HubConnection callbacks run in a thread-pool thread and most UI stacks require that you only modify UI element properties from the UI thread. Generally the UI framework will provide a way to get back to the UI thread. You'll need to do from your HubConnection callback.

Without more detail I can't really provide more specific advise. Can you post a sample project that reproduces the problem you are seeing? Which SignalR client package are you using? Are you using Xamarin or a native Android app?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!

**Comment by KooshkakiH** [comment]
Thanks, i solved this problem after one day of created this issue and you have big delay response.

**Comment by anurse** [comment]
Glad to hear you resolved the issue! Apologies for the delay, we've been clearing up the backlog to get back on track of things.
