### ISSUE TITLE
Latest Chrome will disable sync XHR calls in "beforeunload" please make according changes

### ISSUE THREAD

**Issue by alex-jitbit** [SignalR/SignalR#4365]
Please see this bug: https://bugs.chromium.org/p/chromium/issues/detail?id=952452

Chrome update 73.0.3683.103 has broken the "beforeunload" event - synchronous XHR requests are no longer allowed from within this event. The Chrome team has reverted the change after reports from many software companies (see the bug discussion)

But the Chrome team **will** bring this back in June 2019 (again. see the bug discussion).

As far as I know, SignalR relies on "beforeunload" event to notify the server about a disconnect. Please change that. One option would be to switch from an ajax-call to the `sendBeacon` API.

**Comment by alex-jitbit** [comment]
It finally broke with the new Chrome release like I said. Just proposed a PR that kinda fixes this (verified the fix locally and on server)

**Comment by CedricInfeeny** [comment]
Hello,
A date is announced for the next release?

Thank you.

**Comment by alex-jitbit** [comment]
Just a reminder that current version of Signalr does not work in Chrome currently.

1. I created this issue 12 months ago way ahead of the change.
2. Then I freaking fixed it myself (seeing the lack of action from MS)
3. You still can't release it.

**Comment by Jehoel** [comment]
@alex-jitbit SignalR (non-Core) seems to be working for me in Chorme 83 - can you be more specific? Does it not work at all, or just not work in `<iframe>` and/or not work when the `beforeunload` logic is used?

**Comment by EvgenyKhaliper** [comment]
@Jehoel  SignalR does not connect in Chrome when used inside of iframe.

Do you know how to overcome the issue or should we exclude SignalR from our product ?

**Comment by Jehoel** [comment]
@EvgenyKhaliper  Are you referring to the non-Core version of **SignalR** (for the .NET Framework 4) or are you referring to **SignalR Core**?

**Comment by EvgenyKhaliper** [comment]
@Jehoel My mistake i will fill new issue.

**Comment by halter73** [comment]
We should also look at https://github.com/SignalR/SignalR/issues/2517#issuecomment-783924313 before closing this.
