### ISSUE TITLE
Where can I find API documentation for SignalR's JavaScript API?

### ISSUE THREAD

**Issue by christopherliu** [SignalR/SignalR#4366]
This is the closest I was able to find: https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-javascript-client

I know for example $.connection.hub has an id property, but is there a comprehensive list?

**Comment by anurse** [comment]
I don't believe we have API reference docs for the ASP.NET SignalR JavaScript client. The link you provided is for ASP.NET **Core** SignalR, which is a separate product.

We have some API docs for the JavaScript client here, but they are not "reference-style" docs: https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-javascript-client

**Comment by christopherliu** [comment]
Sad to hear that, but thank you for clarifying.

**Comment by sergeykifyak** [comment]
@christopherliu: https://docs.microsoft.com/en-us/javascript/api/@microsoft/signalr/?view=signalr-js-latest

**Comment by JJAHMEDAMER** [comment]
https://learn.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-9.0&tabs=visual-studio

Getting started
