### ISSUE TITLE
Where is the source for 3.0.0?

### ISSUE THREAD

**Issue by staff0rd** [SignalR/SignalR#4368]
In 2015 there were packages labelled Microsoft.AspNet.SignalR.Server 3.0.0-* which were originally on nuget but then moved to myget.  They no longer seem to be on myget, notably, 3.0.0-rc1-final.

In the case that these packages are indeed no longer available, I'm wondering if the source still is?

I see aspnet/SignalR, but the [first commit](https://github.com/aspnet/SignalR/commit/03352354dc495e3714dbf1e6e738acf807cf4abc) was late 2016 and looks like a rewrite.

Any pointers on how to get either the package or source for Microsoft.AspNet.SignalR.Server 3.0.0-rc1-final would be much appreciated.

**Comment by anurse** [comment]
I believe you are looking for https://github.com/aspnet/SignalR-Server . This is where our initial prototypes of a port of ASP.NET SignalR to ASP.NET Core were done.

The usual disclaimer for this stuff applies: These were prototypes and are not supported in any way. The code is open-source and you're welcome to do what you want with it (as per the terms of the [license](https://github.com/aspnet/SignalR-Server/blob/dev/LICENSE.txt)) but there are no plans to ship this code as supported or fix bugs in it.

**Comment by BrennanConroy** [comment]
That's not a public repo anymore. No one should ever be using it...

**Comment by anurse** [comment]
Ah yeah, we did remove it completely. The prototype has long been abandoned and would basically need to be re-written from scratch to work. Perhaps we could get a better idea of why you need this package?

**Comment by staff0rd** [comment]
I have an application I wrote based on dotnetcore rc1-final that heavily relies on that package.  Although I haven’t used/built the app in 3 years I was hoping to demo its functionality in a talk I’m about to do without needing to rewrite the app to asp.net core SignalR.  I’d be happy with even a compiled binary...

**Comment by anurse** [comment]
Unfortunately we no longer provide those prototype packages for download, since they were just prototype content that was superceded by the official ASP.NET Core SignalR product.

**Comment by staff0rd** [comment]
Completely understand - just querying if I can get either temporary access or a copy of the repo so I can run a demo of my application that depends on it?
