### ISSUE TITLE
WebSocketException exception thrown after Closed Event

### ISSUE THREAD

**Issue by ThomasHuckle** [SignalR/SignalR#4369]
When using a hubConnection to call InvokeAsync, unexpected behavior takes place when that task fails due to a connection interruption. The exception that is thrown from the failed InvokeAsync call is caught and handled. 
From my understanding, as the connection was lost the Closed Event on the HubConnection is fired and the hubconnection itself is either terminated or closed. No other attempts at reconnecting to the hub or to send any more messages are made. Yet, after a seemingly random period of time, under 3-5 minutes, an exception of type "System.Net.WebSockets.WebSocketException" is thrown and not handled anywhere, ultimately causing the application to fail.

Why is this exception being thrown if the exception from the failed invokeAsync call is handled?
Is the connection actually being shut down by the .Closed event or is there a bug present? 

This problem still occurs when manually calling hubConnection.DisposeAsync() or hubConnection.StopAsync()

windows server 2016
IIS version: 10.0.14383.0

**Comment by anurse** [comment]
Your reference to `DisposeAsync`/`StopAsync` makes me think you're referring to ASP.NET **Core** SignalR, is that correct? This repo is just for ASP.NET SignalR. I'd suggest filing this issue, with a runnable sample project attached, in the https://github.com/aspnet/AspNetCore repo if I'm correct.

If not, and you are in fact using ASP.NET SignalR (for .NET Framework/ASP.NET 4.x), let me know and we can reopen.
