### ISSUE TITLE
[Suggestion] ASP.NET Core API With SignalR

### ISSUE THREAD

**Issue by Amine-Smahi** [SignalR/SignalR#4370]
It would be nice to see tutorials that uses ASP.NET Core webapi and EntityframeworkCore with SignalR apart from chat tutorial over and over.
Or realtime push notifications.

**Comment by anurse** [comment]
We're not producing new samples for ASP.NET SignalR. If you're looking for samples using ASP.NET **Core** SignalR, I'd suggest filing this issue in http://github.com/aspnet/AspNetCore.Docs . This repo is for the ASP.NET 4.x version of SignalR (not ASP.NET Core).
