### ISSUE TITLE
signal.min.js.map is not found in Safari

### ISSUE THREAD

**Issue by Nagavijay-kolla** [SignalR/SignalR#4375]
Hi

I am facing an issue in safari that is signal.min.js.map is not found

This is happening only in safari, in all other browsers it is working fine.

We are using signalr V1.0.3. 

Please help me to resolve this issue

Thanks in advance.

**Comment by anurse** [comment]
Can you access the file if you enter the URL for it directly?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
