### ISSUE TITLE
[Request] Opposite callback for `connectionSlow`

### ISSUE THREAD

**Issue by MaKCbIMKo** [SignalR/SignalR#4381]
Currently I can notify user about slow connection. Connection speed can be restored eventually, but there is no way to notify user about that.

For instance, I displaying some message/icon when connection is slow, but there is no way to remove this message/icon once connection speed is fine.

I was thinking about possible options here:
1. Introduce another callback for `connectionFastAgain` (with some proper name)
2. change `connectionSlow` callback to pass a parameter (e.g. true/false) to specify current connection speed status.

### Expected  behavior
Having another callback to notify user that connection speed is fine again.

### Actual behavior
There is no way to provide a callback to opposite event to `connectionSlow`

**Comment by anurse** [comment]
We have no plans to add new functionality like this to ASP.NET SignalR.
