### ISSUE TITLE
Server keeps sending ping messages to client after IIS site is stopped.

### ISSUE THREAD

**Issue by sherif-elmetainy** [SignalR/SignalR#4382]
I have .NET Framework 4.7.2 Server application using a SignalR 2.4.1 hosted on IIS on Windows Server 2019. The IIS Server is hosting multiple websites not related to the APP, using the same SSL Port (443) and SNI.

The client is a console application running .NET Framework 4.7.2 and SignalR client version 2.4.1.

When I stop the website in IIS without recycling/stopping the AppPool, the client (which has tracing enabled) keeps logging that it receives messages from the server while the IIS Site is stopped.

### Expected  behavior
The websocket should be closed and the server should stop sending ping messages to the client, and the client should detect that the connection is lost.

### Actual behavior
The server keeps sending messages to the client, and the client does not detect a disconnect until the AppPool is recycled.

Upon starting the website again, the old connection is kept alive, and all events sent by the server are not received by the client since the client is connected to the instance linked to the old app domain, and new events are triggered from the new app domain. 

This can only be fixed by either restarting the client so that it establishes connection to the new app domain, or recycling the app pool, so that a disconnect event is triggered on the client and the client would attempt to reconnect.

### Steps to reproduce
- Create a SignalR server app and host it on IIS
- Create a console SignalR client with tracing enabled and trace messages being written to console.
- Start the client app while the IIS Site is started.
- Stop the IIS Site
- Note that the client continues to receive messages while the site is stopped (example below)
```
18:23:37.7453778 - c524ec02-4c1f-4c8e-a122-a921bd4f32f5 - WS: OnMessage({})
18:23:47.7465685 - c524ec02-4c1f-4c8e-a122-a921bd4f32f5 - WS: OnMessage({})
18:23:57.7607119 - c524ec02-4c1f-4c8e-a122-a921bd4f32f5 - WS: OnMessage({})
```

I believe #3916 is related to this bug, however it was closed as a part of a cleanup and I cannot re-open it, hence the new issue.

**Comment by anurse** [comment]
It seems like an ASP.NET app doesn't get terminated when you stop it in IIS. Instead, stopping a site just stops new requests from being sent to it. There may be options to flow this data forward but I don't expect this to be something we can get to in a 2.4.x patch release.

**Comment by anurse** [comment]
Closing, as we don't expect to add a first-class feature here. It's possible to use events on [`HttpApplication`](https://docs.microsoft.com/en-us/dotnet/api/system.web.httpapplication?view=netframework-4.8) (via Global.asax) to run code when IIS stops the app and forcibly disconnect the clients.

IIS *should* time out long-running requests during a restart eventually. If that's not happening, there may be an issue in the IIS config.
