### ISSUE TITLE
How to retrieve multiple parameters

### ISSUE THREAD

**Issue by crud-boy** [SignalR/SignalR#4383]
```c#
 lotteryGameHub.On<int, string, long, long, long, string, bool, int, string, long, long>("getIssueInfo", 
                (lotteryGameId, currentSerialNumber, currentStartTime, currentCloseTime, syncTime, lastSerialNumber, 
                isUpdate, UpdateGameId, nextSerialNumber, nextStartTime, nextCloseTime) =>
                {
                    Console.Write(currentSerialNumber)
                });
```
I am calling an interface that returns 11 parameters, but only 7 parameters can be entered here.

**Comment by BrennanConroy** [comment]
We only provide helper methods that support up to 7 arguments and we wont be adding anymore. However, you can probably provide your own helper and copy what the 7 argument overload does.

See link for help.
https://github.com/SignalR/SignalR/blob/3c07d7bebc15ec9cbf6ac9d7339b5d2d54f6fab3/src/Microsoft.AspNet.SignalR.Client/HubProxyExtensions.cs#L345
