### ISSUE TITLE
solving CORS policy error using js client , or nodejs client withouth browser 

### ISSUE THREAD

**Issue by Hretic** [SignalR/SignalR#4384]
i know there has been lots of question about this already , but all of the answers seems to point out to a asp/c# solution 

I'm a php/nodejs developer and have no knowledge of c# /asp, trying to talk to signalR API for the first time ... i dont own the api and dont have access to its code 

here is my code

```

    <script src="jquery.js" type="text/javascript"></script>
    <script src="jquery.signalr-2.2.2.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(function () {
    
            $.connection('https://firouzex.exphoenixtrade.com/realtime').start()
                .done(function(){
                     console.log('connection done!')
                })
                .fail(function(){
                    console.log('error!');
                });
    
            
         });
    </script>

```
but  i got 

>     Access to XMLHttpRequest at 'https://firouzex.exphoenixtrade.com/realtime/negotiate?clientProtocol=1.5&_=1560862133617' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

i also tried JSONP but i got

> Failed to load resource: the server responded with a status of 403 (Forbidden: JSONP is disabled.)

is there anyway to solve this in the client side without making change to server code ?
if not is there a nodejs client that doesn't require browser to run this code so i can get rid of browser ?  (i've already looked into npm there's 1 but it cant work with https )

**Comment by anurse** [comment]
If the server does not support JSONP, they have to allow your application to access the API via CORS. Is this API an official published API from this provider? Usually, if they provide an official API, they will have a mechanism to register your application.

There is no official NodeJS client for ASP.NET SignalR. There are unofficial ones, but are not supported by this team.

**Comment by Hretic** [comment]
thanx , it seems the problem is not at my end
