### ISSUE TITLE
Replace JS .bind()/.unbind() with .on()/.off()

### ISSUE THREAD

**Issue by thedutchess** [SignalR/SignalR#4385]
Please replace the deprecated .bind/.unbind functions with .on/.off to make it compatible with jQuery 1.7.2+/3.0.0+. A [pull request](https://github.com/SignalR/SignalR/pull/3983) was raised for this by @PaulGiletich 2 years ago.

**Comment by anurse** [comment]
We can't update dependency versions in a minor release as it is a breaking change and we have no current plans to release another major version. Are these functions available in the current version (1.6.4)? If so, we could consider a change to simply move to these methods without updating the dependency version.

**Comment by thedutchess** [comment]
No, the .on() and .off() functions were introduced in 1.7, which was released in November 2011, two months after 1.6.4. It seems odd to me that you still rely on a nearly 8 year old library for core functionality with no further updates, especially since ASP.NET Core could still be considered not mature enough for production. We (my team) are only just moving to MVC5 from VB.NET WebForms, but even in the old solution SignalR was, and still is, the only package that requires a jQuery version as old as 1.6.4.

I understand it's a breaking change, but we are simply not ready to move straight onto .NET Core to get the latest major SignalR version. We do however want to be able to use jQuery 3 in our MVC project. Please consider releasing a non-Core major version that's compatible with the latest version of jQuery, to allow for use in modern web applications.

This is from the [jQuery migrate documentation](https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-jqueryfnbind-is-deprecated):

JQMIGRATE: jQuery.fn.bind() is deprecated
JQMIGRATE: jQuery.fn.unbind() is deprecated
JQMIGRATE: jQuery.fn.delegate() is deprecated
JQMIGRATE: jQuery.fn.undelegate() is deprecated

Cause: These event binding methods have been deprecated in favor of the .on() and .off() methods which can handle both delegated and direct event binding. Although the older methods are still present in jQuery 3.0, they may be removed as early as the next major-version update.

Solution: Change the method call to use .on() or .off(), the documentation for the old methods include specific instructions. In general, the .bind() and .unbind() methods can be renamed directly to .on() and .off() respectively since the argument orders are identical.

**Comment by miksh7** [comment]
It's already fixed, please make a release 2.4.2!

**Comment by halter73** [comment]
We are not going to upgrade our jQuery dependency in a patch because that would be a breaking change as noted in https://github.com/SignalR/SignalR/pull/3983.
