### ISSUE TITLE
off() called with a non-null callback will never remove the registration from the list or delete the callbackMap

### ISSUE THREAD

**Issue by Mythagoz** [SignalR/SignalR#4386]
### Expected  behavior
Calling .off() with a non-null callback should that callback registration from the list and delete the callbackMap is that registration was the last remaining registration.

### Actual behavior
In `.off()`, the callback index to remove, `callbackIndex`, is determined in the following loop that will leave `i` at `callbackSpace.length`:
```javascript
for (var i = 0; i < callbackSpace.length; i++) {
    if (callbackSpace[i].guid === callbackIdentity._signalRGuid) {
        callbackIndex = i;
        callbackRegistration = callbackSpace[i];
    }
}
```

When it comes time to splice the array, `i` is used instead of callbackIndex.  As `i` is `callbackSpace.length`, it has no effect on the array:
```javascript
// Remove the registration from the list
callbackSpace.splice(i, 1);
```

`callbackMap` will never be deleted as the code checks for `callbackSpace.length` to be changed to 0:
```javascript
// Check if there are any registrations left, if not we need to destroy it.
if (callbackSpace.length === 0) {
    delete callbackMap[eventName];
} 
```
This can result in memory leaks in code that depends on `callbackMap` being cleaned up.

### Steps to reproduce
Call .off() with a non-null callback

**Comment by nikitaky16** [comment]
Сonfirm that, I encountered the same problem.

**Comment by BrennanConroy** [comment]
Fixed via https://github.com/SignalR/SignalR/pull/4659
