### ISSUE TITLE
OnDisconnected Can't Work

### ISSUE THREAD

**Issue by 99784589** [SignalR/SignalR#4388]
1. Version 2.4.0 and 2.4.1 when client cross nginx to internet to server , when Browser close, func OnDisconnected Doesn't Work.But,Version 2.2.2 ,in the some condition,OnDisconnected is Work well.
2. Version 2.2.2 ,Vivaldi Browser close,, func OnDisconnected Doesn't Work.

**Comment by anurse** [comment]
Can you provide a runnable sample that reproduces the problem? In general, `OnDisconnected` is not guaranteed to be reliable. It is possible for it to fire multiple times (in a multi-server scenario) or not at all (if the client times out).

**Comment by vkuba** [comment]
Hi anurse, 
If `OnDisconnected ` isn't reliable what about `OnConnect`?  I am trying to store connection Id with a group in the concurrency dictionary but when I try to debug this OnConnect isn't called each time and OnDisconnected is called randomly multiple time. I use SignalR Azure service with regular asp .net MVC.

**Comment by anurse** [comment]
I'd expect `OnConnect` to be reliable here. Can you provide a runnable sample that reproduces the problem?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!

**Comment by vkuba** [comment]
The issue was correlated with multiple instances of the same hub with different interfaces.
https://github.com/Azure/azure-signalr/issues/581
