### ISSUE TITLE
ConnectionState.getNextInvocationId() Null pointer exception

### ISSUE THREAD

**Issue by mashahbazi** [SignalR/SignalR#4391]
After I figured the error #6898 and as said it's error fixed in 3.0.0-preview3. but now is start to send NullPointerException on invoke
`Attempt to invoke virtual method 'java.lang.String com.microsoft.signalr.HubConnection$ConnectionState.getNextInvocationId()' on a null object reference`
I check hubConnectionState to be HubConnectionState.CONNECTED before calling method invoke.

**Comment by anurse** [comment]
This repository is for ASP.NET SignalR (NuGet packages like `Microsoft.AspNet.SignalR`) and **not** ASP.NET Core SignalR. Please check https://github.com/aspnet/AspNetCore for this issue and file a new one there if necessary.
