### ISSUE TITLE
Perfmon counters showing zero

### ISSUE THREAD

**Issue by gavin2n** [SignalR/SignalR#4394]
### Expected  behavior

Perfmon counters after an app pool recycle, to show real numbers

### Actual behavior

all perfmon counters currently read zero.

### Steps to reproduce

have signalr 1.2.2 running on windows 2016 in IIS

Installed signalr perfmon utill version 1.2.2

waited for the nightly app pool recycle.

**Comment by gavin2n** [comment]
![image](https://user-images.githubusercontent.com/7013818/61457733-e37bb280-a960-11e9-930b-a0e6f4e623f1.png)

tried again with the latest version of the signalr utils package (2.4.1)

**Comment by anurse** [comment]
> tried again with the latest version of the signalr utils package (2.4.1)

Did you also update your application to 2.4.1 or is the application still running 1.x? SignalR 1.x was [retired as of July 1st, 2019](https://dotnet.microsoft.com/platform/support/policy/aspnet). If you are still able to reproduce the issue on the latest 2.x versions (both with the app **and** the utils package updated) we can investigate further.

**Comment by gavin2n** [comment]
Ironically we wanted the perfmon counters to help track down a bug in our app using 1.2.2, without needing to upgrade to 2.4.1 yet. 

I'll close this ticket and focus on getting upgraded to 2.4.1 hopefully that will solve our issues.

**Comment by anurse** [comment]
Please feel free to open a new ticket (and tag me in it for extra visibility) if you still see an issue with 2.4.1!
