### ISSUE TITLE
Hangs on production environment when using SignalR scale out (based on redis)  

### ISSUE THREAD

**Issue by nissims** [SignalR/SignalR#4396]
### Actual behavior
Hi,
Lately i have been dealing with a major slowdown while using SignalR scaleout based on redis on the production servers. 
in order to troubleshoot the server slow down several dump file has been collected while facing the issue. 
analyzing the dump point to a hang in the Send function 

!syncblk
Index         SyncBlock MonitorHeld Recursion Owning Thread Info          SyncBlock Owner
   73 063cd5a4          683         1 063d4558 1450  23   0a8007ec System.Object --> ~342 threads are waiting on 0a8007ec that owns by thread 23 

OS Thread Id: 0x4e84 (265) (blocked thread from the ~342 threads) 
System.Threading.Monitor.ReliableEnter(System.Object, Boolean ByRef)
Microsoft.AspNet.SignalR.Messaging.ScaleoutStream.Send(System.Func`2, System.Object)
Microsoft.AspNet.SignalR.Messaging.ScaleoutStreamManager.Send(Int32, System.Collections.Generic.IList`1)
Microsoft.AspNet.SignalR.Messaging.ScaleoutMessageBus.Send(System.Collections.Generic.IList`1)
Microsoft.AspNet.SignalR.Messaging.ScaleoutMessageBus.Publish(Microsoft.AspNet.SignalR.Messaging.Message)
Microsoft.AspNet.SignalR.Infrastructure.Connection.Send(Microsoft.AspNet.SignalR.ConnectionMessage)
Microsoft.AspNet.SignalR.Hubs.HubDispatcher.Outgoing(Microsoft.AspNet.SignalR.Hubs.IHubOutgoingInvokerContext)
Microsoft.AspNet.SignalR.Hubs.HubPipelineModule+c__DisplayClass6_0.b__0(Microsoft.AspNet.SignalR.Hubs.IHubOutgoingInvokerContext)
Microsoft.AspNet.SignalR.Hubs.HubPipeline.Send(Microsoft.AspNet.SignalR.Hubs.IHubOutgoingInvokerContext)
Microsoft.AspNet.SignalR.Hubs.ClientProxy.Invoke(System.String, System.Object[])
Microsoft.AspNet.SignalR.Hubs.ClientProxy.TryInvokeMember(System.Dynamic.InvokeMemberBinder, System.Object[], System.Object ByRef)
DynamicClass.CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object, Mobile.DataModel.Notifications.NotificationMessageGroup)
Mobile.NotificationService.Controllers.NotificationController+c__DisplayClass15_1.b__2()
System.Threading.Tasks.Task.InnerInvoke()
System.Threading.Tasks.Task.Execute() 

OS Thread Id: 0x1450 (23) (the thread that own the lock!!!!) 
System.Threading.Monitor.ObjWait(Boolean, Int32, System.Object)
System.Threading.Monitor.Wait(System.Object, Int32, Boolean)
System.Threading.Monitor.Wait(System.Object, Int32)
System.Threading.ManualResetEventSlim.Wait(Int32, System.Threading.CancellationToken)
System.Threading.Tasks.Task.SpinThenBlockingWait(Int32, System.Threading.CancellationToken)
System.Threading.Tasks.Task.InternalWait(Int32, System.Threading.CancellationToken)
System.Threading.Tasks.Task.Wait(Int32, System.Threading.CancellationToken)
Microsoft.AspNet.SignalR.Messaging.ScaleoutStream.Send(System.Func`2, System.Object)
Microsoft.AspNet.SignalR.Messaging.ScaleoutStreamManager.Send(Int32, System.Collections.Generic.IList`1)
Microsoft.AspNet.SignalR.Messaging.ScaleoutMessageBus.Send(System.Collections.Generic.IList`1)
Microsoft.AspNet.SignalR.Messaging.ScaleoutMessageBus.Publish(Microsoft.AspNet.SignalR.Messaging.Message)
Microsoft.AspNet.SignalR.Infrastructure.Connection.MultiSend(System.Collections.Generic.IList`1, System.Object, System.Collections.Generic.IList`1)
Microsoft.AspNet.SignalR.Infrastructure.Connection.Send(Microsoft.AspNet.SignalR.ConnectionMessage)
Microsoft.AspNet.SignalR.Hubs.HubDispatcher.Outgoing(Microsoft.AspNet.SignalR.Hubs.IHubOutgoingInvokerContext)
Microsoft.AspNet.SignalR.Hubs.HubPipelineModule+c__DisplayClass6_0.b__0(Microsoft.AspNet.SignalR.Hubs.IHubOutgoingInvokerContext)
Microsoft.AspNet.SignalR.Hubs.HubPipeline.Send(Microsoft.AspNet.SignalR.Hubs.IHubOutgoingInvokerContext)
Microsoft.AspNet.SignalR.Hubs.MultipleSignalProxy.Invoke(System.String, System.Object[])
Microsoft.AspNet.SignalR.Hubs.MultipleSignalProxy.TryInvokeMember(System.Dynamic.InvokeMemberBinder, System.Object[], System.Object ByRef)
DynamicClass.CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object, Mobile.DataModel.Notifications.NotificationMessageGroup)
Mobile.NotificationService.Controllers.NotificationController+c__DisplayClass15_1.b__0()
System.Threading.Tasks.Task.InnerInvoke()
System.Threading.Tasks.Task.Execute()
System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)

reviewing the source code 

 public Task Send(Func<object, Task> send, object state)
        {
            lock (_lockObj) <-- ~342 threads are waiting 
            {
                if (_error != null)
                {
                    _error.Throw();
                }

                // If the queue is closed then stop sending
                if (_state == StreamState.Closed)
                {
                    throw new InvalidOperationException(Resources.Error_StreamClosed);
                }

                var context = new SendContext(this, send, state);

                if (_initializeDrainTask != null && !_initializeDrainTask.IsCompleted)
                {
                    // Wait on the draining of the queue before proceeding with the send
                    // NOTE: Calling .Wait() here is safe because the task wasn't created on an ASP.NET request thread
                    //       and thus has no captured sync context
                    _initializeDrainTask.Wait(); <-- thread 23 (own the lock) wait 
                }

                if (UsingTaskQueue)
                {
                    Task task = _queue.Enqueue(Send, context);

                    if (task == null)
                    {
                        // The task is null if the queue is full
                        throw new InvalidOperationException(Resources.Error_TaskQueueFull);
                    }

                    // Always observe the task in case the user doesn't handle it
                    return task.Catch(_trace);
                }

                return Send(context);
            } 
        }

I am using the latest public version
204d0000 20528000   Microsoft_AspNet_SignalR_Core   (pdb symbols)          c:\symbols\public\Microsoft.AspNet.SignalR.Core.pdb\8D52D3ECE71546F2B71ECB44073BA5611\Microsoft.AspNet.SignalR.Core.pdb
    Loaded symbol image file: Microsoft.AspNet.SignalR.Core.dll
    Image path: Microsoft.AspNet.SignalR.Core.dll
    Image name: Microsoft.AspNet.SignalR.Core.dll
    Browse all global symbols  functions  data
    Using CLR debugging support for all symbols
    Has CLR image header, track-debug-data flag not set
    Image was built with /Brepro flag.
    Timestamp:        A96C7AE1 (This is a reproducible build file hash, not a timestamp)
    CheckSum:         0005C2B7
    ImageSize:        00058000
    File version:     2.4.1.19093
    Product version:  2.4.1.0
    File flags:       0 (Mask 3F)
    File OS:          4 Unknown Win32
    File type:        2.0 Dll
    File date:        00000000.00000000
    Translations:     0000.04b0
    Information from resource tables:
        CompanyName:      Microsoft
        ProductName:      Microsoft ASP.NET SignalR
        InternalName:     Microsoft.AspNet.SignalR.Core.dll
        OriginalFilename: Microsoft.AspNet.SignalR.Core.dll
        ProductVersion:   2.4.1-rtm-20190403-01
        FileVersion:      2.4.1.19093
        FileDescription:  Microsoft.AspNet.SignalR.Core
        LegalCopyright:   © Microsoft Corporation. All rights reserved.
        Comments:         Async signaling library for .NET to help build real-time, multi-user interactive web applications.

**Questions:** 
1.what does the _initializeDrainTask is responsible for 
2.what was the intent behind the QueuingBehavior (seems there is no documentation for that) 
3.changing the   QueuingBehavior to (always) will prevent the code from waiting how does it effec the behavior from a scale out perspective 

Thanks

**Comment by nissims** [comment]
Hi,
Lately i have been dealing with a major slowdown while using SignalR scaleout based on redis on the production servers. 
in order to troubleshoot the server slow down several dump file has been collected while facing the issue. 
analyzing the dump point to a hang in the Send function 

!syncblk
Index         SyncBlock MonitorHeld Recursion Owning Thread Info          SyncBlock Owner
   73 063cd5a4          683         1 063d4558 1450  23   0a8007ec System.Object --> ~342 threads are waiting on 0a8007ec that owns by thread 23 

OS Thread Id: 0x4e84 (265) (blocked thread from the ~342 threads) 
System.Threading.Monitor.ReliableEnter(System.Object, Boolean ByRef)
Microsoft.AspNet.SignalR.Messaging.ScaleoutStream.Send(System.Func`2, System.Object)
Microsoft.AspNet.SignalR.Messaging.ScaleoutStreamManager.Send(Int32, System.Collections.Generic.IList`1)
Microsoft.AspNet.SignalR.Messaging.ScaleoutMessageBus.Send(System.Collections.Generic.IList`1)
Microsoft.AspNet.SignalR.Messaging.ScaleoutMessageBus.Publish(Microsoft.AspNet.SignalR.Messaging.Message)
Microsoft.AspNet.SignalR.Infrastructure.Connection.Send(Microsoft.AspNet.SignalR.ConnectionMessage)
Microsoft.AspNet.SignalR.Hubs.HubDispatcher.Outgoing(Microsoft.AspNet.SignalR.Hubs.IHubOutgoingInvokerContext)
Microsoft.AspNet.SignalR.Hubs.HubPipelineModule+c__DisplayClass6_0.b__0(Microsoft.AspNet.SignalR.Hubs.IHubOutgoingInvokerContext)
Microsoft.AspNet.SignalR.Hubs.HubPipeline.Send(Microsoft.AspNet.SignalR.Hubs.IHubOutgoingInvokerContext)
Microsoft.AspNet.SignalR.Hubs.ClientProxy.Invoke(System.String, System.Object[])
Microsoft.AspNet.SignalR.Hubs.ClientProxy.TryInvokeMember(System.Dynamic.InvokeMemberBinder, System.Object[], System.Object ByRef)
DynamicClass.CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object, Mobile.DataModel.Notifications.NotificationMessageGroup)
Mobile.NotificationService.Controllers.NotificationController+c__DisplayClass15_1.b__2()
System.Threading.Tasks.Task.InnerInvoke()
System.Threading.Tasks.Task.Execute() 


OS Thread Id: 0x1450 (23) (the thread that own the lock!!!!) 
System.Threading.Monitor.ObjWait(Boolean, Int32, System.Object)
System.Threading.Monitor.Wait(System.Object, Int32, Boolean)
System.Threading.Monitor.Wait(System.Object, Int32)
System.Threading.ManualResetEventSlim.Wait(Int32, System.Threading.CancellationToken)
System.Threading.Tasks.Task.SpinThenBlockingWait(Int32, System.Threading.CancellationToken)
System.Threading.Tasks.Task.InternalWait(Int32, System.Threading.CancellationToken)
System.Threading.Tasks.Task.Wait(Int32, System.Threading.CancellationToken)
Microsoft.AspNet.SignalR.Messaging.ScaleoutStream.Send(System.Func`2, System.Object)
Microsoft.AspNet.SignalR.Messaging.ScaleoutStreamManager.Send(Int32, System.Collections.Generic.IList`1)
Microsoft.AspNet.SignalR.Messaging.ScaleoutMessageBus.Send(System.Collections.Generic.IList`1)
Microsoft.AspNet.SignalR.Messaging.ScaleoutMessageBus.Publish(Microsoft.AspNet.SignalR.Messaging.Message)
Microsoft.AspNet.SignalR.Infrastructure.Connection.MultiSend(System.Collections.Generic.IList`1, System.Object, System.Collections.Generic.IList`1)
Microsoft.AspNet.SignalR.Infrastructure.Connection.Send(Microsoft.AspNet.SignalR.ConnectionMessage)
Microsoft.AspNet.SignalR.Hubs.HubDispatcher.Outgoing(Microsoft.AspNet.SignalR.Hubs.IHubOutgoingInvokerContext)
Microsoft.AspNet.SignalR.Hubs.HubPipelineModule+c__DisplayClass6_0.b__0(Microsoft.AspNet.SignalR.Hubs.IHubOutgoingInvokerContext)
Microsoft.AspNet.SignalR.Hubs.HubPipeline.Send(Microsoft.AspNet.SignalR.Hubs.IHubOutgoingInvokerContext)
Microsoft.AspNet.SignalR.Hubs.MultipleSignalProxy.Invoke(System.String, System.Object[])
Microsoft.AspNet.SignalR.Hubs.MultipleSignalProxy.TryInvokeMember(System.Dynamic.InvokeMemberBinder, System.Object[], System.Object ByRef)
DynamicClass.CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object, Mobile.DataModel.Notifications.NotificationMessageGroup)
Mobile.NotificationService.Controllers.NotificationController+c__DisplayClass15_1.b__0()
System.Threading.Tasks.Task.InnerInvoke()
System.Threading.Tasks.Task.Execute()
System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)

reviewing the source code 

 public Task Send(Func<object, Task> send, object state)
        {
            lock (_lockObj) <-- ~342 threads are waiting 
            {
                if (_error != null)
                {
                    _error.Throw();
                }

                // If the queue is closed then stop sending
                if (_state == StreamState.Closed)
                {
                    throw new InvalidOperationException(Resources.Error_StreamClosed);
                }

                var context = new SendContext(this, send, state);

                if (_initializeDrainTask != null && !_initializeDrainTask.IsCompleted)
                {
                    // Wait on the draining of the queue before proceeding with the send
                    // NOTE: Calling .Wait() here is safe because the task wasn't created on an ASP.NET request thread
                    //       and thus has no captured sync context
                    _initializeDrainTask.Wait(); <-- thread 23 (own the lock) wait 
                }

                if (UsingTaskQueue)
                {
                    Task task = _queue.Enqueue(Send, context);

                    if (task == null)
                    {
                        // The task is null if the queue is full
                        throw new InvalidOperationException(Resources.Error_TaskQueueFull);
                    }

                    // Always observe the task in case the user doesn't handle it
                    return task.Catch(_trace);
                }

                return Send(context);
            } 
        }

I am using the latest public version
204d0000 20528000   Microsoft_AspNet_SignalR_Core   (pdb symbols)          c:\symbols\public\Microsoft.AspNet.SignalR.Core.pdb\8D52D3ECE71546F2B71ECB44073BA5611\Microsoft.AspNet.SignalR.Core.pdb
    Loaded symbol image file: Microsoft.AspNet.SignalR.Core.dll
    Image path: Microsoft.AspNet.SignalR.Core.dll
    Image name: Microsoft.AspNet.SignalR.Core.dll
    Browse all global symbols  functions  data
    Using CLR debugging support for all symbols
    Has CLR image header, track-debug-data flag not set
    Image was built with /Brepro flag.
    Timestamp:        A96C7AE1 (This is a reproducible build file hash, not a timestamp)
    CheckSum:         0005C2B7
    ImageSize:        00058000
    File version:     2.4.1.19093
    Product version:  2.4.1.0
    File flags:       0 (Mask 3F)
    File OS:          4 Unknown Win32
    File type:        2.0 Dll
    File date:        00000000.00000000
    Translations:     0000.04b0
    Information from resource tables:
        CompanyName:      Microsoft
        ProductName:      Microsoft ASP.NET SignalR
        InternalName:     Microsoft.AspNet.SignalR.Core.dll
        OriginalFilename: Microsoft.AspNet.SignalR.Core.dll
        ProductVersion:   2.4.1-rtm-20190403-01
        FileVersion:      2.4.1.19093
        FileDescription:  Microsoft.AspNet.SignalR.Core
        LegalCopyright:   © Microsoft Corporation. All rights reserved.
        Comments:         Async signaling library for .NET to help build real-time, multi-user interactive web applications.


**Questions:** 
1.what does the _initializeDrainTask is responsible for 
2.what was the intent behind the QueuingBehavior (seems there is no documentation for that) 
3.changing the   QueuingBehavior to (always) will prevent the code from waiting how does it effec the behavior from a scale out perspective 

Thanks

**Comment by anurse** [comment]
Can you enable [server-side tracing](https://docs.microsoft.com/en-us/aspnet/signalr/overview/testing-and-debugging/enabling-signalr-tracing#enabling-tracing-on-the-server) and collect traces for the `SignalR.ScaleoutMessageBus` and `SignalR.RedisMessageBus` sources?

> what does the _initializeDrainTask is responsible for

From my understanding it is used to drain the task queue that was configured during initialization.

> what was the intent behind the QueuingBehavior (seems there is no documentation for that)

It controls if messages are sent in-line (thus possibly blocking further sends from occurring and creating backpressure) or if they are queued up (thus allowing messages to be added without backpressure). Backpressure is when the calling code (the one sending the messages) is blocked from continuing until the backlog of messages is flushed out. The trade off is between thread usage and memory usage. Queuing will reduce thread usage (since fewer threads will be blocked waiting for work to complete) but increase memory usage (since new messages just keep getting queued up). Not queuing will reduce memory usage but also reduce throughput (since threads are blocking waiting for messages to be sent).

The default behavior is `InitialOnly` meaning we only queue for the initial phase of establishing the connection to the backplane. After that, we flush all the queued messages and start blocking callers until their messages are sent to the backplane.

> changing the QueuingBehavior to (always) will prevent the code from waiting how does it effec the behavior from a scale out perspective

As described above, changing to Always means you'll always be queuing. That will unblock the threads but the queue may back up and increase memory usage significantly.

---

What kind of load are you getting during this event? Are there a lot of messages being sent/received? Perhaps enabling the [SignalR Performance Counters](https://docs.microsoft.com/en-us/aspnet/signalr/overview/performance/signalr-performance#using-signalr-performance-counters) (if you haven't already) would help get more data about the load in this situation.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
