### ISSUE TITLE
Use with Docker swarm and Traefik proxy

### ISSUE THREAD

**Issue by 93Kamuran** [SignalR/SignalR#4399]
I have a docker swarm with 3 nodes.  In windows, node ı have an aspnet web API Project that works in Microsoft/IIS based image. Normally when ı work on IIS my projects works fine. However to put them into. docker swarm.  my signalR has broken.  I use signalR on the server-side  for send  data to  client-side then  I have code like this

 
                var hubConnection = new HubConnection("http://api.mydomain.com");
                IHubProxy stockTickerHubProxy = hubConnection.CreateHubProxy("MyHub");
              
                await hubConnection.Start(new LongPollingTransport());

                stockTickerHubProxy.Invoke("RefreshData", ID); 

I use Traefik for proxy and using let's encrypt SSL certificates. Normally when this on IIS, the hub could create the connection with subdomain and stars the connection.

But now ı m having an issue like this 

"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond MYmasterNodeIp:433"(this is my master node's IP address  it's a Linux VM and Traefik is on the master node for forwarding request to the services ).  

I tried lots of things but I couldn't achieve to connect signalR with my API.  Everything works perfectly except signalR hub connection on my services. Can anyone help me?

**Comment by anurse** [comment]
When you have a proxy in place in front of SignalR, the first concern I have is if the proxy properly supports WebSockets. If the proxy doesn't handle WebSockets properly, it can cause problems like this since a WebSocket request isn't like a standard HTTP request.

It sounds like the issue is only reproducing when you're behind Traefik instead of directly connecting to IIS, is this accurate?

**Comment by 93Kamuran** [comment]
Absolutely ! When project on iis ı was connecting to hub . One more thing that ı cannot understand is ı have my frontend project is on another iis based image too it is running on another service but same node (windows) in docker swarm.  İt is an angular 7 project ı use hubconnection.start method in constructor of my signalservice.ts fileconnection is is establishing ang return connection is to me. I write same url  for connection . I could not try connection.on method in frontend because I couldnot achieve to connection.start method in severside ever.

**Comment by 93Kamuran** [comment]
> roxy in place in front of SignalR, the first concern I have is if the proxy properly supports WebSockets. If the proxy doesn't handle W

Traefik supports WebSockets. I noticed that My javascript client can connect with the hub behind Traefik proxy it can get Connection id from the hub. However, I need to use .Net client on connecting with the hub class. (Because I send data to .Net client from MSSQL for  connect to hub and invoke the method in the hub) As I told above my code like this. So my  .net client and hub classes are both in the same  WEB API project. When ı look at  WebAPI's container logs I can see 200 result from javascript client requests.

**Comment by halter73** [comment]
```
var hubConnection = new HubConnection("http://api.mydomain.com");
```

Maybe this was just a copy-and-paste error, but you said that you're using let's encrypt SSL certificates. If that's the case you should be using an "https" instead of an "http" url. This would explain the connect timeouts since the client would be trying to connect to port 80, but the server would be listening on port 443.

**Comment by 93Kamuran** [comment]
It was all about my network configurations. I’m using two mssql server they are working on a another VM and they are not in my docker swarm cluster. So ı  resolve my problem with a external ip and move only hubs to my main machine than problem fixed. Thank you  for answers
