### ISSUE TITLE
Groups.Add times out when using redis backplane

### ISSUE THREAD

**Issue by JT00** [SignalR/SignalR#4400]
### Expected  behavior
When client connects, they should be added to group channel successfully using:
`await Groups.Add(Context.ConnectionId, channel);`
I can then send events to group channels with hub context:
`_context = GlobalHost.ConnectionManager.GetHubContext<EventHub>();
_context.Clients.Group(_channel).OnEvent(channel, event);`
where each client in the group will then receive those events.

### Actual behavior
Groups.Add times out, and clients are never added to channel group. Events sent to group channel do not reach any clients, and are not seen in redis. Only connection events and events submitted directly from hub, directly to single client are seen in redis, and reach client.

### Steps to reproduce
Add redis config line to Startup.cs 
GlobalHost.DependencyResolver.UseStackExchangeRedis

Application type: Windows Service 
Environment: windows server 2016
.NET 4.7.2
SignalR version 2.4.1
OWIN Self hosted
REDIS version 4.0.9

Groups.Add works perfect without Redis. Once I add GlobalHost.DependencyResolver.UseStackExchangeRedis line to startup.cs, groups.add times out. 

Redis appears to be working, as I can see initial connection events in Redis, as well as events that are sent directly to the client from the Hub. 

Additionally, if I attempt to send events from outside the hub using 
`_context = GlobalHost.ConnectionManager.GetHubContext<EventHub>();
_context.Clients.Group(_channel).OnEvent(channel, event);`
They appear to fail without exception. I don't see them in redis, nor does the client receive them.

Again, all of this works fine if i remove the redis configuration from startup.

**Comment by anurse** [comment]
Can you collect traces from the server? There is documentation here for enabling these: https://docs.microsoft.com/en-us/aspnet/signalr/overview/testing-and-debugging/enabling-signalr-tracing#enabling-tracing-on-the-server . Specifically, we'd want the `SignalR.RedisMessageBus` and `SignalR.ScaleoutMessageBus` trace sources enabled.

**Comment by JT00** [comment]
Traces are attached. Also here is the Groups.Add timeout exception 

[9:32:07 PM] SIGNALR SUBSCRIBE EXCEPTION: A task was canceled.. InnerException : . StackTrace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at RMCeService.SignalR.EventHub.<Subscribe>d__1.MoveNext()


[transports.log.txt](https://github.com/SignalR/SignalR/files/3513982/transports.log.txt)
[bus.log.txt](https://github.com/SignalR/SignalR/files/3513983/bus.log.txt)

**Comment by JT00** [comment]
Any update on this issue?

**Comment by halter73** [comment]
When Groups.Add times out, do you know for sure if the client is connected? Could it be reconnecting? Or using the long polling transport?

If the client has completely lost its connection to any of the servers, the timeout is expected. If the client is connected to the same machine as the call to Groups.Add, there won't be any message published to the Redis backplane since that will be handled in memory.

**Comment by JT00** [comment]
I'm sure the client is connected because I can see the connection and disconnection events for the the client connection id in Redis. Additionally, I can send a message directly to the client using the client connection id, but only directly from the Hub.  
I'm currently only testing with one machine. Once I get Redis working, I plan to utilize a second machine. 

Please let me know if there's any other details I can provide.

Thanks

**Comment by halter73** [comment]
So if I'm understanding this correctly, *inside a hub method* you can successfully add a connection id to a group and send a message to that group and the newly-added client receives that message. But if you use the IHubContext from GlobalHost.ConnectionManager.GetHubContext, in the very same process, it breaks. And this is with a single server connected to a Redis backplane, but everything work including the IHubContext from GetHubContext if you use the default in-memory MessageBus. Is everything I'm saying an accurate description of the issue?

**Comment by JT00** [comment]
In no scenario does groups.add work with redis enabled. Messages can be sent from the hub directly to a client id, and client can reach hub methods. 
Everything else in your description is accurate.

**Comment by anurse** [comment]
@JT00 do you have the `SignalR.RedisConnection` trace source enabled in your tracing config? If not could you enable it and collect new traces? We're looking to see if there are any Redis connectivity issues during this period.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
