### ISSUE TITLE
Cant call a server method

### ISSUE THREAD

**Issue by mbpakalin** [SignalR/SignalR#4404]
Hello,

I've been trying to work SignalR self hosted but it didnt work like 1 and half day and still i'm working on it. 

I've posted on StackOverflow but still didnt find any solution about it.
Anybody had the same problem ?

StackOverflow link => https://stackoverflow.com/questions/57676824/signalr-self-hosted-and-asp-net-mvc

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!

**Comment by mbpakalin** [comment]
Sorry for the late response, yes this solved by using hub connection.
