### ISSUE TITLE
Hang in _subscriptions dictionary FindEntry

### ISSUE THREAD

**Issue by xdyang1986** [SignalR/SignalR#4406]
Issues related to the Asp.NET Core version of SignalR should be filed in the AspNetCore repo: https://github.com/aspnet/AspNetCore/issues/new/choose
Please remove this line and the line above before submitting a new issue.

### Expected  behavior
when we notify client, it will snd the message correctly.
### Actual behavior
hang in the OnMessageReceived message:

call stack as below:
mscorlib!System.Collections.Generic.Dictionary`2[System.__Canon,System.__Canon].FindEntry(System.__Canon)
mscorlib!System.Collections.Generic.Dictionary`2[System.__Canon,System.__Canon].TryGetValue(System.__Canon, System.__Canon ByRef)
microsoft.aspnet.signalr.client!Microsoft.AspNet.SignalR.Client.HubConnection.OnMessageReceived(Newtonsoft.Json.Linq.JToken)
microsoft.aspnet.signalr.client!Microsoft.AspNet.SignalR.Client.Connection+<>c__DisplayClass169_0.<Microsoft.AspNet.SignalR.Client.IConnection.OnReceived>b__1()
mscorlib!System.Threading.Tasks.Task.Execute()
mscorlib!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
mscorlib!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
mscorlib!System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
mscorlib!System.Threading.Tasks.Task.ExecuteEntry(Boolean)
mscorlib!System.Threading.ThreadPoolWorkQueue.Dispatch()
clr!CallDescrWorkerInternal
clr!??CallDescrWorkerWithHandler
clr!MethodDescCallSite::CallTargetWorker
clr!QueueUserWorkItemManagedCallback
clr!ManagedThreadBase_DispatchInner
clr!ManagedThreadBase_DispatchMiddle
clr!??ManagedThreadBase_DispatchOuter
clr!??ManagedThreadBase_FullTransitionWithAD
clr!ManagedPerAppDomainTPCount::DispatchWorkItem
clr!ThreadpoolMgr::ExecuteWorkRequest
clr!ThreadpoolMgr::WorkerThreadStart
clr!Thread::intermediateThreadProc
kernel32!BaseThreadInitThunk
ntdll!RtlUserThreadStart

More detail:
0:083> !DumpObj /d 00000205d54ba530
Name:        System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[Microsoft.AspNet.SignalR.Client.Hubs.Subscription, Microsoft.AspNet.SignalR.Client]]
MethodTable: 00007ffce9d4cfa8
EEClass:     00007ffd3e905440
Size:        80(0x50) bytes
File:        C:\Windows\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll
Fields:
              MT    Field   Offset                 Type VT     Attr            Value Name
00007ffd3e798538  4001885        8       System.Int32[]  0 instance 00000205d5293be0 buckets
00007ffd3f9f3378  4001886       10 ...non, mscorlib]][]  0 instance 00000205d5293c08 entries
00007ffd3e7985a0  4001887       38         System.Int32  1 instance                2 count
00007ffd3e7985a0  4001888       3c         System.Int32  1 instance                2 version
00007ffd3e7985a0  4001889       40         System.Int32  1 instance               -1 freeList
00007ffd3e7985a0  400188a       44         System.Int32  1 instance                0 freeCount
00007ffd3e787790  400188b       18 ...Canon, mscorlib]]  0 instance 00000205d30dc460 comparer
00007ffd3e7857c0  400188c       20 ...Canon, mscorlib]]  0 instance 0000000000000000 keys
00007ffd3e7aef60  400188d       28 ...Canon, mscorlib]]  0 instance 0000000000000000 values
00007ffd3e795dd8  400188e       30        System.Object  0 instance 0000000000000000 _syncRoot

it seems this dictionary _subscriptions is not thread safe:

        public void InvokeEvent(string eventName, IList<JToken> args)
        {
            Subscription subscription;
            if (_subscriptions.TryGetValue(eventName, out subscription))
            {
                subscription.OnReceived(args);
            }
        }

### Steps to reproduce

Hard to repo in local side, I think if we call hubproxy.on multiple time at the same time in different thread, may hit this issue.

**Comment by anurse** [comment]
Unfortunately, while the `HubConnection` **is** thread-safe when registering callbacks, the `HubProxy` type is not. Generally, invoking methods and receiving callbacks is safe to do from multiple threads but registering methods with `HubProxy.On` should be serialized and done on a single thread only **before** starting the connection.

Changing this is a significant amount of work and we don't intend to do so in a 2.4.x patch release.
