### ISSUE TITLE
WebSocket connection to 'ws://localhost:60377/signalr/connect?transport=webSockets

### ISSUE THREAD

**Issue by kanachrisi** [SignalR/SignalR#4407]
I am trying to run my signalR application but i am getting the following error : "

WebSocket connection to 'ws://localhost:60377/signalr/connect?transport=webSockets&clientProtocol=2.1&connectionToken=f8tOcpqdXVZ245%2BvWKsSFHaGfl6GePMtKf0Jk9wSIJQxsa5KnEiZFyGoFgYuwbQ%2FirsDjiX%2FHtVRJAvhvmOtrvYJpaZD21GHiyyqBw785nI2TICxJ4P33puQnEnjGSlMpmMBxtNk02XxkTJpZxvClw%3D%3D&connectionData=%5B%7B%22name%22%3A%22geologuehub%22%7D%5D&tid=4' failed: Error during WebSocket handshake: Unexpected response code: 500"

I would appreciate any help to fix this problem.

**Comment by kanachrisi** [comment]
Adding the a list of fall-back transports on the javascript fixed the problem. it is weird because i am using googleChrome (Version 77.0.3865.90) and the web socket is not supported!!

  $.connection.hub.start({ transport: ['serverSentEvents', 'longPolling'] }).done(function ()
  {
       console.log(`SignalR connection transport used is "${$.connection.hub.transport.name}"`);
  });

**Comment by BrennanConroy** [comment]
It's likely your server doesn't support websockets or disables websocket connections by default.

**Comment by anurse** [comment]
How are you hosting your application?
* What OS is the server running on?
* Are you using IIS? Self-Host? Some other server?
* What does the "Network" tab in the browser dev-tools show for the WebSocket request?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
