### ISSUE TITLE
Message Broker

### ISSUE THREAD

**Issue by FIVIL** [SignalR/SignalR#4408]
Hi, I don't know even if this is the right question to ask or not. but I was wondering if it's ok to use signalR for developing a message broker service (implementing AMQP) or is it like highly fraud upon?
I know about available message broker solutions and I am aware that this might be considered a somewhat unorthodox use case for signalR. but I was just wondering.

**Comment by anurse** [comment]
Are you trying to use SignalR to **implement** the AMQP protocol? This probably would be very challenging.

In general, adapting SignalR to other protocols isn't something we'd encourage. Having said that, it's all open-source so you're welcome to do what you'd like!

Closing this issue as there's no action for us to take here. We don't provide native support for this at all and have no plans to do so.
