### ISSUE TITLE
Is WatchOS supported by latest version of SignalR client ?

### ISSUE THREAD

**Issue by ThomasLebrun** [SignalR/SignalR#4414]
I'm trying to use SignalR on an Apple Watch project (using WatchOS) but the application is unable to run correctly as it seems to not be a supported plateform (because the SignalR client keep using HttpClientHandler even when I force it to use NSUrlSessionHandler).

I saw some posts saying that NSUrlSessionHandler should be specified but even if I try, it keeps using HttpClientHandler.

Can someone confirm if SignalR client is available (and working) on WatchOS ?

### Expected  behavior
Be able to run the SignalR client, start a connection to the Hub and to receive message

### Actual behavior
At runtime, the application keeps crashing with a PlateformNotSupportedException. The message states the System.Net.HttpClientHandler is not supported, althought it's specified, in csproj of extension projet (and main project), that client handler is NSUrlSessionHandler.
Trying to force it in the WithUrl option parameters gives the same results.

### Steps to reproduce
Create a Watch OS application. Add SignalR Client 3.0 and try to start connection to any Hub.

Thanks !

**Comment by BrennanConroy** [comment]
This issue was moved to aspnet/AspNetCore#14706
