### ISSUE TITLE
Lock contention in TransportHeartBeat.GetConnections()

### ISSUE THREAD

**Issue by paveliak** [SignalR/SignalR#4416]
We had an incident and while analyzing Perfview trace from it I saw lock contention on the ConcurrentDictionary.GetValues() method that leads to [TransportHeartBeat.GetConnections](
https://github.com/SignalR/SignalR/blob/61c1a688f6a4e714e43c5b82b10f6d8b7c612dd6/src/Microsoft.AspNet.SignalR.Core/Transports/TransportHeartBeat.cs#L169)

Changing the code in this way should fix it 
```
return _connections.Select(x => x.Value.Connection).ToList();
```
### Expected  behavior
No lock contention

### Actual behavior
Code acquires all locks of the underlying concurrent dictionary causing lock contention under high load

**Comment by davidfowl** [comment]
@paveliak do you care to send a pull request for this?

**Comment by paveliak** [comment]
@davidfowl I tried but `git push` fails with 403 saying that permission is denied for me

**Comment by davidfowl** [comment]
Yes you can’t push to this repository, you have to fork

**Comment by paveliak** [comment]
Here is the PR https://github.com/SignalR/SignalR/pull/4469
