### ISSUE TITLE
How to mock Clients.GroupExcept

### ISSUE THREAD

**Issue by turowicz** [SignalR/SignalR#4417]
I'm using `Moq` and it fails when I try to mock the `Clients.GroupExcept` method in order for my test to make sure I don't send the information to the unwanted group.

It turns our `Moq` doesn't support interface extension methods so the whole thing is untestable.

Any ideas how can I go about writing my test?

**Comment by turowicz** [comment]
cc @davidfowl @halter73

**Comment by turowicz** [comment]
Surely somebody took that design decision after reviewing things like that?

**Comment by BrennanConroy** [comment]
Did you mean to put this issue here: https://github.com/aspnet/AspNetCore/issues?

I don't think `GroupExcept` exists in ASP.NET SignalR.
