### ISSUE TITLE
Memory leak on SignalR with alot of connections

### ISSUE THREAD

**Issue by TimVervers** [SignalR/SignalR#4421]
Based on issue #3850 we implemented the configuration setting DefaultMessageBufferSize set to 32. But SignalR is still falling in a memory leak. Analyzing the dump file gives roughly 131.000 objects in 26 seconds. Our SignalR version is 2.4.0.

### Expected  behavior
Implementing the setting DefaultMessageBufferSize to 32 should prevent this memory leak based on issue #3850 

### Actual behavior
In-depth objects:
![image](https://user-images.githubusercontent.com/4120383/67015076-37c83700-f0f6-11e9-8604-620a1c5ab232.png)

Heap snapshots:
![image](https://user-images.githubusercontent.com/4120383/67015796-6397ec80-f0f7-11e9-8ca0-258329239770.png)

Memory stack:
![image](https://user-images.githubusercontent.com/4120383/67015833-74e0f900-f0f7-11e9-9a2f-ab56de10f1cc.png)

Memory stack 2:
![image](https://user-images.githubusercontent.com/4120383/67015928-9fcb4d00-f0f7-11e9-84e9-845990f6f89c.png)

### Steps to reproduce
I can only reproduce this issue when starting the SignalR service and immidetialy connect over 200 clients, this by either production activity or the Loadtest tool Crank.

Thanks in advance,

Tim

**Comment by anurse** [comment]
> Analyzing the dump file gives roughly 131.000 objects in 26 seconds.

Where are you seeing 131,000 objects? I see 131,000 **bytes** in the screenshots you provided, but still only 15,000 subscription objects.

Can you provide a little more detail on what the clients do? How many groups are each client part of? What messages are you exchanging back and forth?

As far as I can see, these aren't per-message objects, so reducing the message buffer size wouldn't have an impact on these allocations.

> But SignalR is still falling in a memory leak

Can you clarify how SignalR is **failing**? Is the memory climbing consistently even once all clients are fully connected? I'm trying to understand if this is a _memory leak_ or _high memory usage_.
