### ISSUE TITLE
Sending Message only for Group or Client does not work

### ISSUE THREAD

**Issue by benzmarkus** [SignalR/SignalR#4426]
Using Microsoft.AspNet.SignalR.Core 2.4.1 with asp.net webapi and .net 4.5.

After connecting i create a group "abc".

With a button in the web ui i send a normal http request to the webapi. In the controller i inject  IHubContext<IMessageHub> argMessageHub and try to send the a message only for the group "abc": _messageHub.Clients.Group("abc").NewMessage("dsdfdfdf");

Setup:
I use simpleinjector to inject the container into my MessageHub.

    `GlobalHost.DependencyResolver.Register(typeof(Controllers.MessageHub), () =>
            {
                return new Controllers.MessageHub(argContainer);
            });
            
            var hubConfiguration = new HubConfiguration
            {
                // You can enable JSONP by uncommenting line below.
                // JSONP requests are insecure but some older browsers (and some
                // versions of IE) require JSONP to work cross domain
                // EnableJSONP = true
                EnableDetailedErrors = true,
                EnableJavaScriptProxies = false,
                Resolver = GlobalHost.DependencyResolver
            };

            argApp.Map("/MessageHub", map =>
            {
                // Setup the CORS middleware to run before SignalR.
                // By default this will allow all origins. You can 
                // configure the set of origins and/or http verbs by
                // providing a cors options with a different policy.
                map.UseCors(CorsOptions.AllowAll);
                map.UseOAuthBearerAuthentication(new Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationOptions
                {
                    Provider = new QueryStringOAuthBearerProvider()
                });

                // Run the SignalR pipeline. We're not using MapSignalR
                // since this branch already runs under the "/signalr"
                // path.
                map.RunSignalR(hubConfiguration);
                // map.MapSignalR("", hubConfiguration);
            });`

Mein MessageHub

    `using System;
    using System.Linq;
    using System.Threading.Tasks;
    using Liebherr.SmartApp.Common.Extensions;
    using Liebherr.SmartApp.Contracts.Data.Interfaces;
    using Liebherr.SmartApp.Contracts.Services;
    using Liebherr.SmartApp.WebAPI.Attributes;
    using Liebherr.SmartApp.WebAPI.MessageHub;
    using Microsoft.AspNet.SignalR;
    using Microsoft.AspNet.SignalR.Hubs;
    using Newtonsoft.Json;
    using SimpleInjector;
    using SimpleInjector.Lifestyles;
    
    namespace Liebherr.SmartApp.WebAPI.Controllers
    {
        /// <summary>
        /// Message Hub
        /// </summary>
        [Authorize]
        public class MessageHub : Hub<IMessageHub>
        {
            private readonly Container _container;
    
            /// <summary>
            /// Constructor
            /// </summary>
            /// <param name="argContainer"></param>
            public MessageHub(Container argContainer)
            {
                _container = argContainer;
            }
    
            public override Task OnConnected()
            {
                var connectionId2 = GetConnectionId();
                Groups.Add(connectionId2, "abc");
    
                return base.OnConnected();
            }
    
            private string GetConnectionId()
            {
                string connectionId = null;
                foreach (var keyValue in Context.QueryString)
                {
                    if (keyValue.Key.ToLower() == "connectiontoken")
                    {
                        connectionId = keyValue.Value;
                    }
                }
                return connectionId;
            }
        }
    }`

Webapi Controller:

As Client i use angular-signalr-hub with transport "websocket" not long polling.

    `[AllowAnonymous]
    [RoutePrefix("")]
    public class AppController : ControllerBase
    {
    	public AppController(IHubContext<IMessageHub> argMessageHub)
    	{
    		_messageHub = argMessageHub;
    	}
    	[HttpGet]
    	[AllowAnonymous]
    	[Route("new-message")]
    	public void NewMessage()
    	{
    		_messageHub.Clients.Group("abc").NewMessage("dsdfdfdf");
    	}
    }`

### Expected  behavior
_messageHub.Clients.Group("abc").NewMessage("dsdfdfdf"); should send the message to registered groups
### Actual behavior
nothing happens

**Comment by chartierpw** [comment]
I'm having the exact same issue, same version, 2.4.1   My server hub code is:

using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNet.SignalR;
using SignalrHub;
using System.Data;

namespace SignalRChat
{
    public class ChatHub : Hub
    {

        private static readonly List<User> Users = new List<User>();

        public async override Task OnConnected()
        {

            string userName = Context.QueryString["username"];
            string company = Context.QueryString["company"];
            string department = Context.QueryString["department"];
            string section = Context.QueryString["section"];
            string firstname = Context.QueryString["firstname"];
            string lastname = Context.QueryString["lastname"];
            string connectionId = this.Context.ConnectionId;

            var user = new User();
            user.Name = userName;
            user.firstname = firstname;
            user.lastname = lastname;
            user.company = company;
            user.department = department;
            user.section = section;
            user.ConnectionIds = connectionId;

            await JoinRoom(company.ToUpper()); // There's always a company, join the company room
            if (section != "")
            {
                // If there's a section, join section room
                await JoinRoom(company.ToUpper() + department.ToUpper() + section.ToUpper()); 
            }

            try
            {
                Users.Add(user);
            }
            catch (Exception ex)
            {
                var msg = ex.Message;
            }

            // TODO: Broadcast the connected user

            // send list of connected users to client
            // SendOne(connectionId,userName,"Welcome " + userName + System.Environment.NewLine + "Connected users are:" + System.Environment.NewLine);

            string connectMessage = "";

            foreach (var display in Users)
            {
                if (display.Name != userName)
                {
                    connectMessage = connectMessage + display.Name + System.Environment.NewLine;
                }
            }
            if (connectMessage == "")
            {
                connectMessage = "None";
            }
            SendOne(connectionId, userName, "Welcome " + userName + System.Environment.NewLine + "Connected users are:" + System.Environment.NewLine + connectMessage);
            // SendOne(connectionId, userName, "This is to a specific user.");

            // return base.OnConnected();
        }

        public override Task OnDisconnected(bool stopped)
        {

            string userName = Context.User.Identity.Name;
            string connectionId = Context.ConnectionId;

            var item = Users.Find(x => x.ConnectionIds == connectionId);

            LeaveRoom(item.company.ToUpper()); // Leave company room
            LeaveRoom(item.compny.ToUpper() + item.department.ToUpper() + item.section.ToUpper()); // Leave Section Room

            Users.Remove(item); // remove from users

            return base.OnDisconnected(true);
        }

        public void SendOne(string connectionId, string userName, string message)
        {

            Clients.Client(connectionId).broadcastMessage(userName, message);

        }

        public void Send(string name, string message)
        {
            // Call the broadcastMessage method to update clients.
            Clients.All.broadcastMessage(name, message);
        }

        public void messageSection(string company, string department, string section, string name, string message)
        {
            string GroupName = company.ToUpper() + department.ToUpper() + section.ToUpper();
            Clients.Group(GroupName).addChatMessage(name, message);

        }

        public void messageCompany(string company, string name, string message)
        {
            try
            {
                Clients.Group(company.ToUpper()).addChatMessage(name, message);
            }
            catch (Exception ex)
            {
                string errormsg = ex.Message;
            }

        }

        public List<string> getConnectedUsers()
        {
            List<string> UserNames = new List<string>();

            foreach (var ConnectedUser in Users)
            {
                UserNames.Add(ConnectedUser.Name + ": " + ConnectedUser.firstname + " " + ConnectedUser.lastname);
            }
           return UserNames;
        }

        public List<string> getConnectedSectionUsers(string company, string department, string section, string username)
        {
            List<string> UserNames = new List<string>();


            foreach (var ConnectedUser in Users)
            {
                if (ConnectedUser.company.ToUpper() == company.ToUpper() && ConnectedUser.department.ToUpper() == department.ToUpper() && ConnectedUser.section.ToUpper() == section.ToUpper())
                {
                    if (username.ToUpper() != ConnectedUser.Name.ToUpper())
                    {
                        UserNames.Add(ConnectedUser.Name + ": " + ConnectedUser.firstname + " " + ConnectedUser.lastname);
                    }
                }
            }
            return UserNames;
        }

        public async Task JoinRoom(string roomName)
        {
            await Groups.Add(Context.ConnectionId, roomName);
        }

        public Task LeaveRoom(string roomName)
        {
            return Groups.Remove(Context.ConnectionId, roomName);
        }

    }
}

SendOne method always works correctly and users always get messages.  When sending by group, nothing.

**Comment by benzmarkus** [comment]
Hi,

for me it works now. Used wrong connection id, that was the problem why send by group does not work.

**Comment by chartierpw** [comment]
Unfortunately that's not my issue as I'm sending to the entire group, not a specific connection id using:

Clients.Group(league.ToUpper()).AddChatMessage(name, message)

**Comment by chartierpw** [comment]
Apparently "addChatMessage` is no longer the method one uses to send messages to a group.  I changed "addChatMessage" to "broadcastMessage" and the hub works exactly as I need it to.

**Comment by mak0t0san** [comment]
> Hi,
> 
> for me it works now. Used wrong connection id, that was the problem why send by group does not work.

You should close this issue if it's working for you now. Sounds like it's not an issue anymore.

**Comment by ravisankarchalamalasetty** [comment]
Azure SignalR service + Azure function based hubs
--------------------------------------------------------
I am just wondering if sending message to specific group within connected clients is working at all for anyone? Broadcast is working well though! Likewise, sending message to a specific user within connected clients is also not working just like sending to a specific group of users. Not sure if I am missing something in this context. Any leads would be appreciated!

        [FunctionName("SendMessageToSpecificGroup")]
        public Task SendMessageToSpecificGroup(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post")] object message,
            [SignalR(HubName = "maintenancehub")] IAsyncCollector<SignalRMessage> signalRMessages)
        {
            var inputParameters = JsonConvert.DeserializeObject<GroupDTO>(message.ToString());

            return signalRMessages.AddAsync(
                new SignalRMessage
                {
                    GroupName = inputParameters.GroupName,
                    Target = "GroupSpecificMessageTargetCaller",
                    Arguments = new[] { message }
                });
        }


        [FunctionName("BroadcastMessage")]
        public Task BroadcastMessage(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post")] object message,
            [SignalR(HubName = "maintenancehub")] IAsyncCollector<SignalRMessage> signalRMessages,
            ILogger logger)
        {

            logger.LogInformation($"message to be sent is:" + message);
            return signalRMessages.AddAsync(
                new SignalRMessage
                {
                    Target = "BroadcastMessageTargetCaller",
                    Arguments = new[] { message }
                });
        }
        
The target method i.e. 'GroupSpecificMessageTargetCaller' is never triggering in the client side javascript. 
On the contrary broadcast message to all connected clients is working well though. Target method 'BroadcastMessageTargetCaller' in the html client is getting triggered in broadcast case. 

Client side code
--------------------

    connection.on('BroadcastMessageTargetCaller', BroadcastMessageTargetCaller);
    connection.on('GroupSpecificMessageTargetCaller', GroupSpecificMessageTargetCaller);

    let counter = 0;
    function BroadcastMessageTargetCaller(message) {
      message.id = counter++; // vue transitions need an id
      data.messages.unshift(message);
    }

    let groupCounter = 0;
    function GroupSpecificMessageTargetCaller(message) {
      message.id = groupCounter++; 
      data.groupSpecificMessages.unshift(message);
    }

 
Attaching complete source code for any further investigation. 
Thanks in advance!

[AzureFunctonBasedSignalRService.zip](https://github.com/aspnet/AzureSignalR-samples/files/5711271/AzureFunctonBasedSignalRService.zip)

Server code-->

namespace MyFirstAzureFunction
{
    public class MaintenanceHub : ServerlessHub
    {

        Dictionary<string, string> groupsDictionary = new Dictionary<string, string>();

        #region "SignalR Triggers"

        [FunctionName("negotiate")]
        public  SignalRConnectionInfo Negotiate(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post")] HttpRequest req,
            ClaimsPrincipal claimsPrincipal,
            [SignalRConnectionInfo(HubName = "maintenancehub")] SignalRConnectionInfo connectionInfo, ILogger log)
        {
            return connectionInfo;
        }

        [FunctionName(nameof(OnConnected))]
        public async Task OnConnected([SignalRTrigger] InvocationContext invocationContext, ILogger logger)
        {
            await Clients.All.SendAsync("ClientMethod", invocationContext.ConnectionId);
            logger.LogInformation("Connection Id of the client is:" + invocationContext.ConnectionId);
        }

        [FunctionName(nameof(OnDisconnected))]
        public void OnDisconnected([SignalRTrigger] InvocationContext invocationContext, ILogger logger)
        {
            logger.LogInformation($"{invocationContext.UserId} has disconnected");
        }

        #endregion

        #region "HTTP Triggers"


        [FunctionName("AddUserToGroup")]
        public Task AddUserToGroup(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post")] object userDetails,
            ClaimsPrincipal claimsPrincipal,
            [SignalR(HubName = "maintenancehub")] IAsyncCollector<SignalRGroupAction> signalRGroupActions,
            ILogger logger)
        {

            var loggedInUserDetails = JsonConvert.DeserializeObject<AddUserToGroupDTO>(userDetails.ToString());

            string[] userIdentifierData = loggedInUserDetails.UserName.Split(".", StringSplitOptions.None);

            if (!groupsDictionary.ContainsKey(userIdentifierData[0]))
            {
                groupsDictionary.Add(userIdentifierData[0], userIdentifierData[0]);
                logger.LogInformation($"New group is created with the name: " + userIdentifierData[0]);
            }

            logger.LogInformation($"User added under " + loggedInUserDetails.UserName + " group");
            //var userIdClaim = claimsPrincipal.FindFirst(ClaimTypes.NameIdentifier);

            return signalRGroupActions.AddAsync(
                new SignalRGroupAction
                {
                    UserId = loggedInUserDetails.UserName,//loggedInUserDetails.UserName,
                    GroupName = userIdentifierData[0],
                    Action = GroupAction.Add
                });
        }

        [FunctionName("BroadcastMessage")]
        public Task BroadcastMessage(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post")] object message,
            [SignalR(HubName = "maintenancehub")] IAsyncCollector<SignalRMessage> signalRMessages,
            ILogger logger)
        {

            logger.LogInformation($"message to be sent is:" + message);
            return signalRMessages.AddAsync(
                new SignalRMessage
                {
                    Target = "BroadcastMessageTargetCaller",
                    Arguments = new[] { message }
                });
        }


            //await Clients.All.SendAsync("BroadcastMessageTargetCaller", new[] { message });

        [FunctionName("SendMessageToSpecificGroup")]
        public Task SendMessageToSpecificGroup(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post")] object message,
            [SignalR(HubName = "maintenancehub")] IAsyncCollector<SignalRMessage> signalRMessages)
        {
            var inputParameters = JsonConvert.DeserializeObject<GroupDTO>(message.ToString());

            return signalRMessages.AddAsync(
                new SignalRMessage
                {
                    GroupName = inputParameters.GroupName,
                    Target = "GroupSpecificMessageTargetCaller",
                    Arguments = new[] { message }
                });
        }

        //await Clients.Group(inputParameters.GroupName).SendAsync("GroupSpecificMessageTargetCaller", new[] { message});

        [FunctionName("SendMessageToSpecificUser")]
        public Task SendMessageToSpecificUser(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post")] object message,
            [SignalR(HubName = "maintenancehub")] IAsyncCollector<SignalRMessage> signalRMessages,
            ILogger logger
            )
        {
            var inputParameters = JsonConvert.DeserializeObject<UserDTO>(message.ToString());
            return signalRMessages.AddAsync(
                new SignalRMessage
                {
                    UserId = inputParameters.UserId,
                    Target = "UserSpecificMessageTargetCaller",
                    Arguments = new[] { message }
                });
        }


        #endregion

    }

    #region "Helper classes"

    public class AddUserToGroupDTO
    {

        public string UserName { get; set; }

    }

    public class GroupDTO
    {

        public string Sender { get; set; }

        public string Text { get; set; }

        public string GroupName { get; set; }

    }

    public class UserDTO
    {

        public string Sender { get; set; }

        public string Text { get; set; }

        public string UserId { get; set; }

    }

    public class messageDTO
    {
        public string Sender { get; set; }
        public string Text { get; set; }
    }

    #endregion

}

**Comment by halter73** [comment]
```
        return signalRGroupActions.AddAsync(
            new SignalRGroupAction
            {
                UserId = loggedInUserDetails.UserName,//loggedInUserDetails.UserName,
                GroupName = userIdentifierData[0],
                Action = GroupAction.Add
            });
```

I doubt the UserName is the UserId. You should be using ClaimTypes.NameIdentifier. If you're still having problems, I recommend filing an issue in https://github.com/Azure/azure-signalr.
