### ISSUE TITLE
Identifiy wpf client is online at any point of time with signalr

### ISSUE THREAD

**Issue by Suresh9sb** [SignalR/SignalR#4429]
We have MVC 5 application which holds SignalR Hub and hosted in IIS an we have WPF Clients deployed in user machines which talks with Hub for receiving and sending text information and system works fine. 

On the server Hub I have override OnCOnnect, Onreconnect and OnDisconnect events to update user information who are offline and online. So at any point of time I want to hold active users at a particular time.

Need help in identifying the below use case ( I tried googling for the info and I have not found online) so posting here
1. User Logs off or shutdown the system. 
2. when internet disconnects or he is way for sometime i.e system went to idle state 
so that I will update them as inactive in my database. 

I have followed MSDN article to register onConnected and OnReconnected and deregister Ondisconnected.

Thank you

**Comment by halter73** [comment]
In SignalR 2.1.0, there is a new overload to OnDisconnected that takes a bool indicating whether the client disconnected gracefully or not. See https://github.com/SignalR/SignalR/issues/3115#issuecomment-48425589

For more advance scenarios with scaleout, take a look at https://github.com/DamianEdwards/NDCLondon2013/tree/master/UserPresence
