### ISSUE TITLE
SignalR Scaleout with Redis throws radomly exceptions

### ISSUE THREAD

**Issue by Beczka** [SignalR/SignalR#4431]
Hi, I'm using Redis + SiganlR and I'm  radomlly reciving this exception :

`System.InvalidOperationException: The queue is full. at Microsoft.AspNet.SignalR.Messaging.ScaleoutStream.Send(Func2 send, Object state) at Microsoft.AspNet.SignalR.Infrastructure.Connection.Send(ConnectionMessage message) at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.Outgoing(IHubOutgoingInvokerContext context) at ....`

my configuration is copy/paste from https://docs.microsoft.com/en-US/aspnet/signalr/overview/performance/scaleout-with-redis + I looked into Redis cache. It seems that it's ok. It has enough space. 

Does anyone have any idea why this is happening or how can I debug this?

**Comment by ncapito** [comment]
We are experiencing this same issue.  We get these errors randomly and i can't seem to track down why/what breaks when they happen.

**Comment by ncapito** [comment]
Any one out there listening?  We are still experiencing this issue.  It only started happening after we upgraded this package.

**Comment by hkheireddine** [comment]
Anyone figured out this issue ? i set MaxQueueLength to 50k using the latest StackExchange.Redis 2.0.0.0 and i am still having the issue and i have less than 30K clients connected

**Comment by BrennanConroy** [comment]
Hi. It looks like this is a question about how to use SignalR. This repo is in maintenance mode and we only have the resources to fix major issues, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com/).
