### ISSUE TITLE
OnDisconnectedAsync has null exception when user lost signal

### ISSUE THREAD

**Issue by kienit** [SignalR/SignalR#4432]
I have SignalR hub which has OnDisconnectedAsync() override the base method.
I expected when user lost signal, I must have some reason. However, it always return null

### Expected  behavior
Exception must has some message instead null

### Actual behavior
null exception

### Steps to reproduce

 public override async Task OnDisconnectedAsync(Exception exception)
        {
            var key = Context.GetHttpContext().User.Identity.Name;
            var connectionID = Context.ConnectionId;

            // Disconnect by intention
            if (exception == null)
            {} e;se { }
            await TryStopBroadcast();
            await base.OnDisconnectedAsync(exception);
        }

**Comment by BrennanConroy** [comment]
This issue was moved to aspnet/AspNetCore#17260
