### ISSUE TITLE
function in javascript not getting called SignalR

### ISSUE THREAD

**Issue by dnyati** [SignalR/SignalR#4433]
I have an MVC application which uses signalR for event . In my view I have 4 buttons login, open, refreshToken, Logout.  In my view clieck event of all 3 buttons works i.e login, refreshToken & Logout but onClick of open button is not working. 
below is my code for client side
   $.connection.hub.start().done(function () {
                $('#login').click(function () {
                    // call the Login method on the hub
                    var tokenRequestResponse = IShub.server
                        .login($('#server').val(), false, $('#username').val(), $('#password').val())
                        .done(processTokenRequestResponse);
                });
                $('#refresh').click(function () {
                    $('#events').prepend("refresh.click" + "\n");
                    // call the Refresh method on the hub
                    var tokenRequestResponse = IShub.server
                        .refreshToken($('#accessToken').val(), $('#refreshToken').val())
                        .done();
                });
                $('#logout').click(function () {
                    $('#events').prepend("logout.click" + "\n");
                    // call the Logout method on the hub
                    IShub.server
                        .logout($('#accessToken').val())
                        .done(function (tokenRequestResponse) {
                    });
                });
                $('#open').click(function () {
                    $('#events').prepend("open.click" + "\n");
                    //Call Set Sing on method on hub
                    IShub.server.SignOn($('#accessToken').val())
                        .done();
                });
            });

I have SignOn method on hub. But when I click open button nothing happens. But other 3 button works as expected.  Is there anything I am missing?

**Comment by theutkarshjain** [comment]
Change the naming convention of method name i.e. **signon**  form **SignOn** while calling from javascript. I was also facing the same issue and later I resolved this by doing the same. Hope this will help!!!

**Comment by dnyati** [comment]
Thanks Issue is resolved when I moved it outside/before    $.connection.hub.start().done(function () {}.
