### ISSUE TITLE
No assembly found containing a Startup or [AssemblyName].Startup class."

### ISSUE THREAD

**Issue by colotoon** [SignalR/SignalR#4437]
Hello all!
I`m trying to start simple selfhost app, but got error:

> System.EntryPointNotFoundException: "The following errors occurred while attempting to load the app.
>  - No assembly found containing an OwinStartupAttribute.
>  - No assembly found containing a Startup or [AssemblyName].Startup class."

here:
**using (WebApp.Start(url))**

```
static void Main(string[] args)
        {
            string url = "http://localhost:8080";
            using (WebApp.Start(url))
            {
                Console.WriteLine("Server running on {0}", url);
                Console.ReadLine();
            }
        }

```

full code u can see here: 
https://docs.microsoft.com/en-us/aspnet/signalr/overview/deployment/tutorial-signalr-self-host
i`m not add any new lines to code, all just copy-pasted from tutorial

please, help to start!

### Steps to reproduce
https://docs.microsoft.com/en-us/aspnet/signalr/overview/deployment/tutorial-signalr-self-host

**Comment by halter73** [comment]
What namespace is your Startup class defined in? What's the AssemblyName of your project. If the Startup namespace matches your assembly name, it should work. Even if the Startup class isn't in the conventional place, you should be able to add `[assembly: OwinStartup(typeof(Startup))]` to the assembly calling `WebApp.Start(url)` and make it work that way.
