### ISSUE TITLE
Microsoft.AspNet.SignalR.Client.Samples dependence .NETCoreApp 2.1 error

### ISSUE THREAD

**Issue by akira32chen** [SignalR/SignalR#4441]
I download complete source code and use Visual Studio Professional 2017  to open the solution(After cloning the repository, run build.cmd.)

But I find Microsoft.AspNet.SignalR.Client.Samples's dependence .NETCoreApp 2.1 has errors.
Could somebody know how to solve this problem？

Severity	Code	Description	Project	File	Line	Suppression State
Error		The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.1.	Microsoft.AspNet.SignalR.Client.Samples	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets	112	

Error		The current .NET SDK does not support targeting .NET Standard 2.0.  Either target .NET Standard 1.6 or lower, or use a version of the .NET SDK that supports .NET Standard 2.0.	Microsoft.AspNet.SignalR.Client	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets	126	

Error	NETSDK1050	The version of Microsoft.NET.Sdk used by this project is insufficient to support references to libraries targeting .NET Standard 1.5 or higher.  Please install version 2.0 or higher of the .NET Core SDK.	Microsoft.AspNet.SignalR.Client.JS.Tests	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\Microsoft.NET.Build.Extensions.NETFramework.targets	67

I want to write three projects: Windows Form, Web Client、SignalR Server. Does somebody suggest me to see which book or website?
SignalR Server can be a bridge between Windows Form and Web Client by SignalR.

**Comment by BrennanConroy** [comment]
Hi. It looks like this is a question about how to use SignalR. This repo is in maintenance mode and we only have the resources to fix major issues, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com/).
