### ISSUE TITLE
Error connecting to SignalR from Android Xamarin

### ISSUE THREAD

**Issue by pmarzullo** [SignalR/SignalR#4442]
Hi, I have a web development created with asp mvc 5 (.net 4.7.2) that contains a standard hub nothing complicated.

The JS Client connection works well, from the website.

The problem is with an Android application developed with VS Xamarin, the emulator connects to the hub (already published on the Azure VM host with static IP, etc.) everything works fine.

But when I publish the Android app and use it from the smartphone it doesn't connect.

What could be the problem?

I have several logs with error details.

Thanks

**Comment by davidfowl** [comment]
Seeing the error log would help 😄
