### ISSUE TITLE
SQL Backplane - plan cache becomes bloated when sending due to @Payload parameter changing size

### ISSUE THREAD

**Issue by mak0t0san** [SignalR/SignalR#4444]
### Expected  behavior
SQL should just cache one plan. The `@Payload` parameter should be `varbinary(max)` instead of `varbinary(nnn)` {where nnn  changes based on the size of the message}.

### Actual behavior
The issue is in SqlSender when it creates the `@Payload` parameter.  It's a varbinary and when the SQL runs it will execute with different sizes (`@Payload varbinary(4001)`, `@Payload varbinary(4731)`, `@Payload varbinary(5000)`, etc.).  This causes SQL to cache each one of these separately and bloating the plan cache.
 
![image](https://user-images.githubusercontent.com/987722/73278396-85eedb00-41b9-11ea-9416-9c932cea55d7.png)

I've created a fork and made changes to fix the issue:
https://github.com/mak0t0san/SignalR/commit/f9b12cfcc269a71aeedbbfba00fc4351cd65e9e8

### Steps to reproduce
Use SignalR with SQL backplane.

**Comment by laurihelkkula** [comment]
We are also seeing this problem. Transitioning to some other backplane would be non-trivial, so a fix for this would be nice. 

Would you take a PR for this? The change seems to pretty simple and I think I can also create a unit test.
I do have one question: Is it okay to use varbinary(max) for all payload sizes or is there some benefit for using one size (or few sizes) for payloads under that size and max for anything over that size? For example, use the varbinary(8000) for payloads under 8000 bytes and max for everything over 8000 bytes?  8000 is the max size for non-max varbinary.

**Comment by BrennanConroy** [comment]
https://github.com/SignalR/SignalR/pull/4467#issuecomment-781662759
