### ISSUE TITLE
How do we get connection Id out of Hub?

### ISSUE THREAD

**Issue by huangjinshe** [SignalR/SignalR#4446]
I want to save `Connection Id` when first connect , and  send message to the user that what user I want to send .

`Connection Id` only available in hub, I can't use it other place. Like after in to the `Hub` we're going to more deep, some place we might be use it.

Before I change my WCF to SignalR, I consider so much, WCF so much powerfull to do every thing, but the only problem is Mono don't support DuplexChannel, that cause mobile  can't use it. 
Then when I search framework to replace WCF, I saw some people recommend SignalR, said it is a good framework, also it support duplex channel. 

But After I trying to change my hole WCF project and using it, there are so many limit. What I want is simple, I save the session when first request come in, no matter it's a `Client` or `Session Id`, I just need to call it whatever I want to call and send message (push message to user who I choice, maybe this time, maybe background without in Hub). 

Changing WCF class to send request not cost my too much time, basically I just need to add Hub like:
Original WCF code:

```
[ServiceBehavior(InstanceContextMode = InstanceContextMode.Single,
        ConcurrencyMode = ConcurrencyMode.Multiple), CallbackBehavior]
public class Service : IService{....}
```

New code for support SignalR:
```
[ServiceBehavior(InstanceContextMode = InstanceContextMode.Single,
        ConcurrencyMode = ConcurrencyMode.Multiple), CallbackBehavior]
public class Service : **Hub**, IService{....}
```

I just hoping you guys give us more choise for handle the `Client`. 
Like we could save current `Client` to our Server for use some times.  Also terminate that client we want to terminate.
After all no every one want to use it for make a chat tool. (It's too basic, send to all, or send to 1 , that also need to know session Id, that also required request in the Hub)
Also I hope you guys design it more easy to let developer move from original WCF(or maybe support both, spetially liek handle the callback), that will get more developer in the future to this project, I think there are more people still searching new framework to replace WCF, specially some project that need more advanced feature.

At the end, I still hope you guys give me some advice to get `Session Id` from other place. Thanks

**Comment by huangjinshe** [comment]
These method not working, by the way:

```
var hubContext1 = GlobalHost.DependencyResolver.Resolve<IConnectionManager>().GetHubContext<ServiceHub>();
var hubContext2 = GlobalHost.ConnectionManager.GetHubContext<ServiceHub>();
```
It can get hub context, but push message not working.

**Comment by davidfowl** [comment]
I'm not 100% sure what you're asking for. 

> I want to save Connection Id when first connect , and send message to the user that what user I want to send .

What's the issue with this? Where's the sample code?

**Comment by huangjinshe** [comment]
@davidfowl , I want to save the ConnectionId from the client when the client send me the request first time. And then I want to pull message to the client whenever I want send by the client ConnectionId.

But the thing is, I can't pull message to the client after get hub context by these code

```
var hubContext1 = GlobalHost.DependencyResolver.Resolve<IConnectionManager>().GetHubContext<ServiceHub>();
var hubContext2 = GlobalHost.ConnectionManager.GetHubContext<ServiceHub>();
```

these code even can't get the hub context correctly I guess. because the code never worked:

hub.Clients.Client(service.SignalRClientSessionId).Close();

`hubContext1.Clients.Client(ConnectionId).PullMessage();`

**Comment by davidfowl** [comment]
Handle OnConnected in your service hub, store the connection id.

**Comment by huangjinshe** [comment]
@davidfowl , I can get ConnectionId when get request every time with my own session parameter(because ConnectionId will change if connection has some problems), and I can get it by:

` Context?.ConnectionId`

But when I want to pull message, I can't get Hub Context. these 2 lines all not working for get the current Hub Context.

**Comment by davidfowl** [comment]
I think maybe there's a misunderstanding on how things work. The Hub is stateless, it isn't tied to a specific connection you can't get the connection id for a hub because it doesn't make sense.

> But when I want to pull message, I can't get Hub Context. these 2 lines all not working for get the current Hub Context.

Pull a message from where? What is the context? Which connection are you trying to send it to?

Here's a picture:

![image](https://user-images.githubusercontent.com/95136/80870419-31954480-8c5b-11ea-91a6-3061e118f8e5.png)

2 connections with different ids, are connected to the hub and then there's some background work off on the side in the same process on the server wanting to send to a specific connection. How would that background job get the appropriate connection id? 

Is that what you're trying to solve?

**Comment by huangjinshe** [comment]
@davidfowl ,Really sorry I want to say push.....  I just too anxious and say it to pull.


I want push message to the client.  Yeap.

**Comment by davidfowl** [comment]
But you didn't answer my other questions. The Hub instance is not per connection like I said before, it's stateless. So when a client connects you need to capture a connection and store, it. From your background work, you then need to pick which connection you want to send to. 

Can you explain what you are trying to accomplish? In the diagram above, which client are you trying to send to and where are you trying to send from?

**Comment by huangjinshe** [comment]
Let me say an example:

User A a Manager
User B also a Manager.
User C and D are employee.

Now they all connected to the Hub. now the employee D want send a message to A,B,C,  or maybe Need to send for Managers only (wich C, D). 

Why this is very important? I just want to push message to some client which I want to push, and currently API seems to only can do it by Hub Context + ConnectionId. like:


`Hub.Clients.Client(ConnectionId from specific client).DynamicPushMessage();`

**Comment by davidfowl** [comment]
That's right, you have a few primitives:
- Users
- ConnectionId
- Groups

Have you read the documentation (https://docs.microsoft.com/en-us/aspnet/signalr/)?

You can use those primitives to target a set of clients with an invocation.

**Comment by huangjinshe** [comment]
@davidfowl , I only saw the part which I will use.
Also I didn't use Authorization in it.  I have my own model. 

Currently I already fix all problems. This question I asked like 2 or 3 months ago.

When the first time connect and send request to the Hub, I generate my own SessionId and return it to my client, then after that my client will always send the SessionId, that fix the problem that SignalR ConnectionId will change problems. 


```
// First request
string ClientConnectionId = Context?.ConnectionId;
string ClientSessionId =  Guid.NewGuid();
Store(ClientSessionId, ClientConnectionId);
return ClientSessionId;
```


I am sore the ConnectionId and my own SessionId in Server, If the ConnectionId change, I will know by my own SessionId and I will change it store(replace old). Then I will know the Client always.

```
// Heartbeat for check connection state, or for reconnected it when network failed.
var model = GetCurrentConnection(ClientSessionId)
// But I can't know the connect was Disconnect.
if (model.ClientConnectionId != Context?.ConnectionId || model.IsDisConnect)
{
    model.ClientConnectionId = Context?.ConnectionId;
}
```


After that I get the Hub Context when the first request come, I know it's really dump but I didn't find any API for it. but every client first request all go throw it..... I still don't like this way:


```
 // Every client first request will throw this(this is just for get Hub context, only work for once)
if (null == SomePlace.ServiceHub)
    SomePlace.ServiceHub = _context;
```


Then now I can push message from everywhere(Not from Hub Context, just everywhere):

```
try{
        SomePlace.ServiceHub.Clients.Client(ConnectionId).ServiceTakeoutAddNotification(toClient)
} catch(Exception ex)
{
    Store the message and send it later, if client too long not respose then next time let user get the all data again. and abandon this message.
}
```

But the only problem is I can't try catch this method for know How it worked. WCF could let me know if can't push the notification when use Duplex Channel. That's a another problem:

[Is there any possible make a reliable callback?](https://github.com/SignalR/SignalR/issues/4447)

I write this all just in case someone will need.  If you have a better idea for get Hub Context let me know. Thank you.

**Comment by davidfowl** [comment]
That logic looks *extremely* unreliable. Seems like you should just use the built in primitives. I'll leave you with some high level tips because I think you've already solved the problems in a different (albiet unreliable) way:

- You can keep track ofConnected and Disconnected clients using events on the hub
- You can add connections to groups when clients connect, this allows you to add a bunch of clients to a group then send them a message. So for example, you can use the session id as the group name then send to that session.
- You don't need to store the _context from the hub, I have no idea what you're trying to achieve there but it looks ripe for race conditions.


Your code samples are missing lots of context.

> When the first time connect and send request to the Hub, I generate my own SessionId and return it to my client, then after that my client will always send the SessionId, that fix the problem that SignalR ConnectionId will change problems.

Sounds fine. By change I assume you mean if the connection stops and you restart it?

> I am store the ConnectionId and my own SessionId in Server, If the ConnectionId change, I will know by my own SessionId and I will change it store(replace old) again. Then I will push message to the client always.

Sounds good. Why not add the connection id to a group which is the session id? That way you can send to that connection by sending to the group:

```C#
Context.Group(SessionId).DynamicMessageInvoke();
```

> After that I get the Hub Context when the first request come, I know it's really dumm, but I didn't find any API for it. but every client first request all go throw it..... I still don't like this way:

Why? Why don't you use the global host?

> Then now I can push message from everywhere(Not from Hub Context, just everywhere):

How do you get the right connection id.

```C#
SomePlace.ServiceHub.Clients.Client(ConnectionId).PushDynamicMethod(toClient)
```

Where does ConnectionId and toClient come from? This is what I was asking you originally.

Why wouldn't this work:

```
var hubContext = GlobalHost.ConnectionManager.GetHubContext<ServiceHub>();
hubContext.Clients.Client(ConnectionId).PushDynamicMethod(toClient);
```

**Comment by huangjinshe** [comment]
> Sounds fine. By change I assume you mean if the connection stops and you restart it?
Yes

> Sounds good. Why not add the connection id to a group which is the session id? That way you can send to that connection by sending to the group:
I gave you just a simple example, my clients can't use like a Fixed Group, For example maybe I want pull message to which users that I choice to send. In that case I can't put every clients to a new group,I think create a new group for that every time is unnecessarily for me.

> Why? Why don't you use the global host?
This is a static variable, you could say it's a global host. (Or maybe I misunderstanding you again),
I use WCF with SignalR together right now, WCF is a host in Windows Service. SignalR just a another option for mobile user. (I choice signalR because it support duplex message, but now I know it's not reliable, not like WCF, this is really dissapointing me... Maybe I need to wait WCF until Xamarin move from mono to .net core, then All mobile device could use WCF duplex channel...)

> How do you get the right connection id.
As I said before I store the client sessionId with connectionId. (Actually not only SessionId, I store client info on server), other client just get all client info from server, choice some session ids, and send message, server will get every client Connection Id one by one by Client session Id. done.

> Where does ConnectionId and toClient come from? This is what I was asking you originally.
........... ,  The Connection Id come from server, get it by Session Id, I don't want to repeat it again. `toClient`  obviously is a parameter, which include a message which you want to push to client.


> Why wouldn't this work:
You tell me Boss....I want to use it everywhere but obviously I can get Context by using that way, but after push notification, there is nothing happen. (I don't know is that because I'm using self-hosting or not execute it in the Hub mehod, just like I get `Context `only in the method inside that implement ServiceHub), it was too long time ago, I search so much place, Google, Stackoverflow...
This place just like dead for me.

Choice this global variable hub context way is a really upset move.

**Comment by davidfowl** [comment]
OK now we're making some progress!

> You tell me Boss....I want to use it everywhere but obviously I can get Context by using that way, but after push notification, there is nothing happen. (I don't know is that because I'm using self-hosting or not execute it in the Hub mehod, just like I get Context only in the method inside that implement ServiceHub), it was too long time ago, I search so much place, Google, Stackoverflow...
This place just like dead for me.

Did you set change the IDependencyResolver that SignalR is using anywhere in the code? If so, that could be the reason it's not working. If you set an IDependencyResolver and don't set GlobalHost.DependencyResolver, you'll have different universes.

> This is a static variable, you could say it's a global host. (Or maybe I misunderstanding you again),
I use WCF with SignalR together right now, WCF is a host in Windows Service. SignalR just a another option for mobile user. (I choice signalR because it support duplex message, but now I know it's not reliable, not like WCF, this is really dissapointing me... Maybe I need to wait WCF until Xamarin move from mono to .net core, then All mobile device could use WCF duplex channel...)

I don't know why Xamarin/Mono doesn't support the WCF duplex channel but maybe they do now? If not, I'm sure you filed an issue 😃 . SignalR doesn't have a way to know that clients get a particular message (as you now know), that must be layered on top. It's also not something that will ever change (at least in this version of the product).

**Comment by huangjinshe** [comment]
Nope,  I Register it only for change the global json setting. This is my code:

```
public void StartSignalR(string address)
        {
            SignalR = WebApp.Start<Startup>(address);
        }


public class Startup
    {

        public void Configuration(IAppBuilder app)
        {
            app.UseCors(CorsOptions.AllowAll);


            var hubConfiguration = new HubConfiguration
            {
                EnableDetailedErrors = true,
                EnableJSONP = true,
                EnableJavaScriptProxies = false
            };

            

            GlobalHost.DependencyResolver.Register(typeof(JsonSerializer), () => JsonSerializer.Create(new JsonSerializerSettings
            {
                DefaultValueHandling = DefaultValueHandling.Ignore,
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
                NullValueHandling = NullValueHandling.Ignore
            }));
            GlobalHost.HubPipeline.AddModule(new ErrorHandlingPipelineModule());


            app.MapSignalR(hubConfiguration);

        }
}
```

Xamarin for UWP does support Duplex channel in WCF. but Xamarin for iOS and Andoird because based on Mono, it let me waited so long....

Currently I can only push the message when my iOS or Android App Activated. But if my App go to background and go back to the App, I need to get all new data....That's what currently I can only do by SignalR.   WCF will store the message on server when failed to send, and send all message when App back, but currently SignalR don't know how message success or failed. So.... Thank you anyway.
