### ISSUE TITLE
Is there any possible make a reliable callback?

### ISSUE THREAD

**Issue by huangjinshe** [SignalR/SignalR#4447]
Before when I use `WCF` project, I'm using `Duplex Channel` to handle everything. I can push message or anything by order, My client high depend to `callback`, can't lose, order can't change.

After I heard SignalR support `Duplex message`, I thought I finally can bring the project to non windows platform (based on `Mono` don't support duplex channel ever , and that's why `Xamarin` too.). But after I changing my project, I found the thing is not that simple. There is no reliability for callback that server push to client.

Some people said, server call will not block you're client..... yeah yeah yeah!   It's amazing,  but it's ok to me even it will blocking. I'm not use it for browser, I could make a new thread to my UWP,  WPF, Winform,  even Android or iOS to handle if it blocked . 

I just need catch these callback that not successfully send finish to client, and put it to the server cache, Send them when next time the client available.  You all know phones: **user could be switching between other App, there is no any possible that we keep connecting**. Actually we just keep lose and connect.

So how do we do in that case?  Is there any possible you guys change callback design? **make it to waiteble?** If time out just throw some exception for us, let us know this message not send successfully, and we could save it to server for a while (until some user switch back the phone if not too long).  Also could make sure there is no any callback missing? If too long we could let user relogin and get only new data from data base.

such like you making **a new additional feature** that hold currently callback when it executed, if there is no any response (like client said: callback not got it, or callback has exception when client execute, or no response for this callback maybe not exist or maybe lost), just throw exception to us?  and if client said that's fine, and you no longer hold it, just return the result? (such like doing a middle job between server and client again for callback)

**Comment by davidfowl** [comment]
We're not adding any new features to this version of SignalR. See https://devblogs.microsoft.com/aspnet/the-future-of-asp-net-signalr/ for more details.

**Comment by huangjinshe** [comment]
@davidfowl , @BrennanConroy , Hi guys, sorry for interrupt. Is this in the FP now? you know already 2 years. I don't know do we have a new feature to know the client is disconnected when send data.(at least we don't need to check it by ourselves with making extra connection)

**Comment by davidfowl** [comment]
Not sure what you mean? What exactly are you asking? If there's a new feature in this version of SignalR or the new version?

**Comment by huangjinshe** [comment]
@davidfowl I'm asking about "reliable callback". 2 years ago if we push notification (callback), if the connection disconnected or time out will not give us any alert, server still can push callback to client withou any Exception. I hope we could know if client did not send successfully. that's the feature which I mention. like WCF duplex channel, at least let us know if currently can't send callback to the client (no matter time out or what).

**Comment by davidfowl** [comment]
I replied 2 years ago saying that we aren't adding any new features to this version of SignalR.

**Comment by huangjinshe** [comment]
@davidfowl That's really great!
