### ISSUE TITLE
Decrease SignalR per Message Size to Preserve Bandwidth

### ISSUE THREAD

**Issue by investagrams** [SignalR/SignalR#4456]
We have just observed that when signalR push the message and received in the web client side, there is an excess information (Please see below).  Is there a way to remove the C part or minimize or optimize or compress this data, since this consumes around 250 bytes per message. And our real data is in the H, M and A.

We badly need to decrease the bandwidth.

C: "d-8A08EDFB-F,0|W5s,0|ERo,0|B,0|W5t,0|ERq,0|V,0|W5u,0|ERs,0|K,0|W5v,0|ERu,0|W5w,21|Cd,7|GF,25C|Ch,10|Dv,1A|BNT,0|Cr,3D9|IA,5D|Cm,1C|Sn,19|Cp,56|Cw,EB|Cx,D5|GK,B|Cy,5D|Cz,1B|C0,154|WF,22|XN,11B|3Y,3|C2,7|C3,8D|Fs,11E|C4,39|C5,1B|Ft,10|FRA,2|EqH,0|EqD,0"

![image](https://user-images.githubusercontent.com/8090574/78092292-fefcef80-7401-11ea-909d-7b3b7f02196c.png)

**Comment by davidfowl** [comment]
There are no plans to invest in this level of feature with SignalR. The cursor is a representation of the what signals the client is subscribed to and how far they are within that signal. Is this client a member of lots of groups?

**Comment by investagrams** [comment]
Yes this client is a member of some groups (around 4-5 initially but a lot of joining / leaving groups happening while the user interacts with our website).

**Comment by BrennanConroy** [comment]
Closing as there isn't any work here.
