### ISSUE TITLE
NullReferenceException at Microsoft.AspNet.SignalR.Client/Connection.cs 724 row

### ISSUE THREAD

**Issue by raV720** [SignalR/SignalR#4458]
Sometimes calling Microsoft.AspNet.SignalR.Client.Connection.Stop(TimeSpan timeout) results in NullReferenceException at Microsoft.AspNet.SignalR.Client/Connection.cs 724 row: https://github.com/SignalR/SignalR/blob/9ab6410822b6a877590ded2e5185b3ad3ade4932/src/Microsoft.AspNet.SignalR.Client/Connection.cs#L724
I guess the Monitor should be checked against null like in:
https://github.com/SignalR/SignalR/blob/9ab6410822b6a877590ded2e5185b3ad3ade4932/src/Microsoft.AspNet.SignalR.Client/Connection.cs#L759

**Comment by davidfowl** [comment]
Yes this looks like a bug.

**Comment by tcerdaj** [comment]
Any status about this bug? Thanks.

**Comment by halter73** [comment]
`Disconnect()` also null-checks `_transport`, so if we're going to null-check `Monitor` in `Stop()` we should null-check `_transport` as well.
