### ISSUE TITLE
Adding window "load" handler via JQuery breaks SignalR

### ISSUE THREAD

**Issue by alex-jitbit** [SignalR/SignalR#4461]
Add this line to a page containing SignalR:

`<script> $(window).on("load", function () { console.log("test") })</script>`

SignalR stops working.

Change it to

`<script> window.addEventListener('load', function () { console.log("test") })</script>`

It works again.

UPDATE: in my page, this line is above the two Signalr javascripts ("jquery.signalR-2.4.1.min.js"and "signalr-hubs"), both are loaded with defer

**Comment by BrennanConroy** [comment]
This isn't something we will be able to change at this point. Your workaround looks good, another workaround would be to call `start({ waitForPageLoad: false })`.
