### ISSUE TITLE
net framwork 4.0   winfrom Can  connect   Microsoft.AspNetCore.SignalR.Client?

### ISSUE THREAD

**Issue by dengyantao** [SignalR/SignalR#4463]
net framwork 4.0 Can  connect   Microsoft.AspNetCore.SignalR.Client?

net framwork 4.6.1 Can  connect

**Comment by dengyantao** [comment]
![image](https://user-images.githubusercontent.com/7434747/79103593-79812400-7d9f-11ea-8b9f-88f39c90b2e9.png)

**Comment by dengyantao** [comment]
net framwork 4.6.1 Can connect
![image](https://user-images.githubusercontent.com/7434747/79103792-d54bad00-7d9f-11ea-95a8-1256e4ccca57.png)

**Comment by davidfowl** [comment]
We don't support .NET Framework 4.0 (it's been out of support for a long time).
