### ISSUE TITLE
Error 500 when using AspNet.SignalR.Client on .NET Winforms and a server with AspNetCore.SignalR

### ISSUE THREAD

**Issue by DjeblounSidali** [SignalR/SignalR#4466]
### Code used on my .NET Winforms app
The code below work fine when starting the server using AspNet.SignalR. 2.4.1 
But when starting the server using AspNetCore.SignalR on ASP.NET Core 3.1.2 with the same class "ChatHub" and same url a got the error 

```
_signalRConnection = new HubConnection("http://localhost:5001/chatHub");
_hubProxy = _signalRConnection.CreateHubProxy("ChatHub");
_hubProxy.On<string, string>("ReceiveMessage", (user, message) => writeToLog($"{user}:{message}"));
await _signalRConnection.Start(); ==> Error is thrown here
```

### Expected  behavior
Connect to the server

### Actual behavior
Error:StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.StreamContent, Headers: 
  { 
  Transfer-Encoding: chunked 
  Date: Wed, 29 Apr 2020 11:19:44 GMT 
  Server: Microsoft-IIS/10.0 X-Powered-By: ASP.NET  
  Content-Type: text/plain 
}

**Comment by BrennanConroy** [comment]
ASP.NET SignalR and ASP.NET Core SignalR are not compatible.

**Comment by DjeblounSidali** [comment]
Ok, In my case I have an AspNetCore.SignalR server and an old winform application that I have to connect to my soket server, is there a way to do it ?

**Comment by BrennanConroy** [comment]
Your winform application would need to be using the ASP.NET Core SignalR client.

**Comment by DjeblounSidali** [comment]
it work fine, thanks BrennanConroy.
