### ISSUE TITLE
Return Multiple Data from Different Hub in One Cursor Response

### ISSUE THREAD

**Issue by investagrams** [SignalR/SignalR#4468]
How to force return multiple data from different hubs in one cursor response? Just like this: 

We don't know how to set this but sometimes we see this combined response. We want to our response to be like this always. This minimize the bandwidth needed since only 1 cursor will be used and there are multiple data already.

![image](https://user-images.githubusercontent.com/8090574/81067878-f96b5b80-8f11-11ea-99b7-93ed8a4dd1aa.png)

**Comment by BrennanConroy** [comment]
This isn't something you can control and we aren't investing in any major changes in ASP.NET SignalR anymore. (You could use LongPolling with a longer polling delay, but that add a lot of latency)

You could take a look at migrating to ASP.NET Core SignalR which doesn't have cursors, and has an option to use a binary protocol for your messages.
