### ISSUE TITLE
Old packages license links are broken.

### ISSUE THREAD

**Issue by jeme** [SignalR/SignalR#4472]
Hello, we are using an old nuget package related to SignalR: https://www.nuget.org/packages/Microsoft.AspNet.SignalR.Owin/1.2.2

However, the license link on nuget is broken: https://www.microsoft.com/web/webpi/eula/signalr_rtw.htm

Can anyone point us to the correct URL for a license text for this package?

### Expected  behavior
Link works.

### Actual behavior
Link is broken.

### Steps to reproduce
Click link.

**Comment by halter73** [comment]
Thanks for the report. It seems that https://www.microsoft.com/web/webpi/eula/signalr_rtw.htm is working again.
