### ISSUE TITLE
Null Ref exception in dispose

### ISSUE THREAD

**Issue by gauravsaralMs** [SignalR/SignalR#4474]
Issues related to the Asp.NET Core version of SignalR should be filed in the AspNetCore repo: https://github.com/aspnet/AspNetCore/issues/new/choose
Please remove this line and the line above before submitting a new issue.

### Steps to reproduce
sometime (not consistent) we are seeing null ref crash in dispose

Stack Trace:
0000003c`eccbdeb0 00007ffe`f9b33ea0 System!System.Diagnostics.PerformanceCounter.Decrement+0x50
0000003c`eccbdee0 00007ffe`f9901d90 Microsoft_AspNet_SignalR_Core!Microsoft.AspNet.SignalR.Messaging.Subscription.Dispose+0x70
0000003c`eccbdf20 00007ffe`f9901ea0 Microsoft_AspNet_SignalR_Core!Microsoft.AspNet.SignalR.Messaging.MessageBus.DisposeSubscription+0x80
0000003c`eccbdfa0 00007ffe`f98fef6e Microsoft_AspNet_SignalR_Core!Microsoft.AspNet.SignalR.Infrastructure.DisposableAction.Dispose+0xae
0000003c`eccbdff0 00007ffe`f9952f74 Microsoft_AspNet_SignalR_Core!Microsoft.AspNet.SignalR.Infrastructure.Disposer.Dispose+0x64
0000003c`eccbe020 00007ffe`f9904381 Microsoft_AspNet_SignalR_Core!Microsoft.AspNet.SignalR.Infrastructure.CancellationTokenExtensions+CancellationCallbackWrapper.TryInvoke+0x31
0000003c`eccbe050 00007ffe`f990432d Microsoft_AspNet_SignalR_Core!Microsoft.AspNet.SignalR.Infrastructure.CancellationTokenExtensions+__c._SafeRegister_b__2_0+0x2d
0000003c`eccbe080 00007fff`50c44a96 mscorlib_ni!System.Threading.CancellationCallbackInfo.ExecuteCallback+0x66
0000003c`eccbe0d0 00007fff`50c4489b mscorlib_ni!System.Threading.CancellationTokenSource.ExecuteCallbackHandlers+0x1cb

**Comment by BrennanConroy** [comment]
This project is in maintenance mode and we only have resources for critical issues. If you have a reliable repro for this issue we might be able to take a look.
