### ISSUE TITLE
ASP.NET SignalR JavaScript Library version number in hubs.js

### ISSUE THREAD

**Issue by Staminah** [SignalR/SignalR#4476]
Hi, 

Would it be possible to update version number indicated in the line `ASP.NET SignalR JavaScript Library v2.3.0-rtm` to `v2.4.1` in the following file : [https://github.com/SignalR/SignalR/blob/2.4.1/src/Microsoft.AspNet.SignalR.Core/Scripts/hubs.js](url)

Because of this, some tools that analyzes the code detects this and indicates that the version used of SignalR is not up to date.

### Expected  behavior
The version number specified in the header comment is matching with the current branch tag (2.4.1).

### Actual behavior
The version number specified in the header comment is not matching with the current branch tag.

### Steps to reproduce
--

Thanks in advance.

Best regards

**Comment by BrennanConroy** [comment]
@halter73

**Comment by yguerdat** [comment]
Hello @BrennanConroy 

Do you have any plan for the next release ? We need to inform our customer because the wrong version's number generated create an issue in the security report of our partner. 

Thanks for your feedback and have a nice day

**Comment by BrennanConroy** [comment]
I don't have a timeline for the next release sorry. But this will be fixed in 2.4.2

Fixed by https://github.com/SignalR/SignalR/pull/4477
