### ISSUE TITLE
Upgrade to Stackexchange.Redis 2.0

### ISSUE THREAD

**Issue by jonnybee** [SignalR/SignalR#4478]
Package Microsoft.AspNet.SignalR.Redis should upgrade to Stackexchange.Redis v2.0 as other Microsoft packages has already done such as Microsoft.Web.RedisOutputCacheProvider and Microsoft.Web.RedisSessionStateProvider. We are unable to upgrade to use the new features until all packages that we use have the same dependencies to StackExchange.Redis. 

StackExchange.Redis.Strongname has been deprecated and StackExchange.Redis v2.0 is now strongnamed by default.

From ReleaseNotes for StackExchange.Redis:

> 2.0.495
>2.0 is a large - and breaking - change
>The key focus of this release is stability and reliability.
>
>HARD BREAK: the package identity has changed; instead of StackExchange.Redis (not strong-named) and StackExchange.Redis.StrongName (strong-named), we are now only releasing StackExchange.Redis (strong-named). This is a binary breaking change that requires consumers to be re-compiled; it cannot be applied via binding-redirects

**Comment by BrennanConroy** [comment]
This has already been done https://www.nuget.org/packages/Microsoft.AspNet.SignalR.StackExchangeRedis/
