### ISSUE TITLE
Human In Loop Approach

### ISSUE THREAD

**Issue by sposaro** [SignalR/SignalR#4479]
[Problem Statement]
 We need help in identifying a possible recommendation for one of the solutions we are designing as part of the Chatbot Offerings.

We have developed a Human In Loop scenario for the chatbot where the conversation will be handed over to a human in case the Bot is not able to answer properly. This is custom developed logic and is a hosted middleware. We are now working on a new method to connect the SignalR directly to the Bot core from the current approach avoiding the middleware.

Can anyone comment / validate on the approach we are taking for connecting directly to the Bot core or if there is anything Microsoft has already released which we are unaware of.

We were able to find some info about this but not on a full scale. reference link
https://docs.microsoft.com/en-us/healthbot/handoff

[Why solve it?]
Helps avoid the middleware limitations

[Definition of done]
Confirmation of the steps we are initiating for the approach or if Microsoft has a predefined approach for connecting the SignalR directly to the Bot Core as part of the Azure Bot services we can leverage that.

**Comment by BrennanConroy** [comment]
Hi. It looks like this is a question about how to use SignalR. This repo is in maintenance mode and we only have the resources to fix major issues, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com/).
