### ISSUE TITLE
Long polling transport and scale out generates bogus OnDisconnected() calls on server v2.4.1

### ISSUE THREAD

**Issue by GMacAussie** [SignalR/SignalR#4480]
### Expected  behavior
The OnDisconnected() server call is only made once per connection id when the connection is lost.

### Actual behavior
The OnDisconnected() server call is made 30-40 seconds after establishing a new browser tab connection.

Note that the browser tab is still connected with SignalR (it receives subsequent push notifications).

### Steps to reproduce
* Start a Azure app service (self hosted SignalR) with 2 instances
* Connect via a browser client with long polling. Note OnConnected() called on server for connection
* Note OnDisconnected() on server called for connection 30-40 seconds later

### Further technical details
.NET Framework 4.7.2
Microsoft.AspNet.SignalR v2.4.1
Microsoft.AspNet.SignalR.Core v2.4.1
Microsoft.AspNet.SignalR.JS v2.4.1
Microsoft.AspNet.SignalR.Owin v1.2.2
Microsoft.AspNet.SignalR.Redis v2.4.1
Microsoft.AspNet.SignalR.SystemWeb v2.4.1

* Using Azure Cache for Redis Basic and Standard (no clusters, which only comes with Premium).
* Long polling is being used as we are using Bearer token authentication and have not pushed the token into the query string. In production we also use sessions (with a Redis backplane) and that allows web sockets to work.
* When using a single server instance we have no issues.
* The affinity flag is OFF and we are running 2 server instances in self-hosted SignalR on Azure web services. Even though the SignalR documentation mentions that affinity is not required for SignalR (though it is for Core), when the affinity flag is ON this WORKED as expected - that is, no premature OnDisconnected() was fired. Unfortunately (!) we are using Traffic Manager in production so the affinity flag flip was only for testing purposes.
* We are using the SignalR Redis backplane, but is unclear whether this is in the way. We do run a 2 instance Azure web service in production but the connections use web sockets and it mostly works fine (we have seen a few intermittent disconnects there as well, though we cannot reproduce those).

Additional testing:

* We logged the OnConnected()/OnDisconnected() sequence and found that the server firing the OnDisconnected() call was USUALLY the server that OnConnected() was NOT CALLED against. The SignalR transport/bus logs do not seem to log the server instance however. In addition, even after the initial disconnect, we received further disconnects for the same connection id, usually 3-8 minutes apart, and on both servers.
* We tried GlobalHost.Configuration.KeepAlive = null, no effect.
* We tried GlobalHost.Configuration.LongPollDelay = TimeSpan.FromMilliseconds(5000) and TimeSpan.FromMilliseconds(30000). This worked twice out of about a dozen attempts, but even then we still disconnected a few minutes later, not after 30-40 seconds.
* We looked at using ITransportHeartbeat in the OnConnected()/OnDisconnected() callbacks but we don't see the entry for the browser connection. We suspect it has either not been added yet (OnConnected()) or already cleaned up (OnDisconnected())
* We have switched on SignalR diagnostics, but it is a bit thin gruel. Apart from not having timestamps in the text log, it does not reflect any server source. Attached find a snippet from the transport log when it detects the the new browser tab (which is connection id e7b2306c-c3af-4334-96ab-350e98a09455) showing dead detection and connection new message.

Our suspicion is that the long polling is not multi-instance aware and is causing connection confusion between the servers.

Any suggestions/help would be appreciated.

[transport.log](https://github.com/SignalR/SignalR/files/4860253/transport.log)

**Comment by GMacAussie** [comment]
**Update**

We have no solution for long polling for this, and given our delivery timeframes we instead looked to enable WebSockets (and as it turns out ServerSendEvents) as available when using bearer tokens.

The issue is that we needed to modify the Owin pipeline for our bearer token handler to manage the `access_token` being passed in the (WebSockets/ServerSendEvents) URL parameters. This is what we did:

In our bearer token registration handler:

```CSharp
// wire Jwt authentication for tenant
app.UseOAuthBearerAuthentication(new OAuthBearerAuthenticationOptions {
    // the security token provider handles JWE metadata, signing keys and encryption key
    AccessTokenFormat = jwtFormat,
    Provider = new OAuthBearerAuthenticationProvider() {
        OnRequestToken = async (context) => await OAuthRequestToken(context).ConfigureAwait(false),
        OnValidateIdentity = async (context) => await OAuthValidateIdentity(context).ConfigureAwait(false)
    }
});
```

and added the following method:

```CSharp
private Task OAuthRequestToken(OAuthRequestTokenContext context) {
    // check if this is for SignalR
    if (context.Request.Path.Value.StartsWith("/signalr")) {
        // retrieve the bearer token
        string token = context.Request.Query.Get("access_token");

        if (!string.IsNullOrWhiteSpace(token)) {
            // contrary to documentation, this will correctly cause the token to be validated and SignalR will
            // have the request principal set
            context.Token = token;
        }
    }

    return Task.FromResult<object>(null);
}
```

*Note setting the context.Token!* Some hints in these forums and on the web suggest setting the request `Authorization` header (`"Bearer <token>"`), but this will NOT entirely work. What we found was that even through the token was validated (successfully), the SignalR request did NOT have the principal (request.User) set (making this kind of useless). Setting the Token directly allows the principal to be set in the SignalR request.

**Comment by halter73** [comment]
Unfortunately, this is by design. With scale out, it's not possible for SignalR to efficiently determine if long polling clients disconnected ungracefully, or just polled to another server. Using sticky sessions will prevent this problem. It's also guaranteed that OnDisconnected will be called at most once per connection if `stopCalled` is true. See https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/handling-connection-lifetime-events#detecting-the-reason-for-a-disconnection
