### ISSUE TITLE
How to Add WebSocket Header "Sec-WebSocket-Protocol" Before Start Connection in js/ts file?

### ISSUE THREAD

**Issue by xingwen1987** [SignalR/SignalR#4482]
How to Add WebSocket Header "Sec-WebSocket-Protocol" Before Start Connection in Signalr.js？

**Comment by halter73** [comment]
SignalR doesn't have an extensibility point and we're not adding new features to this version of SignalR. It looks like this can be configured via the WebSocket constructor's optional `protocols` parameter, but it would require modifying the SignalR JS client change this.
