### ISSUE TITLE
Usage In Vue Js

### ISSUE THREAD

**Issue by yehtut-indexzero** [SignalR/SignalR#4483]
Hi Everyone,

How to call SignalR in Vue Js? I am developing desktop application using Electron with Vue Cli and in my application, I have to call SignalR. Thank you.

Have a nice day !

**Comment by RobQuatela** [comment]
Hey,

How we currently use SignalR in our Vue project, is that we will  create a "signalr.js" file where you can create the methods needed to establish a connection, call direct server methods, as well as registering methods for server side push events.

From there, you can export those methods to any Vue component or within the Vuex store. 

In this example below, this would be a SignalR file that contains methods to connect (that you can add to any component that you want to start the connection within the component life cycle or methods.). As well as even dispatching store actions from a server push event.

`import * as signalR from '@aspnet/signalr';
import {store} from './store';

let connection;

export const createConnection = (token) => {
  connection = new signalR.HubConnectionBuilder()
    .withUrl(`${process.env.VUE_APP_API}/hubs`, {
      accessTokenFactory: () => token,
    })
    .build();
};

export const start = () => {

  connection.start()
    .then(() => {
       console.log('connected');
    })
    .catch(err => {
      console.log(err);
};

export const disconnect = () => {
  if (connection) {
    connection.stop();
  }
};

export const onCloseConnection = () => {
  connection.onclose(() => {
    console.log('disconnected');
};`

export const onMessageReceived = () => {
  connection.on('MessageReceived', (data) => {
    store.dispatch('addTomessages', data);
  });
};

**Comment by cdecinkoKnight** [comment]
@RobQuatela it appears you are using the .NET Core version of the client. Is this able to connect to a hub in .NET Framework 4.7?

**Comment by BrennanConroy** [comment]
This seems more like a question for stackoverflow, consider posting there if you need help.
