### ISSUE TITLE
No way to do polymorphic de-serialization of SignalR method parameters

### ISSUE THREAD

**Issue by artakhak** [SignalR/SignalR#4488]
I have a server HUB method that I call from client code that has a parameter animals of type List<Animal>. The client (Angular/Typescript project), sends a JSON array of objects that are supposed to be de-serialized to an instances of Dog, Cat (or Animal, if Json object is Animal in client code).
However, the list always has objects of type of base class Animal (see the method below). You cannot convert individual items in animals parameter to Catd, Dog, etc.

public void CallThisFmClient(List<Animal> animals) {...}

The issue is in method ConvertTo() in Microsoft.AspNet.SignalR.Json.JRawValue class. The method uses a static method to get an instance of JsonSerializer, therefore no matter how we setup the JsonSerializer in web application startup method, it is ignored when the parameters are de-serialized (see the copy of the method below. 

This is a huge limitation, and would be nice if it is addressed soon. 

        public object ConvertTo(Type type)
        {
            // A non generic implementation of ToObject<T> on JToken
            using (var jsonReader = new StringReader(_value))
            {
                var serializer = JsonUtility.CreateDefaultSerializer();
                return serializer.Deserialize(jsonReader, type);
            }
        }

**Comment by gds03** [comment]
anyone?
