### ISSUE TITLE
signalr cross-domain http 403 error

### ISSUE THREAD

**Issue by MrLBQ** [SignalR/SignalR#4491]
signalr 跨域解决后访问/chatHub/negotiate，报错 403，请求大神的救助！
After cross domain resolution, the signalr accesses / chathub / negotiate and reports an error of 403, asking for the help of the great God!
POST http://**:10086/chatHub/negotiate 403 (Forbidden)

**Comment by BrennanConroy** [comment]
Looks like a general question about using SignalR. Consider posting a question on [StackOverflow](https://stackoverflow.com).
