### ISSUE TITLE
Hub.OnDisconnectedAsync is not called if error inside Hub.OnConnectedAsync happens

### ISSUE THREAD

**Issue by Tommigun1980** [SignalR/SignalR#4495]
Hi.

If an exception is thrown inside Hub.OnConnectedAsync, Hub.OnDisconnectedAsync is not called.

C# .NET Core's client's Closed callback is invoked with the exception and the server connection's state is in HubConnectionState.Disconnected so the client works properly. Only problem is that the server never gets a call to OnDisconnectedAsync in this case.

I have for now resorted to manually try catch errors inside OnConnectedAsync and call cleanup manually until this is resolved.

Thanks.

**Comment by BrennanConroy** [comment]
This issue should be filed in dotnet/aspnetcore.

If OnConnectedAsync throws then we don't consider the connection "connected" so OnDisconnectedAsync wont run. Since it is your code in OnConnectedAsync then you'll need to handle any errors and state management.

**Comment by Tommigun1980** [comment]
> This issue should be filed in dotnet/aspnetcore.
> 
> If OnConnectedAsync throws then we don't consider the connection "connected" so OnDisconnectedAsync wont run. Since it is your code in OnConnectedAsync then you'll need to handle any errors and state management.

Thank you, I’ll file it there. But the client IS disconnected if this happens, the server just isn’t notified with OnDisconnectedAsync. Either the client shouldn’t be disconnected OR the server should get a call to OnDisconnectedAsync, as right now the client just gets disconnected without the server knowing about it.

**Comment by BrennanConroy** [comment]
We don't consider the client ever connected in that case, because YOU threw from OnConnectedAsync, the client is only fully connected if OnConnectedAsync completes successfully.

**Comment by Tommigun1980** [comment]
That's a bit weird. If you call something in OnConnectedAsync that throws
an exception, and the client is disconnected, one could assume you should
get a call to OnDisconnectedAsync. I don't care how the client got
disconnected (a third-party library threw an error), I just need to know of
it.
