### ISSUE TITLE
Azure WAF blocking SingalR request by azure front door and detect it as an XSS attack

### ISSUE THREAD

**Issue by kaa-cl** [SignalR/SignalR#4499]
We have several web apps behind the azure front door, we configured a WAF policy for the azure front door.
WAF policy blocks the SIgnal R request and detects it as an XSS.

WAF policy name  : DefaultRuleSet-1.0-SQLI-942340
This ruleset is blocking a request.
The detailed message for detection is: Detects basic SQL authentication bypass attempts 3/3.

I think this is a false positive but I don't know how to tune my WAF/ASP.Net code to prevent this false positive.

**Comment by cannehag** [comment]
Same here. We have multiple different blocks related to SignalR:
XSS Filter - Category 2: Event Handler Vector
SQL Hex   Encoding Identified
Detects basic SQL authentication bypass attempts 3/3

**Comment by halter73** [comment]
> The detailed message for detection is: Detects basic SQL authentication bypass attempts

That's definitely not what SignalR is doing. Isn't this an issue with the WAF policy?
