### ISSUE TITLE
SignalR losing connection every 5 minutes (Kubernetes)

### ISSUE THREAD

**Issue by DinoSourcesRex** [SignalR/SignalR#4502]
### Expected  behavior
SignalR should not disconnect every 5 minutes

### Actual behavior
SignalR is disconnecting every 5 minutes

### Steps to reproduce
I can only describe the scenario here, really.

The application is an angular application being served by an nginx server from Kubernetes.

The SignalR server is a dotnet core application also on Kubernetes.

[This ](https://quay.io/repository/kubernetes-ingress-controller/nginx-ingress-controller?tag=0.32.0&tab=tags)ingress is being used.

The flow is the following:

Ingress -> Service -> Multiple SignalR nodes.

When I port-forward directly to a single node the connection is stable so it's something misconfigured in the first two stages.

I have tried multiple things including the instructions [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?view=aspnetcore-3.1#kubernetes).

The current config is attached with some stuff renamed.

[deployment.yml.txt](https://github.com/SignalR/SignalR/files/5192132/deployment.yml.txt)
[ingress.yml.txt](https://github.com/SignalR/SignalR/files/5192133/ingress.yml.txt)
[service.yml.txt](https://github.com/SignalR/SignalR/files/5192134/service.yml.txt)
[cert.yml.txt](https://github.com/SignalR/SignalR/files/5192135/cert.yml.txt)

**Comment by davidfowl** [comment]
A couple of questions:

- 5 minutes is an interesting number, did you configure any of the timeouts on the server or client side? 
- Do you have any logs when the client or server disconnects?

**Comment by DinoSourcesRex** [comment]
As far as I am aware there are no configurations on this timeout. As mentioned connecting directly to the pod / working locally there are no issues whatsoever. This leads me to believe there's something up with the kubernetes configuration. As far as I am aware there are no custom configuration applied to the nginx beyond this. I will speak to the person who manages this to verify this is the case again.

I have looked through the logs which are currently logging at Information level (I can increase this and test again later on in the day to see if there are some more logs for this scenario).

The only frontend log I have to give you is:

```
SignalR has disconnected because of 1006 and will reconnect silently! Error: WebSocket closed with status code: 1006 ().
    at t.close (main.e5ba4c25028c4aa89012.js:1)
    at WebSocket.o.onclose [as __zone_symbol__ON_PROPERTYclose] (main.e5ba4c25028c4aa89012.js:1)
    at WebSocket.T (polyfills.ab565d4603c29221e94a.js:1)
    at e.invokeTask (polyfills.ab565d4603c29221e94a.js:1)
    at Object.onInvokeTask (main.e5ba4c25028c4aa89012.js:1)
    at e.invokeTask (polyfills.ab565d4603c29221e94a.js:1)
    at t.runTask (polyfills.ab565d4603c29221e94a.js:1)
    at t.invokeTask [as invoke] (polyfills.ab565d4603c29221e94a.js:1)
    at f (polyfills.ab565d4603c29221e94a.js:1)
    at WebSocket.h (polyfills.ab565d4603c29221e94a.js:1)
```

I actually catch the error specifically and silently reconnect at the moment so the user doesn't suffer too much - I just really want to avoid having to do that.

**Comment by DinoSourcesRex** [comment]
Ah somehow I've opened this in the wrong place again. This is using signalr core! My apologise. Really not sure how I managed to open the issue on the wrong tab haha.
