### ISSUE TITLE
SignalR working with clustered Redis starting in 5.0.x?

### ISSUE THREAD

**Issue by JohnHellyer-Cherwell** [SignalR/SignalR#4503]
Redis 5.0 change the default behavior of how scripts are evaluated.  See Selective replication of commands under EVAL function [Eval](https://redis.io/commands/eval). The quick description is Redis used to replicate scripts out to each node to run and keep them all in sync. In 5.0 the default behavior is the results of scripts are sent to each node.  

When using a Redis 4.0.X cluster I would get the duplicate message issue raised in issues #3721 and #3765. After upgrading to Redis 5.0 this problem went away and my application is working as expected. To prove this Redis change was the root cause, I flipped the lua-replicate-commands setting so the cluster replicated scripts as it did before in 4.0.x. As soon as I did this the duplicate messages came back.

The comment from @moozzyk  in #3765 suggests the replication of the scripts between nodes is the reason SignalR can't be used with a Redis cluster. Now that this is no longer the case, is it safe to say that SignlarR support Redis Clusters as of version 5.0?

**Comment by BrennanConroy** [comment]
> is it safe to say that SignlarR support Redis Clusters as of version 5.0?

If it works great, but we aren't going to explicitly support it. This repo is in maintenance mode and no new features will be worked on.
