### ISSUE TITLE
Server has two hubs, but JS client subscribed to only one hub

### ISSUE THREAD

**Issue by golamkibria** [SignalR/SignalR#4504]
Our backend server is ASP.NET MVC 4.5. Frontend is a angular 9 application. We are using this npm package.  There are two hubs in the server but the angular client subscribes to only one hub. 
We have enable the logging to see the log messages. We see only one subscribing message:
  _SignalR: Client subscribed to hub 'notificationshub'._
We have another hub 'bgJobHub'. We do not see any subscribe log message for this hub.

### Expected  behavior
angular client should receive messages from both the hub.
### Actual behavior
angular client receives message from the 'notificationshub' only. And do not receive any message from 'bgJobHub' hub.

We are using the attached service to create hub proxy for the mentioned hubs.
[signalR.service.ts.txt](https://github.com/SignalR/SignalR/files/5306914/signalR.service.ts.txt)

**Comment by halter73** [comment]
It looks like you running into the issue described in https://docs.microsoft.com/en-us/aspnet/signalr/overview/testing-and-debugging/troubleshooting#connection-started-before-subscriptions-are-added where the hub is configured after the hub connection started. The link describes workarounds. If you have further questions, I recommend submitting them to stackoverflow.com.

**Comment by golamkibria** [comment]
You are correct, we were starting the connection on first subscription; We discover it later and fixed out code, though we did not have the MS doc reference that you have mentioned. However, thank you for the troubleshooting reference.
