### ISSUE TITLE
Signalr on subdomain problem

### ISSUE THREAD

**Issue by msatin011** [SignalR/SignalR#4506]
I was using JavaScript signalr client without problems until I changes to subdomain.
My connection_url was : https://domainname.net:811/Signalr/ContadoresHub     (functioning on port 811 without problemas)
On c# Signalr Server I have 👍   _runningInstance = WebApp.Start(urlServer);    when urlServer is https://*:811

now my connection_url is https://subdomain.domainname.net:811/Signalr/ContadoresHub

and can not connect without any error on console
Any special consideration working on subdomains ???

**Comment by BrennanConroy** [comment]
Hi. It looks like this is a question about how to use SignalR. This repo is in maintenance mode and we only have the resources to fix major issues, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com/).
