### ISSUE TITLE
SingalR PONG frame every 30seconds 

### ISSUE THREAD

**Issue by saraheem** [SignalR/SignalR#4507]
### Expected  behavior
SignalR seems to be generating a PONG frame every 30seconds, modifying the KeepAlive to anything above 60seconds doesn’t seem to change the behaviour of the PONG interval.
Inspecting traffic using wire shark confirms this behaviour.
 
I need the ability to control this behaviour  for an IoT use which is battery operated, pong every 30seconds adversely impacts battery performance.

### Actual behavior
Set disconnecttimeout to 360secs, KeepAlive to 120secs. SignalR keeps sending a PONG frame every 30seconds 

### Steps to reproduce

Set disconnecttimeout to 360secs, KeepAlive to 120secs. SignalR keeps sending a PONG frame every 30seconds 

Use wire shark for monitoring network traffic.

**Comment by halter73** [comment]
The ping you're looking at is different from the keep-alive pings. That is a JS-client specific `/ping` request to keep ASP.NET	sessions alive (so it can refresh cookies and stuff like that). This can be configured via the JS client by setting the `pingInteval` on the config passed to hub.start(config). See https://stackoverflow.com/questions/25597468/use-of-signalr-ping-call-when-using-long-polling
