### ISSUE TITLE
How correctly use with Next.js

### ISSUE THREAD

**Issue by pavelvondrasek** [SignalR/SignalR#4509]
Hi,

I've backend in ASP.NET Core 3.1 and on the frontend I've Next.js 10.

I create hub in useEffect which is called only once (is memoized by []):

```ts
  useEffect(() => {
    if (props.node?.permission.canEdit) {
      const connection = new signalR.HubConnectionBuilder()
        .withUrl(`${process.env.BACKEND_URL}/api/node-hub?node=${props.node.id}`)
        .withAutomaticReconnect()
        .build();
    }
  }, []);
```

But in console I see multiple (mostly two) negotiation requests and successful connections. Is it ok?

Every with new `connectionId` and `token`.

Did I something wrong?

Thanks for you reploy and hints!
Pavel

**Comment by BrennanConroy** [comment]
This issue was moved to dotnet/aspnetcore#27781
