### ISSUE TITLE
how to automaticReconnect hubconnection signalR client in java

### ISSUE THREAD

**Issue by MeysamMoghaddam** [SignalR/SignalR#4510]
Hi
I have java project and use signalR client.
how to automaticReconnect hubconnection signalR client in java
I want to auto reconnect my connection.
this feature is available in some platforms such as js,blazor-client but not in java
can you help me?

**Comment by BrennanConroy** [comment]
This is the wrong repo for ASP.NET Core SignalR.

Automatic reconnection for the java client is being tracked by https://github.com/dotnet/aspnetcore/issues/8711
