### ISSUE TITLE
.js Client shows stop event on log but never calls disconnected event

### ISSUE THREAD

**Issue by larryolocke** [SignalR/SignalR#4511]
Issues related to the Asp.NET Core version of SignalR should be filed in the AspNetCore repo: https://github.com/aspnet/AspNetCore/issues/new/choose
Please remove this line and the line above before submitting a new issue.

### Expected  behavior
Upon hitting an error and rising "SignalR: Stopping connection" SignalR should raise OnDisconnected "disconnected"
### Actual behavior
SignalR hits a timeout error and rasies "Stopping connection" OnDisconnected is not raised and the next event raised is Negotiating with '/signalr/negotiate

Logs:
`.
jquery.signalR-2.4.1.js:86 [09:28:23 GMT-0600 (Central Standard Time)] SignalR: Received an error message from the server: Connection ping timeout.
jquery.signalR-2.4.1.js:86 [09:28:23 GMT-0600 (Central Standard Time)] SignalR: Stopping connection.
jquery.signalR-2.4.1.js:86 [09:28:23 GMT-0600 (Central Standard Time)] SignalR: Closing the Websocket.
jquery.signalR-2.4.1.js:86 [09:28:23 GMT-0600 (Central Standard Time)] SignalR: Stopping the monitoring of the keep alive.
jquery.signalR-2.4.1.js:86 [09:28:28 GMT-0600 (Central Standard Time)] SignalR: Client subscribed to hub 'apparatushub'.
jquery.signalR-2.4.1.js:86 [09:28:28 GMT-0600 (Central Standard Time)] SignalR: Client subscribed to hub 'bulletinboardhub'.
jquery.signalR-2.4.1.js:86 [09:28:28 GMT-0600 (Central Standard Time)] SignalR: Client subscribed to hub 'dashboardhub'.
jquery.signalR-2.4.1.js:86 [09:28:28 GMT-0600 (Central Standard Time)] SignalR: Client subscribed to hub 'incidenthub'.
jquery.signalR-2.4.1.js:86 [09:28:28 GMT-0600 (Central Standard Time)] SignalR: Client subscribed to hub 'personnelhub'.
jquery.signalR-2.4.1.js:86 [09:28:28 GMT-0600 (Central Standard Time)] SignalR: Client subscribed to hub 'trainingboardhub'.
jquery.signalR-2.4.1.js:86 [09:28:28 GMT-0600 (Central Standard Time)] SignalR: Negotiating with '/signalr/negotiate?[RemovedURL]
SignalR: Received redirect [RemovedURL]
SignalR: Connecting to websocket endpoint 'wss: [RemovedURL]
SignalR: Websocket opened.
jquery.signalR-2.4.1.js:86 [09:28:28 GMT-0600 (Central Standard Time)] SignalR: webSockets transport connected. Initiating start request.
jquery.signalR-2.4.1.js:86 [09:28:28 GMT-0600 (Central Standard Time)] SignalR: The start request succeeded. Transitioning to the connected state.
jquery.signalR-2.4.1.js:86 [09:28:28 GMT-0600 (Central Standard Time)] SignalR: Now monitoring keep alive with a warning timeout of 66666666.666666664, keep alive timeout of 100000000 and disconnecting timeout of 5000
jquery.signalR-2.4.1.js
`

**Comment by halter73** [comment]
It looks like it reconnected to me, so it didn't "disconnect". The reconnected event should work.
