### ISSUE TITLE
Remove Cursor Payload here in SignalR ASP.NET Framework Library

### ISSUE THREAD

**Issue by firephantomassasin** [SignalR/SignalR#4512]
Hi,

I would like to ask for your help guys. Is there a way to remove the cursor part here in signalR Asp.net framework library? Please, there a lot of users and systems are still in asp.net framework, hopefully, allowing to remove the cursor part in the payload is feasible. This will be worth the effect as it will decrease the payload size. We really want to decrease the payload and bandwidth consumption of our signalR.

![image](https://user-images.githubusercontent.com/8090574/99346739-55a33500-28d0-11eb-93c8-a040a5464325.png)

We don't plan to using the fetching the missing data that wasn't sent when the client disconnect then reconnects again. We don't care if the client disconnects then reconnect again, it doesn't need to receive the missing data. I hope there is a workaround to remove this Cursor part in the payload.

Please i really hope you guys could consider this as your "last" tweaks on the library like probably a configurable in the GlobalHost.Configuration.UseCursor = false, or something like that. This is very important enhancement.

**Comment by BrennanConroy** [comment]
Sorry, we are not adding new features to this library. You could consider porting your application to ASP.NET Core SignalR which is in active development and doesn't include a cursor.
