### ISSUE TITLE
signalr in Android and wechat program how can i to add wss certificate？

### ISSUE THREAD

**Issue by alonger** [SignalR/SignalR#4513]
Issues related to the Asp.NET Core version of SignalR should be filed in the AspNetCore repo: https://github.com/aspnet/AspNetCore/issues/new/choose
Please remove this line and the line above before submitting a new issue.

**Comment by alonger** [comment]
in Android code:
    httpHubConnectionBuilder.setHttpClientBuilderCallback(Action1<OkHttpClient.Builder> configureBuilder);
I  used this code to set a  callback,but I don't known how to set the HttpClientBuilder?

**Comment by BrennanConroy** [comment]
> I used this code to set a callback,but I don't known how to set the HttpClientBuilder?

The callback gives you the builder to then set options on.

Example:
```
httpHubConnectionBuilder.setHttpClientBuilderCallback((builder) => {
    builder.writeTimeout(Duration.ofMinutes(1));
});
```

There are posts online about how to pin certificates etc. https://stackoverflow.com/questions/53304082/adding-a-custom-certificate-to-an-okhttp-client

> Issues related to the Asp.NET Core version of SignalR should be filed in the AspNetCore repo: https://github.com/aspnet/AspNetCore/issues/new/choose

In the future file issues for ASP.NET Core in the correct repo please.
