### ISSUE TITLE
Accessing context.User.Identity.Name inside OnDisconnected throws ObjectDisposedException on windows authentication

### ISSUE THREAD

**Issue by alex-jitbit** [SignalR/SignalR#4514]
Chrome browser 87.0.4280.66
WebSockets transport.
Latest SignalR (2.4.1)
**Windows-integrated authentication** enabled on both server and browser and works properly

Navigating away from a page invokes `OnDisconnected` server event properly but I cannot access `Context.User.Identity.Name`

**Ironically accessing that object is what MS docs suggest to do** https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/mapping-users-to-connections#in-memory-storage

PS. even this workaround does not work any more. https://stackoverflow.com/questions/22892596/signalr-hub-ondisconnect-raises-objectdisposedexception

**Comment by BrennanConroy** [comment]
This repo is in maintenance mode and this issue doesn't meet the bug bar.
