### ISSUE TITLE
Connection disconnected state in ASP.NET Core 3.1

### ISSUE THREAD

**Issue by stanislavstoyanov99** [SignalR/SignalR#4515]
**### Expected  behavior**
Receive a normal text message in the client side.

**### Actual behavior**
Receive an error "Uncaught (in promise) Error: Invocation canceled due to the underlying connection being closed." at line 16 in signalr.min.js.

**### Steps to reproduce**
The initial state of SignalR connection is normal and I receive information in the console that there is a connection to the web socket. So the requested message from the chat is received, but immediately after that the connection is disconnected. I am using ASP.NET Core 3.1 and I am trying to implement SignalR in normal mvc web app. The server is local IIS.

**Comment by BrennanConroy** [comment]
ASP.NET Core SignalR lives in https://github.com/dotnet/aspnetcore, please file an issue there and provide more details about your app and what you're doing. Also, enabling debug level log messages on the server might help.
