### ISSUE TITLE
Send list of objects using MessagePack

### ISSUE THREAD

**Issue by avialonn** [SignalR/SignalR#4516]
Hi there,
I'm using the latest version with .net 5 and I'm trying to send a list of objects with no success.
I can send 1 object with no issue. I've also tried to create wrapper object and set the relevant attr (MessagePackObject).
But this was not successful as well.
Any input will be much appreciated.
aa

**Comment by BrennanConroy** [comment]
This is the wrong repo, please file an issue at https://github.com/dotnet/aspnetcore

Also, provide more information about the issue, including code, logs, and details about what isn't working.

**Comment by avialonn** [comment]
Why is it the wrong repo? the issue is with signalr implementation and not .net core.
When I'm trying to send the objects the signalr return error that the signature is not implemented correctly.

**Comment by BrennanConroy** [comment]
This repo is for ASP.NET SignalR, it looks like you're trying to use ASP.NET Core SignalR which belongs in the aspnetcore github repo.

The new issue template also explains that
>Issues related to the Asp.NET Core version of SignalR should be filed in the AspNetCore repo: https://github.com/aspnet/AspNetCore/issues/new/choose

**Comment by avialonn** [comment]
Ok Thanks!
