### ISSUE TITLE
Cross domain client/server protocol version mismatch

### ISSUE THREAD

**Issue by lance-jsi** [SignalR/SignalR#4517]
Using a ASP.NET Web API project to host a hub with IIS Express (localhost), all clients on other localhost domains cannot connect to the hub

Error: You are using a version of the client that isn't compatible with the server. Client version 2.1, server version undefined.
    at Object.error (jquery.signalR-2.4.1.min.js:9)

Web API project with the latest SignalR packages installed
Microsoft.AspNet.SignalR
Microsoft.AspNet.SignalR.Core
Microsoft.AspNet.SignalR.JS
Microsoft.AspNet.SignalR.SystemWeb

Possibly relevant packages also installed
Microsoft.Owin
Microsoft.Owin.Cors
Microsoft.Owin.Host.SystemWeb
Microsoft.Owin.Security
Microsoft.Owin.OAuth
Owin

The clients are referencing the /signalr scripts hosted on the Web API project directly so there should be no mismatch

Relevant code details here, everything else is boilerplate
`$.connection.hub.url = 'http://localhost:xxxxx'; \\ Web Api project URL`
`$.connection.hub.start({ withCredentials: false }); \\ using this option for CORS`

**Comment by halter73** [comment]
> The clients are referencing the /signalr scripts hosted on the Web API project directly so there should be no mismatch

There could be a version mismatch. Only the hub proxies are generated by the server. The JS SignalR client could still be a different version than the server. Generally speaking, SignalR is resilient to older clients connecting to newer servers since it's sometimes difficult to update every client that could connect to a given server. Using newer clients with older servers is less likely to work.

What are the versions of the server packages?

**Comment by lance-jsi** [comment]
> What are the versions of the server packages?

All the SignalR packages are at 2.4.1

**Comment by BrennanConroy** [comment]
Hi. It looks like this is a question about how to use SignalR. This repo is in maintenance mode and we only have the resources to fix major issues, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com/).

From a quick glance, this doc may help you https://docs.microsoft.com/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-javascript-client#calling-usecors
