### ISSUE TITLE
OnReconnecting event sends a null Exception object inside the handler.

### ISSUE THREAD

**Issue by ijamon** [SignalR/SignalR#4522]
Hello,
I'm using Microsoft.AspNetCore.SignalR.Client 3.1.
I found the following OnReconnecting event behavior:
in some cases, the Exception argument of the handler for this event is null.

### Expected  behavior
Exception object always not null in the OnReconnecting event handler.
### Actual behavior
In some cases, Exception object is null.
### Steps to reproduce
I have not found the exact steps to reproduce, this error reproduces unexpectedly.

**Comment by BrennanConroy** [comment]
This is the wrong repo, file issues for ASP.NET Core SignalR at https://github.com/dotnet/aspnetcore

`OnReconnecting` does not exist, I'm guessing you meant `Reconnecting`.

The callback wont always have an exception, if the server shuts down gracefully or closes the connection gracefully then there wont be an exception. If you're seeing a common error case where there isn't an exception then we can look into improving that.

**Comment by ijamon** [comment]
Thanks.
Yes, I meant Reconnecting event.
When I reproduced this error, I stopped the server in VS and after that the Reconnecting event handler had an Exception object = null.
I've seen this several times, but in most cases the Exception object is not null.

Will post this in the right repo.
