### ISSUE TITLE
Documentation Link redirects to .NET Core documentation

### ISSUE THREAD

**Issue by nfgallimore** [SignalR/SignalR#4525]
It is very hard to find the .NET Framework documentation for Signal R. I think updating the README.md to use this URL for the documentation link is more appropriate: https://docs.microsoft.com/en-us/aspnet/signalr/overview/getting-started/introduction-to-signalr

The current documentation link, links to a web page https://dotnet.microsoft.com/apps/aspnet/signalr, which only has a Get Started button that navigates the user to the .NET Core documentation for SignalR.

**Comment by BrennanConroy** [comment]
Done via https://github.com/SignalR/SignalR/pull/4526
