### ISSUE TITLE
Add support for records with SignalR .Net client

### ISSUE THREAD

**Issue by JaredMRomano** [SignalR/SignalR#4528]
Although System.Text.Json can serialize/Deserialize  positional records, Signalr .Net client apparently cannot.  

### Expected  behavior
Serialize/Deserialize just as System.Text.Json can 

### Actual behavior
Throws "Failed to invoke '<methodName>' due to an error on the server. InvalidDataException: Error binding arguments. Make sure that the types of the provided values match the types of the hub method being invoked."  

This is because the Client fails to serialize the object, but never throws any error.  It looks like it requires a parameterless constructor.  Once I convert it to a class with a parameterless constructor, the client can send the argument to the server.

### Steps to reproduce

Create a signalR hub that has a positional record as a parameter.  Create a client and connect to the server.  Call the method on the server using "InvokeAsync(<methodName>, <positional record type argument>)"

**Comment by BrennanConroy** [comment]
Please file this issue at https://github.com/dotnet/aspnetcore and include code examples.

Also, which version of System.Text.Json supports positional records?

**Comment by JaredMRomano** [comment]
I'm using .Net 5. I used this example: https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-immutability?pivots=dotnet-5-0
