### ISSUE TITLE
JavaScript Hubs Configuration

### ISSUE THREAD

**Issue by YuryLiakhovich** [SignalR/SignalR#4530]
Big Sur 11.2.1 (Apple Silicon)
Mono 6.12.1 (.NET Framework 4.6.1)
Microsoft.AspNet.SignalR 2.4.1

Workflow:

Create new ASP.NET MVC Project and Add OwinStartup to Initialize SignalR.

Problem case: 

The page "~/signalr/hubs" receiving status code and body, but HttpRequest doesn't close and stuck after that. I see too long loading, near 300 seconds, and after that I've got error - 200_IDLE_TIMEOUT.

Is SignalR working at XSP4 server on Mono? Tried to use old version Mono (5) and SignalR - the same case.

**Comment by BrennanConroy** [comment]
We are in maintenance mode and only fixing critical issues. See our [blog post](https://devblogs.microsoft.com/aspnet/the-future-of-asp-net-signalr/) for details. This issue doesn't meet the bug bar. 

You can consider posting this question to stackoverflow for help.
