### ISSUE TITLE
SignalR client does not connect when the cell phone is at 3g/4g

### ISSUE THREAD

**Issue by gimenezfrg** [SignalR/SignalR#4531]
707 / 5000
Resultados de tradução
I'm using SIGNALR to develop a chat application similar to Whatsapp, everything works fine, the point is that I found that when the phone is in 3G / 4G, I can't establish communication with the server's HUB, this in the Android project. On the Android emulator it even works, but on my phone (Xiaomi MI 9) it doesn't. It displays this error: "the handshake with the server could not be completed due to an error: the handshake has been canceled."

Has anyone ever experienced this?

I even thought it was something related to Xiaomi, but I uploaded the server on my local machine and it worked, the production server is on a VPS on the hostinger running Windows Server 2008. WiFi works, 3G / 4G does not.

**Comment by BrennanConroy** [comment]
> the handshake with the server could not be completed due to an error: the handshake has been canceled.

This is generally from a timeout, so you might be having issues connecting to the server endpoint.

We are in maintenance mode and only fixing critical issues. See our [blog post](https://devblogs.microsoft.com/aspnet/the-future-of-asp-net-signalr/) for details. This issue does not meet the bug bar.

You can consider posting this question to stackoverflow for help.

**Comment by gimenezfrg** [comment]
Hello, I discovered the problem, I use a DNS (http://xxx.com:xxxx/api/) to reach the server, WiFI works well, 3G / 4G does not, I changed the DNS for IP and everything worked .. Then I will investigate further the problem with the DNS.

Thanks
