### ISSUE TITLE
Further Updates 2.4.2?

### ISSUE THREAD

**Issue by bryanllewis** [SignalR/SignalR#4532]
We have an issue with SignalR running against an Azure SQL Managed Instance.  This PR resolved that problem:

https://github.com/SignalR/SignalR/pull/4420

However, it was scheduled for 2.4.2 and that version was never released.  Are there going to be further updates or is 2.4.1 the end of the line?

Thanks,
Bryan

**Comment by BrennanConroy** [comment]
> Are there going to be further updates

We're working on the 2.4.2 update and hope to have it out later this year.
