### ISSUE TITLE
Missing required parameter "Url" in command line in Crank tool

### ISSUE THREAD

**Issue by ali-h2010** [SignalR/SignalR#4534]
After downloading the solution and executing build.cmd, i am getting the above error while running the crank tool.

Missing required parameter "Url" in command line ""C:\Users\[USER_Profile]\Downloads\SignalR-master\SignalR-master\artifacts\Debug\bin\Microsoft.AspNet.SignalR.Crank\net45\crank.exe" "

### Expected  behavior
Crank tool should run

### Actual behavior
Crank tool is throwing the above error and stop working

### Steps to reproduce
- Download or clone Master branch.
- run build.cmd
- Update global.json with the installed SDK (5.0.103 is latest installed in my machine)
- Build and run crank tool.
- Error is thrown in crank windows and not proceeding

**Comment by halter73** [comment]
I just tried this in a freshly cloned repo and I don't see any error. It seems strange that updating to the 5.0.103 SDK would be the cause of the problem. Did it work with 2.1.400?

Is there any more interesting build output or do you have anything else special about your environment that might be necessary to repro the issue?

**Comment by BrennanConroy** [comment]
> Missing required parameter "Url" in command line

Did you pass a Url when running the crank command?

**Comment by halter73** [comment]
Ahh. I misread and thought this was about just rerunning `build.cmd`. Calling `crank.exe` without a URL would do it. Here's an example usage: https://github.com/SignalR/SignalR/blob/75126981cd165fb57db4e38e9379e651fec1ecdf/src/Microsoft.AspNet.SignalR.Crank/TPlan.Perf.xml#L14

**Comment by ali-h2010** [comment]
> Ahh. I misread and thought this was about just rerunning `build.cmd`. Calling `crank.exe` without a URL would do it. Here's an example usage:
> 
> https://github.com/SignalR/SignalR/blob/75126981cd165fb57db4e38e9379e651fec1ecdf/src/Microsoft.AspNet.SignalR.Crank/TPlan.Perf.xml#L14

Wait, am i not supposed to type the command in the window after i open the crank.exe?😅

I was just trying to test if it was running and didn't even use the command to execute the tool. I will try again and update you.
