### ISSUE TITLE
Chrome terminates WebSocket conenction

### ISSUE THREAD

**Issue by MJRomka** [SignalR/SignalR#4536]
Looks like recent policy changes in Chrome ([throttling JavaScript timer wake-ups](https://docs.google.com/document/d/11FhKHRcABGS4SWPFGwoL6g0ALMqrFKapCk5ZTKKupEk/view)) forces WebSocket connection termination in 5-7 minutes of tab inactivity.
Also see [this question](https://stackoverflow.com/q/66323874/2551398) on Stackoverflow.
Safari seems to close the connection in exactly 5 mins of inactivity.

My JavaScript client version is v2.2.0

**Comment by MateuszAxence** [comment]
Yup. I have the same issue. My chat stop working after 5 minutes.

I looked at jquery.signalR.js file. 
The setTimeout function, which updates the beat variable to keep the connection active, seems to stop working and then the connection is closed

Any plan to fix that?

**Comment by BrennanConroy** [comment]
Anyone have a simple repro app? I've tried with Chrome 89 and haven't hit any issues so far.

**Comment by benaadams** [comment]
After 5mins+ of being a background tab, Chrome will throttle setTimeout to a rate of 1 per minute (aligned to minute boundaries)

https://github.com/SignalR/SignalR/blob/2f549430b4e7f471a29df1f656563e829eead347/src/Microsoft.AspNet.SignalR.JS/jquery.signalR.transports.common.js#L39-L42

Is the default `keepAliveData.timeout` less than 60 secs?

**Comment by BrennanConroy** [comment]
> Is the default `keepAliveData.timeout` less than 60 secs?

Yes, it's 20 seconds https://github.com/SignalR/SignalR/blob/75126981cd165fb57db4e38e9379e651fec1ecdf/test/Microsoft.AspNet.SignalR.Tests/ConfigurationManagerFacts.cs#L22

**Comment by benaadams** [comment]
Would probably need it to be 80 secs then? (60 secs sleeping, 20 secs timeout)

**Comment by BrennanConroy** [comment]
For users to be safe? Probably, but so far all I've heard is that chrome hypothetically breaks SignalR. Haven't been able to repro any issues yet.

**Comment by benaadams** [comment]
Try starting Chrome with this flag so it kicks in after 10 secs as a background tab rather than having to wait 6+ minutes?
```
--enable-features="IntensiveWakeUpThrottling:grace_period_seconds/10,OptOutZeroTimeoutTimersFromThrottling,AllowAggressiveThrottlingWithWebSocket"
```

![image](https://user-images.githubusercontent.com/1142958/110187203-65a73c00-7e0f-11eb-9680-da29288d6b72.png)

**Comment by BrennanConroy** [comment]
> Try starting Chrome with this flag so it kicks in after 10 secs as a background tab rather than having to wait 6+ minutes?

Yeah, I tried that and also waiting for more than an hour. Still hit no issues.

>Anyone have a simple repro app?

Still looking for an app to investigate the problem.

**Comment by rk4github** [comment]
It is not reproduced consistently in all Windows 10 OS systems with latest Chrome 88 and above. It is reproduced in few Windows 10 OS systems with Chrome 88. It is reproduced for sure in systems where latest windows 10 OS and Chrome 88 installed fresh.

**Comment by romua** [comment]
Looks like I faced the same issue. Reproduced with https://github.com/SignalR/SignalR/issues/4536#issuecomment-791802083 flags.

Got my connection reconnected after 1.5min. Tab was inactive:

![image](https://user-images.githubusercontent.com/8287891/110464261-9a4f1800-80db-11eb-8358-0130dfec67f6.png)

**Comment by KenDFish** [comment]
+1. Like everyone else, I've had this issue since Chrome 88, and I can't reproduce it reliably enough. I reached out to the author of the Google blog post, but all he could suggest was to file a bug with steps to reproduce the issue - which is very difficult!

**Comment by KenDFish** [comment]
FWIW, I've raised a Chromium [bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=1186569). Not sure if it'll get any traction, but it can't hurt.

**Comment by MJRomka** [comment]
Looks like the issue is not reproducing on localhost, but once the same app is hosted (e.g. in Azure) it always occurs. FYI

**Comment by romua** [comment]
> Looks like the issue is not reproducing on localhost, but once the same app is hosted (e.g. in Azure) it always occurs. FYI

In my case it's reproducing on localhost

**Comment by halter73** [comment]
@fdoray's comment on the chromium issue (I'm guessing it's the same person):


> Chrome is currently rolling out intensive throttling of Javascript timers. This blog post explains it in details: https://developer.chrome.com/blog/timer-throttling-in-chrome-88/ We deciced to throttle Javascript timers intensively because they are often not the most resource-efficient mechanism to achieve a goal.
> 
> I understand that the use case of SignalR is to ping the server at regular intervals to keep a connection alive https://github.com/SignalR/SignalR/blob/2f549430b4e7f471a29df1f656563e829eead347/src/Microsoft.AspNet.SignalR.JS/jquery.signalR.core.js#L223-L228. Would this solution work?
> 
> Pseudo-code:
> 
> ```JS
> onTimeout() {
>   // If this ever runs, it means that the connection is broken.
> }
> ```
> 
> ```JS
> pingServer() {
>   Send a ping to the server.
>   timeout_id = setTimeout(onTimeout, timeout);
> }
> ```
> 
> ```JS
> // This is invoked when the server replies to the ping.
> onServerResponse() {
>   clearInterval(timeout_id);
>   // Schedule another ping.
>   setTimeout(pingServer, ping_interval);
> }
> ```
> 
> ```JS
> // Schedule the initial ping.
> setTimeout(pingServer, ping_interval);
> ```
>
> Why this works? Intensive throttling is not applied to timers that are scheduled from a network response handler, because this tells the browser that useful work was performed.

The SignalR server doesn't rely on `setInterval` for it's normal KeepAlive messages. Those are sent from the server to the client and should still work if network response handlers aren't throttled.

The `config.pingInterval` logic is for making normal XHRs intended to refresh cookies (see https://stackoverflow.com/a/25634573/719967) and only defaults to executing every 5 minutes anyway. This does line up with closing the connection after "exactly 5 mins of inactivity", but I'm not sure why this failing to run would cause the connection to die. Disabling `config.pingInterval` by setting it to null is supported and shouldn't be a problem if you don't need to refresh cookies.

**Comment by halter73** [comment]
https://github.com/SignalR/SignalR/blob/5d7dd18eba57349e64e8c6438cdd931f48a68496/src/Microsoft.AspNet.SignalR.JS/jquery.signalR.transports.common.js#L18-L29

https://github.com/SignalR/SignalR/blob/5d7dd18eba57349e64e8c6438cdd931f48a68496/src/Microsoft.AspNet.SignalR.JS/jquery.signalR.transports.common.js#L640-L651

https://github.com/SignalR/SignalR/blob/5d7dd18eba57349e64e8c6438cdd931f48a68496/src/Microsoft.AspNet.SignalR.JS/jquery.signalR.transports.common.js#L675-L681

I think the above logic might be causing the issue. IIRC, this was written this way to SignalR can quickly recognize when the device came back from sleep and stop the connection.

If the issue is that beat isn't updating `connection._.lastActiveAt` frequently enough due to the timer throttlling, but `markLastMessage` is still being called and updating `connection._.lastMessageAt` because that's called by a "network response handler", the fix might be just to always update `connection._.lastActiveAt` when we update `connection._.lastMessageAt`. Before this was unnecessary because if network callbacks were being called so were the timer callbacks.

**Comment by halter73** [comment]
Can someone confirm that `connection._.lastMessageAt` is still fresh when `connection._.lastActiveAt` becomes stale because the throttled timer wakeups?

**Comment by mgazell** [comment]
@halter73, do we need a corresponding change in the asp.net core client too? I'm facing the similar connection drop issue when using @microsoft/signalr package.

**Comment by francoisdoray** [comment]
Did a48ebc6c5f08c9dbb87a9d6506529c388cbaa7ad resolve the issue?

I'm the owner of Intensive Wake Up Throttling in Chrome. I'll keep an eye on this bug.

**Comment by BrennanConroy** [comment]
> do we need a corresponding change in the asp.net core client too? I'm facing the similar connection drop issue when using @microsoft/signalr package.

Please file an issue in the dotnet/aspnetcore repo. And provide a minimal repro app with instructions on how to hit the issue.

> Did [a48ebc6](https://github.com/SignalR/SignalR/commit/a48ebc6c5f08c9dbb87a9d6506529c388cbaa7ad) resolve the issue?

We can only guess because we've been unable to reproduce the issue. If someone could give us a simple repro or test the change out that would be helpful.

**Comment by bacobart** [comment]
We were able to consistently reproduce this as follows:

- set chrome://flags/#intensive-wake-up-throttling to enabled (or enabled 10 secs)
- open tab with signalr connection (don't open devtools!)
- open different tabs
- minimize chrome
- wait 5 minutes
- connection is dropped
- go to initial tab, observe connection was dropped, and will be restored once tab gains focus again

**Comment by mgazell** [comment]
> 
> Please file an issue in the dotnet/aspnetcore repo. And provide a minimal repro app with instructions on how to hit the issue.
> 

Created new issue in aspnetcore repo https://github.com/dotnet/aspnetcore/issues/31079

**Comment by firephantomassasin** [comment]
+1! We are also experiencing this issue in .net framework 4.7.2. It looks like an issue in the front end js chrome. Any workaround?

**Comment by IanYates** [comment]
> Can someone confirm that `connection._.lastMessageAt` is still fresh when `connection._.lastActiveAt` becomes stale because the throttled timer wakeups?

We are hitting this issue a *lot* so I'll see if we can add some logging to check these values  (it's almost midnight here in Australia so give us a good 24-48 hours from now to do that :D )

**Comment by cnavarro16** [comment]
Can confirm that I can repro this issue consistently in both Chrome and Edge, however, the root cause in our environment is different for both browsers:
* **Edge**: Seems to be due to the 'sleeping tabs' feature. I confirmed by changing the default time of 2 hours to five minutes, and observed that our app terminated the WebSocket connection consistently. However, there is the ability to whitelist sites/domains, so doing this helped mitigate the issue for our internal apps.
* **Chrome:** For Chrome it does seem like the throttling feature they've introduced is the culprit here. However, I noticed that sometimes it might take a bit longer than 5 minutes for it to kick in and terminate the WebSocket connection. I consistently was able to reproduce the issue by leaving the tab inactive for 10 minutes. Disabling the throttling feature seems to have fixed the issue.

**Comment by cnavarro16** [comment]
@firephantomassasin please see my comment above for a potential workaround.

**Comment by IanYates** [comment]
> Can someone confirm that `connection._.lastMessageAt` is still fresh when `connection._.lastActiveAt` becomes stale because the throttled timer wakeups?

Am I experiencing the issue if these are different?  I've applied your code fix and think I may still have hit the issue, but I'm not 100% sure as I'm not quite understanding if these should *always* be identical, or if there is reason why they might differ, and if so, which one ought to be ahead.

**Comment by BrennanConroy** [comment]
>  I've applied your code fix and think I may still have hit the issue

What makes you unsure if you hit the issue still or not?

> if these should _always_ be identical, or if there is reason why they might differ, and if so, which one ought to be ahead.

`lastActiveAt` can show a larger (newer) value than `lastMessageAt`.

**Comment by IanYates** [comment]
`What makes you unsure if you hit the issue still or not?`: We're still getting SignalR disconnects....

Thanks for the advice about the value expectations.

I've also seen chatter on StackOverflow about having the server send data over the socket very often to avoid this, so I've since implemented a very regular (every 5 seconds right now) server-to-client ping and am going to be testing that in conjunction with this patch too.

**Comment by BrennanConroy** [comment]
> We're still getting SignalR disconnects....

What values were you seeing for `lastActiveAt` and `lastMessageAt` when the connection disconnected?

**Comment by rk4github** [comment]
> Can someone confirm that `connection._.lastMessageAt` is still fresh when `connection._.lastActiveAt` becomes stale because the throttled timer wakeups?
Yes, `connection._.lastMessageAt` is still fresh when `connection._.lastActiveAt` becomes stale when Js timer throttle happens in chrome.

**Comment by rk4github** [comment]
As suggested by you, updating the connection._.lastActiveAt while marking last message is fixing the issue. It is verified.
 markLastMessage: function (connection) {
            connection._.lastMessageAt = new Date().getTime();
            connection._.lastActiveAt = connection._.lastMessageAt;
        },

**Comment by halter73** [comment]
Thanks @rk4github. This gives us more confidence to merge #4544.

**Comment by nitzzzu** [comment]
This was a very frustrating issue and really difficult to debug.
Now we are using this workaround to reconnect manually:

`
$.connection.hub.disconnected(function () {
    if ($.connection.hub.lastError)
    {
		$.connection.hub.start();
	}
});
`

Do you have any plans to release an official fix for this in the near future?

**Comment by cppmyjob** [comment]
Is there a simple hotfix for 2.4.1 version?

**Comment by cppmyjob** [comment]
Can I use changes for https://github.com/SignalR/SignalR/pull/4544 as a hotfix on production?

**Comment by halter73** [comment]
@cppmyjob I say go for it. If it causes more issues, revert it and tell us what went wrong, but I don't foresee anything major.

**Comment by IanYates** [comment]
> Can I use changes for #4544 as a hotfix on production?

We have slowly deployed this to a few customers.  I haven't got good feedback as to whether or not it has resolved the issue yet, although we haven't had further reports of the problem so I'm hopeful.

Prior to deploying the hotfix I also added in a server->client ping that happens regularly in the background so that even if our page has no reason to contact the server, and vice-versa, then the server is just pushing a "ping" to the client, and the client then calls back to the server.  I can say that this extra ping, just on its own, did *not* solve the issue.

**Comment by firephantomassasin** [comment]
When will you guys release a new version in the nuget that contains this fix?

**Comment by MdV303** [comment]
Looks like the #intensive-wake-up-throttling flag has been removed in Chrome v90, so there goes a potential browser-side workaround.

Our application is using ASP.NET SignalR 2.4.1. Migrating to APS.Net Core is currently not an option. 
What do you recommend? Install the 2.4.2 preview as described [here](https://github.com/SignalR/SignalR/pull/4544#issuecomment-818588053) or wait for a 2.4.2 package to become available at nuget? When can we expect such a package?

Thanks!

**Comment by BrennanConroy** [comment]
We pushed the npm package with this fix at https://www.npmjs.com/package/signalr/v/2.4.2

**Comment by shaapala** [comment]
> Looks like the #intensive-wake-up-throttling flag has been removed in Chrome v90, so there goes a potential browser-side workaround.
> 
> Our application is using ASP.NET SignalR 2.4.1. Migrating to ASP.Net Core is currently not an option.
> Downloaded and installed 2.4.2 preview. In combination with the 2.4.2 JS library the disconnects seem to be gone :-)
> 
> Thanks!

Don't lose hope. You can still disable it using chrome policy.  I just tested this and it works.
You have two options (either HKLM or HKCU)

Add the following reg key and then restart chrome.
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome]
"IntensiveWakeUpThrottlingEnabled"=dword:00000000

Go there to show it worked: 
chrome://policy/

See details here. 
https://chromeenterprise.google/policies/?policy=IntensiveWakeUpThrottlingEnabled

**Comment by glimpsedchaos** [comment]
> We pushed the npm package with this fix at https://www.npmjs.com/package/signalr/v/2.4.2

As asked by firephantomassasin, is this going to get pushed out to NuGet? I upvoted that question, but the NPM availability came with no comment about NuGet.

**Comment by mohghm** [comment]
NuGet availability is very much needed, being flamed with requests from clients for many systems using SignalR, please update us with a roll out date, appreciated!

**Comment by francoisdoray** [comment]
The #intensive-wake-up-throttling flag is back in the latest release of Chrome Canary (92.0.4487.0). Enterprise users can use a policy https://chromeenterprise.google/intl/en_ca/policies/#IntensiveWakeUpThrottlingEnabled to disable Intensive Wake Up Throttling until there software is adapted.

**Comment by BrennanConroy** [comment]
NuGet packages have been pushed.

**Comment by glimpsedchaos** [comment]
> NuGet packages have been pushed.

@BrennanConroy Thank you for the push. 

I have updated a small existing project from 2.4.1 to 2.4.2 and test.

**Comment by Bgajic-mono** [comment]
Not sure who to ping, @BrennanConroy we upgraded to 2.4.3 and it did not fix the disconnect after 5 minutes of inactivity issue. If the application is ran in debug mode the issue is not present and everything is working as expected, though once ran in release the disconnect happens. We're using Web Sockets as HttpTransportType. Please advise.
  
![image](https://user-images.githubusercontent.com/95707767/209691888-36920355-f787-4d06-a627-f6d036b8c749.png)

**Comment by jbennink** [comment]
I'm using Edge but I still see my signalR connection stop after several minutes as a "background" tab (ie not the active tab.

**Comment by faizannazir** [comment]
facing the same issue it still exists
