### ISSUE TITLE
How do we make sure the message delivered to client using signalR.?

### ISSUE THREAD

**Issue by Shyam268** [SignalR/SignalR#4539]
How do we make sure the message delivered to client using signalR?. Some times the messages are not delivered to client 

Packages used:
 Microsoft.Azure.SignalR - 1.4.3

**Comment by halter73** [comment]
SignalR does not have a built-in mechanism to verify message delivery. If this is important, we recommend manually acknowledging the invocation after handling it on the client. See https://stackoverflow.com/a/14203349/719967 for more details.
