### ISSUE TITLE
 the handlers of the client methods (js) become multiplied

### ISSUE THREAD

**Issue by ariellarraburu** [SignalR/SignalR#4540]
I have quite strange behavior in some client instances of my application. On some computers it never happens, while on others it is quite common, using the same version of chrome.

The server sends a message to clients (clients.all.MustUpdate) to notify them of new data. the mustUpdate function calls the server to get the new data set. That is normal behavior.

Some computers, upon receiving the call to the javascript function mustUpdate, make not one, but several calls to the server. This is because, for some reason, some clients start duplicating the proxy callbackmap handlers.

### Expected  behavior
https://i.imgur.com/2bPUO1j.png

### Actual behavior
https://i.imgur.com/wEaZuTI.png

### Steps to reproduce
I couldn't find a way to reproduce it, it only happens on some clients. It never happens in the development environment.

**Comment by halter73** [comment]
Are you reattaching callbacks when the client reconnects? If so, you don't have to.

**Comment by ariellarraburu** [comment]
> Are you reattaching callbacks when the client reconnects? If so, you don't have to.

Hi, no. I check if a previous handlers exists

if (!sigiHub.client.MapaSitIncidentesChangedDataAvailable) {
        sigiHub.client.MapaSitIncidentesChangedDataAvailable = function (key, ids) {
            if (signalrStarted === true) {
                getIncidentesChangedBykey(key, ids);
            }
        };
    }

    if (!sigiHub.client.MapaSitRecursosChangedDataAvailable) {
        sigiHub.client.MapaSitRecursosChangedDataAvailable = function (key, ids) {
            if (signalrStarted === true) {
                getRecursosChangedBykey(key, ids);
            }
        };
    }

    if (!sigiHub.client.MapaSitRecursosDataAvailable) {
        sigiHub.client.MapaSitRecursosDataAvailable = function () {
            if (signalrStarted === true) {
                getRecursosByFiltro(filterNameRecursos);
            }
        };
    }

    if (!sigiHub.client.MapaSitRecursosUbicacionDataAvailable) {
        sigiHub.client.MapaSitRecursosUbicacionDataAvailable = function () {
            if (signalrStarted === true) {
                getRecursosUbicacion();
            }
        };
    }
...

but they are duplicated anyway. I was able to verify that they even begin to duplicate without having reconnections.

Obviously it is wrong that the handlers are repeated, but even when I eliminate the repeated ones with the function that follows, the invocations are repeated anyway.

function removeRepeatedHandlers() {
    var pCallback = $.connection.hub.proxies.sigihub._.callbackMap;
    

    try {
        if (pCallback.communicationfailaddressarrival.length == 1 && pCallback.communicationfailaddressarrival[0].eventHandlers.length > 1) {
            console.log((pCallback.communicationfailaddressarrival[0].eventHandlers.length - 1).toString() + " duplicated handlers removed from communicationfailaddressarrival");
            pCallback.communicationfailaddressarrival[0].eventHandlers = pCallback.communicationfailaddressarrival[0].eventHandlers.slice(0, 1);
        }
    }
    catch (err) {
        console.log("Error removing duplicates from communicationfailaddressarrival:" + err.message);
    }

    try {
        if (pCallback.dismissnotification.length == 1 && pCallback.dismissnotification[0].eventHandlers.length > 1) {
            console.log((pCallback.dismissnotification[0].eventHandlers.length - 1).toString() + " duplicated handlers removed from dismissnotification");
            pCallback.dismissnotification[0].eventHandlers = pCallback.dismissnotification[0].eventHandlers.slice(0, 1);
        }
    }
    catch (err) {
        console.log("Error removing duplicates from dismissnotification:" + err.message);
    }

**Comment by halter73** [comment]
Without an repro, I can't tell you exactly what's going on, but it sure seems like it has to deal with the generated hub proxy logic.

https://github.com/SignalR/SignalR/blob/82e25550a3609ea124ed6be17aee67d23a574e85/src/Microsoft.AspNet.SignalR.Core/Scripts/hubs.js#L29-L79

Is you're client completely up to date? 2.4.1 is the latest. I wonder if unsubscribing in disconnected is failing because you don't have https://github.com/SignalR/SignalR/pull/4249.

**Comment by ariellarraburu** [comment]
> Without an repro, I can't tell you exactly what's going on, but it sure seems like it has to deal with the generated hub proxy logic.
> 
> https://github.com/SignalR/SignalR/blob/82e25550a3609ea124ed6be17aee67d23a574e85/src/Microsoft.AspNet.SignalR.Core/Scripts/hubs.js#L29-L79
> 
> Is you're client completely up to date? 2.4.1 is the latest. I wonder if unsubscribing in disconnected is failing because you don't have #4249.

Yes, I have the latest client libraries "jquery.signalR-2.4.1.js"

Server side config
```

 #region Owin config method
    public void Configuration(IAppBuilder app)
    {
        app.Map("/signalr", map =>
        {
            GlobalHost.Configuration.DefaultMessageBufferSize = this.SignalrDefaultMessageBufferSize;            
            
            map.UseCors(CorsOptions.AllowAll);                
            map.RunSignalR(new HubConfiguration()
            {
                EnableDetailedErrors = true,
                EnableJavaScriptProxies = true                 
            });
        });
    }
 #endregion
```
 
Configuration
```
 <add key="owin:AutomaticAppStartup" value="true" />
 <add key="SignalrDefaultMessageBufferSize" value="32" />
```
 
Client Side (just the relevant code)
```

'use strict';
var sigiHub;



function initSignalr() {
    // Declare a proxy to reference the hub. 

    signalrStarted = false;
    sigiHub = $.connection.sigiHub;

    if (!sigiHub.client.mapaSitIncidentesDataAvailable) {
        sigiHub.client.mapaSitIncidentesDataAvailable = function () {
            // Irrelevant code
        };
    }

    if (!sigiHub.client.mapaSitIncidentesLlamadoDataAvailableByKey) {
        sigiHub.client.mapaSitIncidentesLlamadoDataAvailableByKey = function (key) {
            // Irrelevant code
        };
    }
    
    if (!sigiHub.client.MapaSitIncidentesChangedDataAvailable) {
        sigiHub.client.MapaSitIncidentesChangedDataAvailable = function (key, ids) {
            if (signalrStarted === true) {
                // Irrelevant code
            }
        };
    }

    if (!sigiHub.client.MapaSitRecursosChangedDataAvailable) {
        sigiHub.client.MapaSitRecursosChangedDataAvailable = function (key, ids) {
            if (signalrStarted === true) {
                // Irrelevant code
            }
        };
    }

    if (!sigiHub.client.MapaSitRecursosDataAvailable) {
        sigiHub.client.MapaSitRecursosDataAvailable = function () {
            if (signalrStarted === true) {
                // Irrelevant code
            }
        };
    }

    if (!sigiHub.client.MapaSitRecursosUbicacionDataAvailable) {
        sigiHub.client.MapaSitRecursosUbicacionDataAvailable = function () {
            if (signalrStarted === true) {
                // Irrelevant code
            }
        };
    }

    if (!sigiHub.client.LlamadoDataAvailable) {
        sigiHub.client.LlamadoDataAvailable = function (llamadoID, telefonoCallerID) {
            if (signalrStarted === true) {
                // Irrelevant code
            }
        };
    }

    if (!sigiHub.client.eliminarNotificacionLlamado) {
        sigiHub.client.eliminarNotificacionLlamado = function (llamadoID) {
            if (signalrStarted === true) {
                // Irrelevant code
            }
        };
    }

    if (!sigiHub.client.communicationFailAddressArrival) {
        sigiHub.client.communicationFailAddressArrival = function (incidenteID, uuid, startTime) {
            if (signalrStarted === true) {
                // Irrelevant code
            }
        };
    }

    if (!sigiHub.client.dismissNotification) {
        sigiHub.client.dismissNotification = function (id) {
            if (signalrStarted === true) {
                // Irrelevant code
            }
        };
    }

    if (!sigiHub.client.signalrHeartBeat) {
        sigiHub.client.signalrHeartBeat = function (serverDate) {
            if (signalrStarted === true) {
                // Irrelevant code
            }
        };
    }

    hubClientStart();

    $.connection.hub.connectionSlow(function () {
        console.log('Alerta de conexión lenta');
    });

    $.connection.hub.disconnected(function () {
        setTimeout(function () {
            hubClientStart();
        }, 5000); // Reinicio a los 5 segundos de la desconeccion
        if ($.connection.hub.lastError) { console.log('Disconnected. Reason: ' + $.connection.hub.lastError.message); }
    });

    signalrKeepAliveTmr = setInterval(signalrKeepAlive, 30000);
}

/*
this was just an attempt to mitigate the problem, I run it every few seconds to eliminate the repeated handlers, but the messages are still repeated.
*/


function removeRepeatedHandlers() {
    var pCallback = $.connection.hub.proxies.sigihub._.callbackMap;
    

    try {
        if (pCallback.communicationfailaddressarrival.length == 1 && pCallback.communicationfailaddressarrival[0].eventHandlers.length > 1) {
            console.log((pCallback.communicationfailaddressarrival[0].eventHandlers.length - 1).toString() + " duplicated handlers removed from communicationfailaddressarrival");
            pCallback.communicationfailaddressarrival[0].eventHandlers = pCallback.communicationfailaddressarrival[0].eventHandlers.slice(0, 1);
        }
    }
    catch (err) {
        console.log("Error removing duplicates from communicationfailaddressarrival:" + err.message);
    }

    try {
        if (pCallback.dismissnotification.length == 1 && pCallback.dismissnotification[0].eventHandlers.length > 1) {
            console.log((pCallback.dismissnotification[0].eventHandlers.length - 1).toString() + " duplicated handlers removed from dismissnotification");
            pCallback.dismissnotification[0].eventHandlers = pCallback.dismissnotification[0].eventHandlers.slice(0, 1);
        }
    }
    catch (err) {
        console.log("Error removing duplicates from dismissnotification:" + err.message);
    }

    try {
        if (pCallback.eliminarnotificacionllamado.length == 1 && pCallback.eliminarnotificacionllamado[0].eventHandlers.length > 1) {
            console.log((pCallback.eliminarnotificacionllamado[0].eventHandlers.length - 1).toString() + " duplicated handlers removed from eliminarnotificacionllamado");
            pCallback.eliminarnotificacionllamado[0].eventHandlers = pCallback.eliminarnotificacionllamado[0].eventHandlers.slice(0, 1);
        }
    }
    catch (err) {
        console.log("Error removing duplicates from eliminarnotificacionllamado:" + err.message);
    }

    try {
        if (pCallback.llamadodataavailable.length == 1 && pCallback.llamadodataavailable[0].eventHandlers.length > 1) {
            console.log((pCallback.llamadodataavailable[0].eventHandlers.length - 1).toString() + " duplicated handlers removed from llamadodataavailable");
            pCallback.llamadodataavailable[0].eventHandlers = pCallback.llamadodataavailable[0].eventHandlers.slice(0, 1);
        }
    }
    catch (err) {
        console.log("Error removing duplicates from llamadodataavailable:" + err.message);
    }

    try {
        if (pCallback.mapasitincidenteschangeddataavailable.length == 1 && pCallback.mapasitincidenteschangeddataavailable[0].eventHandlers.length > 1) {
            console.log((pCallback.mapasitincidenteschangeddataavailable[0].eventHandlers.length - 1).toString() + " duplicated handlers removed from mapasitincidenteschangeddataavailable");
            pCallback.mapasitincidenteschangeddataavailable[0].eventHandlers = pCallback.mapasitincidenteschangeddataavailable[0].eventHandlers.slice(0, 1);
        }
    }
    catch (err) {
        console.log("Error removing duplicates from mapasitincidenteschangeddataavailable:" + err.message);
    }

    try {
        if (pCallback.mapasitincidentesdataavailable.length == 1 && pCallback.mapasitincidentesdataavailable[0].eventHandlers.length > 1) {
            console.log((pCallback.mapasitincidentesdataavailable[0].eventHandlers.length - 1).toString() + " duplicated handlers removed from mapasitincidentesdataavailable");
            pCallback.mapasitincidentesdataavailable[0].eventHandlers = pCallback.mapasitincidentesdataavailable[0].eventHandlers.slice(0, 1);
        }
    }
    catch (err) {
        console.log("Error removing duplicates from mapasitincidentesdataavailable:" + err.message);
    }

    try {
        if (pCallback.mapasitincidentesllamadodataavailablebykey.length == 1 && pCallback.mapasitincidentesllamadodataavailablebykey[0].eventHandlers.length > 1) {
            console.log((pCallback.mapasitincidentesllamadodataavailablebykey[0].eventHandlers.length - 1).toString() + " duplicated handlers removed from mapasitincidentesllamadodataavailablebykey");
            pCallback.mapasitincidentesllamadodataavailablebykey[0].eventHandlers = pCallback.mapasitincidentesllamadodataavailablebykey[0].eventHandlers.slice(0, 1);
        }
    }
    catch (err) {
        console.log("Error removing duplicates from mapasitincidentesllamadodataavailablebykey:" + err.message);
    }

    try {
        if (pCallback.mapasitrecursoschangeddataavailable.length == 1 && pCallback.mapasitrecursoschangeddataavailable[0].eventHandlers.length > 1) {
            console.log((pCallback.mapasitrecursoschangeddataavailable[0].eventHandlers.length - 1).toString() + " duplicated handlers removed from mapasitrecursoschangeddataavailable");
            pCallback.mapasitrecursoschangeddataavailable[0].eventHandlers = pCallback.mapasitrecursoschangeddataavailable[0].eventHandlers.slice(0, 1);
        }
    }
    catch (err) {
        console.log("Error removing duplicates from mapasitrecursoschangeddataavailable:" + err.message);
    }

    try {
        if (pCallback.mapasitrecursosdataavailable.length == 1 && pCallback.mapasitrecursosdataavailable[0].eventHandlers.length > 1) {
            console.log((pCallback.mapasitrecursosdataavailable[0].eventHandlers.length - 1).toString() + " duplicated handlers removed from mapasitrecursosdataavailable");
            pCallback.mapasitrecursosdataavailable[0].eventHandlers = pCallback.mapasitrecursosdataavailable[0].eventHandlers.slice(0, 1);
        }
    }
    catch (err) {
        console.log("Error removing duplicates from mapasitrecursosdataavailable:" + err.message);
    }

    try {
        if (pCallback.mapasitrecursosubicaciondataavailable.length == 1 && pCallback.mapasitrecursosubicaciondataavailable[0].eventHandlers.length > 1) {
            console.log((pCallback.mapasitrecursosubicaciondataavailable[0].eventHandlers.length - 1).toString() + " duplicated handlers removed from mapasitrecursosubicaciondataavailable");
            pCallback.mapasitrecursosubicaciondataavailable[0].eventHandlers = pCallback.mapasitrecursosubicaciondataavailable[0].eventHandlers.slice(0, 1);
        }
    }
    catch (err) {
        console.log("Error removing duplicates from mapasitrecursosubicaciondataavailable:" + err.message);
    }

    try {
        if (pCallback.sendnotifasignautoemer.length == 1 && pCallback.sendnotifasignautoemer[0].eventHandlers.length > 1) {
            console.log((pCallback.sendnotifasignautoemer[0].eventHandlers.length - 1).toString() + " duplicated handlers removed from sendnotifasignautoemer");
            pCallback.sendnotifasignautoemer[0].eventHandlers = pCallback.sendnotifasignautoemer[0].eventHandlers.slice(0, 1);
        }
    }
    catch (err) {
        console.log("Error removing duplicates from sendnotifasignautoemer:" + err.message);
    }

    try {
        if (pCallback.signalrheartbeat.length == 1 && pCallback.signalrheartbeat[0].eventHandlers.length > 1) {
            console.log((pCallback.signalrheartbeat[0].eventHandlers.length - 1).toString() + " duplicated handlers removed from signalrheartbeat");
            pCallback.signalrheartbeat[0].eventHandlers = pCallback.signalrheartbeat[0].eventHandlers.slice(0, 1);
        }
    }
    catch (err) {
        console.log("Error removing duplicates from signalrheartbeat:" + err.message);
    }
}

function hubClientStart() {
    $.connection.hub.logging = false;
    $.connection.hub.start().done(function () {
        signalrStarted = true;
        // Irrelevant code
    }).fail(function () {
        console.log('Error al conectar signalr')
        setTimeout(function () {
            hubClientStart();
        }, 5000); // Reinicio a los 5 segundos de la desconeccion
    });
}
   



```

**Comment by BrennanConroy** [comment]
Could you provide a minimal runnable repro app?

**Comment by ariellarraburu** [comment]
> Could you provide a minimal runnable repro app?

Hi, I tried to reproduce the duplication of handlers and so far I could not do it in a "minimal runnable app". but, I was able to get the messages to duplicate, although it happens only a few times under conditions that I don't know how to reproduce intensionally, but it does happen eventually.

https://github.com/ariellarraburu/SignalRRepeatedSample

![image](https://user-images.githubusercontent.com/6170164/120471395-0b206c00-c37b-11eb-88a3-365f61970148.png)

I have a single client running, and while everything was working correctly, the corresponding application pool showed an active request. When the messages started to duplicate another request appeared

![image](https://user-images.githubusercontent.com/6170164/120471898-aa456380-c37b-11eb-8f50-d93959434d65.png)

I believe that at some point, for some reason, instances of the hub are generated. These instances cannot communicate with the client, that is, invocations to clients.all.method () do not reach the client, but when the client calls mainHub.server.getData (reqId) both instances respond.

One of the reasons that inspire me to believe this is that if you look at the reqIds that come from the server, they are not consecutive, only even numbers come. I think, the event is fired in SingletonHub, both instances receive it and increment the value of serv2ClientReqId, but only one of them reaches the client. But, when the client calls the server, both instances respond.

**Comment by halter73** [comment]
I see that the argument is the same for the two highlighted invocations (`"A":[2392]`), but the invocations are unique from SignalR's prespective. That's why the invocation id's are different (`"I":36` and `"I":37). So there's no confusion at the lower signalr layers. I find it interesting the argument value is increasing by two every two invocations, but maybe that's expected for your app.

We'll need a consistent repro (or some clear reason why it cannot be reprod consistently and a way to make the repro more likely) before we can really investigate this further.

**Comment by ariellarraburu** [comment]
> I see that the argument is the same for the two highlighted invocations (`"A":[2392]`), but the invocations are unique from SignalR's prespective. That's why the invocation id's are different (`"I":36` and `"I":37`). So there's no confusion at the lower SignalR layers. I find it interesting the argument value is increasing by two every two invocations, **but maybe that's expected for your app.**

it's not

> 
> We'll need a consistent repro (or some clear reason why it cannot be reprod consistently and a way to make the repro more likely) before we can really investigate this further.

the application is hosted on a server behind a vpn. After being running for a long time, after some reconnections of the vpn, some restart of the application pool, or some modification of the web.config it begins to have this behavior, but not always enough to give you the recipe on how to reproduce it. The number and size of the packages may be a factor, because in production this happens all the time, but there is no way to pass that code to them.

One thing that is reproducible, although I don't know if it is the correct behavior, is what I put in the image. If I disconnect the vpn for a few seconds and reconnect it, the server sends all the packets that it could not send during the disconnection. In my case, where the message from the server, serves only to tell the clients that there is new data available (a data update), this generates a problem because the clients go 20 times to the server to get the exactly data.

Is there a way to configure signalr so packets that failed to send during disconnect are simply lost?

It is also strange to me that the many messages are not seen. In the image you can see a 1622 DataAvailable, and the next one is 1633. But obviously there was a 1623, 1624, .... Because there are GetData for those IDs.

![image](https://user-images.githubusercontent.com/6170164/120644850-2dcf8500-c44e-11eb-91b9-6e9209e0ee48.png)

**Comment by halter73** [comment]
> Is there a way to configure signalr so packets that failed to send during disconnect are simply lost?

No. This is something we've considered for a long time, but it's not been implemented yet. https://github.com/SignalR/SignalR/issues/2277. If it is going to happen, it will be in ASP.NET Core.

> It is also strange to me that the many messages are not seen. In the image you can see a 1622 DataAvailable, and the next one is 1633. But obviously there was a 1623, 1624, .... Because there are GetData for those IDs.

How fast are you sending messages and what message bus are you using? If you're using the default message bus, it is possible to overrun the circular buffer before some clients can read all the messages. https://stackoverflow.com/a/15460582/719967
