### ISSUE TITLE
The Connection Slow Event is being raised every exactly 30 minutes - We are currently experiencing difficulties with the connection

### ISSUE THREAD

**Issue by firephantomassasin** [SignalR/SignalR#4547]
Using the latest 2.4.1 server signalR version, hosted in IIS 10 Windows Server 2019 DC,

Every 30 minutes (Exact 30 minutes), we have noticed that we are encountering the connection slow event - We are currently experiencing difficulties with the connection.  It happens always every 30 minutes (e.g. 9am, 930am, 10am, 1030am, etc.)

Do you have any idea on how to avoid this? Our application pool is setup to run always and we don't have any recycling period every 30 mins in the IIS.  Is there any config in signalR that needs to adjust?

**Comment by halter73** [comment]
This just means that keep alives were delayed by over 10 seconds. If the keep alives were missed entirely, the client would start trying to reconnect. Are you seeing that at all? Could something be adding increased load on the server or client every thirty minutes that could be slowing down the network or starving the thread pool?

**Comment by firephantomassasin** [comment]
The keep alives were sending constantly every 10 seconds and it has never been missed. There are no increased load on the server as well since it keeps on happening even on midnight where there are no users. We are using Azure VM w/ IIS installed on it. Not sure if it is Azure related or VM related, do you have any ideas?

**Comment by halter73** [comment]
I would suggest enabling logging on the client: https://docs.microsoft.com/en-us/aspnet/signalr/overview/testing-and-debugging/enabling-signalr-tracing#javascript

That might give some interesting diagnostic details. If you could collect network traces on the client at the same time, you can use that to further verify that the sent keep alives aren't being delayed somehow on the network.

I don't think this is your problem, but we did fix a problem related to Chrome timer throttling causing connections to be unnecessarily closed in 2.4.2. See https://github.com/SignalR/SignalR/issues/4536. It might be worth upgrading to see if that helps.
