### ISSUE TITLE
how to choose SignalR js client for reactJS with Asp.NET MVC 5 (Microsoft.AspNet.SignalR), not Asp.NET Core

### ISSUE THREAD

**Issue by hackcodesid** [SignalR/SignalR#4548]
This is my situation,

I am using MVC 5, Microsoft.AspNet.SignalR and ReactJS.
I am not using Asp.NET Core.

Based on my understanding, @microsoft/signalr and @aspnet/signalr are used for Asp.NET Core only.
So, which SignalR js client (ReactJS), do I need to use in my situation?

Thanks in advance.

**Comment by BrennanConroy** [comment]
https://www.npmjs.com/package/signalr
