### ISSUE TITLE
Microsoft CDN does not have the latest javascript libraries

### ISSUE THREAD

**Issue by neilsoult** [SignalR/SignalR#4555]
### Expected  behavior

Visiting the page https://docs.microsoft.com/en-us/aspnet/ajax/cdn/overview#ASPNET_SignalR_Releases_on_the_CDN_17
should have links to the most recent versions of the client libraries.

### Actual behavior
2.2.2 is the most recent version available.

### Steps to reproduce
visit the link, look at the available versions.

**Comment by BrennanConroy** [comment]
@bradygaster Do we care about this CDN? All npmjs packages are available by default on other CDNs like unpkg, example https://unpkg.com/signalr@2.4.2/jquery.signalR.js

**Comment by bradygaster** [comment]
I always show CDNJS. thats the one I care about the most.

**Comment by neilsoult** [comment]
Perhaps I'm being a bit naive, but I would think that a Microsoft product would care about the official Microsoft CDN. 

But if the preference is to use third party CDNs like cdnjs or unpkg, perhaps that should be noted in the README? Since the current README links to the official documentation on docs.microsoft.com.

**Comment by bradygaster** [comment]
I validated this internally - the team has moved away from using the internal CDN, so w.r.t. SignalR, you can use either cdnjs (my personal recommendation) or unpkg. Closing this issue. Might be worth calling this out in the main doc, so cc'ing @Rick-Anderson

**Comment by Rick-Anderson** [comment]
https://github.com/dotnet/AspNetDocs/pull/537/files

**Comment by Rick-Anderson** [comment]
@neilsoult  thanks for bringing this to our attention.
