### ISSUE TITLE
Isn't unity2018 supporting netstandard2.0?

### ISSUE THREAD

**Issue by bbhxwl** [SignalR/SignalR#4559]
Isn't unity2018 supporting netstandard2.0?

Why can't I quote signalr？

### Expected  behavior
  unity  use signalR

### Actual behavior
![image](https://user-images.githubusercontent.com/26525599/120331950-dc75a780-c320-11eb-9942-ddae508f6e27.png)

**Comment by BrennanConroy** [comment]
Looks like you're using ASP.NET Core SignalR, issues for that project belong in https://github.com/dotnet/aspnetcore
