### ISSUE TITLE
signalr client throw a lot of error 

### ISSUE THREAD

**Issue by cysnet** [SignalR/SignalR#4560]
Client Version: Microsoft.AspNet.SignalR.Client2.4.1

the signalr client throw a lot of error:

`
System.NullReferenceException: Object reference not set to an instance of an object.\n   at System.Net.WebSockets.ClientWebSocket.CloseAsync(WebSocketCloseStatus closeStatus, String statusDescription, CancellationToken cancellationToken)\n   at Microsoft.AspNet.SignalR.WebSockets.WebSocketHandler.ProcessWebSocketRequestAsync(WebSocket webSocket, CancellationToken disconnectToken, Func`2 messageRetriever, Object state)\n   at Microsoft.AspNet.SignalR.Client.Transports.WebSocketTransport.PerformConnect(String url)\n   at Microsoft.AspNet.SignalR.Client.Transports.WebSocketTransport.DoReconnect()
`

`
System.InvalidOperationException: There is already one outstanding 'ReceiveAsync' call for this WebSocket instance. ReceiveAsync and SendAsync can be called simultaneously, but at most one outstanding operation for each of them is allowed at the same time.\n   at System.Net.WebSockets.ManagedWebSocket.ThrowOperationInProgress(String methodName)\n   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsync(ArraySegment`1 buffer, CancellationToken cancellationToken)\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.AspNet.SignalR.WebSockets.WebSocketMessageReader.ReadMessageAsync(WebSocket webSocket, Int32 bufferSize, Nullable`1 maxMessageSize, CancellationToken disconnectToken)\n   at Microsoft.AspNet.SignalR.WebSockets.WebSocketHandler.ProcessWebSocketRequestAsync(WebSocket webSocket, CancellationToken disconnectToken, Func`2 messageRetriever, Object state)
`

`
System.OperationCanceledException: Aborted\n ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.\n ---> System.Net.Sockets.SocketException (125): Operation canceled\n   --- End of inner exception stack trace ---\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)\n   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)\n   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)\n   at System.Net.Http.HttpConnection.ReadBufferedAsyncCore(Memory`1 destination)\n   at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)\n   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)\n   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)\n   --- End of inner exception stack trace ---\n   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)\n   at Microsoft.AspNet.SignalR.WebSockets.WebSocketMessageReader.ReadMessageAsync(WebSocket webSocket, Int32 bufferSize, Nullable`1 maxMessageSize, CancellationToken disconnectToken)\n   at Microsoft.AspNet.SignalR.WebSockets.WebSocketHandler.ProcessWebSocketRequestAsync(WebSocket webSocket, CancellationToken disconnectToken, Func`2 messageRetriever, Object state)
`

at last the connection was closed
`
System.TimeoutException: Couldn't reconnect within the configured timeout of 00:00:30, disconnecting.
`

maybe related with the signalr server restart.

**Comment by BrennanConroy** [comment]
Try 2.4.2, there was a similar looking issue that was fixed https://github.com/SignalR/SignalR/issues/4412

**Comment by cysnet** [comment]
> Try 2.4.2, there was a similar looking issue that was fixed #4412

will try to upgrade to 2.4.2

**Comment by cysnet** [comment]
> Try 2.4.2, there was a similar looking issue that was fixed #4412

this problem was gone after upgrate to 2.4.2. I thinks this issue can be closed.
