### ISSUE TITLE
Microsoft.AspNet.SignalR.Core, Version=2.4.1 referencing Microsoft.Owin, Version=2.1.0.0

### ISSUE THREAD

**Issue by BrennanConroy** [SignalR/SignalR#4562]
---
**Issue moved from dotnet/aspnetcore#33599**
- Please respond to @borap90.

---

_From @borap90 on Thursday, June 17, 2021 7:00:17 AM_

Facing an issue while generating type library for our .NET Component which uses Microsoft.AspNet.SignalR.Core NuGet package (version 2.4.1). 
----------------------------------------------------------------------------------------------------------
Our .NET component, uses the below NuGet packages. 
Nuget Package							     Version			.NET Framework

jQuery									       3.5.1				.Net4.8
Microsoft.AspNet.Cors						       5.2.7				.Net4.8
Microsoft.AspNet.SignalR					       2.4.1				.Net4.8
Microsoft.AspNet.SignalR.Core				       2.4.1				.Net4.8
Microsoft.AspNet.SignalR.JS					       2.4.1				.Net4.8
Microsoft.AspNet.SignalR.SystemWeb			       2.4.1				.Net4.8
Microsoft.Owin							       4.1.0				.Net4.8
Microsoft.Owin.Cors						       4.1.0				.Net4.8
Microsoft.Owin.Host.HttpListener			               4.1.0				.Net4.8
Microsoft.Owin.Host.SystemWeb				       4.1.0				.Net4.8
Microsoft.Owin.Hosting						       4.1.0				.Net4.8
Microsoft.Owin.Security						       4.1.0				.Net4.8
Newtonsoft.Json							       12.0.3			.Net4.8
Owin									       1.0				.Net4.8

The .NET component is in turn used by an unmanaged C++ component. 
For this, it is required to generate the type library of the .NET Component which is then referred within the unmanaged C++ classes. The problem happens when we try to invoke tlbexp command for the .NET Component.  The Type library export fails with the following error.

Microsoft (R) .NET Framework Assembly to Type Library Converter 4.8.3928.0
Copyright (C) Microsoft Corporation.  All rights reserved.

TlbExp : warning TX0013117F : Type library exporter warning processing 'Microsoft.AspNet.SignalR.Hub`1, Microsoft.AspNet.SignalR.Core'. Warning: Type library exporter encountered a generic type. Generic classes may not be exposed to COM.
TlbExp : warning TX0013117F : Type library exporter warning processing 'Microsoft.AspNet.SignalR.IHubContext`1, Microsoft.AspNet.SignalR.Core'. Warning: Type library exporter encountered a generic type. Generic classes may not be exposed to COM.
TlbExp : error TX0000 : Type library exporter encountered an error while processing 'TMNETBrowserIndependenceService.SignalRHub, TMNETBrowserIndependenceService'. Error: Type library exporter encountered an error while processing 'Microsoft.AspNet.SignalR.Owin.Middleware.HubDispatcherMiddleware, Microsoft.AspNet.SignalR.Core'. Error: Type library exporter cannot load type 'Microsoft.AspNet.SignalR.Owin.Middleware.HubDispatcherMiddleware' (error: Could not load file or assembly 'Microsoft.Owin, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)).

As per the error message “error: Could not load file or assembly 'Microsoft.Owin, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'”. It seems like the Microsoft.AspNet.SignalR.Core is looking for 'Microsoft.Owin, Version=2.1.0.0 which is not referenced within project (As per the table).
As you can see above, we are using Microsoft.Owin (v 4.1.0)
Checking the Microsoft.AspNet.SignalR.Core.dll using DotPeek (by JetBrains)  shows that the library refers to version 2.1.0.0 of Microsoft.Owin instead of the latest one.

We believe -
There should be backwards compatibility with Microsoft.Owin (4.1.0) 
If there is a dependency on Microsoft.Owin (2.1.0) for Microsoft.AspNet.SignalR.Core (2.4.1), then it should be flagged as a dependency.
Using Microsoft.Owin (2.1.0) with Microsoft.AspNet.SignalR.Core (2.4.1), gives the same error

Could you please let us know if there is a way to resolve this issue?
Also, is there another way to raise this - so that this can be resolved?

**Comment by halter73** [comment]
Is this a regression? Do you have a sample app that worked before that breaks when you update the SignalR package to 2.4.1?

Normally I would just say add a binding redirect, but I'm not sure if that works with tlbexp.

**Comment by borap90** [comment]
> Is this a regression? Do you have a sample app that worked before that breaks when you update the SignalR package to 2.4.1?
> **@halter73 Yes, it. 
I have uploaded the sample code here - [https://github.com/borap90/SampleApps_SignalR_ForIssue4562.git](url)
_SampleLib_Old_ has references to older versions of AspNet.SignalR.Core (v2.2.0) and Microsoft.Owin (v2.1.0)
whereas, _SampleLib_Updated_ has references to later versions of AspNet.SignalR.Core (v2.4.1) and Microsoft.Owin (v4.1.0)
Also, attached are the outputs for generating the tlb which shows the problem. For the SampleLib_Old, no errors, but for SampleLib_Updated, errors are reported for tlbexp** 
**_SampleLib_Old (tlbexp)_**
![image](https://user-images.githubusercontent.com/52690005/124769904-7ef3fc80-df57-11eb-93b2-ddacce371467.png)
**_SampleLib_Updated (tlbexp)_**
![image](https://user-images.githubusercontent.com/52690005/124770110-af3b9b00-df57-11eb-81d7-06abf56c5ddb.png)

> > If there is a dependency on Microsoft.Owin (2.1.0) for Microsoft.AspNet.SignalR.Core (2.4.1), then it should be flagged as a dependency.
> 
> Looking at https://www.nuget.org/packages/Microsoft.AspNet.SignalR.Core/2.4.1, the nuget package seems to appropriately ask for the 2.1.0 versions of the Microsoft.Owin* dependencies.
> @halter73 **Yes, it does state that >= 2.1.0. So, v4.1.0 should work as well.** 
> > There should be backwards compatibility with Microsoft.Owin (4.1.0)
> 
> I don't personally know of a break in backwards compatibility between Microsoft Owin 2.1 and 4.1. Normally I would just say add a [binding redirect](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions), but I'm not sure if that works with tlbexp.

> @halter73 **We already make use of binding redirects. [app.config] in the sample projects. I don't know if binding redirects is applicable for tlbexp.**
> > TlbExp : warning TX0013117F : Type library exporter warning processing 'Microsoft.AspNet.SignalR.Hub1, Microsoft.AspNet.SignalR.Core'. Warning: Type library exporter encountered a generic type. Generic classes may not be exposed to COM. TlbExp : warning TX0013117F : Type library exporter warning processing 'Microsoft.AspNet.SignalR.IHubContext1, Microsoft.AspNet.SignalR.Core'. Warning: Type library exporter encountered a generic type. Generic classes may not be exposed to COM.
> 
> Do you need to expose `Hub<T>` via COM?
@halter73 **Is this warning not for Microsoft.AspNet.SignalR.Hub? I believe it is. Is this something that needs to be done in SignalRCore**

**Comment by halter73** [comment]
If [your binding redirects](https://github.com/borap90/SampleApps_SignalR_ForIssue4562/blob/main/SampleLib_Updated/SampleLib_Updated/app.config#L14-L16) don't work for `tlbexp`, I guess you're stuck with using Owin 2.1. I'm not an expert on `tlbexp`, but this does not seem to be an issue with SignalR working with Microsoft.Owin 4.1 in general. This seems to be an issue with `tlbexp` not working with binding redirects.
