### ISSUE TITLE
There is already an open DataReader associated with this Command which must be closed first.

### ISSUE THREAD

**Issue by 1Jesper1** [SignalR/SignalR#4563]
"'There is already an open DataReader associated with this Command which must be closed first."
I'm using the DbContext in the class implementing IUserIdProvider. 

### Expected  behavior
Do not throw this error.

**Comment by BrennanConroy** [comment]
I'm not sure what you expect the SignalR library to do, it sounds like it's a problem in your code.

Suggest posting on stackoverflow if you're still having an issue.
