### ISSUE TITLE
Azure CDN multiple origin combination

### ISSUE THREAD

**Issue by kethasid** [SignalR/SignalR#4565]
I'm trying to use Azure CDN for azure static website through storage accounts and azure app service for our frontend. In the configuration part we are unable to configure origin for storage and web app in one endpoint. 

Wanted to know if  there is a possibility of configuring both the origins in the same endpoint or we have to create different endpoints for each of the above origins.

**Comment by BrennanConroy** [comment]
This doesn't look like a SignalR issue. Please ask your question on an Azure forum or stackoverflow.
