### ISSUE TITLE
MacOS Big Sur Version 11.4 - Latest Safari Version behaves differently when reconnecting from other browsers and previous versions.

### ISSUE THREAD

**Issue by euangordon** [SignalR/SignalR#4566]
After updating to the most recent version of MacOS (Big Sur 11.4) & Safari (14.1.1) from the most recent previous version, SignalR no longer works unless you disable the setting "Enable content blockers" in Safari. 

This setting is by default on in Safari 14.1.1

![image](https://user-images.githubusercontent.com/32622054/123413962-3d547080-d5ab-11eb-98dc-a346094e30fa.png)

After disabling this setting, SignalR v2.4.2 works as normal. 

![image](https://user-images.githubusercontent.com/32622054/123413843-20b83880-d5ab-11eb-9b56-0a8a4a708256.png)

For reference, SignalR is working perfectly for us in all other common browsers, including Chrome on MacOS.

A few questions:

1. Is this a known issue? I couldn't find it anywhere, but might have missed it.
2. Anyway to avoid the issue? 
3. Anyway to detect the setting being wrong and inform the user to change it?

ASP.NET MVC 5
.NET Framework 4.8
Azure SignalR
Microsoft.AspNet.SignalR v2.4.2
Microsoft.AspNet.SignalR.Core v2.4.2
Microsoft.AspNet.SignalR.JS v2.4.2
Microsoft.AspNet.SignalR.System.Web v2.4.2
Microsoft.AspNet.SignalR.AspNet v1.8.2 & tried v.19.0 too
Microsoft.AspNet.SignalR.Protocols v1.8.2 & tried v.1.9.0 too

**Comment by euangordon** [comment]
Found this old issue in Aspnet/SignalR, which feels similar:

[https://github.com/aspnet/SignalR/issues/3126](https://github.com/aspnet/SignalR/issues/3126)

@davidfowl @anurse @mikaelm12 Can any of you give me any pointers?

My current investigation has taken me as far as seeing that with:

- "Enable content blockers" disabled, Safari is communicating with SignalR and receiving responses as you would expect
- With "Enable content blockers" enabled (default Safari state), Safari is communicating with Azure SignalR, but the responses coming back are empty. I will keep digging and adding here.

**Comment by euangordon** [comment]
Server Logs from Safari with "Enable Content Blockers" disabled, this is when it works fine:

![image](https://user-images.githubusercontent.com/32622054/123435930-017ad480-d5c6-11eb-8dd3-2c06cb994d7b.png)

**Comment by euangordon** [comment]
Okay, finally worked it out. Sharing my findings in case anyone else faces this.

Firstly, please note that all major browsers were working fine and that the previous version of MacOS Safari was also working fine, however in Safari 14.1.1 this issue raised its head.

**What was actually happening:**
When Safari 14.1.1 had it's cache completely cleared and restarted it was connecting to SignalR no problem. The "Enable Content Blockers" change was actually fixing it because it was clearing the cache and connection.

The actual issue was happening when Safari was re-starting and not managing to connect to the hub. Really strange that this works the first time, but not subsequently after that:

![image](https://user-images.githubusercontent.com/32622054/123630176-1e551900-d80d-11eb-8a1a-7501c77e44cb.png)

The answer on this post gave me the solution:
[The On event on the SignalR Client Hub does not get called](https://stackoverflow.com/questions/16064651/the-on-event-on-the-signalr-client-hub-does-not-get-called)

Basically, I needed to move the hub start to be the last thing:

```
// Reference the auto-generated proxy for the hub.  
var notificationsHub;

function SetupNotificationsClient() {
    // Reference the auto-generated proxy for the hub.  
    notificationsHub = $.connection.NotificationsHub;

    //Enable logging (with the generated proxy)
    $.connection.hub.logging = true;

    //Raised before any data is sent over the connection.
    $.connection.hub.starting(function () {
        //let notification = { Title: `Connection Starting` };
        //DisplayUserNotifcation(notification);
        console.log(`Connection Starting`);
    });

    //Raised when any data is received on the connection. Provides the received data.
    $.connection.hub.received(function (data) {
        //let notification = { Title: `Received Message` };
        //DisplayUserNotifcation(notification);
        console.log(`Received Message`);
        console.log(data);
    });

    //Raised when the client detects a slow or frequently dropping connection.
    $.connection.hub.connectionSlow(function () {
        let notification = { Title: `Connection Slow` };
        DisplayUserNotifcation(notification);
        console.log(`Connection Slow`);
    });

    //Raised when the underlying transport begins reconnecting.
    $.connection.hub.reconnecting = function () {
        //let notification = { Title: `Connection Reconnecting` };
        //DisplayUserNotifcation(notification);
        console.log(`Connection Reconnecting`);
    };

    //Raised when the underlying transport has reconnected.
    $.connection.hub.reconnected = function () {
        let notification = { Title: `Connection Reconnected` };
        DisplayUserNotifcation(notification);
        console.log(`Connection Reconnected`);
    };

    //Raised when the connection state changes. Provides the old state and the new state (Connecting, Connected, Reconnecting, or Disconnected).
    $.connection.hub.stateChanged = function () {
        //let notification = { Title: `State Changed` };
        //DisplayUserNotifcation(notification);
        console.log(`State Changed`);
    };

    //Raised when the connection has disconnected.
    $.connection.hub.disconnected(function () {

        if ($.connection.hub.lastError) {
            //let notification = { Title: `Disconnected`, SubTitle: `Reason: ${$.connection.hub.lastError.message}` };
            //DisplayUserNotifcation(notification);
            console.log(`SignalR Disconnected - Reason ${$.connection.hub.lastError.message}`);
        }

        //Try To Reconnect if disconnected
        setTimeout(function () {
            //let notification = { Title: `Attempting to reconnect` };
            //DisplayUserNotifcation(notification);
            console.log(`Attempting to reconnect`);
            $.connection.hub.start();
        }, 5000); // Restart connection after 5 seconds.

    });

    // Create a function that the hub can call back to display messages.
    notificationsHub.client.SendNotificationToUI = function (notification) {
        DisplayUserNotifcation(notification);
        console.log(`SendNotificationToUI`);
    };

    $.connection.hub.error(function (error) {
        console.log('SignalR error: ' + error)
    });

    // Start the connection.
    $.connection.hub.start().done(function () {
        //When a user connects, check the database for unread notifications and send them to them
        console.log(`Connection Started`);
        GetUnreadNotifications();
    });

}
```

**Comment by halter73** [comment]
Glad you resolved the issue! That is an unfortunate gotcha, but longstanding one.

**Comment by euangordon** [comment]
@halter73 thanks for your reply.

Is there a reason the start has to be last? 

It was really strange that it seemed to work perfectly in all browsers and then suddenly broke in the latest Safari version.
