### ISSUE TITLE
Backplane (e.g.: redis) - Send a message to a specific user

### ISSUE THREAD

**Issue by Nordes** [SignalR/SignalR#4568]
I have some issues when using Redis backplane + authorization. I try to send to a specific user but the message does not always go all the way.

### Expected  behavior
When I send a message to a user, if the instance receiving the message is not the same as where the user is connected to, the message should reach him. At least the Hub should try to push to redis and then the notification being received by the other service to push the message to the user.

Side note, it might be the way we implemented SignalR that cause such issue, but still there's almost no code.

### Actual behavior
The connections are only by instance of the service and it does not go to the user. I don't want to do a broadcast, but only target a specific user.

### Steps to reproduce
- Create a hub
- Connect to redis as backplane
- Add authorization (using token)
- Ensure that the identity is set when connecting to the wss
- Have multiple instances of the service + redis (e.g.: using tye)

In the code when you do:
```csharp
 await _myHub.Clients.Users("targetUser").SendAsync("NewNotification", new Notification { Title= "abc", Details = "def" });
```

It does not reach all the instances where the users is connected and sometimes the message is kind of lost.

**Comment by halter73** [comment]
So I take it broadcasts got to all users connected to all server instances?

Are you sure the client(s) belonging to "targetUser" have "targetUser" as their `IPrincipal.Identity.Name` when the connect via SignalR? If not, you can also customize this with a non-default `IUserIdProvider`. If you haven't already, take a look at https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/mapping-users-to-connections#iuserid-provider.

As a diagnostic step, can you try sending to a specific connection id on another server instance and tell us if that works?
