### ISSUE TITLE
How to set minimum message size in signalr?

### ISSUE THREAD

**Issue by Parveen-Mothsara** [SignalR/SignalR#4570]
Hi All,
I am using signalr for stock market ,my message size is only 30byte but ,on client side when i check it will take  approx 2kb/sec bandwidth which is huge.can any one suggest me how to reduce this.
Thanks

**Comment by halter73** [comment]
SignalR tries to keep things pretty compact by using single character property names in the JSON payloads. Have you tried looking at a network trace either using browser F12 tools or something like Wireshark? Can you show us the payloads?
