### ISSUE TITLE
Cross-Site Scripting vulnerability on  jquery.signalR-2.4.2.js

### ISSUE THREAD

**Issue by halm0291** [SignalR/SignalR#4571]
This is not a specific behavior bug, I have an app where Im using Microsoft.AspNet.SignalR.JS, this app is periodically scanned using fortify(https://ams.fortify.com/Docs/en/index.htm) the thing is I updated the signalR packages to the lates version 2.4.0 and now a cross site scripting vulnerability is detected.
 These are the details.
 The method onFailed() in jquery.signalR-2.4.2.js sends unvalidated data to a web browser on lines 680, which can result in the browser executing malicious code.
 The method start() in jquery.signalR-2.4.2.js sends unvalidated data to a web browser on lines 686,576, which can result in the browser executing malicious code.
Wanted to know if you are ware of this, if so, do you have a workaround or a new version comming thats fixes this?
Thanks

**Comment by halter73** [comment]
I looked at these lines:

https://github.com/SignalR/SignalR/blob/48d919685fc2368a9bfe06dbfdcb2dd41c755b45/src/Microsoft.AspNet.SignalR.JS/jquery.signalR.core.js#L576

https://github.com/SignalR/SignalR/blob/48d919685fc2368a9bfe06dbfdcb2dd41c755b45/src/Microsoft.AspNet.SignalR.JS/jquery.signalR.core.js#L680

https://github.com/SignalR/SignalR/blob/48d919685fc2368a9bfe06dbfdcb2dd41c755b45/src/Microsoft.AspNet.SignalR.JS/jquery.signalR.core.js#L686

I'm not seeing the vulnerability. These are just invoking error-handling callbacks defined by SignalR user code. If someone comes up with an explanation why this is a vulnerability, we can look into it.

**Comment by halm0291** [comment]
Hi, I went deeper in the vulnerabilities report and found this.
In the start callback line 462, the protocol is obtained from the window.document.location.protocol;
then the connection object is used at:
 line 773, setConnectionUrl(connection, splitUrlAndQs[0]);
 line 779 onFailed(signalR._.error(resources.jsonpNotSupportedWithAccessToken), connection);
