### ISSUE TITLE
make signal r client call synchronous

### ISSUE THREAD

**Issue by mkumar3010** [SignalR/SignalR#4573]
Is there any way we can make the signalr client call synchronous from signal r hub. any pointers to the documentation is greatly appreciated.

**Comment by BrennanConroy** [comment]
> signalr client call synchronous from signal r hub

Do you mean you want client side return values/acks? So the hub sends a message and waits for the client to finish?
That isn't supported and wont be supported. If you want something like that you'll have to implement a custom solution.

**Comment by mkumar3010** [comment]
@BrennanConroy  - Yes you are right. we wanted to signal a client and want the processed result back to the hub. till then we want the server to wait for the response to come back. if at all we have to make custom solution, which class file needs to be modified any pointers?

**Comment by BrennanConroy** [comment]
Hi. It looks like this is a question about how to use SignalR. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com/) using the signalr tag.

The general idea would be to have a separate hub method that the client calls when it has a result from a previous call.
