### ISSUE TITLE
Xamarin Android Release Build Doesn't Connect

### ISSUE THREAD

**Issue by christoroth** [SignalR/SignalR#4574]
My system:

Visual Studio 2019 v 16.10.3
Dev environment Windows 10, Building Xamarin Forms project for Android 
Project is .Net Standard 2.0

SignalR library version 2.4.2 when nuget, 2.4.3-preview1-t000 when switched to building source
Newtonsoft Json library 11.0 was brought in by the nuget as that's the min version required by SignalR 2.4.2 on standard 2.0 but also tried updating to the latest 13.0 but same behavior.

### Expected  behavior
SignalR Client should connect in Release build the same as Debug build of Xamarin app

### Actual behavior

Start of the HubConnection throws Exception for Internal Server Error so and connection state goes from Connecting to Disconnected.  But only if the app is built as a release build.   

As you'll see below, I believe the 

### Steps to reproduce

Turning off optimize code in my project doesn't help (I thought code optimisation might have messed something up - what else does a release build do that could cause a difference between that and debug?)

I know from searching the internet that others have had the same problem but no solution was found.  In some cases they move to the aspnetcore version of SignalR, others were able to ditch SignalR as something else worked for them.   I don't have either of those options (aspnetcore client is stated to not be compatible with aspnet signalR backend and  I cannot change my backend at this time).

I do not have a simplified app that proves the issue (without my back end it would be tricky anyway) but I have put a couple of days of time into trying to solve the issue and have learned a lot but nothing that leads me to being able to fix it (I've reached the end of my abilities I think):

- First thing to state is that I am/was using the nuget version of this package.  
- Using wireshark I could see that the connectionData json sent as part of the negotiation phase is empty ( [ {} ] ) for the release build and populated with my hub name for the debug build.  
- Looking at the github code I learned more about how it works and extended HubConnection to override the OnSending method (had to also replicate the constructors and supply a copy of GetUrl as that's used by one of the constructors).
- My extended class did not have access to the private _hubs property but I know the name of my hub so I created a local List of HubRegistration objects populated with my name (mimicing the Linq code in the main HubConnection class OnSending method)
- With this I was able to prove that this.JsonSerializeObject does indeed return [ {} ] in release mode but [ { "Name": "myhubname" } ] in debug mode.
- From there I tried hard coding the json that is returned and although that progressed further (I could see the server accept that and return a token), it quickly had a different error, I believe in the deserialisation of the returned json that contains the negotiated token.  

- What followed was building the SignalRClient project for .netStandard 2.0 and adding that to my project instead of the nuget and that continued to show the same behavior.   Using tracing on the hubconnetion object and adding lines of my own I debugged JsonSerializeObject a little more but didn't learn much except that when I got the enumerator from the Linq object and iterated it to prove that JsonSerializeObject had data in it, it started to produce the expected json.  Could it be a timing issue and release build is too fast and my logging code slowed it down enough?!  Regardless it again progressed further and then hit issues elsewhere.

Not sure what code to share but here is what I referred to above:

HubConnection.cs
```
original: 
protected override string OnSending()
        {
            var data = _hubs.Select(p => new HubRegistrationData
            {
                Name = p.Key
            });

            return this.JsonSerializeObject(data);            
        }

  // my attempts at debugging
protected override string OnSending()
        {
            var data = _hubs.Select(p => new HubRegistrationData
            {
                Name = p.Key
            });

            // my debugging code
            Newtonsoft.Json.Serialization.MemoryTraceWriter traceWriter = new Newtonsoft.Json.Serialization.MemoryTraceWriter();

            traceWriter.LevelFilter = System.Diagnostics.TraceLevel.Verbose;

            this.JsonSerializer.TraceWriter = traceWriter;

            data.GetEnumerator().MoveNext();     // attempt to nudge the enumerator (failed)      

            string json = this.JsonSerializeObject(data);
            
            CBMessage += "HubConnection OnSending json is " + json; // added a property as an alternative to tracing so that I could pass messages back to my app

            /*
            if (_hubs != null && _hubs.Count > 0)
            {
                CBMessage += "from  hub name =" + _hubs.Keys.First() + "";
            }

            CBMessage += "\nJsonSerializerFormat=" + this.JsonSerializer.Formatting.ToString();
            CBMessage += "\nJsonTrace=" + traceWriter.ToString();

            this.JsonSerializer.TraceWriter = null;
            */

            return json;
        }
```

And in ConnectionExtensions.cs I tried with JsonSerializeObject - my code commented out which was enough to get the correct json out but I don't know why and doesnt help all the other places where json is used in the library.

```
public static string JsonSerializeObject(this IConnection connection, object value)
        {
            if (connection == null)
            {
                throw new ArgumentNullException("connection");
            }

            /*
            if (value is System.Collections.Generic.IEnumerable<Hubs.HubRegistrationData>)
            {
                System.Collections.Generic.IEnumerable<Hubs.HubRegistrationData> hubsData = value as System.Collections.Generic.IEnumerable<Hubs.HubRegistrationData>;


                String msg = "";
                if (hubsData == null || hubsData.GetEnumerator() == null) msg = "In JsonSerializeObject hubsData is null";
                else
                {
                    msg = "In JsonSerializeObject hubsData is :";
                    System.Collections.Generic.IEnumerator<Hubs.HubRegistrationData> enumerator = hubsData.GetEnumerator();

                    while (enumerator.MoveNext())
                    {
                        Hubs.HubRegistrationData hd = enumerator.Current;
                        msg += hd.Name + ",";
                    }
                }
                connection.Trace(TraceLevels.Messages, msg);
            }
            */

            var sb = new StringBuilder(0x100);
            using (var stringWriter = new StringWriter(sb, CultureInfo.InvariantCulture))
            {
                using (var jsonWriter = new JsonTextWriter(stringWriter) { CloseOutput = false })
                {
                    jsonWriter.Formatting = connection.JsonSerializer.Formatting;
                    connection.JsonSerializer.Serialize(jsonWriter, value);
                }

                return stringWriter.ToString();
            }
        }

```

We're about to ship a debug version of our app to a customer which is not something I do lightly.  As you can see, I'm willing to investigate further but I now don't know where to turn.  If anyone can run with it that'd be fantastic but if not, some questions/suggestions that point me on a path would be great (I have drawn the line at getting the json code but digging into that would be the next logical step wouldn't it?...).

Thank you for any responses at all!

**Comment by christoroth** [comment]
We have solved the issue but I am still very curious as to why it worked (appreciate this is the issues list for the SignalR library though, not Xamarin or the Json library).

Our Xamarin Forms Android Project was set to link sdk+user assemblies.    Changing it to link Sdk assemblies only for our release build worked.    Could it be that a dependency of Newtonsoft Json was not being linked in but somehow that didn't crash the code, just made it return empty json strings?  

My knowledge of build processes isn't sufficient to know the answer!   

Leaving open in-case someone can shed light on it (it does still seem like there's a problem somewhere, you could end up in a situation where this needs linking that way but something else requires it set differently?) but if anyone feels it should be closed, that's fair enough.

**Comment by halter73** [comment]
I'm glad you found the solution in just trimming the SDK and not user assemblies.

> Could it be that a dependency of Newtonsoft Json was not being linked in but somehow that didn't crash the code, just made it return empty json strings?

It could be that. Another common thing you'll see when trimming code that serializes to JSON is empty objects (`{}`). Trimming non-SDK code is probably causing properties of SignalR's and your Hub's DTOs to be trimmed that aren't explicitly referenced even though they're needed by the client. Since Newtonsoft.Json uses reflection to serialize all the properties, the trimmer can not see these properties are actually referenced.
