### ISSUE TITLE
[Question] Should Blazor webassembly pages always create its own HubConnection?

### ISSUE THREAD

**Issue by drakeforte5** [SignalR/SignalR#4575]
Just need a clarification.

Looking at samples and docs and it seems a HubConnection is always created per Blazor webassembly page.  It seems this creates multiple client connections per app if there are multiple pages with signalr connection then a lot of users then client connections would just baloon I would imagine.

Should the practice be to create the HubConnection during the client app startup and inject it so that it can be reused by all the pages in the app.  That  is what I would do if I were using any messaging library.  One connection with multiple subscriptions but I'm not sure if signlar works this way.

Thanks.

**Comment by BrennanConroy** [comment]
> Should the practice be to create the HubConnection during the client app startup and inject it so that it can be reused by all the pages in the app

Probably something like that.

This is the wrong repo, any issues with ASP.NET Core SignalR or Blazor should be filed at https://github.com/dotnet/aspnetcore
