### ISSUE TITLE
Connection ends in Blazor WASM

### ISSUE THREAD

**Issue by AndersMalmgren** [SignalR/SignalR#4577]
I have a ,NET 5.0 signalr client working both for .NET Core 5.0 client and for Blazor WASM. 

 I configure the clients exactly the same. But in Blazor WASM the conenction dies after a while while in the Core 5.0 client app the connection remains intact.

Here is how I handle connections 

https://github.com/AndersMalmgren/SignalR.EventAggregatorProxy/blob/master/SignalR.EventAggregatorProxy.Client.DotNetCore/Bootstrap/Factories/HubProxyFactory.cs

The Blazor WASM bootstrap

https://github.com/AndersMalmgren/SignalR.EventAggregatorProxy/blob/master/SignalR.EventAggregatorProxy.Demo.BlazorWasm/Client/Program.cs

Its identical to how I setup in Core 5.0 client app

https://github.com/AndersMalmgren/SignalR.EventAggregatorProxy/blob/master/SignalR.EventAggregatorProxy.Demo.DotNetCore/Bootstrap/Bootstrapper.cs

WASM is a bit of a blackbox and I do not know more than that the connection dies. (The disconnect events trigger on the server)

**Comment by AndersMalmgren** [comment]
If you want to try the demo you can find it here, 

https://github.com/AndersMalmgren/SignalR.EventAggregatorProxy/blob/master/SignalR.EventAggregatorProxy.Demo.sln

**Comment by BrennanConroy** [comment]
ASP.NET Core SignalR issues should be filed at https://github.com/dotnet/aspnetcore

Are you using chrome and is the tab not active when the connection dies? If yes, then you're likely hitting the chrome timer throttling issue https://github.com/dotnet/runtime/issues/51041
