### ISSUE TITLE
SignalR with Redis backplane causes increase in server and Redis load

### ISSUE THREAD

**Issue by JGdalevich** [SignalR/SignalR#4580]
Hello,

This could be related to #4578 or could be a different issue.

We are running an ASP.NET Web application on two Windows Servers. Each server has a SignalR message server with nine different hubs for different types of messages. Normally, both servers should run behind a load balancer using Redis as a SignalR backplane.

When both servers are running together, the amount of data in Redis keeps increasing and the amount of memory each server is using keeps growing until some applications stop working or there are noticeable delays in the clients receiving messages. This could take anywhere from one day to one week.

Network profile of Redis. Falls are when the app pool recycles:
https://i.stack.imgur.com/hyBMj.png

Memory on the server before it starts having problems. SignalR is taking up most of it:
https://i.stack.imgur.com/HrOZ6.png

There are no problems when either of the servers is running by itself (no backplane).  There are no exceptions or errors in the server logs and we cannot reproduce the issue in another environment including with load testing with a significantly higher number of clients and messages.

We are using:
- .NET Framework 4.7.1
- ASP.NET SignalR version 2.4.2 (JS and .NET clients also use the same version)
- `StackExchange.Redis` version 2.2.62 (previously used `StackExchange.Redis.StrongName` 1.2.6)
- Redis server 3.2.12 - cluster support disabled

Our setup:
- Two servers active behind a proxy/load balancer
- Each server has its app pool recycled once per day at different times
- Few hundred SignalR JS and SignalR.NET clients at any given time, each connected to one or more hubs
- The total number of clients goes up and down through out the day but is constant from day to day
- Not using sticky sessions (this is necessary with .NET Core but not with ASP)
- Only web socket protocol is used
- Different channels in Redis are used for other messages between servers like when a client connects or disconnects

```
     GlobalHost.Configuration.ConnectionTimeout = TimeSpan.FromSeconds(110);
     GlobalHost.Configuration.DisconnectTimeout = TimeSpan.FromSeconds(30);
     GlobalHost.Configuration.KeepAlive = TimeSpan.FromSeconds(10);
     GlobalHost.Configuration.DefaultMessageBufferSize = 32;  // This is the minimum size

     GlobalHost.DependencyResolver.UseStackExchangeRedis(new RedisScaleoutConfiguration(RedisHostName, RedisAppNameKey));

     var hubConfiguration = new HubConfiguration { EnableDetailedErrors = true };

     app.MapSignalR(hubConfiguration);
```

Looking at SignalR Redis messages, we noticed that some are being duplicated multiple times. Looking at the proxy logs, we noticed there are continuous SignalR `abort` and `negotiate` messages even with one server running. When logging client connects and disconnects, there are sometimes duplicate connections for the same `ConnectionId` for the same Hubs.

We took a SignalR trace of both servers for about an hour. `bus.log.txt` is clean with no exceptions until the app pool was recycled. `transports.log.txt` has multiple exceptions all through the log on both servers.

```
SignalR.Transports.WebSocketTransport Error: 0 : OnError(c1861e14-03c8-40d9-a81e-a4e8b10cd361, System.Net.WebSockets.WebSocketException (0x80070026): Reached the end of the file
   at System.Web.WebSockets.WebSocketPipe.<>c__DisplayClass9_0.<ReadFragmentAsync>b__0(Int32 hrError, Int32 cbIO, Boolean fUtf8Encoded, Boolean fFinalFragment, Boolean fClose)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.WebSockets.AspNetWebSocket.<DoWork>d__45`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.WebSockets.AspNetWebSocket.<>c__DisplayClass36_0.<<ReceiveAsyncImpl>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SignalR.WebSockets.WebSocketMessageReader.<ReadMessageAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SignalR.WebSockets.WebSocketHandler.<ProcessWebSocketRequestAsync>d__25.MoveNext())
SignalR.Transports.WebSocketTransport Information: 0 : CloseSocket(c1861e14-03c8-40d9-a81e-a4e8b10cd361)
```

```
SignalR.Transports.WebSocketTransport Error: 0 : OnError(d8f299ca-d658-40e8-af83-ba4bbc0166f2, System.Net.WebSockets.WebSocketException (0x800703E3): The I/O operation has been aborted because of either a thread exit or an application request
   at System.Web.WebSockets.WebSocketPipe.<>c__DisplayClass9_0.<ReadFragmentAsync>b__0(Int32 hrError, Int32 cbIO, Boolean fUtf8Encoded, Boolean fFinalFragment, Boolean fClose)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.WebSockets.AspNetWebSocket.<DoWork>d__45`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.WebSockets.AspNetWebSocket.<>c__DisplayClass36_0.<<ReceiveAsyncImpl>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SignalR.WebSockets.WebSocketMessageReader.<ReadMessageAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SignalR.WebSockets.WebSocketHandler.<ProcessWebSocketRequestAsync>d__25.MoveNext()
```

Here are the links to the SignalR trace files from one of the two server.  They are over one hour of both servers running.
https://drive.google.com/file/d/1yLdVwK0e6HHzbEnD-w54Jr3kRmpMi74C/view?usp=sharing
https://drive.google.com/file/d/1Jz9lq8afLHWklTu1GiJ0QSCnmErxCqCi/view?usp=sharing

837 cases of `“in New”` vs. 457 cases of `“Removing connection”` on this one server but we are not sure why.  If the clients were making multiple connections, we would expect to see it one a single server with no Redis as well.

**Comment by halter73** [comment]
> When logging client connects and disconnects, there are sometimes duplicate connections for the same ConnectionId for the same Hubs.

Is this in the linked logs. Any specific ConnectionId we should look at?

The memory usage on the server doesn't seem that crazy given the number of clients and hubs and the large size of some of the messages. If you wanted to control that, you could look at chunking up the larger messages and/or adjusting the DefaultMessageBufferSize to be lower than it's default of 1000. Just note that if you send messages quickly enough clients might miss messages if this is configured too low especially if their reconnecting.

https://docs.microsoft.com/en-us/aspnet/signalr/overview/performance/signalr-performance#tuning-your-signalr-server-for-performance

I don't have any great theories for the increased bandwidth usage between SignalR and Redis. Do you see a corresponding increase in the rate of SignalR message bus logs? I wonder if a network capture might be enlightening.

**Comment by JGdalevich** [comment]
Thank you very much for your reply.  I really appreciate you looking at this issue.

> Is this in the linked logs? Any specific ConnectionId we should look at?

This is in our application logs where I log each SignalR connect and disconnect.  I am seeing the same ConnectionID connecting multiple times.  I am not sure how helpful those logs would be since they are specific to our application.

Our current `DefaultMessageBufferSize` is 32 (the minimum) to reduce the memory footprint.  Large messages are very rare.  Usually a few times a day.  Most messages are relatively small (100 characters).  What I can do is change the large messages to go over REST if that will improve anything with SignalR.  Do you think that is a good idea?

The issue with memory is that it keeps increasing over time even when the number of SignalR clients is relatively constant.  It goes down at night and back up during the day but the max number is the same.  It almost looks like there is a memory leak somewhere where disconnected clients are not being cleaned up correctly.

The strange part is that everything works great and the memory growth corresponds to the user count if the backplane is turned off. I am actually considering  setting up a separate server just for SignalR  and letting the other servers shared other tasks like REST.

> Do you see a corresponding increase in the rate of SignalR message bus logs?

I wasn't able to run it log enough due to space constraints.  The issues become visible after several days and the bus logs grow at about 1 GB an hour.

> I wonder if a network capture might be enlightening.

I should try that.  The only network logs I have are from our Proxy where there are a large number of SignalR `abort` and `negotiate` messages.  Not sure if that is a problem since they occur when running on a single server as well.

One other piece of data that I have is a message trace from Redis.  This is a growth over time of heartbeat SignalR messages (pings) that each client receives every 15 seconds.  The number of clients is relatively constant and would go down in the evening.
![image](https://user-images.githubusercontent.com/7634486/132031326-19e2b8cb-2004-43a1-a47c-a1a803fce614.png)

1. Do the exceptions in the SignalR traces mean anything?  Are they "normal" or is this something I need to fix?
2. Is it acceptable to have constant SignalR `abort` and `negotiate` messages?  If not, what kind of issue could this be?
3. Do you recommend sending large messages (few MB) over REST instead of SignalR?
4. I am sending user connects and disconnect Redis messages so each server knows all of the SignalR users connected to it (see need this for business reasons).  Is it a good idea to use the same Redis server, but different channels for non-SignalR messages?
5. Do you recommend a `DefaultMessageBufferSize` to start with?  
6. Are there other settings I could change?

**Comment by halter73** [comment]
> 1. Do the exceptions in the SignalR traces mean anything? Are they "normal" or is this something I need to fix?

The exceptions that I saw in the logs looked like pretty normal network issues. Sometimes there are exceptions produced for what should be clean disconnects. But if you have any exceptions in particular that you are concerned about, please point them out.

> 2. Is it acceptable to have constant SignalR abort and negotiate messages? If not, what kind of issue could this be?

That's an indication that clients are disconnecting (either through an explicit call to `.stop()` on the client or someone closing a browser tab) and creating brand-new connections at a rapid rate.

I wonder if single clients are establishing multiple concurrent SignalR connections somehow.

> 3. Do you recommend sending large messages (few MB) over REST instead of SignalR?

That could be a good mitigation. We've had customers succeed sending messages this large, but obviously it depends on the application and usage. Another option might be to return the large messages from a Hub method rather than using `Clients.Caller` or something similar since returned-values don't go to the backplane.

> 4. I am sending user connects and disconnect Redis messages so each server knows all of the SignalR users connected to it (see need this for business reasons). Is it a good idea to use the same Redis server, but different channels for non-SignalR messages?

It would probably be best to use different servers for presence and the SignalR backplane for diagnostic purposes if nothing else.

I encourage you to take a look at this sample [PresenceMonitor](https://github.com/DamianEdwards/NDCLondon2013/blob/0a2fdb6aa408859a2824abfe883c0554a7384cdc/UserPresence/PresenceMonitor.cs) that checks the `ITransportHeartbeat` on an interval on each server to observe all the connected clients and then updates a central database. This uses SQL, but it should be easy enough to update it to use Redis.

This is nice because it's resilient to restarts and reconnects and stuff like that which can make it difficult to properly detect disconnects. Instead, clients get removed if they haven't been seen for a long enough period. The `UserTrackingHub` in the project checks for disconnects more proactively, but I recommend using the newer `OnDisconnected(bool stopCalled)` overload and only stop tracking if `stopCalled` is true. Otherwise, it's possible the client may still reconnect.

> 5. Do you recommend a DefaultMessageBufferSize to start with?

If the messages are small, I think the 1000 is a good default (which is the default IIRC), but with relatively infrequent large messages I can see wanting to reduce it. Especially considering how much memory in the process was being used by MessageStores.

> 6. Are there other settings I could change?

Reducing `IConfigurationManager.MaxScaleoutMappingsPerStream` could reduce the size of the `ScaleoutMappingStore`s you see in your dump. This could make it less likely that reconnecting clients get messages replayed, but you can estimate how likely this is to be a problem using this formula

```
Time spent reconnecting before missing messages = MaxScaleoutMappingsPerStream / (rate of all messages sent over the backplane)
```

---

I think point #2 could be the big clue though. Are you getting more SignalR connections than clients? How are you measuring the rate of SignalR pings?

**Comment by JGdalevich** [comment]
Thank you very much for the info.  This is very helpful.  We are getting more SignalR connections than clients.  The messages measure is from Redis.  We just counted the amount of specific SignalR messages over time in the `signalr` Redis channel.

**Comment by JGdalevich** [comment]
Thank you very much for all of your help.  We decided to move away for SignalR so I am closing this issue.
