### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by nssidhu** [SignalR/SignalR#4581]
I am using Blazor WebAssembly where in a page I am using Timer to poll my WebAPI to check for data every 30 seconds.
Usually my Api calls returns in 300 ms to 1 second. 
But in case it takes longer than 30 seconds i can manually suppress next timer call to skip and wait for configure 30 second before initiating another call.
so no matter how long my Web API takes i always prevent overlapping calls and always able to tack on 30 seconds after the last API call returns.

Was wonder if I replace my timer code with SingalR  Long-Polling feature to cover all aspects of above mentioned use case ?
Can I configure the interval of long polling ?
Is there a way to prevent overlapping call if the previous call has not returned yet ?
Is Long Polling configured on server or both on client and server.
Can i have Mix of Long-Polling and Realtime (i.e. some pages use real-time and other use Long Polling)
(May by having two SignalR hub on Server one configured to Real-Time and another for Long-Polling) ?

When using Long Polling Only, would i need to deploy on Azure SignalR service ?

**Comment by halter73** [comment]
As @JGdalevich suggest, this isn't the right repo for SignalR Core and Blazor questions. These kind of questions are generally better for https://stackoverflow.com. If there are any product issues, you can file them at https://github.com/dotnet/aspnetcore.

I don't think it makes sense to use SignalR to query your WebAPI. If you want to replace your WebAPI endpoint with a SignalR Hub method, that might make sense. Also, long polling is real-time. It's just not as efficient as WebSockets. I wouldn't try forcing a specific transport without a really good reason.
