### ISSUE TITLE
How to distinguish the jquey library corresponding to the version?

### ISSUE THREAD

**Issue by bbhxwl** [SignalR/SignalR#4584]
I used asp.net core 3.1 to create a signalr. I tried to connect with JavaScript without any problem. I couldn't send messages. I checked for an hour to find out that it was jquery3 that was used, so I could use jQuery 1.6 normally. I don't know what version my server uses, what version of jquery corresponds to, and where can I view the version?

**Comment by JGdalevich** [comment]
Hi,

If you are using Core, this is not the right version of SIgnalR for you.

You need to use https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?WT.mc_id=dotnet-35129-website&view=aspnetcore-5.0&tabs=visual-studio
and https://github.com/aspnet/AspNetCore/tree/main/src/SignalR 

My understanding is that jQuery is no longer required with Core.

**Comment by halter73** [comment]
This (non-Core) version of SignalR depends on jQuery 1.6.4 or higher. You can look at the minimum version for jQuery dependency on [nuget](https://www.nuget.org/packages/Microsoft.AspNet.SignalR.JS/) or [npm](https://www.npmjs.com/package/signalr).

That said, if you're using asp.net core 3.1, @JGdalevich is right that there is no jQuery dependency at all.
