### ISSUE TITLE
Asp.net Core 3.1 SignalR Web Socket Windows 7 Connection Problem

### ISSUE THREAD

**Issue by JarvisPos** [SignalR/SignalR#4585]
Hello,

3 days ago, we moved our asp.net core 3.1 signalr websocket project running on iis 10 version to aws container service. It broadcasts on Kestrel. We structured our project as follows. Sockets client application running on windows 10 is working, but we are getting an error in the application running on windows 7. error message "No requested transports available on the server." can you help us?

Server : Asp.net core 3.1 Startup.cs

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using AspNetCoreRateLimit;
using JarvisPos.DataAccess.Context;
using JarvisPos.Service.BaseQuartz;
using JarvisPos.Service.Helper;
using JarvisPos.Service.Middleware;
using JarvisPos.Service.Services;
using JarvisPos.Service.SignalR;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.FileProviders;
using Quartz;
using StackExchange.Profiling.Storage;

namespace JarvisPos.Service
{
    public class Startup
    {
        public Startup(IConfiguration configuration, IWebHostEnvironment env)
        {
            Configuration = configuration;
            _env = env;
        }

        private readonly IWebHostEnvironment _env;
        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            QuartzCall.UserQuartz(services, typeof(QuartzJob));
            //services.AddControllersWithViews();
            //services.AddSingleton<IActionContextAccessor, ActionContextAccessor>();
            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });
            services.AddControllers();

            services.AddCors(options =>
            {
                options.AddPolicy("CorsPolicy",
                    builder =>
                    builder
                    .AllowAnyOrigin()
                    .AllowAnyMethod()
                    .AllowAnyHeader());
            });

            services.AddDbContext<JarvisPosContext>(options =>
            {
                options.UseNpgsql(Configuration.GetConnectionString("JarvisPosConnectionPostgresql"),
                    b => b.MigrationsAssembly("JarvisPos.DataAccess"));
            });

            //services.AddSingleton<IDatabaseChangeNotificationService, SqlDependencyService>();
            services.AddSignalR(
                hubOptions =>
                {
                    hubOptions.EnableDetailedErrors = true;
                    hubOptions.KeepAliveInterval = TimeSpan.FromSeconds(3);
                }).AddStackExchangeRedis("");

            services.AddMvc().AddNewtonsoftJson();

            services.AddOptions();
            services.AddMemoryCache();

            services.Configure<ClientRateLimitOptions>(Configuration.GetSection("ClientRateLimiting"));
            services.Configure<ClientRateLimitPolicies>(Configuration.GetSection("ClientRateLimitPolicies"));
            services.AddSingleton<IClientPolicyStore, MemoryCacheClientPolicyStore>();
            services.AddSingleton<IRateLimitCounterStore, MemoryCacheRateLimitCounterStore>();
            services.AddHttpContextAccessor();
            services.AddSingleton<IRateLimitConfiguration, RateLimitConfiguration>();
            services.AddControllers();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseRequestResponseLogging();

            app.UseMiniProfiler();
            app.UseRouting();
            app.UseClientRateLimiting();
            app.UseCors("CorsPolicy");

            app.UseAuthentication();

            app.UseEndpoints(routes =>
            {
                routes.MapHub<TableHub>("/table");
                routes.MapHub<PrinterHub>("/printer");
                routes.MapHub<CallCenterHub>("/callcenter");
                routes.MapHub<CallerIdHub>("/callerid");
                routes.MapHub<SystemHub>("/system");
                routes.MapHub<ScalesHub>("/scales");
                routes.MapHub<CustomerScreenHub>("/customerscreen");
                routes.MapHub<TrackHub>("/track");
                routes.MapHub<PendingPackageHub>("/pendingpackage");
                routes.MapControllerRoute("DefaultRoute", "api/{controller}/{action}");
            });

            //app.UseMiddleware<AuthenticationMid>();
            //app.UseCorsMiddleware();

            app.UseWebSockets();
            //notificationService.Config();

            var scheduler = app.ApplicationServices.GetService<IScheduler>();
            QuartzServiceUtility.StartJob<QuartzJob>(scheduler);
        }
    }
}

Client Code : Microsoft.AspNetCore.SignalR.Client.Core, Version=6.0.0.0

Guid userId = Guid.NewGuid();
                string brandId = emp.CenterBrandId;
                conPrinter = new HubConnectionBuilder()
                 .WithUrl($"",
                 options =>
                 {
                     options.SkipNegotiation = true;
                     options.Transports = Microsoft.AspNetCore.Http.Connections.HttpTransportType.WebSockets;
                 })
                 .WithAutomaticReconnect(new RandomRetryPolicy())
                 .Build();

Issues related to the Asp.NET Core version of SignalR should be filed in the AspNetCore repo: https://github.com/aspnet/AspNetCore/issues/new/choose
Please remove this line and the line above before submitting a new issue.

**Comment by JGdalevich** [comment]
If you are using Core, this is not the right version of SignalR for you.

You need to use https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?WT.mc_id=dotnet-35129-website&view=aspnetcore-5.0&tabs=visual-studio
and https://github.com/aspnet/AspNetCore/tree/main/src/SignalR

**Comment by JarvisPos** [comment]
@JGdalevich SignalR Server => Asp.Net Core Api 3.1 - Desktop Client .Net Framework 4.7

I will try and inform for the server Microsoft.AspNetCore.SignalR

**Comment by JGdalevich** [comment]
SignalR ASP.NET and SignalR ASP.NET Core use different protocols.  Your .NET client also needs to be Core to talk to your new server.

**Comment by JarvisPos** [comment]
@JGdalevich my problem is solved thank you very much
