### ISSUE TITLE
Blazor Wasm Connection Status Change events ?

### ISSUE THREAD

**Issue by nssidhu** [SignalR/SignalR#4586]
I am using Blazor Wasm and was trying to figure out is there are events to notify when connection state changes ?
Any links to example of that in Blazor WASM .
something like what is available in JavaScript 
https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/handling-connection-lifetime-events#how-to-notify-the-user-about-disconnections

Also is there option to automatically disconnect client after  say 7 PM ?

**Comment by JGdalevich** [comment]
I am not sure about Blazor WASM.  Does it not require .NET Core?

There is no way for a SignalR server to disconnect a client.  A work-around is to have the server call a client method that will do the disconnect from the client.

**Comment by nssidhu** [comment]
Yes, current version run on runs on .Net 5/6.I was looking to subscribe to connection state change events.


Sent from Yahoo Mail for iPhone


On Wednesday, September 1, 2021, 10:03 AM, Jonathan Gdalevich ***@***.***> wrote:




I am not sure about Blazor WASM. Does it not require .NET Core?

There is no way for a SignalR server to disconnect a client. A work-around is to have the server call a client method that will do the disconnect from the client.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JGdalevich** [comment]
If you are using Core, this is not the right version of SignalR for you.

You need to use https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?WT.mc_id=dotnet-35129-website&view=aspnetcore-5.0&tabs=visual-studio
and https://github.com/aspnet/AspNetCore/tree/main/src/SignalR

**Comment by nssidhu** [comment]
Thanks for providing that information.
