### ISSUE TITLE
Client unable to receive message with Jquery v3.6.0

### ISSUE THREAD

**Issue by eeldivad** [SignalR/SignalR#4587]
### Expected  behavior
I have Chrome opened on my Windows 10 machine and Chrome opened on my Windows server 2019 machine.  When I type a message and click send, it sends to the hub service and the hub service simply calls
Clients.All.addMessage(message);

So this should tell all clients to display the message.

### Actual behavior
It only sends the message to Windows 10 Chrome machines, but not any of my Windows Server 2019 with Chrome.  I tried multiple combinations and the message never arrives on Server 2019.  

### Steps to reproduce
`
Create a simple hub method
        public void Send(string message) {
            Clients.All.addMessage(message);
        }

Clientside code:
            testHub.on("addMessage", function (message) {
                $('#logs').append(message);
            });
`
- Chrome Version 93.0.4577.63 (Official Build) (64-bit)
- jquery.signalR.js version 2.4.2
- jquery 3.6.0
- Open Chrome browser on Windows 10 and another one on Windows Server 2019
- You will notice the message reaches the Windows 10 machine but not Server 2019

If I downgrade jquery to v2.1.3 then it works as expected.  Please fix issue related to latest jquery 3.6.0

**Comment by BrennanConroy** [comment]
We haven't seen other reports of this and given it seems to be machine specific we will close for now. If there are more reports of this sort of problem or if there are more in-depth details we can reopen.
