### ISSUE TITLE
nuget can't be restored

### ISSUE THREAD

**Issue by JorgeEscobarTruextend** [SignalR/SignalR#4588]
Issues related to the Asp.NET Core version of SignalR should be filed in the AspNetCore repo: https://github.com/aspnet/AspNetCore/issues/new/choose
### Expected  behavior
Download the repo and run build.cmd, Code builds fine

### Actual behavior

C:\Users\me\.dotnet\x64\sdk\2.1.302\NuGet.targets(114,5): error : Unable to load the service index for source https://dotnet.myget.org/F/aspnetcore-tools/api/v3/index.json. [F:\work\Issues\SignalR-dev\SignalR-dev\Microsoft.AspNet.SignalR.sln]
C:\Users\me\.dotnet\x64\sdk\2.1.302\NuGet.targets(114,5): error :   The SSL connection could not be established, see inner exception. [F:\work\Issues\SignalR-dev\SignalR-dev\Microsoft.AspNet.SignalR.sln]
C:\Users\me\.dotnet\x64\sdk\2.1.302\NuGet.targets(114,5): error :   The remote certificate is invalid according to the validation procedure. [F:\work\Issues\SignalR-dev\SignalR-dev\Microsoft.AspNet.SignalR.sln]

Build FAILED.

### Steps to reproduce

Having Visual Studio 2015 and 2019  installed

**Comment by BrennanConroy** [comment]
We aren't referencing that feed anymore, looks like you're using an old version of the repo.
See https://github.com/SignalR/SignalR/pull/4527 where we updated the feeds.
