### ISSUE TITLE
What is the compatibility of signalr in web browsers

### ISSUE THREAD

**Issue by bbhxwl** [SignalR/SignalR#4589]
What is the compatibility of signalr in web browsers

If you use IE8 or the IE browser of XP system, will Ajax polling be used automatically? Or can't you use it?

**Comment by JGdalevich** [comment]
You can't use websockets in IE8 but long-polling should work.  SignalR will negotiate the best protocol to support for your browser/system.

**Comment by bbhxwl** [comment]
> You can't use websockets in IE8 but long-polling should work. SignalR will negotiate the best protocol to support for your browser/system.

Is the mode automatically selected?

**Comment by JGdalevich** [comment]
> Is the mode automatically selected?

Yes, unless you force it.

**Comment by bbhxwl** [comment]
> > Is the mode automatically selected?
> 
> Yes, unless you force it.

Then how did I hear that the new signalr core no longer supports IE? Others say they support it. I don't know whether I support it or not.

**Comment by JGdalevich** [comment]
This GitHub is for the "old" version of SignalR which does support IE. See https://docs.microsoft.com/en-us/aspnet/signalr/overview/getting-started/supported-platforms for details.  Officially, it is only supported on IE11 as Microsoft no longer supports older version.  The problem could be with jQuery because it officially supports IE9 or later.  It may be that for IE8, you will not be able to updated SignalR and/or jQuery.

SignalR Core supports IE11.  The JS client uses ES6 which is not supported on earlier IE versions.

**Comment by BrennanConroy** [comment]
Thanks for helping here @JGdalevich, looks like this has been answered.

**Comment by bbhxwl** [comment]
> This GitHub is for the "old" version of SignalR which does support IE. See https://docs.microsoft.com/en-us/aspnet/signalr/overview/getting-started/supported-platforms for details. Officially, it is only supported on IE11 as Microsoft no longer supports older version. The problem could be with jQuery because it officially supports IE9 or later. It may be that for IE8, you will not be able to updated SignalR and/or jQuery.
> 
> SignalR Core supports IE11. The JS client uses ES6 which is not supported on earlier IE versions.

Why doesn't the signalr of the latest asp.net core support the old version of IE? Does the new version have Ajax polling? I'm using translation software. The description may not be very accurate.

**Comment by JGdalevich** [comment]
Microsoft no longer supports IE in favor of Edge.  At some point, one has to stop supporting old technology.

**Comment by bbhxwl** [comment]
> This GitHub is for the "old" version of SignalR which does support IE. See https://docs.microsoft.com/en-us/aspnet/signalr/overview/getting-started/supported-platforms for details. Officially, it is only supported on IE11 as Microsoft no longer supports older version. The problem could be with jQuery because it officially supports IE9 or later. It may be that for IE8, you will not be able to updated SignalR and/or jQuery.
> 
> SignalR Core supports IE11. The JS client uses ES6 which is not supported on earlier IE versions.

This version can be compared with ASP Net core with signalr? I want to be compatible with the old version ie.
