### ISSUE TITLE
SignalR disconnects Server send events under corporate network (proxies and stuff). SignalR stops conection (long-polling in our case) right after it was established. 

### ISSUE THREAD

**Issue by satish2832** [SignalR/SignalR#4590]
We experience similar behaviour 100% under corporate network (proxies and stuff). SignalR stops conection (long-polling in our case) right after it was established. we are using version 2.4.1

**Comment by BrennanConroy** [comment]
Please provide information about what you're seeing.

If your app is at 100% then it might not be able to accept new connections so you might want to fix your app first.

**Comment by satish2832** [comment]
Its working in all regular cases .. 99% cases ..signalr choosing serversentevents , But 1% cases its choosing longpolling as transport , It was connected but immediately closing after 5 seconds ..and its not connecting back again.

Its happening only in some customer networks (not every one). suing 2.4.1 version now

**Comment by satish2832** [comment]
Any thing missed here ? , can u reply on my issue

**Comment by satish2832** [comment]
@BrennanConroy Please update me , what would be the issue here .

**Comment by JGdalevich** [comment]
@satish2832 It might help if you could get SignalR traces from the server and the client that is having issues.  See https://docs.microsoft.com/en-us/aspnet/signalr/overview/testing-and-debugging/enabling-signalr-tracing

Also, are all of your clients doing long-polling?  Are they browsers or do you have C#/Java/etc. clients?  We also has an issue with long-polling at one point but switching to websockets "fixed" it.

What is the CPU and memory load on your server?  How many servers are you running?  Is there a backplane?

Finally, there is a known bug with SignalR 2.4.1 and Chrome that is fixed in 2.4.2.  You might want to try to upgrade to it.

**Comment by satish2832** [comment]
@JGdalevich 99% of users connecting to the serversentevents transport protocol, and very few signalr trying to connect with long polling , But its immediately getting disconnected after 5 seconds .. and no connection establishing with signalr..its only for few users.. Upgraded to 2.4.2 .But facing same issue

**Comment by satish2832** [comment]
@BrennanConroy Please check this below log

[16:09:28 GMT-0500 (Eastern Standard Time)] SignalR: Client subscribed to hub 'chat'. jquery.signalR-2.0.0.js:75
[16:09:28 GMT-0500 (Eastern Standard Time)] SignalR: Negotiating with '/signalr/negotiate?connectionData=%5B%7B%22name%22%3A%22chat%22%7D%5D&clientProtocol=1.3'. jquery.signalR-2.0.0.js:75
[16:09:28 GMT-0500 (Eastern Standard Time)] SignalR: Attempting to connect to SSE endpoint 'http://mysubdomain.mydomain.com/signalr/connect?transport=serverSentEvents&con…bYUr2xEEBuw%3D%3D&connectionData=%5B%7B%22name%22%3A%22chat%22%7D%5D&tid=6'. jquery.signalR-2.0.0.js:75
[16:09:33 GMT-0500 (Eastern Standard Time)] SignalR: serverSentEvents timed out when trying to connect. jquery.signalR-2.0.0.js:75
[16:09:33 GMT-0500 (Eastern Standard Time)] SignalR: EventSource calling close(). jquery.signalR-2.0.0.js:75
[16:09:33 GMT-0500 (Eastern Standard Time)] SignalR: This browser supports SSE, skipping Forever Frame. jquery.signalR-2.0.0.js:75
[16:09:33 GMT-0500 (Eastern Standard Time)] SignalR: Opening long polling request to 'http://mysubdomain.mydomain.com/signalr/connect?transport=longPolling&connecti…bYUr2xEEBuw%3D%3D&connectionData=%5B%7B%22name%22%3A%22chat%22%7D%5D&tid=2'. jquery.signalR-2.0.0.js:75
[16:09:33 GMT-0500 (Eastern Standard Time)] SignalR: Long poll complete. jquery.signalR-2.0.0.js:75
[16:09:33 GMT-0500 (Eastern Standard Time)] SignalR: LongPolling connected.

and its bit urgent ,please respond on this.

**Comment by satish2832** [comment]
@jonathanptew Please check my above logs

**Comment by satish2832** [comment]
Hey everyone, my client is having issues with using SignalR on one of my websites. The site works for other clients but not this one, I assumed it was some kind of firewall/VPN issue (still may be) but it seems to work for some people on their network, but not others.

This led me to believe maybe it was something on the local environment, maybe antivirus or something else?

Does anyone have any idea what would be causing the client to abort? as I cannot find any details on what causes this to fire. I know it will cause the connection to drop, which is what we are seeing.

What could be the issue here ?

**Comment by halter73** [comment]
Those logs make it appear the client stayed connected. Is that not the case? What evidence is there of disconnection. If SSE is problematic, you can just disable it so you don't have the 5 second timeout.

**Comment by Akshaymane71** [comment]
> Hey everyone, my client is having issues with using SignalR on one of my websites. The site works for other clients but not this one, I assumed it was some kind of firewall/VPN issue (still may be) but it seems to work for some people on their network, but not others.
> 
> This led me to believe maybe it was something on the local environment, maybe antivirus or something else?
> 
> Does anyone have any idea what would be causing the client to abort? as I cannot find any details on what causes this to fire. I know it will cause the connection to drop, which is what we are seeing.
> 
> What could be the issue here ?

Hi satish I am also experiencing same behaviour, my webapp is working on customer side but not on my side, did too many R&D & found error signalr calls       /signalr/connect /signalr/poll    /signalr/reconnect.

**Comment by Akshaymane71** [comment]
> We experience similar behaviour 100% under corporate network (proxies and stuff). SignalR stops conection (long-polling in our case) right after it was established. we are using version 2.4.1

@JGdalevich @satish2832  @BrennanConroy 
Hi I am also experiencing same issue we are using signalr 2.4.3 library in our application. most of Indian region client could not able to connect means receive messages from server {here signalr comes into picture} while trouble shooting app service & we found that error signalr calls /signalr/connect /signalr/poll /signalr/reconnect. 

we also check with ISP for any proxy blocking for that we have bypassed our firewall also but the still issue persists.
I don't know what is issue exactly ? please help us. I am stuck in this for months.
