### ISSUE TITLE
Signalr Client for WPF for .NET6 RC does not connect to hub

### ISSUE THREAD

**Issue by vinaykapoor** [SignalR/SignalR#4591]
I have a WPF application which connects via signalr websockets. Prior to updating to .NET 6 RC, I was able to connect to the hub however after the update I get a 401 and get the following messages
--After updating
net6.0-windows10.0.19041

16:56:14.646|DEBUG|Connection id "0HMBPACG2TKSM" accepted.
16:56:14.646|DEBUG|Connection id "0HMBPACG2TKSM" started.
16:56:14.664|INFO|Request starting HTTP/1.1 GET http://netsbappw03:52976/orderHub - -
16:56:14.664|DEBUG|The request is insecure. Skipping HSTS header.
16:56:14.664|DEBUG|1 candidate(s) found for the request path '/orderHub'
16:56:14.664|DEBUG|Request matched endpoint '/orderHub'
16:56:14.664|DEBUG|AuthenticationScheme: Negotiate was not authenticated.
16:56:14.664|INFO|Authorization failed. These requirements were not met:
DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
16:56:14.664|DEBUG|Challenged 401 Negotiate.
16:56:14.664|INFO|AuthenticationScheme: Negotiate was challenged.
16:56:14.664|DEBUG|Connection id "0HMBPACG2TKSM" completed keep alive response.
16:56:14.664|INFO|Request finished HTTP/1.1 GET http://netsbappw03:52976/orderHub - - - 401 0 - 6.8255ms
16:56:14.701|INFO|Request starting HTTP/1.1 GET http://netsbappw03:52976/orderHub - -
16:56:14.701|DEBUG|The request is insecure. Skipping HSTS header.
16:56:14.701|DEBUG|1 candidate(s) found for the request path '/orderHub'
16:56:14.701|DEBUG|Request matched endpoint '/orderHub'
16:56:14.701|INFO|Incomplete Negotiate handshake, sending an additional 401 Negotiate challenge.
16:56:14.701|DEBUG|Connection id "0HMBPACG2TKSM" completed keep alive response.
16:56:14.701|INFO|Request finished HTTP/1.1 GET http://netsbappw03:52976/orderHub - - - 401 0 - 5.4285ms
16:56:14.718|INFO|Request starting HTTP/1.1 GET http://netsbappw03:52976/orderHub - -
16:56:14.718|DEBUG|The request is insecure. Skipping HSTS header.
16:56:14.718|DEBUG|1 candidate(s) found for the request path '/orderHub'
16:56:14.718|DEBUG|Request matched endpoint '/orderHub'
16:56:14.718|INFO|Incomplete Negotiate handshake, sending an additional 401 Negotiate challenge.
16:56:14.718|DEBUG|Connection id "0HMBPACG2TKSM" completed keep alive response.
16:56:14.718|INFO|Request finished HTTP/1.1 GET http://netsbappw03:52976/orderHub - - - 401 0 - 5.0385ms
16:56:14.734|DEBUG|Connection id "0HMBPACG2TKSM" received FIN.
16:56:14.734|DEBUG|Connection id "0HMBPACG2TKSM" disconnecting.
16:56:14.734|DEBUG|Connection id "0HMBPACG2TKSM" sending FIN because: "The client closed the connection."
16:56:14.741|DEBUG|Connection id "0HMBPACG2TKSM" stopped.
Heartbeat

Before updating
net5.0-windows10.0.19041
16:57:47.896|DEBUG|Connection id "0HMBPACG2TKSN" accepted.
16:57:47.896|DEBUG|Connection id "0HMBPACG2TKSN" started.
16:57:47.933|INFO|Request starting HTTP/1.1 GET http://netsbappw03:52976/orderHub - -
16:57:47.933|DEBUG|The request is insecure. Skipping HSTS header.
16:57:47.933|DEBUG|1 candidate(s) found for the request path '/orderHub'
16:57:47.933|DEBUG|Request matched endpoint '/orderHub'
16:57:47.933|DEBUG|AuthenticationScheme: Negotiate was not authenticated.
16:57:47.937|INFO|Authorization failed. These requirements were not met:
DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
16:57:47.937|DEBUG|Challenged 401 Negotiate.
16:57:47.937|INFO|AuthenticationScheme: Negotiate was challenged.
16:57:47.937|DEBUG|Connection id "0HMBPACG2TKSN" completed keep alive response.
16:57:47.937|INFO|Request finished HTTP/1.1 GET http://netsbappw03:52976/orderHub - - - 401 0 - 6.5964ms
16:57:47.980|INFO|Request starting HTTP/1.1 GET http://netsbappw03:52976/orderHub - -
16:57:47.980|DEBUG|The request is insecure. Skipping HSTS header.
16:57:47.980|DEBUG|1 candidate(s) found for the request path '/orderHub'
16:57:47.980|DEBUG|Request matched endpoint '/orderHub'
16:57:47.980|INFO|Incomplete Negotiate handshake, sending an additional 401 Negotiate challenge.
16:57:47.984|DEBUG|Connection id "0HMBPACG2TKSN" completed keep alive response.
16:57:47.984|INFO|Request finished HTTP/1.1 GET http://netsbappw03:52976/orderHub - - - 401 0 - 4.6097ms
16:57:48.005|INFO|Request starting HTTP/1.1 GET http://netsbappw03:52976/orderHub - -
16:57:48.005|DEBUG|The request is insecure. Skipping HSTS header.
16:57:48.005|DEBUG|1 candidate(s) found for the request path '/orderHub'
16:57:48.005|DEBUG|Request matched endpoint '/orderHub'
16:57:48.018|DEBUG|Completed Negotiate authentication.
16:57:48.018|DEBUG|AuthenticationScheme: Negotiate was successfully authenticated.
16:57:48.018|DEBUG|Authorization was successful.
16:57:48.018|INFO|Executing endpoint '/orderHub'
16:57:48.018|DEBUG|New connection S2LT9th78VCe_WVyJiAftw created.
16:57:48.018|DEBUG|Establishing new connection.
16:57:48.018|DEBUG|OnConnectedAsync started.
16:57:48.018|DEBUG|Socket opened using Sub-Protocol: '(null)'.
16:57:48.086|DEBUG|Found protocol implementation for requested protocol: messagepack.
16:57:48.086|DEBUG|Completed connection handshake. Using HubProtocol 'messagepack'.
/mon/admin/getpermissionedobjects {"application":"APEX","allObjects":false,"requestId":"ef22ee92eac64ea491aa3ddc10635a152","requestor":"vkapoor","timestamp":null}
Write complete.
16:57:48.172|INFO|Connected : S2LT9th78VCe_WVyJiAftw User :vkapoor On :WebSockets
Heartbeat
Listener Hearbeat count: 0
16:57:52.553|DEBUG|Received hub invocation: InvocationMessage { InvocationId: "11", Target: "Heartbeat", Arguments: [ ], StreamIds: [ ] }.

Connecting to a signalr hub using websockets only through the WPF signalr client has caused issues in earlier versions too. This should be fairly straight forward . Since this is a release candidate can this be fixed.

**Comment by vinaykapoor** [comment]
I am using Kestrel to host signalr hubs

**Comment by JGdalevich** [comment]
If you are using Core (NET 5 or 6), this is not the right version of SignalR for you.

You need to use https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?WT.mc_id=dotnet-35129-website&view=aspnetcore-5.0&tabs=visual-studio
and https://github.com/aspnet/AspNetCore/tree/main/src/SignalR

**Comment by vinaykapoor** [comment]
I do not follow . I am trying to use the .NET 6 RC for WPF. The link you sent me is for web based signalr clients.

**Comment by vinaykapoor** [comment]
I am using target platform windows10.0.19041.

**Comment by BrennanConroy** [comment]
Wrong repo like Jonathan pointed out.

**Comment by vinaykapoor** [comment]
Can you explain some more . I don’t follow. Either you are suggesting that I am using an incorrect version in which case the correct version would help, or you are just ignoring my problem and are inclined to closing the issue . Can you please explain a bit more. This is a valid bug. I have attached the logs too.
