### ISSUE TITLE
HubMethodNameAttribute not used from interface in strongly typed hubs

### ISSUE THREAD

**Issue by angelaki** [SignalR/SignalR#4598]
Guess no more words needed 🙂 I'd like to define my hub methods in the interface, e.g.

```
public interface IClient
{
    [HubMethodName("Method")]
    Task MethodAsync();
}

public class ClientHub : Hub<IClient> { ... }
```

but right now need to repeat the interface in the implementation.

**Comment by halter73** [comment]
Thanks for the report. While I agree this is a gap, this attribute has never been supported on client interfaces and [we're not adding new features](https://github.com/SignalR/SignalR#aspnet-signalr) and we don't consider this critical issue.

**Comment by angelaki** [comment]
Oh, actually I wanted to post it to the Core version. Thank you!

**Comment by halter73** [comment]
Are you using .NET 5? I should be fixed there by https://github.com/dotnet/aspnetcore/pull/23614.
