### ISSUE TITLE
Is there an option for Asp.Net server SDK to force clients using WebSocket transport?

### ISSUE THREAD

**Issue by terencefan** [SignalR/SignalR#4600]
### Expected  behavior

An option that could force the client to use **WebSocket** transport on server-side other than fallback to other transports.

Like what we did in `Asp.net Core` version of `SignalR`.

![image](https://user-images.githubusercontent.com/4176855/138687924-9dbf7879-ed6d-44ab-9393-d0965a4e6a92.png)

### Actual behavior

I can't find an option to do this in `Asp.net` server SDK.

### Steps to reproduce

**Comment by halter73** [comment]
It is possible to do on the server, but it requires messing with the DependencyResolver.

```C#
using Microsoft.AspNet.SignalR;
using Microsoft.AspNet.SignalR.Transports;
using Owin;
namespace MyApplication
{
    public static class Startup
    {
        public static void ConfigureSignalR(IAppBuilder app)
        {
            GlobalHost.DependencyResolver.Resolve<ITransportManager>() as TransportManager;
            transportManager.Remove("webSockets");
            app.MapSignalR();
        }
    }
}
```

See https://stackoverflow.com/a/21337672/719967

And you can find the other transport names at:

https://github.com/SignalR/SignalR/blob/ee6fb29879bedf72c0eadc36fa0ccbefc6ad2288/src/Microsoft.AspNet.SignalR.Core/Transports/TransportManager.cs#L30-L33
