### ISSUE TITLE
Resolving HubContext when using Redis backplane

### ISSUE THREAD

**Issue by MJRomka** [SignalR/SignalR#4604]
We were using SignalR without Redis backplane for years resolving HubContext only once in a singleton:
`GlobalHost.ConnectionManager.GetHubContext<SignalRHub>()`

When we enabled Redis
`GlobalHost.DependencyResolver.UseStackExchangeRedis(config) `
SignalR stopped working properly: connection was establishing, but no messages received. It fixed by resolving Hub Context each time before calling any its method.

Is it expected behaviour or we are doing something conceptually wrong?

**Comment by JGdalevich** [comment]
` GlobalHost.DependencyResolver.UseStackExchangeRedis(new RedisScaleoutConfiguration(hostname, key));` in Startup.cs is what we use and it resolves fine.

**Comment by MJRomka** [comment]
> ` GlobalHost.DependencyResolver.UseStackExchangeRedis(new RedisScaleoutConfiguration(hostname, key));` in Startup.cs is what we use and it resolves fine.

It resolves fine, but the issue is that we have to resolve it EVERY time before broadcasting anything. Before Redis was attached we resolved it once and stored HubContext instance in a singleton.
I am fine to do that, just want a confirmation that I do it right.

**Comment by JGdalevich** [comment]
We only need to resolve it once in the Singleton.  Adding Redis did not change this for us.  This is an example of what we do in the Singleton for each hub.
` private static readonly Lazy<MySingletonHandler> instance = new Lazy<MySingletonHandler>(() => new MySingletonHandler(GlobalHost.ConnectionManager.GetHubContext<MyHub>().Clients));`

**Comment by MJRomka** [comment]
Interesting, you store Clients in the singleton, and we stored Context. I know it sounds strange, but maybe it makes a difference

**Comment by halter73** [comment]
Do you have any updates on this @MJRomka? This does seem strange. Could it be that the first time `GlobalHost.ConnectionManager.GetHubContext<SignalRHub>()` was called, `GlobalHost.DependencyResolver.UseStackExchangeRedis(config)` hadn't been called yet?

**Comment by MJRomka** [comment]
I don't have any updates, I just made sure that in our code we get hub context every time before usage.
And I can confirm this is not an issue of sequence of registering and calling: I tried different scenarios and the conclusion was that previously received hub context was not valid (did not work) for further usage. It worked  only within one HTTP request I think.

**Comment by BrennanConroy** [comment]
Without a minimal repro we are going to close this issue. Feel free to reopen if you can provide more details.
