### ISSUE TITLE
.NET 6 How to get an instance of IHubContext

### ISSUE THREAD

**Issue by LuGuangguang** [SignalR/SignalR#4605]
I want to get an instance to used for dependency injection，I browse the MSDN documentation from **https://docs.microsoft.com/en-us/aspnet/core/signalr/hubcontext?view=aspnetcore-6.0**   "Get an instance of IHubContext from IHost";
But  I found it is based on .net 5 or less.
I run the code normally under .net core 3.1.

You know the asp.net core 6.0 Use the WebApplication to Host, so I try code
`IHubContext<SignalRHubs.ChatHub>? hubContext = app.Services.GetService(typeof(IHubContext<ChatHub>)) as IHubContext<ChatHub>;
            services.AddSingleton<IHubContext<SignalRHubs.ChatHub>>(hubContext);`

But when I use the  hubContext,I found the Client link count aways 0.
![S1X35SE7}GY5XRJ(P4EKXG3](https://user-images.githubusercontent.com/34500722/142387888-74d45108-e8de-462a-b07c-f5e63d9198d1.png)

Is my method is error or otherings?

**Comment by JGdalevich** [comment]
If you are using Core (NET 5 or 6), this is not the right version of SignalR for you.

You need to use https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?WT.mc_id=dotnet-35129-website&view=aspnetcore-5.0&tabs=visual-studio
and https://github.com/aspnet/AspNetCore/tree/main/src/SignalR
