### ISSUE TITLE
SignalR Logging - no Event Message File and no date/time in file-based logging

### ISSUE THREAD

**Issue by manfredczujan** [SignalR/SignalR#4606]
Hi folks,
After enabled Logging of SignalR (https://docs.microsoft.com/en-us/aspnet/signalr/overview/testing-and-debugging/enabling-signalr-tracing)  through adding a <system.diagnostic> section to the web.config of my app, i've experienced the following problems:

    if logging is configured to log into a text file, it works fine, but no date / time is logged (?)
    if logging is configured to log to eventlog, and i added the event source manually, the eventlog can't find the "event message file" or the file (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\EventLogMessages.dll) does not contain the error descriptions of SignalR Events.
anybody knows, how to configure logging for signalr in a more detailed way ?
I would be fine with the log files, but without having date/time, its hard to find issues..
br Manfred

**Comment by BrennanConroy** [comment]
Try using [TraceOptions](https://docs.microsoft.com/dotnet/api/system.diagnostics.traceoptions?view=net-6.0), specifically DateTime

**Comment by manfredczujan** [comment]
Hi Brennan !
Thanx !

It seems, that TraceOptions are not allowed with the SignalR system.diagnostics config.

I get Application Event Log Warning 3008, Source: ASP.NET

Message: Event message: A configuration error has occurred.
Exception information: 
    Exception type: ConfigurationErrorsException 
    Exception message: A listener with no type name specified references the sharedListeners section and cannot have any attributes other than 'Name'.  Listener: 'SignalR-Transports'.

this is true for all the listeners...

br
Manfred

**Comment by manfredczujan** [comment]
ahhh, wrong place for "output".... 
It worked after adding the "Traceoptions" to the Listeners.
