### ISSUE TITLE
SignalR Disconnect method on client side is not invoked on Internet Disconnection

### ISSUE THREAD

**Issue by MuteebAhmad148** [SignalR/SignalR#4608]
Hi,
I'm using Azure SignalR for Real Time communication in my application. There is a possibility that the of Internet might disconnect on users side so, I written the code that will create a new connection to handle this scenario & I'm relying on SignalR disconnect method to do so. But the issue is SignalR disconnect method is not invoked when I test it on Chrome & Edge web Browser. 
It is working fine on mobile devices & Firefox browser. 
I'm using SignalR version 2.4.1

**Comment by JGdalevich** [comment]
Try version 2.4.2.  It fixes some issues with Chrome.  Edge is based on Chrome.

**Comment by halter73** [comment]
@MuteebAhmad148 I would definitely try upgrading to 2.4.2. It's possible that without the fix to #4536, the timer callback that would normally notice the missed keep-alive messages and fire the `disconnected` callbacks is being throttled. If that doesn't fix the issue for you, please report back your findings.
