### ISSUE TITLE
Error: Failed to start the transport 'WebSockets': Error: WebSocket failed to connect. 

### ISSUE THREAD

**Issue by bbhxwl** [SignalR/SignalR#4615]
My server uses nginx. Does this have anything to do with nginx?

```
 services.AddCors(op =>
            {
                op.AddPolicy("AllowAll", builder =>
                {
                    builder.SetIsOriginAllowed(_ => true).AllowAnyMethod().AllowAnyHeader().AllowCredentials();
                });
            });

```

```
app.UseWebSockets();
app.UseSession();
            app.UseAuthorization();
            app.UseCors("AllowAll");
app.UseEndpoints(endpoints =>
            {
                endpoints.MapHub<ForwardMessageHub>("/ForwardMessageHub");
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=chart}/{action=Index}/{id?}");
            });
```
![image](https://user-images.githubusercontent.com/26525599/150792608-364ad9ad-f9fd-484e-91bc-4b3e9f18e198.png)

Error: Failed to start the transport 'WebSockets': Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled.

**Comment by BrennanConroy** [comment]
> Does this have anything to do with nginx?

Yes, like the error message says, your proxy could be blocking the websocket connection. You could verify this by looking at your server logs and seeing if the websocket request ever hits your server.
Take a look at the docs for nginx configuration: https://docs.microsoft.com/aspnet/core/signalr/scale?view=aspnetcore-6.0#linux-with-nginx

Also, this is the wrong repo for ASP.NET Core SignalR so closing the issue.

**Comment by J3ster1337** [comment]
That's how I just fixed this:
https://stackoverflow.com/a/77411481/22065821
