### ISSUE TITLE
An exception occurred in the electron.

### ISSUE THREAD

**Issue by bbhxwl** [SignalR/SignalR#4617]
It's strange that it's not compatible with this browser.

electron-packager . test --platform=win32 --arch=x64 --icon=logo.ico --out=D:\\out --asar --app-version=0.0.1 --overwrite --electron-version=1.4.13  

![image](https://user-images.githubusercontent.com/26525599/151282456-d886ac6f-a5c1-4e0b-9fbf-b2f5222d9c68.png)

**Comment by BrennanConroy** [comment]
This is the wrong repo for ASP.NET Core SignalR, please file an issue at https://github.com/dotnet/aspnetcore and provide more info, like the version of the SignalR library, and if possible a repro app.
