### ISSUE TITLE
Sometimes SignalR create a new auth cookie

### ISSUE THREAD

**Issue by DomZZ** [SignalR/SignalR#4619]
I'm using last SignalR nuget version 2.4.3 on a website that use cookie authentication with OWIN.
When I connect to the application a get a new auth cookie which is correct, but sometimes when SignalR throw request on /signalr path (hubs, negociate, ...) a new cookie with the same name is created.

### Expected  behavior
SignalR should use existing auth cookie and don't create a new one.

### Actual behavior
A new auth cookie is issued by SignalR with the same name

We are not able to always reproduce this ...
Any idea ?

**Comment by BrennanConroy** [comment]
> SignalR should use existing auth cookie and don't create a new one.

Isn't it your app that's creating the cookie? SignalR doesn't create cookies for you so something in your app is doing that.
