### ISSUE TITLE
Legacy SignalR + Blazor WASM?

### ISSUE THREAD

**Issue by alexthekid07** [SignalR/SignalR#4624]
Curious how I would go about connecting a Blazor WASM client to this legacy .NET Framework version of SignalR?

I understand the ASP.NET Core version exists for this purpose, but I am trying to develop a modern web app and connect to an older/legacy server still running old SignalR.

**Comment by BrennanConroy** [comment]
It probably isn't possible to use the .NET Framework client in WASM. There was some work that had to be done in the ASP.NET Core .NET client to make it work in WASM, this project is in [maintenance mode](https://github.com/SignalR/SignalR#aspnet-signalr) and we're not going to be doing any of that work here for ASP.NET SignalR.

Your best bet is to use the javascript client and either write your own .NET wrapper in WASM for it, or interop with the javascript client from WASM.
