### ISSUE TITLE
Cannot have HTML Element with Id="exports" and SignalR.js on the same page

### ISSUE THREAD

**Issue by barmendarez** [SignalR/SignalR#4626]
### Expected  behavior
Expected to just return the connection info into the console
### Actual behavior

`Uncaught ReferenceError: signalR is not defined
`
### Steps to reproduce
Have any HTML element with an Id="exports" and try to load signalr.js

anyfile.html
`<a data-not-implemented="" id="exports">Exports</a>`

anyfile.js
`let connection = new signalR.HubConnectionBuilder()
    .withUrl("/signalrhub")
    .configureLogging(signalR.LogLevel.Information)
    .build();

$(document).ready(function () {
    console.log(connection)
});
`
**This is very much an edge case thing, however there is no documentation or really anything out there on this**

**Comment by BrennanConroy** [comment]
You are using ASP.NET Core SignalR, file issues at github.com/dotnet/aspnetcore instead of here.
