### ISSUE TITLE
CORS issue with Typescript and C# based Negotiation API

### ISSUE THREAD

**Issue by abhaldar** [SignalR/SignalR#4627]
Issues related to the Asp.NET Core version of SignalR should be filed in the AspNetCore repo: 

### Expected  behavior
Negotiation API should acknowledge cross domain call when exclusively allowed using allow-origin "*"

### Actual behavior
CORS Err

### Steps to reproduce
Calling Negotiation API over a different host from client.

![image](https://user-images.githubusercontent.com/25233770/167492507-3cb885ca-7aa5-4856-ac44-c75de8586359.png)

**Comment by BrennanConroy** [comment]
This is the wrong repo as stated at the top of the issue template.
