### ISSUE TITLE
Npm audit: critical severity

### ISSUE THREAD

**Issue by theramenboy** [SignalR/SignalR#4629]
Hi, I found a problem with the "npm audit" command which is integrated into a build pipeline on azure.
Until yesterday no problem, today "npm audit" returns this error

![image](https://user-images.githubusercontent.com/35604768/170516784-04e30a6f-de70-4526-a2ac-449ec0fe5580.png)

My project is a vite + vue project and my package.json has @microsoft/signalr@6.0.0. The audit fix propose me to set it to 0.0.0. but I think there is something going on and I do not want to have the 0.0.0 version

Anyone with this issue?

Thank you

**Comment by BrennanConroy** [comment]
Wrong github repo.

Additionally, the error is temporary as eventsource 1.1.1 isn't vulnerable but databases still claim it is.

If you need a quick fix, you can reference 2.0.2 of eventsource yourself to force a newer version.

**Comment by theramenboy** [comment]
Thank you
