### ISSUE TITLE
System.NullReferenceException in SignalProxy.Invoke, SignalProxy.cs:line 46

### ISSUE THREAD

**Issue by doboczyakos** [SignalR/SignalR#4633]
### Expected  behavior
No NullReferenceException if client is disconnected

### Actual behavior
System.NullReferenceException
Object reference not set to an instance of an object.

at Microsoft.AspNet.SignalR.Hubs.SignalProxy.Invoke(String method, Object[] args) in /_/src/Microsoft.AspNet.SignalR.Core/Hubs/SignalProxy.cs:line 46

### Steps to reproduce
Non-deterministic - sometimes disconnected client causes this error

**Comment by BrennanConroy** [comment]
What version are you using? Can you provide a minimal repro app as a GitHub project?

**Comment by doboczyakos** [comment]
> What version are you using? Can you provide a minimal repro app as a GitHub project (even if it's non-deterministic)?

Sorry, no. Please try the following:
1. Get the client: Clients.Client(connectionId)
2. Close the browser
3. Send a message to the already disconnected client

IMHO nothing else can be null but:
return _Invoker_.Send(context);

**Comment by halter73** [comment]
> Get the client: Clients.Client(connectionId)

It sounds like you're storing the result of `Clients.Client(connectionId)` and then using it after the hub method you retrieved it in completed. This is unsupported. If you want to store the `IClientProxy` for use outside of a running hub method, you should use `GlobalHost.ConnectionManager.GetHubContext<YourHub>().Clients.Client(connectionId)` instead.

**Comment by halter73** [comment]
See https://learn.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server#how-to-call-client-methods-and-manage-groups-from-outside-the-hub-class
