### ISSUE TITLE
Using SignalR hub in class library

### ISSUE THREAD

**Issue by Phelecks** [SignalR/SignalR#4635]
Issues related to the Asp.NET Core version of SignalR should be filed in the AspNetCore repo: 

I am using .net 6 API application and also .net 6 class library. My class library added to API project and do some processes and need to send some data via signalr to my web applicaiton (Separate solution and project). I noticed that SignalR is embed to .net6 and cant add version 6 of SignalR to my class library. (Only version 1.1.0 is available).

### Expected  behavior
I can add SignalR 6 to my class library and implement my hub class inherited from Hub<IMyInterface> and then call SignalR methods.

### Actual behavior
I can only find SignalR 1.1.0 and its deprecated. what should I do?

**Comment by poormonfared** [comment]
I have the same issue!!! #up

**Comment by BrennanConroy** [comment]
Use a framework reference: https://docs.microsoft.com/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-6.0&tabs=visual-studio

Also, this is the wrong repo for ASP.NET Core SignalR related issues.

**Comment by jbennink** [comment]
Wow finally found the solution, a framework reference :-|
