### ISSUE TITLE
Error when adding SignalR client to a VsCode extension

### ISSUE THREAD

**Issue by AlirezaHaghshenas** [SignalR/SignalR#4639]
### Expected  behavior
Be able to add SignalR to a VsCode extension.

### Actual behavior
I get the error:
```
requireFunc is not a function
```

The error is in the following location in `node_modules/@microsoft/signalr/src/HttpConnection.ts`

```ts
        if (Platform.isNode && typeof require !== "undefined") {
            // In order to ignore the dynamic require in webpack builds we need to do this magic
            // @ts-ignore: TS doesn't know about these names
            const requireFunc = typeof __webpack_require__ === "function" ? __non_webpack_require__ : require;
            webSocketModule = requireFunc("ws");
            eventSourceModule = requireFunc("eventsource");
        }
```

### Steps to reproduce
Following the steps to add SignalR client to a typescript project: install the package, create the connection.

**Comment by BrennanConroy** [comment]
Wrong repo, see https://github.com/dotnet/aspnetcore/issues for the correct issue tracker.

Also, this isn't enough information. Please provide details such as package version and more accurate repro steps. If it was as easy as "install the package" many other people would have seen this.
