### ISSUE TITLE
SignalR (self-host) connection always fails when enable Tracing.

### ISSUE THREAD

**Issue by daviduuang** [SignalR/SignalR#4645]
SignalR (self-host) connection always fails when enable Tracing.

### Environment

.NET Framemwork v4.6.1

[SignalR (self-host)](https://docs.microsoft.com/zh-cn/aspnet/signalr/overview/deployment/tutorial-signalr-self-host) : 
- [Microsoft.AspNet.SignalR.SelfHost v2.4.3](https://www.nuget.org/packages/Microsoft.AspNet.SignalR.SelfHost/2.4.3?_src=template)
- [Microsoft.AspNet.SignalR.Client v2.4.3](https://www.nuget.org/packages/Microsoft.AspNet.SignalR.Client/2.4.3?_src=template)

[Enable SignalR Tracing on server side](https://docs.microsoft.com/zh-cn/aspnet/signalr/overview/testing-and-debugging/enabling-signalr-tracing#server_eventlog)

### Steps to reproduce

1. Run SignalR server and client demo app in visual studio.

2. Diagnose information in the output panel of visual studio:
```

   SignalR.PerformanceCounterManager Error: 0 : Performance counter failed to load: System.InvalidOperationException: 请求的性能计数器不是自定义计数器，它必须初始化为 ReadOnly。

   在 System.Diagnostics.PerformanceCounter.InitializeImpl()

   在 System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName, Boolean readOnly)

   在 Microsoft.AspNet.SignalR.Infrastructure.PerformanceCounterManager.LoadCounter(String categoryName, String counterName, String instanceName, Boolean isReadOnly)

SignalR.PerformanceCounterManager Error: 0 : Performance counter failed to load: System.InvalidOperationException: 请求的性能计数器不是自定义计数器，它必须初始化为 ReadOnly。

   在 System.Diagnostics.PerformanceCounter.InitializeImpl()

   在 System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName, Boolean readOnly)

   在 Microsoft.AspNet.SignalR.Infrastructure.PerformanceCounterManager.LoadCounter(String categoryName, String counterName, String instanceName, Boolean isReadOnly)

线程 0x4ec8 已退出，返回值为 0 (0x0)。
```

3. Client couldn't connect to server.

4. Client connect server successful when disable SignalR server side tracing. 

It seems that the PerformanceManager run into exception when tracing enabled, and finally made SignalR server hang. The exception message match the line 457 in [PerformanceCounterManager.cs](https://github.com/SignalR/SignalR/blob/main/src/Microsoft.AspNet.SignalR.Core/Infrastructure/PerformanceCounterManager.cs) .

**Comment by halter73** [comment]
Does `SignalR.exe ipc` fix the issue for you? https://learn.microsoft.com/aspnet/signalr/overview/performance/signalr-performance#perfcounters

**Comment by daviduuang** [comment]
> Does `SignalR.exe ipc` fix the issue for you? https://learn.microsoft.com/aspnet/signalr/overview/performance/signalr-performance#perfcounters

No.

It's my fault. There's error in the "shared listener" part of my app.config file. 
The right one as follows:

<sharedListeners>
  
  <add name="SignalR-Transports" **type="MyLib.LogWriterTraceListener, MyLib"** />
  
  <add name="SignalR-Bus" **type="MyLib.LogWriterTraceListener, MyLib"** />
  
  <add name="SignalR-Init" **type="MyLib.LogWriterTraceListener, MyLib"** />
</sharedListeners>
