### ISSUE TITLE
Decrease bundle size

### ISSUE THREAD

**Issue by andriijas** [SignalR/SignalR#4649]
microsoft signalR  is one of the largest dependencies we use in our app.

Would it be possible to set a goal to shave the yak for future releases? 🐐

https://bundlephobia.com/package/@microsoft/signalr@6.0.9
Thanks!🙏

**Comment by BrennanConroy** [comment]
Wrong repo, this belongs at github.com/dotnet/aspnetcore

Also, is 42kb really too big?

**Comment by BrennanConroy** [comment]
I think gziped we were down to 12kb last I checked.
