### ISSUE TITLE
Getting disconnected every 6-10minutes from the client side

### ISSUE THREAD

**Issue by mandreou** [SignalR/SignalR#4651]
Hello there, 
SignalR is getting disconnected every 6-10 minutes. If i do a workaround of location.reload() before the disconnection happens seems to be working. However, i'm looking for the proper solution please

**Comment by BrennanConroy** [comment]
Please provide information about the issue.

What version of the client are you using?
Are there any console logs on the server or client?
Have you looked at a network trace?
