### ISSUE TITLE
Support Redis Clusters with Redis 7 & SSubscribe/SPublish

### ISSUE THREAD

**Issue by tomap** [SignalR/SignalR#4656]
Hello,

Currently, the way to scale out SignalR servers is to rely on a backplane.
Unfortunately, this backplane cannot be made redundant by using a Redis Cluster because the current behavior of SignalR is to use Subscribe/Publish commands which are not relayed to the other nodes of a redis cluster

Redis 7 introduced SSubscribe & SPublish which is a pub sub mecanism compatible with cluster (aka messages are relayed to every node of the cluster)
https://redis.io/docs/manual/pubsub/#sharded-pubsub
This could be a way to support Redis Clusters

The current status is that StackExchange.Redis does not support those new commands, but work is tracked here:
https://github.com/StackExchange/StackExchange.Redis/issues/2055
Hopefully, once the work is done on StackExchange.Redis side, SignalR can pickup from there to use those new features ? 

For reference: https://github.com/dotnet/AspNetCore.Docs/issues/7814#issuecomment-1231516740 & https://github.com/dotnet/AspNetCore.Docs/issues/27693#issuecomment-1320943482

**Comment by BrennanConroy** [comment]
Did you mean to post on https://github.com/aspnetcore/? This repo is maintenance only and unlikely to make any big changes.

Also, we just tested Redis Clustering and it seemed to work just fine
https://github.com/dotnet/aspnetcore/issues/27583#issuecomment-1310746715

**Comment by tomap** [comment]
Indeed. I'm closing this issue
