### ISSUE TITLE
No responses received on the client until all SignalR hub calls have completed

### ISSUE THREAD

**Issue by djdd87** [SignalR/SignalR#4666]
I've got a project where clients have been complaining that certain actions occasionally take a long time. I added some metric tracking around the hub calls and noticed that every single request was coming back at the same time once all requests had completed.

![OpeningProjects](https://user-images.githubusercontent.com/22151993/223097342-37c586b9-17f6-4f52-9f25-f976e5ac3ac3.gif)

This is just a simple example of what's going in my actual code. It seems that when the client makes multiple simultaneous _expensive_ requests (which are triggered by a background proces), they're blocked/delayed from doing anything else until the other requests have finished.

I've seen there's a flag that can be set to allow parallelised requests in .Net 5 onwards, but this seems like incorrect behaviour anyway and this project is unable to be upgraded at the moment. It seems very odd that a request does not complete and then return until some/all requests have finished.

### Expected  behavior
Multiple calls to the same hub and method should return as each complete, regardless of whether there are other incoming requests made while the current request(s) are processing.

### Actual behavior
All hub calls return at exactly the same time/in chunks once the last request has finished.

### Steps to reproduce

**Using attached solution:**
- Launch the project
- Go to StockTicker.html
- Click the Increment button 10 times quickly
- The number does not increment uniformly. Sometimes it increments to 1 then 2 after 5/6 seconds, then jumps to 10. Sometimes it jumps straight to 10.

**From scratch:**
- Create a hub call that does Thread.Sleep(2000)
- Create a client side button that calls the hub method
- Make the done event of the hub call increment a count of an input box
- Hit the button 10 times quickly
- The number does not increment uniformly. Sometimes it increments to 1 then 2 after 5/6 seconds, then jumps to 10. Sometimes it jumps straight to 10.

Test project attached.

[SignalRIssue.zip](https://github.com/SignalR/SignalR/files/10897551/SignalRIssue.zip)

**Comment by BrennanConroy** [comment]
Please share the repro project as a github repository and not a zip file.

**Comment by djdd87** [comment]
> Please share the repro project as a github repository and not a zip file.

As requested: https://github.com/djdd87/SignalR-4666

**Comment by BrennanConroy** [comment]
This is by design. Server to client responses are not guaranteed to be ordered (see similar issue https://github.com/SignalR/SignalR/issues/4099).

**Comment by djdd87** [comment]
This isn't about guaranteeing order. This about the server not responding to the client at all when the client makes continued requests.

**Comment by BrennanConroy** [comment]
The server does respond, if you look at the network you can see the server responds to every invocation.

I would also recommend not blocking a thread using Thread.Sleep and instead use async or, if you need to do long running synchronous work to Task.Run the work and respond via a TaskCompletionSource.

```c#
public Task Increment()
{
    return Task.Delay(2000);
}
```

Or for a value returning method

```c#
// works with "public Task Increment()" too if you don't need a value
public Task<int> Increment()
{
    TaskCompletionSource<int> tcs = new TaskCompletionSource<int>();
    Task.Run(() =>
    {
        // expensive code
        tcs.SetResult(1);
    });
    return tcs.Task;
}
```

**Comment by djdd87** [comment]
Thanks, this seems to solve the issue on the repro and the server returns the responses in a timely manner. I'll try the same thing in our actual code and report back.

**Comment by djdd87** [comment]
Yup. All our Hub calls follow a standard pattern of returning the response in a wrapped HubResult object, so I simply made a generic run function and wrapped the offending methods in a ```Func<T>```:

``` csharp
public static Task<HubResult> Run(Func<HubResult> function)
{
    TaskCompletionSource<HubResult> tcs = new TaskCompletionSource<HubResult>();
    Task.Run(() =>
    {
        try
        {
            HubResult result = function();
            tcs.SetResult(result);
        }
        catch (Exception ex) 
        {
            tcs.SetException(ex);
        }
    });
    return tcs.Task;
}
```
