### ISSUE TITLE
Client.Client(connectionId) returing incorrect proxy connection

### ISSUE THREAD

**Issue by BobbyCannon** [SignalR/SignalR#4668]
![image](https://user-images.githubusercontent.com/840590/225006046-ce356f65-32a9-4e5b-8577-26c53bab31e2.png)

The issue only happens on OnConnectedAsync. The issue does **not** happen on OnDisconnectedAsync and will work as expected.

### Expected  behavior

When calling Clients.Client with a Connection Id, I would expect the correct client proxy to be returned.

### Actual behavior

Clients.Client is returning the wrong client.

### Steps to reproduce

Try to call another connected client when a different client is connecting. 

When the client is connecting in "public override async Task OnConnectedAsync()" then try to get another proxy via the Clients.Client(otherId). The current connecting connection proxy will be returned.

**Comment by BrennanConroy** [comment]
Wrong repo, like the text you deleted says
> Issues related to the Asp.NET Core version of SignalR should be filed in the AspNetCore repo: https://github.com/aspnet/AspNetCore/issues/new/choose

Also, are you putting the hub in DI as a singleton?

**Comment by BobbyCannon** [comment]
Referencing the new issue. https://github.com/dotnet/aspnetcore/issues/47189
