### ISSUE TITLE
Asp.Net Core + SignalR + Nginx Connection Not Open

### ISSUE THREAD

**Issue by KuldeepSinghAdaptit** [SignalR/SignalR#4670]
Good Morning All 

I am in Trouble My Boss Say me to Implement Real Time Notification Using  .NET Core + SignalR + Nginx, Locally It's Working Perfect 
But When I Deploy This Code On Environment Then Following Error Comes 

![image](https://user-images.githubusercontent.com/110213171/230059165-d426f3d2-abc7-4be5-96c5-61f8c66407fc.png)

I used Following Article To Implement 

https://code-maze.com/netcore-signalr-angular-realtime-charts/

For Nginx Configuration We are using Below Configuration Given By Microsoft
https://learn.microsoft.com/en-us/aspnet/core/signalr/scale?view=aspnetcore-6.0#linux-with-nginx

![image](https://user-images.githubusercontent.com/110213171/230059764-e23ec289-9043-41ce-ad6e-82181ed63156.png)

Any Idea Please Kindly Suggest , Or Provide Me Some Demo Application .Thanks In Advance

**Comment by BrennanConroy** [comment]
This is the wrong repository for ASP.NET SignalR Core.
To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com/) using the signalr tag.
