### ISSUE TITLE
HOW TO CALL SIGNALR FROM ANYWHERE IN CODE wITH SPECIFIC MESSAGE PER CLIENT (CONNECTION)

### ISSUE THREAD

**Issue by EricOuellet2** [SignalR/SignalR#4672]
HOW TO CALL SIGNALR FROM ANYWHERE IN CODE wITH SPECIFIC MESSAGE PER CLIENT (CONNECTION)

### Expected  behavior
Being easy to call signalR from anywhere in code and being able to call each client with specific message or none 

### Actual behavior
Unable to instanciate a MyHub, just a HubContext<MyHub> (using: https://learn.microsoft.com/en-us/aspnet/core/signalr/hubcontext?view=aspnetcore-7.0). Where HubContext has lots of restriction and still can't see functions of MyHub ???? 
Also, how to send specific message to specific client?

### Steps to reproduce
None

**Comment by EricOuellet2** [comment]
Thanks a lot for your sample! but... 
Sorry, I wasn't clear enough. I'm talking about the server side. After the connection is establish.
My Hub is already working based on the sample and everything works.
There is 2 problems: 
1- how to get a valid MyHub in hand from anywhere in code
2- send specific message to client according to specific configuration

**Comment by CZEMacLeod** [comment]
@EricOuellet2 
I think you need to use
```cs
IHubContext hubContext = GlobalHost.ConnectionManager.GetHubContext<NotificationHub>();
await hubContext.Clients.All.SendAsync("SomeNotification", message);
```
The first line will grab the hub for you from anywhere. GlobalHost here is `Microsoft.AspNet.SignalR.GlobalHost` and is a singleton.
You can then use `hubContext.Clients` with `.All`, `.Client`, or `.Group` to get the client or clients you want to send the message to.

**Comment by MacrayBlackhand** [comment]
What is your client-side environment? Is this a web app or are you using C# on the client-side?

**Comment by EricOuellet2** [comment]
I very recently created a WebService ASP.Net Core project. That's what I'm using on the server side where the problem reside.

**Comment by EricOuellet2** [comment]
@CZEMacLeod, Thank you very much for your answer. There is few things I don't understand. I juste created my project few weeks ago and it seems to be the new way to go. By defaut it insert 3 Packages references which all start with "Microsoft.AspNetCore" : Microsoft.AspNetCore.OpenApi, Microsoft.AspNetCore.SignalR.Common, Microsoft.AspNetCore.Protocols.Json. "Globalhost" was not found and require to add Microsoft.AspNet.SignalR.Core which seems to be part of another previous release of AspNet. It sound weird that 2 namespaces are so differents and that GlobalHost is not there by default. I would like to know what the hell exists between these 2 differents namespaces. It sounds like Microsoft has not completed the documentation and possibly the API of a remake of SignalR???

**Comment by MacrayBlackhand** [comment]
Okay, sorry, my example assumed a web app with Javascript on the client side.

**Comment by EricOuellet2** [comment]
@MacrayBlackhand Thank you very much for having try to help! 👍

**Comment by CZEMacLeod** [comment]
@EricOuellet2 from the readme for this repo:
> This repository hosts code and project management for ASP.NET SignalR, for use in .NET Framework applications using System.Web or Katana. If you are looking for information on ASP.NET Core SignalR, see the https://github.com/aspnet/AspNetCore/tree/main/src/SignalR repository.

It looks like you are using aspnetcore and the new version of SignalR. So I would advise going to that repo to find your answers.

**Comment by CZEMacLeod** [comment]
@EricOuellet2 here is the page that describes what you wanted.
https://learn.microsoft.com/en-us/aspnet/core/signalr/hubcontext?view=aspnetcore-7.0

**Comment by EricOuellet2** [comment]
I was at the wrong place (there is another place for the new ASP.Net). Thanks!

**Comment by EricOuellet2** [comment]
@CZEMacLeod , Thanks, I read it 10x times actually... But I should be missing something. Thanks a lot for your help. Honestly, there is something I find terribly horrifying... How could it be so complex to get a Hub??? And how could it be so comples to send message to specific client??? Why can't we just iterate client? Why not calling that a connection. It seems that there is conenction and client, what is the differences? It is not your fault at all, but it appears totally ridiculous to me. That's drive me crazy, it should be simple, very simple but it appears to me as the complete opposite.
