### ISSUE TITLE
Unable to send msg to Signalr clients after restarting signalr service

### ISSUE THREAD

**Issue by sharath1984** [SignalR/SignalR#4682]
Issues related to the Asp.NET Core version of SignalR should be filed in the AspNetCore repo: https://github.com/aspnet/AspNetCore/issues/new/choose
 We have created a signalr server as shown below , we are saving the connectionid and group name in db, when the signlar server restarts we are fetching the connectionid and groupname and adding it to the signalr service but when we send msg to the clients , the clients are not receiving the msg, could you pls take a look

### Expected  behavior
Signalr client should be able to receive the msg
### Actual behavior
Signalr client  is not able to receive the msg
### Steps to reproduce
1)Run the signalr service this developed using aspnet core .
2)Connect a javascript client and it will be able to connect and receive msg.
3)Save the connectionid and groupname in db
3)restart the signalr service, fetch the connectionid from db and try to pass it to signalr code, the clients will not receive the msg and 
another thing we observerd is clients connectionid will be changed once it reconnects to signalr service.

Signalr server code
 public async Task JoinGroup(string groupName, string token)
        {
            try
            {
                if (string.IsNullOrEmpty(groupName))
                {
                    _logger?.LogError("Group name cannot be null ");
                    return;
                }
                _logger?.LogInformation("Inside JoinGroup, groupname {0}  ", groupName);
                //If we hardcode the connectionid to old value and send msg it is not working,
                await Groups.AddToGroupAsync(Context.ConnectionId, groupName);
                await Clients.Group(groupName).SendAsync("ReceiveMessage", $"{Context.ConnectionId} joined the group {groupName}");

                await Clients.Client(Context.ConnectionId).SendAsync("History", groupName);
                Users user = new Users();

                var userDetails =  GetUserInfo(token).GetAwaiter().GetResult(); 
                var obj =   JsonConvert.DeserializeObject<SignalrUserInfo>(userDetails);
                user.UserName = obj.Name;
                user.Connected = true;
                user.GroupName = groupName;
                user.ConnectionId = Context.ConnectionId;
                
                _users.SaveLoggedInUser(user);
            }

Client code 
var connection = new signalR.HubConnectionBuilder().withUrl("http://localhost:50443/SignalrManager", {
   
    transport: signalR.HttpTransportType.WebSockets,
}).configureLogging(signalR.LogLevel.Information).withAutomaticReconnect().build();

async function start() {
    try {
        console.log("SignalR going to be Connected.");
        await connection.start();
        console.log("SignalR Connected.");
    } catch (err) {
        console.log(err);
        setTimeout(start, 5000);
    }
};

connection.onclose(async () => {
    await start();
});

// Start the connection.
start();

**Comment by BrennanConroy** [comment]
1. The ConnectionId changes whenever a client (re)connects so your approach of storing and using the connection id in a database won't work when the client leaves and comes back. It's better to use Users or Groups.
2. This is the wrong repo for ASP.NET Core issues, those go in github.com/dotnet/aspnetcore
3. General questions like this are better suited for stackoverflow: https://stackoverflow.com/questions/tagged/signalr
