### ISSUE TITLE
Fallback on network blocking

### ISSUE THREAD

**Issue by tas885** [SignalR/SignalR#4686]
Curious.. Will this library automatically and seamlessly fall back to Long Polling and/or Server-Sent Events when WebSockets are not supported by the server or blocked by a firewall/proxy? It's not clear from the docs https://learn.microsoft.com/en-us/aspnet/core/signalr/introduction?view=aspnetcore-7.0#transports, so I just wanted to make sure. TY!

**Comment by BrennanConroy** [comment]
In most cases yes. In some rare situations, like if a proxy accepts the websocket connection and then immediately closes it, then fallback will not occur. Although, I'm not aware of any situations like that with common proxies.
