### ISSUE TITLE
Intermittent failure to receive messages during e2e testing in github workflow

### ISSUE THREAD

**Issue by aa89227** [SignalR/SignalR#4692]
During the execution of end-to-end (e2e) testing in github workflow, there are instances where messages are not received.

The usual speed for passing the tests is around 100ms, while failed tests throw exceptions due to timeouts. The first test, which is the BroadcastTestAsync, takes longer because some things are being initialized (AssemblyInitialize), which takes some time.

### Expected  behavior
All messages should be received consistently during e2e testing.

### Actual behavior
Messages are intermittently not received during e2e testing, leading to unexpected gaps in communication.

### Steps to reproduce
I'm not sure in what situation this issue arises, but you can refer to https://github.com/aa89227/SignalR.E2ETesting/actions/runs/6525044707/job/17717418167.  
I ran the job 10 times, and the last attempt failed.
I couldn't reproduce this issue in my own environment, even when I opened 1000 clients.

**Comment by BrennanConroy** [comment]
This is the wrong repo for aspnetcore signalr issues.

You should enable timestamps in your logs and add more logging to help narrow down the issue.

**Comment by aa89227** [comment]
I apologize for taking up your time, I created another repo, this one will be more focused on the issue I want to present.
repo: https://github.com/aa89227/SignalR-E2ETestingExample

[This Job only prints out the client side logs, I think the server side logs will make it impossible to reproduce the problem (see the workflow of the first two commits for more details)](https://github.com/aa89227/SignalR-E2ETestingExample/actions/runs/6571809322)

Still the same problem, when testing in Github Workflow sometimes the client can't receive the message.

If this issue is still not part of aspnetcore signalr, please close this issue again.
