### ISSUE TITLE
Question: Can we use SignalR client for binance or other socket endpoints for stocks information?

### ISSUE THREAD

**Issue by Sen-Gupta** [SignalR/SignalR#4700]
Hello,

I'm curious to know if SignalR client can support socket endpoints such as binance or other stock exchange websocket endpoints?
Or is tied up with .net server implementation?

Though, I believe later should be the answer. ;-)

Regards
Sen

**Comment by BrennanConroy** [comment]
SignalR is a protocol, if those endpoints support the SignalR protocol then it can work. But I highly doubt they do.

The .NET server implementation is just that, an implementation of the SignalR protocol. Nothing restricts SignalR to .NET.
