### ISSUE TITLE
Failed to invoke 'xxx' due to an error on the server.

### ISSUE THREAD

**Issue by SaleCar** [SignalR/SignalR#4701]
Hello,

I have this hub method:

```
public async Task<IResult> GetDocument(RequestArgs args) {
    var document = await dataService.GetDocument(args);
    return Results.Ok(document);
}
```

Argument is simple object with filters...

```
public class RequestArgs {
    public int Id { get; set; }
    ...
}
```

And when client send Id **as string**, for example:

```
{
    "arguments":[ { "id": "10" } ],
    "invocationId":"0",
    "target":"GetDocument",
    "type":1
}
```

There is error: **Failed to invoke 'GetDocument' due to an error on the server**.

How to catch and handle this binding exception when from client is send wrong var type (in this case string instead int) ?

**Comment by BrennanConroy** [comment]
Wrong repository. Also, you can't catch the binding error.
