### ISSUE TITLE
System.InvalidOperationException: InvokeAsync only works with Single clients.

### ISSUE THREAD

**Issue by Y4er** [SignalR/SignalR#4716]
after read this https://learn.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-8.0#client-results

I try to get the result from the javascript client, I get the following error:

fail: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8]
Failed to invoke hub method 'GetMessage'.
System.InvalidOperationException: InvokeAsync only works with Single clients.

i try to change my hub option with 

```
builder.Services.AddSignalR((options) =>
{
    options.MaximumParallelInvocationsPerClient = 10;
});
```

doesn't work.

Does the JavaScript client not support getting the returned results?

**Comment by BrennanConroy** [comment]
Like the error says, you can only use `InvokeAsync` when sending to a single client. It's likely you're doing something like `Context.Clients.All.InvokeAsync` or `Context.Clients.User("id").InvokeAsync` or similar.
