### ISSUE TITLE
Hub called but never come back

### ISSUE THREAD

**Issue by Mafyou** [SignalR/SignalR#4720]
Hi,

### Expected  behavior
Send message to all connected on the hub.

### Actual behavior
It comes to the Hub but never come back or send to different client.
I tried with a specific user but same for "All".

### Steps to reproduce
- Add JWT
- Add.Inject SignalR
- Add the hub: 
```c#
app.MapHub<KITHub>(hubName);`
```
```c#
[Authorize]
public class KITHub(IHubContext<KITHub> hubContext) : Hub<IKITHub>, IKITHub
{
    [HubMethodName("SendMessage")]
    public async Task SendMessage(ChatSettings settings, SendMessage sm)
    {
        Console.WriteLine("ReceivingMessage de " + settings.Me.Pseudo + " to other " + settings.Other.Pseudo);
        await hubContext.Clients.User(settings.Other.Id.ToString()).SendAsync(ChatHubStatus.ReceivingMessage, new ReceivingMessage(sm.Message));
        Console.WriteLine("Sendessage ACK " + settings.Me.Pseudo);
        await hubContext.Clients.User(settings.Me.Id.ToString()).SendAsync(ChatHubStatus.ReceivingMessage, new ReceivingMessage(sm.Message));
    }
}`
```
- Then, the client:
```c#
hub.On<ReceivingMessage>(ChatHubStatus.ReceivingMessage, (rm) =>
{
    Console.WriteLine($"{chatSettings.Me.Pseudo} : {rm.Message}");
});
```
- And call like this:
```c#
await hub.SendAsync(ChatHubStatus.SendMessage, chatSettings, new SendMessage(line));
```

Here the repo to show that => https://github.com/Mafyou/ChatSignalR

**Comment by BrennanConroy** [comment]
Please simplify your repro app if you believe there is an issue. Since you mention "All" doesn't work either, you should be able to remove auth as well to narrow down any potential problems.

**Comment by Mafyou** [comment]
Auth is mandatory to send a message to a specific user with SignalR.
I tried to make the simplest one.
Just see the SendMessage hub method: it send to both clients side but it doesn't work. Client receive nothing. Why?

**Comment by BrennanConroy** [comment]
Remove the `while (true)` and `Console.ReadLine()`, you're probably blocking the message processing loop.

**Comment by Mafyou** [comment]
So true. Thank you !
