### ISSUE TITLE
how to decode and encode the blazorpack/messagepacks using any network traffic tool or Dev tools

### ISSUE THREAD

**Issue by Pradeepcheedalla** [SignalR/SignalR#4721]
Hi All,

Can anyone help me on how to decode and encode the blazorpack/messagepack using any network traffic tool (like Fiddler/ Wireshark/ Burp or etc..)

Also, Please help me on how to build the Blazor/SignalR requests and how to validate the real response using JMeter Tool.

Thanks
Pradeep

**Comment by BrennanConroy** [comment]
This is a question for a forum like stackoverflow.
