### ISSUE TITLE
Version 2.4.3 released to npm has bug in off function

### ISSUE THREAD

**Issue by Madajevas** [SignalR/SignalR#4729]
In repository correct callback index is used when removing handler:
https://github.com/SignalR/SignalR/blob/336c877743924c990aeefc75930d63e609e624ac/src/Microsoft.AspNet.SignalR.JS/jquery.signalR.hubs.js#L190-L205

In NPM, however, `i` from loop above is used, which at  the time of removal points at last element of handlers array:

![image](https://github.com/user-attachments/assets/196982ab-f1ef-4e9a-916b-2194dd126204)

https://www.npmjs.com/package/signalr?activeTab=code

### Expected  behavior
Calling `off` on hub proxy removes correct handler

### Actual behavior
Call `off` removes nothing. Handler is still being called

### Steps to reproduce
* add listener on proxy
* attempt removal with `off`
* publish event to that hub
* observe handler being executed

**Comment by BrennanConroy** [comment]
It was fixed in https://github.com/SignalR/SignalR/pull/4659 which will be in 2.4.4

**Comment by Madajevas** [comment]
Is there a date planned for release?
