### ISSUE TITLE
Does Microsoft.AspNetCore.SignalR.Client support AOT?

### ISSUE THREAD

**Issue by JusterZhu** [SignalR/SignalR#4730]
### Expected  behavior
Can Microsoft.AspNetCore.SignalR.Client be used for AOT publishing in a console application or WPF

### Actual behavior
When I publish the console application with AOT, it cannot receive server push messages. However, if I cancel the AOT publishing, it can send and receive messages normally. This issue occurs in .NET 9 and the latest version of Microsoft.AspNetCore.SignalR.Client 9.0.0.

### Steps to reproduce
The code to reproduce the issue is very simple. It's just a standard example of a SignalR server and client. Once the client is compiled with AOT, it can no longer receive messages.

**Comment by davidfowl** [comment]
This is the wrong place to file ASP.NET Core SignalR issues. https://github.com/dotnet/aspnetcore

**Comment by JusterZhu** [comment]
> This is the wrong place to file ASP.NET Core SignalR issues. Use https://github.com/dotnet/aspnetcore

ok
