### ISSUE TITLE
Error in reconnect

### ISSUE THREAD

**Issue by juloliveira** [SignalR/SignalR#487]
Hello,

My application:

MVC 3
IIS Express (and IIS 7.5)

My application work correct but when restart IIS Express (or IIS 7.5) the SignalR dont reconnect. (I want simulate reconnect feature)

My hub:

[HubName("apuracaoHub")]
    public class ApuracaoHub : Hub, IDisconnect, IConnected
    {
        public void Atualizar()  { /// do stuff... }

```
    public Task Disconnect()
    {
        return Clients.leave(Context.ConnectionId, DateTime.Now.ToString());
    }

    public Task Connect()
    {
        return Clients.joined(Context.ConnectionId, DateTime.Now.ToString());
    }

    public Task Reconnect(IEnumerable<string> groups)
    {
        return Clients.rejoined(Context.ConnectionId, DateTime.Now.ToString());
    }

}
```

In Chrome, console report this:

The server is unreachable...
EventSource's response has a MIME type ("application/x-javascript") that is not "text/event-stream". Aborting the connection.

In javascript to trace statusChanges I implement this:

```
  $.connection.hub.stateChanged(function (change) {
            if (change.newState === $.signalR.connectionState.reconnecting) {
                timeout = setTimeout(function () { console.log('The server is unreachable...'); }, interval);
            }
            else if (timeout && change.newState === $.signalR.connectionState.connected) {
                console.log('The server is online');
                clearTimeout(timeout);
                timeout = null;
            }
        });
```

My routes:

....MapHubs("~/signalr/hubs");

In Firefox, console report outher message:

Firefox failed to connect to the server http://localhost:49190/signalr/hubs?transport=serverSentEvents&connectionId=82ea36cf-a7ac-4dd3-b7cc-dde343c34b55&connectionData=%5B%7B%22name%22%3A%22apuracaoHub%22%7D%5D&messageId=9.

This error occour only when I try simulate one reconnection.

More info:

In Firefox, console report error in line 717 of the jquery.signalR-0.5.1.js

connection.eventSource = new window.EventSource(url);

Anybody can help me?

Thank´s

**Comment by ARCSIndia** [comment]
I am using the javascript Version  jquery.signalR-1.0.0-rc2 and still facing the issue
