### ISSUE TITLE
Support CamelCasePropertyNamesContractResolver when serialize

### ISSUE THREAD

**Issue by scott-xu** [SignalR/SignalR#500]
For issue 138:
https://github.com/SignalR/SignalR/issues/138

Can we use JsonProperty in the build-in objects to serialize to {"Url":"/signalr","ClientId":"194d19cf-219b-405e-9ed2-d5309d098022"} so that we can choose using CamelCasePropertyNamesContractResolver or not.

**Comment by jnm2** [comment]
+1 for native support.

**Comment by pisqko** [comment]
+1 for native support

**Comment by jpierson** [comment]
When i try going the same route of creating a manual resolver it's not working me with latest version of SignalR and JSON.NET. The type JsonNetSerializer cannot be found amongst other things, have these types moved namespaces, assemblies, or been renamed?

**Comment by ryanwischkaemper** [comment]
Using SignalR v2.2.0 and Autofac 3.5.2, if I use the code snippets above and register a binding with Autofac like this 
```csharp
var settings = new JsonSerializerSettings {ContractResolver = new SignalRContractResolver()};
var serializer = JsonSerializer.Create(settings);
builder.Register(c => serializer).As<JsonSerializer>();
```
then the camel case resolver is being used.

**Comment by axsauze** [comment]
+1 for native support

**Comment by Worthaboutapig** [comment]
+1 for native support
