### ISSUE TITLE
signalr/hubs js file not found when deploy to production server

### ISSUE THREAD

**Issue by The-Vu-SHG** [SignalR/SignalR#53]
I have a test application with the quick code provided from the documenation using Hubs.  I've managed to run this sucessfully on my local machine (both in Developmental Environment and IIS Hosting).  However, when I published this onto a production server, the page cannot load the signalr/hubs JS file.  I even tried to browse to it manually and received a 404 error.  I should say that I got this working on one server running IIS7 and failed to get it to work on a different one running IIS6, so I'm not sure if there's some settings in IIS that's preventing the signalr/hubs js file from being generated.  Looks like someone else besides me also running into this problem too (although he cannot get it to work on IIS7 or IIS6)

http://stackoverflow.com/questions/8053229/signalr-works-in-visual-studio-but-gives-a-404-error-when-deployed-to-iis

**Comment by hamadKhan21** [comment]
Hi There, i am facing the same issue. I have deployed my project on server and it gives me this error 404 not found signalr/hubs js file,
