### ISSUE TITLE
Modernizr 2.5.3.min causes forever frame to fail after 10mins in IE9

### ISSUE THREAD

**Issue by timbjames** [SignalR/SignalR#566]
I discovered, after a long time of testing, that the cause of foreverFrame to fail after 10mins in IE9, was being caused by version 2.5.3.min of Modernizr.

REPRO 

Build a basic console app which connects to the hub.

``` csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SignalR;
using SignalR.Client;
using SignalR.Client.Hubs;
using System.IO;

namespace ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {            
            HubConnection hub = new HubConnection("http://snlr.azurewebsites.net");
            IHubProxy proxy = hub.CreateProxy("MyHub");
            hub.Start().Wait();       
            while (true)
            {
                /* lol that should keep it running all night! */
                proxy.Invoke("sendData");
                Console.WriteLine(DateTime.Now.ToString());
                System.Threading.Thread.Sleep(5000);
            }              
            Console.ReadLine();                                    
        }
    }
}
```

Open IE9 and go to the page http://snlr.azurewebsites.net/home/withmodernizer
After 10mins it will stop working. 
Close IE9, then open and go to the page http://snlr.azurewebsites.net/home/without
This is the same page but without the modernizer file. It will continue working.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
