### ISSUE TITLE
3 seconds delay on start() (ASP.NET MVC 3)

### ISSUE THREAD

**Issue by PlucM** [SignalR/SignalR#601]
Hangs for a little over 3 seconds when calling  `$.connection.hub.start();`

Tested on:
- Windows 2003 w/ IIS 6
- Windows 7 w/ ASP.NET Development Server
- Windows 7 w/ IIS 7

Steps to reproduce:
1. New MVC 3 project
2. Add SignalR package with NuGet
3. Create a empty Hub (Called mine MyHub)
4. Add standard SignalR connection to index (Exemple below)

``` html
<script src="@Url.Content("~/Scripts/jquery.signalR-0.5.2.js")" type="text/javascript"></script>
<script type="text/javascript" src="@Url.Content("~/signalr/hubs")"></script>
<script type="text/javascript">
    var DataListenerHub = $.connection.myHub;
    $.connection.hub.start();
</script>
```

**Comment by aghwotu** [comment]
#601
@davidfowl  Hello David. I'm quite new to SignalR and C# in general so my question might seem odd - How do I check if I'm behind a proxy ?(I'm in the process of debugging my code using your comments) and I'm experiencing a delay of 15 seconds in my code. Can you suggest what I can do to speed up this process? Thanks. 

`<script src="Scripts/jquery-1.6.4.min.js"></script>
    <script src="Scripts/jquery.signalR-2.2.1.min.js"></script>
    <script src="/signalR/hubs"></script>
    <script type="text/javascript">     

        $(function () {

            //Proxy created on the fly
            var job = $.connection.myHub;

            //Declare a function on the job hub so that the server can invoke it
            job.client.displayStatus = function () {
                getStatus();
            };

            //Start the connection
            $.connection.hub.start();
            getStatus();

        });

        function getStatus() {
            alert("hello");
            var $name = $('#name');
            $.ajax({
                url: "demo2.aspx/GetStatus",
                contentType: "application/json; charset = utf-8",
                dataType: "json",
                type: "POST",
                success: function (data) {
                    debugger;
                    alert("hey");
                    alert(data.d.length);
                    var element = document.getElementById("name");
                    element.innerText = data.d;
                    $name = data.d;

                    //$.connection.hub.stop();  Uncommented this cause it caused a longer dalay. Not sure where to put it
                }
            });
        }
    </script>`
`<form id="form1" runat="server">
    <div>
        <label id="name" ></label>
        <asp:Label ID="price" runat="server" Text="Hello World"></asp:Label>
    </div>
    </form>`
