### ISSUE TITLE
Remove all clients from a group

### ISSUE THREAD

**Issue by kraghavk** [SignalR/SignalR#66]
How do I remove all the client connections from a group? I could not find any API to do that! There's only AddToGroup and RemoveFromGroup methods in the Hub.

Thanks,
Raghu

**Comment by SoundLogic** [comment]
in the meantime you can use a quick and dirty approach like  this: 

    public static class SignalRConnectionToGroupsMap
    {
        private static readonly ConcurrentDictionary<string, List<string>>  Map = new ConcurrentDictionary<string, List<string>>();

        public static bool TryAddGroup(string connectionId, string groupName)
        {
            List<string> groups;

            if (!Map.TryGetValue(connectionId, out groups))
            {
                return Map.TryAdd(connectionId, new List<string>() {groupName});
            }

            if (!groups.Contains(groupName))
            {
                groups.Add(groupName);
            }

            return true;
        }

        public static bool TryRemoveConnection(string connectionId, out List<string> result)
        {
            return Map.TryRemove(connectionId, out result);
        }
    }

**Comment by Unders0n** [comment]
this post is 2015, any updates on this?

**Comment by DinoSourcesRex** [comment]
@Unders0n bit of a late response to this but if you are using .netcore [RemoveFromGroupAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.signalr.igroupmanager.removefromgroupasync?view=aspnetcore-3.1#Microsoft_AspNetCore_SignalR_IGroupManager_RemoveFromGroupAsync_System_String_System_String_System_Threading_CancellationToken_) on the `Groups` property on your hub.

**Comment by D4n1aLLL** [comment]
Was this implemeted?

**Comment by kierenj** [comment]
@DamianEdwards Where's that new repo please?

**Comment by DamianEdwards** [comment]
https://github.com/dotnet/aspnetcore

**Comment by kierenj** [comment]
Thanks @DamianEdwards . Doesn't look like this made it there, unless I just missed it. Shall I raise it?
