### ISSUE TITLE
Signalr and rewrite rules falls back to long polling for Chrome and FF

### ISSUE THREAD

**Issue by prinrj** [SignalR/SignalR#678]
From server https://a.local, I'm connecting to a SignalR connection:

```
/gateway/signalr/status (so https://a.local/gateway/signalr/status)
```

That then hits a URL rewrite rule which handles cross domain calls.  The rule translate the request into:

```
https://b.local/signalr/status 
```

This works fine and message are received.  However, in Chrome (and FF) it tries to connect with transport serverSentEvents, times out and then falls back to longPolling.

The transport serverSentEvents does connect when using a test page

```
https://b.local/signalr/test.html
```

so I know there's not a problem with this transport, just some oddness with rewrite rules.

Is there anything special I need to do to get this working?  Do I need to configure IIS in some way to get serverSentEvents working with rewrite rules?

Thanks for any help.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
