### ISSUE TITLE
Self host server can't resolve connection paths for requests with URLs different from the servers base URL.

### ISSUE THREAD

**Issue by xAragornx** [SignalR/SignalR#684]
Lets say a self host server is created for url "http://localhost:8080". The self host server seems to only accept connections from SignalR clients that call on the same base url of "http://localhost:8080". Clients that try to connect on "http://127.0.0.1:8080", "http://hostname:8080", or on a valid ip address for the server all fail. There many different ways for a SignalR client to specify a Url for to connect to a SignalR server and they are technically valid networking wise so the SignalR server should be able to handle those requests but it currently fails.

I traced the issue down to the "ResolvePath" method in "Server.cs". That method explicitly does a Regex check to make sure that the incoming request's URL starts with the same baseURL as the server. So any call that does not start with the same base URL fail even though they are technically reaching the right server and the request should be accepted.

I would suggest that the baseUrl check should be removed and that the method should simply return the connectionPath parsed from the request Url.

**Comment by amangautam15** [comment]
I created a server having signalR hub and a client. both are windows applications.
I want to connect my signalR hub to my organization server's IP address. But when i start the connection its throwing the exception 
![signalr exception](https://cloud.githubusercontent.com/assets/13640135/9058242/4816b8a0-3abd-11e5-9f62-5a04803f0905.jpg)

please help me urgently. How to connect the signalR hub on an internet enabled system ? 
Thanks!
