### ISSUE TITLE
Protocol error: Unknown transport.

### ISSUE THREAD

**Issue by shawnmclean** [SignalR/SignalR#757]
I installed SignalR in an asp.net mvc 4 application through nuget. I got v0.5.3. If I browse to the url: http://localhost:1840/signalr/hubs/ (where I should get the hubs javascript file). It throws the following error:

Protocol error: Unknown transport.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

```
[InvalidOperationException: Protocol error: Unknown transport.]
  SignalR.PersistentConnection.ProcessRequestAsync(HostContext context) +670
  SignalR.Hubs.HubDispatcher.ProcessRequestAsync(HostContext context) +120
  SignalR.Hosting.AspNet.AspNetHandler.ProcessRequestAsync(HttpContextBase context) +463
  SignalR.Hosting.AspNet.HttpTaskAsyncHandler.System.Web.IHttpAsyncHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object extraData) +68
  System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +301
  System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155
```

My javascript client does not work without this file, my .net clients tell me there is a 404 error. Any idea what is happening?

I'm using Visual studio 2012, debugs in IIS express.

**Comment by sanghreaajit** [comment]
Hi Xiaohongt 

Did you found the solution i facing the same issue
http://localhost:1840/signalr/hubs this is redirecting to login.aspx
