### ISSUE TITLE
Should throw an InvalidOperationException when trying to access Hub members from invalid time

### ISSUE THREAD

**Issue by DamianEdwards** [SignalR/SignalR#767]
E.g. trying to access Caller from the body of the Disconnect method.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
