### ISSUE TITLE
Memory continuosly increasing for Browsers IE8 and Firefox

### ISSUE THREAD

**Issue by rehmanm** [SignalR/SignalR#809]
The memory is continuously increasing as my application is getting data after every 5 seconds.

I tried to clear the iframe, but it won't help.

code for clearing iframe

```
            $("iframe").contents().find("body").html("");
            $("iframe").contents().find("head").html("");
```

**Comment by hp17688** [comment]
Hi All, Any updates on this yet? I am forcing Longpolling when IE is used. Is it good to force for longpolling instead of ForeverFrame?

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
