### ISSUE TITLE
console .net client connection to hub - Context.User.Identity = no value

### ISSUE THREAD

**Issue by gregsara00** [SignalR/SignalR#815]
Please help as I'm probably doing something wrong, however I can't seem to get a User.Identity value when connecting via a console .net client to a hub.  I get everything working with my standard asp.net mvc views as expected.  What do I have to do special or different when connecting via a console application?

Here is my console app connection code.  I'm attempting to pass in an ICredentials object.  Does proper setting of the ICredentials object persist in the HUB?  Is that the proper way to do it or should it persist somehow via mvc authentication like my web clients do?

```
HubConnection connection = new HubConnection("https://somedomain.com/");
IHubProxy myHub = connection.CreateProxy("MyHub");

using (var httpClient = new HttpClient())
{
     string user = ConfigurationManager.AppSettings["username"];
     string pass = ConfigurationManager.AppSettings["password"];

     var response = HttpClient.PostAsJsonAsync("https://somedomain.com/dNETLogOn/",
                                    new { username = user, password = pass }, CancellationToken.None).Result;
      response.EnsureSuccessStatusCode();

      bool success = response.Content.ReadAsAsync<bool>().Result;
      if (success)
      {
      ICredentials cred = new NetworkCredential(user, pass);
      connection.Credentials = cred;
      connection.Start().ContinueWith(task =>
      {
            if (task.IsFaulted)
            {
                 // Bad connection
            }
            else
            {
                  myHub.Invoke("Send", System.Environment.MachineName + " connection established.");
            }
      }).Wait();
```

My HUB is just the following: 

```
public class MyHub : Hub
{
    public void Send(string message)
    {
        Clients.addMessage(Context.User.Identity + message);
    }
}
```

Does passing in the ICredentials object fill in the Context.User on the Hub side of things?
Am I not properly setting up an IPrincipal in my console application?

**Comment by stefanzvonar** [comment]
Any chance you could please post the extra code that inserted the CookieContainer?
