### ISSUE TITLE
Cross-Platform C++ API's

### ISSUE THREAD

**Issue by CreepyGnome** [SignalR/SignalR#844]
It would be great if there where native API's available for SingalR especially Windows and Mac.  We are looking into using it and on the server side C# is great, and right now the only way we can on our endpoints is via Mono Embedded which is doable but not as clean.

**Comment by moozzyk** [comment]
Cross platform SignalR C++ client can be found here: https://github.com/aspnet/SignalR-Client-Cpp. It currently runs on Windows and Linux.
