### ISSUE TITLE
Limited unique connections (opened tabs) IIS8, Windows8

### ISSUE THREAD

**Issue by Lionberg** [SignalR/SignalR#849]
It is omposible to use SignalR, when several tabs opened  with unique ids assigned to each tab (see. http://stackoverflow.com/questions/10426163/when-signalr-made-8-10-connections-at-a-time-live-chat-doesnt-work).

But. there is a workaround I described in this stackoverflow issue. The idea is to overwrite connectionid  in order, that every opened tab would have the same connection id:  thus, logicaly, in my particular case, there is no reason to have unique ids for each tab, 'cos each tab is opened by one MyApplicationUserId.

Anyway, you noticed in stackoverflow (see http://stackoverflow.com/questions/11522090/signalr-how-is-a-duplicate-connection-id-handled ), that connectionid must be unique. And they say, that IConnectionIdGenerator  will be removed in an upcomming release.

So, this is a kind of blind alley. I must use unique ids, but I cannot use SignalR with several browser tabs opened.

Thank you.
Dmitry.

**Comment by slimjack** [comment]
Want to share my [solution](https://github.com/slimjack/IWC-SignalR) based on localStorage

**Comment by gopaldahal** [comment]
What I am not getting here is. let say its the limitation of the browser. But Why is the user running on different browser on different machine not able to browse the URL. They are able to browse only when the spining(hanging) Url on mine is closed. He is beiing able to browse the URL immediately after the spinning tab is closed.
