### ISSUE TITLE
If the Task returned by the Subscription.WorkAsync call in MessaggeBroker.PumpImpl is faulted, the Subscription might be left in a permanent non-idle state.

### ISSUE THREAD

**Issue by halter73** [SignalR/SignalR#921]
If WorkAsync throws for a reason other than the subscribed client disconnecting, it may leave the Subscription in a non-idle state causing it never to be queued again even though no worker is processing messages for the Subscription. If this happens, the subscribed client will not receive any more messages.

Even though Subscription.UnsetQueued will always be called even if the Task returned Subscription.WorkAsync is faulted, UnsetQueued no ops if the Subscription _state is > State.Working.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
