### ISSUE TITLE
Failure to invoke client side method doesn't propogate to the caller

### ISSUE THREAD

**Issue by raybooysen** [SignalR/SignalR#951]
Consider this example on the server side:
Foo x = //initialise to some value;
Boo y = // initialise;

Clients.Caller.spot(x);
Clients.Caller.spot(y);

Consider the code on the client side.  Using the On<Foo> call, the client will first receive x and after that the client will try deserialise y and provide the handler a new instance of Foo. 

This should probably propagate an error instead when y is received on the client.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!
