### ISSUE TITLE
SignalR: Connection must be started before data can be sent. Call .start() before .send()";

### ISSUE THREAD

**Issue by MominI** [SignalR/SignalR#974]
```
 $(function () {
            var connection = $.connection('echo');

            connection.received(function (data) {

                $('#messages').append('<li>' + data + '</li>');
            }
        );


            connection.start(

                $("#broadcast").click(function () 
                {
                    connection.send($('#msg').val());
                }
                ));

        });
```

throws me a error 'SignalR: Connection must be started before data can be sent. Call .start() before .send()";' while trying to use example in hosted environment , works well in my localhost

**Comment by agshealth-sureshp** [comment]
I Configured my application in http it's working fine ,but not working in https ? 
Below error occured:
Connection must be started before data can be sent. Call .start() before .send()
what is the problem?
Thanks
Suresh.P

**Comment by moozzyk** [comment]
Probably the connection did not start due to some network issues/configuration. btw. Stackoverflow is **the** place to ask this kind of questions.

**Comment by agshealth-sureshp** [comment]
k moozzyk thanks gi..

**Comment by abhishekbhalani** [comment]
Hi,
@davidfowl 
I have few questions.

1) How to reconnect signalr hub if connection lost while chatting to end user ? 
2) Will it automatically connect if timeout? How to intimate the connected user after reconnect and available to chat?

can you update me in this cases & solution ?

**Comment by moozzyk** [comment]
@abhishekbhalani http://www.asp.net/signalr/overview/guide-to-the-api/handling-connection-lifetime-events

**Comment by abhishekbhalani** [comment]
Thank @moozzyk I also checked it before..
l will let you know if any technical issue face by our team..
